Repository Yoast/wordpress-seo, pull requests merged in 2018-07, with the labels that each got.

#10202 Disable `wp-emoji` in combination with the snippet editor
  admin/class-config.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
Labels: needs-code-review ★

#10164 Make sure $term->taxonomy is set before using it, fixes #10143
  inc/options/class-wpseo-taxonomy-meta.php
Labels: community-patch

#10122 Fix error when $terms[0] does not exist in open-graph
  frontend/class-opengraph.php
Labels: code-review, community-patch

#9863 Update class-rewrite.php
  inc/class-rewrite.php
Labels: code-review, community-patch

#10237 Set the correct milestone for the deprication warnings of 10072
  admin/taxonomy/class-taxonomy.php
  frontend/class-frontend.php
Labels: acceptance

#10250 Change direct call of the analyzer to refresh
  js/src/analysis/PostDataCollector.js
Labels: needs-code-review ★

#10212 [FIX] Fix display of post type archive settings
  admin/views/tabs/metas/post-types.php
Labels: community-patch

#10257 Remove style overwrite
  css/src/metabox.scss
  js/src/components/SnippetPreviewSection.js
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
Labels: acceptance

#10260 Upgrade Jest to latest version
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  package.json
  yarn.lock
Labels: acceptance

#10270 Sidebar banner rebuild
  admin/banner/class-admin-banner-renderer.php
  admin/banner/class-admin-banner-sidebar-renderer.php
  admin/banner/class-admin-banner-sidebar.php
  admin/banner/class-admin-banner-spot-renderer.php
  admin/banner/class-admin-banner-spot.php
  admin/banner/class-admin-banner.php
  admin/class-yoast-form.php
  admin/views/sidebar.php
  css/dist/yst_plugin_tools-78-RC3-rtl.css
  css/dist/yst_plugin_tools-78-RC3-rtl.min.css
  css/dist/yst_plugin_tools-78-RC3.css
  css/dist/yst_plugin_tools-78-RC3.min.css
  css/src/yst_plugin_tools.scss
  images/BasicSEO.svg
  images/Local_SEO_Icon.svg
  images/News_SEO_Icon.svg
  images/SEO_for_beginners.svg
  images/Video_SEO_Icon.svg
  images/Woo_SEO_Icon.svg
  images/banner/basic-seo-training.png
  images/banner/local-seo-for-woocommerce.png
  images/banner/local-seo.png
  images/banner/news-seo.png
  images/banner/premium-seo.png
  images/banner/seo-care.png
  images/banner/seo-for-beginners-training.png
  images/banner/video-seo.png
  images/banner/website-review.png
  images/banner/woocommerce-seo.png
  images/banner/yoast-seo-for-wordpress-training-2018.png
  phpcs.xml
  tests/admin/banner/test-class-admin-banner-renderer.php
  tests/admin/banner/test-class-admin-banner-sidebar-renderer.php
  tests/admin/banner/test-class-admin-banner-sidebar.php
  tests/admin/banner/test-class-admin-banner-spot-renderer.php
  tests/admin/banner/test-class-admin-banner-spot.php
  tests/admin/banner/test-class-admin-banner.php
Labels: needs-code-review

#10169 CS: clean up after merges
  admin/class-admin-asset-manager.php
  admin/class-admin-asset-yoast-components-l10n.php
  admin/class-admin-media-purge-notification.php
  admin/class-admin-recommended-replace-vars.php
  admin/class-config.php
  admin/class-help-center.php
  admin/class-yoast-dashboard-widget.php
  admin/config-ui/class-configuration-page.php
  admin/menu/class-network-admin-menu.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  admin/views/tabs/metas/post-types.php
  admin/watchers/class-slug-change-watcher.php
  frontend/class-breadcrumbs.php
  inc/class-rewrite.php
  inc/class-wpseo-content-images.php
  inc/class-wpseo-replace-vars.php
  tests/admin/help_center/test-class-help-center-template-variables-tab.php
  tests/admin/test-class-admin-recommended-replace-vars.php
  tests/admin/test-class-database-proxy.php
  tests/frontend/test-class-opengraph.php
  tests/frontend/test-class-wpseo-content-images.php
  tests/frontend/test-class-wpseo-image-utils.php
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: yoast cs

#10322 Fix the paper styling for in-paper replace var editors.
  admin/views/paper-collapsible.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
Labels: acceptance

#10324 Set yoast-components dependency to develop branch
  package.json
  yarn.lock
Labels: needs-acceptance

#10334 Change Pinterest claim site links
  admin/views/tabs/social/pinterest.php
Labels: acceptance

#10305 Pass results field instead of object to SeoAnalysis
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/contentAnalysis/SeoAnalysis.js
Labels: acceptance

#10283 Readme cleanup
  readme.txt
Labels: community-patch

#10306 Fix search errors
  frontend/class-frontend.php
Labels: community-patch

#10309 Revert "Merge pull request #9381 from Yoast/stories/9305-2-implement-openSections"
  js/src/redux/actions/openSidebarSections.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/openSidebarSections.js
  js/tests/redux/actions/openSidebarSections.test.js
  js/tests/redux/reducers/openSidebarSections.test.js
Labels: acceptance

#10333 Add days active to short links
  inc/class-wpseo-shortlinker.php
Labels: acceptance

#10376 Check for truthy has_archive values
  admin/views/tabs/metas/paper-content/post-type-content.php
Labels: needs-acceptance

#9611 Support settings import for non-default FS_METHOD definitions
  admin/import/class-import-settings.php
Labels: community-patch, needs-changes

#10423 Add a sorted YoastSidebar slot.
  js/src/components/SidebarItem.js
  js/src/components/higherorder/withYoastSidebarPriority.js
  js/src/edit.js
Labels: code-review

#10431 Import YoastSEO.js without paths
  js/src/analysis/PostDataCollector.js
  js/src/analysis/TermDataCollector.js
  js/src/analysis/classicEditorData.js
  js/src/analysis/getIndicatorForScore.js
  js/src/analysis/snippetPreview.js
  js/src/analysis/usedKeywords.js
  js/src/assessors/taxonomyAssessor.js
  js/src/components/contentAnalysis/mapResults.js
  js/src/containers/SnippetEditor.js
  js/src/decorator/tinyMCE.js
  js/src/wp-seo-recalculate.js
  package.json
  yarn.lock
Labels: development
