Repository Yoast/wordpress-seo, pull requests merged in 2018-06, with the labels that each got.

#9715 Changed the amount of images queried to be placed in OG tags: now exits after first suitable image found.
  frontend/class-opengraph-image.php
  inc/class-upgrade.php
  inc/class-wpseo-content-images.php
  inc/class-wpseo-image-utils.php
  tests/doubles/class-wpseo-content-images-double.php
  tests/frontend/test-class-opengraph.php
  tests/frontend/test-class-wpseo-content-images.php
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: component: social

#9947 Remove the WP-CLI `redirect` command for the free plugin version
  cli/class-cli-premium-requirement.php
  cli/class-cli-redirect-base-command.php
  cli/class-cli-redirect-command-namespace.php
  cli/class-cli-redirect-create-command.php
  cli/class-cli-redirect-delete-command.php
  cli/class-cli-redirect-follow-command.php
  cli/class-cli-redirect-has-command.php
  cli/class-cli-redirect-list-command.php
  cli/class-cli-redirect-update-command.php
  cli/class-cli-redirect-upsell-command-namespace.php
  cli/class-cli-yoast-command-namespace.php
  wp-seo-main.php
Labels: wp-cli

#10023 Use refresh instead of runAnalyzer to avoid delays after typing
  js/dist/search-appearance-76-RC1.js
  js/dist/search-appearance-76-RC1.min.js
  js/dist/search-appearance-761.js
  js/dist/search-appearance-761.min.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-term-scraper.js
Labels: acceptance ★

#10025 Add missing change log item
  readme.txt
Labels: code-review

#10051 Change version number in update routine
  inc/class-upgrade.php
  inc/class-wpseo-content-images.php
Labels: needs-acceptance

#10065 Fix custom fields with spaces are erroneously duplicated on reload
  js/src/helpers/replacementVariableHelpers.js
  js/src/search-appearance.js
  js/src/wp-seo-replacevar-plugin.js
Labels: acceptance ★

#10096 Fix php notice on pt_??? replace vars
  inc/class-wpseo-replace-vars.php
Labels: needs-code-review ★

#10104 Removed a margin and disabled paper styling in Search Appearance
  admin/views/class-view-utils.php
  admin/views/tabs/metas/post-types.php
  js/src/components/SnippetPreviewSection.js
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  yarn.lock
Labels: code-review

#10113 Update notification copy
  admin/watchers/class-slug-change-watcher.php
Labels: needs-code-review

#9959 Add endpoint for image size
  admin/class-cornerstone.php
  admin/endpoints/class-endpoint-file-size.php
  admin/exceptions/class-file-size-exception.php
  admin/services/class-file-size.php
  tests/admin/services/test-class-file-size.php
  wp-seo-main.php
Labels: acceptance, component: content analysis 2.0

#10149 Add notification for terms
  admin/class-admin.php
  admin/watchers/class-slug-change-watcher.php
  js/dist/wp-seo-quick-edit-handler-770.js
  js/dist/wp-seo-quick-edit-handler-770.min.js
  js/src/wp-seo-quick-edit-handler.js
  tests/admin/watchers/test-class-slug-change-watcher.php
  wp-seo-main.php
Labels: acceptance
