Repository Yoast/wordpress-seo, pull requests merged in 2018-12, with the labels that each got.

#11718 Remove dependency on 'wp-sanitize' until WP 5.0 is released
  admin/class-admin-asset-manager.php
  js/src/helpers/replacementVariableHelpers.js
  js/src/helpers/stripTags.js
Labels: regression

#11775 Adds an post type accessible check
  inc/sitemaps/class-post-type-sitemap-provider.php
Labels: code-review

#11583 CS: Move multi-line parameters out of function calls [3]
  admin/capabilities/class-capability-manager-integration.php
  admin/class-yoast-network-admin.php
  admin/class-yoast-notification-center.php
  admin/config-ui/fields/class-field-multiple-authors.php
  admin/config-ui/fields/class-field-success-message.php
  admin/filters/class-abstract-post-filter.php
  admin/google_search_console/class-gsc-table.php
  admin/google_search_console/class-gsc.php
  admin/google_search_console/views/gsc-display.php
  admin/metabox/class-metabox.php
  admin/onpage/class-onpage-request.php
  admin/taxonomy/class-taxonomy.php
  admin/views/js-templates-primary-term.php
  admin/views/tabs/metas/paper-content/breadcrumbs-content.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/metas/paper-content/media-content.php
  admin/views/tool-bulk-editor.php
  inc/class-wpseo-admin-bar-menu.php
  inc/class-wpseo-replace-vars.php
  inc/options/class-wpseo-taxonomy-meta.php
  inc/sitemaps/class-author-sitemap-provider.php
Labels: acceptance, yoast cs/qa

#11616 Improve logic for page_on_front and page_for_posts in sitemaps
  inc/sitemaps/class-post-type-sitemap-provider.php
  tests/doubles/class-wpseo-post-type-sitemap-provider-double.php
  tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
Labels: community-patch

#11795 Rename Focus KW to Keyphrase in Screen Options
  admin/class-meta-columns.php
  admin/formatter/class-term-metabox-formatter.php
Labels: in progress

#11738 Only run a single js build on yarn start
  package.json
  webpack/webpack.config.js
Labels: acceptance, component: tools, has patch

#11828 Bump YoastSEO.js to 1.44.0
  package.json
  yarn.lock
Labels: acceptance lingo

#11816 CS: Move static arrays to a class property [7]
  tests/test-class-wpseo-statistics.php
Labels: in progress, yoast cs/qa

#11815 CS: Move static arrays to a class property [6]
  tests/notifications/test-class-yoast-notification-center.php
Labels: in progress, yoast cs/qa

#11814 CS: Move static arrays to a class property [5]
  tests/inc/test-class-wpseo-admin-bar-menu.php
Labels: in progress, yoast cs/qa

#11812 CS: Move static arrays to a class property [3]
  frontend/class-twitter.php
Labels: in progress, yoast cs/qa

#11842 CS: Move multi-line parameters out of function calls [11]
  admin/taxonomy/class-taxonomy-social-fields.php
Labels: in progress, yoast cs/qa

#11841 CS: Move multi-line parameters out of function calls [10]
  tests/test-class-admin-asset-manager.php
Labels: in progress, yoast cs/qa

#11844 CS: Move multi-line parameters out of function calls [13]
  src/wordpress/integration-group.php
Labels: in progress, yoast cs/qa

#11588 CS: Move static arrays to a class property [1]
  admin/config-ui/class-configuration-structure.php
Labels: yoast cs/qa

#11845 CS: Miscellanous other function call related fixes
  admin/class-help-center.php
  admin/metabox/class-metabox.php
  admin/views/tabs/metas/paper-content/date-archives-settings.php
  inc/class-wpseo-replace-vars.php
  inc/options/class-wpseo-option-titles.php
  tests/config-ui/test-class-configuration-components.php
  tests/src/unit-tests/config/database-migration-test.php
  tests/src/unit-tests/config/plugin-test.php
  tests/src/unit-tests/formatters/indexable-post-formatter-test.php
  tests/test-class-wpseo-statistics.php
Labels: code-review, yoast cs/qa

#11843 CS: Move multi-line parameters out of function calls [12]
  inc/class-wpseo-admin-bar-menu.php
Labels: in progress, yoast cs/qa

#11840 CS: Move multi-line parameters out of function calls [9]
  src/yoast-model.php
Labels: yoast cs/qa

#11810 CS: clean up after merges
  admin/class-admin-asset-manager.php
  admin/class-admin-init.php
  admin/class-config.php
  admin/class-recalibration-beta.php
  admin/endpoints/class-endpoint-file-size.php
  admin/notifiers/class-recalibration-beta.php
  admin/services/class-file-size.php
  admin/views/licenses.php
  admin/views/paper-collapsible.php
  admin/views/sidebar.php
  tests/admin/test-class-recalibration-beta.php
  tests/doubles/class-import-settings-double.php
  tests/notifiers/test-class-recalibration-beta-notification.php
  tests/test-class-wpseo-json-ld.php
Labels: code-review, yoast cs/qa

#11582 CS: Each parameter should start on a new line in multi-line function calls [2]
  admin/config-ui/class-configuration-options-adapter.php
  admin/filters/class-cornerstone-filter.php
  admin/formatter/class-metabox-formatter.php
  admin/links/class-link-column-count.php
  admin/links/class-link-factory.php
  admin/links/class-link-reindex-dashboard.php
  admin/links/class-link-storage.php
  admin/menu/class-replacevar-editor.php
  admin/menu/class-replacevar-field.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/taxonomy/class-taxonomy.php
  admin/views/tool-file-editor.php
  admin/views/tool-import-export.php
  inc/class-upgrade.php
  inc/class-wpseo-meta.php
  inc/structured-data-blocks/class-faq-block.php
  inc/structured-data-blocks/class-how-to-block.php
  migrations/20171228151840_WpYoastIndexable.php
  tests/admin/import/test-class-import-premium-seo-pack.php
  tests/admin/import/test-class-import-squirrly.php
  tests/config-ui/test-class-configuration-options-adapter.php
  tests/config-ui/test-class-configuration-service.php
  tests/frontend/test-class-wpseo-opengraph-image.php
  tests/notifications/test-class-yoast-notification-center.php
  tests/sitemaps/test-class-wpseo-sitemap-image-parser.php
  tests/src/unit-tests/config/database-migration-test.php
  wp-seo-main.php
Labels: code-review, yoast cs/qa

#11813 CS: Move static arrays to a class property [4]
  tests/admin/test-class-admin-asset-dev-server-location.php
Labels: in progress, yoast cs/qa

#11746 Re-adds the recalibration changelog entries
  readme.txt
Labels: in progress

#11849 Fixed PHPCS warnings in primary-term-watcher.php
  src/watchers/primary-term-watcher.php
Labels: code-review, in progress, yoast cs/qa

#11855 CS: Move multi-line parameters out of function calls [8]
  tests/admin/help_center/test-class-help-center-template-variables-tab.php
  tests/admin/test-class-admin-asset-seo-location.php
  tests/admin/test-class-yoast-network-settings-api.php
  tests/admin/watchers/test-class-slug-change-watcher.php
  tests/frontend/test-class-opengraph.php
  tests/frontend/test-class-twitter.php
  tests/inc/options/test-class-wpseo-options-backfill.php
  tests/sitemaps/test-class-wpseo-sitemaps-cache.php
  tests/sitemaps/test-class-wpseo-sitemaps.php
  tests/src/unit-tests/config/plugin-test.php
  tests/test-class-admin-asset-manager.php
  tests/test-class-admin-asset.php
  tests/test-class-wpseo-json-ld.php
Labels: in progress, yoast cs/qa

#11858 Yoast CS: Adds isset() check on superglobal.
  admin/class-admin-init.php
Labels: acceptance, yoast cs/qa

#11854 Yoast CS: Add sanitization for inc\sitemaps\class-sitemaps-router.php
  inc/sitemaps/class-sitemaps-router.php
Labels: needs-code-review, yoast cs/qa

#11867 Update changelog
  readme.txt
Labels: in progress

#11865 CS/QA: Update for PHPCompatibility 9.1.0
  composer.lock
Labels: in progress, yoast cs/qa

#11856 CS/I18n: Remove line breaks from translatable strings
  admin/config-ui/fields/class-field-company-or-person.php
  admin/config-ui/fields/class-field-environment.php
  admin/config-ui/fields/class-field-google-search-console-intro.php
  admin/config-ui/fields/class-field-multiple-authors.php
  admin/config-ui/fields/class-field-post-type-visibility.php
  admin/config-ui/fields/class-field-social-profiles-intro.php
  admin/config-ui/fields/class-field-title-intro.php
Labels: component: i18n, in progress, yoast cs/qa

#11866 Yoast CS: Do sanitization and nonce verification in class-bulk-editor-list-table.php
  admin/class-bulk-editor-list-table.php
Labels: code-review, yoast cs/qa

#11877 Documentation: add missing @throws tags
  tests/admin/test-class-yoast-network-admin.php
  tests/src/unit-tests/exceptions/no-indexable-found-test.php
Labels: code-review, in progress, yoast cs/qa

#11875 Documentation: add missing class docblocks
  tests/src/doubles/database-migration.php
  tests/src/doubles/indexable-author-formatter-double.php
  tests/src/doubles/indexable-post-formatter-double.php
  tests/src/doubles/indexable-term-formatter-double.php
  tests/src/doubles/plugin.php
Labels: code-review, in progress, yoast cs/qa

#11852 Rename namespaces to agreed standard
  composer.json
  migrations/20171228151840_WpYoastIndexable.php
  migrations/20171228151841_WpYoastPrimaryTerm.php
  migrations/20180515101200_WpYoastIndexableMeta.php
  src/config/admin.php
  src/config/database-migration.php
  src/config/dependency-management.php
  src/config/frontend.php
  src/config/plugin.php
  src/config/upgrade.php
  src/exceptions/missing-method.php
  src/exceptions/no-indexable-found.php
  src/formatters/indexable-author-formatter.php
  src/formatters/indexable-post-formatter.php
  src/formatters/indexable-term-formatter.php
  src/loaders/indexable.php
  src/loggers/logger.php
  src/loggers/migration-logger.php
  src/models/indexable-meta.php
  src/models/indexable.php
  src/models/primary-term.php
  src/models/seo-meta.php
  src/watchers/indexable-author-watcher.php
  src/watchers/indexable-post-watcher.php
  src/watchers/indexable-term-watcher.php
  src/watchers/primary-term-watcher.php
  src/wordpress/integration-group.php
  src/wordpress/integration.php
  src/yoast-model.php
  src/yoast-orm-wrapper.php
  tests/src/doubles/database-migration.php
  tests/src/doubles/indexable-author-formatter-double.php
  tests/src/doubles/indexable-post-formatter-double.php
  tests/src/doubles/indexable-term-formatter-double.php
  tests/src/doubles/plugin.php
  tests/src/integration-tests/config/database-migration-test.php
  tests/src/integration-tests/config/upgrade-test.php
  tests/src/unit-tests/config/admin-test.php
  tests/src/unit-tests/config/database-migration-test.php
  tests/src/unit-tests/config/dependency-management-test.php
  tests/src/unit-tests/config/frontend-test.php
  tests/src/unit-tests/config/plugin-test.php
  tests/src/unit-tests/config/upgrade-test.php
  tests/src/unit-tests/exceptions/no-indexable-found-test.php
  tests/src/unit-tests/formatters/indexable-author-formatter-test.php
  tests/src/unit-tests/formatters/indexable-post-formatter-test.php
  tests/src/unit-tests/formatters/indexable-term-formatter-test.php
  tests/src/unit-tests/watchers/indexable-author-watcher-test.php
  tests/src/unit-tests/watchers/indexable-post-watcher-test.php
  tests/src/unit-tests/watchers/indexable-term-watcher-test.php
  tests/src/unit-tests/wordpress/integration-group-test.php
Labels: code-review, in progress, yoast cs/qa

#11872 Fix possible unminified build for the analysis worker
  webpack/webpack.config.js
Labels: code-review lingo

#11878 YoastCS: Add nonce verification social admin
  admin/class-social-admin.php
Labels: needs-acceptance, yoast cs/qa

#11868 Yoast CS: Resolve unslash and sanitization issues
  inc/class-wpseo-utils.php
Labels: needs-code-review, yoast cs/qa

#11851 Yoast CS: Fixes the input issues in ajax.php
  admin/ajax.php
Labels: needs-code-review, yoast cs/qa

#11879 Yoastcs: Fix input issues for class-metabox.php
  admin/metabox/class-metabox.php
Labels: acceptance, yoast cs/qa

#11881 Build/PHPCS: Rename PHPCS configuration file
  .gitattributes
  .gitignore
  grunt/config/phpcs.js
  phpcs.xml.dist
Labels: code-review, yoast cs/qa

#11864 Composer: improve compatibility with Windows OS
  composer.json
Labels: component: tools, needs-code-review

#11895 Documentation: use full docblocks for properties
  admin/endpoints/class-endpoint-file-size.php
  inc/options/class-wpseo-option.php
  src/config/database-migration.php
  tests/admin/links/test-class-link-type-classifier.php
  tests/admin/services/test-class-indexable-post-provider.php
  tests/admin/test-class-admin-recommended-replace-vars.php
  tests/admin/test-class-database-proxy.php
  tests/admin/watchers/test-class-slug-change-watcher.php
  tests/config-ui/components/test-class-component-connect-gsc.php
  tests/doubles/wpseo-config-component-connect-google-search-console-mock.php
  tests/doubles/wpseo-role-manager-mock.php
  tests/framework/class-wpseo-unit-test-case-frontend.php
  tests/frontend/test-class-front-end-page-type.php
  tests/frontend/test-class-opengraph.php
  tests/inc/test-class-wpseo-admin-bar-menu.php
  tests/notifications/test-class-yoast-notification-center.php
  tests/notifications/test-class-yoast-notification.php
  tests/recalculate/test-class-recalculate-scores-ajax.php
  tests/test-class-primary-term-admin.php
Labels: code-review, yoast cs/qa

#11888 Rename ORMWrapper::_create_model_instance() method
  src/yoast-orm-wrapper.php
Labels: code-review, yoast cs/qa

#11897 Unslash the value
  admin/pages/dashboard.php
Labels: code-review, yoast cs/qa

#11885 Yoast CS: Adds sanitization in file class-remove-reply-to-com.php
  frontend/class-remove-reply-to-com.php
Labels: code-review, yoast cs/qa

#11869 Cs fix input tools files
  admin/class-bulk-editor-list-table.php
  admin/views/tool-bulk-editor.php
  admin/views/tool-file-editor.php
Labels: needs-code-review, yoast cs/qa

#11890 YoastCS: Fix cs issues in inc\class-wpseo-meta.php
  admin/class-social-admin.php
  frontend/class-frontend.php
  inc/class-wpseo-meta.php
  tests/test-class-wpseo-meta.php
Labels: needs-code-review, yoast cs/qa
