Repository Yoast/wordpress-seo, pull requests merged in 2018-04, with the labels that each got.

#9347 CS: clean up after latest merges - escape output
  admin/config-ui/fields/class-field-google-search-console-intro.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/tool/import-seo.php
Labels: yoast cs

#9510 Setup webpack config for the snippet editor
  webpack/webpack.config.default.js
Labels: acceptance ★

#9288 Added to documentation of getColorFromScore()
  js/src/wp-seo-dashboard-widget.js
Labels: blocked

#9529 Add ESLinting to tests
  Gruntfile.js
  grunt/config/eslint.js
  js/tests/.eslintrc
  js/tests/data.test.js
  js/tests/edit.test.js
  js/tests/isGutenbergDataAvailable.test.js
  js/tests/shortcode-plugin.test.js
Labels: acceptance ★

#9547 Changed 'Dashboard' into 'General' in Admin menu
  inc/wpseo-non-ajax-functions.php
Labels: needs-code-review

#9554 Move the Gutenberg register to the configuration page class
  admin/class-admin-asset-manager.php
  admin/config-ui/class-configuration-page.php
Labels: needs-code-review ★

#9559 Fixes backwards compatibility for WPSEO_Opengraph_Image class
  frontend/class-frontend.php
  frontend/class-opengraph-image.php
  frontend/class-opengraph.php
  frontend/class-twitter.php
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: needs-acceptance

#9572 Reverts the wpseo_focuskw_strippable_chars filter
  inc/class-wpseo-meta.php
  readme.txt
Labels: needs-code-review
