Repository Yoast/wordpress-seo, pull requests merged in 2018-02, with the labels that each got.

#8872 Move company info / your info
  admin/class-config.php
  admin/pages/dashboard.php
  admin/pages/metas.php
  admin/views/tabs/dashboard/knowledge-graph.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/breadcrumbs.php
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/general/force-rewrite-title.php
  admin/views/tabs/metas/general/homepage.php
  admin/views/tabs/metas/general/knowledge-graph.php
  admin/views/tabs/metas/general/title-separator.php
  admin/views/tabs/metas/home.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/taxonomies.php
  css/dist/yst_plugin_tools-700-rtl.css
  css/dist/yst_plugin_tools-700-rtl.min.css
  css/dist/yst_plugin_tools-700.css
  css/dist/yst_plugin_tools-700.min.css
  css/src/yst_plugin_tools.scss
  inc/class-upgrade.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-option-wpseo.php
  js/dist/commons-700.js
  js/dist/commons-700.min.js
  js/dist/configuration-wizard-700.js
  js/dist/configuration-wizard-700.min.js
  js/dist/jquery.tablesorter.min.js
  js/dist/wp-seo-dashboard-widget-700.js
  js/dist/wp-seo-dashboard-widget-700.min.js
  js/dist/wp-seo-help-center-700.js
  js/dist/wp-seo-help-center-700.min.js
  js/dist/wp-seo-post-scraper-700.js
  js/dist/wp-seo-post-scraper-700.min.js
  js/dist/wp-seo-term-scraper-700.js
  js/dist/wp-seo-term-scraper-700.min.js
  languages/wordpress-seo.pot
  tests/config-ui/test-class-configuration-options-adapter.php
Labels: needs-code-review

#8974 Move restore default settings
  admin/class-config.php
  admin/views/tabs/dashboard/general.php
Labels: acceptance, backend

#8922 Adds functionality to invert logic for displaying the metabox
  admin/class-yoast-form.php
  admin/metabox/class-metabox.php
  admin/views/class-view-utils.php
  tests/test-class-wpseo-metabox.php
Labels: acceptance

#8931 Improve the Webmaster tools page labels, links, and help text.
  admin/views/tabs/dashboard/webmaster-tools.php
Labels: development

#8874 Remove deprecated functions
  admin/ajax.php
  admin/class-admin-init.php
  admin/class-admin.php
  admin/class-config.php
  admin/class-help-center.php
  admin/class-meta-columns.php
  admin/class-social-admin.php
  admin/class-yoast-notification-center.php
  admin/metabox/class-metabox.php
  admin/onpage/class-onpage-option.php
  admin/onpage/class-onpage-request.php
  admin/taxonomy/class-taxonomy.php
  deprecated/class-googleplus.php
  deprecated/class-onpage-email-presenter.php
  deprecated/class-onpage-notifier.php
  deprecated/class-snippet-preview.php
  deprecated/class-yoast-textstatistics.php
  frontend/class-breadcrumbs.php
  frontend/class-json-ld.php
  frontend/class-twitter.php
  inc/class-wpseo-statistics.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option.php
  inc/sitemaps/class-author-sitemap-provider.php
  inc/sitemaps/class-sitemap-image-parser.php
  inc/sitemaps/class-sitemaps.php
  inc/wpseo-functions-deprecated.php
  inc/wpseo-non-ajax-functions.php
  readme.txt
Labels: code-review

#8979 Always show the config wizard banner
  admin/notifiers/class-configuration-notifier.php
  admin/pages/dashboard.php
  admin/views/about.php
  admin/views/tabs/dashboard/dashboard.php
  admin/views/tabs/dashboard/general.php
  tests/notifiers/test-class-configuration-notifier.php
  tests/test-class-wpseo-metabox.php
Labels: code-review

#8950 Add question mark and help to the switch toggles
  admin/class-yoast-form.php
  admin/views/class-view-utils.php
  admin/views/tabs/dashboard/security.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/taxonomies.php
  css/dist/admin-global-700-rtl.css
  css/dist/admin-global-700-rtl.min.css
  css/dist/admin-global-700.css
  css/dist/admin-global-700.min.css
  css/dist/alerts-700-rtl.css
  css/dist/alerts-700-rtl.min.css
  css/dist/alerts-700.css
  css/dist/alerts-700.min.css
  css/dist/metabox-700-rtl.css
  css/dist/metabox-700-rtl.min.css
  css/dist/metabox-700.css
  css/dist/metabox-700.min.css
  css/dist/toggle-switch-700-rtl.css
  css/dist/toggle-switch-700-rtl.min.css
  css/dist/toggle-switch-700.css
  css/dist/toggle-switch-700.min.css
  css/dist/yoast-components-700-rtl.css
  css/dist/yoast-components-700-rtl.min.css
  css/dist/yoast-components-700.css
  css/dist/yoast-components-700.min.css
  css/src/admin-global.scss
  css/src/toggle-switch.scss
  js/dist/commons-700.js
  js/dist/commons-700.min.js
  js/dist/configuration-wizard-700.js
  js/dist/configuration-wizard-700.min.js
  js/dist/wp-seo-dashboard-widget-700.js
  js/dist/wp-seo-dashboard-widget-700.min.js
  js/dist/wp-seo-help-center-700.js
  js/dist/wp-seo-help-center-700.min.js
  js/dist/wp-seo-metabox-700.js
  js/dist/wp-seo-metabox-700.min.js
  js/dist/wp-seo-post-scraper-700.js
  js/dist/wp-seo-post-scraper-700.min.js
  js/dist/wp-seo-recalculate-700.js
  js/dist/wp-seo-recalculate-700.min.js
  js/dist/wp-seo-term-scraper-700.js
  js/dist/wp-seo-term-scraper-700.min.js
Labels: development

#8996 CS: clean up after merges
  admin/class-admin-init.php
  admin/class-meta-columns.php
  admin/class-social-facebook.php
  admin/class-yoast-form.php
  admin/formatter/class-post-metabox-formatter.php
  admin/links/class-link-query.php
  admin/notifiers/class-configuration-notifier.php
  admin/pages/dashboard.php
  admin/views/tabs/dashboard/dashboard.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/dashboard/webmaster-tools.php
  admin/views/tabs/metas/general/force-rewrite-title.php
  admin/views/tabs/metas/general/homepage.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/taxonomies.php
  admin/views/user-profile.php
  deprecated/class-submenu-hider.php
  deprecated/class-wpseo-advanced-settings.php
  deprecated/class-wpseo-option-internallinks.php
  deprecated/class-wpseo-option-permalinks.php
  frontend/class-frontend.php
  inc/class-upgrade.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option-titles.php
  inc/sitemaps/class-post-type-sitemap-provider.php
  tests/admin/test-class-option-tab.php
  tests/config-ui/test-class-configuration-options-adapter.php
  tests/formatter/test-post-metabox-formatter.php
  tests/frontend/test-class-remove-reply-to-com.php
  tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
  tests/test-class-opengraph.php
  tests/test-class-wpseo-json-ld.php
Labels: yoast cs

#9008 Upgrade yoast-components to 3.0.2
  package.json
  yarn.lock
Labels: needs-acceptance ★

#9048 Update yarn grunt packages
  languages/wordpress-seo-es_AR.json
  languages/wordpress-seo-es_VE.json
  languages/wordpress-seo-pt_PT.json
  languages/wordpress-seo-zh_CN.json
  languages/wordpress-seo.pot
  package.json
  yarn.lock
Labels: code-review

#9053 Avoid ini value parsing
  admin/class-import.php
Labels: needs-code-review

#9020 Add support for a new template variable `%%archive_title%%`
  inc/class-wpseo-replace-vars.php
Labels: community-patch
