Repository Yoast/wordpress-seo, pull requests merged in 2018-10, with the labels that each got.

#11140 Add target="_blank" to open new tab when click
  admin/config-ui/fields/class-field-google-search-console-intro.php
Labels: code-review, community-patch

#11153 CS: Consistency, newly deprecated method
  admin/class-yoast-form.php
Labels: yoast cs

#11159 CS: Each parameter should start on a new line in multi-line function calls
  admin/class-add-keyword-modal.php
  admin/class-admin-init.php
  admin/class-admin.php
  admin/class-database-proxy.php
  admin/class-meta-storage.php
  admin/class-plugin-availability.php
Labels: yoast cs

#11155 CS: method modifier/visibility order
  inc/indexables/class-indexable.php
Labels: yoast cs

#11161 CS: Move multi-line parameters out of function calls [2]
  admin/class-asset.php
Labels: yoast cs

#11154 CS: fix method name
  tests/admin/test-class-plugin-compatibility.php
Labels: yoast cs

#11156 CS/best practices: use incrementor/decrementor were appropriate
  admin/google_search_console/class-gsc-marker.php
Labels: code-review, yoast cs

#11158 QA: use `wp_rand()` instead of `mt_rand()` [2]
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: yoast cs

#11157 QA: use `wp_rand()` instead of `mt_rand()` [1]
  inc/class-wpseo-image-utils.php
Labels: yoast cs

#11184 Bump Yoast Components to 4.13.0.
  package.json
  yarn.lock
Labels: acceptance

#11202 Update README.md
  README.md
Labels: community-patch

#11198 #9317 Fixed the date archives settings description.
  admin/views/tabs/metas/paper-content/date-archives-settings.php
Labels: community-patch

#10843 Change font of title measure element to mimic Google
  js/src/analysis/PostDataCollector.js
  js/src/analysis/TermDataCollector.js
  js/src/helpers/measureTextWidth.js
  yarn.lock
Labels: acceptance lingo

#11302 Update changelog
  readme.txt
Labels: code-review lingo

#11064 Feature/valid image url filter
  frontend/class-opengraph-image.php
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: community-patch, development

#11162 Refactor the `WPSEO_Customizer` class
  admin/class-customizer.php
Labels: yoast cs

#11263 Remove first usable image fallback from opengraph
  frontend/class-opengraph-image.php
  frontend/class-twitter.php
  tests/frontend/test-class-twitter.php
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: needs-code-review

#11196 [i18n] Add missing gettext function
  admin/views/sidebar.php
Labels: community-patch

#11211 CS/QA: Update for PHPCompatibility 9.0.0 / PHPCompatibilityWP 2.0.0
  composer.json
  composer.lock
  inc/sitemaps/class-sitemap-image-parser.php
  phpcs.xml
Labels: yoast cs

#11204 Fix minor php notice
  inc/class-wpseo-meta.php
Labels: community-patch, needs-changes

#11365 Update YoastSEO.js to 1.41.0
  package.json
  yarn.lock
Labels: needs-code-review lingo

#11321 Add permalink warning on settings page
  admin/class-admin-init.php
Labels: community-patch

#11310 Add some unit tests
  admin/class-option-tabs.php
  tests/admin/test-class-option-tabs.php
  tests/config-ui/components/test-class-component-mailchimp-signup.php
Labels: needs-code-review

#11426 Add clean tasks to build:js and build:css
  grunt/config/aliases.yaml
  grunt/config/clean.js
Labels: acceptance

#11463 Update YoastSEO.js and components
  package.json
  yarn.lock
Labels: acceptance lingo

#11472 Update changelog
  readme.txt
Labels: acceptance lingo

#11481 Checks if attachments are disabled for Yoast SEO
  inc/class-wpseo-utils.php
Labels: acceptance
