Repository Yoast/wordpress-seo, pull requests merged in 2018-05, with the labels that each got.

#9599 Add store to replacevars plugins and dispatch action to fill store.
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-replacevar-plugin.js
Labels: acceptance ★

#9645 Removed ratio check as it is currently breaking OpenGraph
  frontend/class-opengraph-image.php
  inc/class-wpseo-image-utils.php
  readme.txt
  tests/frontend/test-class-wpseo-image-utils.php
Labels: needs-code-review

#9663 CS/QA: rename some local variables to snake_case
  tests/admin/import/test-class-import-premium-seo-pack.php
  tests/admin/import/test-class-import-squirrly.php
Labels: yoast cs

#9662 CS: clean up after latest merges
  admin/class-add-keyword-modal.php
  admin/class-bulk-editor-list-table.php
  admin/class-premium-benefits-list.php
  admin/class-unsupported-php-message.php
  admin/class-yoast-modal.php
  admin/google_search_console/views/gsc-display.php
  admin/import/plugins/class-import-seo-framework.php
  admin/import/plugins/class-import-squirrly.php
  admin/metabox/class-metabox-add-keyword-tab.php
  admin/metabox/class-metabox-addon-section.php
  admin/metabox/class-metabox.php
  admin/services/class-indexable-post-provider.php
  admin/services/class-indexable.php
  admin/views/licenses.php
  frontend/class-opengraph-image.php
  inc/options/class-wpseo-option-social.php
  tests/admin/import/test-class-import-premium-seo-pack.php
  tests/admin/import/test-class-import-smartcrawl.php
  tests/admin/import/test-class-import-squirrly.php
  tests/admin/test-class-database-proxy.php
  tests/frontend/test-class-wpseo-image-utils.php
  tests/frontend/test-class-wpseo-opengraph-image.php
  tests/inc/test-class-post-type.php
  tests/onpage/test-class-onpage.php
  tests/services/test-class-indexable-post-provider.php
  tests/services/test-class-indexable-term-provider.php
  tests/sitemaps/test-class-wpseo-sitemaps-renderer.php
Labels: yoast cs

#9667 Check if url key exists in given argument
  frontend/class-opengraph-image.php
  inc/class-wpseo-image-utils.php
  tests/frontend/test-class-wpseo-image-utils.php
  tests/frontend/test-class-wpseo-opengraph-image.php
Labels: development

#9678 Create classic editor data object and get more replacevars from wpseoReplaceVarsL10n
  js/src/analysis/PostDataCollector.js
  js/src/analysis/classicEditorData.js
  js/src/analysis/data.js
  js/src/edit.js
  js/src/helpers/updateReplacementVariables.js
  js/src/redux/actions/snippetEditor.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-replacevar-plugin.js
  js/tests/data.test.js
  js/tests/edit.test.js
Labels: acceptance ★

#9707 Add missing replace variables default
  js/src/values/defaultReplaceVariables.js
Labels: code-review ★

#9708 Implement working category replacevar for posts
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-replacevar-plugin.js
Labels: acceptance ★

#9557 Add WP-CLI commands to manage redirects
  .travis.yml
  cli/class-cli-premium-requirement.php
  cli/class-cli-redirect-base-command.php
  cli/class-cli-redirect-command-namespace.php
  cli/class-cli-redirect-create-command.php
  cli/class-cli-redirect-delete-command.php
  cli/class-cli-redirect-follow-command.php
  cli/class-cli-redirect-has-command.php
  cli/class-cli-redirect-list-command.php
  cli/class-cli-redirect-update-command.php
  composer.json
  wp-seo-main.php
Labels: wp-cli

#9722 Default active keyword to empty string
  js/src/redux/reducers/activeKeyword.js
Labels: needs-code-review ★

#9725 Implement legacy replacevars
  js/src/components/SnippetPreviewSection.js
  js/src/containers/SnippetEditor.js
  js/src/redux/actions/snippetEditor.js
  js/src/redux/reducers/snippetEditor.js
  js/src/values/defaultReplaceVariables.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-replacevar-plugin.js
  js/src/wp-seo-term-scraper.js
  js/tests/redux/reducers/snippetEditor.test.js
Labels: needs-code-review ★

#9742 Custom field and custom taxonomy replacevars
  js/src/analysis/classicEditorData.js
  js/src/redux/actions/snippetEditor.js
  js/src/redux/reducers/snippetEditor.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-replacevar-plugin.js
  js/src/wp-seo-term-scraper.js
Labels: needs-code-review ★

#9747 Add data equality checks for the snippet editor data
  js/src/wp-seo-term-scraper.js
Labels: acceptance ★

#9720 Remove the old snippet preview
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-content-fields.php
  js/src/analysis/PostDataCollector.js
  js/src/analysis/TermDataCollector.js
  js/src/analysis/classicEditorData.js
  js/src/components/SnippetPreviewSection.js
  js/src/edit.js
  js/src/wp-seo-metabox.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-term-scraper.js
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/containers/SnippetEditor.test.js
Labels: code-review ★

#9813 Fix translations for YoastSEO.js
  grunt/custom/i18n-clean-json.js
Labels: needs-code-review ★

#9816 Fix custom fields and taxonomies in the gutenberg editor
  js/src/analysis/classicEditorData.js
  js/src/analysis/data.js
  js/src/helpers/replacementVariableHelpers.js
  js/src/helpers/updateReplacementVariables.js
Labels: needs-code-review ★

#9822 Add template variable tab to Term Help Center
  admin/help_center/class-template-variables-tab.php
  admin/taxonomy/class-taxonomy.php
  tests/admin/help_center/test-class-help-center-template-variables-tab.php
Labels: needs-code-review

#9762 Fixed the analysis failing on numbers only keyword
  js/src/analysis/keywordTab.js
Labels: code-review ★

#9856 Bump YoastSEO.js to 1.33.1
  package.json
  yarn.lock
Labels: needs-code-review

#9858 Revert "Merge pull request #9720 from Yoast/stories/remove-old-snippet-editor"
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-content-fields.php
  js/src/analysis/PostDataCollector.js
  js/src/analysis/TermDataCollector.js
  js/src/analysis/classicEditorData.js
  js/src/components/SnippetPreviewSection.js
  js/src/edit.js
  js/src/wp-seo-metabox.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-term-scraper.js
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/containers/SnippetEditor.test.js
Labels: needs-acceptance ★

#9853 Readme/Changelog: make a link clickable
  readme.txt
Labels: code-review, documentation

#9887 Add X-Redirect-By header to all redirects
  frontend/class-frontend.php
  inc/class-rewrite.php
  inc/sitemaps/class-sitemaps-router.php
Labels: needs-code-review

#9748 JSON-LD breadcrumbs
  frontend/class-breadcrumbs.php
  frontend/class-json-ld.php
Labels: acceptance

#9907 Add Yoast seo.js changelog items
  readme.txt
Labels: code-review
