Repository Yoast/wordpress-seo, pull requests merged in 2018-08, with the labels that each got.

#10487 Made styled components a global dependency
  js/src/wp-seo-wp-globals-backport.js
  webpack/paths.js
  webpack/webpack.config.js
Labels: acceptance

#10492 Fix padding and margin in the container on the metabox
  css/dist/metabox-790-rtl.css
  css/dist/metabox-790-rtl.min.css
  css/dist/metabox-790.css
  css/dist/metabox-790.min.css
  css/src/metabox.scss
Labels: needs-code-review

#10496 Only use `printf` on the part that needs a variable
  admin/metabox/class-metabox-section-react.php
Labels: bug

#10500 Add links to explanation texts
  admin/class-admin.php
  admin/class-expose-shortlinks.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  inc/class-wpseo-utils.php
  js/src/analysis/TermDataCollector.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/contentAnalysis/SeoAnalysis.js
Labels: development, gutenberg

#10514 Add webpack bundle analyzer
  .gitignore
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: code-review

#10549 Fix styling of the metabox tabs on small screens
  css/dist/metabox-80-RC1-rtl.css
  css/dist/metabox-80-RC1-rtl.min.css
  css/dist/metabox-80-RC1.css
  css/dist/metabox-80-RC1.min.css
  css/src/metabox.scss
Labels: needs-changes

#10583 Fix Jest security error: localStorage is not available for opaque origins at Window.get localStorage
  package.json
Labels: code-review

#10575 CS/QA: use `self` when referencing a (static) class member from within the same class
  admin/class-admin-utils.php
  admin/onpage/class-onpage.php
  inc/options/class-wpseo-options.php
Labels: code-review

#10576 CS: clean up after merges
  admin/class-admin.php
  admin/class-paper-presenter.php
  admin/config-ui/fields/class-field-success-message.php
  admin/formatter/class-metabox-formatter.php
  admin/google_search_console/class-gsc-modal.php
  admin/import/class-import-settings.php
  admin/links/class-link-installer.php
  admin/links/class-link-reindex-dashboard.php
  admin/metabox/class-metabox-section-react.php
  admin/notifiers/class-post-type-archive-notification-handler.php
  admin/onpage/class-ryte-service.php
  admin/views/sidebar.php
  admin/views/tabs/metas/paper-content/breadcrumbs-content.php
  admin/views/tool-file-editor.php
  frontend/class-breadcrumbs.php
  inc/class-wpseo-admin-bar-menu.php
  inc/class-wpseo-custom-taxonomies.php
  inc/sitemaps/class-sitemap-image-parser.php
  inc/wpseo-non-ajax-functions.php
  tests/admin/test-class-admin-editor-specific-replace-vars.php
  tests/frontend/test-class-opengraph.php
  tests/test-class-wpseo-meta.php
Labels: needs-code-review

#10623 Bumped version of YoastSEO to 1.37, components to 4.9.0
  package.json
  yarn.lock
Labels: needs-code-review

#10627 Restricts loading of backports if classic editor is currently being used
  admin/class-admin-asset-manager.php
Labels: needs-acceptance

#10625 Fixed broken version compare checks
  admin/class-gutenberg-compatibility.php
  tests/admin/test-class-gutenberg-compatibility.php
Labels: acceptance

#10613 Render json-ld server side to circumvent tags being stripped from post_content.
  admin/class-admin.php
  admin/class-gutenberg-compatibility.php
  inc/class-structured-data-blocks.php
  inc/structured-data-blocks/class-how-to-block.php
  js/src/structured-data-blocks/how-to/block.js
  js/src/structured-data-blocks/how-to/components/HowTo.js
  js/src/structured-data-blocks/how-to/components/HowToStep.js
  wp-seo-main.php
Labels: acceptance, bug

#10645 Create Structured Data Block - FAQ Page
  css/src/structured-data-blocks.scss
  inc/class-structured-data-blocks.php
  inc/structured-data-blocks/class-faq-block.php
  inc/structured-data-blocks/class-how-to-block.php
  js/src/structured-data-blocks/faq/block.js
  js/src/structured-data-blocks/faq/components/FAQ.js
  js/src/structured-data-blocks/faq/components/Question.js
  js/src/structured-data-blocks/how-to/components/HowTo.js
  js/src/structured-data-blocks/how-to/components/HowToStep.js
  js/src/structured-data-blocks/how-to/legacy/index.js
  js/src/structured-data-blocks/how-to/legacy/v1.js
  js/src/wp-seo-structured-data-blocks.js
Labels: development

#10659 How to block time duration improvements
  js/src/structured-data-blocks/how-to/block.js
  js/src/structured-data-blocks/how-to/components/HowTo.js
  js/src/structured-data-blocks/how-to/legacy/index.js
  js/src/structured-data-blocks/how-to/legacy/v1.js
  package.json
  yarn.lock
Labels: needs-code-review

#10713 Reintroduce structured data blocks feature flag
  wp-seo-main.php
Labels: acceptance

#10722 Fix error when async or defer is added to scripts
  admin/class-admin-asset-manager.php
  grunt/config/copy.js
  js/vendor/lodash-noconflict.js
Labels: needs-code-review

#10735 Give access to image functions for use in extensions
  frontend/class-opengraph-image.php
Labels: needs-code-review

#10749 Reintroduce parent title code for gutenberg
  js/src/wp-seo-replacevar-plugin.js
Labels: needs-code-review

#10753 Send paper to worker.
  js/src/analysis/collectAnalysisData.js
  js/src/analysis/refreshAnalysis.js
Labels: needs-code-review lingo

#10751 Expose mark button status as a selector
  js/src/redux/selectors/results.js
Labels: needs-code-review lingo

#10764 Always refresh previously used keywords.
  js/src/analysis/usedKeywords.js
Labels: needs-code-review lingo

#10744 Decrease the number of cases that can cause changing overall scores
  js/src/analysis/refreshAnalysis.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-term-scraper.js
  readme.txt
Labels: needs-code-review

#10784 Make og:url unpaginated by default
  frontend/class-opengraph.php
Labels: acceptance

#10772 Change CRLF to LF line endings in the issue template files
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Custom.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: needs-code-review

#10804 Remove WHIP dependency and code
  admin/class-admin-init.php
  admin/class-admin-utils.php
  admin/class-admin.php
  admin/class-unsupported-php-message.php
  composer.json
  composer.lock
Labels: needs-code-review

#10815 Bump YoastSEO.js to 1.39.0
  package.json
  yarn.lock
Labels: acceptance lingo

#10840 Replace h3 with strong
  js/src/structured-data-blocks/faq/components/Question.js
Labels: acceptance
