Repository Yoast/wordpress-seo, pull requests merged in 2019-07, with the labels that each got.

#13143 Remove noindex from feeds
  frontend/class-frontend.php
Labels: 0.5

#13126 Image set in setting should never show for authors
  frontend/schema/class-schema-author.php
  frontend/schema/class-schema-person.php
Labels: 0.5, in sprint

#13142 Implement ARIA tabbed interface for the new metabox tabs
  admin/metabox/class-metabox-addon-section.php
  admin/metabox/class-metabox-section-react.php
  admin/metabox/class-metabox-section-readability.php
  admin/metabox/class-metabox-tab-section.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  js/src/wp-seo-metabox.js
Labels: 2, in sprint

#13195 CS: clean up after merges
  admin/ajax/class-yoast-dismissable-notice.php
  admin/class-admin.php
  admin/class-bulk-title-editor-list-table.php
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox-section-readability.php
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-author.php
  frontend/schema/class-schema-breadcrumb.php
  frontend/schema/class-schema-faq-question-list.php
  frontend/schema/class-schema-faq-questions.php
  frontend/schema/class-schema-faq.php
  frontend/schema/class-schema-howto.php
  frontend/schema/class-schema-organization.php
  frontend/schema/class-schema-person.php
  frontend/schema/class-schema-utils.php
  frontend/schema/class-schema-website.php
  frontend/schema/class-schema.php
  inc/class-wpseo-meta.php
  inc/options/class-wpseo-option-titles.php
  inc/sitemaps/class-post-type-sitemap-provider.php
  integration-tests/taxonomy/test-class-taxonomy-presenter.php
  src/loaders/indexable.php
  tests/admin/admin-asset-analysis-worker-location-test.php
  tests/doubles/class-schema-how-to-double.php
  tests/doubles/onpage-option-mock.php
  tests/frontend/schema/class-schema-how-to-test.php
  tests/frontend/schema/class-schema-webpage-test.php
  tests/frontend/schema/mainimage-test.php
  tests/metabox/metabox-editor-test.php
  tests/roles/role-manager-test.php
Labels: yoast cs/qa

#13194 CS/QA: Update for PHPCompatibility 9.2.0
  composer.lock
Labels: yoast cs/qa

#13175 Remove advanced tab
  admin/class-paper-presenter.php
  admin/class-social-admin.php
  admin/metabox/class-abstract-sectioned-metabox-tab.php
  admin/metabox/class-metabox-addon-section.php
  admin/metabox/class-metabox-collapsible.php
  admin/metabox/class-metabox-collapsibles-section.php
  admin/metabox/class-metabox-section-react.php
  admin/metabox/class-metabox-tab-section.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/taxonomy/class-taxonomy.php
  admin/views/paper-collapsible.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/breadcrumbs.php
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/rss.php
  admin/views/tabs/metas/taxonomies.php
  css/src/metabox.scss
  css/src/yst_plugin_tools.scss
  tests/admin/class-paper-presenter-test.php
  tests/metabox/class-metabox-collapsibles-section-test.php
Labels: UI change

#13112 Improve vendor prefixing by only adding PHP files that aren't tests or examples
  config/php-scoper/idiorm.inc.php
Labels: 1, in sprint

#13153 Fix capitalizing of Classic Editor plugin
  admin/class-admin-init.php
Labels: community-patch

#12971 Fix for issue #10002
  inc/class-wpseo-image-utils.php
Labels: community-patch

#13255 CS: clean up after merges
  admin/class-paper-presenter.php
  admin/metabox/class-abstract-sectioned-metabox-tab.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/views/paper-collapsible.php
  config/composer/actions.php
  config/dependency-injection/container-compiler.php
  config/dependency-injection/custom-loader.php
  frontend/schema/class-schema-webpage.php
  src/builders/indexable-post-builder.php
  src/conditionals/admin-conditional.php
  src/conditionals/conditional.php
  src/conditionals/feature-flag-conditional.php
  src/conditionals/indexables-feature-flag-conditional.php
  src/conditionals/no-conditionals.php
  src/database/database-setup.php
  src/database/migration-runner.php
  src/database/ruckusing-framework.php
  src/repositories/indexable-repository.php
  src/repositories/primary-term-repository.php
  src/watchers/primary-term-watcher.php
  src/wordpress/wrapper.php
  tests/admin/class-paper-presenter-test.php
  tests/bootstrap.php
  tests/builders/indexable-author-builder-test.php
  tests/builders/indexable-post-builder-test.php
  tests/builders/indexable-term-builder-test.php
  tests/database/migration-runner-test.php
  tests/doubles/class-my-yoast-proxy.php
  tests/doubles/class-schema-faq-questions-double.php
  tests/frontend/schema/class-schema-faq-questions-test.php
  tests/frontend/schema/class-schema-how-to-test.php
  tests/frontend/schema/class-schema-image-test.php
  tests/frontend/schema/class-schema-webpage-test.php
  tests/loader-test.php
  tests/metabox/class-metabox-collapsibles-section-test.php
  tests/watchers/indexable-post-watcher-test.php
  tests/watchers/indexable-term-watcher-test.php
Labels: yoast cs/qa

#13185 Fix WP_Query usage
  admin/links/class-link-columns.php
Labels: community-patch

#13243 Add 'user_language' to links to Yoast.com
  inc/class-wpseo-shortlinker.php
  yarn.lock
Labels: community-patch

#13250 Use importScripts inside the worker instead of module imports to replicate webpack external behavior
  js/src/wp-seo-analysis-worker.js
Labels: 3

#13280 Fixed output sanitation errors in PHPCS regarding the bulk editor.
  admin/class-bulk-description-editor-list-table.php
  admin/class-bulk-editor-list-table.php
  admin/class-bulk-title-editor-list-table.php
Labels: yoast cs/qa

#13290 QA: make text translatable
  admin/views/licenses.php
Labels: yoast cs/qa

#13238 Create separate tabs for video and news in metabox
  admin/metabox/class-metabox-addon-section.php
  admin/metabox/class-metabox-section-additional.php
  admin/metabox/class-metabox.php
  deprecated/class-metabox-addon-section.php
  tests/TestCase.php
  tests/admin/metabox/metabox-collapsibles-section-test.php
  tests/admin/metabox/metabox-editor-test.php
  tests/admin/metabox/metabox-section-additional-test.php
  tests/admin/metabox/metabox-test.php
  tests/admin/myyoast-proxy-test.php
  tests/admin/roles/register-roles-test.php
  tests/admin/roles/role-manager-factory-test.php
  tests/admin/roles/role-manager-test.php
  tests/admin/watchers/indexable-author-watcher-test.php
  tests/admin/watchers/indexable-post-watcher-test.php
  tests/admin/watchers/indexable-term-watcher-test.php
  tests/doubles/admin/metabox/metabox-double.php
  tests/doubles/admin/my-yoast-proxy-double.php
  tests/doubles/frontend/schema/schema-faq-questions-double.php
  tests/doubles/frontend/schema/schema-how-to-double.php
  tests/doubles/frontend/schema/schema-main-image-double.php
  tests/frontend/schema/mainimage-test.php
  tests/frontend/schema/schema-faq-questions-test.php
  tests/frontend/schema/schema-how-to-test.php
  tests/frontend/schema/schema-image-test.php
  tests/frontend/schema/schema-webpage-test.php
Labels: UI change
