Repository Yoast/wordpress-seo, pull requests merged in 2019-10, with the labels that each got.

#13557 Revert "Add clean:artifact after compress:artifact"
  grunt/config/aliases.yaml
Labels: changelog: non-user-facing

#13566 Presentation home page robots
  src/presentations/indexable-home-page-presentation.php
Labels: changelog: non-user-facing

#13458 Passed posts' main image url to new mobile snippet preview
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  inc/class-wpseo-content-images.php
  inc/class-wpseo-image-utils.php
  js/src/containers/SnippetEditor.js
  js/src/edit.js
  tests/TestCase.php
  tests/admin/formatter/post-metabox-formatter-test.php
  tests/admin/formatter/term-metabox-formatter-test.php
  tests/doubles/admin/formatter/post-metabox-formatter-double.php
  tests/doubles/admin/formatter/term-metabox-formatter-double.php
  tests/doubles/inc/image-utils-double.php
  tests/inc/class-wpseo-content-images-test.php
  tests/inc/class-wpseo-image-utils-test.php
Labels: UI change, changelog: enhancement

#13354 CS: enforce consistent array format
  phpcs.xml.dist
  src/loggers/logger.php
  src/orm/yoast-model.php
  tests/TestCase.php
  tests/admin/admin-features-test.php
  tests/admin/formatter/term-metabox-formatter-test.php
  tests/admin/metabox/metabox-editor-test.php
  tests/admin/myyoast-proxy-test.php
  tests/admin/roles/role-manager-test.php
  tests/admin/watchers/indexable-author-watcher-test.php
  tests/admin/watchers/indexable-post-watcher-test.php
  tests/admin/watchers/indexable-term-watcher-test.php
  tests/frontend/schema/schema-faq-questions-test.php
  tests/frontend/schema/schema-webpage-test.php
  tests/inc/class-wpseo-content-images-test.php
  tests/inc/options/option-social-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13576 CS: clean up after merges / namespaced files
  config/php-codeshift/remove-vendor-prefixing-array-key-visitor.php
  config/php-codeshift/remove-vendor-prefixing-codemod.php
  config/php-codeshift/remove-vendor-prefixing-comment-visitor.php
  config/php-codeshift/remove-vendor-prefixing-visitor.php
  src/repositories/indexable-repository.php
  tests/admin/formatter/post-metabox-formatter-test.php
  tests/admin/formatter/term-metabox-formatter-test.php
  tests/inc/class-wpseo-content-images-test.php
  tests/inc/class-wpseo-image-utils-test.php
  tests/inc/options/option-social-test.php
Labels: yoast cs/qa

#13532 Makes "old WP version notice" dynamic
  admin/class-admin-init.php
Labels: changelog: enhancement

#13573 CS: update Premium to use YoastCS 1.3.0
  .travis.yml
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#13580 CS: clean up after merges
  admin/admin-settings-changed-listener.php
  admin/class-admin-init.php
  admin/class-config.php
  admin/class-plugin-compatibility.php
  admin/class-yoast-input-validation.php
  admin/class-yoast-notification.php
  admin/config-ui/fields/class-field-success-message.php
  admin/import/plugins/class-import-wpseo.php
  admin/notifiers/class-configuration-notifier.php
  admin/tracking/class-tracking-plugin-data.php
  admin/tracking/class-tracking.php
  admin/views/class-yoast-input-select.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  config/php-codeshift/remove-vendor-prefixing-array-key-visitor.php
  config/php-codeshift/remove-vendor-prefixing-codemod.php
  config/php-codeshift/remove-vendor-prefixing-comment-visitor.php
  config/php-codeshift/remove-vendor-prefixing-visitor.php
  deprecated/class-yoast-form-fieldset.php
  inc/class-structured-data-blocks.php
  inc/health-check.php
  inc/options/class-wpseo-option.php
  inc/sitemaps/class-sitemaps.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
  integration-tests/config-ui/test-class-configuration-endpoint.php
  integration-tests/doubles/frontend-double.php
  src/orm/yoast-model.php
  tests/admin/input-validation-test.php
  tests/doubles/inc/options/option-social-double.php
  tests/inc/class-wpseo-image-utils-test.php
  tests/inc/language-utils-test.php
  tests/inc/options/option-social-test.php
Labels: yoast cs/qa

#13572 Add logic to remove defaults from options, remove Google+ defaults
  inc/class-upgrade.php
Labels: changelog: bugfix

#13589 Add search result page and error page presentations with robots output
  src/integrations/front-end-integration.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-error-page-presentation.php
  src/presentations/indexable-search-result-page-presentation.php
  tests/presentations/indexable-error-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-error-page-presentation/robots-test.php
  tests/presentations/indexable-search-result-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-search-result-page-presentation/robots-test.php
Labels: changelog: non-user-facing

#13274 Update URLs to ping Google and Bing
  inc/sitemaps/class-sitemaps.php
Labels: community-patch

#13597 Fix nested paragraph in description field
  admin/metabox/class-metabox.php
Labels: changelog: bugfix

#13604 Implements the OpenGraph site name meta tag via the front-end integration
  src/context/meta-tags-context.php
  src/helpers/robots-helper.php
  src/helpers/site-helper.php
  src/helpers/taxonomy-helper.php
  src/integrations/front-end-integration.php
  src/presentations/indexable-presentation.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/open-graph/site-name-presenter.php
  src/presenters/open-graph/title-presenter.php
  src/presenters/twitter/card-presenter.php
  src/presenters/twitter/title-presenter.php
  tests/_mocks/meta-tags-context.php
  tests/presentations/indexable-presentation/og-site-name-test.php
  tests/presentations/indexable-presentation/presentation-instance-builder.php
  tests/presenters/open-graph/image-presenter-test.php
  tests/presenters/open-graph/site-name-presenter-test.php
Labels: changelog: non-user-facing

#13601 Added presenter and presentation for single page twitter creator metatag
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/twitter/creator-presenter.php
  tests/presentations/indexable-post-type-presentation/twitter-creator-test.php
  tests/presenters/twitter/creator-presenter-test.php
Labels: changelog: other

#13606 Return attachment url instead of entire attachment array
  src/helpers/image-helper.php
  src/helpers/open-graph/image-helper.php
  src/presentations/indexable-presentation.php
  src/presenters/open-graph/image-presenter.php
  tests/presentations/indexable-presentation-test.php
  tests/presenters/open-graph/image-presenter-test.php
Labels: changelog: non-user-facing

#13611 Add schema and google keyword to Gutenblocks
  js/src/structured-data-blocks/faq/block.js
  js/src/structured-data-blocks/how-to/block.js
Labels: changelog: enhancement

#13614 Added tests for open graph title presenter
  tests/presenters/open-graph/title-presenter-test.php
Labels: changelog: non-user-facing

#13613 Added open graph type presenter
  src/presenters/open-graph/type-presenter.php
  tests/presenters/open-graph/type-presenter-test.php
Labels: changelog: non-user-facing

#13615 Add missing presentation and presenter tests
  tests/presentations/indexable-presentation/twitter-creator-test.php
  tests/presenters/debug/marker-close-presenter-test.php
  tests/presenters/debug/marker-open-presenter-test.php
Labels: changelog: non-user-facing

#13562 Add a rankmath importer
  admin/import/plugins/class-import-rankmath.php
  admin/import/plugins/class-importers.php
  integration-tests/admin/import/test-class-import-rankmath.php
  integration-tests/admin/import/test-class-importers.php
Labels: changelog: enhancement

#13621 Add symfony config dev dependency
  composer.json
  composer.lock
Labels: changelog: non-user-facing

#13581 CS/QA: use `wp_strip_all_tags()` [2]
  frontend/schema/class-schema-faq-questions.php
  frontend/schema/class-schema-howto.php
  tests/TestCase.php
Labels: yoast cs/qa

#13578 Bug fix: use the correct function
  tests/bootstrap.php
Labels: yoast cs/qa

#13579 PHPCompatibility fix: pass encoding to htmlspecialchars() et al functions
  inc/options/class-wpseo-option.php
  tests/TestCase.php
Labels: yoast cs/qa

#13574 Travis: run PHP 7.4 against WP master
  .travis.yml
Labels: yoast cs/qa

#13336 Output escaping partial alerts template
  admin/class-yoast-notification.php
  admin/views/class-yoast-input-select.php
  admin/views/partial-alerts-template.php
  deprecated/class-yoast-form-fieldset.php
Labels: changelog: non-user-facing

#13330 Escape output in paper-collapsible.php
  admin/views/paper-collapsible.php
  inc/class-wpseo-utils.php
Labels: changelog: non-user-facing

#13629 Revert the escaping of content collapsible paper because it stripped too much
  admin/views/paper-collapsible.php
Labels: changelog: non-user-facing

#13605 Use inline-block to display ok checkmark
  css/src/yst_plugin_tools.scss
Labels: changelog: non-user-facing

#13628 Add fallback for getting the post id
  admin/metabox/class-metabox.php
Labels: changelog: bugfix, type: bug

#13618 Add the last twitter title presenters
  src/builders/indexable-author-builder.php
  src/builders/indexable-term-builder.php
  src/helpers/current-page-helper.php
  src/helpers/options-helper.php
  src/integrations/front-end-integration.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-date-archive-presentation.php
  src/presentations/indexable-search-result-page-presentation.php
  src/repositories/indexable-repository.php
  tests/presentations/indexable-author-archive-presentation/title-test.php
  tests/presentations/indexable-author-archive-presentation/twitter-title-test.php
  tests/presentations/indexable-date-archive-presentation/robots-test.php
  tests/presentations/indexable-date-archive-presentation/title-test.php
  tests/presentations/indexable-date-archive-presentation/twitter-title-test.php
  tests/presentations/indexable-search-result-page-presentation/title-test.php
  tests/presentations/indexable-search-result-page-presentation/twitter-title-test.php
Labels: changelog: non-user-facing

#13633 Reduce tracking
  admin/tracking/class-tracking-plugin-data.php
  admin/tracking/class-tracking-settings-data.php
Labels: changelog: non-user-facing

#13642 Use get_core_updates to get the latest major WordPress version
  admin/class-admin-init.php
Labels: regression

#13546 Add method to retrieve posts with outdated words
  migrations/20190813111111_WpYoastProminentWordIndexableColumns.php
  src/repositories/indexable-repository.php
  tests/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing, component: innovation, component: internal links

#13641 Open graph article publisher and author
  src/context/meta-tags-context.php
  src/helpers/user-helper.php
  src/presentations/indexable-post-type-presentation.php
  src/presenters/open-graph/article-author-presenter.php
  src/presenters/open-graph/article-publisher-presenter.php
  tests/presentations/indexable-post-type-presentation/og-article-author-test.php
  tests/presentations/indexable-post-type-presentation/og-article-publisher-test.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
  tests/presenters/open-graph/article-author-presenter-test.php
  tests/presenters/open-graph/article-publisher-presenter-test.php
Labels: changelog: bugfix

#13635 Change Twitter settings page
  admin/views/tabs/social/twitterbox.php
Labels: community-patch

#13647 Increase minimally required PHP version
  readme.txt
Labels: changelog: other

#13640 OG description presenter with post type presentation
  src/helpers/post-type-helper.php
  src/presentations/indexable-post-type-presentation.php
  src/presenters/open-graph/description-presenter.php
  tests/presentations/indexable-post-type-presentation/og-description-test.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-presentation/title-test.php
  tests/presentations/indexable-post-type-presentation/twitter-description-test.php
  tests/presenters/open-graph/description-presenter-test.php
Labels: changelog: non-user-facing

#13638 Organization of image helpers
  src/builders/indexable-post-builder.php
  src/helpers/image-helper.php
  src/helpers/open-graph/image-helper.php
  src/values/images.php
  tests/helpers/image-helper-test.php
  tests/helpers/open-graph/image-helper-test.php
  tests/helpers/twitter/image-helper-test.php
Labels: changelog: non-user-facing

#13648 Added "Strong" parameter to Light Switch component
  admin/class-yoast-form.php
  admin/views/tabs/social/twitterbox.php
  css/src/toggle-switch.scss
Labels: UI change, changelog: enhancement

#13656 Use PHP_EOL instead of \n
  src/integrations/front-end-integration.php
  src/presenters/debug/marker-close-presenter.php
  src/presenters/schema-presenter.php
Labels: changelog: non-user-facing

#13653 Meta description for author archive
  src/helpers/options-helper.php
  src/presentations/indexable-author-archive-presentation.php
  tests/presentations/indexable-author-archive-presentation/meta-description-test.php
Labels: changelog: non-user-facing

#13652 Open graph article modified and publish time presenters and presentations
  src/helpers/post-type-helper.php
  src/integrations/front-end-integration.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/open-graph/article-modified-time-presenter.php
  src/presenters/open-graph/article-published-time-presenter.php
  tests/presentations/indexable-post-type-presentation/og-article-author-test.php
  tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php
  tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php
  tests/presentations/indexable-post-type-presentation/og-article-publisher-test.php
  tests/presentations/indexable-post-type-presentation/og-description-test.php
  tests/presentations/indexable-presentation/og-article-published-time-test.php
  tests/presentations/indexable-presentation/presentation-instance-builder.php
  tests/presenters/open-graph/article-author-presenter-test.php
  tests/presenters/open-graph/article-modified-time-presenter-test.php
  tests/presenters/open-graph/article-published-time-presenter-test.php
  tests/presenters/open-graph/article-publisher-presenter-test.php
  tests/presenters/open-graph/description-presenter-test.php
Labels: changelog: non-user-facing

#13662 Twitter site
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/twitter/site-presenter.php
  tests/presentations/indexable-author-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-date-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-error-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-home-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
  tests/presentations/indexable-presentation/presentation-instance-builder.php
  tests/presentations/indexable-presentation/robots-test.php
  tests/presentations/indexable-presentation/twitter-image-test.php
  tests/presentations/indexable-presentation/twitter-site-test.php
  tests/presentations/indexable-search-result-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-term-archive-presentation/presentation-instance-builder.php
  tests/presenters/twitter/creator-presenter-test.php
  tests/presenters/twitter/twitter-site-presenter-test.php
Labels: changelog: non-user-facing

#13660 Show installation default title when SEO title is not set for posts
  src/presentations/indexable-post-type-presentation.php
  tests/presentations/indexable-post-type-presentation/title-test.php
Labels: changelog: bugfix

#13577 [Tests] Remove unused duplicate file
  tests/doubles/class-my-yoast-proxy.php
Labels: yoast cs/qa

#13664 Don't check for active local license but for active local plugin
  admin/class-config.php
Labels: changelog: non-user-facing

#13667 Add short descriptions and cover tags
  integration-tests/capabilities/test-class-capability-manager-factory.php
  integration-tests/capabilities/test-class-capability-manager.php
  integration-tests/doubles/class-admin-bar-menu-double.php
  integration-tests/doubles/class-admin-editor-specific-replace-vars-double.php
  integration-tests/doubles/class-indexable-double.php
  integration-tests/doubles/class-indexable-post-provider-double.php
  integration-tests/doubles/class-indexable-term-provider-double.php
  integration-tests/doubles/class-my-yoast-api-request-double.php
  integration-tests/doubles/class-opengraph-image-double.php
  integration-tests/doubles/class-post-type-archive-notification-handler-double.php
  integration-tests/doubles/class-sitemap-image-parser-double.php
  integration-tests/doubles/class-term-indexable-double.php
  integration-tests/doubles/class-upgrade-double.php
  integration-tests/doubles/class-wpseo-content-images-double.php
  integration-tests/doubles/class-wpseo-post-type-sitemap-provider-double.php
  integration-tests/doubles/class_indexable_service_double.php
Labels: changelog: non-user-facing

#13668 Add doc comments
  integration-tests/admin/links/test-class-link-utils.php
  integration-tests/capabilities/test-class-register-capabilities.php
  integration-tests/doubles/wpseo-config-field-double.php
  integration-tests/doubles/wpseo-configuration-service-mock.php
  integration-tests/doubles/wpseo-meta-columns-double.php
  integration-tests/doubles/wpseo-onpage-double.php
  integration-tests/doubles/wpseo-wp-rest-server-mock.php
Labels: changelog: non-user-facing

#13658 Add date helper to wrap mysql2date
  src/generators/schema/article.php
  src/generators/schema/webpage.php
  src/helpers/date-helper.php
  src/presentations/indexable-post-type-presentation.php
  tests/generators/schema/article-test.php
  tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php
  tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
Labels: changelog: non-user-facing

#13630 Remove indexables feature flag conditional
  src/conditionals/indexables-feature-flag-conditional.php
  src/initializers/migration-runner.php
  src/integrations/front-end-integration.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-home-page-watcher.php
  src/integrations/watchers/indexable-post-type-archive-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  tests/database/migration-runner-test.php
  tests/integrations/watchers/indexable-author-watcher-test.php
  tests/integrations/watchers/indexable-home-page-watcher-test.php
  tests/integrations/watchers/indexable-post-type-archive-watcher-test.php
  tests/integrations/watchers/indexable-post-watcher-test.php
  tests/integrations/watchers/indexable-term-watcher-test.php
Labels: changelog: non-user-facing, component: innovation

#13673 Check if there are installed addons first before doing things
  inc/class-addon-manager.php
  integration-tests/inc/test-class-addon-manager.php
  tests/doubles/inc/addon-manager-double.php
  tests/inc/addon-manager-test.php
Labels: changelog: non-user-facing

#13675 Remove the last traces of the indexables feature flag
  src/integrations/watchers/indexable-date-archive-watcher.php
  src/integrations/watchers/indexable-system-page-watcher.php
  tests/integrations/watchers/indexable-date-archive-watcher-test.php
  tests/integrations/watchers/indexable-system-page-watcher-test.php
Labels: changelog: non-user-facing, component: innovation

#13669 Add short descriptions to the tests.
  integration-tests/config-ui/components/test-class-factory-post-type.php
  integration-tests/config-ui/fields/test-class-config-field-choice.php
  integration-tests/config-ui/fields/test-class-config-field.php
  integration-tests/config-ui/test-class-configuration-components.php
  integration-tests/config-ui/test-class-configuration-endpoint.php
  integration-tests/config-ui/test-class-configuration-options-adapter.php
  integration-tests/config-ui/test-class-configuration-storage.php
  integration-tests/config-ui/test-class-configuration-structure.php
  tests/admin/metabox/metabox-editor-test.php
  tests/admin/myyoast-proxy-test.php
  tests/admin/roles/register-roles-test.php
  tests/admin/roles/role-manager-factory-test.php
  tests/admin/roles/role-manager-test.php
  tests/database/migration-runner-test.php
  tests/frontend/schema/mainimage-test.php
  tests/frontend/schema/schema-how-to-test.php
  tests/frontend/schema/schema-utils-test.php
  tests/frontend/schema/schema-webpage-test.php
  tests/oauth/client-test.php
Labels: changelog: non-user-facing

#13679 Adjust custom form controls styling for WP 5.3.
  css/src/admin-global.scss
  css/src/yst_plugin_tools.scss
Labels: UI change, changelog: enhancement

#13632 Deprecation of the Google Search Console code
  admin/ajax.php
  admin/class-admin-init.php
  admin/class-admin.php
  admin/config-ui/class-configuration-components.php
  admin/config-ui/class-configuration-page.php
  admin/config-ui/class-configuration-storage.php
  admin/config-ui/class-configuration-structure.php
  admin/config-ui/components/class-component-connect-google-search-console.php
  admin/google_search_console/class-gsc-ajax.php
  admin/google_search_console/class-gsc-bulk-action.php
  admin/google_search_console/class-gsc-category-filters.php
  admin/google_search_console/class-gsc-config.php
  admin/google_search_console/class-gsc-count.php
  admin/google_search_console/class-gsc-issue.php
  admin/google_search_console/class-gsc-issues.php
  admin/google_search_console/class-gsc-mapper.php
  admin/google_search_console/class-gsc-marker.php
  admin/google_search_console/class-gsc-platform-tabs.php
  admin/google_search_console/class-gsc-service.php
  admin/google_search_console/class-gsc-settings.php
  admin/google_search_console/class-gsc-table.php
  admin/google_search_console/class-gsc.php
  admin/google_search_console/views/gsc-display.php
  admin/menu/class-admin-menu.php
  composer.json
  composer.lock
  css/src/yoast-components.scss
  css/src/yst_plugin_tools.scss
  deprecated/admin/config-ui/components/class-component-connect-google-search-console.php
  deprecated/admin/config-ui/fields/class-field-connect-google-search-console.php
  deprecated/admin/config-ui/fields/class-field-google-search-console-intro.php
  deprecated/admin/google-search-console/class-gsc-ajax.php
  deprecated/admin/google-search-console/class-gsc-bulk-action.php
  deprecated/admin/google-search-console/class-gsc-category-filters.php
  deprecated/admin/google-search-console/class-gsc-config.php
  deprecated/admin/google-search-console/class-gsc-count.php
  deprecated/admin/google-search-console/class-gsc-issue.php
  deprecated/admin/google-search-console/class-gsc-issues.php
  deprecated/admin/google-search-console/class-gsc-mapper.php
  deprecated/admin/google-search-console/class-gsc-marker.php
  deprecated/admin/google-search-console/class-gsc-modal.php
  deprecated/admin/google-search-console/class-gsc-platform-tabs.php
  deprecated/admin/google-search-console/class-gsc-service.php
  deprecated/admin/google-search-console/class-gsc-settings.php
  deprecated/admin/google-search-console/class-gsc-table.php
  grunt/config/shell.js
  integration-tests/config-ui/components/test-class-component-connect-gsc.php
  integration-tests/config-ui/test-class-configuration-structure.php
  integration-tests/doubles/wpseo-config-component-connect-google-search-console-mock.php
  js/src/components/ConnectGoogleSearchConsole.js
  js/src/components/modals/RedirectUpsell.js
  js/src/configuration-wizard.js
  js/src/wp-seo-admin-gsc.js
  js/src/wp-seo-admin.js
  tests/admin/admin-features-test.php
Labels: changelog: non-user-facing

#13654 Canonical presentations
  src/builders/indexable-post-builder.php
  src/helpers/rel-adjacent-helper.php
  src/helpers/url-helper.php
  src/integrations/front-end-integration.php
  src/models/indexable.php
  src/presentations/indexable-date-archive-presentation.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/canonical-presenter.php
  src/presenters/open-graph/url-presenter.php
  src/presenters/rel-next-presenter.php
  src/presenters/rel-prev-presenter.php
  src/values/images.php
  src/wrappers/wp-rewrite-wrapper.php
  tests/TestCase.php
  tests/_mocks/indexable.php
  tests/builders/indexable-post-builder-test.php
  tests/helpers/rel-adjacent-helper-test.php
  tests/helpers/url-helper-test.php
  tests/presentations/indexable-author-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-date-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-error-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-home-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-presentation/canonical-test.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-presentation/rel-next-test.php
  tests/presentations/indexable-post-type-presentation/rel-prev-test.php
  tests/presentations/indexable-presentation/presentation-instance-builder.php
  tests/presentations/indexable-presentation/presentation-instance-generator-builder.php
  tests/presentations/indexable-presentation/rel-next-test.php
  tests/presentations/indexable-presentation/rel-prev-test.php
  tests/presentations/indexable-presentation/robots-test.php
  tests/presentations/indexable-presentation/twitter-site-test.php
  tests/presentations/indexable-search-result-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-term-archive-presentation/presentation-instance-builder.php
  tests/presentations/presentation-instance-dependencies.php
  tests/presenters/canonical-presenter-test.php
  tests/presenters/rel-next-presenter-test.php
  tests/presenters/rel-prev-presenter-test.php
Labels: changelog: other, component: innovation

#13676 Added ms_is_switched check to terms
  admin/taxonomy/class-taxonomy.php
Labels: changelog: bugfix

#13637 Improve the import and export settings textarea labels and descriptions.
  admin/class-export.php
  admin/views/tabs/tool/wpseo-import.php
  admin/views/tool-file-editor.php
  css/src/yst_plugin_tools.scss
Labels: UI change, changelog: enhancement

#13693 Adds logic for having the values in case of noindex and nosnippet
  src/helpers/robots-helper.php
  tests/helpers/robots-helper-test.php
Labels: changelog: non-user-facing

#13685 Add image fallbacks
  src/builders/indexable-author-builder.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-social-image-trait.php
  src/builders/indexable-term-builder.php
  src/helpers/image-helper.php
  src/helpers/twitter/image-helper.php
  tests/builders/indexable-author-builder-test.php
  tests/builders/indexable-post-builder-test.php
  tests/builders/indexable-term-builder-test.php
Labels: changelog: enhancement

#13696 Adjust the Configuration Wizard user selector styling for WP 5.3.
  js/src/components/WordPressUserSelector.js
Labels: changelog: non-user-facing

#13697 Fix fatal by adding multisite check
  admin/taxonomy/class-taxonomy.php
Labels: changelog: non-user-facing

#13683 Remove feature flag usage
  integration-tests/frontend/test-class-wpseo-frontend.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#13688 Social conditionals
  src/integrations/front-end-integration.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/presentations/indexable-presentation/twitter-description-test.php
  tests/presentations/indexable-presentation/twitter-title-test.php
  tests/presentations/indexable-term-archive-presentation/og-description-test.php
  tests/presentations/indexable-term-archive-presentation/twitter-description-test.php
Labels: changelog: non-user-facing

#13706 Add premium/src folder to rules in premium-check-cs script
  composer.json
Labels: changelog: non-user-facing

#13692 Update snippet preview image
  .travis.yml
  js/src/analysis/classicEditorData.js
  js/src/analysis/data.js
  js/src/containers/SnippetEditor.js
  js/tests/data.test.js
Labels: changelog: non-user-facing

#13709 Fixes the indexable repository tests.
  tests/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing, component: tests

#13711 Adds missing docs
  integration-tests/sitemaps/test-class-wpseo-sitemaps-renderer.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-router.php
  integration-tests/sitemaps/test-class-wpseo-taxonomy-sitemap-provider.php
  integration-tests/statistics/test-class-statistics-service.php
  integration-tests/taxonomy/test-class-taxonomy-fields.php
  integration-tests/taxonomy/test-class-taxonomy-social-fields.php
  src/conditionals/admin-conditional.php
  src/conditionals/feature-flag-conditional.php
  src/database/database-setup.php
  src/database/migration-runner.php
  src/database/ruckusing-framework.php
  src/loggers/logger.php
  src/loggers/migration-logger.php
  src/orm/yoast-orm-wrapper.php
  tests/admin/admin-features-test.php
  tests/admin/myyoast-proxy-test.php
Labels: changelog: non-user-facing, component: documentation, component: tests

#13713 Improve doc comments
  admin/class-yoast-notification-center.php
  integration-tests/framework/class-wpseo-unit-test-case.php
  integration-tests/inc/test-class-wpseo-upgrade-history.php
  integration-tests/notifications/test-class-yoast-notification-center.php
  integration-tests/recalculate/test-class-recalculate-posts.php
  tests/inc/addon-manager-test.php
Labels: changelog: non-user-facing

#13715 Fix PHPCS doc comments for 3 files
  integration-tests/formatter/test-term-metabox-formatter.php
  integration-tests/onpage/test-class-ryte-service.php
  integration-tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
Labels: changelog: non-user-facing

#13703 Removal of debug mark
  frontend/class-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
Labels: changelog: non-user-facing

#13689 Add method for register option
  inc/options/class-wpseo-option.php
  inc/options/class-wpseo-options.php
Labels: changelog: non-user-facing

#13702 Frontend metadesc cleanup
  frontend/class-frontend.php
  frontend/class-opengraph.php
  frontend/class-twitter.php
  frontend/schema/class-schema-context.php
  integration-tests/frontend/test-class-opengraph.php
  integration-tests/frontend/test-class-twitter.php
  integration-tests/frontend/test-class-wpseo-frontend-woocommerce-shop.php
Labels: changelog: non-user-facing, component: innovation

#13719 Removal of Twitter title from class Twitter
  frontend/class-twitter.php
  integration-tests/doubles/class-expose-wpseo-twitter.php
  integration-tests/frontend/test-class-twitter.php
Labels: changelog: non-user-facing

#13725 Remove the functionality related to Twitter card and Twitter image
  frontend/class-twitter.php
  integration-tests/frontend/test-class-twitter.php
Labels: changelog: non-user-facing

#13723 Fix the height of select2 inputs when zooming in in WP 5.3
  css/src/admin-global.scss
Labels: changelog: non-user-facing

#13724 Removal of title
  frontend/class-frontend.php
  frontend/class-opengraph.php
  integration-tests/doubles/frontend-double.php
  integration-tests/frontend/test-class-opengraph.php
  integration-tests/frontend/test-class-wpseo-frontend-title.php
  integration-tests/frontend/test-class-wpseo-frontend-woocommerce-shop.php
Labels: changelog: non-user-facing

#13727 Removal of canonical and rel next/prev
  frontend/class-frontend.php
  frontend/class-opengraph.php
  integration-tests/frontend/test-class-opengraph.php
  integration-tests/frontend/test-class-wpseo-frontend.php
Labels: changelog: non-user-facing

#13716 Fix snippet preview image bug.
  js/src/analysis/classicEditorData.js
Labels: changelog: non-user-facing

#13731 Remove the functionality regarding Twitter site
  frontend/class-twitter.php
  integration-tests/frontend/test-class-twitter.php
Labels: changelog: non-user-facing

#13718 Deprecate theme title hooks
  frontend/class-frontend.php
  src/integrations/front-end/theme-titles.php
Labels: changelog: non-user-facing

#13730 Add webmaster tools meta
  frontend/class-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
  src/helpers/current-page-helper.php
  src/integrations/front-end/webmaster-tools-meta.php
  tests/integrations/front-end/webmaster-tools-meta-test.php
Labels: changelog: non-user-facing, component: innovation

#13736 Implement Black Friday 2019 banner
  admin/class-admin-banner.php
  admin/class-admin.php
  css/src/admin-global.scss
  images/crosshair.svg
  images/yoasie_banner_bf.gif
  inc/options/class-wpseo-option-wpseo.php
Labels: changelog: non-user-facing

#13738 Call the method the right way
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#13740 Bump package dependencies for 12.4
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13741 Fix banner for mobile
  css/src/admin-global.scss
Labels: changelog: non-user-facing

#13743 Bump package dependencies for 12.5-RC1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13734 Remove the functionality and tests regarding Twitter creator
  frontend/class-twitter.php
  integration-tests/doubles/class-expose-wpseo-twitter.php
  integration-tests/frontend/test-class-twitter.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#13737 Disables the forcerewritetitle option
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#13749 Removed WordPress update notice
  admin/class-admin-init.php
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#13748 Set tested up to to 5.3, minimum wp to 5.2 and PHP to 5.6.20
  readme.txt
Labels: changelog: other

#13754 Add a migration for prominent word indexable column
  migrations/20191029111111_WpYoastProminentWordIndexableColumn.php
  src/models/indexable.php
Labels: changelog: non-user-facing

#13756 Deprecating og description
  frontend/class-opengraph.php
  integration-tests/frontend/test-class-opengraph.php
Labels: changelog: non-user-facing

#13755 Embed rssfooter integration
  frontend/class-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
  src/integrations/front-end/rss-footer-embed.php
  tests/integrations/front-end/rss-footer-embed-test.php
Labels: changelog: non-user-facing

#13761 Add indexing controls integration
  frontend/class-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
  src/integrations/front-end/indexing-controls.php
  tests/integrations/front-end/indexing-controls-test.php
Labels: changelog: non-user-facing

#13712 Added various missing short descriptions to test files
  integration-tests/formatter/test-post-metabox-formatter.php
  integration-tests/frontend/test-class-front-end-page-type.php
  integration-tests/frontend/test-class-woocommerce-shop-page.php
  integration-tests/sitemaps/test-class-wpseo-sitemap-image-parser.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-validator.php
Labels: changelog: non-user-facing
