Repository Yoast/wordpress-seo, pull requests merged in 2019-04, with the labels that each got.

#12454 Move the CornerstoneToggle to Wordpress-seo instead of Yoast-components
  js/src/components/CollapsibleCornerstone.js
  js/src/components/CornerstoneToggle.js
  js/tests/components/CornerstoneToggleTest.js
  js/tests/components/__snapshots__/CornerstoneToggleTest.js.snap
Labels: blocked

#12481 Test documentation: use correct @expectedException annotations
  tests/admin/test-class-my-yoast-proxy.php
Labels: yoast cs/qa

#12580 CS: clean up after merges
  admin/class-extensions.php
  admin/class-yoast-network-admin.php
  admin/views/licenses.php
  inc/class-wpseo-shortlinker.php
  tests/doubles/class-yoast-notification-center-double.php
  tests/inc/test-class-addon-manager.php
  tests/notifications/test-class-yoast-notification-center.php
Labels: yoast cs/qa

#12583 Documentation: use @see tag
  tests/test-class-wpseo-meta.php
Labels: yoast cs/qa

#12584 Documentation: some method docblock format improvements
  inc/sitemaps/class-sitemap-cache-data.php
  src/config/admin.php
Labels: yoast cs/qa

#12585 Documentation: don't use docblocks for inline comments
  inc/options/class-wpseo-option-social.php
  tests/admin/test-class-database-proxy.php
Labels: yoast cs/qa

#12581 QA: don't use array_merge when its not needed
  admin/views/licenses.php
Labels: yoast cs/qa

#12681 Bump yoast components to v. 4.23.1
  package.json
  yarn.lock
Labels: code-review lingo

#12646 Add upsell for Local SEO to search appearance
  .babelrc
  admin/class-config.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  grunt/config/imagemin.js
  images/brushstroke_background.svg
  images/local_assistant.svg
  js/src/components/LocalSEOUpsell.js
  js/src/search-appearance.js
  js/tests/components/LocalSEOUpsell.test.js
  js/tests/components/UpsellBox.test.js
  js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/components/__snapshots__/UpsellBox.test.js.snap
  js/tests/setupTests.js
  package.json
  yarn.lock
Labels: UI change

#12716 Use full size instead of thumbnail image
  frontend/schema/class-schema-image.php
Labels: regression

#12511 Introduces method get_post_statuses in sitemaps
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-sitemaps.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
Labels: community-patch

#12424 Remove target="_blank" from JS components and use makeOutboundLink instead
  admin/config-ui/components/class-component-suggestions.php
  grunt/config/eslint.js
  js/src/components/RaisedDefaultButton.js
  js/src/components/RaisedURLNewWindowButton.js
  js/src/configuration-wizard.js
  js/src/wp-seo-dashboard-widget.js
Labels: a11y-has-patch

#12742 Fix copy-pasta in constructor comment
  frontend/schema/class-schema-person.php
Labels: community-patch

#12722 Fix search-appearance React error
  js/src/components/WordPressUserSelector.js
  js/src/components/WordPressUserSelectorOnboardingWizard.js
  js/src/redux/utils/configureEnhancers.js
  package.json
  yarn.lock
Labels: regression

#12710 CS: clean up after merges
  admin/class-admin.php
  admin/class-config.php
  admin/class-schema-person-upgrade-notification.php
  admin/class-yoast-form.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/social/accounts.php
  frontend/class-frontend.php
  frontend/schema/class-schema-author.php
  frontend/schema/class-schema-breadcrumb.php
  frontend/schema/class-schema-image.php
  frontend/schema/class-schema.php
  frontend/schema/interface-wpseo-graph-piece.php
  inc/class-addon-manager.php
  inc/class-wpseo-utils.php
  tests/admin/test-class-schema-person-upgrade-notification.php
Labels: yoast cs/qa

#12685 Stitch structured data blocks into graph
  frontend/schema/class-schema-article.php
  inc/class-wpseo-utils.php
  inc/structured-data-blocks/class-faq-block.php
  inc/structured-data-blocks/class-how-to-block.php
  tests/inc/structured-data-blocks/test-class-faq-block.php
  tests/inc/structured-data-blocks/test-class-how-to-block.php
Labels: component: schema (JSON+LD)

#12209 Snippet preview modal background color
  js/src/components/SnippetPreviewModal.js
Labels: UI change, has patch

#12098 Make the plugin sidebar title depend on the plugin version.
  admin/formatter/class-metabox-formatter.php
  js/src/edit.js
Labels: UI change

#12712 Documentation: use multi-line comment format for long inline comments
  inc/options/class-wpseo-option.php
  tests/admin/test-class-database-proxy.php
  tests/frontend/test-class-wpseo-frontend.php
  tests/frontend/test-class-wpseo-opengraph-image.php
  tests/sitemaps/test-class-wpseo-sitemaps-cache.php
  tests/test-class-rewrite.php
Labels: yoast cs/qa

#12582 Update .gitattributes
  .gitattributes
Labels: yoast cs/qa

#12713 Documentation: improve miscellaneous tag alignment and grouping
  admin/capabilities/class-capability-manager-integration.php
  frontend/class-opengraph.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option-wpseo.php
  inc/wpseo-functions.php
  src/models/primary-term.php
  tests/admin/services/test-class-endpoint-indexable.php
  tests/admin/services/test-class-indexable-post-provider.php
  tests/admin/test-class-admin-recommended-replace-vars.php
  tests/admin/test-class-yoast-network-admin.php
  tests/config-ui/test-class-configuration-options-adapter.php
  tests/inc/indexables/test-class-indexable.php
  tests/inc/indexables/test-class-post-indexable.php
  tests/inc/indexables/test-class-term-indexable.php
  tests/inc/options/test-class-wpseo-option-wpseo.php
  tests/inc/options/test-class-wpseo-option.php
  tests/inc/test-class-addon-manager.php
  tests/sitemaps/test-class-wpseo-sitemaps-router.php
  tests/test-class-admin-asset-manager.php
  tests/test-class-wpseo-meta-columns.php
  tests/test-class-wpseo-utils.php
Labels: yoast cs/qa

#12714 Documentation: improve property docblock formatting
  inc/class-wpseo-meta.php
Labels: yoast cs/qa

#12715 Test documentation: add some missing @covers tags
  tests/admin/test-class-admin-editor-specific-replace-vars.php
  tests/test-class-wpseo-rank.php
Labels: yoast cs/qa

#12711 CS: Move multi-line function call out of embedded PHP
  admin/config-ui/class-configuration-page.php
  admin/views/js-templates-primary-term.php
  admin/views/licenses.php
Labels: yoast cs/qa

#12172 Reintroduce wp-sanitize dependency
  admin/class-admin-asset-manager.php
  js/src/helpers/replacementVariableHelpers.js
  js/src/helpers/stripTags.js
Labels: has patch

#12457 Use the `wp_doing_ajax` function instead of constants
  admin/class-admin-init.php
  admin/links/class-link-columns.php
  admin/taxonomy/class-taxonomy-columns.php
  wp-seo-main.php
Labels: has patch

#12795 Fix wrong Pinterest confirmation URL
  admin/views/tabs/social/pinterest.php
Labels: community-patch
