Repository Yoast/wordpress-seo, pull requests merged in 2019-09, with the labels that each got.

#13420 Composer: update PHPCompatibility
  composer.lock
  inc/sitemaps/class-sitemaps-renderer.php
  phpcs.xml.dist
  wp-seo-main.php
Labels: yoast cs/qa

#13437 Update cs dependencies
  composer.lock
  inc/sitemaps/class-sitemaps-renderer.php
  phpcs.xml.dist
  wp-seo-main.php
Labels: changelog: non-user-facing, yoast cs/qa

#13450 Move the WPSEO_Replace_Vars::setup_statics_once call
  inc/class-wpseo-replace-vars.php
  wp-seo-main.php
Labels: changelog: bugfix

#13456 13141 responsive banners sidebar
  admin/views/sidebar.php
  css/src/yst_plugin_tools.scss
  js/src/wp-seo-admin.js
Labels: UI change, changelog: bugfix

#13322 Output escaping: admin/taxonomy/class-taxonomy-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
Labels: changelog: non-user-facing

#13457 Renamed filters to use the old wpseo_ prefix
  frontend/schema/class-schema-context.php
  frontend/schema/class-schema-organization.php
  readme.txt
Labels: changelog: non-user-facing

#13454 Add install and activation endpoints for addons.
  inc/class-addon-manager.php
  inc/class-my-yoast-api-request.php
  inc/class-my-yoast-plugin-installer-skin.php
  inc/endpoints/class-myyoast-download-activate.php
  inc/endpoints/class-myyoast-download-install.php
  integration-tests/inc/test-class-myyoast-api-request.php
  tests/inc/endpoints/myyoast-download-activate-test.php
  tests/inc/endpoints/myyoast-download-install-test.php
  wp-seo-main.php
Labels: changelog: enhancement

#13440 Add alert when organization info is missing
  admin/class-config.php
  admin/config-ui/class-configuration-storage.php
  admin/config-ui/class-configuration-structure.php
  admin/config-ui/fields/class-field-company-info-missing.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  inc/language-utils.php
  js/src/components/CompanyInfoMissing.js
  js/src/components/CompanyInfoMissingOnboardingWizard.js
  js/src/configuration-wizard.js
  js/src/search-appearance.js
  js/tests/components/CompanyInfoMissing.test.js
  js/tests/components/CompanyInfoMissingOnboardingWizard.test.js
  js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap
  js/tests/components/__snapshots__/CompanyInfoMissingOnboardingWizard.test.js.snap
  tests/TestCase.php
  tests/inc/language-utils-test.php
  tests/inc/options/option-social-test.php
Labels: UI change, changelog: enhancement

#13470 Moves the retrieve_enabled_features function out of the area of deprecated functions
  inc/class-wpseo-utils.php
Labels: changelog: non-user-facing

#13486 Bumped yoast javascript packages to the newest version.
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13492 Mention that training is free
  admin/class-help-center.php
  admin/views/sidebar.php
Labels: UI change, changelog: other

#13500 Change configuration wizard for plugin training
  admin/config-ui/class-configuration-structure.php
  admin/config-ui/components/class-component-suggestions.php
  admin/config-ui/fields/class-field-success-message.php
  css/src/yoast-components.scss
  grunt/config/eslint.js
  images/Yoast_Academy_video.png
  integration-tests/config-ui/test-class-configuration-structure.php
  js/src/components/FinalStep.js
Labels: changelog: enhancement

#13404 Add error descriptions to the validated URL fields
  admin/class-yoast-input-validation.php
  inc/options/class-wpseo-option.php
  tests/inc/options/option-social-test.php
Labels: 1, changelog: enhancement, in sprint

#13511 Remove colon from labels in option form fields
  admin/class-yoast-form.php
Labels: UI change, changelog: other

#13502 Include yoast-seo-adminbar style in AMP dev mode
  admin/class-admin-asset-manager.php
Labels: community-patch

#13498 Adds abstract WPSEO Health Check class
  inc/health-check.php
Labels: changelog: non-user-facing

#13495 Plugin installation flow
  admin/class-plugin-installation.php
  admin/views/licenses.php
  css/src/extensions.scss
  inc/class-addon-manager.php
  js/src/components/PluginInstallation.js
  js/src/install-plugin/actions.js
  js/src/install-plugin/reducer.js
  js/src/plugin-installation.js
Labels: UI change

#13497 Deprecate yoast_plugin_compatibility_notification and related code
  admin/class-admin-init.php
  admin/class-plugin-compatibility.php
  inc/class-upgrade.php
  integration-tests/admin/test-class-plugin-compatibility.php
Labels: changelog: other

#13515 Fix the heading structure of the readme
  readme.txt
Labels: changelog: non-user-facing

#13419 Floating Save Changes button for admin pages.
  admin/admin-settings-changed-listener.php
  admin/class-admin-asset-manager.php
  admin/class-admin.php
  admin/class-yoast-form.php
  css/src/admin-global.scss
  js/src/wp-seo-admin.js
Labels: UI change, changelog: enhancement

#13428 Add anonimized settings tracking class
  admin/tracking/class-tracking-plugin-data.php
  admin/tracking/class-tracking-settings-data.php
  admin/tracking/class-tracking.php
Labels: changelog: non-user-facing

#13526 Frontend robots presenter
  config/dependency-injection/container-compiler.php
  config/dependency-injection/services.php
  frontend/class-frontend.php
  src/presenters/abstract-robots-presenter.php
  src/presenters/post-type/robots-presenter.php
  src/presenters/site/open-graph-locale-presenter.php
  src/presenters/site/site-presenter-interface.php
  tests/_mocks/Indexable.php
  tests/presenters/abstract-robots-presenter-test.php
  tests/presenters/post-type/robots-presenter-test.php
Labels: changelog: non-user-facing

#13531 Add clean:artifact after compress:artifact
  grunt/config/aliases.yaml
Labels: changelog: non-user-facing

#13545 Bump packages for 12.2
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13548 Bump packages for RCs 12.3
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13549 Rewritten robots presenter/presentation code, added robots presentati…
  src/helpers/post-type-helper.php
  src/helpers/robots-helper.php
  src/presentations/indexable-home-page-presentation.php
  src/presentations/indexable-post-type-archive-presentation.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/robots-presenter.php
  tests/helpers/robots-helper-test.php
  tests/presentations/indexable-post-type-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-archive-presentation/robots-test.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-presentation/robots-test.php
  tests/presentations/indexable-post-type-presentation/twitter-image-test.php
  tests/presentations/indexable-presentation/robots-test.php
  tests/presenters/abstract-robots-presenter-test.php
  tests/presenters/robots-presenter-test.php
Labels: changelog: non-user-facing
