Repository Yoast/wordpress-seo, pull requests merged in 2019-06, with the labels that each got.

#13061 Uses WPSEO_Utils::home_url() if home page shows latest posts
  inc/sitemaps/class-post-type-sitemap-provider.php
  integration-tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
  tests/doubles/class-wpseo-post-type-sitemap-provider-double.php
Labels: community-patch

#13013 [integration-tests] QA: remove the `checkRequirements()` method
  integration-tests/admin/test-class-yoast-network-admin.php
  integration-tests/capabilities/test-class-register-capabilities.php
  integration-tests/framework/class-wpseo-unit-test-case.php
  integration-tests/inc/options/test-class-wpseo-option-wpseo.php
  integration-tests/inc/options/test-class-wpseo-option.php
  integration-tests/inc/options/test-class-wpseo-options.php
  integration-tests/notifications/test-class-yoast-notification-center.php
Labels: yoast cs/qa

#12988 [src] Documentation: use FQCN in docblocks
  src/config/database-migration.php
  src/config/dependency-management.php
  src/config/plugin.php
  src/config/upgrade.php
  src/exceptions/no-indexable-found.php
  src/formatters/indexable-author-formatter.php
  src/formatters/indexable-post-formatter.php
  src/formatters/indexable-term-formatter.php
  src/loggers/logger.php
  src/models/indexable-meta.php
  src/models/indexable.php
  src/models/primary-term.php
  src/models/seo-meta.php
  src/oauth/client.php
  src/watchers/indexable-author-watcher.php
  src/watchers/indexable-post-watcher.php
  src/watchers/indexable-term-watcher.php
  src/watchers/primary-term-watcher.php
  src/wordpress/integration-group.php
  src/yoast-model.php
  src/yoast-orm-wrapper.php
Labels: yoast cs/qa

#13056 [tests] QA: use global constants with a fully qualified name
  tests/admin/admin-asset-analysis-worker-location-test.php
  tests/config/database-migration-test.php
  tests/config/dependency-management-test.php
  tests/metabox/metabox-editor-test.php
Labels: yoast cs/qa

#13062 Horizontal metabox menu
  admin/class-social-admin.php
  admin/metabox/class-metabox-section-react.php
  admin/metabox/class-metabox-tab-section.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  css/src/metabox.scss
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/wp-seo-metabox.js
Labels: UI change

#13012 [src] QA: consistently use `use` statements
  src/exceptions/no-indexable-found.php
  src/formatters/indexable-post-formatter.php
  src/formatters/indexable-term-formatter.php
  src/loaders/oauth.php
  src/oauth/client.php
  src/watchers/primary-term-watcher.php
Labels: yoast cs/qa

#13107 [tests] QA: use the most specific PHPUnit assertion possible
  tests/admin/admin-asset-analysis-worker-location-test.php
  tests/admin/admin-features-test.php
  tests/config/database-migration-test.php
  tests/config/plugin-test.php
  tests/config/upgrade-test.php
  tests/exceptions/no-indexable-found-test.php
  tests/formatters/indexable-author-formatter-test.php
  tests/formatters/indexable-post-formatter-test.php
  tests/formatters/indexable-term-formatter-test.php
  tests/metabox/metabox-editor-test.php
  tests/oauth/client-test.php
  tests/roles/role-manager-factory-test.php
  tests/roles/role-manager-test.php
  tests/wordpress/integration-group-test.php
Labels: yoast cs/qa

#13116 [src] QA: call global functions using a fully qualified name
  src/config/database-migration.php
  src/config/dependency-management.php
  src/config/plugin.php
  src/config/upgrade.php
  src/exceptions/missing-method.php
  src/formatters/indexable-author-formatter.php
  src/formatters/indexable-post-formatter.php
  src/formatters/indexable-term-formatter.php
  src/loggers/logger.php
  src/models/indexable-meta.php
  src/models/indexable.php
  src/models/primary-term.php
  src/oauth/client.php
  src/watchers/primary-term-watcher.php
  src/wordpress/integration-group.php
  src/yoast-model.php
Labels: yoast cs/qa

#13118 [integration-tests] QA/PHPUnit 7: fix faulty unit test
  integration-tests/frontend/test-class-wpseo-frontend-robots.php
Labels: yoast cs/qa

#13117 [src] CS: order `use` statements alphabetically
  src/config/admin.php
  src/watchers/indexable-author-watcher.php
  src/watchers/indexable-post-watcher.php
  src/watchers/indexable-term-watcher.php
Labels: yoast cs/qa

#13119 [src] QA: use global constants with a fully qualified name
  src/config/database-migration.php
  src/config/dependency-management.php
  src/config/plugin.php
  src/watchers/indexable-author-watcher.php
  src/watchers/indexable-post-watcher.php
  src/watchers/indexable-term-watcher.php
  src/watchers/primary-term-watcher.php
Labels: yoast cs/qa

#12980 Tests: improve test skipping
  integration-tests/notifications/test-class-yoast-notification.php
Labels: yoast cs/qa

#13147 Add readability tab.
  admin/metabox/class-metabox-section-readability.php
  admin/metabox/class-metabox.php
  css/src/metabox.scss
  grunt/config/eslint.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/contentAnalysis/ScoreIconPortal.js
  js/src/components/contentAnalysis/SeoAnalysis.js
Labels: UI change

#13159 Metabox readability tab fixes
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
Labels: UI change

#13114 Change @id for Person globally
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-context.php
  frontend/schema/class-schema-ids.php
  frontend/schema/class-schema-person.php
  frontend/schema/class-schema-utils.php
  tests/frontend/schema/schema-utils-test.php
Labels: 2

#13160 Metabox tabs: responsive, border and other box-shadow
  css/src/metabox.scss
Labels: UI change
