Repository Yoast/wordpress-seo, pull requests merged in 2019-11, with the labels that each got.

#13720 Move wpml filter to integration
  inc/class-wpseo-utils.php
  src/conditionals/wpml-conditional.php
  src/integrations/compatibility/wpml.php
Labels: changelog: non-user-facing

#13764 Improve banners in admin
  admin/class-premium-upsell-admin-block.php
  admin/views/licenses.php
  admin/views/sidebar.php
  css/src/extensions.scss
  css/src/yoastcom/0-settings/_type.scss
  css/src/yoastcom/_promoblock.scss
  css/src/yst_plugin_tools.scss
  images/Local_SEO_Icon.svg
  images/News_SEO_Icon.svg
  images/SEO_for_beginners.svg
  images/Video_SEO_Icon.svg
  images/Woo_SEO_Icon.svg
  images/all-round-SEO.svg
  images/extensions-local.png
  images/extensions-news.png
  images/extensions-premium-ribbon.png
  images/extensions-video.png
  images/extensions-woo.png
  images/local_plugin_assistant.svg
  images/news_plugin_assistant.svg
  images/video_plugin_assistant.svg
  images/woo_plugin_assistant.svg
  images/yoast_seo_for_wp_2.svg
  inc/class-upgrade.php
Labels: UI change, changelog: other

#13760 Moves redirects to integration
  admin/tracking/class-tracking-settings-data.php
  frontend/class-frontend.php
  inc/options/class-wpseo-option-titles.php
  integration-tests/doubles/frontend-double.php
  integration-tests/frontend/test-class-wpseo-frontend-redirects.php
  integration-tests/frontend/test-class-wpseo-frontend.php
  src/helpers/current-page-helper.php
  src/integrations/front-end/redirects.php
  tests/integrations/front-end/redirects-test.php
Labels: changelog: non-user-facing

#13774 Tests: remove incorrect `@covers` tags
  tests/admin/admin-asset-analysis-worker-location-test.php
  tests/admin/admin-features-test.php
  tests/admin/metabox/metabox-test.php
  tests/admin/myyoast-proxy-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13775 Tests: fix incorrect `@covers` tags
  tests/inc/options/option-social-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13778 Documentation: minor formatting tweaks
  admin/class-admin-help-panel.php
  admin/menu/class-replacevar-editor.php
  admin/onpage/class-ryte-service.php
  frontend/class-frontend.php
  inc/class-wpseo-image-utils.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-replace-vars.php
  integration-tests/config-ui/components/test-class-factory-post-type.php
  integration-tests/config-ui/fields/test-class-config-field.php
  integration-tests/config-ui/test-class-configuration-options-adapter.php
  integration-tests/doubles/class-sitemap-image-parser-double.php
  src/builders/indexable-term-builder.php
  tests/admin/roles/role-manager-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13779 CS: clean up after merges
  admin/class-admin-banner.php
  config/composer/actions.php
  deprecated/admin/google-search-console/class-gsc-settings.php
  inc/class-my-yoast-api-request.php
  integration-tests/admin/import/test-class-import-rankmath.php
  tests/TestCase.php
  tests/admin/metabox/metabox-editor-test.php
  tests/inc/addon-manager-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13780 CS: clean up arrays
  tests/inc/addon-manager-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13781 CS/I18n: fix missing text domain in gettext call
  frontend/schema/class-schema-article.php
Labels: changelog: non-user-facing, yoast cs/qa

#13782 CS: clean up after merges / namespaced files
  config/composer/actions.php
  tests/TestCase.php
  tests/admin/admin-features-test.php
  tests/admin/myyoast-proxy-test.php
  tests/doubles/inc/addon-manager-double.php
  tests/inc/addon-manager-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13783 CS/Tests: fix incorrect namespace names
  tests/admin/metabox/metabox-test.php
  tests/admin/roles/register-roles-test.php
  tests/admin/roles/role-manager-factory-test.php
  tests/admin/roles/role-manager-test.php
  tests/admin/watchers/indexable-author-watcher-test.php
  tests/admin/watchers/indexable-post-watcher-test.php
  tests/admin/watchers/indexable-term-watcher-test.php
  tests/inc/class-wpseo-image-utils-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13784 Deprecate og except image
  frontend/class-opengraph.php
  integration-tests/frontend/test-class-opengraph.php
  src/presenters/open-graph/article-author-presenter.php
  src/presenters/open-graph/article-publisher-presenter.php
  src/presenters/open-graph/site-name-presenter.php
Labels: changelog: non-user-facing

#13763 Fixes the dev server with YoastSEO.js
  js/src/wp-seo-analysis-worker.js
Labels: changelog: non-user-facing

#13769 Fix 6 console errors
  js/src/analysis/data.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
Labels: 0.5, changelog: non-user-facing

#13785 Port FB app ID to new format
  src/context/meta-tags-context.php
  src/integrations/front-end-integration.php
  src/presentations/indexable-presentation.php
  src/presenters/open-graph/fb-app-id-presenter.php
  tests/presentations/indexable-presentation/og-fb-app-id-test.php
  tests/presenters/open-graph/fb-app-id-presenter-test.php
Labels: changelog: non-user-facing

#13788 Deprecate og image
  frontend/class-opengraph-image.php
  frontend/class-opengraph.php
  integration-tests/frontend/test-class-opengraph.php
  integration-tests/frontend/test-class-wpseo-opengraph-image.php
  src/presenters/presenter-interface.php
Labels: changelog: non-user-facing

#13772 Make woocommerce integration
  frontend/class-frontend.php
  frontend/class-woocommerce-shop-page.php
  integration-tests/doubles/frontend-double.php
  integration-tests/frontend/test-class-woocommerce-shop-page.php
  integration-tests/frontend/test-class-wpseo-frontend-woocommerce-shop.php
  src/conditionals/woocommerce-conditional.php
  src/integrations/third-party/woocommerce.php
  src/presentations/abstract-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/meta-description-presenter.php
  src/presenters/open-graph/title-presenter.php
  src/presenters/title-presenter.php
  tests/integrations/third-party/woocommerce-test.php
  tests/presenters/open-graph/title-presenter-test.php
  tests/presenters/title-presenter-test.php
Labels: changelog: non-user-facing

#13751 Add description property to website node
  frontend/schema/class-schema-context.php
  frontend/schema/class-schema-website.php
Labels: changelog: enhancement

#13766 Assign jQuery to its $ alias
  js/src/analysis/data.js
  js/tests/data.test.js
  readme.txt
Labels: changelog: non-user-facing

#13786 Make force rewrite title integration
  frontend/class-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
  src/integrations/front-end/force-rewrite-title.php
  tests/integrations/front-end/force-rewrite-title-test.php
Labels: changelog: non-user-facing

#13789 Fixes empty faq and howto errors
  src/generators/schema/faq.php
  src/generators/schema/howto.php
Labels: changelog: bugfix

#13790 Deprecate class opengraph
  deprecated/frontend/class-opengraph-image.php
  deprecated/frontend/class-opengraph.php
  deprecated/frontend/class-twitter.php
  integration-tests/frontend/test-class-opengraph.php
Labels: changelog: non-user-facing

#13796 Fixing a bug where the needle for strpos
  frontend/class-opengraph.php
Labels: community-patch

#13806 Added og:url presentation implementations
  src/helpers/current-page-helper.php
  src/presentations/indexable-date-archive-presentation.php
  src/presentations/indexable-home-page-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-search-result-page-presentation.php
  src/presentations/indexable-static-posts-page-presentation.php
  tests/helpers/current-page-helper-test.php
  tests/presentations/indexable-date-archive-presentation/og-url-test.php
  tests/presentations/indexable-home-page-presentation/og-url-test.php
  tests/presentations/indexable-presentation/og-url-test.php
  tests/presentations/indexable-search-result-page-presentation/og-url-test.php
  tests/presentations/indexable-static-posts-page-presentation/og-url-test.php
Labels: changelog: non-user-facing

#13733 Output optimized breadcrumbs
  config/dependency-injection/services.php
  frontend/class-breadcrumbs.php
  integration-tests/doubles/class-breadcrumbs-double.php
  integration-tests/framework/class-wpseo-unit-test-case-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
  integration-tests/test-class-wpseo-breadcrumbs.php
  phpcs.xml.dist
  src/backwards-compatibility/breadcrumbs.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-post-type-archive-builder.php
  src/builders/indexable-term-builder.php
  src/context/meta-tags-context.php
  src/generators/breadcrumbs-generator.php
  src/generators/schema/breadcrumb.php
  src/helpers/current-page-helper.php
  src/integrations/front-end-integration.php
  src/memoizers/meta-tags-context-memoizer.php
  src/memoizers/presentation-memoizer.php
  src/presentations/indexable-presentation.php
  src/presenters/breadcrumbs-presenter.php
  src/repositories/indexable-repository.php
  tests/builders/indexable-post-builder-test.php
  tests/builders/indexable-term-builder-test.php
  tests/presentations/presentation-instance-dependencies.php
Labels: changelog: non-user-facing, component: innovation

#13835 Fixes the images by running grunt build:images
  images/local_plugin_assistant.svg
  images/news_plugin_assistant.svg
  images/video_plugin_assistant.svg
  images/woo_plugin_assistant.svg
Labels: changelog: non-user-facing

#13818 Remove (site-wide default) None from the meta robots advanced field
  admin/metabox/class-metabox.php
  inc/class-wpseo-meta.php
  integration-tests/test-class-wpseo-meta.php
Labels: 1, UI change, changelog: enhancement

#13842 Bumped monrepo packages for 12.6-RC1.
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13519 Simplify the way of registering upgrade routines
  inc/class-upgrade.php
Labels: 1, changelog: non-user-facing, has patch, technical-debt

#13700 Implement focus style for the notification center buttons
  css/src/alerts.scss
Labels: UI change, changelog: bugfix

#13776 Stop explicit support for PHP < 5.6 / WP < 5.2
  .travis.yml
  composer.json
  composer.lock
  wp-seo-main.php
Labels: changelog: non-user-facing, yoast cs/qa

#13777 Composer: sync with other config files
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#13858 Bump monorepo packages for 12.6 RC2
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13850 13831 pass presentation instance to presenter filters
  src/generators/og-image-generator.php
  src/presentations/indexable-presentation.php
  src/presenters/breadcrumbs-presenter.php
  src/presenters/canonical-presenter.php
  src/presenters/debug/marker-close-presenter.php
  src/presenters/debug/marker-open-presenter.php
  src/presenters/googlebot-presenter.php
  src/presenters/meta-description-presenter.php
  src/presenters/open-graph/article-author-presenter.php
  src/presenters/open-graph/article-modified-time-presenter.php
  src/presenters/open-graph/article-published-time-presenter.php
  src/presenters/open-graph/article-publisher-presenter.php
  src/presenters/open-graph/description-presenter.php
  src/presenters/open-graph/fb-app-id-presenter.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/open-graph/locale-presenter.php
  src/presenters/open-graph/site-name-presenter.php
  src/presenters/open-graph/title-presenter.php
  src/presenters/open-graph/type-presenter.php
  src/presenters/open-graph/url-presenter.php
  src/presenters/rel-next-presenter.php
  src/presenters/rel-prev-presenter.php
  src/presenters/robots-presenter.php
  src/presenters/schema-presenter.php
  src/presenters/title-presenter.php
  src/presenters/twitter/card-presenter.php
  src/presenters/twitter/creator-presenter.php
  src/presenters/twitter/description-presenter.php
  src/presenters/twitter/image-presenter.php
  src/presenters/twitter/site-presenter.php
  src/presenters/twitter/title-presenter.php
  tests/presenters/canonical-presenter-test.php
  tests/presenters/googlebot-presenter-test.php
  tests/presenters/open-graph/article-author-presenter-test.php
  tests/presenters/open-graph/article-publisher-presenter-test.php
  tests/presenters/open-graph/description-presenter-test.php
  tests/presenters/open-graph/image-presenter-test.php
  tests/presenters/open-graph/site-name-presenter-test.php
  tests/presenters/open-graph/title-presenter-test.php
  tests/presenters/open-graph/type-presenter-test.php
  tests/presenters/twitter/title-presenter-test.php
  tests/presenters/twitter/twitter-site-presenter-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#13863 Fixes private CPT in sitemaps
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-sitemaps.php
Labels: community-patch

#13797 Optimize parsing gallery shortcode in sitemaps
  inc/sitemaps/class-sitemap-image-parser.php
Labels: Yoast: SEO Features, community-patch, component: xml sitemap, severity: minor

#13893 Implement HelpScout consent button
  admin/class-admin-asset-manager.php
  admin/class-admin.php
  admin/class-helpscout.php
  js/src/help-scout-beacon.js
  webpack/paths.js
Labels: UI change, changelog: enhancement

#13899 Set node version back to lts
  .travis.yml
Labels: changelog: non-user-facing

#13857 Build/PHPCS: change minimum supported PHP version to PHP 5.6
  admin/class-yoast-dashboard-widget.php
  admin/import/class-import-settings.php
  composer.lock
  inc/class-wpseo-utils.php
  inc/sitemaps/class-sitemap-image-parser.php
  phpcs.xml.dist
  wp-seo-main.php
Labels: changelog: non-user-facing, yoast cs/qa

#13919 Fixed overlapping of help scout beacon on pages iwth ads
  js/src/help-scout-beacon.js
Labels: changelog: non-user-facing

#13930 Introduce date format helper
  admin/formatter/class-post-metabox-formatter.php
  frontend/class-breadcrumbs.php
  frontend/class-opengraph.php
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-webpage.php
  inc/class-wpseo-replace-vars.php
  inc/date-helper.php
  tests/frontend/schema/schema-webpage-test.php
Labels: changelog: bugfix

#13934 Bump package versions
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13909 Re-send tracking data after WordPress core update
  admin/tracking/class-tracking.php
Labels: changelog: enhancement

#13942 Prefix the date helper class
  admin/formatter/class-post-metabox-formatter.php
  frontend/class-breadcrumbs.php
  frontend/class-opengraph.php
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-webpage.php
  inc/class-wpseo-replace-vars.php
  inc/date-helper.php
Labels: changelog: bugfix, type: bug

#13946 bump monorepo packages for 12.7 rc
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13951 Add safety check for when the PHP date format would return false
  inc/date-helper.php
Labels: changelog: bugfix

#13957 Remove webpack-dev-server modules from analysis
  webpack/webpack.config.js
Labels: changelog: non-user-facing

#13964 Make sure target image is centered on cursor
  css/src/admin-global.scss
Labels: changelog: bugfix

#13967 Fix missing @cover tags
  integration-tests/test-class-wpseo-breadcrumbs.php
  integration-tests/test-filters.php
Labels: changelog: non-user-facing

#13971 Adds missing `@covers` to unit tests
  integration-tests/inc/options/test-class-wpseo-options.php
  integration-tests/notifications/test-class-yoast-notification-center.php
  integration-tests/onpage/test-class-onpage-option.php
  integration-tests/onpage/test-class-onpage.php
  integration-tests/onpage/test-class-ryte-service.php
  integration-tests/recalculate/test-class-recalculate-posts.php
  integration-tests/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-data.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-validator.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-cache.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps.php
  integration-tests/statistics/test-class-statistics-service.php
  integration-tests/taxonomy/test-class-taxonomy-content-fields.php
  integration-tests/taxonomy/test-class-taxonomy-fields.php
  integration-tests/taxonomy/test-class-taxonomy-settings-fields.php
  integration-tests/taxonomy/test-class-taxonomy.php
Labels: changelog: non-user-facing, type: development, yoast cs/qa

#13968 Add covers tags
  integration-tests/test-class-admin-asset.php
Labels: changelog: non-user-facing

#13955 Implement date helper
  src/generators/schema/article.php
  src/generators/schema/webpage.php
  src/helpers/date-helper.php
  src/presentations/indexable-post-type-presentation.php
  tests/generators/schema/article-test.php
  tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php
  tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php
Labels: changelog: non-user-facing

#13962 Remove all IE11-specific scss
  css/src/admin-global.scss
  css/src/alerts.scss
  css/src/extensions.scss
  css/src/toggle-switch.scss
  css/src/wpseo-dismissible.scss
  css/src/yoast-components.scss
  css/src/yst_plugin_tools.scss
Labels: changelog: non-user-facing
