Repository Yoast/wordpress-seo, pull requests merged in 2019-12, with the labels that each got.

#13988 CS: clean up after merges
  admin/class-admin.php
  admin/class-helpscout.php
  admin/metabox/class-metabox.php
  admin/views/licenses.php
  admin/views/sidebar.php
  frontend/schema/class-schema-context.php
  integration-tests/admin/links/test-class-link-type-classifier.php
Labels: changelog: non-user-facing, yoast cs/qa

#13989 CS/QA: Helpscout - use `WPSEO_Utils::format_json_encode()`
  admin/class-helpscout.php
Labels: changelog: non-user-facing, yoast cs/qa

#13992 CS: clean up whitespace
  admin/views/licenses.php
Labels: changelog: non-user-facing, yoast cs/qa

#13987 Filter test: fix @covers tag
  integration-tests/test-filters.php
Labels: changelog: non-user-facing, yoast cs/qa

#13993 Restore the CSS fixed table layout on the settings pages.
  css/src/yst_plugin_tools.scss
Labels: changelog: non-user-facing

#13617 Fix an empty post title from changing a breadcrumb SD schema url
  frontend/schema/class-schema-breadcrumb.php
Labels: changelog: bugfix

#13929 Fix notification center buttons style.
  css/src/alerts.scss
  grunt/config/eslint.js
  js/src/wp-seo-admin-global.js
Labels: changelog: bugfix

#13943 Remove featured image alt attribute fallback to image title.
  js/src/wp-seo-featured-image.js
Labels: changelog: bugfix

#13979 prefixed CSS properties.
  css/src/yoastcom/0-tools/_mixins.scss
  css/src/yoastcom/_promoblock.scss
Labels: changelog: non-user-facing

#13840 Fixed rel next and rel prev for static home pages
  src/helpers/current-page-helper.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-static-home-page-presentation.php
  tests/presentations/indexable-static-home-page-presentation/canonical-test.php
  tests/presentations/indexable-static-home-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-static-home-page-presentation/rel-next-test.php
  tests/presentations/indexable-static-home-page-presentation/rel-prev-test.php
Labels: changelog: non-user-facing

#13860 Remove functionality saving vector length on indexable
  migrations/20191029111111_WpYoastProminentWordIndexableColumn.php
  src/models/indexable.php
Labels: changelog: non-user-facing

#13953 Date helper implementation
  deprecated/inc/sitemaps/class-sitemap-timezone.php
  inc/class-wpseo-utils.php
  inc/date-helper.php
  inc/sitemaps/class-sitemap-timezone.php
  inc/sitemaps/class-sitemaps-renderer.php
  inc/sitemaps/class-sitemaps.php
  integration-tests/test-class-wpseo-utils.php
  tests/helpers/date-helper-test.php
Labels: changelog: enhancement

#13570 Correctly implemented count_user_posts call in class-frontend.php
  frontend/class-frontend.php
  inc/sitemaps/class-author-sitemap-provider.php
  integration-tests/frontend/test-class-wpseo-frontend-robots.php
  src/helpers/author-archive-helper.php
  tests/helpers/author-archive-helper-test.php
Labels: 3, changelog: bugfix, has patch, in sprint

#13801 Bugreports 633 notification re index is never shown
  admin/capabilities/class-capability-utils.php
  admin/class-yoast-notification-center.php
  admin/class-yoast-notification.php
  integration-tests/notifications/test-class-yoast-notification-center.php
  integration-tests/notifications/test-class-yoast-notification.php
  tests/admin/admin-features-test.php
Labels: changelog: non-user-facing, has patch

#13960 escaped howto and faq IDs
  src/generators/schema/faq.php
  src/generators/schema/howto.php
Labels: changelog: non-user-facing

#13977 Remove -ms- prefixes everywhere
  css/src/toggle-switch.scss
  css/src/yoastcom/0-tools/_mixins.scss
  css/src/yst_plugin_tools.scss
  package.json
  yarn.lock
Labels: 1, changelog: enhancement

#13983 Travis: don't allow builds against PHP 7.4 to fail
  .travis.yml
  composer.json
  composer.lock
  integration-tests/admin/links/test-class-link-content-processor.php
  integration-tests/admin/links/test-class-link-storage.php
  integration-tests/admin/links/test-class-link-type-classifier.php
  integration-tests/admin/services/test-class-file-size.php
  integration-tests/admin/test-class-plugin-suggestions.php
  integration-tests/config-ui/test-class-configuration-components.php
  integration-tests/config-ui/test-class-configuration-endpoint.php
  integration-tests/config-ui/test-class-configuration-options-adapter.php
  integration-tests/config-ui/test-class-configuration-service.php
  integration-tests/config-ui/test-class-configuration-storage.php
  integration-tests/framework/class-wpseo-unit-test-case.php
  integration-tests/inc/test-class-wpseo-admin-bar-menu.php
  integration-tests/notifications/test-class-yoast-notification-center.php
  integration-tests/notifiers/test-class-dismissible-notification.php
  integration-tests/test-class-admin-asset-manager.php
Labels: changelog: non-user-facing, yoast cs/qa

#13852 [indexables] Add missing multisite checks for the actions
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  src/integrations/watchers/primary-term-watcher.php
Labels: changelog: non-user-facing, component: indexables

#14003 Change text reference to Open Graph checkbox.
  admin/views/tabs/social/pinterest.php
  admin/views/tabs/social/twitterbox.php
Labels: UI change, changelog: enhancement

#13399 Update CSS classes passed to add_settings_error.
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-option.php
  tests/inc/options/option-social-test.php
Labels: changelog: bugfix

#14005 Date helper implementation
  deprecated/inc/sitemaps/class-sitemap-timezone.php
  inc/class-wpseo-utils.php
  inc/date-helper.php
  inc/sitemaps/class-author-sitemap-provider.php
  inc/sitemaps/class-sitemap-timezone.php
  inc/sitemaps/class-sitemaps-renderer.php
  inc/sitemaps/class-sitemaps.php
  integration-tests/test-class-wpseo-utils.php
  tests/helpers/date-helper-test.php
Labels: changelog: enhancement

#14008 Indexables: fix per-post robots setting
  src/presentations/indexable-post-type-presentation.php
Labels: changelog: non-user-facing

#14016 Extends the OG image class with the one that replaces it
  deprecated/frontend/class-opengraph-image.php
Labels: changelog: non-user-facing, component: indexables, component: innovation, type: development

#14014 @var type from array to int
  frontend/class-breadcrumbs.php
Labels: changelog: other, community-patch

#14019 Remove BlackFriday option
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#13677 Checks if class has identifier property and use that as the class name.
  frontend/schema/class-schema.php
Labels: 1, has patch

#14028 Bump monorepo packages for 12.7 release
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14017 Check for identifier property to override the class name value.
  src/generators/schema-generator.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation, type: development

#14018 13841 update static page indexable
  src/integrations/watchers/indexable-static-home-page-watcher.php
  src/repositories/indexable-repository.php
  tests/integrations/watchers/indexable-static-home-page-watcher-test.php
Labels: changelog: non-user-facing, component: indexables

#13848 Add missing multisite checks for the actions
  admin/class-admin.php
  admin/links/class-link-watcher.php
  admin/statistics/class-statistics-integration.php
  admin/taxonomy/class-taxonomy.php
Labels: changelog: bugfix

#14033 Removal of manual set x-redirect-by headers
  frontend/class-frontend.php
  inc/class-rewrite.php
  inc/sitemaps/class-sitemaps-router.php
Labels: changelog: non-user-facing, component: redirects, type: development

#14030 Introduces a home url helper
  src/helpers/home-url-helper.php
Labels: changelog: other, type: development

#13522 Move notice paginated comments to health check
  admin/class-admin-init.php
  inc/class-upgrade.php
  inc/health-check-page-comments.php
  inc/health-check.php
  tests/inc/health-check-page-comments-test.php
  tests/inc/health-check-test.php
Labels: changelog: other

#13055 Prevent multiple checks to get all options
  admin/import/class-import-settings.php
  inc/options/class-wpseo-options.php
  integration-tests/capabilities/test-class-register-capabilities.php
  integration-tests/frontend/test-class-opengraph.php
  integration-tests/frontend/test-class-wpseo-frontend-robots.php
  integration-tests/inc/test-class-wpseo-admin-bar-menu.php
  integration-tests/sitemaps/test-class-wpseo-author-sitemap-provider.php
Labels: 1, has patch

#14037 Revert "Adjust input fields heights after WordPress 5.3 CSS changes."
  css/src/admin-global.scss
Labels: changelog: non-user-facing

#14029 13996 send list of blocks to analysis
  js/src/analysis/collectAnalysisData.js
  js/src/wp-seo-post-scraper.js
  js/tests/__test-data__/blocksForAnalysisTestData.json
  js/tests/__test-data__/gutenbergBlocksTestData.json
  js/tests/collectAnalysisData.test.js
Labels: changelog: non-user-facing

#14048 Add pdo_mysql extension to tracking and remove modXml as it doesn't exist
  admin/tracking/class-tracking-server-data.php
Labels: changelog: non-user-facing

#14009 Use WPSEO_Options::get where we can
  admin/class-yoast-form.php
  inc/wpseo-non-ajax-functions.php
  integration-tests/admin/test-class-yoast-form.php
Labels: 1, changelog: non-user-facing

#14040 Remove wp 4.9 code
  admin/class-admin-asset-manager.php
  admin/class-admin-init.php
  admin/config-ui/class-configuration-page.php
  js/src/structured-data-blocks/faq/components/Question.js
  js/src/structured-data-blocks/how-to/components/HowToStep.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-term-scraper.js
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: changelog: enhancement

#13991 WPSEO_Metabox::is_internet_explorer(): bug fixes / input handling
  admin/metabox/class-metabox.php
  tests/TestCase.php
Labels: changelog: non-user-facing, yoast cs/qa

#14026 Bump plugin grunt tasks
  grunt/config/aliases.yaml
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#13252 Introduce Migration_Status object to handle migration locks and conditionals
  package.json
  src/conditionals/migrations-conditional.php
  src/config/migration-status.php
  src/initializers/migration-runner.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-date-archive-watcher.php
  src/integrations/watchers/indexable-home-page-watcher.php
  src/integrations/watchers/indexable-post-type-archive-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-system-page-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  tests/database/migration-runner-test.php
  tests/database/migration-status-test.php
  tests/integrations/watchers/indexable-author-watcher-test.php
  tests/integrations/watchers/indexable-date-archive-watcher-test.php
  tests/integrations/watchers/indexable-home-page-watcher-test.php
  tests/integrations/watchers/indexable-post-type-archive-watcher-test.php
  tests/integrations/watchers/indexable-post-watcher-test.php
  tests/integrations/watchers/indexable-system-page-watcher-test.php
  tests/integrations/watchers/indexable-term-watcher-test.php
  wp-seo-main.php
  wp-seo.php
Labels: 5, has patch

#13924 Fix HowTo naming in code documentation / comments
  frontend/schema/class-schema-howto.php
Labels: community-patch

#14036 Add upgrade routine to remove WordPress upgrade notice
  inc/class-upgrade.php
Labels: changelog: other

#14042 Add is_public to indexables table
  migrations/20191211144248_WpYoastIndexablesAddIsPublicField.php
  src/builders/indexable-post-builder.php
  src/models/indexable.php
  tests/builders/indexable-post-builder-test.php
Labels: changelog: non-user-facing

#14050 Removal of the manual set x-redirect-header
  src/helpers/redirect-helper.php
  src/integrations/front-end/comment-link-fixer.php
  src/integrations/front-end/redirects.php
  tests/integrations/front-end/comment-link-fixer-test.php
  tests/integrations/front-end/redirects-test.php
Labels: 0.5, component: indexables, component: innovation

#14035 Use browserlist instead of babel targets directly
  .babelrc
  package.json
Labels: changelog: non-user-facing

#14057 Fill cache properly when option is registered.
  inc/options/class-wpseo-options.php
  tests/TestCase.php
Labels: changelog: non-user-facing

#13649 Changed Snippet Preview title to Google search result preview
  js/src/components/Metabox.js
  js/src/components/SnippetPreviewModal.js
Labels: UI change, changelog: enhancement

#14068 Add env to grunt
  .env.example
  .gitignore
  Gruntfile.js
  grunt/config/aliases.yaml
  grunt/config/notify-slack.js
  grunt/config/prompt.js
  grunt/config/rc-slack-notification.js
  grunt/custom/notify-slack.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14069 Premium: Update to YoastCS 2.0.0
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#14076 Adds jed as dependency
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing

#14078 Uses content instead of value
  src/presenters/open-graph/image-presenter.php
  src/presenters/open-graph/type-presenter.php
  tests/presenters/open-graph/image-presenter-test.php
  tests/presenters/open-graph/type-presenter-test.php
Labels: changelog: non-user-facing

#14075 Optimize the cache fill
  inc/options/class-wpseo-option.php
  inc/options/class-wpseo-options.php
Labels: changelog: non-user-facing, type: development

#14080 More informative error if remote branch does not exist
  grunt/config/ensure-pre-release-branch.js
Labels: changelog: non-user-facing

#14083 Commit the modified changelog
  Gruntfile.js
  grunt/config/update-readme.js
Labels: changelog: non-user-facing

#14074 Add database logging
  inc/sitemaps/class-sitemaps-renderer.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps.php
  src/conditionals/development-conditional.php
  src/loggers/database-logger.php
Labels: 0.5

#13990 CS: fix placement PHP open/close tags for embedded PHP
  admin/views/sidebar.php
Labels: changelog: non-user-facing, yoast cs/qa

#14095 Add missing short descriptions
  admin/tracking/class-tracking-settings-data.php
  config/php-codeshift/remove-vendor-prefixing-array-key-visitor.php
  config/php-codeshift/remove-vendor-prefixing-comment-visitor.php
  config/php-codeshift/remove-vendor-prefixing-visitor.php
  inc/health-check.php
Labels: changelog: non-user-facing

#14094 Fix Create GitHub pre release task
  .env.example
  grunt/config/github-pre-release.js
  grunt/config/tools/get-user-input.js
  grunt/config/update-readme.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14104 Add spaces to the googlebot meta tag
  src/presenters/googlebot-presenter.php
  tests/presenters/googlebot-presenter-test.php
Labels: changelog: non-user-facing
