Repository Yoast/wordpress-seo, pull requests merged in 2019-08, with the labels that each got.

#13326 Don't allow all HTML tags in the schema description
  frontend/schema/class-schema-webpage.php
  inc/class-wpseo-utils.php
  readme.txt
  tests/frontend/schema/class-schema-webpage-test.php
Labels: 0.5

#13270 Configuration wizard onboarding image: Add missing empty alt attribute
  admin/notifiers/class-configuration-notifier.php
  integration-tests/notifiers/test-class-configuration-notifier.php
Labels: a11y-has-patch, component: admin, component: notifications

#13353 CS: clean up after merges
  admin/config-ui/components/class-component-connect-google-search-console.php
  admin/metabox/class-metabox-section-additional.php
  admin/metabox/class-metabox-section-react.php
  admin/metabox/class-metabox.php
  tests/TestCase.php
  tests/admin/metabox/metabox-section-additional-test.php
  tests/admin/metabox/metabox-test.php
  tests/builders/indexable-term-builder-test.php
  tests/frontend/schema/schema-webpage-test.php
Labels: yoast cs/qa

#13355 CS: clean up after merges / namespaced files
  config/dependency-injection/container-compiler.php
  config/dependency-injection/custom-loader.php
  config/dependency-injection/loader-pass.php
  config/dependency-injection/services.php
  src/builders/indexable-post-builder.php
  src/conditionals/feature-flag-conditional.php
  src/config/dependency-management.php
  src/database/database-setup.php
  src/database/migration-runner.php
  src/database/ruckusing-framework.php
  src/loggers/logger.php
  src/loggers/migration-logger.php
  src/main.php
  src/models/indexable-extension.php
  src/models/indexable.php
  src/orm/yoast-model.php
  src/repositories/indexable-repository.php
  src/repositories/primary-term-repository.php
  src/repositories/seo-links-repository.php
  src/repositories/seo-meta-repository.php
  src/watchers/indexable-post-watcher.php
  tests/TestCase.php
  tests/admin/admin-features-test.php
  tests/admin/metabox/metabox-editor-test.php
  tests/admin/metabox/metabox-section-additional-test.php
  tests/admin/metabox/metabox-test.php
  tests/database/migration-runner-test.php
  tests/frontend/schema/schema-how-to-test.php
  tests/frontend/schema/schema-webpage-test.php
Labels: yoast cs/qa

#13293 set maxwidth to 800
  css/src/metabox.scss
Labels: community-patch

#13359 Add the translations of the javascript monorepo packages
  Gruntfile.js
  grunt/config/aliases.yaml
  grunt/config/clean.js
  grunt/config/copy.js
  grunt/config/shell.js
  package.json
Labels: changelog: bugfix

#13361 Travis: only one command per condition
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#13363 Remove kses_post from notification
  admin/class-yoast-notification-center.php
Labels: changelog: non-user-facing

#13240 Improve user input validation for URL fields
  inc/options/class-wpseo-option.php
  integration-tests/frontend/test-class-wpseo-opengraph-image.php
  integration-tests/inc/options/test-class-wpseo-option-social.php
  tests/TestCase.php
  tests/doubles/inc/options/option-social-double.php
  tests/inc/options/option-social-test.php
Labels: 8, in sprint, underestimated

#13377 Apply the same premium logic for the taxonomy social tabs as for posts
  admin/class-social-admin.php
  admin/taxonomy/class-taxonomy-metabox.php
Labels: changelog: non-user-facing

#13379 13350 add internal linking columns to indexables table
  migrations/20190813111111_WpYoastProminentWordIndexableColumns.php
  src/models/indexable.php
Labels: changelog: non-user-facing

#13304 Identify form controls with error: add error messages and visual-semantic feedback
  .editorconfig
  admin/class-yoast-form.php
  admin/class-yoast-input-validation.php
  css/src/yst_plugin_tools.scss
  images/error-icon.svg
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-option.php
  tests/admin/input-validation-test.php
  tests/doubles/inc/options/option-social-double.php
  tests/inc/options/option-social-test.php
Labels: UI change

#13390 Improves plugin icon consistency
  images/Local_SEO_Icon.svg
  images/News_SEO_Icon.svg
  images/Video_SEO_Icon.svg
  images/Woo_SEO_Icon.svg
  images/Yoast_SEO_Icon.svg
Labels: UI change, changelog: enhancement

#13391 Remove unused images
  images/editicon.png
  images/exclamation-triangle.svg
  images/extensions-local-for-woocommerce.png
  images/sample_course_card_header.png
  images/waiting.gif
  images/yoast-configuration-icon.svg
Labels: changelog: non-user-facing

#13392 Show site icon as favicon in mobile snippet preview
  admin/formatter/class-metabox-formatter.php
  js/src/containers/SnippetEditor.js
  js/src/edit.js
Labels: changelog: enhancement

#13357 Apply lodash.unescape to term names in TaxonomyPicker
  js/src/components/TaxonomyPicker.js
Labels: changelog: bugfix, community-patch

#13247 Add filter for company_name and company_logo_id
  frontend/schema/class-schema-context.php
Labels: community-patch

#13380 Added filter to modify organization sameAs attributes.
  frontend/schema/class-schema-organization.php
Labels: community-patch

#13292 updates robots() to have an echo param like other frontend methods
  frontend/class-frontend.php
Labels: community-patch

#13358 Fix vendor prefixing composer
  .travis.yml
  composer.json
  composer.lock
  config/php-codeshift/remove-vendor-prefixing-array-key-visitor.php
  config/php-codeshift/remove-vendor-prefixing-codemod.php
  config/php-codeshift/remove-vendor-prefixing-comment-visitor.php
  config/php-codeshift/remove-vendor-prefixing-visitor.php
  config/php-scoper/dependency-injection.inc.php
  config/php-scoper/guzzlehttp.inc.php
  config/php-scoper/idiorm.inc.php
  config/php-scoper/ruckusing.inc.php
  grunt/config/aliases.yaml
  grunt/config/shell.js
  src/config/dependency-management.php
  src/main.php
  tests/config/dependency-management-test.php
Labels: 1, in sprint

#13417 Remove the Courses menu-item in Yoast SEO
  admin/class-admin-asset-manager.php
  admin/courses-overview.php
  admin/menu/class-admin-menu.php
  admin/menu/class-menu.php
  admin/pages/courses.php
  inc/class-wpseo-utils.php
  js/src/courses-overview.js
  webpack/paths.js
  wp-seo-main.php
Labels: UI change, changelog: other

#13413 Add a paper collapsible around the hidden Yoast alerts
  admin/class-paper-presenter.php
  admin/views/paper-collapsible.php
  admin/views/partial-alerts-errors.php
  admin/views/partial-alerts-template.php
  admin/views/partial-alerts-warnings.php
  admin/views/tabs/dashboard/dashboard.php
  css/src/alerts.scss
Labels: UI change, changelog: enhancement

#13374 Add find_by_indexable_id method to indexable repository
  src/repositories/indexable-repository.php
Labels: changelog: non-user-facing

#13242 Replace 'SEO Available' with more descriptive text
  admin/formatter/class-metabox-formatter.php
  inc/class-wpseo-rank.php
  integration-tests/test-class-wpseo-rank.php
  integration-tests/test-class-wpseo-utils.php
Labels: community-patch

#13427 Remove AMP glue suggestion notification
  admin/class-plugin-availability.php
  inc/class-upgrade.php
Labels: 1

#13418 Add wp_version and php_version to the feed request
  admin/class-yoast-dashboard-widget.php
  js/src/wp-seo-dashboard-widget.js
Labels: 2, changelog: other
