Repository Yoast/wordpress-seo, pull requests merged in 2020-03, with the labels that each got.

#14436 Adds unit tests for the schema helpers.
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/faq.php
  src/helpers/image-helper.php
  src/helpers/schema/article-helper.php
  src/helpers/schema/image-helper.php
  src/helpers/schema/language-helper.php
  src/helpers/twitter/image-helper.php
  tests/TestCase.php
  tests/generators/schema/article-test.php
  tests/generators/schema/author-test.php
  tests/generators/schema/person.php
  tests/helpers/image-helper-test.php
  tests/helpers/schema/article-helper-test.php
  tests/helpers/schema/id-helper-test.php
  tests/helpers/schema/image-helper-test.php
  tests/helpers/schema/language-helper-test.php
Labels: 1, changelog: non-user-facing

#14443 Update the PR template to also ask for context
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: non-user-facing

#14463 Bump monorepo packages for 13.3-RC1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14451 Add tests for helpers
  src/helpers/blocks-helper.php
  src/helpers/current-page-helper.php
  src/helpers/date-helper.php
  src/helpers/image-helper.php
  src/helpers/meta-helper.php
  src/helpers/options-helper.php
  src/helpers/post-helper.php
  src/helpers/post-type-helper.php
  src/helpers/product-helper.php
  src/helpers/redirect-helper.php
  src/helpers/site-helper.php
  src/helpers/string-helper.php
  src/helpers/taxonomy-helper.php
  src/helpers/url-helper.php
  src/helpers/user-helper.php
  tests/helpers/blocks-helper-test.php
  tests/helpers/current-page-helper-test.php
  tests/helpers/home-url-helper-test.php
  tests/helpers/options-helper-test.php
  tests/helpers/post-helper-test.php
  tests/helpers/product-helper-test.php
  tests/helpers/taxonomy-helper-test.php
  tests/helpers/url-helper-test.php
Labels: 1, changelog: non-user-facing, component: indexables

#14399 Card and paper styling
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-form.php
  admin/notifiers/class-configuration-notifier.php
  admin/views/licenses.php
  admin/views/paper-collapsible.php
  admin/views/partial-alerts-errors.php
  admin/views/partial-alerts-template.php
  admin/views/sidebar.php
  admin/views/tabs/dashboard/dashboard.php
  css/src/admin/all.css
  css/src/base/_mixins.scss
  css/src/base/colors.css
  css/src/base/icons.css
  css/src/components/buttons.css
  css/src/components/card.css
  css/src/components/headings.css
  css/src/components/paper.css
  images/local_plugin_assistant.svg
  images/news_plugin_assistant.svg
  images/video_plugin_assistant.svg
  js/src/wp-seo-admin-global.js
Labels: UI change, changelog: non-user-facing

#14479 Add tests for integrations
  src/helpers/site-helper.php
  src/integrations/front-end-integration.php
  src/integrations/front-end/category-description.php
  src/integrations/front-end/comment-link-fixer.php
  src/integrations/front-end/force-rewrite-title.php
  src/integrations/front-end/handle-404.php
  src/integrations/front-end/indexing-controls.php
  src/integrations/front-end/open-graph-oembed.php
  src/integrations/front-end/redirects.php
  src/integrations/front-end/rss-footer-embed.php
  src/integrations/front-end/theme-titles.php
  src/integrations/front-end/webmaster-tools-meta.php
  src/integrations/integration-interface.php
  src/integrations/third-party/bbpress.php
  src/integrations/third-party/jetpack.php
  src/integrations/third-party/woocommerce.php
  src/integrations/third-party/wpml.php
  src/integrations/watchers/indexable-permalink-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  tests/doubles/integrations/watchers/primary-term-watcher-double.php
  tests/integrations/front-end-integration-test.php
  tests/integrations/front-end/category-description-test.php
  tests/integrations/front-end/comment-link-fixer-test.php
  tests/integrations/front-end/force-rewrite-title-test.php
  tests/integrations/front-end/handle-404-test.php
  tests/integrations/front-end/indexing-controls-test.php
  tests/integrations/front-end/open-graph-oembed-test.php
  tests/integrations/front-end/redirects-test.php
  tests/integrations/front-end/rss-footer-embed-test.php
  tests/integrations/front-end/theme-titles-test.php
  tests/integrations/front-end/webmaster-tools-meta-test.php
  tests/integrations/third-party/bbpress-test.php
  tests/integrations/third-party/jetpack-test.php
  tests/integrations/third-party/woocommerce-test.php
  tests/integrations/third-party/wpml-test.php
  tests/integrations/watchers/indexable-author-watcher-test.php
  tests/integrations/watchers/indexable-date-archive-watcher-test.php
  tests/integrations/watchers/indexable-home-page-watcher-test.php
  tests/integrations/watchers/indexable-permalink-watcher-test.php
  tests/integrations/watchers/indexable-post-type-archive-watcher-test.php
  tests/integrations/watchers/indexable-post-watcher-test.php
  tests/integrations/watchers/indexable-static-home-page-watcher-test.php
  tests/integrations/watchers/indexable-system-page-watcher-test.php
  tests/integrations/watchers/indexable-term-watcher-test.php
  tests/integrations/watchers/primary-term-watcher-test.php
Labels: 1, component: indexables, component: innovation, component: tests

#14478 Use strcasecmp to compare encoded URLs
  inc/class-wpseo-utils.php
Labels: changelog: bugfix, community-patch

#14481 Use sanitize_url to sanitize canonical field
  admin/metabox/class-metabox.php
Labels: community-patch

#14317 Repurpose the is_public column
  migrations/20171228151840_WpYoastIndexable.php
  src/backwards-compatibility/breadcrumbs.php
  src/backwards-compatibility/frontend.php
  src/builders/indexable-author-builder.php
  src/builders/indexable-builder.php
  src/builders/indexable-date-archive-builder.php
  src/builders/indexable-hierarchy-builder.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-post-type-archive-builder.php
  src/builders/indexable-rebuilder.php
  src/builders/indexable-term-builder.php
  src/commands/generate-indexables-command.php
  src/helpers/author-archive-helper.php
  src/helpers/blocks-helper.php
  src/helpers/post-helper.php
  src/helpers/taxonomy-helper.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/models/indexable.php
  src/orm/yoast-orm-wrapper.php
  src/repositories/indexable-repository.php
  tests/_mocks/indexable.php
  tests/builders/indexable-author-builder-test.php
  tests/builders/indexable-date-archive-builder-test.php
  tests/builders/indexable-hierarchy-builder-test.php
  tests/builders/indexable-post-builder-test.php
  tests/builders/indexable-post-type-archive-builder-test.php
  tests/builders/indexable-rebuilder-test.php
  tests/builders/indexable-term-builder-test.php
  tests/doubles/builders/indexable-post-builder-double.php
  tests/doubles/integrations/watchers/indexable-post-watcher-double.php
  tests/helpers/author-archive-helper-test.php
  tests/helpers/blocks-helper-test.php
  tests/integrations/watchers/indexable-author-watcher-test.php
  tests/integrations/watchers/indexable-post-watcher-test.php
  tests/integrations/watchers/indexable-static-home-page-watcher-test.php
Labels: changelog: non-user-facing

#14492 Add unit tests
  integration-tests/test-class-wpseo-metabox.php
  integration-tests/test-class-wpseo-utils.php
  js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap
  js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
Labels: changelog: non-user-facing, component: tests

#14486 Fix site represents checks in context
  src/context/meta-tags-context.php
  tests/context/meta-tags-context-test.php
Labels: changelog: non-user-facing

#14502 Improve method sanitize_url
  inc/class-wpseo-utils.php
  integration-tests/test-class-wpseo-utils.php
  tests/inc/options/option-social-test.php
Labels: community-patch

#14507 Fix bump versions PR versions
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14480 Add tests for FAQ and breadcrumbs Schema generators
  src/generators/schema/breadcrumb.php
  src/generators/schema/faq.php
  src/helpers/current-page-helper.php
  tests/generators/schema/breadcrumb-test.php
  tests/generators/schema/faq-test.php
Labels: changelog: non-user-facing

#14509 Add tests for integrations/watchers
  src/integrations/watchers/indexable-post-type-archive-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  tests/integrations/watchers/indexable-author-watcher-test.php
  tests/integrations/watchers/indexable-date-archive-watcher-test.php
  tests/integrations/watchers/indexable-home-page-watcher-test.php
  tests/integrations/watchers/indexable-permalink-watcher-test.php
  tests/integrations/watchers/indexable-post-type-archive-watcher-test.php
  tests/integrations/watchers/indexable-post-watcher-test.php
  tests/integrations/watchers/indexable-static-home-page-watcher-test.php
  tests/integrations/watchers/indexable-system-page-watcher-test.php
  tests/integrations/watchers/indexable-term-watcher-test.php
  tests/integrations/watchers/primary-term-watcher-test.php
Labels: 1, component: indexables, component: innovation, component: tests

#14508 Adds tests for the author Schema generator
  src/generators/schema/author.php
  tests/generators/schema/author-test.php
Labels: changelog: non-user-facing

#14518 Little fixes for method sanitize_url
  inc/class-wpseo-utils.php
Labels: community-patch

#14513 Add more tests for method sanitize
  integration-tests/test-class-wpseo-utils.php
Labels: changelog: non-user-facing, community-patch

#14483 Don't output breadcrumb schema on error pages
  src/generators/schema/breadcrumb.php
  tests/generators/schema/breadcrumb-test.php
Labels: changelog: non-user-facing

#14522 Add unit tests for article generator
  src/generators/schema/article.php
  tests/doubles/generators/schema/article-double.php
  tests/generators/schema/article-test.php
Labels: changelog: non-user-facing, component: indexables, component: tests

#14523 Change the order in which the functions are executed
  frontend/class-frontend.php
Labels: changelog: non-user-facing

#14488 Add tests for the indexable presenters
  src/presenters/abstract-indexable-presenter.php
  src/presenters/breadcrumbs-presenter.php
  src/presenters/meta-description-presenter.php
  src/presenters/open-graph/title-presenter.php
  src/presenters/title-presenter.php
  src/presenters/twitter/image-presenter.php
  tests/_mocks/meta-tags-context.php
  tests/presenters/breadcrumbs-presenter-test.php
  tests/presenters/googlebot-presenter-test.php
  tests/presenters/meta-description-presenter-test.php
  tests/presenters/open-graph/article-author-presenter-test.php
  tests/presenters/open-graph/article-modified-time-presenter-test.php
  tests/presenters/open-graph/article-published-time-presenter-test.php
  tests/presenters/open-graph/article-publisher-presenter-test.php
  tests/presenters/open-graph/description-presenter-test.php
  tests/presenters/open-graph/fb-app-id-presenter-test.php
  tests/presenters/open-graph/image-presenter-test.php
  tests/presenters/open-graph/locale-presenter-test.php
  tests/presenters/open-graph/site-name-presenter-test.php
  tests/presenters/open-graph/title-presenter-test.php
  tests/presenters/open-graph/type-presenter-test.php
  tests/presenters/open-graph/url-presenter-test.php
  tests/presenters/rel-next-presenter-test.php
  tests/presenters/rel-prev-presenter-test.php
  tests/presenters/robots-presenter-test.php
  tests/presenters/schema-presenter-test.php
  tests/presenters/title-presenter-test.php
  tests/presenters/twitter/description-presenter-test.php
  tests/presenters/twitter/image-presenter-test.php
  tests/presenters/twitter/title-presenter-test.php
Labels: changelog: non-user-facing, component: indexables, component: tests

#14527 Full test coverage for main image
  tests/generators/schema/main-image-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation, component: tests

#14528 Adds unit tests for the breadcrumbs generator.
  src/generators/breadcrumbs-generator.php
  tests/generators/breadcrumbs-generator-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation, component: tests

#14530 Add tests for the Open_Graph_Locale_Generator
  tests/generators/open-graph-locale-generator-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation, component: tests

#14536 An indexable is built for a term when it is created.
  src/integrations/watchers/indexable-term-watcher.php
Labels: changelog: non-user-facing

#14532 Change namespaces
  src/generators/breadcrumbs-generator.php
  src/generators/generator-interface.php
  src/generators/open-graph-image-generator.php
  src/generators/open-graph-locale-generator.php
  src/generators/schema-generator.php
  src/generators/schema/abstract-schema-piece.php
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/breadcrumb.php
  src/generators/schema/faq.php
  src/generators/schema/howto.php
  src/generators/schema/main-image.php
  src/generators/schema/organization.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/generators/schema/website.php
  src/generators/twitter-image-generator.php
  src/presentations/indexable-presentation.php
  tests/_mocks/author.php
  tests/doubles/generators/schema/article-double.php
  tests/generators/open-graph-locale-generator-test.php
  tests/generators/schema-generator-test.php
  tests/generators/schema/article-test.php
  tests/generators/schema/author-test.php
  tests/generators/schema/breadcrumb-test.php
  tests/generators/schema/faq-test.php
  tests/generators/schema/main-image-test.php
  tests/generators/schema/person.php
  tests/generators/schema/website-test.php
  tests/presentations/presentation-instance-dependencies.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14529 Tests generators schema organization
  src/generators/schema/organization.php
  tests/generators/schema/organization-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation, component: tests

#14531 Add tests for HowTo Schema generator
  src/generators/schema/howto.php
  tests/generators/schema/howto-test.php
Labels: changelog: non-user-facing

#14550 Fix og:url for static posts pages
  src/presentations/indexable-static-posts-page-presentation.php
  tests/presentations/indexable-static-posts-page-presentation/open-graph-url-test.php
  tests/presentations/indexable-static-posts-page-presentation/presentation-instance-builder.php
Labels: changelog: non-user-facing

#14556 Add styling for tools page
  admin/links/class-link-reindex-dashboard.php
  admin/pages/tools.php
  css/src/admin/all.css
  css/src/components/card.css
  css/src/components/headings.css
  css/src/components/lists.css
  css/src/components/tabs.css
Labels: UI change, changelog: non-user-facing

#14559 Bump versions
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14547 Fix author not being output when site represents organization
  src/generators/schema/author.php
  tests/generators/schema/author-test.php
Labels: changelog: non-user-facing

#14526 Better checking authority/host parts in URL
  inc/class-wpseo-utils.php
  integration-tests/test-class-wpseo-utils.php
Labels: 0.5, community-patch

#14510 Add styling to sidebar content
  admin/class-yoast-form.php
  admin/views/sidebar.php
  css/src/admin/all.css
  css/src/components/sidebar.css
  images/local_plugin_assistant_small.svg
  images/news_plugin_assistant_small.svg
  images/video_plugin_assistant_small.svg
  images/woo_plugin_assistant_small.svg
Labels: UI change, changelog: non-user-facing

#14560 Added additional test for the schema generator.
  tests/_mocks/meta-tags-context.php
  tests/generators/schema-generator-test.php
Labels: 1, changelog: non-user-facing, component: indexables, component: innovation, component: tests

#14557 Fix breadcrumbs home when indexables do not yet exist
  src/generators/breadcrumbs-generator.php
  src/repositories/indexable-repository.php
  tests/generators/breadcrumbs-generator-test.php
Labels: 0.5, regression

#14568 Bump monorepo packages for 13.4-RC1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14578 Added a dash to max-age in caching headers of .xsl files
  inc/sitemaps/class-sitemaps.php
Labels: changelog: non-user-facing, has patch

#14402 Add content-type header to request
  admin/tracking/class-tracking.php
Labels: changelog: non-user-facing, has patch

#14497 Add term hierarchy replacement variable on category page
  admin/class-admin-editor-specific-replace-vars.php
  admin/class-admin-recommended-replace-vars.php
  admin/taxonomy/class-taxonomy.php
  inc/class-wpseo-replace-vars.php
  integration-tests/admin/test-class-admin-editor-specific-replace-vars.php
  integration-tests/admin/test-class-admin-recommended-replace-vars.php
  js/src/wp-seo-replacevar-plugin.js
Labels: UI change, changelog: enhancement

#14579 Improve backwards compatibility of deprecated methods.
  deprecated/frontend/schema/class-schema-image.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14565 Fix title interaction with themes
  src/integrations/front-end-integration.php
  tests/integrations/front-end-integration-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation, regression

#14548 Add components css stylesheet to the plugin
  admin/class-admin-asset-manager.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  js/tests/__mocks__/styleMock.js
  js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap
  js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: changelog: non-user-facing

#14584 Have better BC in WPSEO_Schema_Utils
  deprecated/frontend/schema/class-schema-utils.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14551 A post's primary category is created when lazily creating a post by visiting it on the frontend.
  src/builders/indexable-builder.php
  src/builders/primary-term-builder.php
  src/helpers/primary-term-helper.php
  src/integrations/watchers/primary-term-watcher.php
  tests/builders/primary-term-builder-test.php
  tests/doubles/builders/primary-term-builder-double.php
  tests/doubles/integrations/watchers/primary-term-watcher-double.php
  tests/helpers/primary-term-helper-test.php
  tests/integrations/watchers/primary-term-watcher-test.php
Labels: changelog: non-user-facing, component: innovation

#14595 Make sure monorepo css survives grunt build steps
  grunt/config/aliases.yaml
  grunt/config/clean.js
Labels: changelog: non-user-facing

#14594 Implements BC for WPSEO_Schema_Breadcrumb.
  deprecated/frontend/schema/class-schema-breadcrumb.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14593 implemented potentialAction array in website schema
  src/generators/schema/webpage.php
  src/generators/schema/website.php
  tests/generators/schema-generator-test.php
  tests/generators/schema/website-test.php
Labels: changelog: non-user-facing

#14576 Update help icons
  admin/class-admin-help-button.php
  admin/class-admin-help-panel.php
  admin/class-paper-presenter.php
  admin/class-yoast-form.php
  admin/metabox/class-metabox.php
  admin/notifiers/class-configuration-notifier.php
  admin/taxonomy/class-taxonomy-fields-presenter.php
  admin/views/class-view-utils.php
  admin/views/class-yoast-feature-toggle.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/licenses.php
  admin/views/paper-collapsible.php
  admin/views/partial-alerts-template.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/dashboard/webmaster-tools.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/archives/help.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/paper-content/author-archive-settings.php
  admin/views/tabs/metas/paper-content/date-archives-settings.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
  admin/views/tabs/metas/paper-content/post-type-content.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  admin/views/tabs/metas/paper-content/rss-content.php
  admin/views/tabs/metas/paper-content/special-pages.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/rss.php
  admin/views/tabs/metas/taxonomies/category-url.php
  admin/views/tabs/network/features.php
  admin/views/tabs/social/accounts.php
  admin/views/tabs/social/facebook.php
Labels: UI change, changelog: non-user-facing

#14611 Link monorepo when deploying feature branches to yoast-dist
  .travis.yml
Labels: changelog: non-user-facing

#14583 Improve backwards compatibility for basic schema classes
  deprecated/frontend/schema/class-schema-article.php
  deprecated/frontend/schema/class-schema-author.php
  deprecated/frontend/schema/class-schema-faq.php
  deprecated/frontend/schema/class-schema-howto.php
  deprecated/frontend/schema/class-schema-main-image.php
  deprecated/frontend/schema/class-schema-organization.php
  deprecated/frontend/schema/class-schema-person.php
  deprecated/frontend/schema/class-schema-webpage.php
  deprecated/frontend/schema/class-schema-website.php
  src/generators/schema/author.php
Labels: changelog: non-user-facing, component: innovation

#14620 Add safety check around filter author schema
  src/generators/schema/author.php
  tests/generators/schema/author-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14622 Add novalidate to our forms as we don't use native validation.
  admin/class-yoast-form.php
  js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap
  js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
Labels: changelog: bugfix

#14624 Add tests for website schema
  tests/generators/schema/website-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14612 React refactor: extract slots, fills and portals
  js/src/components/MetaboxPortal.js
  js/src/components/SettingsReplacementVariableEditors.js
  js/src/components/Sidebar.js
  js/src/components/SidebarItem.js
  js/src/components/SocialMetadata.js
  js/src/components/Suggestions.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/contentAnalysis/ScoreIconPortal.js
  js/src/components/contentAnalysis/SeoAnalysis.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/components/portals/CompanyInfoMissingPortal.js
  js/src/components/portals/LocalSEOUpsellPortal.js
  js/src/components/portals/MetaboxPortal.js
  js/src/components/portals/Portal.js
  js/src/components/portals/ReadabilityResultsPortal.js
  js/src/components/portals/ScoreIconPortal.js
  js/src/components/portals/SettingsEditorPortal.js
  js/src/components/portals/SettingsFieldPortal.js
  js/src/components/portals/SocialMetadataPortal.js
  js/src/components/portals/UserSelectPortal.js
  js/src/components/slots/FacebookPreviewSlot.js
  js/src/components/slots/MetaboxSlot.js
  js/src/components/slots/SidebarSlot.js
  js/src/components/slots/SynonymSlot.js
  js/src/components/slots/TwitterPreviewSlot.js
  js/src/configuration-wizard.js
  js/src/containers/MetaboxFill.js
  js/src/containers/SidebarFill.js
  js/src/edit.js
  js/src/helpers/classicEditor.js
  js/src/search-appearance.js
  js/src/wp-seo-api.js
  js/src/wp-seo-dashboard-widget.js
  js/src/wp-seo-featured-image.js
Labels: changelog: non-user-facing

#14627 Stop forcing WP_Post object
  admin/links/class-link-watcher.php
  integration-tests/admin/links/test-class-link-watcher.php
Labels: changelog: bugfix

#14633 Attachment redirects should be a 301
  src/integrations/front-end/redirects.php
  tests/integrations/front-end/redirects-test.php
Labels: changelog: bugfix

#14621 Lazily update indexable hierarchy
  src/integrations/watchers/option-titles-watcher.php
  src/repositories/indexable-hierarchy-repository.php
  src/repositories/indexable-repository.php
  tests/integrations/watchers/option-titles-watcher-test.php
  tests/repositories/indexable-hierarchy-repository-test.php
  tests/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing

#14637 Use proper fallback for the Woocommerce shop page
  src/integrations/third-party/woocommerce.php
  tests/integrations/third-party/woocommerce-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14640 Temporary disable the deprecation notices for schema.
  deprecated/frontend/schema/class-schema-article.php
  deprecated/frontend/schema/class-schema-author.php
  deprecated/frontend/schema/class-schema-breadcrumb.php
  deprecated/frontend/schema/class-schema-faq-question-list.php
  deprecated/frontend/schema/class-schema-faq-questions.php
  deprecated/frontend/schema/class-schema-faq.php
  deprecated/frontend/schema/class-schema-howto.php
  deprecated/frontend/schema/class-schema-image.php
  deprecated/frontend/schema/class-schema-main-image.php
  deprecated/frontend/schema/class-schema-organization.php
  deprecated/frontend/schema/class-schema-person.php
  deprecated/frontend/schema/class-schema-utils.php
  deprecated/frontend/schema/class-schema-webpage.php
  deprecated/frontend/schema/class-schema-website.php
  deprecated/frontend/schema/class-schema.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14656 Bump monorepo packages for 13.4
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14645 Drop og:image:secure_url
  src/presenters/open-graph/image-presenter.php
  tests/presenters/open-graph/image-presenter-test.php
Labels: changelog: enhancement

#14660 Add aliases for Initializer, Integration and Loadable
  src/initializers/initializer-interface.php
  src/integrations/integration-interface.php
  src/loadable-interface.php
Labels: changelog: non-user-facing

#14655 Removal of @since where possible
  src/backwards-compatibility/frontend.php
  src/generators/schema/author.php
  src/generators/schema/breadcrumb.php
  src/generators/schema/faq.php
  src/generators/schema/howto.php
  src/generators/schema/main-image.php
  src/generators/schema/organization.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/generators/schema/website.php
  src/helpers/schema/id-helper.php
  src/integrations/front-end/comment-link-fixer.php
  src/integrations/front-end/indexing-controls.php
  src/integrations/front-end/rss-footer-embed.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14663 Move Schema constants to a config class
  src/config/schema-ids.php
  src/context/meta-tags-context.php
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/breadcrumb.php
  src/generators/schema/main-image.php
  src/generators/schema/organization.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/generators/schema/website.php
  src/helpers/schema/id-helper.php
  tests/generators/schema/article-test.php
  tests/generators/schema/author-test.php
  tests/generators/schema/breadcrumb-test.php
  tests/generators/schema/main-image-test.php
  tests/generators/schema/organization-test.php
  tests/helpers/schema/id-helper-test.php
Labels: changelog: non-user-facing, component: indexables

#14661 Add helpers surface to easily access helpers externally
  src/main.php
  src/surfaces/helpers-surface.php
  src/surfaces/open-graph-helpers-surface.php
  src/surfaces/schema-helpers-surface.php
  src/surfaces/twitter-helpers-surface.php
Labels: component: indexables

#14652 Fix fatal in term builder
  src/builders/indexable-hierarchy-builder.php
  src/builders/indexable-term-builder.php
  tests/builders/indexable-hierarchy-builder-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation

#14657 Fix logging for non text/html requests
  src/loggers/database-logger.php
Labels: changelog: non-user-facing, component: indexables

#14669 Bump monorepo packages for 14.0-RC1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14659 Our own title tag is only removed is force rewriting of the title is disabled.
  src/integrations/front-end-integration.php
  tests/integrations/front-end-integration-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables

#14670 Add is_wp_error check
  src/builders/indexable-hierarchy-builder.php
Labels: 0.5, changelog: non-user-facing, component: indexables, component: innovation

#14673 Fix deprecated schema pieces
  deprecated/frontend/schema/class-schema-article.php
  deprecated/frontend/schema/class-schema-author.php
  deprecated/frontend/schema/class-schema-breadcrumb.php
  deprecated/frontend/schema/class-schema-faq-question-list.php
  deprecated/frontend/schema/class-schema-faq-questions.php
  deprecated/frontend/schema/class-schema-faq.php
  deprecated/frontend/schema/class-schema-howto.php
  deprecated/frontend/schema/class-schema-ids.php
  deprecated/frontend/schema/class-schema-image.php
  deprecated/frontend/schema/class-schema-main-image.php
  deprecated/frontend/schema/class-schema-organization.php
  deprecated/frontend/schema/class-schema-person.php
  deprecated/frontend/schema/class-schema-utils.php
  deprecated/frontend/schema/class-schema-webpage.php
  deprecated/frontend/schema/class-schema-website.php
  deprecated/frontend/schema/class-schema.php
  deprecated/frontend/schema/interface-wpseo-graph-piece.php
Labels: changelog: non-user-facing

#14674 Sets the deprecated version to 14.0
  admin/class-admin-init.php
  deprecated/frontend/class-handle-404.php
  deprecated/frontend/class-opengraph-image.php
  deprecated/frontend/class-opengraph-oembed.php
  deprecated/frontend/class-opengraph.php
  deprecated/frontend/class-primary-category.php
  deprecated/frontend/class-twitter.php
  frontend/class-woocommerce-shop-page.php
  inc/wpseo-functions-deprecated.php
  inc/wpseo-functions.php
  src/backwards-compatibility/frontend.php
  src/integrations/front-end/theme-titles.php
  tests/integrations/front-end/theme-titles-test.php
  wp-seo-main.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14505 14386 create social containers
  js/src/components/portals/SocialMetadataPortal.js
  js/src/components/social/FacebookWrapper.js
  js/src/components/social/SocialForm.js
  js/src/components/social/SocialMetadata.js
  js/src/components/social/SocialUpsell.js
  js/src/components/social/TwitterWrapper.js
  js/src/containers/Facebook.js
  js/src/containers/Twitter.js
  js/src/redux/actions/index.js
  js/src/redux/actions/social.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/settings.js
  js/src/redux/selectors/snippetEditor.js
  js/src/redux/selectors/social.js
  js/src/redux/selectors/socialSelectors.js
Labels: changelog: non-user-facing

#14678 Change backward compatibility of person schema to include protected functionality
  deprecated/frontend/schema/class-schema-person.php
Labels: changelog: non-user-facing
