Repository Yoast/wordpress-seo, pull requests merged in 2020-02, with the labels that each got.

#14323 Merge pull request #14323 from Yoast/bump-monorepo-packages-for-13.0
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14308 Add inlanguage property to the schema CreativeWork pieces
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-faq-questions.php
  frontend/schema/class-schema-howto.php
  frontend/schema/class-schema-image.php
  frontend/schema/class-schema-utils.php
  frontend/schema/class-schema-webpage.php
  frontend/schema/class-schema-website.php
  tests/frontend/schema/schema-faq-questions-test.php
  tests/frontend/schema/schema-how-to-test.php
  tests/frontend/schema/schema-image-test.php
Labels: changelog: enhancement

#14319 Remove the Search Console menu item
  admin/menu/class-base-menu.php
  inc/class-wpseo-admin-bar-menu.php
Labels: UI change, changelog: other

#14309 Set the Schema HowTo name and Article headline to the post title with a fallback
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-howto.php
  frontend/schema/class-schema-utils.php
  tests/frontend/schema/schema-how-to-test.php
Labels: changelog: enhancement

#14314 Allow the SEO Manager role to view the Site Health checks.
  admin/capabilities/class-register-capabilities.php
  inc/class-upgrade.php
Labels: changelog: enhancement

#14325 Merge pull request #14325 from Yoast/bump-monorepo-packages-for-13.1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14149 Add cURL version test to Site Health
  admin/class-admin-init.php
  inc/class-addon-manager.php
  inc/health-check-curl-version.php
  tests/inc/health-check-curl-version-test.php
  tests/inc/health-check-default-tagline-test.php
  tests/inc/health-check-postname-permalink-test.php
Labels: changelog: enhancement, component: site health

#14123 Move Ryte integration to site health
  admin/ajax.php
  admin/class-admin-init.php
  admin/class-yoast-dashboard-widget.php
  admin/onpage/class-onpage.php
  admin/onpage/class-ryte-service.php
  admin/ryte/class-ryte-option.php
  admin/ryte/class-ryte-request.php
  admin/ryte/class-ryte.php
  admin/tracking/class-tracking-settings-data.php
  admin/views/class-yoast-feature-toggles.php
  css/src/admin-global.scss
  deprecated/admin/ajax/class-yoast-onpage-ajax.php
  deprecated/admin/endpoints/class-endpoint-ryte.php
  deprecated/admin/onpage/class-onpage-option.php
  deprecated/admin/onpage/class-onpage-request.php
  deprecated/admin/onpage/class-onpage.php
  deprecated/admin/onpage/class-ryte-service.php
  inc/class-upgrade.php
  inc/health-check-ryte.php
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  integration-tests/doubles/onpage-option-mock.php
  integration-tests/doubles/wpseo-onpage-double.php
  integration-tests/doubles/wpseo-onpage-request-double.php
  integration-tests/inc/options/test-class-wpseo-option-wpseo.php
  integration-tests/inc/options/test-class-wpseo-options.php
  integration-tests/onpage/test-class-onpage.php
  integration-tests/onpage/test-class-ryte-service.php
  integration-tests/ryte/test-class-ryte-option.php
  integration-tests/ryte/test-class-ryte-request.php
  integration-tests/ryte/test-class-ryte.php
  js/src/wp-seo-dashboard-widget.js
  tests/inc/health-check-ryte-test.php
  wp-seo-main.php
Labels: UI change, changelog: other

#14331 Remove yoast class from wrapper div
  admin/class-yoast-form.php
  admin/pages/dashboard.php
  admin/pages/metas.php
  admin/pages/social.php
  admin/pages/tools.php
  admin/views/licenses.php
Labels: changelog: non-user-facing

#14328 Remove unneccessary css
  Gruntfile.js
  admin/class-admin-asset-manager.php
  admin/class-admin.php
  admin/class-config.php
  css/src/_colors.scss
  css/src/_icons.scss
  css/src/_yoastseo.scss
  css/src/admin/_wp.scss
  css/src/admin/adminbar.scss
  css/src/admin/dashboard.scss
  css/src/admin/tabs.scss
  css/src/admin/yoast-components.scss
  css/src/editor/_score_icon.scss
  css/src/editor/_yoastseo.scss
  css/src/editor/edit-page.scss
  css/src/editor/featured-image.scss
  css/src/editor/metabox-primary-category.scss
  css/src/editor/metabox.scss
  css/src/editor/post-overview-global.scss
  css/src/editor/structured-data-blocks.scss
  css/src/editor/yst_plugin_tools.scss
  css/src/extensions.scss
  css/src/inside-editor.scss
  css/src/search-appearance.scss
  css/src/to-be-removed/admin-global.scss
  css/src/to-be-removed/alerts.scss
  css/src/to-be-removed/filter-explanation.scss
  css/src/to-be-removed/inside-editor.scss
  css/src/to-be-removed/toggle-switch.scss
  css/src/to-be-removed/wpseo-dismissible.scss
  css/src/to-be-removed/yst_plugin_tools.scss
  css/src/to-be-removed/yst_seo_score.scss
  css/src/user-selector.scss
  css/src/yoastcom/0-settings/_all.scss
  css/src/yoastcom/0-settings/_color.scss
  css/src/yoastcom/0-settings/_type.scss
  css/src/yoastcom/0-settings/_units.scss
  css/src/yoastcom/0-tools/_mixins.scss
  css/src/yoastcom/_bordered.scss
  css/src/yoastcom/_buttons.scss
  css/src/yoastcom/_headings.scss
  css/src/yoastcom/_lists.scss
  css/src/yoastcom/_promoblock.scss
  css/src/yoastcom/_variables.scss
Labels: UI change, changelog: enhancement

#14324 13825 generate replace vars object renaming
  src/backwards-compatibility/frontend.php
  src/context/meta-tags-context.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  src/presenters/abstract-indexable-presenter.php
  tests/presentations/indexable-post-type-presentation/og-article-author-test.php
  tests/presentations/indexable-post-type-presentation/og-article-modified-time-test.php
  tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php
  tests/presentations/indexable-post-type-presentation/replace-vars-object-test.php
  tests/presentations/indexable-post-type-presentation/twitter-creator-test.php
  tests/presentations/indexable-presentation/replace-vars-object-test.php
  tests/presentations/indexable-term-archive-presentation/canonical-test.php
  tests/presentations/indexable-term-archive-presentation/replace-vars-object-test.php
  tests/presentations/indexable-term-archive-presentation/robots-test.php
  tests/presentations/indexable-term-archive-presentation/title-test.php
  tests/presenters/open-graph/description-presenter-test.php
  tests/presenters/open-graph/title-presenter-test.php
  tests/presenters/title-presenter-test.php
  tests/presenters/twitter/description-presenter-test.php
  tests/presenters/twitter/title-presenter-test.php
Labels: changelog: non-user-facing

#14311 Check whether all OG and Twitter filters are correct
  admin/class-admin-init.php
  src/conditionals/jetpack-conditional.php
  src/integrations/third-party/jetpack.php
  src/presenters/open-graph/title-presenter.php
  tests/conditionals/jetpack-conditional-test.php
  tests/presenters/open-graph/title-presenter-test.php
Labels: changelog: non-user-facing

#14275 Reset indexables permalink after settings change
  src/generators/schema-generator.php
  src/integrations/watchers/indexable-permalink-watcher.php
  src/memoizers/meta-tags-context-memoizer.php
  tests/integrations/watchers/indexable-permalink-watcher-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14333 Update heading styling
  css/src/admin/all.scss
  css/src/components/headings.scss
  css/src/to-be-removed/admin-global.scss
Labels: UI change, changelog: non-user-facing

#14336 Improve the Ryte health check "cannot be indexed" copy
  inc/health-check-ryte.php
Labels: changelog: enhancement

#14340 Add design implementation issue template
  .github/ISSUE_TEMPLATE/Design_implementation.md
Labels: changelog: non-user-facing

#14339 Improve Ryte site health checks usability
  admin/ryte/class-ryte-option.php
  admin/ryte/class-ryte.php
  inc/health-check-ryte.php
  tests/inc/health-check-ryte-test.php
Labels: changelog: enhancement, component: site health

#14345 Create post helper
  src/helpers/post-helper.php
  src/helpers/post-type-helper.php
  src/presentations/indexable-post-type-presentation.php
  tests/presentations/indexable-post-type-presentation/og-article-published-time-test.php
  tests/presentations/indexable-post-type-presentation/og-description-test.php
  tests/presentations/indexable-post-type-presentation/presentation-instance-builder.php
  tests/presentations/indexable-post-type-presentation/twitter-description-test.php
  tests/presentations/indexable-static-home-page-presentation/presentation-instance-builder.php
  tests/presentations/indexable-static-posts-page-presentation/presentation-instance-builder.php
Labels: 0.5

#14334 Add an ID to the FAQ sections output
  js/src/structured-data-blocks/faq/block.js
  js/src/structured-data-blocks/faq/components/Question.js
  js/src/structured-data-blocks/faq/legacy/13.1.js
  js/src/structured-data-blocks/faq/legacy/index.js
  js/src/structured-data-blocks/how-to/block.js
Labels: changelog: enhancement

#14354 Remove content image fallback for Open Graph and Twitter
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/helpers/image-helper.php
  tests/builders/indexable-term-builder-test.php
  tests/helpers/image-helper-test.php
Labels: changelog: non-user-facing

#14350 Merges the indexable migrations into the first initial migration.
  migrations/20171228151840_WpYoastIndexable.php
  migrations/20190529075734_WpYoastExpandIndexable.php
  migrations/20190925153544_WpYoastAddTwitterCardField.php
  migrations/20190930094459_WpYoastIndexablesExpandObjectTypeColumn.php
  migrations/20191001101822_WpYoastIndexablesAddOpenGraphImageID.php
  migrations/20191008131020_WpYoastIndexablesAddImageFields.php
  migrations/20191011105120_WpYoastIndexablesAddOGImageMetaField.php
  migrations/20191021131550_WpYoastRemoveTwitterCardField.php
  migrations/20191029111111_WpYoastProminentWordIndexableColumn.php
  migrations/20191211144248_WpYoastIndexablesAddIsPublicField.php
  migrations/20200121154000_WpYoastIndexablesAddFields.php
Labels: changelog: non-user-facing

#14371 Show FAQPage as page type in schema output
  src/generators/schema-generator.php
Labels: changelog: non-user-facing

#14373 Remove dismiss tagline notice remnants
  admin/ajax.php
  admin/class-admin.php
  js/src/wp-seo-admin-global.js
Labels: changelog: enhancement

#14372 Handle the Ryte API response errors
  admin/ryte/class-ryte-request.php
  admin/ryte/class-ryte.php
  inc/health-check-ryte.php
  tests/inc/health-check-ryte-test.php
Labels: changelog: enhancement

#14093 Introduce surfaces
  inc/class-wpseo-admin-bar-menu.php
  src/functions.php
  src/loader.php
  src/main.php
  src/surfaces/classes-surface.php
  src/surfaces/current-page-surface.php
  wp-seo-main.php
Labels: 2, changelog: non-user-facing, needs-pair

#14364 Fixes Schema on author archives and 404-pages
  src/context/meta-tags-context.php
  src/generators/schema/author.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/helpers/site-helper.php
  tests/_mocks/author.php
  tests/context/meta-tags-context-test.php
  tests/generators/schema/author-test.php
  tests/generators/schema/person.php
Labels: changelog: non-user-facing

#14382 Remove the "get headers" item from the adminbar
  inc/class-wpseo-admin-bar-menu.php
Labels: changelog: bugfix, has patch

#14378 Implement site health checks
  admin/ajax.php
  admin/capabilities/class-register-capabilities.php
  admin/class-admin-init.php
  admin/class-admin.php
  admin/class-yoast-dashboard-widget.php
  admin/onpage/class-onpage-request.php
  admin/onpage/class-onpage.php
  admin/onpage/class-ryte-service.php
  admin/ryte/class-ryte-option.php
  admin/ryte/class-ryte-request.php
  admin/ryte/class-ryte.php
  admin/tracking/class-tracking-settings-data.php
  admin/views/class-yoast-feature-toggles.php
  css/src/admin-global.scss
  deprecated/admin/ajax/class-yoast-onpage-ajax.php
  deprecated/admin/endpoints/class-endpoint-ryte.php
  deprecated/admin/onpage/class-onpage-option.php
  deprecated/admin/onpage/class-onpage-request.php
  deprecated/admin/onpage/class-onpage.php
  deprecated/admin/onpage/class-ryte-service.php
  inc/class-addon-manager.php
  inc/class-upgrade.php
  inc/health-check-curl-version.php
  inc/health-check-default-tagline.php
  inc/health-check-page-comments.php
  inc/health-check-postname-permalink.php
  inc/health-check-ryte.php
  inc/health-check.php
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  integration-tests/doubles/onpage-option-mock.php
  integration-tests/doubles/wpseo-onpage-double.php
  integration-tests/doubles/wpseo-onpage-request-double.php
  integration-tests/inc/options/test-class-wpseo-option-wpseo.php
  integration-tests/inc/options/test-class-wpseo-options.php
  integration-tests/onpage/test-class-onpage.php
  integration-tests/onpage/test-class-ryte-service.php
  integration-tests/ryte/test-class-ryte-option.php
  integration-tests/ryte/test-class-ryte-request.php
  integration-tests/ryte/test-class-ryte.php
  js/src/wp-seo-admin-global.js
  js/src/wp-seo-dashboard-widget.js
  tests/inc/health-check-curl-version-test.php
  tests/inc/health-check-default-tagline-test.php
  tests/inc/health-check-page-comments-test.php
  tests/inc/health-check-postname-permalink-test.php
  tests/inc/health-check-ryte-test.php
  tests/inc/health-check-test.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#14390 Bump monorepo packages for 13.1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14376 Update styling buttons
  admin/class-admin-asset-manager.php
  admin/class-bulk-editor-list-table.php
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-form.php
  admin/links/class-link-reindex-dashboard.php
  admin/notifiers/class-configuration-notifier.php
  admin/views/sidebar.php
  admin/views/tabs/tool/wpseo-export.php
  admin/views/tabs/tool/wpseo-import.php
  css/src/admin/all.css
  css/src/admin/all.scss
  css/src/base/_colors.scss
  css/src/base/_icons.scss
  css/src/base/colors.css
  css/src/base/icons.css
  css/src/components/buttons.css
  css/src/components/headings.css
  css/src/components/headings.scss
  css/src/components/tabs.css
  css/src/editor/post-overview-global.scss
Labels: UI change, changelog: non-user-facing

#14397 The twitter title tag for archives now use the default logic for indexables.
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-date-archive-presentation.php
  tests/presentations/indexable-author-archive-presentation/twitter-title-test.php
  tests/presentations/indexable-date-archive-presentation/twitter-title-test.php
Labels: changelog: non-user-facing

#14278 Introduces a method for retrieving the value from the options
  admin/class-yoast-form.php
Labels: 0.5, has patch, owner: development, technical-debt, type: development

#14405 Fixes the breadcrumbs shortcode.
  src/integrations/breadcrumbs-integration.php
  src/surfaces/current-page-surface.php
  tests/integrations/breadcrumbs-integration-test.php
Labels: changelog: non-user-facing

#14394 `og:image:width` and `og:image:height` are now output on the homepage
  src/builders/indexable-home-page-builder.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-social-image-trait.php
  src/helpers/open-graph/image-helper.php
  src/values/open-graph/images.php
  tests/builders/indexable-home-page-builder-test.php
  tests/helpers/open-graph/image-helper-test.php
  tests/values/images-tests.php
  tests/values/open-graph/images-test.php
Labels: changelog: non-user-facing

#14400 Port the schema inLanguage changes from 14308 to the indexables branch
  deprecated/frontend/schema/class-schema-utils.php
  src/generators/schema/article.php
  src/generators/schema/faq.php
  src/generators/schema/howto.php
  src/generators/schema/webpage.php
  src/generators/schema/website.php
  src/helpers/schema/image-helper.php
  src/helpers/schema/language-helper.php
  src/helpers/site-helper.php
  tests/generators/schema/article-test.php
  tests/generators/schema/website-test.php
  tests/helpers/schema/image-helper-test.php
Labels: changelog: enhancement

#14388 14302 remove floating save button
  admin/class-yoast-form.php
  admin/pages/dashboard.php
  admin/pages/metas.php
  admin/pages/social.php
  js/src/wp-seo-admin.js
Labels: UI change, changelog: non-user-facing

#14408 Remove the readfile try - go straight into the wp_remote_get
  admin/class-my-yoast-proxy.php
  tests/admin/myyoast-proxy-test.php
Labels: changelog: non-user-facing

#14411 Consider static homepages to be a singular page
  src/integrations/front-end-integration.php
Labels: changelog: non-user-facing

#14414 14407 create redux store images
  admin/formatter/class-metabox-formatter.php
  js/src/edit.js
  js/src/redux/reducers/settings.js
  js/tests/redux/actions/settings.test.js
  js/tests/redux/reducers/settings.test.js
Labels: changelog: non-user-facing

#14424 Changes cURL Health Check status from recommended to critical
  inc/health-check-curl-version.php
  tests/inc/health-check-curl-version-test.php
Labels: changelog: other

#14341 Add potentialAction to webpage and article Schema
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-webpage.php
Labels: changelog: enhancement

#14410 Port 14309 to the indexables branch.
  deprecated/frontend/schema/class-schema-utils.php
  src/generators/schema/article.php
  src/generators/schema/howto.php
  src/helpers/post-helper.php
  tests/generators/schema/article-test.php
  tests/helpers/post-helper-test.php
Labels: changelog: enhancement

#14413 Port 14012 to the Indexables branch.
  src/generators/schema/article.php
  src/generators/schema/webpage.php
  tests/generators/schema/article-test.php
Labels: changelog: enhancement

#14437 add fallback selectors for imageUrl, title and description
  admin/formatter/class-metabox-formatter.php
  js/src/edit.js
  js/src/redux/selectors/fallbackSelectors.js
  js/src/redux/selectors/index.js
  js/tests/redux/selectors/fallbackSelectors.test.js
Labels: changelog: non-user-facing

#14342 Don't sanitize properly encoded URL
  inc/class-wpseo-utils.php
Labels: community-patch

#14396 Change HTML and CSS for nav tabs
  admin/class-option-tabs-formatter.php
  css/src/base/colors.css
  css/src/components/tabs.css
  css/src/editor/post-overview-global.scss
  css/src/editor/yst_plugin_tools.scss
  js/src/wp-seo-admin.js
Labels: UI change, changelog: non-user-facing

#14444 Class configuration page cscleanup
  admin/config-ui/class-configuration-page.php
  inc/class-rewrite.php
  inc/sitemaps/class-sitemaps-router.php
Labels: changelog: non-user-facing

#14417 Code coverage presentation tests
  src/presentations/abstract-presentation.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  tests/_mocks/abstract_presentation.php
  tests/presentations/abstract_presentation_test.php
  tests/presentations/indexable-post-type-presentation/open-graph-article-publisher-test.php
Labels: 0.5, changelog: non-user-facing, component: indexables
