Repository Yoast/wordpress-seo, pull requests merged in 2020-07, with the labels that each got.

#15525 P2 22 Introduce indexables indexation completed option
  admin/tracking/class-tracking-settings-data.php
  inc/class-upgrade.php
  inc/options/class-wpseo-option-wpseo.php
  src/actions/indexables/indexable-complete-indexation-action.php
  src/commands/index-command.php
  src/integrations/admin/indexation-integration.php
  src/routes/indexable-indexation-route.php
  tests/actions/indexables/indexable-complete-indexation-action-test.php
  tests/commands/index-command-test.php
  tests/integrations/admin/indexation-integration-test.php
  tests/routes/indexable-indexation-route-test.php
Labels: changelog: non-user-facing

#15590 Add image validation to Social previews
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
  js/src/redux/reducers/facebookEditor.js
  js/src/redux/reducers/twitterEditor.js
Labels: changelog: non-user-facing

#15601 Add contentImage and snippetPreviewImageUrl variables to nonReplaceVars
  js/src/helpers/replacementVariableHelpers.js
Labels: changelog: non-user-facing

#15608 Bump plugin-grunt-tasks, drops sass dependency
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15493 QA: tweak some prepared SQL statements
  admin/import/plugins/class-abstract-plugin-importer.php
  admin/import/plugins/class-import-squirrly.php
  inc/class-upgrade.php
  src/actions/indexation/indexable-post-indexation-action.php
  src/actions/indexation/indexable-term-indexation-action.php
  src/integrations/watchers/option-titles-watcher.php
  tests/actions/indexation/indexable-post-indexation-action-test.php
  tests/actions/indexation/indexable-term-indexation-action-test.php
  tests/integrations/watchers/option-titles-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15614 FRO-177 Restore Yoast settings styling on the user profile page.
  admin/class-admin-asset-manager.php
  admin/class-admin-user-profile.php
  css/src/admin/user-profile.css
Labels: changelog: non-user-facing

#15615 Fro 134 update upsell block 2
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-form.php
  admin/views/licenses.php
  admin/views/sidebar.php
  css/src/components/buttons.css
  css/src/components/lists.css
  css/src/components/paper.css
  css/src/components/sidebar.css
Labels: changelog: non-user-facing

#15611 Siblings and subpages block fixes
  src/config/migrations/20200702141921_CreateIndexableSubpagesIndex.php
  src/integrations/blocks/abstract-dynamic-block.php
  src/repositories/indexable-repository.php
Labels: changelog: non-user-facing

#15362 P2-28 Cache unindexed counts for a day
  src/actions/indexation/indexable-post-indexation-action.php
  src/actions/indexation/indexable-post-type-archive-indexation-action.php
  src/actions/indexation/indexable-term-indexation-action.php
  src/repositories/indexable-repository.php
  tests/actions/indexation/indexable-post-indexation-action-test.php
  tests/actions/indexation/indexable-post-type-archive-indexation-action-test.php
  tests/actions/indexation/indexable-term-indexation-action-test.php
  tests/repositories/indexable-repository-test.php
Labels: changelog: bugfix

#15610 Fix CS in functions
  admin/class-admin-asset-yoast-components-l10n.php
  admin/config-ui/class-configuration-translations.php
  admin/formatter/class-metabox-formatter.php
  admin/import/plugins/class-import-rankmath.php
  admin/tracking/class-tracking-server-data.php
  config/dependency-injection/custom-loader.php
  integration-tests/inc/test-class-wpseo-upgrade.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-cache-data.php
  integration-tests/sitemaps/test-class-wpseo-sitemaps-cache.php
  src/integrations/front-end-integration.php
Labels: changelog: non-user-facing

#15604 P3-60 Add basic SEMrush modal container
  images/Yoast_icon_kader.svg
  js/src/components/RelatedKeyphraseModalContent.js
  js/src/components/RelatedKeyphrasesModal.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/containers/SEMrushRelatedKeyphrases.js
  js/src/initializers/edit.js
Labels: changelog: non-user-facing

#15597 XMLRPC noindexing
  src/conditionals/xmlrpc-conditional.php
  src/integrations/xmlrpc.php
  tests/integrations/xmlrpc-test.php
Labels: changelog: enhancement

#15617 Fixes a bug where core/link format isn't available anymore
  js/src/inline-links/edit-link.js
  js/src/inline-links/utils.js
Labels: changelog: bugfix

#15603 P1-49 Decrease the time it takes to run yarn start
  package.json
Labels: changelog: non-user-facing

#15621 Revert tracking config wizard
  admin/config-ui/class-configuration-storage.php
  admin/config-ui/class-configuration-structure.php
  admin/config-ui/fields/class-field-tracking-intro.php
  admin/config-ui/fields/class-field-tracking.php
  admin/tracking/class-tracking.php
  admin/views/class-yoast-feature-toggles.php
  inc/options/class-wpseo-option-wpseo.php
  integration-tests/config-ui/test-class-configuration-structure.php
  js/tests/__snapshots__/advancedSettings.test.js.snap
Labels: changelog: non-user-facing

#15606 P1-17 Create the schema tab component
  admin/metabox/class-metabox.php
  css/src/metabox.css
  inc/class-wpseo-meta.php
  inc/class-wpseo-utils.php
  js/src/components/SchemaTab.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/containers/SchemaTab.js
Labels: changelog: enhancement

#15624 Show a bottom border for the metabox container
  css/src/metabox.css
  js/tests/__snapshots__/advancedSettings.test.js.snap
Labels: changelog: bugfix

#15625 Turns disable core sitemaps into an initializer
  src/initializers/disable-core-sitemaps.php
  tests/initializers/disable-core-sitemaps-test.php
Labels: changelog: non-user-facing

#15631 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15618 P3-73 Create an "Integrations" tab in the General settings of Yoast SEO
  admin/pages/dashboard.php
  admin/tracking/class-tracking-settings-data.php
  admin/views/class-yoast-integration-toggles.php
  admin/views/tabs/dashboard/integrations.php
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  integration-tests/inc/options/test-class-wpseo-option-wpseo.php
Labels: changelog: non-user-facing

#15634 Remove snapshot tests
  js/tests/__snapshots__/advancedSettings.test.js.snap
  js/tests/advancedSettings.test.js
  js/tests/components/CompanyInfoMissing.test.js
  js/tests/components/CompanyInfoMissingOnboardingWizard.test.js
  js/tests/components/CornerstoneToggleTest.js
  js/tests/components/LocalSEOUpsell.test.js
  js/tests/components/SnippetPreviewSection.test.js
  js/tests/components/UpsellBox.test.js
  js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap
  js/tests/components/__snapshots__/CompanyInfoMissingOnboardingWizard.test.js.snap
  js/tests/components/__snapshots__/CornerstoneToggleTest.js.snap
  js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/components/__snapshots__/UpsellBox.test.js.snap
Labels: changelog: non-user-facing

#15607 Adds OAuth for communication with SEMrush API.
  admin/tracking/class-tracking-settings-data.php
  config/dependency-injection/services.php
  inc/options/class-wpseo-option-wpseo.php
  js/tests/__snapshots__/advancedSettings.test.js.snap
  js/tests/components/__snapshots__/CompanyInfoMissing.test.js.snap
  js/tests/components/__snapshots__/LocalSEOUpsell.test.js.snap
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/components/__snapshots__/UpsellBox.test.js.snap
  src/actions/semrush/semrush-login-action.php
  src/config/semrush-client.php
  src/exceptions/oauth/oauth-authentication-failed-exception.php
  src/exceptions/oauth/oauth-expired-token-exception.php
  src/exceptions/oauth/oauth-failed-token-storage-exception.php
  src/exceptions/semrush/semrush-empty-token-exception.php
  src/exceptions/semrush/semrush-empty-token-property-exception.php
  src/exceptions/semrush/semrush-failed-token-storage-exception.php
  src/routes/semrush-route.php
  src/values/semrush/semrush-token.php
  tests/actions/semrush/semrush-login-action-test.php
  tests/config/semrush-client-test.php
  tests/doubles/config/semrush-client-double.php
  tests/routes/semrush-route-test.php
  tests/values/semrush/semrush-token-test.php
Labels: changelog: non-user-facing

#15630 Added proper check for whether Premium is active or not.
  js/src/initializers/edit.js
Labels: changelog: non-user-facing

#15636 Bump @yoast/social-metadata-forms
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15598 Add cron conditional
  src/conditionals/cron-conditional.php
  tests/conditionals/cron-conditional-test.php
Labels: changelog: non-user-facing

#15638 P2-84-yoast-didnt-recognize-my-keyphrase-not-shown
  admin/formatter/class-metabox-formatter.php
Labels: changelog: non-user-facing

#15632 Adds a term_value method
  src/helpers/meta-helper.php
Labels: changelog: non-user-facing, type: development

#15612 P2-82 These methods are moved to premium
  src/repositories/indexable-repository.php
Labels: changelog: non-user-facing

#15648 Optimize script and style loading
  admin/class-admin-asset-manager.php
  admin/class-asset.php
  integration-tests/test-class-admin-asset.php
Labels: changelog: enhancement

#15605 Update checkbox to new styling
  admin/class-yoast-form.php
  js/tests/__snapshots__/advancedSettings.test.js.snap
Labels: UI change

#15649 Convert person selection warning to Alert
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  js/src/components/WordPressUserSelectorSearchAppearance.js
Labels: UI change, type: development

#15532 Add Web Stories integration
  src/conditionals/web-stories-conditional.php
  src/integrations/third-party/web-stories.php
  tests/conditionals/web-stories-conditional-test.php
  tests/integrations/third-party/web-stories-test.php
Labels: changelog: enhancement, community-patch

#15646 Remove an unused method
  src/repositories/indexable-repository.php
Labels: changelog: non-user-facing

#15647 FRO-217 title scrollbar windows fix
  js/src/components/MetaboxCollapsible.js
Labels: changelog: non-user-facing

#15639 P1-56 Fix word form recognition check
  js/src/analysis/isWordFormRecognitionActive.js
Labels: changelog: non-user-facing

#15655 Prevent conflicts by making ids configurable.
  js/src/indexation.js
  src/integrations/admin/indexation-integration.php
  src/presenters/admin/indexation-modal-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-modal-presenter-test.php
Labels: changelog: non-user-facing

#15653 Fro 194 console error cornerstone overview
  admin/class-admin-asset-manager.php
  admin/filters/class-abstract-post-filter.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  css/src/editor/post-overview-global.css
Labels: changelog: non-user-facing

#15662 QAK-2042 Restrict og:title change to single URLs
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
Labels: changelog: non-user-facing

#15658 Do not strip slashes from the title and og:title, these are already b…
  src/presenters/open-graph/title-presenter.php
  src/presenters/title-presenter.php
Labels: changelog: bugfix

#15650 Add a filter for the graph piece's type
  src/generators/schema-generator.php
Labels: changelog: other

#15664 Use title as facebook title fallback
  js/src/redux/selectors/fallbacks.js
  js/tests/redux/selectors/fallbackSelectors.test.js
Labels: changelog: non-user-facing

#15668 Cleanup console notifications
  inc/class-wpseo-utils.php
  js/src/admin-global.js
Labels: changelog: non-user-facing

#15670 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15660 Inline link aria-label fix
  js/src/inline-links/utils.js
Labels: changelog: bugfix

#15635 P1-13 Populate hidden input field in schema tab with data
  inc/class-wpseo-meta.php
  js/src/containers/SchemaTab.js
Labels: changelog: non-user-facing

#15676 Only fall back to og:image in Twitter preview if og is enabled
  js/src/components/social/SocialMetadata.js
  js/src/redux/selectors/fallbacks.js
  js/tests/redux/selectors/fallbackSelectors.test.js
Labels: changelog: non-user-facing

#15619 Remove option to control showing date in google preview
  admin/formatter/class-post-metabox-formatter.php
  admin/tracking/class-tracking-settings-data.php
  admin/views/class-view-utils.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  inc/options/class-wpseo-option-titles.php
  integration-tests/formatter/test-post-metabox-formatter.php
Labels: UI change, changelog: other

#15680 Fix jumping Google Preview modal
  js/src/components/SnippetPreviewModal.js
Labels: changelog: non-user-facing

#15681 Use term_title as fallback for terms rather than empty replacevar title
  js/src/redux/selectors/fallbacks.js
  js/tests/redux/selectors/fallbackSelectors.test.js
Labels: changelog: non-user-facing

#15616 FRO-178 upsell-button metabox
  js/src/components/UpsellBox.js
  js/src/components/modals/KeywordSynonyms.js
  js/src/components/modals/MultipleKeywords.js
Labels: changelog: non-user-facing

#15661 Fix indexation alerts
  js/src/indexation.js
Labels: UI change, changelog: non-user-facing

#15685 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15689 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15688 Show post/term title instead of SEO title as twitter:title
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/presentations/indexable-post-type-presentation/twitter-title-test.php
  tests/presentations/indexable-term-archive-presentation/twitter-title-test.php
Labels: changelog: non-user-facing

#15691 P1-67 Prefix block names with Yoast
  js/src/structured-data-blocks/faq/block.js
  js/src/structured-data-blocks/how-to/block.js
Labels: UI change, changelog: non-user-facing

#15672 Fix `grunt watch`
  Gruntfile.js
  composer.json
  config/composer/actions.php
  grunt/config/aliases.yaml
  grunt/config/clean.js
  grunt/config/eslint.js
  grunt/config/postcss.js
  grunt/config/shell.js
  grunt/config/watch.js
  js/tests/data.test.js
  js/tests/edit.test.js
  js/tests/helpers/factory.js
Labels: changelog: non-user-facing

#15700 Delete phpdoc.xml
  phpdoc.xml
Labels: changelog: non-user-facing

#15701 Delete .removeable-files
  .removeable-files
Labels: changelog: non-user-facing

#15699 Move webpack config to config directory
  Gruntfile.js
  config/webpack/paths.js
  config/webpack/webpack.config.js
  grunt/config/webpack.js
  grunt/custom/bump-rc-version.js
  package.json
Labels: changelog: non-user-facing

#15705 Remove all leftover references to Ruckusing
  .gitattributes
  config/php-codeshift/remove-vendor-prefixing-codemod.php
  grunt/config/copy.js
  grunt/config/shell.js
  ruckusing.conf.php
  tests/bootstrap.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#15698 P1-65 Add example and extra keywords to structured data blocks
  js/src/structured-data-blocks/faq/block.js
  js/src/structured-data-blocks/how-to/block.js
Labels: UI change, changelog: enhancement

#15707 P1-63 Add logo to our block categories
  admin/class-admin-asset-manager.php
  js/src/components/PluginIcon.js
  js/src/initializers/edit.js
Labels: UI change, changelog: enhancement

#15491 QA: no need for a closure when there is a native PHP function
  lib/migrations/adapter.php
Labels: changelog: non-user-facing, yoast cs/qa

#15663 P3-9 add redux for semrush
  js/src/components/RelatedKeyphrasesModal.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/containers/RelatedKeyphrases.js
  js/src/containers/SEMrush.js
  js/src/initializers/edit.js
  js/src/redux/actions/SEMrushKeyphrases.js
  js/src/redux/actions/SEMrushModal.js
  js/src/redux/actions/SEMrushRequest.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/SEMrushKeyphrases.js
  js/src/redux/reducers/SEMrushModal.js
  js/src/redux/reducers/SEMrushRequest.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/SEMrushKeyphrases.js
  js/src/redux/selectors/SEMrushModal.js
  js/src/redux/selectors/SEMrushRequest.js
  js/src/redux/selectors/index.js
Labels: changelog: non-user-facing

#15712 Remove the color of the block category icon.
  js/src/initializers/edit.js
Labels: UI change, changelog: non-user-facing

#15709 Set permissions callback on get_head rest registration
  src/routes/indexables-head-route.php
  tests/routes/indexables-head-route-test.php
Labels: changelog: non-user-facing

#15713 Revert "Changed readfile to get_contents from wp_filesystem"
  inc/sitemaps/class-sitemaps.php
Labels: changelog: bugfix

#15492 QA: don't use double negatives
  inc/class-wpseo-utils.php
Labels: changelog: non-user-facing, yoast cs/qa

#15714 Fix values/images tests
  tests/values/images-test.php
Labels: changelog: non-user-facing

#15715 Make sure to copy the translator comments
  grunt/custom/convert-pot-to-wp.js
Labels: 0, changelog: non-user-facing, component: translations

#15696 Create SEMrush Country Selection component
  js/src/components/RelatedKeyphraseModalContent.js
  js/src/components/modals/CountrySelector.js
  js/src/components/modals/SemRushCountrySelector.js
Labels: changelog: non-user-facing

#15679 P3-77 Read option for SEMrush integration to show or hide the "Get related keyphrases" button
  admin/formatter/class-metabox-formatter.php
  js/src/analysis/isSEMrushIntegrationActive.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#15686 Add unit tests to increase indexables coverage
  src/integrations/admin/indexation-integration.php
  src/presenters/admin/indexation-permalink-warning-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/integrations/watchers/indexable-category-permalink-watcher-test.php
  tests/integrations/watchers/indexable-permalink-watcher-test.php
  tests/presenters/admin/indexation-permalink-warning-presenter-test.php
Labels: changelog: non-user-facing

#15717 Fixes a bug where wpseoShortcodePluginL10n was not defined.
  js/src/post-edit.js
Labels: changelog: bugfix

#15720 Travis: minor tweak
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#15592 P2 41 indexable route should call actions
  src/actions/indexation/indexable-complete-indexation-action.php
  src/actions/indexation/indexable-prepare-indexation-action.php
  src/commands/index-command.php
  src/helpers/date-helper.php
  src/routes/indexable-indexation-route.php
  tests/actions/indexation/indexable-complete-indexation-action-test.php
  tests/actions/indexation/indexable-prepare-indexation-action-test.php
  tests/commands/index-command-test.php
  tests/routes/indexable-indexation-route-test.php
Labels: changelog: non-user-facing

#15729 Remove clip path because it doesn't work any longer
  css/src/metabox.css
Labels: changelog: non-user-facing

#15719 Reset the indexation process when it fails so that it can be start again.
  js/src/indexation.js
Labels: changelog: bugfix

#15673 P3-41 Create keyphrases table
  admin/class-expose-shortlinks.php
  css/src/gutenberg-modal.css
  js/src/components/AreaChart.js
  js/src/components/HelpLink.js
  js/src/components/RelatedKeyphraseModalContent.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/modals/KeyphrasesTable.js
  js/src/components/modals/SemRushLimitReached.js
  js/src/components/modals/SemRushUpsellAlert.js
  js/src/inline-links/inline.js
Labels: changelog: non-user-facing

#15730 Exit after a successful safe redirect from the core sitemaps
  src/initializers/disable-core-sitemaps.php
  tests/initializers/disable-core-sitemaps-test.php
Labels: changelog: non-user-facing

#15725 If we are not premium; disable tracking on plugin activation
  wp-seo-main.php
Labels: changelog: non-user-facing

#15690 P3-81 Add REST endpoint to set country code option for SEMrush
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-wpseo.php
  src/actions/semrush/semrush-options-action.php
  src/routes/semrush-route.php
  tests/routes/semrush-route-test.php
Labels: changelog: non-user-facing

#15733 Bump monorepo packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15641 P1-3 Create schema settings component
  admin/class-admin-asset-manager.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  css/src/search-appearance.css
  inc/options/class-wpseo-option-titles.php
  js/src/components/SchemaSettings.js
  js/src/components/portals/SchemaSettingsPortal.js
  js/src/containers/SchemaSettings.js
  js/src/initializers/search-appearance.js
  js/src/values/SchemaOptions.js
Labels: UI change, changelog: enhancement

#15737 P1-81 Fix schema tab error on term pages
  grunt/config/eslint.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
Labels: changelog: non-user-facing

#15742 Differentiate between sidebar and metabox for language feedback
  js/src/components/contentAnalysis/KeywordInput.js
Labels: changelog: non-user-facing

#15739 Fixes scores in classic editor publish box.
  js/src/ui/publishBox.js
Labels: changelog: bugfix

#15743 P2-146 Fix bugs in the RC automatization pipeline
  grunt/config/aliases.yaml
  grunt/custom/bump-rc-version-and-commit.js
  grunt/custom/bump-rc-version.js
  grunt/custom/github-pre-release.js
Labels: changelog: non-user-facing

#15748 Fixes an issue where default filters were not added back if the option value didn't change
  inc/options/class-wpseo-option.php
Labels: changelog: other

#15702 P1-6 Save schema tab data
  admin/class-config.php
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  inc/class-wpseo-meta.php
  inc/options/class-wpseo-option-titles.php
  integration-tests/test-class-wpseo-metabox.php
  js/src/components/SchemaSettings.js
  js/src/components/SchemaTab.js
  js/src/components/portals/SchemaSettingsPortal.js
  js/src/containers/SchemaSettings.js
  js/src/containers/SchemaTab.js
  js/src/values/SchemaOptions.js
  src/builders/indexable-post-builder.php
  src/config/schema-types.php
  tests/builders/indexable-post-builder-test.php
Labels: changelog: non-user-facing

#15745 Added migration to add indexes for prominent words to the indexables table.
  src/config/migrations/20200728095334_AddIndexesForProminentWordsOnIndexables.php
Labels: changelog: non-user-facing

#15747 Add get related keyphrase endpoint
  src/actions/semrush/semrush-phrases-action.php
  src/config/semrush-client.php
  src/routes/semrush-route.php
  tests/actions/semrush/semrush-phrases-action-test.php
  tests/routes/semrush-route-test.php
Labels: changelog: non-user-facing

#15752 Move scripts to config dir
  .travis.yml
  composer.json
  config/composer/scripts/maybe-restore-composer-lock.php
  config/travis/deploy_to_dist.sh
  config/yarn/bump_monorepo_packages.js
  config/yarn/link_monorepo_to_plugin.js
  config/yarn/unlink_monorepo.js
  package.json
Labels: changelog: non-user-facing

#15755 Delete phpmd.xml
  phpmd.xml
Labels: changelog: non-user-facing

#15758 CS: no yoda conditions
  src/integrations/third-party/web-stories.php
Labels: changelog: non-user-facing, yoast cs/qa

#15759 Docs: various minor fixes
  lib/orm.php
  src/presenters/url-list-presenter.php
  src/repositories/indexable-repository.php
  tests/helpers/capability-helper-test.php
  tests/values/images-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15760 CS: variety of fixes
  admin/views/class-yoast-feature-toggles.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  config/composer/actions.php
  config/dependency-injection/services.php
  lib/orm.php
  src/commands/index-command.php
  src/config/migrations/20200609154515_AddHasAncestorsColumn.php
  src/config/migrations/20200616130143_ReplacePermalinkHashIndex.php
  src/config/migrations/20200702141921_CreateIndexableSubpagesIndex.php
  src/generators/schema-generator.php
  src/generators/schema/article.php
  src/integrations/admin/indexation-integration.php
  src/integrations/blocks/abstract-dynamic-block.php
  src/integrations/blocks/block-categories.php
  src/integrations/blocks/structured-data-blocks.php
  src/integrations/third-party/web-stories.php
  src/presenters/admin/indexation-permalink-warning-presenter.php
  src/presenters/url-list-presenter.php
  src/repositories/indexable-repository.php
  src/routes/indexable-indexation-route.php
  tests/actions/indexation/indexable-complete-indexation-action-test.php
  tests/actions/indexation/indexable-post-indexation-action-test.php
  tests/actions/indexation/indexable-term-indexation-action-test.php
  tests/builders/indexable-hierarchy-builder-test.php
  tests/commands/index-command-test.php
  tests/conditionals/yoast-tools-page-conditional-test.php
  tests/generators/schema/article-test.php
  tests/helpers/capability-helper-test.php
  tests/initializers/disable-core-sitemaps-test.php
  tests/integrations/admin/indexation-integration-test.php
  tests/integrations/third-party/web-stories-test.php
  tests/integrations/watchers/indexable-category-permalink-watcher-test.php
  tests/integrations/xmlrpc-test.php
  tests/presenters/admin/indexation-permalink-warning-presenter-test.php
  tests/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15757 Move deploy keys to Travis config.
  .gitattributes
  .travis.yml
  config/travis/deploy_keys/travis_dist_id_rsa.enc
Labels: changelog: non-user-facing

#15751 Make sure the modal will be opened
  js/src/indexation.js
Labels: changelog: non-user-facing, component:tools

#15753 Remove transients when permalinks are reset
  src/integrations/watchers/indexable-permalink-watcher.php
Labels: changelog: non-user-facing

#15756 P3 51 connect redux to component
  js/src/components/RelatedKeyphraseModalContent.js
  js/src/components/RelatedKeyphrasesModal.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/components/modals/SemRushCountrySelector.js
  js/src/containers/RelatedKeyphrases.js
  js/src/containers/RelatedKeyphrasesModal.js
  js/src/containers/SEMrush.js
  js/src/redux/actions/SEMrushKeyphrases.js
  js/src/redux/actions/SEMrushModal.js
  js/src/redux/actions/SEMrushRequest.js
  js/src/redux/reducers/SEMrushModal.js
  js/src/redux/reducers/SEMrushRequest.js
  js/src/redux/selectors/SEMrushModal.js
  js/src/redux/selectors/SEMrushRequest.js
Labels: changelog: non-user-facing

#15754 Add the tracking option to the network overrides
  inc/options/class-wpseo-option-ms.php
Labels: changelog: non-user-facing

#15761 Migration for indexes on prominent words version columns should be in free.
  src/config/migrations/20200728095334_AddIndexesForProminentWordsOnIndexables.php
Labels: changelog: non-user-facing

#15746 Remove the cron conditional
  src/conditionals/cron-conditional.php
  tests/conditionals/cron-conditional-test.php
Labels: 0, changelog: non-user-facing

#15767 Add missing method to RelatedKeyphrases container
  js/src/containers/RelatedKeyphrasesModal.js
Labels: changelog: non-user-facing

#15769 Fix GitHub pre release asking for changelog
  grunt/custom/github-pre-release.js
Labels: changelog: non-user-facing

#15768 P1-1 Output correct schema based on Schema settings
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  inc/class-wpseo-meta.php
  inc/options/class-wpseo-option-titles.php
  js/src/components/SchemaSettings.js
  js/src/components/SchemaTab.js
  js/src/containers/SchemaTab.js
  src/config/schema-types.php
  src/context/meta-tags-context.php
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/helpers/schema/article-helper.php
  tests/integration/test-class-wpseo-metabox.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/context/meta-tags-context-test.php
  tests/unit/doubles/context/meta-tags-context-mock.php
  tests/unit/doubles/models/indexable-mock.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/article-test.php
  tests/unit/generators/schema/author-test.php
  tests/unit/generators/schema/person-test.php
  tests/unit/generators/schema/webpage-test.php
Labels: changelog: enhancement

#15770 P1-98 Readability score link in the publish box triggers an error
  js/src/ui/publishBox.js
Labels: changelog: bugfix
