Repository Yoast/wordpress-seo, pull requests merged in 2020-12, with the labels that each got.

#16433 Do early return on network admin
  admin/tracking/class-tracking.php
Labels: changelog: other

#16435 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16437 Add l10n initialization
  .travis.yml
  js/src/elementor.js
  package.json
Labels: changelog: non-user-facing

#16403 Exclude specific Elementor post types from being saved to the indexable table.
  composer.json
  src/actions/indexing/indexable-post-indexation-action.php
  src/builders/indexable-builder.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/conditionals/third-party/elementor-activated-conditional.php
  src/conditionals/third-party/elementor-edit-conditional.php
  src/exceptions/indexable/indexable-exception.php
  src/exceptions/indexable/invalid-term-exception.php
  src/exceptions/indexable/post-not-found-exception.php
  src/exceptions/indexable/source-exception.php
  src/exceptions/indexable/term-not-found-exception.php
  src/helpers/post-type-helper.php
  src/integrations/exclude-oembed-cache-post-type.php
  src/integrations/third-party/elementor-exclude-post-types.php
  src/integrations/third-party/elementor.php
  src/integrations/watchers/indexable-post-watcher.php
  tests/unit/actions/indexing/indexable-post-indexation-action-test.php
  tests/unit/builders/indexable-builder-test.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/conditionals/third-party/elementor-activated-conditional-test.php
  tests/unit/exceptions/indexable/invalid-term-exception-test.php
  tests/unit/exceptions/indexable/post-not-found-exception-test.php
  tests/unit/exceptions/indexable/term-not-found-exception-test.php
  tests/unit/integrations/exclude-oembed-cache-post-type-test.php
  tests/unit/integrations/third-party/elementor-exclude-post-types-test.php
  tests/unit/integrations/watchers/indexable-post-watcher-test.php
Labels: changelog: bugfix

#16427 P2-543 Make the unit test generator work with Premium.
  config/composer/actions.php
  config/composer/unit-test-generator.php
Labels: changelog: non-user-facing

#16441 Set minimum WP version to 5.5 and tested up to to 5.6
  tests/unit/inc/addon-manager-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: non-user-facing

#16186 Fix stats for the languages dir in premium
  .gitattributes
Labels: changelog: non-user-facing

#16399 Add localize script to asset manager
  admin/class-admin-asset-manager.php
  admin/class-admin-asset-yoast-components-l10n.php
  admin/class-admin.php
  admin/class-config.php
  admin/class-primary-term-admin.php
  admin/class-yoast-dashboard-widget.php
  admin/class-yoast-network-admin.php
  admin/config-ui/class-configuration-page.php
  admin/filters/class-abstract-post-filter.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  src/integrations/admin/indexing-tool-integration.php
  src/integrations/third-party/elementor.php
  tests/unit/integrations/admin/indexing-tool-integration-test.php
Labels: changelog: non-user-facing

#16439 P3-241 Ensure the AreaChart max values are at least 1 to avoid a division by zero
  js/src/components/AreaChart.js
Labels: changelog: bugfix

#16440 Improve performance for taxonomy sitemaps
  inc/sitemaps/class-taxonomy-sitemap-provider.php
Labels: changelog: enhancement, community-patch

#16442 P2-558 Register replacevars in the schema-blocks integration.
  composer.json
  inc/class-wpseo-replace-vars.php
  src/generators/schema-generator.php
  src/integrations/schema-blocks.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing

#16443 P1-286 Fix socials translations
  js/src/components/social/SocialUpsell.js
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
Labels: changelog: bugfix

#16449 Add release notification
  release-info.json
Labels: changelog: non-user-facing

#16446 Only set the state after the component has mounted
  js/src/dashboard-widget.js
Labels: changelog: non-user-facing

#16452 Disable the Usage tracking feature toggle on multisite subsites
  admin/class-yoast-form.php
Labels: UI change, changelog: bugfix

#16016 [P3-266] Remove the admin bar on block editor pages
  inc/class-wpseo-admin-bar-menu.php
Labels: UI change, changelog: enhancement

#16377 P1-225 Estimated reading time
  src/builders/indexable-post-builder.php
  src/conditionals/admin/post-conditional.php
  src/config/migrations/20201202144329_AddEstimatedReadingTime.php
  src/helpers/input-helper.php
  src/models/indexable.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/conditionals/post-conditional-test.php
  tests/unit/helpers/input-helper-test.php
Labels: changelog: non-user-facing

#16458 Integration Tests: make the testsuite x-version compatible and test against PHP 8
  .travis.yml
  composer.json
  composer.lock
  phpunit-integration.xml.dist
  phpunit.xml.dist
  tests/integration/admin/import/test-class-import-premium-seo-pack.php
  tests/integration/admin/services/test-class-file-size.php
  tests/integration/admin/test-class-admin-asset-dev-server-location.php
  tests/integration/admin/test-class-admin-asset-seo-location.php
  tests/integration/admin/test-class-plugin-suggestions.php
  tests/integration/admin/test-class-yoast-input-select.php
  tests/integration/admin/test-class-yoast-network-admin.php
  tests/integration/admin/test-class-yoast-network-settings-api.php
  tests/integration/bootstrap.php
  tests/integration/capabilities/test-class-capability-manager-factory.php
  tests/integration/capabilities/test-class-capability-manager.php
  tests/integration/capabilities/test-class-register-capabilities.php
  tests/integration/config-ui/components/test-class-factory-post-type.php
  tests/integration/config-ui/fields/test-class-config-field-choice.php
  tests/integration/config-ui/fields/test-class-config-field.php
  tests/integration/config-ui/test-class-configuration-components.php
  tests/integration/config-ui/test-class-configuration-endpoint.php
  tests/integration/config-ui/test-class-configuration-options-adapter.php
  tests/integration/config-ui/test-class-configuration-service.php
  tests/integration/config-ui/test-class-configuration-storage.php
  tests/integration/config-ui/test-class-configuration-structure.php
  tests/integration/formatter/test-metabox-formatter.php
  tests/integration/framework/class-wpseo-unit-test-case.php
  tests/integration/framework/reflectiontostring-deprecation-handler-trait.php
  tests/integration/inc/test-class-myyoast-api-request.php
  tests/integration/inc/test-class-wpseo-admin-bar-menu.php
  tests/integration/inc/test-class-wpseo-shortlinker.php
  tests/integration/inc/test-class-wpseo-upgrade-history.php
  tests/integration/notifications/test-class-yoast-notification-center.php
  tests/integration/notifications/test-class-yoast-notification.php
  tests/integration/notifiers/test-class-configuration-notifier.php
  tests/integration/notifiers/test-class-dismissible-notification.php
  tests/integration/sitemaps/test-class-wpseo-author-sitemap-provider.php
  tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
  tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-validator.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-renderer.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps.php
  tests/integration/sitemaps/test-class-wpseo-taxonomy-sitemap-provider.php
  tests/integration/taxonomy/test-class-taxonomy-presenter.php
  tests/integration/taxonomy/test-class-taxonomy.php
  tests/integration/test-class-admin-asset-manager.php
  tests/integration/test-class-admin-asset.php
  tests/integration/test-wpseo-functions.php
  tests/unit/TestCase.php
  tests/unit/conditionals/post-conditional-test.php
  tests/unit/helpers/input-helper-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16455 P1-223 Add advanced replacement variables in Elementor
  js/src/elementor/replaceVars/elementor-replacevar-plugin.js
  js/src/elementor/replaceVars/general/index.js
  js/src/elementor/replaceVars/general/modified.js
  js/src/elementor/replaceVars/general/name.js
  js/src/elementor/replaceVars/general/pageNumber.js
  js/src/elementor/replaceVars/general/pageTotal.js
  js/src/elementor/replaceVars/general/postTypeNamePlural.js
  js/src/elementor/replaceVars/general/postTypeNameSingular.js
  js/src/elementor/replaceVars/general/term404.js
  js/src/elementor/replaceVars/general/userDescription.js
  src/integrations/third-party/elementor.php
Labels: changelog: enhancement

#16456 P1-222 Add term related replacevars to the elementor integration
  js/src/elementor/replaceVars/elementor-replacevar-plugin.js
  js/src/elementor/replaceVars/general/index.js
  js/src/elementor/replaceVars/general/primaryCategory.js
  js/src/elementor/replaceVars/general/tag.js
  src/integrations/third-party/elementor.php
Labels: changelog: enhancement

#16463 Update README.md to use badge from travis-ci.com instead of travis-ci.org
  README.md
Labels: community-patch

#16471 Bump monorepo versions for 15.5
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16469 Unit tests: remove custom expectOutput*() methods and other improvements
  tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
  tests/unit/TestCase.php
  tests/unit/admin/metabox/metabox-collapsibles-section-test.php
  tests/unit/admin/metabox/metabox-section-additional-test.php
  tests/unit/admin/myyoast-proxy-test.php
  tests/unit/integrations/admin/indexing-tool-integration-test.php
  tests/unit/integrations/admin/migration-error-integration-test.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/integrations/front-end/force-rewrite-title-test.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16476 P2-576 Moved schema-blocks CSS to the monorepo.
  css/src/schema-blocks.css
Labels: changelog: non-user-facing, component: innovation

#16249 Deprecate WPSEO_Validator
  src/deprecated/inc/class-wpseo-validator.php
Labels: changelog: non-user-facing, community-patch

#16447 Remove about page remnants.
  admin/class-admin.php
  admin/pages/dashboard.php
Labels: changelog: non-user-facing, technical-debt

#16490 Web Stories: ensure that there’s always a meta description
  src/integrations/third-party/web-stories.php
  tests/unit/integrations/third-party/web-stories-test.php
Labels: changelog: enhancement

#16103 Web Stories: ensure that there’s always a meta description
  src/integrations/third-party/web-stories.php
  tests/unit/integrations/third-party/web-stories-test.php
Labels: community-patch

#15905 11327 audit function exists checks
  admin/class-admin-asset-manager.php
  admin/class-admin-asset-seo-location.php
  admin/class-admin-asset-yoast-components-l10n.php
  admin/class-config.php
  admin/class-yoast-notification-center.php
  admin/config-ui/class-configuration-service.php
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/statistics/class-statistics-service.php
  admin/taxonomy/class-taxonomy.php
  composer.json
  inc/language-utils.php
  src/deprecated/admin/add-keyword-modal.php
  src/deprecated/admin/keyword-synonyms-modal.php
  src/deprecated/admin/multiple-keywords-modal.php
  tests/integration/formatter/test-metabox-formatter.php
  tests/unit/admin/metabox/metabox-editor-test.php
Labels: changelog: non-user-facing

#16492 Add Rank Math to the plugin conflict list
  admin/class-plugin-conflict.php
Labels: changelog: enhancement

#16496 Add Norwegian to languages with morphology and function words
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#16486 Move Estimated Reading Time calculation and data flow to free
  admin/metabox/class-metabox.php
  js/src/elementor.js
  js/src/helpers/fields/EstimatedReadingTimeFields.js
  js/src/initializers/estimated-reading-time.js
  js/src/post-edit.js
  js/src/redux/actions/estimatedReadingTime.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/estimatedReadingTime.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/estimatedReadingTime.js
  js/src/redux/selectors/index.js
  src/conditionals/admin/estimated-reading-time-conditional.php
  src/integrations/estimated-reading-time.php
  src/integrations/third-party/elementor.php
  tests/unit/conditionals/estimated-reading-time-conditional-test.php
  tests/unit/integrations/estimated-reading-time-test.php
Labels: changelog: non-user-facing

#16462 Use Estimated Reading Time indexable value in Enhanced Slack Integration
  src/presentations/indexable-presentation.php
  src/presenters/slack/enhanced-data-presenter.php
  tests/unit/integrations/estimated-reading-time-test.php
  tests/unit/presenters/slack/enhanced-data-presenter-test.php
Labels: changelog: non-user-facing

#16489 Port changes made to free code in premium back to free
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  lib/orm.php
Labels: changelog: non-user-facing

#16479 Expose the Yoast editormodules which are used outside of Yoast SEO.
  admin/class-admin-asset-manager.php
  config/webpack/paths.js
  js/src/editor-modules.js
Labels: changelog: non-user-facing

#16498 Web Stories: Update metadata filters
  src/integrations/third-party/web-stories.php
  tests/unit/integrations/third-party/web-stories-test.php
Labels: community-patch

#16484 Add columns to modal
  css/src/modal.css
Labels: changelog: non-user-facing

#16470 P2-371 Inject Schema IDs
  composer.json
  inc/class-wpseo-replace-vars.php
  src/generators/schema-generator.php
  src/helpers/schema/replace-vars-helper.php
  src/integrations/schema-blocks.php
  tests/unit/doubles/helpers/schema/replace-vars-helper-double.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/integrations/front-end/force-rewrite-title-test.php
Labels: changelog: non-user-facing, component: innovation

#16499 Fixes a couple of CS errors in the tests
  composer.json
  tests/unit/database/migration-runner-test.php
  tests/unit/integrations/watchers/indexable-author-watcher-test.php
  tests/unit/integrations/watchers/indexable-date-archive-watcher-test.php
  tests/unit/integrations/watchers/indexable-home-page-watcher-test.php
  tests/unit/integrations/watchers/indexable-post-type-archive-watcher-test.php
  tests/unit/integrations/watchers/indexable-system-page-watcher-test.php
  tests/unit/integrations/watchers/indexable-term-watcher-test.php
  tests/unit/integrations/watchers/option-titles-watcher-test.php
Labels: changelog: non-user-facing

#16502 Add three more editorModules.
  admin/class-admin-asset-manager.php
  config/webpack/paths.js
  js/src/editor-modules.js
Labels: changelog: non-user-facing

#16497 Added migration to transform ID columns in the indexable table to bigint.
  src/config/migrations/20201216124002_ExpandIndexableIDColumnLengths.php
  src/config/migrations/20201216141134_ExpandPrimaryTermIDColumnLengths.php
Labels: changelog: bugfix

#16503 Add the editor modal to the editor modules
  js/src/editor-modules.js
Labels: changelog: non-user-facing

#16504 Add CSS for two columns in modal
  css/src/modal.css
Labels: changelog: non-user-facing

#16511 Fixed PHP notice on non-post pages.
  src/helpers/schema/replace-vars-helper.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
Labels: changelog: non-user-facing

#16514 Bump monorepo versions for 15.6
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16515 Bumps the `schema-blocks` package to 1.1.0-RC1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16517 Add release notification
  release-info.json
Labels: changelog: non-user-facing
