Repository Yoast/wordpress-seo, pull requests merged in 2020-06, with the labels that each got.

#15321 Add required headers in plugin
  wp-seo.php
Labels: changelog: other, community-patch

#15330 P3-25 Make sure all replacement variable values are strings.
  inc/class-wpseo-replace-vars.php
Labels: changelog: non-user-facing

#15358 Fix zero index
  src/generators/schema/faq.php
  tests/generators/schema-generator-test.php
  tests/generators/schema/faq-test.php
Labels: 0.5, changelog: bugfix

#15360 FRO-95 Add namespace to CSS variables
  css/src/admin-global.css
  css/src/icons.css
  css/src/metabox.css
  css/src/notifications.css
  css/src/yoast-extensions.css
  css/src/yst_plugin_tools.css
Labels: changelog: bugfix

#15366 Bump the version of the monorepo packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15378 Bump JS monorepo packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15382 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15365 Publish flow
  css/src/metabox.css
  images/icon-facebook.svg
  images/icon-twitter.svg
  js/src/components/DocumentSidebar.js
  js/src/components/PostPublish.js
  js/src/components/PrePublish.js
  js/src/containers/DocumentSidebar.js
  js/src/containers/PostPublish.js
  js/src/containers/PrePublish.js
  js/src/edit.js
  js/src/redux/selectors/focusKeyPhrase.js
  js/src/redux/selectors/index.js
  webpack/webpack.config.js
Labels: UI change, changelog: enhancement

#15348 Add inline-link (nofollow / sponsored) block editor integration.
  admin/class-expose-shortlinks.php
  js/src/components/RaisedDefaultButton.js
  js/src/edit.js
  js/src/helpers/createInterpolateElement.js
  js/src/inline-links/edit-link.js
  js/src/inline-links/inline.js
  js/src/inline-links/link-editor.js
  js/src/inline-links/link-viewer.js
  js/src/inline-links/positioned-at-selection.js
  js/src/inline-links/url-input.js
  js/src/inline-links/utils.js
  js/src/wp-seo-api.js
  js/src/wp-seo-bulk-editor.js
  js/src/wp-seo-dashboard-widget.js
  js/src/wp-seo-featured-image.js
  js/src/wp-seo-metabox-category.js
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: UI change, changelog: enhancement

#15373 Admin Bar: fix link to Facebook Debugger
  inc/class-wpseo-admin-bar-menu.php
Labels: changelog: bugfix, community-patch

#15392 Introduces a field to have clear the indexable contains ancestors
  src/builders/indexable-builder.php
  src/builders/indexable-hierarchy-builder.php
  src/config/migrations/20200609154515_AddHasAncestorsColumn.php
  src/models/indexable.php
  tests/builders/indexable-hierarchy-builder-test.php
  tests/doubles/models/indexable-mock.php
Labels: changelog: bugfix

#15399 Use first image in content as a fallback in the social previews
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  js/src/analysis/classicEditorData.js
  js/src/analysis/data.js
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
  js/src/initializers/edit.js
  js/src/redux/actions/settings.js
  js/src/redux/reducers/settings.js
  js/src/redux/selectors/fallbacks.js
Labels: changelog: non-user-facing

#15396 QAK-1869 Fix publish flow bugs
  css/src/metabox.css
  js/src/components/DocumentSidebar.js
  js/src/components/PrePublish.js
  js/src/containers/DocumentSidebar.js
  js/src/containers/PrePublish.js
  js/src/edit.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/preferences.js
Labels: changelog: bugfix

#15383 P3-32 Create get related keyphrases basic modal dialog
  admin/class-admin-asset-manager.php
  css/src/admin-global.css
  css/src/gutenberg-modal.css
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/SnippetPreviewModal.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/components/modals/CountrySelector.js
  js/src/components/modals/KeyphrasesTable.js
Labels: changelog: non-user-facing

#14023 class-wpseo-options: fix "array_merge(): Argument #1 is not an array" notice
  inc/options/class-wpseo-options.php
Labels: changelog: bugfix, community-patch

#15369 P3-2 Add SEMrush modal "limit reached" content
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/modals/SemRushLimitReached.js
Labels: changelog: non-user-facing

#15422 Add Schema as tag to readme.txt
  readme.txt
Labels: changelog: non-user-facing

#15404 Create prominent words integration
  js/src/wp-seo-indexation.js
  src/conditionals/yoast-tools-page-conditional.php
  src/integrations/admin/indexation-integration.php
  src/presenters/admin/indexation-list-item-presenter.php
  src/presenters/admin/indexation-warning-presenter.php
  src/routes/indexable-indexation-route.php
  tests/conditionals/yoast-tools-page-conditional-test.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-list-item-presenter-test.php
  tests/presenters/admin/indexation-warning-presenter-test.php
Labels: changelog: non-user-facing

#15407 FRO 101 collapsibles admin pages
  admin/class-collapsible-presenter.php
  admin/class-paper-presenter.php
  admin/views/collapsible.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/taxonomies.php
  css/src/admin/all.css
  css/src/components/collapsible.css
Labels: UI change

#15388 Change close wizard to link
  admin/class-yoast-form.php
  admin/config-ui/class-configuration-page.php
  css/src/components/configuration-wizard.css
  js/src/components/FinalStep.js
  js/src/components/MailchimpSignup.js
  js/src/components/MediaUpload.js
  js/src/components/Suggestion.js
Labels: UI change, changelog: enhancement

#15415 QAK-1874 Use standard plugin document panel
  js/src/edit.js
Labels: changelog: bugfix

#15355 FRO-70 Style the info table of the RSS tab
  admin/views/tabs/metas/paper-content/rss-content.php
Labels: UI change, changelog: enhancement

#14203 Fix REST response to be 200
  admin/services/class-file-size.php
Labels: changelog: non-user-facing

#15395 P3-33 Fix configuration wizard local seo link
  admin/config-ui/components/class-component-suggestions.php
  grunt/config/eslint.js
Labels: changelog: bugfix

#15427 Clear the category permalinks when stripcategorybase option changes
  inc/options/class-wpseo-options.php
  src/actions/indexation/indexable-term-indexation-action.php
  src/integrations/admin/indexation-integration.php
  src/integrations/watchers/indexable-category-permalink-watcher.php
  src/presenters/admin/indexation-permalink-warning-presenter.php
  src/presenters/admin/indexation-warning-presenter.php
  tests/actions/indexation/indexable-term-indexation-action-test.php
  tests/integrations/admin/indexation-integration-test.php
  tests/integrations/watchers/indexable-category-permalink-watcher-test.php
Labels: UI change, changelog: bugfix

#15433 Add yoast prefixes to CSS variables
  css/src/base/colors.css
  css/src/base/icons.css
  css/src/components/buttons.css
  css/src/components/card.css
  css/src/components/collapsible.css
  css/src/components/headings.css
  css/src/components/lists.css
  css/src/components/paper.css
  css/src/components/sidebar.css
  css/src/components/tabs.css
Labels: changelog: non-user-facing

#15331 Fix CS in the lib folder
  lib/model.php
  lib/orm.php
  phpcs.xml.dist
Labels: changelog: non-user-facing

#15439 Clear permalinks on taxonomy settings change
  src/conditionals/yoast-admin-and-dashboard-conditional.php
  src/integrations/watchers/indexable-category-permalink-watcher.php
  src/integrations/watchers/indexable-permalink-watcher.php
Labels: changelog: other

#15248 FRO-16 update styling table
  admin/class-bulk-editor-list-table.php
  css/src/admin/all.css
  css/src/base/icons.css
  css/src/components/sidebar.css
  css/src/components/table.css
  css/src/editor/yst_plugin_tools.css
Labels: UI change, changelog: enhancement

#15442 Don't show it when an email address is already on the mailing list
  js/src/components/MailchimpSignup.js
Labels: changelog: enhancement

#15446 Change primary button into upsell button in configuration wizard
  admin/config-ui/components/class-component-suggestions.php
  js/src/components/Suggestion.js
  js/tests/__snapshots__/advancedSettings.test.js.snap
Labels: UI change, changelog: enhancement

#15450 Remove COUNT(*) from query in author_has_a_public_post() and author_has_a_post_with_is_public_null()
  src/helpers/author-archive-helper.php
Labels: community-patch

#15155 FRO-11 update styling form fields settings pages
  admin/class-export.php
  admin/class-yoast-form.php
  admin/views/collapsible.php
  admin/views/licenses.php
  admin/views/tabs/dashboard/webmaster-tools.php
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/paper-content/breadcrumbs-content.php
  admin/views/tabs/metas/paper-content/general/force-rewrite-title.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
  admin/views/tabs/metas/paper-content/media-content.php
  admin/views/tabs/metas/rss.php
  admin/views/tabs/metas/taxonomies.php
  admin/views/tabs/social/accounts.php
  admin/views/tabs/social/pinterest.php
  admin/views/tabs/social/twitterbox.php
  admin/views/tabs/tool/import-seo.php
  admin/views/tabs/tool/wpseo-export.php
  admin/views/tabs/tool/wpseo-import.php
  admin/views/tool-file-editor.php
  css/src/admin/admin.css
  css/src/admin/all.css
  css/src/base/colors.css
  css/src/base/icons.css
  css/src/components/card.css
  css/src/components/paper.css
  images/yoast_seo_premium.svg
  js/src/wp-seo-admin.js
  js/tests/__snapshots__/advancedSettings.test.js.snap
  src/presenters/admin/indexation-list-item-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-list-item-presenter-test.php
Labels: UI change, changelog: enhancement

#15441 Add migration to replace the permalink_hash index
  src/config/migrations/20200616130143_ReplacePermalinkHashIndex.php
Labels: changelog: non-user-facing

#15452 Introduce skip confirmation to the Yoast reindex CLI
  src/commands/index-command.php
Labels: changelog: enhancement

#15456 Add caching for authors with no posts to prevent full table scanning in author_has_a_public_post and author_has_a_post_with_is_public_null
  src/helpers/author-archive-helper.php
Labels: community-patch

#15434 Premium feature toggles
  admin/class-yoast-form.php
  admin/views/class-yoast-feature-toggle.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/network/features.php
  css/src/components/buttons.css
  src/helpers/language-helper.php
Labels: changelog: enhancement

#15458 Depend on latest link formatter, copy changes and update babel.
  .babelrc
  .eslintignore
  admin/views/class-view-utils.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
  babel.config.json
  js/src/analysis/PostDataCollector.js
  js/src/analysis/TermDataCollector.js
  js/src/analysis/classicEditorData.js
  js/src/analysis/data.js
  js/src/analysis/getApplyMarks.js
  js/src/analysis/getIndicatorForScore.js
  js/src/analysis/getL10nObject.js
  js/src/analysis/isContentAnalysisActive.js
  js/src/analysis/isCornerstoneContentActive.js
  js/src/analysis/isKeywordAnalysisActive.js
  js/src/analysis/isWordFormRecognitionActive.js
  js/src/analysis/usedKeywords.js
  js/src/decorator/tinyMCE.js
  js/src/edit.js
  js/src/inline-links/edit-link.js
  js/src/inline-links/inline.js
  js/src/inline-links/link-editor.js
  js/src/inline-links/link-viewer.js
  js/src/inline-links/positioned-at-selection.js
  js/src/inline-links/url-input.js
  js/src/inline-links/vendor/link-control.js
  js/src/inline-links/vendor/search-create-button.js
  js/src/inline-links/vendor/search-input.js
  js/src/inline-links/vendor/search-item.js
  js/src/inline-links/vendor/settings-drawer.js
  js/src/ui/adminBar.js
  js/src/ui/publishBox.js
  js/src/ui/trafficLight.js
  js/src/values/replaceVar.js
  js/src/wp-seo-post-scraper.js
  js/src/wp-seo-recalculate.js
  js/src/wp-seo-tinymce.js
  js/tests/components/SnippetPreviewSection.skip.js
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/components/__snapshots__/UpsellBox.test.js.snap
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: UI change, changelog: bugfix

#15460 Define required property Type on ReplacementVariableEditor
  js/src/components/SettingsReplacementVariableField.js
Labels: changelog: non-user-facing

#15462 Simplify value parsing for userID
  js/src/components/WordPressUserSelectorSearchAppearance.js
Labels: changelog: non-user-facing

#15457 FRO-119 remove 404 error css files
  admin/class-admin-asset-manager.php
  css/src/admin/admin.css
Labels: changelog: enhancement

#15464 FRO-120 Add spacing around the knowledge graph container
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
Labels: UI change

#15473 Revert babel upgrade / don't load nofollow functionality for wp < 5.4
  .babelrc
  .eslintignore
  babel.config.json
  grunt/config/eslint.js
  js/src/edit.js
  js/src/inline-links/inline.js
  js/src/inline-links/vendor/link-control.js
  js/src/inline-links/vendor/search-create-button.js
  js/src/inline-links/vendor/search-input.js
  js/src/inline-links/vendor/search-item.js
  js/src/inline-links/vendor/settings-drawer.js
  js/tests/__snapshots__/advancedSettings.test.js.snap
  js/tests/components/SnippetPreviewSection.test.js
  js/tests/components/__snapshots__/SnippetPreviewSection.test.js.snap
  js/tests/components/__snapshots__/UpsellBox.test.js.snap
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: changelog: bugfix

#15476 CS: method modifier order
  lib/migrations/migration.php
Labels: changelog: non-user-facing, yoast cs/qa

#15475 CS: use self for in-class references
  inc/class-wpseo-utils.php
Labels: changelog: non-user-facing, yoast cs/qa

#15480 CS: no implicit array creation
  lib/orm.php
Labels: changelog: non-user-facing, yoast cs/qa

#15479 QA: remove unused `use` statement
  deprecated/frontend/schema/class-schema-person.php
Labels: changelog: non-user-facing, yoast cs/qa

#15477 CS: use boolean and/or operators
  lib/orm.php
Labels: changelog: non-user-facing, yoast cs/qa

#15478 CS: formatting of multiline function calls
  admin/metabox/class-metabox.php
  lib/migrations/adapter.php
  lib/orm.php
  src/repositories/indexable-hierarchy-repository.php
Labels: changelog: non-user-facing, yoast cs/qa

#15471 Travis/Composer: switch over to parallel linting of PHP files
  .travis.yml
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#15481 Docs: various fixes
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  lib/migrations/adapter.php
  lib/migrations/column.php
  lib/migrations/migration.php
  lib/migrations/table.php
  lib/orm.php
  src/presenters/breadcrumbs-presenter.php
  tests/bootstrap.php
  tests/doubles/database/migration-double.php
  tests/presentations/indexable-static-posts-page-presentation/presentation-instance-builder-trait.php
Labels: changelog: non-user-facing, yoast cs/qa

#15474 CS: clean up after merges
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/class-meta-columns.php
  admin/formatter/class-metabox-formatter.php
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/taxonomy/class-taxonomy.php
  deprecated/admin/class-social-admin.php
  deprecated/frontend/abstract-class-deprecated-schema-piece.php
  inc/options/class-wpseo-options.php
  integration-tests/formatter/test-metabox-formatter.php
  lib/migrations/adapter.php
  lib/migrations/column.php
  lib/migrations/migration.php
  lib/migrations/table.php
  lib/orm.php
  src/helpers/author-archive-helper.php
  tests/database/migration-runner-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15485 CS: multi-item associative arrays should be multi-line
  lib/migrations/adapter.php
  lib/migrations/table.php
Labels: changelog: non-user-facing, yoast cs/qa

#15486 QA: use FQN function and constant names
  src/config/migrations/20200408101900_AddCollationToTables.php
  src/helpers/author-archive-helper.php
  src/helpers/language-helper.php
  src/initializers/migration-runner.php
Labels: changelog: non-user-facing, yoast cs/qa

#15487 CS: don't use Yoda conditions
  lib/migrations/adapter.php
  lib/orm.php
  src/helpers/author-archive-helper.php
Labels: changelog: non-user-facing, yoast cs/qa

#15489 QA: use WPSEO_Utils::format_json_encode()
  src/builders/indexable-post-builder.php
  src/builders/indexable-social-image-trait.php
  tests/builders/indexable-home-page-builder-test.php
  tests/generators/open-graph-image-generator-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15490 QA: remove two empty files
  src/loggers/database-logger.php
  tests/frontend/schema/mainimage-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15466 Fix social editor focus and implement better fallback/placeholder functionality
  js/src/components/social/SocialForm.js
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
Labels: changelog: bugfix, changelog: non-user-facing

#15499 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15445 Saves the reason for the notice to show
  admin/ajax.php
  inc/options/class-wpseo-option-wpseo.php
  src/actions/indexation/indexable-post-indexation-action.php
  src/actions/indexation/indexable-term-indexation-action.php
  src/integrations/admin/indexation-integration.php
  src/integrations/watchers/indexable-category-permalink-watcher.php
  src/integrations/watchers/indexable-permalink-watcher.php
  src/presenters/admin/indexation-permalink-warning-presenter.php
  src/presenters/admin/indexation-warning-presenter.php
  src/routes/indexable-indexation-route.php
  tests/actions/indexation/indexable-post-indexation-action-test.php
  tests/integrations/admin/indexation-integration-test.php
  tests/integrations/watchers/indexable-category-permalink-watcher-test.php
  tests/integrations/watchers/indexable-permalink-watcher-test.php
Labels: changelog: enhancement

#15448 Added the loading SEMrush modal content
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/modals/SemRushLoading.js
Labels: changelog: non-user-facing

#15504 Use get to test for experimentalLinkControl presence
  js/src/edit.js
Labels: changelog: non-user-facing

#15431 Make the pluginicon in the editor reflect the SEO and Readability score.
  css/src/metabox.css
  images/Yoast_icon_kader.svg
  js/src/components/PluginIcon.js
  js/src/containers/PluginIcon.js
  js/src/initializers/edit.js
Labels: UI change, changelog: enhancement

#15505 Add dash to file name
  admin/class-admin-asset-manager.php
Labels: 0, changelog: non-user-facing

#15447 Run indexation JS on our tools page only
  js/src/indexation.js
  src/integrations/admin/indexation-integration.php
  src/presenters/admin/indexation-permalink-warning-presenter.php
  src/presenters/admin/indexation-warning-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-warning-presenter-test.php
Labels: changelog: other

#15501 Fro 123 remove wpseo admin help panel class
  admin/class-admin-help-panel.php
  js/src/admin-global.js
Labels: changelog: non-user-facing

#15508 Only extract PrePublishPanel after we know we are in Gutenberg
  js/src/initializers/edit.js
Labels: changelog: non-user-facing

#15506 P3-46 Create Upsell info Alert content for the modal
  grunt/config/eslint.js
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/modals/SemRushLimitReached.js
  js/src/components/modals/SemRushLoading.js
  js/src/components/modals/SemRushUpsellAlert.js
Labels: changelog: non-user-facing

#15511 Bump JS packages for 14.5 RC
  package.json
  scripts/bump_monorepo_packages.js
  yarn.lock
Labels: changelog: non-user-facing

#15512 Only add link buttons for non-hidden fields
  admin/taxonomy/class-taxonomy-fields-presenter.php
Labels: changelog: non-user-facing

#15514 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15515 Bump social metadata forms
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15513 Add SEMrush "request failed" content
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/modals/SemRushRequestFailed.js
Labels: changelog: non-user-facing

#15517 FRO-126 Remove strong tag in Content types
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
Labels: changelog: enhancement

#15516 FRO-125 Add progressbar css and update styling
  admin/links/class-link-reindex-dashboard.php
  css/src/admin/admin.css
  src/presenters/admin/indexation-modal-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-modal-presenter-test.php
Labels: UI change, changelog: enhancement

#15518 P3-3 Create "Max number related keyphrases entered" content
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/modals/SemRushMaxRelatedKeyphrases.js
Labels: changelog: non-user-facing

#15520 Moved the import of window.wp.blockEditor components to the render funtions where they are used.
  js/src/inline-links/edit-link.js
  js/src/inline-links/inline.js
Labels: changelog: non-user-facing

#14239 Fix undefined `get_plugins()` error in some conditions
  inc/class-addon-manager.php
Labels: community-patch, wait for feedback

#15470 PHPCS: enable caching between runs (Premium)
  .cache/.gitkeep
  .gitattributes
  .gitignore
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#15405 Notice: Trying to access array offset on value of type bool fixed
  admin/formatter/class-post-metabox-formatter.php
Labels: community-patch

#15533 Introduce coding standards interactive composer menu
  composer.json
  config/composer/actions.php
Labels: changelog: non-user-facing

#15530 Fixed relative URL to SVG file.
  css/src/admin/dashboard.css
Labels: changelog: non-user-facing

#15538 Aligns input field to one line in html code
  admin/class-yoast-form.php
Labels: changelog: non-user-facing

#15540 Output comment count in Article schema when relevant
  src/generators/schema/article.php
  tests/generators/schema/article-test.php
Labels: changelog: bugfix

#15543 P2-57 Fixes a bug where the webpack config env would not exist
  webpack/webpack.config.js
Labels: changelog: non-user-facing

#15526 Make cornerstone visibility depend on both general setting AND post/term
  js/src/containers/MetaboxFill.js
Labels: changelog: bugfix

#14498 Removes stripslashes from retrieve_title()
  inc/class-wpseo-replace-vars.php
Labels: changelog: bugfix, community-patch

#15550 Add a generic class to allow styling inside of metabox tab section
  css/src/editor/metabox.css
Labels: changelog: non-user-facing

#15544 Fix icon for notifications on dashboard
  css/src/base/icons.css
  css/src/components/paper.css
Labels: changelog: non-user-facing

#15553 FRO-136 upload image styling
  css/src/components/headings.css
  integration-tests/notifiers/test-class-configuration-notifier.php
Labels: UI change, changelog: non-user-facing

#15549 Changed readfile to get_contents from wp_filesystem
  inc/sitemaps/class-sitemaps.php
Labels: changelog: non-user-facing

#15554 Missing no posts no index toggle
  js/src/initializers/admin.js
Labels: changelog: non-user-facing

#15555 Redirect attachment toggle fix
  admin/views/tabs/metas/paper-content/media-content.php
  js/src/initializers/admin.js
Labels: changelog: non-user-facing

#15556 Remove paper style breadcrumbs and add extra header
  admin/views/tabs/metas/breadcrumbs.php
  admin/views/tabs/metas/paper-content/breadcrumbs-content.php
Labels: UI change, changelog: non-user-facing

#15561 FRO-154 fix sidebar placement
  css/src/components/sidebar.css
Labels: UI change, changelog: non-user-facing

#15563 Bumped monorepo packages for 14.5-RC3.
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15548 FRO-132 Updates radio and legend to new styling
  admin/class-yoast-form.php
Labels: UI change, changelog: non-user-facing

#15552 Add tracking opt-in to Yoast free, opt-out to premium
  admin/config-ui/class-configuration-storage.php
  admin/config-ui/class-configuration-structure.php
  admin/config-ui/fields/class-field-tracking-intro.php
  admin/config-ui/fields/class-field-tracking.php
  admin/config-ui/fields/class-field-upsell-configuration-service.php
  admin/config-ui/fields/class-field-upsell-site-review.php
  admin/tracking/class-tracking.php
  admin/views/class-yoast-feature-toggles.php
  inc/options/class-wpseo-option-wpseo.php
  integration-tests/config-ui/test-class-configuration-structure.php
Labels: UI change, changelog: enhancement

#15565 FRO-152 Update check mark to new class and update tests
  src/integrations/admin/indexation-integration.php
  src/presenters/admin/indexation-list-item-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-list-item-presenter-test.php
Labels: changelog: non-user-facing

#15564 Add the ALLOW_KEY_PREFIX back to the toggles
  admin/views/tabs/network/features.php
Labels: changelog: bugfix

#15575 FRO-137 Move help scout icon
  js/src/help-scout-beacon.js
Labels: changelog: non-user-facing

#15546 P2-53 Decrease the zip size
  admin/class-admin-asset-manager.php
  grunt/config/copy.js
  grunt/config/shell.js
  grunt/custom/i18n-clean-json.js
  js/src/externals/components.js
  js/src/externals/draft-js.js
  js/src/helpers/i18n.js
  package.json
  scripts/link_monorepo_to_plugin.js
  webpack/webpack.config.js
Labels: changelog: non-user-facing

#15576 FRO-174 Style delete content notification
  admin/class-yoast-notification.php
  admin/watchers/class-slug-change-watcher.php
  css/src/components/headings.css
  css/src/editor/post-overview-global.css
Labels: changelog: non-user-facing

#15529 Disable WP core sitemaps
  src/integrations/disable-core-sitemaps.php
  tests/integrations/disable-core-sitemaps-test.php
Labels: changelog: enhancement

#15586 Fix the meta columns for the title and description
  admin/class-meta-columns.php
Labels: changelog: bugfix

#15588 P1-39 Add wp-element and wp-i18n as dependency to network admin
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing

#15578 Restore Related keyphrases modal basic styling.
  css/src/editor/metabox.css
  css/src/gutenberg-modal.css
  js/src/components/contentAnalysis/SeoAnalysis.js
Labels: changelog: non-user-facing

#15587 P3-62 Fix SEMrush limit-reached upsell button css
  js/src/components/RelatedKeyPhrasesModal.js
  js/src/components/modals/SemRushLimitReached.js
Labels: changelog: non-user-facing
