Repository Yoast/wordpress-seo, pull requests merged in 2020-01, with the labels that each got.

#14129 Reintroduce register_wp_assets for backwards compatibility
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing, test by qa

#14102 Add Good result status to the Paging comments Site Health test.
  inc/health-check-page-comments.php
  tests/inc/health-check-page-comments-test.php
Labels: changelog: enhancement, component: site health

#14117 Move the tagline notification to a site health test
  admin/class-admin-init.php
  inc/class-upgrade.php
  inc/health-check-default-tagline.php
  inc/health-check.php
  package.json
  tests/inc/health-check-default-tagline-test.php
  tests/inc/health-check-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#14136 Move deprecated method
  admin/class-admin-init.php
Labels: changelog: non-user-facing

#14122 Adds a checkbox list field
  admin/class-yoast-form.php
Labels: 0.5, changelog: enhancement

#14139 Use the getters for retrieving the option value
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
Labels: changelog: non-user-facing

#14147 Bump monorepo packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14153 Bump monorepo packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14133 Revert vendor/bin composer changes
  composer.json
Labels: 0.5, changelog: non-user-facing, component: indexables, type: development

#14155 Consistent spacing in our tags
  src/integrations/front-end-integration.php
  src/integrations/front-end/webmaster-tools-meta.php
  src/presenters/googlebot-presenter.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/open-graph/title-presenter.php
  src/presenters/open-graph/type-presenter.php
  src/presenters/open-graph/url-presenter.php
  src/presenters/robots-presenter.php
  tests/presenters/googlebot-presenter-test.php
  tests/presenters/open-graph/image-presenter-test.php
  tests/presenters/open-graph/title-presenter-test.php
  tests/presenters/open-graph/type-presenter-test.php
  tests/presenters/robots-presenter-test.php
Labels: changelog: non-user-facing, test by qa

#14108 Created issue when zip size is too big
  .env.example
  grunt/config/tools/parse-version.js
  grunt/config/update-readme.js
  grunt/config/verify-zip-size.js
Labels: changelog: non-user-facing

#14161 Apply new namespace convention in indexable repository test
  tests/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing, component: innovation

#14162 bump plugin grunt task to fix RTL CSS minified files not being loaded
  package.json
  yarn.lock
Labels: 0.5, changelog: non-user-facing

#14152 Stop showing twitter title and description when fallback on OG
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/presentations/indexable-post-type-presentation/twitter-description-test.php
  tests/presentations/indexable-presentation/twitter-description-test.php
  tests/presentations/indexable-presentation/twitter-title-test.php
  tests/presentations/indexable-term-archive-presentation/presentation-instance-builder.php
  tests/presentations/indexable-term-archive-presentation/twitter-description-test.php
  tests/presentations/presentation-instance-dependencies.php
Labels: 0.5

#14166 Rename snippet preview to Google preview in search appearance
  admin/views/class-view-utils.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
Labels: changelog: non-user-facing

#14167 Add covers to tests
  integration-tests/admin/links/test-class-link-columns-count.php
  integration-tests/admin/links/test-class-link-columns.php
  integration-tests/admin/links/test-class-link-content-processor.php
  integration-tests/admin/links/test-class-link-extractor.php
  integration-tests/admin/links/test-class-link-factory.php
  integration-tests/admin/links/test-class-link-internal-lookup.php
  integration-tests/admin/links/test-class-link-storage.php
  integration-tests/admin/links/test-class-link-watcher.php
  integration-tests/admin/links/test-class-link_reindex_dashboard.php
  integration-tests/config-ui/test-class-configuration-service.php
  integration-tests/inc/options/test-class-wpseo-options-backfill.php
  integration-tests/inc/test-class-myyoast-api-request.php
  integration-tests/inc/test-class-post-type.php
Labels: changelog: non-user-facing, component: tests, yoast cs/qa

#14168 Remove tests that doesn't really test anything
  integration-tests/admin/test-class-yoast-network-admin.php
Labels: changelog: non-user-facing

#14170 Fix Yoda conditions
  admin/class-admin-asset-dev-server-location.php
  admin/class-admin-help-panel.php
  admin/class-admin-init.php
  admin/class-admin-user-profile.php
  admin/class-admin.php
  admin/class-bulk-editor-list-table.php
  admin/class-config.php
  admin/class-customizer.php
  admin/class-meta-columns.php
  admin/class-meta-table-accessible.php
  admin/class-primary-term-admin.php
  admin/class-social-admin.php
  admin/class-yoast-notification-center.php
  admin/class-yoast-notification.php
  admin/config-ui/factories/class-factory-post-type.php
  admin/formatter/class-post-metabox-formatter.php
  admin/links/class-link-columns.php
  admin/links/class-link-query.php
  admin/links/class-link-table-accessible.php
  admin/pages/tools.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#14171 Stop using yoda conditions
  admin/recalculate/class-recalculate-posts.php
  admin/recalculate/class-recalculate-terms.php
  admin/recalculate/class-recalculate.php
  admin/taxonomy/class-taxonomy.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/social/facebook.php
  config/dependency-injection/custom-loader.php
  frontend/schema/class-schema-context.php
  frontend/schema/class-schema-website.php
  inc/class-post-type.php
  inc/class-rewrite.php
  inc/class-upgrade-history.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-replace-vars.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-options.php
  inc/options/class-wpseo-taxonomy-meta.php
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-sitemap-image-parser.php
  inc/sitemaps/class-sitemaps-admin.php
  inc/sitemaps/class-sitemaps-cache.php
  inc/sitemaps/class-sitemaps-renderer.php
  inc/sitemaps/class-sitemaps.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
  integration-tests/bootstrap.php
  integration-tests/test-class-rewrite.php
  src/orm/yoast-model.php
  src/watchers/primary-term-watcher.php
Labels: changelog: non-user-facing, yoast cs/qa

#14172 Revert yoda conditions
  admin/class-admin-init.php
  admin/metabox/class-abstract-sectioned-metabox-tab.php
  admin/onpage/class-onpage.php
Labels: changelog: non-user-facing

#14174 Fix @covers tags in SEO Free
  integration-tests/admin/test-class-plugin-availability.php
  integration-tests/admin/test-class-plugin-suggestions.php
Labels: changelog: non-user-facing

#14132 Update changelog at subsequent RC build
  grunt/config/tools/get-user-input.js
  grunt/config/update-readme.js
Labels: changelog: non-user-facing

#14120 Move permalink notification to Site Health.
  admin/class-admin-init.php
  inc/class-upgrade.php
  inc/health-check-postname-permalink.php
  tests/inc/health-check-postname-permalink-test.php
Labels: changelog: enhancement, component: site health

#14154 Schema: strip tags on text fields
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/faq.php
  src/generators/schema/howto.php
  src/generators/schema/organization.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/generators/schema/website.php
  src/helpers/schema/html-helper.php
  src/helpers/schema/id-helper.php
  src/helpers/schema/image-helper.php
  tests/generators/schema/article-test.php
  tests/helpers/schema/html-helper-test.php
Labels: changelog: bugfix, needs-pair, test by qa

#14165 Added @context variable
  src/generators/schema-generator.php
  tests/generators/schema-generator-test.php
Labels: changelog: non-user-facing

#14200 Fixes a bug where memory got exhausted on sites with a lot of users.
  admin/capabilities/class-capability-utils.php
  tests/admin/capabilities/capability-utils-test.php
Labels: changelog: bugfix, test by qa

#14140 Make all shortlinker calls secure
  admin/views/tabs/dashboard/dashboard.php
  admin/views/tabs/metas/paper-content/breadcrumbs-content.php
Labels: changelog: non-user-facing

#14184 Improve paging comments health check
  css/src/admin-global.scss
  inc/health-check-page-comments.php
  inc/health-check.php
  tests/inc/health-check-page-comments-test.php
  tests/inc/health-check-test.php
Labels: changelog: enhancement

#14205 Call right cache clear method
  inc/options/class-wpseo-option.php
Labels: 0.5, changelog: bugfix

#14182 Automate RC creation with Grunt (Hackaton)
  .env.example
  .gitignore
  Gruntfile.js
  grunt/config/aliases.yaml
  grunt/config/bump-rc-version.js
  grunt/config/celebrate.js
  grunt/config/check-deploy-allowed.js
  grunt/config/ensure-pre-release-branch.js
  grunt/config/github-pre-release.js
  grunt/config/glotpress_download.js
  grunt/config/notify-slack.js
  grunt/config/prompt.js
  grunt/config/shell.js
  grunt/config/tools/get-user-input.js
  grunt/config/tools/github-api.js
  grunt/config/tools/parse-version.js
  grunt/config/tools/upload-to-github.js
  grunt/config/update-readme.js
  grunt/config/verify-zip-size.js
  grunt/config/webpack.js
  grunt/custom/notify-slack.js
  package.json
  webpack/webpack.config.js
  yarn.lock
Labels: changelog: non-user-facing

#14194 No longer use .min as a suffix
  Gruntfile.js
  admin/class-admin-asset-seo-location.php
  admin/class-asset.php
  grunt/config/copy.js
  integration-tests/admin/test-class-admin-asset-dev-server-location.php
  integration-tests/admin/test-class-admin-asset-seo-location.php
  integration-tests/test-class-admin-asset-manager.php
  integration-tests/test-class-admin-asset.php
  tests/admin/admin-asset-analysis-worker-location-test.php
  tests/admin/metabox/metabox-editor-test.php
  webpack/webpack.config.js
Labels: 1

#14208 Don't output and image object graph piece when the url is empty
  src/generators/schema/main-image.php
  tests/generators/schema/article-test.php
  tests/generators/schema/main-image-test.php
Labels: changelog: non-user-facing, component: indexables

#14212 14063 add description to website
  src/generators/schema/website.php
  tests/generators/schema/website-test.php
Labels: changelog: non-user-facing, component: indexables

#14224 Travis: use 7.4 not snapshot
  .travis.yml
Labels: changelog: non-user-facing, yoast cs/qa

#14219 Fix image caption in schema integration
  src/helpers/schema/image-helper.php
  tests/helpers/schema/html-helper-test.php
  tests/helpers/schema/image-helper-test.php
Labels: changelog: non-user-facing, component: indexables

#14221 Fix robots noindex on static homepage
  src/helpers/robots-helper.php
  tests/admin/capabilities/capability-utils-test.php
  tests/helpers/robots-helper-test.php
  tests/inc/options/options-test.php
Labels: changelog: non-user-facing, component: indexables

#14230 Stop using og image as twitter image
  src/presentations/indexable-presentation.php
  tests/presentations/indexable-post-type-presentation/twitter-image-test.php
  tests/presentations/indexable-presentation/twitter-image-test.php
Labels: changelog: non-user-facing, component: indexables

#14234 QA/I18n: add missing translators comments
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
Labels: changelog: non-user-facing, yoast cs/qa

#14235 CS/QA: clean up namespaced files
  src/builders/indexable-author-builder.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/database/ruckusing-framework.php
  src/helpers/home-url-helper.php
  src/oauth/client.php
  tests/admin/capabilities/capability-utils-test.php
  tests/helpers/author-archive-helper-test.php
  tests/inc/options/options-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#14236 QA: test `setUp()` should not return
  tests/inc/health-check-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#14233 CS/Docs: clean up after merges
  admin/class-admin-asset-seo-location.php
  admin/class-yoast-notification-center.php
  frontend/class-frontend.php
  inc/health-check-page-comments.php
  inc/options/class-wpseo-options.php
  inc/wpseo-non-ajax-functions.php
  integration-tests/admin/links/test-class-link-internal-lookup.php
  integration-tests/capabilities/test-class-capability-manager.php
  integration-tests/frontend/test-class-opengraph.php
  integration-tests/frontend/test-class-wpseo-frontend-robots.php
  integration-tests/notifications/test-class-yoast-notification-center.php
  integration-tests/test-class-admin-asset-manager.php
  tests/admin/capabilities/capability-utils-test.php
  tests/doubles/inc/options/options-double.php
  tests/helpers/author-archive-helper-test.php
  tests/helpers/date-helper-test.php
  tests/inc/health-check-page-comments-test.php
  tests/inc/health-check-test.php
  tests/inc/options/options-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#14237 Docs: use short form types
  admin/class-asset.php
  admin/class-bulk-editor-list-table.php
  admin/class-export.php
  admin/metabox/class-metabox-form-tab.php
  admin/onpage/class-onpage.php
  frontend/class-frontend.php
Labels: changelog: non-user-facing, yoast cs/qa

#14238 QA: properties before methods
  src/database/migration-runner.php
  src/watchers/indexable-author-watcher.php
  src/watchers/indexable-post-watcher.php
  src/watchers/indexable-term-watcher.php
  src/watchers/primary-term-watcher.php
Labels: changelog: non-user-facing, yoast cs/qa

#14231 Hide facebook options when facebook is disabled
  admin/views/tabs/social/facebook.php
  js/src/wp-seo-admin.js
Labels: UI change, changelog: enhancement

#14229 Fixed webpack dev server after hackaton branch was merged
  grunt/config/webpack.js
  webpack/webpack.config.js
Labels: 0.5, changelog: non-user-facing

#14246 Bump monorepo packages for the 12.9 release
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14244 Update taxonomy title
  src/integrations/watchers/indexable-term-watcher.php
  src/presentations/indexable-term-archive-presentation.php
  tests/admin/capabilities/capability-utils-test.php
  tests/presentations/indexable-term-archive-presentation/title-test.php
Labels: changelog: non-user-facing, component: indexables, component: innovation

#14247 Bump RC packages for 13.0 release
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#14260 Adds two fields to the indexables table
  migrations/20200121154000_WpYoastIndexablesAddFields.php
  src/builders/indexable-post-builder.php
  src/models/indexable.php
  tests/builders/indexable-post-builder-test.php
Labels: changelog: non-user-facing, component: indexables

#14223 Limit targets for force rewrite titles option to title tags in head tag
  frontend/class-frontend.php
  integration-tests/frontend/test-class-wpseo-frontend.php
Labels: community-patch

#14266 Add doc comments
  src/builders/indexable-post-builder.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  src/models/indexable-extension.php
  src/repositories/indexable-repository.php
  tests/builders/indexable-author-builder-test.php
Labels: changelog: non-user-facing, component: indexables

#14268 Various codestyle fixes
  admin/import/plugins/class-import-rankmath.php
  frontend/schema/class-schema-article.php
  frontend/schema/class-schema-person.php
  inc/class-rewrite.php
  inc/class-upgrade.php
  inc/class-wpseo-primary-term.php
  inc/sitemaps/class-sitemaps-cache.php
  integration-tests/admin/exceptions/test-file-size-exception.php
  integration-tests/admin/links/test-class-link-storage.php
  integration-tests/doubles/class-dismissible-notification-double.php
  integration-tests/doubles/frontend-double.php
  integration-tests/frontend/test-class-wpseo-opengraph-image.php
  integration-tests/inc/test-class-wpseo-upgrade.php
  integration-tests/notifications/test-class-yoast-notification-center.php
  src/conditionals/indexables-feature-flag-conditional.php
  src/watchers/indexable-author-watcher.php
  src/watchers/indexable-post-watcher.php
  src/watchers/indexable-term-watcher.php
  src/watchers/primary-term-watcher.php
  tests/admin/capabilities/capability-utils-test.php
  tests/admin/myyoast-proxy-test.php
Labels: changelog: non-user-facing

#14269 Merge pull request #14269 from Yoast/code-cleanup-free-docs-maarten
  admin/class-yoast-notification-center.php
  integration-tests/admin/test-class-yoast-network-admin.php
  integration-tests/doubles/class-dismissible-notification-double.php
  integration-tests/doubles/class-upgrade-double.php
  integration-tests/doubles/frontend-double.php
Labels: changelog: non-user-facing

#14262 Simpler copy for the paginated comments Site Health test.
  inc/health-check-page-comments.php
  tests/inc/health-check-page-comments-test.php
Labels: UI change, changelog: enhancement

#14293 Adds the `yoast` body class yoast SEO admin pages
  admin/class-admin.php
Labels: changelog: non-user-facing

#14305 Duplicate directory in Composer autoload
  composer.json
Labels: changelog: non-user-facing, community-patch

#14150 Make get_date_archive_permalink use a static return
  src/helpers/current-page-helper.php
  tests/helpers/current-page-helper-test.php
Labels: changelog: non-user-facing

#14180 Removes support for PHP < 5.6
  admin/class-admin.php
  admin/links/class-link-compatibility-notifier.php
  deprecated/admin/links/class-link-compatibility-notifier.php
  inc/class-addon-manager.php
  inc/sitemaps/class-sitemaps-renderer.php
  tests/admin/admin-features-test.php
Labels: changelog: non-user-facing, community-patch

#14176 Don't sanitize properly encoded URL
  inc/class-wpseo-utils.php
Labels: community-patch
