Repository Yoast/wordpress-seo, pull requests merged in 2020-08, with the labels that each got.

#15773 Bump packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15774 Change the background-image when the schema-tab is selected
  css/src/metabox.css
Labels: changelog: enhancement

#15776 Hide notice from other pages than the tools page
  src/integrations/admin/indexation-integration.php
  src/presenters/admin/indexation-warning-presenter.php
  tests/integrations/admin/indexation-integration-test.php
  tests/presenters/admin/indexation-warning-presenter-test.php
Labels: changelog: non-user-facing

#15777 Set minimum WP version to 5.4
  .travis.yml
  readme.txt
  wp-seo.php
Labels: changelog: other

#15779 Bump packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15781 Fixes schema person being output when article is not
  src/generators/schema/author.php
  src/generators/schema/person.php
Labels: changelog: non-user-facing

#15775 Build a schema tab for the metabox
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  css/src/metabox.css
  css/src/search-appearance.css
  grunt/config/eslint.js
  inc/class-wpseo-meta.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option-titles.php
  js/src/components/SchemaSettings.js
  js/src/components/SchemaTab.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/components/portals/SchemaSettingsPortal.js
  js/src/containers/SchemaSettings.js
  js/src/containers/SchemaTab.js
  js/src/initializers/search-appearance.js
  src/builders/indexable-post-builder.php
  src/config/schema-types.php
  src/context/meta-tags-context.php
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/person.php
  src/generators/schema/webpage.php
  src/helpers/schema/article-helper.php
  tests/integration/test-class-wpseo-metabox.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/context/meta-tags-context-test.php
  tests/unit/doubles/context/meta-tags-context-mock.php
  tests/unit/doubles/models/indexable-mock.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/article-test.php
  tests/unit/generators/schema/author-test.php
  tests/unit/generators/schema/person-test.php
  tests/unit/generators/schema/webpage-test.php
Labels: UI change, changelog: enhancement

#15782 Fix travis deploy
  .travis.yml
Labels: changelog: non-user-facing

#15783 P2-205 Hide the permalink warning also when you're not on the tools page
  src/presenters/admin/indexation-permalink-warning-presenter.php
  src/presenters/admin/indexation-warning-presenter.php
Labels: changelog: non-user-facing

#15785 Load TwitterCardType in store and update the selector
  admin/formatter/class-metabox-formatter.php
  js/src/initializers/edit.js
  js/src/redux/selectors/twitterEditor.js
Labels: changelog: enhancement

#15787 Bump packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15789 Fixes a bug where the option titles would error on schema settings wh…
  inc/options/class-wpseo-option-titles.php
Labels: changelog: non-user-facing

#15791 P3-98 Add `yoast` class to SEMrush modal
  js/src/components/RelatedKeyphrasesModal.js
Labels: changelog: non-user-facing

#15793 Add missing text domain in JS tests
  js/tests/setupTests.js
Labels: changelog: non-user-facing

#15794 Add post settings modal redux layer
  js/src/redux/actions/index.js
  js/src/redux/actions/postSettingsModal.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/postSettingsModal.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/postSettingsModal.js
  js/tests/redux/actions/postSettingsModal.test.js
  js/tests/redux/reducers/postSettingsModal.test.js
  js/tests/redux/selectors/postSettingsModal.test.js
Labels: changelog: non-user-facing

#15792 Finish Country Selector Component
  admin/formatter/class-metabox-formatter.php
  css/src/gutenberg-modal.css
  js/src/components/RelatedKeyphrasesModal.js
  js/src/components/RelatedKeyphrasesModalContent.js
  js/src/components/modals/KeyphrasesTable.js
  js/src/components/modals/SEMrushCountrySelector.js
  js/src/containers/RelatedKeyphrases.js
  js/src/initializers/edit.js
  js/src/redux/actions/SEMrushRequest.js
  js/src/redux/reducers/SEMrushModal.js
  js/src/redux/reducers/SEMrushRequest.js
  js/src/redux/selectors/SEMrushRequest.js
Labels: changelog: non-user-facing

#15797 P3-100 Check the Dashboard widget response.
  js/src/dashboard-widget.js
Labels: changelog: bugfix

#15798 Update grunt plugin tasks
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15795 P1-102 add open post settings button to sidebar
  js/src/components/OpenPostSettingsModal.js
  js/src/components/fills/SidebarFill.js
Labels: changelog: enhancement

#15735 Refactor: separate block editor and classic editor initialization
  admin/class-admin-asset-manager.php
  admin/metabox/class-metabox.php
  config/webpack/paths.js
  config/webpack/webpack.config.js
  inc/class-wpseo-utils.php
  js/src/analysis/blockEditorData.js
  js/src/analysis/classicEditorData.js
  js/src/analysis/collectAnalysisData.js
  js/src/analysis/getIndicatorForScore.js
  js/src/analysis/getL10nObject.js
  js/src/analysis/plugins/replacevar-plugin.js
  js/src/block-editor.js
  js/src/classic-editor.js
  js/src/components/SnippetPreviewModal.js
  js/src/components/social/FacebookWrapper.js
  js/src/components/social/TwitterWrapper.js
  js/src/containers/FacebookEditor.js
  js/src/containers/SnippetEditor.js
  js/src/containers/TwitterEditor.js
  js/src/helpers/classicEditor.js
  js/src/helpers/isBlockEditor.js
  js/src/helpers/isGutenbergAvailable.js
  js/src/helpers/isGutenbergDataAvailable.js
  js/src/initializers/block-editor-integration.js
  js/src/initializers/classic-editor-integration.js
  js/src/initializers/edit.js
  js/src/initializers/editor-store.js
  js/src/initializers/featured-image.js
  js/src/initializers/metabox-tabs.js
  js/src/initializers/post-scraper.js
  js/src/initializers/primary-category.js
  js/src/initializers/term-scraper.js
  js/src/initializers/used-keywords-assessment.js
  js/src/post-edit.js
  js/src/redux/actions/primaryTaxonomies.js
  js/src/redux/reducers/facebookEditor.js
  js/src/redux/reducers/markerButtons.js
  js/src/redux/reducers/twitterEditor.js
  js/src/redux/selectors/facebookEditor.js
  js/src/redux/selectors/twitterEditor.js
  js/src/term-edit.js
  js/tests/blockEditorData.test.js
  js/tests/edit.test.js
  js/tests/isGutenbergAvailable.test.js
  package.json
  yarn.lock
Labels: changelog: bugfix, changelog: non-user-facing

#15804 Check if there is a language string before adding translator comment
  grunt/custom/convert-pot-to-wp.js
Labels: 0, changelog: non-user-facing

#15813 Sets the assets directory for svn
  Gruntfile.js
Labels: build tooling, changelog: non-user-facing

#15465 POC: Use helpers instead of static utils
  admin/admin-settings-changed-listener.php
  admin/class-admin-media-purge-notification.php
  admin/class-admin.php
  inc/class-wpseo-replace-vars.php
  inc/class-wpseo-utils.php
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-sitemap-image-parser.php
  src/helpers/current-page-helper.php
  src/helpers/site-helper.php
  src/helpers/url-helper.php
  tests/helpers/site-helper-test.php
  tests/integration/formatter/test-post-metabox-formatter.php
  tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
  tests/unit/admin/admin-features-test.php
  tests/unit/helpers/url-helper-test.php
Labels: changelog: non-user-facing

#15805 P3-92 Remove SEMrush logic that belongs to Premium
  js/src/containers/RelatedKeyphrases.js
  js/src/redux/actions/SEMrushKeyphrases.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/SEMrushKeyphrases.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/SEMrushKeyphrases.js
  js/src/redux/selectors/index.js
Labels: changelog: non-user-facing

#15697 Adds writable check to robots.txt file editor to comply with WordPress.com
  admin/views/tool-file-editor.php
Labels: changelog: bugfix, community-patch

#15812 Move grunt config to config dir
  .gitattributes
  Gruntfile.js
  config/grunt/custom-tasks/bump-rc-version.js
  config/grunt/custom-tasks/celebrate.js
  config/grunt/custom-tasks/check-deploy-allowed.js
  config/grunt/custom-tasks/convert-pot-to-wp.js
  config/grunt/custom-tasks/ensure-pre-release-branch.js
  config/grunt/custom-tasks/ensure-rc-dependencies.js
  config/grunt/custom-tasks/github-pre-release.js
  config/grunt/custom-tasks/i18n-clean-json.js
  config/grunt/custom-tasks/notify-slack.js
  config/grunt/custom-tasks/remove-vendor-prefixed-folder.js
  config/grunt/custom-tasks/sync-gutenberg-version.js
  config/grunt/custom-tasks/update-changelog.js
  config/grunt/custom-tasks/update-readme.js
  config/grunt/custom-tasks/verify-zip-size.js
  config/grunt/lib/get-user-input.js
  config/grunt/lib/github-api.js
  config/grunt/lib/parse-version.js
  config/grunt/lib/upload-to-github.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/convert-pot-to-wp.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/eslint.js
  config/grunt/task-config/glotpress_download.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/notify-slack.js
  config/grunt/task-config/po2json.js
  config/grunt/task-config/postcss.js
  config/grunt/task-config/prompt.js
  config/grunt/task-config/shell.js
  config/grunt/task-config/update-changelog.js
  config/grunt/task-config/update-version.js
  config/grunt/task-config/watch.js
  config/grunt/task-config/webpack.js
Labels: changelog: non-user-facing

#15810 Remove unused JavaScript dependencies
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15818 Make addon display titles translatable
  admin/views/licenses.php
Labels: changelog: non-user-facing

#15821 Moved site-helper-test.php to its appropriate subfolder.
  tests/unit/helpers/site-helper-test.php
Labels: changelog: non-user-facing

#15820 Remove the monorepo version bumps from the RC automatization
  config/grunt/custom-tasks/ensure-rc-dependencies.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/shell.js
Labels: changelog: non-user-facing

#15825 P1-121 Add safety check to the tool file editor
  admin/views/tool-file-editor.php
Labels: changelog: non-user-facing

#15290 Deprecate all SEO score recalculation related code
  admin/ajax.php
  admin/ajax/class-recalculate-scores-ajax.php
  admin/class-admin-asset-manager.php
  admin/class-admin.php
  admin/class-recalculate-scores.php
  admin/pages/tools.php
  admin/recalculate/class-recalculate-posts.php
  admin/recalculate/class-recalculate-terms.php
  admin/recalculate/class-recalculate.php
  config/webpack/paths.js
  deprecated/admin/ajax/class-recalculate-scores-ajax.php
  deprecated/admin/class-recalculate-scores.php
  deprecated/admin/recalculate/class-recalculate-posts.php
  deprecated/admin/recalculate/class-recalculate-terms.php
  deprecated/admin/recalculate/class-recalculate.php
  js/src/recalculate.js
  tests/integration/doubles/class-recalculate-posts-double.php
  tests/integration/recalculate/test-class-recalculate-posts.php
  tests/integration/recalculate/test-class-recalculate-scores-ajax.php
  tests/integration/recalculate/test-class-recalculate-terms.php
Labels: 0.5, changelog: non-user-facing

#15824 Remove the WP_CLI command namespaces.
  cli/class-cli-redirect-upsell-command-namespace.php
  cli/class-cli-yoast-command-namespace.php
  composer.json
  config/grunt/task-config/copy.js
  wp-seo-main.php
Labels: changelog: non-user-facing

#15799 Connect Related keyphrases API call to the redux state and UI
  js/src/components/RelatedKeyphrasesModal.js
  js/src/components/RelatedKeyphrasesModalContent.js
  js/src/components/modals/KeyphrasesTable.js
  js/src/components/modals/SEMrushCountrySelector.js
  js/src/containers/RelatedKeyphrases.js
  js/src/helpers/classicEditor.js
  js/src/redux/actions/SEMrushRequest.js
  js/src/redux/reducers/SEMrushRequest.js
  js/src/redux/selectors/SEMrushRequest.js
  src/routes/semrush-route.php
Labels: changelog: non-user-facing

#15827 Show Country Selector with request failed message
  js/src/components/RelatedKeyphrasesModalContent.js
Labels: changelog: non-user-facing

#15819 Fix premium button styling in keyphrases table
  js/src/components/modals/KeyphrasesTable.js
Labels: changelog: non-user-facing

#15831 P1-124 Do not overwrite our YoastSEO global (on terms)
  js/src/initializers/term-scraper.js
Labels: changelog: non-user-facing

#15740 Improved sql performance
  src/helpers/post-helper.php
  src/surfaces/meta-surface.php
Labels: changelog: bugfix

#15817 Ensure only a single indexable query is run for the posts overview
  admin/class-meta-columns.php
  src/surfaces/meta-surface.php
  tests/unit/surfaces/meta-surface-test.php
Labels: changelog: non-user-facing

#15834 Refactored the API call slightly to return less columns
  js/src/components/modals/KeyphrasesTable.js
  src/actions/semrush/semrush-phrases-action.php
Labels: changelog: non-user-facing

#15808 Add Polish to the list of morphology-supported languages
  src/helpers/language-helper.php
Labels: changelog: non-user-facing

#15826 Added validation for the keyphrase input
  js/src/components/contentAnalysis/KeywordInput.js
Labels: changelog: enhancement

#15828 P1-123 Add schema type validation
  src/generators/schema-generator.php
  tests/unit/generators/schema-generator-test.php
Labels: changelog: other

#15842 Fix dependency on wp-blocks for classic editor integration.
  admin/class-admin-asset-manager.php
  admin/class-primary-term-admin.php
  admin/metabox/class-metabox.php
  src/integrations/third-party/web-stories.php
  tests/unit/integrations/third-party/web-stories-test.php
Labels: changelog: bugfix

#15840 P3-101 - P3-95 Refactor checks for comma in keyphrase and max keyphrase length
  js/src/components/contentAnalysis/KeywordInput.js
Labels: changelog: non-user-facing

#15843 Show maximum related keyphrase warning
  js/src/components/RelatedKeyphrasesModal.js
  js/src/components/RelatedKeyphrasesModalContent.js
Labels: changelog: enhancement

#15823 P3 84 update notifications
  admin/class-admin-init.php
  admin/class-yoast-notification-center.php
  release-info.json
Labels: changelog: enhancement

#15839 P1-119 Apply advanced section capability and option to the schema tab
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/views/class-yoast-feature-toggles.php
  inc/class-wpseo-meta.php
  js/src/components/SchemaTab.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/containers/MetaboxFill.js
  js/src/containers/SchemaTab.js
  js/src/redux/reducers/preferences.js
  tests/unit/admin/metabox/metabox-test.php
Labels: changelog: non-user-facing

#15816 Fix breadcrumb page numbers in paginated series
  src/generators/breadcrumbs-generator.php
  src/generators/schema/breadcrumb.php
  src/helpers/pagination-helper.php
  tests/unit/generators/breadcrumbs-generator-test.php
  tests/unit/generators/schema/breadcrumb-test.php
  tests/unit/helpers/pagination-helper-test.php
Labels: changelog: bugfix

#15844 Show SchemaSettings change alert before onBlur
  js/src/components/SchemaSettings.js
Labels: changelog: non-user-facing

#15852 Bump monorepo packages for 14.8-RC4
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15811 Updates the screenshots
  svn-assets/screenshot-1.png
  svn-assets/screenshot-2.png
Labels: changelog: non-user-facing

#15854 Remove underscore prefixes from method names
  lib/orm.php
Labels: changelog: non-user-facing

#15829 P3-103 disable SEMrush on terms edit pages and edit attachment page
  admin/formatter/class-term-metabox-formatter.php
  admin/metabox/class-metabox.php
Labels: changelog: non-user-facing

#15599 Add port to indeaxble permalink when available
  src/models/indexable.php
Labels: changelog: bugfix, community-patch, has patch

#15857 Initialize slug from the store when in block editor
  js/src/analysis/PostDataCollector.js
Labels: changelog: bugfix

#15856 P3 109 send request on open modal
  js/src/components/RelatedKeyphrasesModalContent.js
  js/src/components/modals/SEMrushCountrySelector.js
Labels: UI change, changelog: enhancement

#15870 P1-132 Fix primary category
  admin/class-primary-term-admin.php
Labels: changelog: non-user-facing

#15871 P3-111 Adds wp-api-fetch to the classic-editor asset loading configuration
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing

#15874 Bump monorepo packages for 14.8 release
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15875 Bump monorepo packages for 14.9-RC1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15815 P1-104 Create post settings modal component
  config/webpack/paths.js
  css/src/metabox.css
  css/src/modal.css
  js/src/components/ModalButtonContainer.js
  js/src/components/OpenPostSettingsModal.js
  js/src/components/contentAnalysis/SeoAnalysis.js
  js/src/components/fills/SidebarFill.js
  js/src/components/modals/Modal.js
  js/src/components/modals/PostSettingsModal.js
  js/src/components/modals/SeoAnalysisModal.js
  js/src/modal.js
  js/src/redux/actions/index.js
  js/src/redux/actions/postSettingsModal.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/postSettingsModal.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/postSettingsModal.js
  js/tests/redux/actions/postSettingsModal.test.js
  js/tests/redux/reducers/postSettingsModal.test.js
  js/tests/redux/selectors/postSettingsModal.test.js
Labels: changelog: non-user-facing

#15876 Cherry pick modal changes from feature metabox modal
  config/webpack/paths.js
  css/src/metabox.css
  css/src/modal.css
  js/src/components/ModalButtonContainer.js
  js/src/components/contentAnalysis/SeoAnalysis.js
  js/src/components/modals/Modal.js
  js/src/components/modals/SeoAnalysisModal.js
  js/src/modal.js
Labels: changelog: non-user-facing

#15879 [P2-272] Don't do queries when there are no post IDs
  admin/class-meta-columns.php
  src/repositories/indexable-repository.php
  tests/unit/admin/meta-columns-test.php
Labels: changelog: non-user-facing

#15882 WebPack RC build version fix - P2-256
  config/grunt/task-config/webpack.js
Labels: changelog: non-user-facing

#15880 P1-133 Merge robot meta tags
  src/integrations/front-end-integration.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presenters/bingbot-presenter.php
  src/presenters/googlebot-presenter.php
  src/surfaces/values/meta.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/presentations/indexable-author-archive-presentation/robots-test.php
  tests/unit/presentations/indexable-date-archive-presentation/robots-test.php
  tests/unit/presentations/indexable-post-type-archive-presentation/robots-test.php
  tests/unit/presentations/indexable-post-type-presentation/robots-test.php
  tests/unit/presentations/indexable-presentation/googlebot-test.php
  tests/unit/presentations/indexable-presentation/robots-test.php
  tests/unit/presentations/indexable-term-archive-presentation/robots-test.php
  tests/unit/presenters/bingbot-presenter-test.php
  tests/unit/presenters/googlebot-presenter-test.php
Labels: changelog: other

#15878 Add SECURITY.md to the repository
  .github/SECURITY.md
Labels: changelog: non-user-facing

#15881 Changes the SEMrush modal to the custom Yoast modal one
  js/src/components/RelatedKeyphrasesModal.js
Labels: changelog: non-user-facing

#15884 P3-118 Fix problem with country code not initialized with value from database
  js/src/initializers/editor-store.js
Labels: changelog: non-user-facing

#15885 Set a max width on the SEMrush modal and moved to modal.css
  css/src/admin-global.css
  css/src/gutenberg-modal.css
  css/src/modal.css
Labels: changelog: enhancement

#15853 Exclude the file_system specific sniffs
  phpcs.xml.dist
Labels: yoast cs/qa

#15849 Cleanup frontend classes
  admin/views/tabs/metas/paper-content/post_type/woocommerce-shop-page.php
  composer.json
  deprecated/frontend/class-frontend-page-type.php
  deprecated/frontend/class-woocommerce-shop-page.php
  frontend/class-woocommerce-shop-page.php
  frontend/index.php
  src/helpers/woocommerce-helper.php
  src/surfaces/helpers-surface.php
  tests/integration/doubles/class-wpseo-woocommerce-shop-page-double.php
  tests/integration/frontend/test-class-front-end-page-type.php
  tests/integration/frontend/test-class-woocommerce-shop-page.php
  tests/unit/helpers/woocommerce-helper-test.php
  tests/unit/integrations/third-party/woocommerce-test.php
Labels: changelog: non-user-facing

#15858 Use premium composer for checks
  .travis.yml
  composer.json
  config/composer/actions.php
Labels: changelog: non-user-facing

#15536 Issue #15082 - Expected parameter 2 to be an array, bool given
  src/actions/indexation/indexable-post-type-archive-indexation-action.php
Labels: community-patch

#15883 Resets the child permalinks
  src/builders/indexable-builder.php
  src/helpers/indexable-helper.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/repositories/indexable-hierarchy-repository.php
  src/repositories/indexable-repository.php
  src/surfaces/helpers-surface.php
  tests/unit/builders/indexable-builder-test.php
  tests/unit/helpers/indexable-helper-test.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: bugfix, component: indexables

#15890 Renamed files and classes to ensure consistency
  js/src/components/SEMrushRelatedKeyphrasesModal.js
  js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/modals/SEMrushKeyphrasesTable.js
  js/src/components/modals/SEMrushLimitReached.js
  js/src/components/modals/SEMrushLoading.js
  js/src/components/modals/SEMrushMaxRelatedKeyphrases.js
  js/src/components/modals/SEMrushRequestFailed.js
  js/src/components/modals/SEMrushUpsellAlert.js
  js/src/containers/SEMrushRelatedKeyphrases.js
  js/src/containers/SEMrushRelatedKeyphrasesModal.js
Labels: changelog: non-user-facing

#15886 Add postSettingsModal actions
  css/src/modal.css
  js/src/components/AdvancedSettings.js
  js/src/components/PrimaryTaxonomyFilter.js
  js/src/components/PrimaryTaxonomyPicker.js
  js/src/components/SchemaTab.js
  js/src/components/SnippetPreviewSection.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/contentAnalysis/Results.js
  js/src/components/contentAnalysis/SeoAnalysis.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/components/modals/PostSettingsModal.js
  js/src/components/portals/SocialMetadataPortal.js
  js/src/components/social/SocialMetadata.js
  js/src/containers/PostSettingsModal.js
  js/src/containers/PrimaryTaxonomyPicker.js
  js/src/containers/Results.js
  js/src/containers/SocialMetadata.js
  js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#15892 Fixes the building of the monorepo.css when running grunt artifact.
  config/grunt/task-config/webpack.js
Labels: changelog: non-user-facing

#15891 Check trimmed keyphrase before opening the modal
  js/src/components/SEMrushRelatedKeyphrasesModal.js
  js/src/components/contentAnalysis/KeywordInput.js
Labels: changelog: non-user-facing

#15889 P1-134 Prevent modal from closing when the media library opens
  js/src/components/AdvancedSettings.js
  js/src/components/modals/PostSettingsModal.js
Labels: changelog: non-user-facing

#15899 Add postSettingsModal actions
  js/src/components/SnippetPreviewModal.js
Labels: UI change, changelog: other

#15895 Moves SEMrush PHP tests to the new directory and added missing tests for options action
  tests/unit/actions/semrush/semrush-login-action-test.php
  tests/unit/actions/semrush/semrush-options-action-test.php
  tests/unit/actions/semrush/semrush-phrases-action-test.php
  tests/unit/config/semrush-client-test.php
  tests/unit/doubles/config/semrush-client-double.php
  tests/unit/routes/semrush-route-test.php
  tests/unit/values/semrush/semrush-token-test.php
Labels: changelog: non-user-facing

#15906 Set gutenberg version to 8.8.0
  admin/class-gutenberg-compatibility.php
Labels: changelog: non-user-facing

#15907 Adds attribute docs.
  tests/unit/presentations/indexable-date-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-error-page-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-home-page-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-presentation/title-test.php
  tests/unit/presentations/indexable-presentation/twitter-description-test.php
  tests/unit/presentations/indexable-presentation/twitter-title-test.php
  tests/unit/presentations/indexable-search-result-page-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/presentation-instance-dependencies-trait.php
  tests/unit/presenters/admin/indexation-list-item-presenter-test.php
  tests/unit/presenters/twitter/card-presenter-test.php
  tests/unit/presenters/twitter/description-presenter-test.php
  tests/unit/presenters/webmaster/baidu-presenter-test.php
  tests/unit/presenters/webmaster/bing-presenter-test.php
  tests/unit/presenters/webmaster/google-presenter-test.php
  tests/unit/presenters/webmaster/pinterest-presenter-test.php
  tests/unit/presenters/webmaster/yandex-presenter-test.php
  tests/unit/surfaces/meta-surface-test.php
  tests/unit/values/images-test.php
  tests/unit/values/open-graph/images-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#13768 Added output escaping
  admin/views/tabs/dashboard/webmaster-tools.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/archives/help.php
  admin/views/tabs/metas/breadcrumbs.php
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
  admin/views/tabs/metas/paper-content/media-content.php
  admin/views/tabs/metas/paper-content/post_type/woocommerce-shop-page.php
  admin/views/tabs/metas/paper-content/rss-content.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/rss.php
  admin/views/tabs/metas/taxonomies.php
  admin/views/tabs/social/accounts.php
  admin/views/tabs/social/facebook.php
Labels: changelog: non-user-facing

#15903 Increased coverage of indexable post builder, indexable term builder and social image trait
  src/builders/indexable-post-builder.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/builders/indexable-social-image-trait-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/doubles/builders/indexable-post-builder-double.php
  tests/unit/doubles/builders/indexable-social-image-trait-double.php
  tests/unit/doubles/builders/indexable-term-builder-double.php
Labels: changelog: non-user-facing, component: innovation

#15922 Call the article helper to determine the Schema article type
  inc/options/class-wpseo-option-titles.php
  src/helpers/schema/article-helper.php
Labels: changelog: enhancement

#15923 Add integration to disable concatenate scripts
  src/integrations/admin/disable-concatenate-scripts-integration.php
  tests/unit/integrations/admin/indexation-integration-test.php
Labels: changelog: bugfix

#15912 Pass the indexable to the wpseo_schema_article_type filter
  src/context/meta-tags-context.php
Labels: changelog: non-user-facing, component: innovation

#15838 Add wpseo_sitemap_index_links filter
  inc/sitemaps/class-sitemaps.php
Labels: changelog: enhancement, community-patch

#15917 Route data via Redux for Advanced Tab
  inc/class-wpseo-utils.php
  js/src/components/AdvancedSettings.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/modals/PostSettingsModal.js
  js/src/containers/AdvancedSettings.js
  js/src/containers/PostSettingsModal.js
  js/src/helpers/fields/AdvancedFields.js
  js/src/redux/actions/advancedSettings.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/advancedSettings.js
  js/src/redux/reducers/editorContext.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/preferences.js
  js/src/redux/selectors/advancedSettings.js
  js/src/redux/selectors/editorContext.js
  js/src/redux/selectors/index.js
  js/tests/redux/actions/advancedSetings.test.js
  js/tests/redux/reducers/advancedSettings.test.js
Labels: changelog: non-user-facing

#15915 P3 123 add tests for semrush redux
  js/src/components/modals/SEMrushCountrySelector.js
  js/src/containers/SEMrushRelatedKeyphrases.js
  js/src/redux/actions/SEMrushRequest.js
  js/tests/redux/actions/SEMrushModal.test.js
  js/tests/redux/actions/SEMrushRequest.test.js
  js/tests/redux/reducers/SEMrushModal.test.js
  js/tests/redux/reducers/SEMrushRequest.test.js
  js/tests/redux/selectors/SEMrushModal.test.js
  js/tests/redux/selectors/SEMrushRequest.test.js
Labels: changelog: non-user-facing, component: tests

#15931 Up WC tested up to to 4.5.0
  wp-seo.php
Labels: changelog: non-user-facing

#15927 Add SEMrush login popup
  admin/formatter/class-metabox-formatter.php
  config/grunt/task-config/eslint.js
  css/src/modal.css
  js/src/components/SEMrushRelatedKeyphrasesModal.js
  js/src/containers/SEMrushRelatedKeyphrasesModal.js
  js/src/initializers/editor-store.js
  js/src/redux/actions/SEMrushRequest.js
  js/src/redux/reducers/SEMrushRequest.js
  js/src/redux/selectors/SEMrushRequest.js
Labels: changelog: non-user-facing

#15929 Upgrade react-select to the latest version
  admin/config-ui/fields/class-field-tracking.php
  js/src/components/WordPressUserSelector.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15930 Strip extra robot values
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  tests/unit/presentations/indexable-author-archive-presentation/robots-test.php
  tests/unit/presentations/indexable-date-archive-presentation/robots-test.php
  tests/unit/presentations/indexable-post-type-archive-presentation/robots-test.php
  tests/unit/presentations/indexable-post-type-presentation/robots-test.php
  tests/unit/presentations/indexable-presentation/robots-test.php
  tests/unit/presentations/indexable-term-archive-presentation/robots-test.php
Labels: changelog: bugfix

#15924 Add redux to the Schema-tab.
  js/src/components/SchemaTab.js
  js/src/components/social/FacebookWrapper.js
  js/src/components/social/TwitterWrapper.js
  js/src/containers/FacebookEditor.js
  js/src/containers/SchemaTab.js
  js/src/containers/TwitterEditor.js
  js/src/helpers/fields/SchemaFields.js
  js/src/redux/actions/index.js
  js/src/redux/actions/schemaTab.js
  js/src/redux/reducers/facebookEditor.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/schemaTab.js
  js/src/redux/reducers/twitterEditor.js
  js/src/redux/selectors/facebookEditor.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/schemaTab.js
  js/src/redux/selectors/twitterEditor.js
Labels: changelog: non-user-facing

#15911 Introduce PHP coding-standards thresholds
  .editorconfig
  .travis.yml
  composer.json
  composer.lock
  config/composer/actions.php
  config/composer/scripts/maybe-restore-composer-lock.php
  phpcs.xml.dist
  phpunit.xml.dist
Labels: changelog: non-user-facing

#15939 Prevent ATtype of null to end up in our schema
  src/context/meta-tags-context.php
Labels: changelog: bugfix

#15938 Cleaned up the containers to use a better notation
  js/src/containers/SEMrushRelatedKeyphrases.js
  js/src/containers/SEMrushRelatedKeyphrasesModal.js
Labels: changelog: non-user-facing

#15941 Remove legacy indexables code
  admin/endpoints/class-endpoint-indexable.php
  admin/services/class-indexable-post-provider.php
  admin/services/class-indexable-provider.php
  admin/services/class-indexable-term-provider.php
  admin/services/class-indexable.php
  admin/services/interface-indexable-provider.php
  inc/indexables/class-indexable.php
  inc/indexables/class-object-type.php
  inc/indexables/class-post-indexable.php
  inc/indexables/class-post-object-type.php
  inc/indexables/class-term-indexable.php
  inc/indexables/class-term-object-type.php
  inc/indexables/validators/class-endpoint-validator.php
  inc/indexables/validators/class-keyword-validator.php
  inc/indexables/validators/class-link-validator.php
  inc/indexables/validators/class-meta-values-validator.php
  inc/indexables/validators/class-object-type-validator.php
  inc/indexables/validators/class-opengraph-validator.php
  inc/indexables/validators/class-robots-validator.php
  inc/indexables/validators/class-twitter-validator.php
  phpcs.xml.dist
  tests/integration/admin/services/test-class-endpoint-indexable.php
  tests/integration/admin/services/test-class-indexable-post-provider.php
  tests/integration/admin/services/test-class-indexable-term-provider.php
  tests/integration/doubles/class-indexable-double.php
  tests/integration/doubles/class-indexable-post-provider-double.php
  tests/integration/doubles/class-indexable-term-provider-double.php
  tests/integration/doubles/class_indexable_service_double.php
  tests/integration/inc/indexables/test-class-indexable.php
  tests/integration/inc/indexables/test-class-object-type.php
  tests/integration/inc/indexables/test-class-post-indexable.php
  tests/integration/inc/indexables/test-class-term-indexable.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#15946 CS: no unnecessary double quoted string usage
  composer.json
  tests/integration/sitemaps/test-class-wpseo-sitemaps.php
  tests/unit/builders/indexable-social-image-trait-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15947 CS: fix modifier keyword order
  composer.json
  src/actions/indexation/abstract-link-indexing-action.php
Labels: changelog: non-user-facing, yoast cs/qa

#15948 CS: fix a variety of whitespace and other small issues
  admin/class-admin-init.php
  admin/class-yoast-notification-center.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-fields.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  composer.json
  inc/options/class-wpseo-option-wpseo.php
  lib/orm.php
  src/actions/indexation/abstract-link-indexing-action.php
  src/builders/indexable-link-builder.php
  src/deprecated/admin/taxonomy/class-taxonomy-content-fields.php
  src/deprecated/admin/taxonomy/class-taxonomy-settings-fields.php
  src/deprecated/admin/taxonomy/class-taxonomy-social-fields.php
  src/helpers/indexable-helper.php
  src/integrations/watchers/indexable-post-watcher.php
  src/presenters/admin/indexation-warning-presenter.php
  src/presenters/admin/meta-fields-presenter.php
  src/routes/link-indexing-route.php
  tests/unit/admin/admin-features-test.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/builders/indexable-social-image-trait-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/generators/breadcrumbs-generator-test.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/webpage-test.php
  tests/unit/helpers/indexable-helper-test.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/helpers/site-helper-test.php
  tests/unit/helpers/url-helper-test.php
  tests/unit/integrations/admin/admin-columns-cache-integration-test.php
  tests/unit/presenters/webmaster/google-presenter-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15949 Docs: various fixes
  composer.json
  src/actions/indexation/abstract-link-indexing-action.php
  src/exceptions/missing-method.php
  src/models/seo-meta.php
  src/presentations/indexable-presentation.php
  src/presenters/bingbot-presenter.php
  src/presenters/googlebot-presenter.php
  src/repositories/seo-meta-repository.php
  src/wordpress/wrapper.php
  tests/unit/doubles/builders/indexable-social-image-trait-double.php
  tests/unit/generators/breadcrumbs-generator-test.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/surfaces/meta-surface-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15950 CS: more whitespace fixes
  composer.json
  src/config/migrations/20200728095334_AddIndexesForProminentWordsOnIndexables.php
  src/surfaces/meta-surface.php
  src/values/open-graph/images.php
  tests/integration/doubles/wpseo-capability-manager-double.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/integrations/admin/indexation-integration-test.php
  tests/unit/repositories/indexable-repository-test.php
  tests/unit/surfaces/meta-surface-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15951 CS: multi-line array and function call fixes
  admin/class-admin-init.php
  composer.json
  lib/orm.php
  src/actions/indexation/post-link-indexing-action.php
  src/actions/indexation/term-link-indexing-action.php
  src/builders/indexable-link-builder.php
  src/config/migrations/20200617122511_CreateSEOLinksTable.php
  src/routes/link-indexing-route.php
  src/surfaces/meta-surface.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps.php
  tests/unit/actions/indexation/post-link-indexing-action-test.php
  tests/unit/actions/indexation/term-link-indexing-action-test.php
  tests/unit/builders/indexable-link-builder-test.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/helpers/url-helper-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15954 Fix id column options in SEO Links migration
  src/config/migrations/20200617122511_CreateSEOLinksTable.php
Labels: changelog: non-user-facing

#15926 Fix PHPCS: docs
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/network/features.php
  config/dependency-injection/services.php
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#15957 Remove the edit button from the Google Preview
  js/src/containers/SnippetEditor.js
Labels: UI change, changelog: other

#15958 Add postSettingsModal actions
  js/src/components/fills/SidebarFill.js
Labels: UI change, changelog: other

#15942 Remove unused myyoast oauth code
  admin/class-admin.php
  admin/class-my-yoast-route.php
  inc/class-my-yoast-api-request.php
  inc/class-wpseo-utils.php
  inc/endpoints/class-myyoast-connect.php
  src/loaders/oauth.php
  src/oauth/client.php
  tests/integration/admin/test-class-my-yoast-route.php
  tests/integration/doubles/class-my-yoast-route-double.php
  tests/integration/inc/endpoints/test-class-myyoast-connect.php
  tests/integration/inc/test-class-myyoast-api-request.php
  tests/unit/doubles/oauth/client-double.php
  tests/unit/oauth/client-test.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#15960 Adds tests for SEMrushRelatedKeyphrasesModal and SEMrushRelatedKeyphrasesModalContent
  js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  js/src/components/contentAnalysis/KeywordInput.js
  js/tests/__mocks__/@wordpress/api-fetch.js
  js/tests/__mocks__/@wordpress/components.js
  js/tests/__mocks__/@wordpress/url.js
  js/tests/components/SEMrushRelatedKeyphrasesModal.test.js
  js/tests/components/SEMrushRelatedKeyphrasesModalContent.test.js
  js/tests/components/contentAnalysis/KeywordInput.test.js
Labels: changelog: non-user-facing

#15956 Added has_function_word_support method to language_helper.
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#15963 We've added the 14.9 notification
  release-info.json
Labels: changelog: non-user-facing

#15909 Renew the permalinks when no taxonomy is set for the breadcrumbs
  src/conditionals/migrations-conditional.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/repositories/indexable-hierarchy-repository.php
  src/repositories/indexable-repository.php
  tests/unit/builders/indexable-link-builder-test.php
  tests/unit/initializers/disable-core-sitemaps-test.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: bugfix

#15961 Add modal location to social slots
  js/src/components/modals/PostSettingsModal.js
  js/src/components/social/FacebookWrapper.js
  js/src/components/social/TwitterWrapper.js
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
Labels: changelog: non-user-facing

#15965 Tests: add missing `@covers` and fix an incorrect one
  tests/unit/builders/indexable-social-image-trait-test.php
  tests/unit/generators/schema/organization-test.php
  tests/unit/helpers/site-helper-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15966 QA: add output escaping
  admin/views/sidebar.php
Labels: changelog: non-user-facing, yoast cs/qa

#15967 Docs: clean up some code documentation
  inc/options/class-wpseo-option.php
Labels: changelog: non-user-facing, yoast cs/qa

#15968 CS: more minor fixes
  admin/class-admin-init.php
  admin/class-premium-upsell-admin-block.php
  admin/config-ui/class-configuration-structure.php
  admin/import/plugins/class-abstract-plugin-importer.php
  admin/views/tabs/dashboard/webmaster-tools.php
  inc/class-addon-manager.php
  src/config/migrations/20200617122511_CreateSEOLinksTable.php
  src/context/meta-tags-context.php
  src/repositories/seo-meta-repository.php
  src/values/open-graph/images.php
  tests/integration/doubles/wpseo-capability-manager-double.php
  tests/unit/helpers/language-helper-test.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
  tests/unit/integrations/xmlrpc-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#15971 PHPCS: clean up and fix ignore annotations
  admin/class-admin-init.php
  admin/class-admin.php
  admin/class-bulk-description-editor-list-table.php
  admin/class-bulk-editor-list-table.php
  admin/class-meta-columns.php
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-network-admin.php
  admin/import/plugins/class-abstract-plugin-importer.php
  admin/metabox/class-metabox.php
  admin/roles/class-role-manager-wp.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/tracking/class-tracking-server-data.php
  admin/views/paper-collapsible.php
  admin/views/partial-notifications-template.php
  admin/views/tabs/dashboard/dashboard.php
  admin/views/tabs/dashboard/webmaster-tools.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/archives/help.php
  admin/views/tabs/metas/breadcrumbs.php
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/media.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
  admin/views/tabs/metas/paper-content/media-content.php
  admin/views/tabs/metas/paper-content/rss-content.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/rss.php
  admin/views/tabs/metas/taxonomies.php
  admin/views/tabs/social/accounts.php
  admin/views/tabs/social/facebook.php
  admin/views/tool-bulk-editor.php
  admin/views/tool-file-editor.php
  composer.json
  config/composer/actions.php
  inc/class-addon-manager.php
  inc/class-wpseo-image-utils.php
  inc/class-wpseo-utils.php
  inc/health-check-default-tagline.php
  inc/options/class-wpseo-options.php
  lib/migrations/constants.php
  lib/model.php
  lib/orm.php
  src/commands/index-command.php
  src/functions.php
  src/generators/schema/article.php
  tests/integration/admin/test-class-plugin-suggestions.php
  tests/integration/admin/test-class-yoast-network-admin.php
  tests/unit/TestCase.php
  wp-seo-main.php
Labels: changelog: non-user-facing, yoast cs/qa

#15975 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15976 Create a PostSettingsModal for the metabox
  css/src/modal.css
  inc/class-wpseo-utils.php
  js/src/components/AdvancedSettings.js
  js/src/components/PrimaryTaxonomyFilter.js
  js/src/components/PrimaryTaxonomyPicker.js
  js/src/components/SchemaTab.js
  js/src/components/SnippetPreviewModal.js
  js/src/components/SnippetPreviewSection.js
  js/src/components/contentAnalysis/ReadabilityAnalysis.js
  js/src/components/contentAnalysis/Results.js
  js/src/components/contentAnalysis/SeoAnalysis.js
  js/src/components/fills/MetaboxFill.js
  js/src/components/fills/SidebarFill.js
  js/src/components/modals/PostSettingsModal.js
  js/src/components/portals/SocialMetadataPortal.js
  js/src/components/social/FacebookWrapper.js
  js/src/components/social/SocialMetadata.js
  js/src/components/social/TwitterWrapper.js
  js/src/containers/AdvancedSettings.js
  js/src/containers/FacebookEditor.js
  js/src/containers/PostSettingsModal.js
  js/src/containers/PrimaryTaxonomyPicker.js
  js/src/containers/Results.js
  js/src/containers/SnippetEditor.js
  js/src/containers/SocialMetadata.js
  js/src/containers/TwitterEditor.js
  js/src/helpers/fields/AdvancedFields.js
  js/src/redux/actions/advancedSettings.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/advancedSettings.js
  js/src/redux/reducers/editorContext.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/preferences.js
  js/src/redux/selectors/advancedSettings.js
  js/src/redux/selectors/editorContext.js
  js/src/redux/selectors/index.js
  js/tests/redux/actions/advancedSetings.test.js
  js/tests/redux/reducers/advancedSettings.test.js
  src/presentations/indexable-error-page-presentation.php
  src/presentations/indexable-post-type-archive-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-static-home-page-presentation.php
Labels: UI change, changelog: enhancement

#15977 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#15964 Add Arabic to languages with word form support
  src/helpers/language-helper.php
Labels: changelog: non-user-facing

#15979 CS: fixes for config/migrations
  src/config/migrations/20171228151840_WpYoastIndexable.php
  src/config/migrations/20191011111109_WpYoastIndexableHierarchy.php
Labels: changelog: non-user-facing, yoast cs/qa
