Repository Yoast/wordpress-seo, pull requests merged in 2021-07, with the labels that each got.

#17209 Add passive voice assessment for Slovak
  packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/getClausesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sk/values/ClauseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultSlovakSpec.js
  packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/internal/nonPassives.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/sk/helpers/getClauses.js
  packages/yoastseo/src/languageProcessing/languages/sk/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/sk/values/Clause.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoiceResult.js
Labels: changelog: enhancement

#17066 Added preparation time block
  packages/schema-blocks/src/instructions/blocks/Duration.tsx
  src/schema-templates/cooking-time.block.php
  src/schema-templates/cooking-time.schema.php
  src/schema-templates/preparation-time.block.php
  src/schema-templates/preparation-time.schema.php
  src/schema-templates/recipe.block.php
  src/schema-templates/recipe.schema.php
  tests/unit/dependency-injection/schema-templates-loader-test.php
Labels: changelog: non-user-facing, component: innovation

#17208 Do 434 zip test
  config/jenkins/Jenkinsfile_artifact
Labels: changelog: non-user-facing

#17211 [IM-456] Fix backwards compatibility of feature-flags
  src/integrations/feature-flag-integration.php
  tests/unit/integrations/feature-flag-integration-test.php
Labels: changelog: bugfix

#17213 replace / with - in branch names during zip creation
  config/jenkins/Jenkinsfile_artifact
Labels: changelog: non-user-facing

#17215 Added Meta_Tags_Context to wpseo_frontend_presenters filter
  src/integrations/front-end-integration.php
  src/routes/yoast-head-rest-field.php
  tests/unit/integrations/front-end-integration-test.php
Labels: changelog: non-user-facing

#17212 Add sentence beginning assessment for Slovak
  packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/firstWordExceptions.js
Labels: changelog: enhancement

#17222 Fix content analysis app not working for Czech and Slovak
  apps/content-analysis/src/App.js
  apps/content-analysis/src/analysis.worker.js
  apps/content-analysis/src/index.js
  apps/content-analysis/src/utils/calculateProminentWords.js
  apps/content-analysis/src/utils/runKeyphraseAnalysis.js
  apps/content-analysis/yarn.lock
Labels: changelog: non-user-facing

#17224 replace is_singular check with post type check
  src/presenters/slack/enhanced-data-presenter.php
  tests/unit/presenters/slack/enhanced-data-presenter-test.php
Labels: changelog: bugfix

#17225 Fix protection of password protected posts in schema generation
  src/generators/schema-generator.php
  tests/unit/generators/schema-generator-test.php
Labels: changelog: non-user-facing

#17223 Fix urls being decoded by WP API
  src/routes/indexables-head-route.php
  tests/unit/routes/indexables-head-route-test.php
Labels: changelog: non-user-facing

#17226 Add conditional for the Norwegian readability feature flag
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  src/conditionals/norwegian-readability-conditional.php
Labels: changelog: non-user-facing

#17145 Add more Norwegian function words
  packages/yoastseo/src/languageProcessing/languages/nb/config/functionWords.js
Labels: changelog: enhancement

#17229 Fix replacevars for rest api
  inc/class-wpseo-replace-vars.php
Labels: changelog: non-user-facing

#17228 P2 1105 correctly deprecate elementor exclusions
  config/dependency-injection/renamed-classes.php
  config/dependency-injection/services.php
  src/deprecated/src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#17217 Improves stemming of some common irregular nouns in Slovak
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/stemSpec.js
  packages/yoastseo/src/languageProcessing/languages/sk/helpers/internal/stem.js
Labels: changelog: enhancement

#17230 [P2-1109] Fix passing context to get presenters
  src/integrations/front-end-integration.php
  src/surfaces/values/meta.php
  tests/unit/integrations/front-end-integration-test.php
Labels: changelog: non-user-facing

#17227 Add full text tests for Slovak
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper3.js
Labels: changelog: non-user-facing

#17232 Rename WordPress_Helper to Wordpress_Helper.
  src/helpers/wordpress-helper.php
  src/integrations/blocks/block-categories.php
  src/surfaces/helpers-surface.php
  tests/unit/helpers/wordpress-helper-test.php
Labels: changelog: non-user-facing

#17231 Add Slovak to README.md in yoastseo package
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#17197 P2-1058 Throw a notification in the /wp-admin/plugins.php to users who have an expired subscription
  inc/class-addon-manager.php
Labels: changelog: enhancement

#17216 Add screen reader text to image select button
  packages/components/src/image-select/ImageSelect.js
  packages/components/tests/ImageSelectTest.js
  packages/components/tests/__snapshots__/ImageSelectTest.js.snap
Labels: changelog: bugfix

#17237 IM-465 Prevent an empty breadcrumbs array on a paginated static frontpage
  src/generators/schema/breadcrumb.php
Labels: community-patch

#17238 Remove Slovak feature flag
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
  src/conditionals/slovak-support-conditional.php
  src/config/researcher-languages.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#17242 Set tested up to version to WP 5.8
  readme.txt
  tests/unit/bootstrap.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#17243 Set WC tested up to to 5.5
  wp-seo.php
Labels: changelog: non-user-facing

#17239 Remove Norwegian readability feature flag
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  src/deprecated/src/conditionals/norwegian-readability-conditional.php
Labels: changelog: non-user-facing

#17156 Added key props to all schema block instruction components
  packages/schema-blocks/src/core/blocks/BlockDefinition.tsx
  packages/schema-blocks/src/core/blocks/BlockLeaf.ts
  packages/schema-blocks/src/leaves/blocks/BlockElementLeaf.ts
  packages/schema-blocks/src/leaves/blocks/BlockRootLeaf.ts
Labels: changelog: non-user-facing

#17235 bump grunt-plugin-tasks to 2.1.2
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#17241 PRODUCT-348 Add cornerstone workout with upsell
  admin/class-admin-asset-manager.php
  admin/views/workouts.php
  css/src/workouts.css
  images/seo_fitness_assistants_fit.svg
  images/seo_fitness_assistants_unfit.svg
  images/stale-cornerstone-content-in-yoast-seo.png
  src/conditionals/premium-inactive-conditional.php
  src/integrations/admin/workouts-integration.php
Labels: UI change, changelog: enhancement

#17187 P2-1115 Improve some performance for AJAX calls and empty WP_Queries
  src/integrations/admin/admin-columns-cache-integration.php
  tests/unit/integrations/admin/admin-columns-cache-integration-test.php
Labels: changelog: bugfix

#17245 P2-1133 update core/editor getBlocks deprecation
  packages/js/src/containers/DocumentSidebar.js
  packages/js/src/containers/PrePublish.js
  packages/js/src/decorator/gutenberg.js
  packages/js/src/helpers/addCheckToChecklist.js
  packages/js/tests/containers/mockSelectors.js
Labels: changelog: non-user-facing

#17244 Fix incorrect robots tag generation
  src/integrations/front-end/wp-robots-integration.php
  tests/unit/integrations/front-end/wp-robots-integration-test.php
Labels: changelog: bugfix

#17261 Fix Slovak feature flag
  src/config/researcher-languages.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: bugfix

#17248 P2-1106 - Show error details if SEO optimization fails.
  packages/components/src/Alert.js
  packages/components/tests/__snapshots__/AlertTest.js.snap
  packages/js/src/components/Indexation.js
  packages/js/src/components/IndexingError.js
  packages/js/src/errors/ParseError.js
  packages/js/src/errors/RequestError.js
  packages/js/tests/indexation.test.js
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
  src/integrations/admin/indexing-tool-integration.php
  src/presenters/admin/indexing-error-presenter.php
  src/routes/indexing-route.php
  tests/unit/integrations/admin/indexing-tool-integration-test.php
  tests/unit/presenters/admin/indexing-error-presenter-test.php
Labels: UI change, changelog: enhancement

#17264 Store the result count of the general indexing action in a transient.
  src/actions/indexing/indexable-general-indexation-action.php
  tests/unit/actions/indexing/indexable-general-indexation-action-test.php
Labels: changelog: enhancement

#17247 Refactored logic for background indexation to reduce count queries
  composer.json
  src/actions/indexing/abstract-indexing-action.php
  src/actions/indexing/abstract-link-indexing-action.php
  src/actions/indexing/indexable-general-indexation-action.php
  src/actions/indexing/indexable-post-indexation-action.php
  src/actions/indexing/indexable-post-type-archive-indexation-action.php
  src/actions/indexing/indexable-term-indexation-action.php
  src/actions/indexing/indexation-action-interface.php
  src/actions/indexing/post-link-indexing-action.php
  src/actions/indexing/term-link-indexing-action.php
  src/commands/index-command.php
  src/helpers/indexable-helper.php
  src/helpers/indexing-helper.php
  src/integrations/admin/background-indexing-integration.php
  tests/unit/actions/indexing/indexable-post-indexation-action-test.php
  tests/unit/actions/indexing/indexable-term-indexation-action-test.php
  tests/unit/actions/indexing/post-link-indexing-action-test.php
  tests/unit/actions/indexing/term-link-indexing-action-test.php
  tests/unit/helpers/indexing-helper-test.php
  tests/unit/integrations/admin/background-indexing-integration-test.php
Labels: changelog: bugfix

#17271 Improve performance for the query to find unindexed posts
  src/actions/indexing/indexable-post-indexation-action.php
  tests/unit/actions/indexing/indexable-post-indexation-action-test.php
Labels: changelog: enhancement

#17270 Remove .gitattributes file
  .gitattributes
Labels: changelog: non-user-facing

#17274 Add product assessors
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17255 P2-1129 Improve editor performance by reducing estimated reading time calculations
  packages/js/src/initializers/estimated-reading-time.js
Labels: changelog: non-user-facing

#17272 P2-1155 Fixes a bug where the incorrect amount of unindexed general pages was returned
  src/actions/indexing/indexable-general-indexation-action.php
  tests/unit/actions/indexing/indexable-general-indexation-action-test.php
Labels: changelog: non-user-facing

#17269 P2-1153 Added post- and term-link indexing to the index cli command
  src/commands/index-command.php
  tests/unit/commands/index-command-test.php
Labels: changelog: enhancement

#17273 Adjust the config for product pages and include videos in images assessment
  packages/yoastseo/spec/languageProcessing/researches/videoCountSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ImageCountAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/researches/videoCount.js
  packages/yoastseo/src/scoring/assessments/seo/ImageCountAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17276 Create a list assessment
  packages/yoastseo/spec/languageProcessing/researches/findListSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ListAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/researches/findList.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: enhancement

#17278 Add product pages config for SEO title width assessment
  packages/yoastseo/spec/scoring/assessments/seo/PageTitleWidthAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17279 Adapt config for product pages text length assessment
  packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17282 Adjust transition words assessment applicability
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper1.js
  packages/yoastseo/spec/scoring/assessments/readability/transitionWordsAssessmentSpec.js
  packages/yoastseo/spec/scoring/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
Labels: changelog: enhancement

#17284 Add extra check for subheading distribution assessment's applicability
  packages/yoastseo/spec/scoring/assessments/readability/subheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/src/scoring/assessments/readability/subheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: enhancement

#17289 Adjust paragraph length criteria for product pages
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/paragraphTooLongAssessment.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: enhancement

#17293 Moves limited indexation count to new interface to avoid complication with backwards compatibility.
  src/actions/indexing/abstract-indexing-action.php
  src/actions/indexing/indexable-general-indexation-action.php
  src/actions/indexing/indexable-post-type-archive-indexation-action.php
  src/actions/indexing/indexation-action-interface.php
  src/actions/indexing/limited-indexing-action-interface.php
  src/helpers/indexing-helper.php
Labels: changelog: non-user-facing

#17295 Delete image count assessment from related keyphrase assessors
  packages/yoastseo/spec/scoring/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/relatedKeywordAssessorSpec.js
  packages/yoastseo/src/scoring/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/relatedKeywordAssessor.js
Labels: changelog: non-user-facing

#17256 Let web worker load custom assessors
  apps/content-analysis/src/analysis.worker.js
  packages/yoastseo/spec/scoring/storeBlog/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storeBlog/seoAssessorSpec.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/scoring/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storeBlog/seoAssessor.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: enhancement

#17299 Use total counts for unindexed links
  src/actions/indexing/abstract-link-indexing-action.php
  tests/unit/actions/indexing/post-link-indexing-action-test.php
  tests/unit/actions/indexing/term-link-indexing-action-test.php
Labels: changelog: non-user-facing
