Repository Yoast/wordpress-seo, pull requests merged in 2021-06, with the labels that each got.

#17100 Revert "Remove the Addon installation feature flag"
  src/conditionals/addon-installation-conditional.php
  src/integrations/admin/addon-installation/dialog-integration.php
  src/integrations/admin/addon-installation/installation-integration.php
  src/routes/supported-features-route.php
  tests/unit/routes/supported-features-route-test.php
Labels: changelog: non-user-facing

#17097 Add Grunt `build:ts` command for compiling TypeScript in the plugin
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/shell.js
Labels: changelog: non-user-facing, component: innovation

#17108 Move social settings below schema settings and restore New badges
  admin/views/tabs/metas/paper-content/post-type-content.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  src/config/badge-group-names.php
  src/integrations/admin/social-templates-integration.php
  tests/unit/config/badge-group-names-test.php
Labels: UI change

#17109 P3-666 Remove ads
  admin/class-admin-init.php
  admin/class-premium-upsell-admin-block.php
  admin/views/sidebar.php
  src/integrations/admin/social-templates-integration.php
Labels: UI change, changelog: enhancement

#16673 Fix for issue 8113
  src/presentations/indexable-post-type-presentation.php
  tests/unit/presentations/indexable-post-type-presentation/open-graph-description-test.php
Labels: community-patch

#17111 P3-668 Improve copy of the moved-homepage-settings alert
  admin/views/tabs/social/facebook.php
Labels: changelog: non-user-facing

#17113 P3-671 Move rewrite titles to separate paper
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/paper-content/general/force-rewrite-title.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
Labels: UI change, changelog: other

#16951 Add support for LiteSpeed web servers
  inc/class-wpseo-utils.php
Labels: community-patch

#17118 P3-674 do not output Twitter tag if OG tag already existing
  src/presentations/indexable-presentation.php
  tests/unit/presentations/indexable-presentation/twitter-description-test.php
  tests/unit/presentations/indexable-presentation/twitter-title-test.php
Labels: changelog: non-user-facing

#17092 Add adjacent relative links for WC shop page
  src/integrations/third-party/woocommerce.php
Labels: changelog: enhancement, community-patch

#17120 P3-676 Improve ImageSelect support for 16:9 images
  packages/components/src/image-select/image-select.css
Labels: UI change, changelog: other

#17119 LINGO-728 Add Norwegian consecutive sentences assessment
  packages/yoastseo/spec/languageProcessing/languages/nb/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/firstWordExceptions.js
Labels: changelog: enhancement

#17122 Add Norwegian transition words assessment
  packages/yoastseo/spec/languageProcessing/languages/nb/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/twoPartTransitionWords.js
Labels: changelog: enhancement

#17123 P3-678 do not prefill form with social templates on Free
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
Labels: changelog: non-user-facing

#17121 Add social settings heading.
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/metas/paper-content/post-type-content.php
  css/src/badge.css
  css/src/search-appearance.css
  css/src/yst_plugin_tools.css
  src/integrations/admin/social-templates-integration.php
  src/presenters/admin/premium-badge-presenter.php
Labels: changelog: non-user-facing

#17067 Clean vendor_prefixed before running composer install
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/shell.js
Labels: changelog: non-user-facing

#17124 Exclude tables from consecutive sentences assessment
  packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/languageProcessing/researches/getSentenceBeginnings.js
Labels: changelog: enhancement

#17110 LINGO-614 Exclude table of contents from analysis
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeTableOfContentsTagSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeTableOfContentsTag.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWords.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
  packages/yoastseo/src/languageProcessing/researches/getSubheadingTextLengths.js
  packages/yoastseo/src/languageProcessing/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/scoring/assessments/readability/textPresenceAssessment.js
Labels: changelog: enhancement

#17127 P3-681 Reset existing Social titles options to the new defaults via upgrade routine
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#17133 P3-681 addendum: Add checks to upgrade routine
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#17131 Expand list of Norwegian function words
  packages/yoastseo/src/languageProcessing/languages/nb/config/functionWords.js
Labels: changelog: enhancement

#17135 P3-685 require Premium 16.5 for social templates
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  src/integrations/admin/social-templates-integration.php
  tests/unit/doubles/admin/formatter/post-metabox-formatter-double.php
  tests/unit/doubles/admin/formatter/term-metabox-formatter-double.php
Labels: changelog: non-user-facing

#17090 Added requiredFor, recommendedFor and optionalFor options to SchemaInstruction.
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/initialize.ts
  packages/schema-blocks/src/functions/presenters/BlockSuggestionsPresenter.tsx
  packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
  packages/schema-blocks/src/instructions/schema/Schema.ts
  packages/schema-blocks/tests/instructions/schema/Schema.test.ts
  src/integrations/schema-blocks.php
Labels: changelog: non-user-facing, component: innovation

#17134 Update yoastseo package readme
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#17140 GST: Change update to Premium alert text
  css/src/search-appearance.css
  src/integrations/admin/social-templates-integration.php
Labels: changelog: non-user-facing

#17136 Adjust content-analysis app configs
  apps/content-analysis/config/paths.js
  apps/content-analysis/config/webpack.config.js
  apps/content-analysis/config/webpackDevServer.config.js
Labels: changelog: non-user-facing

#17076 Use ANSI SQL compliant string quoting chars in MySQL queries
  admin/class-bulk-editor-list-table.php
  admin/filters/class-cornerstone-filter.php
  composer.json
Labels: changelog: bugfix, community-patch

#17104 P2-978 - Feature flags in javascript
  .travis.yml
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  inc/class-wpseo-utils.php
  lib/abstract-main.php
  packages/js/src/analysis/worker.js
  packages/js/src/components/SchemaTab.js
  packages/js/src/containers/SchemaTab.js
  src/conditionals/addon-installation-conditional.php
  src/conditionals/feature-flag-conditional.php
  src/conditionals/schema-blocks-conditional.php
  src/integrations/feature-flag-integration.php
  tests/integration/test-class-wpseo-utils.php
  tests/unit/integrations/feature-flag-integration-test.php
Labels: changelog: non-user-facing

#17141 Add Norwegian passive voice assessment
  packages/yoastseo/spec/languageProcessing/languages/nb/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/getClausesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nb/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/nb/values/ClauseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getPassiveVoiceResult/getPassiveVoiceResultNorwegianSpec.js
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/internal/participles.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/languageProcessing/languages/nb/config/stopWords.js
  packages/yoastseo/src/languageProcessing/languages/nb/helpers/getClauses.js
  packages/yoastseo/src/languageProcessing/languages/nb/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/nb/values/Clause.js
  packages/yoastseo/src/languageProcessing/researches/getPassiveVoiceResult.js
Labels: changelog: enhancement

#17137 Fix breadcrumb name attribute
  src/generators/schema/breadcrumb.php
  tests/unit/generators/schema/breadcrumb-test.php
Labels: changelog: enhancement

#17148 Updated Travis build config, in the hope that the 5.6 build will work…
  .travis.yml
Labels: changelog: non-user-facing

#17130 P2 755 check premium license on seo opt
  packages/js/src/components/Indexation.js
  src/integrations/admin/indexing-notification-integration.php
  src/integrations/admin/indexing-tool-integration.php
  src/presenters/admin/indexing-failed-notification-presenter.php
  tests/unit/helpers/language-helper-test.php
  tests/unit/integrations/admin/indexing-notification-integration-test.php
  tests/unit/integrations/admin/indexing-tool-integration-test.php
  tests/unit/presenters/admin/indexing-failed-notification-presenter-test.php
Labels: UI change, changelog: bugfix, component: innovation

#17150 P3-696 Optimize loading of Social Templates Integration
  src/integrations/admin/social-templates-integration.php
Labels: changelog: non-user-facing

#17128 Add norwegian full text test
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper1.html
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper2.html
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper3.html
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper3.js
Labels: changelog: non-user-facing

#17153 Fix PRODUCT-339
  src/generators/schema/website.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/website-test.php
Labels: changelog: enhancement

#17129 P2-1023 - Schema blocks misaligned
  packages/schema-blocks/src/instructions/blocks/ClassName.ts
  packages/schema-blocks/tests/instructions/blocks/ClassName.test.ts
Labels: changelog: bugfix, component: innovation

#17165 Add methods to indexable repository for the workouts integration
  src/repositories/indexable-repository.php
Labels: changelog: non-user-facing

#17164 Rename to avoid conflict with the global var
  admin/pages/dashboard.php
  admin/pages/metas.php
  admin/pages/network.php
  admin/pages/social.php
Labels: changelog: non-user-facing

#17163 Fixes the metabox for classic editor when schema blocks are active
  packages/js/src/components/SchemaTab.js
  packages/js/src/containers/SchemaTab.js
  packages/schema-blocks/package.json
  packages/schema-blocks/src/functions/initialize.tsx
  packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
  yarn.lock
Labels: changelog: non-user-facing, component: innovation

#17170 Retry wordpress-seo/pull/17169
  admin/capabilities/class-register-capabilities.php
Labels: changelog: bugfix, community-patch

#17155 P2-816 remove redundantblocks validation
  packages/schema-blocks/src/core/validation/BlockValidation.ts
  packages/schema-blocks/src/core/validation/RequiredBlock.ts
  packages/schema-blocks/src/core/validation/RequiredBlockOption.ts
  packages/schema-blocks/src/core/validation/index.ts
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
  packages/schema-blocks/src/functions/validators/innerBlocksValid.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
  packages/schema-blocks/tests/functions/process.test.ts
  packages/schema-blocks/tests/functions/validators/innerBlocksValid.test.ts
Labels: changelog: non-user-facing, component: innovation

#17161 Fix breadcrumb for static posts page
  src/generators/schema/breadcrumb.php
  tests/unit/generators/schema/breadcrumb-test.php
Labels: changelog: bugfix

#17177 Remove abstract schema piece type hint from Schema_Generator::type_filter.
  src/generators/schema-generator.php
Labels: changelog: non-user-facing

#17167 Implement feature flag for Slovak support
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
  src/conditionals/slovak-support-conditional.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#17179 Global badge styling
  admin/class-admin-asset-manager.php
  css/src/admin-global.css
  css/src/badge.css
  src/presenters/admin/badge-presenter.php
  src/presenters/admin/premium-badge-presenter.php
Labels: changelog: non-user-facing

#17157 P2-1042 A few small renames regarding JobPosting
  packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
  packages/schema-blocks/src/functions/presenters/SidebarWarningPresenter.ts
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
  packages/schema-blocks/tests/functions/presenters/SidebarWarningPresenter.test.ts
Labels: changelog: non-user-facing, component: innovation

#17182 Rename the Job closing date block to Job application closing date
  packages/schema-blocks/src/functions/redux/selectors/schemaBlocks.ts
Labels: changelog: non-user-facing, component: innovation

#17149 Add Researcher and language folders for Slovak
  packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
  packages/yoastseo/spec/specHelpers/getResearcher.js
  packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
  src/config/researcher-languages.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#17186 Improve documentation for the 'wpseo_schema_{identifier/type}' filter
  src/generators/schema-generator.php
Labels: changelog: non-user-facing

#17183 Add stripHTMLtags helper to languageProcessing index
  packages/yoastseo/src/languageProcessing/index.js
Labels: changelog: non-user-facing

#17188 QAK-2961 Workouts improvements
  config/dependency-injection/services.php
  css/src/admin-global.css
  packages/js/src/components/CollapsibleCornerstone.js
  src/repositories/indexable-repository.php
  src/wordpress/wrapper.php
Labels: changelog: non-user-facing

#17189 [QAK-2956] Allow the admin menu to display submenus with different capabilities
  admin/menu/class-admin-menu.php
  admin/menu/class-base-menu.php
Labels: UI change, changelog: non-user-facing

#17143 Move url helpers
  inc/class-wpseo-utils.php
  src/helpers/url-helper.php
  tests/unit/admin/admin-features-test.php
Labels: changelog: non-user-facing

#17185 When creating unindexed indexables ensure that they have a permalink
  composer.json
  src/generators/schema-generator.php
  src/models/indexable.php
  src/repositories/indexable-repository.php
  tests/unit/models/indexable-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: bugfix

#17194 Add custom css for premium badges in admin / adminbar menu
  src/integrations/admin/menu-badge-integration.php
Labels: changelog: non-user-facing

#17168 Replace deprecated filter `block_categories` by `block_categories_all`
  src/helpers/wordpress-helper.php
  src/integrations/blocks/block-categories.php
  src/surfaces/helpers-surface.php
  tests/unit/helpers/wordpress-helper-test.php
Labels: changelog: non-user-facing

#17196 Changed get_feature_flag method from public to protected again.
  src/conditionals/addon-installation-conditional.php
  src/conditionals/feature-flag-conditional.php
  src/conditionals/schema-blocks-conditional.php
  src/integrations/feature-flag-integration.php
  tests/unit/integrations/feature-flag-integration-test.php
Labels: changelog: non-user-facing

#17195 Add algolia setting and premium badge for integrations
  admin/class-admin-init.php
  admin/views/class-yoast-feature-toggle.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/class-yoast-integration-toggles.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/dashboard/integrations.php
  css/src/admin-global.css
  inc/options/class-wpseo-option-wpseo.php
  tests/unit/admin/views/feature-toggles-test.php
  tests/unit/admin/views/integration-toggles-test.php
Labels: UI change, changelog: non-user-facing

#17142 P2 221 recipe instructions block
  packages/schema-blocks/src/instructions/schema/RecipeInstructions.ts
  packages/schema-blocks/src/instructions/schema/index.ts
  src/schema-templates/assets/icons.php
  src/schema-templates/ingredients.block.php
  src/schema-templates/recipe-description.block.php
  src/schema-templates/recipe-ingredients.block.php
  src/schema-templates/recipe-ingredients.schema.php
  src/schema-templates/recipe-instructions.block.php
  src/schema-templates/recipe-instructions.schema.php
  src/schema-templates/recipe.block.php
  src/schema-templates/recipe.schema.php
  src/schema-templates/step.block.php
  src/schema-templates/step.schema.php
  src/schema-templates/steps.block.php
  src/schema-templates/steps.schema.php
  tests/unit/dependency-injection/schema-templates-loader-test.php
Labels: changelog: enhancement

#17162 P2 925 expand yoast head with json
  composer.json
  src/actions/indexables/indexable-head-action.php
  src/deprecated/src/presenters/open-graph/fb-app-id-presenter.php
  src/presenters/abstract-indexable-presenter.php
  src/presenters/abstract-indexable-tag-presenter.php
  src/presenters/canonical-presenter.php
  src/presenters/meta-description-presenter.php
  src/presenters/open-graph/article-author-presenter.php
  src/presenters/open-graph/article-modified-time-presenter.php
  src/presenters/open-graph/article-published-time-presenter.php
  src/presenters/open-graph/article-publisher-presenter.php
  src/presenters/open-graph/description-presenter.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/open-graph/locale-presenter.php
  src/presenters/open-graph/site-name-presenter.php
  src/presenters/open-graph/title-presenter.php
  src/presenters/open-graph/type-presenter.php
  src/presenters/open-graph/url-presenter.php
  src/presenters/rel-next-presenter.php
  src/presenters/rel-prev-presenter.php
  src/presenters/robots-presenter.php
  src/presenters/schema-presenter.php
  src/presenters/slack/enhanced-data-presenter.php
  src/presenters/title-presenter.php
  src/presenters/twitter/card-presenter.php
  src/presenters/twitter/creator-presenter.php
  src/presenters/twitter/description-presenter.php
  src/presenters/twitter/image-presenter.php
  src/presenters/twitter/site-presenter.php
  src/presenters/twitter/title-presenter.php
  src/presenters/webmaster/baidu-presenter.php
  src/presenters/webmaster/bing-presenter.php
  src/presenters/webmaster/google-presenter.php
  src/presenters/webmaster/pinterest-presenter.php
  src/presenters/webmaster/yandex-presenter.php
  src/routes/yoast-head-rest-field.php
  src/surfaces/values/meta.php
  tests/unit/actions/indexables/indexable-head-action-test.php
  tests/unit/admin/admin-asset-analysis-worker-location-test.php
  tests/unit/admin/metabox/metabox-editor-test.php
  tests/unit/integrations/front-end/wp-robots-integration-test.php
  tests/unit/integrations/watchers/indexable-post-meta-watcher-test.php
  tests/unit/presenters/canonical-presenter-test.php
  tests/unit/presenters/webmaster/baidu-presenter-test.php
  tests/unit/presenters/webmaster/bing-presenter-test.php
  tests/unit/presenters/webmaster/google-presenter-test.php
  tests/unit/presenters/webmaster/pinterest-presenter-test.php
  tests/unit/presenters/webmaster/yandex-presenter-test.php
  tests/unit/routes/yoast-head-rest-field-test.php
Labels: changelog: enhancement

#17200 Make sure the schema blocks analysis is rendered in both the metabox and the sidebar
  packages/js/src/components/SchemaTab.js
  packages/schema-blocks/src/functions/initialize.tsx
Labels: changelog: non-user-facing

#17193 Add Slovak stemmer
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/getStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/stemmerCoverage/calculateCoverage.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/stemmerCoverage/generateStems.js
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/languages/sk/helpers/internal/stemmerCoverage/sampleVocabulary.json
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sk/helpers/getStemmer.js
  packages/yoastseo/src/languageProcessing/languages/sk/helpers/internal/stem.js
  src/config/researcher-languages.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: enhancement

#17202 Add Slovak transition words
  packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/twoPartTransitionWords.js
Labels: changelog: enhancement

#17207 Dont throw exception when no key is provided in abstract indexable tag presenter
  src/presenters/abstract-indexable-presenter.php
  src/presenters/abstract-indexable-tag-presenter.php
  src/surfaces/values/meta.php
Labels: changelog: non-user-facing

#17199 Add Slovak function words
  packages/yoastseo/spec/languageProcessing/languages/sk/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/sk/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sk/config/functionWords.js
Labels: changelog: enhancement
