Repository Yoast/wordpress-seo, pull requests merged in 2021-12, with the labels that each got.

#17744 Only show First-time configuration notice to first-install users
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/workouts-integration.php
  src/routes/workouts-route.php
  wp-seo-main.php
Labels: changelog: bugfix

#17743 Also update auto_update settings when a new addon is installed.
  inc/class-addon-manager.php
  inc/class-upgrade.php
  src/integrations/watchers/addon-update-watcher.php
  tests/unit/doubles/inc/addon-manager-double.php
  tests/unit/inc/addon-manager-test.php
Labels: changelog: bugfix

#17722 Wincher: ensure that collect_all_keyphrases does not collect from taxonomies
  src/actions/wincher/wincher-keyphrases-action.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
Labels: community-patch

#17747 Sketch initial classic editor setup
  admin/class-admin-asset-manager.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/package.json
  packages/js/src/classic-editor.js
  packages/js/src/watchers/classicEditorWatcher.js
  yarn.lock
Labels: innovation, changelog: non-user-facing

#17719 update Social previews to adapt recent changes
  apps/components/FacebookPreviewExample.js
  packages/js/src/components/social/FacebookWrapper.js
  packages/js/src/containers/FacebookEditor.js
  packages/js/src/containers/TwitterEditor.js
  packages/js/src/elementor/containers/FacebookEditor.js
  packages/js/src/elementor/containers/TwitterEditor.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/helpers/createCustomEvent.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/initializers/metabox-tabs.js
  packages/js/src/redux/selectors/settings.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
  packages/social-metadata-previews/src/facebook/FacebookAuthorName.js
  packages/social-metadata-previews/src/facebook/FacebookDescription.js
  packages/social-metadata-previews/src/facebook/FacebookPreview.js
  packages/social-metadata-previews/src/facebook/FacebookSiteAndAuthorNames.js
  packages/social-metadata-previews/src/facebook/FacebookSiteUrl.js
  packages/social-metadata-previews/src/facebook/FacebookTitle.js
  packages/social-metadata-previews/src/helpers/determineImageProperties.js
  packages/social-metadata-previews/src/twitter/TwitterDescription.js
  packages/social-metadata-previews/src/twitter/TwitterPreview.js
  packages/social-metadata-previews/src/twitter/TwitterSiteUrl.js
  packages/social-metadata-previews/src/twitter/TwitterTextWrapper.js
  packages/social-metadata-previews/src/twitter/TwitterTitle.js
  packages/social-metadata-previews/tests/facebook/FacebookSiteAndAuthorNamesTest.js
  packages/social-metadata-previews/tests/helpers/determineImagePropertiesTest.js
Labels: UI change, changelog: enhancement

#17739 Create analyze initialize function
  apps/seo-integration/public/dist/analysis/analysis.js
  apps/seo-integration/public/dist/analysis/languages/default.js
  apps/seo-integration/public/dist/bootstrap-analysis.js
  apps/seo-integration/public/dist/vendor/autop.js
  apps/seo-integration/public/dist/vendor/lodash.js
  apps/seo-integration/public/dist/yoast/featureFlag.js
  apps/seo-integration/public/dist/yoast/jed.js
  apps/seo-integration/src/index.js
  packages/seo-integration/src/analysis-result-containers/transformers.js
  packages/seo-integration/src/analysis.js
  packages/seo-integration/src/analyze.js
  packages/seo-integration/src/index.js
  packages/seo-store/src/analysis/slice/results.js
  packages/seo-store/src/index.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
  packages/yoastseo/src/worker/bootstrapAnalysis.js
  packages/yoastseo/webpack/externals/externals.js
Labels: innovation, changelog: non-user-facing

#17748 Bump plugin-grunt-tasks to 2.2.1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#17735 Fix highlighting words functionality in Japanese
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
  packages/yoastseo/src/languageProcessing/researches/keyphraseDistribution.js
Labels: changelog: non-user-facing

#17749 DUPP-124 small styling fixes workouts
  css/src/workouts.css
Labels: changelog: non-user-facing

#17753 Persist indexation state when moving back and forth between workouts
  packages/js/src/workouts/components/ConfigurationWorkout.js
Labels: changelog: bugfix

#17752 Adapt sentence length assessment for Japanese
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ca/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/es/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/fa/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/he/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/it/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/sentenceLength.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
Labels: changelog: non-user-facing

#17755 Wincher: do not include trashed posts when using "Add existing keyphrases"
  src/actions/wincher/wincher-keyphrases-action.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
  wp-seo-main.php
Labels: community-patch, changelog: non-user-facing

#17760 Allow passing of id to card and add more ids to its contents
  packages/js/src/workouts/components/ConfigurationWorkoutCard.js
  packages/js/src/workouts/components/CornerstoneWorkoutCard.js
  packages/js/src/workouts/components/OrphanedWorkoutCard.js
  packages/js/src/workouts/components/WorkoutCard.js
Labels: changelog: non-user-facing

#17736 Adjust applicability of assessments for Japanese
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TransitionWordsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/assessmentApplicabilityCharacterCount.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
Labels: changelog: non-user-facing

#17767 DUPP-136 installation success integration
  inc/options/class-wpseo-option-wpseo.php
  src/conditionals/installation-success-conditional.php
  src/integrations/admin/installation-success-integration.php
  src/integrations/admin/workouts-integration.php
  tests/unit/integrations/admin/installation-success-integration-test.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#17762 Adapt keyphrase length research for Japanese
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getKeyphraseLengthSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getKeyphraseLength.js
Labels: changelog: non-user-facing

#17775 Composer: update dev dependencies + installer package
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: other

#17776 DUPP-138 add cards
  admin/class-admin-asset-manager.php
  config/webpack/paths.js
  css/src/installation-success.css
  images/man_with_tablet.png
  packages/js/src/installation-success.js
  src/integrations/admin/installation-success-integration.php
Labels: changelog: non-user-facing

#17769 QA-2602 Wincher: remove extra dot from limit reached message
  admin/views/tabs/metas/paper-content/integrations/wincher.php
Labels: community-patch, changelog: non-user-facing

#17740 P1-479 Upgrade draft-js and plugins
  css/src/metabox.css
  css/src/search-appearance.css
  packages/js/package.json
  packages/replacement-variable-editor/package.json
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
  packages/replacement-variable-editor/src/helpers/positionSuggestions.js
  packages/replacement-variable-editor/tests/positionSuggestionsTest.js
  yarn.lock
Labels: changelog: non-user-facing

#17742 Adapt paragraph length assessment for Japanese
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/paragraphLength.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: non-user-facing

#17785 DUPP-145 Revert conf. workout prerequisite
  packages/js/src/workouts/components/CornerstoneWorkoutCard.js
  packages/js/src/workouts/components/OrphanedWorkoutCard.js
Labels: changelog: non-user-facing

#17745 Adapt text length assessment for Japanese
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/textLengthSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/textLength.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/textLength.js
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
  packages/yoastseo/src/scoring/assessor.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/collectionPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
  packages/yoastseo/src/scoring/relatedKeywordTaxonomyAssessor.js
  packages/yoastseo/src/scoring/taxonomyAssessor.js
Labels: changelog: non-user-facing

#17781 Disable keyword in slug assessment for Japanese
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/UrlKeywordAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
Labels: changelog: non-user-facing

#17791 Dupp 148 add wincher feature flag
  admin/class-yoast-dashboard-widget.php
  admin/views/class-yoast-integration-toggles.php
  admin/views/tabs/metas/paper-content/integrations/wincher.php
  packages/js/src/components/WincherSEOPerformanceModal.js
  src/conditionals/wincher-conditional.php
  src/integrations/third-party/wincher-publish.php
  tests/unit/admin/views/integration-toggles-test.php
  tests/unit/integrations/third-party/wincher-publish-test.php
Labels: changelog: non-user-facing

#17786 P1-1091 - Setup the analysis worker
  apps/seo-integration/src/index.js
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/analysis.js
  packages/js/src/classic-editor/components/index.js
  packages/js/src/classic-editor/helpers/index.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/src/classic-editor/replacement-variables.js
  packages/js/src/classic-editor/watcher.js
  packages/js/tests/classic-editor/analysis.test.js
  packages/seo-integration/src/analysis.js
  packages/seo-integration/src/index.js
Labels: changelog: non-user-facing

#17795 WPSEO_Admin_Gutenberg_Compatibility_Notification_Test: minor fixes/simplification
  tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17796 HTML_Helper_Test: improve tests
  tests/unit/helpers/schema/html-helper-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17797 Date_Helper_Test: improve tests
  tests/unit/helpers/date-helper-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17798 Meta_Surface_Test::for_url_provider(): use named data sets
  tests/unit/surfaces/meta-surface-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17799 WPSEO_Sitemap_Provider_Overlap_Test: stabilize the tests
  tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
Labels: yoast cs/qa, changelog: non-user-facing

#17789 Add skip link to free installation success page
  css/src/installation-success.css
  packages/js/src/installation-success.js
Labels: changelog: non-user-facing

#17803 WPSEO_Sitemaps_Cache_Data_Test: improve tests
  tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-data.php
Labels: yoast cs/qa, changelog: non-user-facing

#17792 Change font size alerts from 14px to 13px
  css/src/alerts.css
  packages/components/src/Alert.js
  packages/components/tests/__snapshots__/AlertTest.js.snap
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
Labels: changelog: other

#17810 Fix wincher feature flag
  admin/formatter/class-metabox-formatter.php
  packages/js/src/initializers/block-editor-integration.js
Labels: changelog: non-user-facing

#17813 Tests: fix some incorrect `@covers` tags
  tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17801 P1-1097 Setup metabox with components
  .eslintrc
  packages/js/package.json
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/components/focus-keyphrase-input.js
  packages/js/src/classic-editor/components/index.js
  packages/js/src/classic-editor/components/metabox/index.js
  packages/js/src/classic-editor/components/metabox/slot-fill.js
  packages/js/src/classic-editor/components/readability-analysis.js
  packages/js/src/classic-editor/components/seo-analysis.js
  packages/js/src/classic-editor/editor-store.js
  packages/js/src/components/contentAnalysis/KeywordInput.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/portals/ReadabilityResultsPortal.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/helpers/reactRoot.js
  packages/js/src/helpers/register-global-apis.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/redux/selectors/preferences.js
  packages/js/tests/components/SEMrushRelatedKeyphrasesModal.test.js
  packages/js/tests/redux/controls/dismissedAlerts.test.js
  packages/seo-store/src/analysis/tests.js
  yarn.lock
Labels: innovation, changelog: non-user-facing

#17778 DUPP-139 add stepper and title
  css/src/installation-success.css
  packages/js/src/installation-success.js
Labels: changelog: non-user-facing

#17814 Add localization to the workouts page
  src/integrations/admin/workouts-integration.php
Labels: changelog: bugfix

#17788 Add blog posting type
  src/config/schema-types.php
Labels: changelog: enhancement

#17709 IM-1614 Fix incoming link count of 0
  src/repositories/seo-links-repository.php
Labels: community-patch, changelog: bugfix

#17730 17727 Fix `og:image:type` meta output.
  src/presenters/open-graph/image-presenter.php
Labels: community-patch, changelog: bugfix

#17821 Fix readability analysis for terms
  packages/js/src/analysis/refreshAnalysis.js
Labels: changelog: non-user-facing

#17819 DUPP-137 install success bulk action
  src/integrations/admin/installation-success-integration.php
  tests/unit/integrations/admin/installation-success-integration-test.php
Labels: changelog: non-user-facing

#17800 Don't redirect to free success page when also activating Premium
  src/integrations/admin/installation-success-integration.php
  tests/unit/integrations/admin/installation-success-integration-test.php
Labels: changelog: non-user-facing

#17823 Only allow admins to use the deactivating plugins endpoint
  src/routes/importing-route.php
Labels: changelog: non-user-facing

#17824 DUPP-135 Prevent installation success to be displayed when activating with WP CLI
  wp-seo-main.php
Labels: changelog: non-user-facing

#17802 Get editor data from the classic editor to use as the initial state o…
  .eslintrc
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/components/focus-keyphrase-input.js
  packages/js/src/classic-editor/components/metabox/index.js
  packages/js/src/classic-editor/components/readability-analysis.js
  packages/js/src/classic-editor/components/seo-analysis.js
  packages/js/src/classic-editor/dom.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/src/redux/reducers/editorData.js
  packages/seo-integration/src/index.js
Labels: changelog: non-user-facing

#17816 Adapt Keyphrase in title assessment for Japanese
  packages/yoastseo/spec/languageProcessing/helpers/match/findKeywordFormsInStringSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/match/matchTextWithArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/match/matchTextWithWordSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/match/processExactMatchRequestSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/findExactMatchMultiWordKeyphraseInTitleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TitleKeywordAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/match/findKeywordFormsInString.js
  packages/yoastseo/src/languageProcessing/helpers/match/matchTextWithArray.js
  packages/yoastseo/src/languageProcessing/helpers/match/matchTextWithWord.js
  packages/yoastseo/src/languageProcessing/helpers/match/processExactMatchRequest.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/findExactMatchMultiWordKeyphraseInTitle.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/scoring/assessments/seo/TitleKeywordAssessment.js
Labels: changelog: non-user-facing

#17700 Implement importing posttype defaults settings from AIOSEO in chunks
  src/actions/importing/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo-custom-archive-settings-importing-action.php
  src/actions/importing/aioseo-default-archive-settings-importing-action.php
  src/actions/importing/aioseo-general-settings-importing-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  src/actions/importing/aioseo-posttype-defaults-settings-importing-action.php
  src/actions/importing/aioseo-taxonomy-settings-importing-action.php
  src/actions/importing/import-cursor-manager-trait.php
  tests/unit/actions/importing/abstract-aioseo-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/doubles/actions/importing/abstract-aioseo-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-custom-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-default-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-general-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-posttype-defaults-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-taxonomy-settings-importing-action-double.php
Labels: changelog: non-user-facing

#17829 DUPP-144 Improve style of the installation success page on mobile screens
  css/src/installation-success.css
  packages/js/src/installation-success.js
Labels: changelog: non-user-facing

#17832 DUPP-167 Deal with showing installation success for network activation of the plugin
  src/integrations/admin/installation-success-integration.php
  tests/unit/integrations/admin/installation-success-integration-test.php
Labels: changelog: non-user-facing

#17608 Replace 'words' with 'characters' in the Japanese feedback strings for certain assessments
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
Labels: changelog: non-user-facing

#17833 DUPP-164 Use `capability` instead of deprecated `who` param in WP 5.9
  admin/class-admin.php
  inc/sitemaps/class-author-sitemap-provider.php
Labels: changelog: bugfix

#17818 P1-1115 Setup cornerstone component
  packages/js/src/classic-editor/components/advanced-settings.js
  packages/js/src/classic-editor/components/cornerstone-content.js
  packages/js/src/classic-editor/components/google-preview.js
  packages/js/src/classic-editor/components/metabox/index.js
Labels: innovation, changelog: non-user-facing

#17807 QA-2601 Wincher: Fatal error on routes if no token is present
  src/actions/wincher/wincher-account-action.php
  src/routes/wincher-route.php
Labels: community-patch, changelog: non-user-facing

#17837 Fix 8.1 compatibility: Table yoast_wp_seo_models_indexable doesn't exist
  lib/model.php
Labels: changelog: bugfix

#17817 QA-2612 Disallow contributors from using the Wincher integration
  admin/class-yoast-dashboard-widget.php
  admin/formatter/class-metabox-formatter.php
  src/helpers/wincher-helper.php
  src/routes/wincher-route.php
Labels: community-patch, changelog: non-user-facing

#17826 Schema sameAs URLs should be unique
  src/generators/schema/organization.php
  src/generators/schema/person.php
  tests/unit/generators/schema/organization-test.php
  tests/unit/generators/schema/person-test.php
Labels: changelog: enhancement

#17779 Adapt meta description keyword research for Japanese
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/languageProcessing/researches/metaDescriptionKeyword.js
Labels: changelog: non-user-facing

#17806 QA-2609 Wincher: Fix React warnings in the dashboard widget
  packages/js/src/components/WincherPerformanceReport.js
  packages/js/src/dashboard-widget.js
Labels: community-patch, changelog: non-user-facing

#17805 QA-2610 Wincher: Use horizontal scroll for table on mobile
  packages/components/src/Toggle.js
  packages/js/src/components/WincherKeyphrasesTable.js
  packages/js/src/components/WincherPerformanceReport.js
Labels: community-patch, changelog: non-user-facing

#17836 Remove unused images
  images/seo_fitness_assistants_fit.svg
  images/seo_fitness_assistants_unfit.svg
Labels: changelog: non-user-facing

#17848 DUPP-175 Revert the removal of WPSEO_Frontend
  composer.json
  config/dependency-injection/services.php
  src/deprecated/frontend/frontend.php
Labels: changelog: other

#17839 P1-1095 shortcode plugin
  packages/js/package.json
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/shortcodes.js
  packages/seo-integration/package.json
  yarn.lock
Labels: innovation, changelog: non-user-facing

#17849 Update readme for Japanese support
  packages/yoastseo/README.md
Labels: changelog: non-user-facing

#17787 Transform AIOSEO data before saving the Yoast indexable
  src/actions/importing/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo-custom-archive-settings-importing-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  src/actions/importing/aioseo-taxonomy-settings-importing-action.php
  src/services/importing/aioseo-replacevar-handler.php
  tests/unit/actions/importing/abstract-aioseo-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/doubles/actions/importing/abstract-aioseo-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-custom-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-default-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-general-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-posttype-defaults-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-taxonomy-settings-importing-action-double.php
  tests/unit/services/importing/aioseo-replacevar-handler-test.php
  tests/unit/services/importing/importable-detector-test.php
  tests/unit/services/importing/importer-action-filter-trait-test.php
Labels: changelog: non-user-facing

#17790 Adapt keyphrase length assessment for Japanese
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/de/config/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/keyphraseLength.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
Labels: changelog: non-user-facing

#17844 DUPP-172 Fix installation success integration tests
  tests/unit/integrations/admin/installation-success-integration-test.php
Labels: changelog: non-user-facing

#17780 WP 5.9 | `WPSEO_Author_Sitemap_Provider`: use user capability queries
  admin/class-admin.php
  inc/sitemaps/class-author-sitemap-provider.php
Labels: component: xml sitemap, yoast cs/qa, changelog: non-user-facing

#17835 QA-2616 Wincher: add explanation to table on the Dashboard
  packages/js/src/components/WincherPerformanceReport.js
Labels: community-patch

#17771 QA-2596 Fix loading of slugs for drafts in Elementor
  src/integrations/third-party/elementor.php
Labels: community-patch, changelog: non-user-facing

#17860 Decrease max-width of description workouts overview for mobile screens
  css/src/workouts.css
Labels: changelog: enhancement

#17834 QA-2598 QA-2617 Wincher: improve toggle stability
  packages/js/package.json
  packages/js/src/components/WincherKeyphrasesTable.js
  packages/js/src/components/WincherPostPublish.js
  packages/js/src/components/WincherSEOPerformance.js
  packages/js/src/components/WincherTableRow.js
  packages/js/src/containers/WincherKeyphrasesTable.js
  packages/js/src/containers/WincherPostPublish.js
  packages/js/src/helpers/wincherEndpoints.js
  packages/js/src/redux/actions/WincherRequest.js
  packages/js/src/redux/reducers/WincherRequest.js
  src/routes/wincher-route.php
  tests/unit/routes/wincher-route-test.php
Labels: community-patch

#17830 Adapt get link statistics research for Japanese
  packages/yoastseo/spec/languageProcessing/helpers/match/findKeywordInUrlSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getLinkStatisticsSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TitleKeywordAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/match/findKeywordInUrl.js
  packages/yoastseo/src/languageProcessing/helpers/match/processExactMatchRequest.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/researches/getLinkStatistics.js
Labels: changelog: bugfix, changelog: non-user-facing

#17831 Adapt keyphrase density assessment for Japanese
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getKeywordDensitySpec.js
  packages/yoastseo/spec/languageProcessing/researches/getKeywordDensitySpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/researches/getKeywordDensity.js
  packages/yoastseo/src/languageProcessing/researches/keywordCount.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/helpers/assessments/recommendedKeywordCount.js
Labels: changelog: non-user-facing

#17863 Cleaned up spec descriptions for assessing text and paragraph length
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
Labels: changelog: non-user-facing

#17865 Fix failing Wincher JS tests
  packages/js/tests/components/WincherKeyphrasesTable.test.js
Labels: community-patch, changelog: non-user-facing

#17808 QA-2606 Disable Wincher integration for multisite environments
  src/conditionals/wincher-conditional.php
Labels: community-patch

#17815 Adapt subheading distribution assessment
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/specHelpers/factory.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/subheadingsTooLong.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js
Labels: changelog: non-user-facing

#17537 PHP 8.1: fix "missing return type" deprecation warnings
  lib/model.php
  lib/orm.php
Labels: yoast cs/qa, changelog: enhancement

#17784 PHP 8.1 | WPSEO_Sitemap_Cache_Data: implement magic serialization methods
  inc/sitemaps/class-sitemap-cache-data.php
  inc/sitemaps/class-sitemaps-cache.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-data.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-cache.php
Labels: component: xml sitemap, yoast cs/qa, changelog: enhancement

#17811 PHP 8.1 | Tests: fix two incomplete mocks
  tests/unit/actions/addon-installation/addon-activate-action-test.php
  tests/unit/actions/addon-installation/addon-install-action-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17812 PHP 8.1 | WPSEO_Admin_Gutenberg_Compatibility_Notification: fix null to non-nullable notice
  admin/class-gutenberg-compatibility.php
Labels: component: gutenberg, yoast cs/qa, changelog: other

#17854 PHP 8.1 | Meta_Surface::is_date_archive_url(): prevent null to non-nullable deprecation notice
  src/surfaces/meta-surface.php
  tests/unit/surfaces/meta-surface-test.php
Labels: yoast cs/qa, changelog: other

#17852 PHP 8.1 | HTML_Helper: add input validation
  src/helpers/schema/html-helper.php
  tests/unit/doubles/stringable-object-mock.php
  tests/unit/helpers/schema/html-helper-test.php
Labels: yoast cs/qa, changelog: other

#17858 PHP 8.1 | Schema_Generator::get_type_from_piece(): prevent null to non-nullable deprecation notice
  src/generators/schema-generator.php
Labels: yoast cs/qa, changelog: other

#17857 PHP 8.1 | Current_Page_Helper::is_yoast_seo_page() prevent null to non-nullable deprecation notice
  src/helpers/current-page-helper.php
Labels: yoast cs/qa, changelog: other

#17856 PHP 8.1 | Indexable::save() prevent null to non-nullable deprecation notice + multi-byte language fix
  src/models/indexable.php
  tests/unit/models/indexable-test.php
Labels: yoast cs/qa, changelog: other

#17853 PHP 8.1 | Date_Helper: add input validation (x2)
  src/helpers/date-helper.php
  tests/unit/helpers/date-helper-test.php
Labels: yoast cs/qa, changelog: other

#17870 Remove Japanese feature flag
  inc/class-wpseo-replace-vars.php
  packages/js/src/helpers/replacementVariableHelpers.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper2.js
  packages/yoastseo/spec/languageProcessing/helpers/prominentWords/determineProminentWordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getKeyphraseLengthSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/customGetStemmerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/getContentWordsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/getWordsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/internal/createWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/internal/determineStemSpec.js
  packages/yoastseo/spec/languageProcessing/researches/countSentencesFromTextSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/spec/languageProcessing/researches/functionWordsInKeyphraseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getKeywordDensitySpec.js
  packages/yoastseo/spec/languageProcessing/researches/getLinkStatisticsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInsightsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
  packages/yoastseo/spec/languageProcessing/researches/readingTimeSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TitleKeywordAssessmentSpec.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizerJapanese.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/researches/readingTime.js
  src/config/researcher-languages.php
  src/deprecated/src/conditionals/japanese-support-conditional.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: enhancement

#17871 Pass tracking params to shortlinks configuration workout
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/NewsletterSignup.js
  src/integrations/admin/configuration-workout-integration.php
Labels: changelog: non-user-facing

#17873 PHP 8.1: fix deprecation warning / http_build_query()
  inc/sitemaps/class-sitemaps-renderer.php
Labels: yoast cs/qa, changelog: other

#17872 Change the Wincher feature flag into a regular conditional based on a new Non_Multisite conditional
  admin/class-yoast-dashboard-widget.php
  admin/formatter/class-metabox-formatter.php
  admin/views/class-yoast-integration-toggles.php
  admin/views/tabs/metas/paper-content/integrations/wincher.php
  packages/js/src/components/WincherSEOPerformanceModal.js
  src/actions/wincher/wincher-account-action.php
  src/conditionals/non-multisite-conditional.php
  src/conditionals/wincher-conditional.php
  src/helpers/wincher-helper.php
  src/integrations/third-party/wincher.php
  tests/unit/admin/views/integration-toggles-test.php
  tests/unit/conditionals/non-multisite-conditional-test.php
  tests/unit/conditionals/wincher-conditional-test.php
  tests/unit/integrations/third-party/wincher-publish-test.php
  tests/unit/integrations/third-party/wincher-test.php
Labels: changelog: enhancement

#17850 Dupp 174 remove config wizard refs
  admin/class-schema-person-upgrade-notification.php
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/copy.js
  config/grunt/task-config/extract-extra-pr-texts-from-yoast-cli-md.js
  config/grunt/task-config/shell.js
  config/grunt/task-config/update-package-changelog.js
Labels: changelog: non-user-facing

#17876 Add JSON_UNESCAPED_UNICODE flag for schema output
  inc/class-wpseo-utils.php
Labels: component: schema (JSON+LD), changelog: enhancement

#17838 Import showMetaBox setting when importing posttype settings
  src/actions/importing/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo-posttype-defaults-settings-importing-action.php
Labels: changelog: non-user-facing

#17878 DUPP-185 fix translations in the installation success page
  css/src/installation-success.css
  src/integrations/admin/installation-success-integration.php
Labels: changelog: non-user-facing

#17880 Remove version from JS file names and add it as a file hash in the ve…
  .travis.yml
  admin/class-admin-asset-manager.php
  config/webpack/webpack.config.js
Labels: changelog: non-user-facing

#17884 QA-2712 Wincher: fix keyphrase limit message not being shown
  packages/js/src/components/WincherKeyphrasesTable.js
  src/actions/wincher/wincher-keyphrases-action.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
Labels: community-patch, changelog: non-user-facing

#17879 Allow all blur events except media library clicks to close editormodals
  packages/js/src/components/modals/editorModals/EditorModal.js
Labels: changelog: bugfix

#17887 [QA-2720] Fix loading JS on workouts pages
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing

#17883 Remove spaces before processing keyphrase in Japanese
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/functionWordsInKeyphraseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getWordForms.js
Labels: changelog: non-user-facing

#17888 QA-2713 Wincher: fix modal not shown if Yoast sidebar panel was disabled
  packages/js/src/components/WincherPostPublish.js
  packages/js/src/components/WincherSEOPerformanceModal.js
  packages/js/src/containers/WincherPostPublish.js
Labels: community-patch, changelog: non-user-facing

#17885 Use correct shortlink for wincher help icon in the post publish sidebar
  packages/js/src/components/WincherPostPublish.js
Labels: changelog: non-user-facing

#17890 [QA-2716] Keep tracked keyphrases in Wincher table until untrack/reload
  packages/js/src/redux/selectors/WincherSEOPerformance.js
Labels: community-patch, changelog: non-user-facing

#17893 Composer: allow plugins
  composer.json
Labels: yoast cs/qa, changelog: non-user-facing

#17894 Travis: various tweaks
  .travis.yml
Labels: yoast cs/qa, changelog: non-user-facing

#17886 Fixes the assessment of short cornerstone content
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/assessmentApplicabilityCharacterCount.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/subheadingsTooLong.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: non-user-facing

#17891 PHP 8.1 | Composer: update OAuth2-Client + underlying dependencies
  composer.json
  composer.lock
  config/php-scoper/oauth2-client.inc.php
Labels: yoast cs/qa, changelog: non-user-facing

#17471 [NEEDS INPUT TEAM] QA: fix test not running
  inc/health-check.php
  tests/unit/doubles/inc/health-check-double.php
  tests/unit/inc/health-check-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17898 QA-2722 Wincher: fix debounce not working in WincherKeyphrasesTable
  packages/js/src/components/WincherKeyphrasesTable.js
Labels: changelog: non-user-facing

#17851 Create a new importing action for the noindex setting of default settings
  src/actions/importing/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo-custom-archive-settings-importing-action.php
  src/actions/importing/aioseo-default-archive-settings-importing-action.php
  src/actions/importing/aioseo-posttype-defaults-settings-importing-action.php
  src/actions/importing/aioseo-taxonomy-settings-importing-action.php
  tests/unit/actions/importing/abstract-aioseo-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/doubles/actions/importing/abstract-aioseo-settings-importing-action-double.php
Labels: changelog: non-user-facing

#17828 AR-122 Single Responsibility Per File
  docs/project-decisions/0002-single-responsibility-per-file.md
Labels: changelog: non-user-facing

#17845 P1-1099 Editor data watcher
  apps/seo-integration/src/app.js
  apps/seo-integration/src/replacement-variables.js
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/dom.js
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/helpers/index.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/src/classic-editor/watcher.js
  packages/js/src/watchers/classicEditorWatcher.js
  packages/seo-store/src/analysis/hooks.js
  packages/seo-store/src/analysis/slice/results.js
  packages/seo-store/src/form/slice/keyphrases.js
  packages/seo-store/src/form/tests.js
Labels: innovation, changelog: non-user-facing
