Repository Yoast/wordpress-seo, pull requests merged in 2021-02, with the labels that each got.

#16607 P2-634 No longer load the Premium schema templates in Free
  config/dependency-injection/schema-templates-loader.php
  src/integrations/schema-blocks.php
Labels: changelog: non-user-facing, component: innovation

#16612 P1-361 Add redux flow and self-contained implementation for the modals
  css/src/metabox.css
  js/src/components/modals/editorModals/EditorModal.js
  js/src/containers/EditorModal.js
  js/src/redux/actions/editorModals.js
  js/src/redux/actions/index.js
  js/src/redux/reducers/editorContext.js
  js/src/redux/reducers/editorModals.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/editorContext.js
  js/src/redux/selectors/editorModals.js
  js/src/redux/selectors/index.js
Labels: changelog: enhancement, component: innovation

#16613 P3-353 Refactor the light switch toggle by introducing a presenter
  admin/class-yoast-form.php
  composer.json
  src/presenters/admin/light-switch-presenter.php
Labels: changelog: non-user-facing

#16620 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16616 P1-360 add allowed dismissable alerts
  src/actions/alert-dismissal-action.php
  src/builders/indexable-post-builder.php
  src/integrations/alerts/abstract-dismissable-alert.php
  src/routes/alert-dismissal-route.php
  tests/unit/actions/alert-dismissal-action-test.php
  tests/unit/routes/alert-dismissal-route-test.php
Labels: changelog: non-user-facing, component: innovation

#16615 [QAK-2638] Move HelpScout beacon to a new style integration
  admin/class-admin.php
  js/src/help-scout-beacon.js
  src/integrations/admin/helpscout-beacon.php
Labels: changelog: bugfix

#16582 Remove the address block and schema template from Free
  src/schema-templates/address.block.php
  src/schema-templates/address.schema.php
  tests/unit/dependency-injection/schema-templates-loader-test.php
Labels: changelog: non-user-facing, component: innovation

#16621 Added extra CSS for schema blocks.
  css/src/schema-blocks.css
Labels: UI change, changelog: non-user-facing, component: innovation

#16627 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16624 Always enable bc schema
  readme.txt
  src/context/meta-tags-context.php
  src/generators/schema/breadcrumb.php
  src/generators/schema/webpage.php
  src/surfaces/values/meta.php
  tests/unit/doubles/context/meta-tags-context-mock.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/breadcrumb-test.php
  tests/unit/generators/schema/webpage-test.php
Labels: changelog: enhancement

#16598 P2-280 Add schema pre-publishing check
  js/src/components/AnalysisCheck.js
  js/src/components/AnalysisChecklist.js
  js/src/components/DocumentSidebar.js
  js/src/components/PrePublish.js
  js/src/containers/DocumentSidebar.js
  js/src/containers/PrePublish.js
  js/src/helpers/addCheckToChecklist.js
  js/src/redux/reducers/schemaBlocks.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/schemaBlocks.js
  js/tests/components/AnalysisCheckList.test.js
  js/tests/components/PrePublish.test.js
  js/tests/containers/DocumentSidebar.test.js
  js/tests/containers/PrePublish.test.js
Labels: UI change, changelog: non-user-facing, component: innovation

#16629 [QAK-2647] Don't parse already parsed JSON
  js/src/help-scout-beacon.js
Labels: changelog: non-user-facing

#16640 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16642 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16641 Moved some schema blocks CSS to Premium.
  css/src/schema-blocks.css
Labels: UI change, changelog: non-user-facing, component: innovation

#16637 Cache (shortly) retrieving the home-page indexable
  src/builders/indexable-hierarchy-builder.php
  src/repositories/indexable-hierarchy-repository.php
  src/repositories/indexable-repository.php
  tests/unit/builders/indexable-hierarchy-builder-test.php
Labels: changelog: enhancement

#16648 P2-560 Replace console.logs with logger, initialize at ERROR level
  js/src/schema-blocks.js
Labels: changelog: non-user-facing, changelog: other, component: innovation

#16647 Setup the tasks for building the translations for schema-blocks
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/copy.js
  config/grunt/task-config/shell.js
  package.json
Labels: changelog: non-user-facing, component: innovation

#16650 Put recipe schema behind feature flag
  config/dependency-injection/schema-templates-loader.php
  src/integrations/schema-blocks.php
  tests/unit/dependency-injection/schema-templates-loader-test.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing

#16597 P3-341 Add Badge and Help link presenters
  admin/class-admin-asset-manager.php
  admin/class-yoast-form.php
  css/src/admin-global.css
  css/src/badge.css
  src/presenters/admin/badge-presenter.php
  src/presenters/admin/help-link-presenter.php
  tests/unit/presenters/admin/badge-presenter-test.php
  tests/unit/presenters/admin/help-link-presenter-test.php
Labels: changelog: non-user-facing

#16655 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16626 Implement Video in Elementor editor
  js/src/redux/reducers/editorContext.js
  js/src/redux/selectors/editorContext.js
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#16656 Prevent fatal error due to type declaration
  src/builders/indexable-hierarchy-builder.php
Labels: changelog: bugfix, community-patch

#16657 Introduce broken breadcrumb array check
  src/generators/schema/breadcrumb.php
Labels: Yoast: Schema, changelog: bugfix, community-patch, component: breadcrumbs

#16662 P3-368 Reinstate code added to Free files in Premium repo by mistake
  admin/views/class-yoast-feature-toggle.php
  admin/views/tabs/dashboard/integrations.php
Labels: changelog: bugfix

#16658 P2-668 Use the helper to get the product name
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-metabox.php
  admin/taxonomy/class-taxonomy.php
  src/helpers/product-helper.php
  tests/unit/helpers/product-helper-test.php
Labels: changelog: non-user-facing

#16660 Replaces the deprecated indexable_prepare_indexation_action in the indexing command with the appropriate replacement.
  src/commands/index-command.php
  src/deprecated/src/actions/indexing/indexable-prepare-indexation-action.php
  src/routes/indexing-route.php
  tests/unit/commands/index-command-test.php
  tests/unit/routes/indexing-route-test.php
Labels: changelog: non-user-facing

#16671 Bump monorepo packages for 15.9-RC3
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16676 P2-693 Prevent assets from being loaded when feature flag is disabled
  src/integrations/schema-blocks.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing, component: innovation

#16643 P1 341 abstract dismissable alert
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/metabox/class-metabox.php
  js/src/containers/PersistentDismissableAlert.js
  js/src/initializers/editor-store.js
  js/src/redux/actions/dismissedAlerts.js
  js/src/redux/actions/index.js
  js/src/redux/controls/dismissedAlerts.js
  js/src/redux/controls/index.js
  js/src/redux/reducers/dismissedAlerts.js
  js/src/redux/reducers/index.js
  js/src/redux/selectors/dismissedAlerts.js
  js/src/redux/selectors/index.js
  js/tests/redux/actions/dismissedAlerts.test.js
  js/tests/redux/controls/dismissedAlerts.test.js
  js/tests/redux/reducers/dismissedAlerts.test.js
  js/tests/redux/selectors/dismissedAlerts.test.js
  src/actions/alert-dismissal-action.php
  src/integrations/third-party/elementor.php
  tests/unit/actions/alert-dismissal-action-test.php
Labels: changelog: non-user-facing, component: innovation

#16675 Add custom versions to the migration runner
  src/config/migration-status.php
  src/initializers/migration-runner.php
  tests/unit/database/migration-runner-test.php
  tests/unit/database/migration-status-test.php
Labels: changelog: non-user-facing

#16677 Move initialization to initial file load
  tests/unit/bootstrap.php
  tests/unit/database/migration-status-test.php
  tests/unit/load/wp-seo.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#16686 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16687 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16688 P1 332 persistent dismissable alert for addon settings
  js/src/containers/PersistentDismissableAlert.js
  js/src/editor-modules.js
  js/src/initializers/settings-store.js
  js/src/settings.js
Labels: changelog: non-user-facing, component: innovation

#16689 Fix conflict between Yoast Seo and Polylang For WooCommerce
  src/builders/indexable-link-builder.php
Labels: community-patch

#16669 Create warning for users who enabled WP core auto updates
  admin/class-plugin-conflict.php
  admin/google_search_console/views/gsc-display.php
  composer.json
  src/integrations/estimated-reading-time.php
  src/integrations/watchers/auto-update-watcher.php
  src/presenters/admin/auto-update-notification-presenter.php
  tests/unit/integrations/watchers/auto-update-watcher-test.php
  tests/unit/presenters/admin/auto-update-notification-presenter-test.php
  tests/unit/presenters/slack/enhanced-data-presenter-test.php
Labels: changelog: other

#16693 PHP 8: prevent warning in Yoast_Feature_Toggles
  admin/views/class-yoast-feature-toggles.php
  tests/unit/admin/views/feature-toggles-test.php
Labels: changelog: bugfix, component: admin, php8

#16692 PHP 8: prevent warning in Yoast_Integration_Toggles
  admin/views/class-yoast-integration-toggles.php
  tests/unit/admin/views/integration-toggles-test.php
Labels: changelog: bugfix, component: admin, php8

#16700 [QAK-2725] Fix missing dependency in settings script
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing

#16699 [P3-405] [QAK-2723] [QAK-2722] Fix usage of is_premium functions.
  admin/class-admin-init.php
  admin/class-admin.php
  admin/class-config.php
  admin/class-product-upsell-notice.php
  admin/class-yoast-form.php
  admin/config-ui/components/class-component-suggestions.php
  admin/formatter/class-metabox-formatter.php
  admin/formatter/class-post-metabox-formatter.php
  admin/views/licenses.php
  admin/watchers/class-slug-change-watcher.php
  inc/class-addon-manager.php
  inc/class-wpseo-features.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-shortlinker.php
  inc/class-wpseo-utils.php
  src/helpers/product-helper.php
  src/presenters/debug/marker-open-presenter.php
  tests/integration/doubles/wpseo-features-mock.php
  tests/unit/admin/admin-features-test.php
  tests/unit/helpers/product-helper-test.php
  tests/unit/inc/addon-manager-test.php
  tests/unit/inc/health-check-curl-version-test.php
  tests/unit/inc/health-check-link-table-not-accessible-test.php
  tests/unit/inc/health-check-ryte-test.php
  tests/unit/inc/language-utils-test.php
  tests/unit/integrations/admin/migration-error-integration-test.php
  tests/unit/presenters/admin/migration-error-presenter-test.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#16698 Integrate with wp_robots
  composer.json
  src/conditionals/wp-robots-conditional.php
  src/integrations/front-end-integration.php
  src/integrations/front-end/wp-robots-integration.php
  tests/unit/conditionals/wp-robots-conditional-test.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/integrations/front-end/wp-robots-integration-test.php
Labels: changelog: enhancement

#16705 Delay Elementor load
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#16690 Add contentUrl to schema image output
  src/helpers/schema/image-helper.php
  tests/unit/helpers/schema/image-helper-test.php
Labels: changelog: enhancement

#16649 Performance optimization for company / person logo
  inc/options/class-wpseo-option-titles.php
  src/context/meta-tags-context.php
  src/generators/schema/organization.php
  src/generators/schema/person.php
  src/helpers/image-helper.php
  src/helpers/schema/image-helper.php
  tests/unit/generators/schema/author-test.php
  tests/unit/generators/schema/organization-test.php
  tests/unit/generators/schema/person-test.php
Labels: changelog: enhancement
