Repository Yoast/wordpress-seo, pull requests merged in 2021-04, with the labels that each got.

#16856 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16858 P3-501 Add new yost form method and related CSS.
  admin/class-yoast-form.php
  css/src/yst_plugin_tools.css
Labels: changelog: non-user-facing

#16813 map_taxonomies_for_js() - speed up get_terms call by avoiding priming term meta caches
  admin/class-primary-term-admin.php
Labels: community-patch

#16857 P2-224 Add recipe name block and schema templates
  src/schema-templates/recipe-name.block.php
  src/schema-templates/recipe-name.schema.php
  src/schema-templates/recipe.block.php
  src/schema-templates/recipe.schema.php
  tests/unit/dependency-injection/schema-templates-loader-test.php
Labels: UI change, changelog: non-user-facing

#16864 Bump monorepo packages for 16.2 beta
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16867 Excluded post types are now not build anymore in the build_post_hierarchy method.
  src/builders/indexable-post-builder.php
  src/helpers/post-type-helper.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
Labels: changelog: bugfix

#16828 P1-323 Changes to make the new draft-js-plugins in the monorepo work
  css/src/metabox.css
  css/src/search-appearance.css
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16871 Asset location backward compatibility
  admin/class-admin-asset-manager.php
  admin/class-admin-asset-seo-location.php
Labels: changelog: non-user-facing

#16870 Add Czech to language lists
  src/config/researcher-languages.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#16873 Fix news dependencies
  src/conditionals/news-conditional.php
  src/integrations/admin/fix-news-dependencies-integration.php
Labels: changelog: non-user-facing

#16840 Make sure consistent version information is built for the HTML comment
  src/presenters/debug/marker-open-presenter.php
  tests/unit/presenters/debug/marker-open-presenter-test.php
Labels: changelog: non-user-facing, community-patch

#16859 Allow lower priority hooks to wp_robots
  src/integrations/front-end/wp-robots-integration.php
Labels: changelog: non-user-facing, community-patch

#16831 Add filter for Person schema
  src/generators/schema/person.php
Labels: changelog: enhancement

#16824 P1 345 woo product data in google preview
  js/src/components/SnippetPreviewSection.js
  js/src/containers/SnippetEditor.js
  js/src/redux/actions/index.js
  js/src/redux/actions/shoppingData.js
  js/src/redux/reducers/index.js
  js/src/redux/reducers/shoppingData.js
  js/src/redux/selectors/index.js
  js/src/redux/selectors/shoppingData.js
  js/tests/containers/SnippetEditor.test.js
Labels: changelog: enhancement, component: innovation

#16880 P3-522 Revert renaming of `wpseo_admin_page_meta_post_types` hook
  admin/views/tabs/metas/paper-content/post-type-content.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
Labels: changelog: non-user-facing

#16886 Remove return documentation from constructors
  inc/class-wpseo-replacement-variable.php
  inc/options/class-wpseo-option-wpseo.php
  inc/options/class-wpseo-option.php
  lib/migrations/column.php
  lib/migrations/migration.php
  lib/migrations/table.php
Labels: changelog: non-user-facing

#16888 Set default header of ingredients title to h3
  src/schema-templates/ingredients.block.php
Labels: changelog: non-user-facing

#16893 Reset homepage indexable's image source and meta
  src/builders/indexable-home-page-builder.php
  tests/unit/builders/indexable-home-page-builder-test.php
Labels: changelog: non-user-facing

#16892 Prevent the css/src folder from being shipped
  config/grunt/task-config/copy.js
Labels: changelog: bugfix

#16872 P3-507 Add hook inside the post type archive section of the Search appearance
  admin/views/tabs/metas/paper-content/author-archive-settings.php
  admin/views/tabs/metas/paper-content/date-archives-settings.php
  admin/views/tabs/metas/paper-content/post-type-content.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
Labels: changelog: other

#16883 Make sure translations for the schema-blocks are working
  Gruntfile.js
  admin/class-admin-asset-yoast-components-l10n.php
  config/grunt/custom-tasks/i18n-clean-json.js
  config/grunt/task-config/clean.js
  config/grunt/task-config/convert-pot-to-wp.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/po2json.js
  config/grunt/task-config/shell.js
  js/src/schema-blocks.js
  src/integrations/schema-blocks.php
Labels: changelog: non-user-facing, component: innovation

#16891 For RC1, as well as for beta1, ask the user to enter the full QA changelog
  config/grunt/custom-tasks/github-pre-release.js
Labels: changelog: non-user-facing

#16895 Copies all files in the css directory instead of the ones in the root
  config/grunt/task-config/copy.js
Labels: changelog: non-user-facing

#16898 P1-475 revert draft js upgrade
  css/src/metabox.css
  css/src/search-appearance.css
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16834 Move frontpage form to Content Types tab and add replace var support
  admin/views/class-view-utils.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/metas/taxonomies.php
  admin/views/tabs/social/facebook.php
  composer.json
  css/src/admin-global.css
  inc/class-upgrade.php
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-option-titles.php
  js/src/initializers/search-appearance.js
  js/src/initializers/social-settings.js
  src/generators/schema/breadcrumb.php
  src/integrations/watchers/indexable-home-page-watcher.php
  tests/unit/generators/schema/article-test.php
  tests/unit/inc/options/option-social-test.php
  tests/unit/integrations/watchers/indexable-home-page-watcher-test.php
Labels: UI change, changelog: enhancement

#16897 Removed call to error code in remote handler class as we can't be sure it's an integer
  src/wrappers/wp-remote-handler.php
Labels: changelog: non-user-facing

#16901 P2 857 Save primary term right
  admin/class-primary-term-admin.php
  src/integrations/watchers/primary-term-watcher.php
  tests/unit/integrations/watchers/primary-term-watcher-test.php
Labels: changelog: bugfix

#16908 Handle the situation where the auto_update_plugins option did not previously exist
  inc/class-upgrade.php
  src/integrations/watchers/addon-update-watcher.php
  tests/unit/integrations/watchers/addon-update-watcher-test.php
Labels: changelog: bugfix

#16907 Fix additional space between setting titles and settings.
  admin/views/tabs/metas/paper-content/author-archive-settings.php
  admin/views/tabs/metas/paper-content/date-archives-settings.php
  admin/views/tabs/metas/paper-content/post-type-content.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
  admin/views/tabs/metas/post-types.php
  css/src/yst_plugin_tools.css
Labels: UI change, changelog: enhancement

#16913 Fix woo assessment error
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#16915 Replace SEMrush by Semrush in user-facing strings
  admin/views/class-yoast-integration-toggles.php
  js/src/components/modals/SEMrushKeyphrasesTable.js
  js/src/components/modals/SEMrushLimitReached.js
  js/src/components/modals/SEMrushLoading.js
  tests/unit/admin/views/integration-toggles-test.php
Labels: UI change, changelog: other

#16914 Rename variable-tag-rich-text to heading
  src/schema-templates/ingredients.block.php
  src/schema-templates/recipe-name.block.php
  src/schema-templates/steps.block.php
Labels: UI change, changelog: non-user-facing

#16875 Add "New" badge component for global social templates
  admin/menu/class-replacevar-editor.php
  js/src/components/ImageSelectComponent.js
  js/src/components/SettingsReplacementVariableEditor.js
  js/src/components/SettingsReplacementVariableEditors.js
  js/src/components/portals/ImageSelectPortal.js
  js/src/components/portals/SettingsEditorPortal.js
  js/src/initializers/search-appearance.js
Labels: changelog: non-user-facing

#16850 P3-378 update presentation classes with Global Social Templates
  inc/class-upgrade.php
  inc/options/class-wpseo-option-titles.php
  src/generators/open-graph-image-generator.php
  src/helpers/open-graph/values-helper.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/unit/generators/open-graph-image-generator-test.php
  tests/unit/helpers/open-graph/values-helper-test.php
  tests/unit/presentations/indexable-author-archive-presentation/open-graph-images-test.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-post-type-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-presentation/open-graph-title-test.php
  tests/unit/presentations/indexable-presentation/twitter-description-test.php
  tests/unit/presentations/indexable-presentation/twitter-title-test.php
  tests/unit/presentations/indexable-term-archive-presentation/open-graph-description-test.php
  tests/unit/presentations/presentation-instance-dependencies-trait.php
Labels: changelog: non-user-facing

#16903 Travis: run CS in separate workflow & other minor tweaks
  .travis.yml
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#16902 P2-818 Removed Schema blocks feature flag conditional from Schema blocks integration.
  src/integrations/schema-blocks.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing

#16917 Bump monorepo versions for 16.2
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16921 P2-895 block schema blocks translations from shipping
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
Labels: build tooling, changelog: non-user-facing

#16923 P2-896 Load the Request helper through dependency injection
  src/integrations/front-end-integration.php
  tests/unit/integrations/front-end-integration-test.php
Labels: changelog: non-user-facing

#16928 P2-897 - Remove all schema translations logic
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/shell.js
  package.json
Labels: changelog: non-user-facing

#16922 Allow Free and Premium to use separate instances of the Capability Manager
  admin/capabilities/class-capability-manager-factory.php
Labels: changelog: non-user-facing

#16798 Add product gallery image as fallback
  js/src/redux/selectors/fallbacks.js
Labels: changelog: non-user-facing

#16929 Bump monorepo RCs for 16.3
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16930 Remove all the configuration regarding the `schema-blocks` translations
  Gruntfile.js
  config/grunt/custom-tasks/i18n-clean-json.js
  config/grunt/task-config/clean.js
  config/grunt/task-config/convert-pot-to-wp.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/po2json.js
Labels: changelog: non-user-facing

#16933 Fix broken domain name in the social previews.
  js/src/redux/selectors/fallbacks.js
Labels: changelog: bugfix

#16934 Formatted post date correctly in schema replace vars helper.
  src/helpers/schema/replace-vars-helper.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
Labels: changelog: non-user-facing, component: innovation

#16931 Add Grunt changelog tasks from plugin-grunt-tasks
  .gitignore
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/build-qa-changelog.js
  config/grunt/task-config/download-qa-changelog.js
  config/grunt/task-config/update-changelog-with-latest-pr-texts.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16695 Add thumbnailUrl attribute to Article schema pieces
  src/context/meta-tags-context.php
  src/generators/schema/article.php
  src/generators/schema/main-image.php
  tests/unit/doubles/context/meta-tags-context-mock.php
  tests/unit/generators/schema/article-test.php
  tests/unit/generators/schema/main-image-test.php
Labels: changelog: enhancement

#16937 Bump monorepo packages for 16.3-RC
  package.json
  yarn.lock
Labels: changelog: non-user-facing
