Repository Yoast/wordpress-seo, pull requests merged in 2021-05, with the labels that each got.

#16940 Allow multiple FAQ blocks
  js/src/structured-data-blocks/faq/block.js
Labels: changelog: enhancement

#16939 Add url property to author schema
  src/generators/schema/author.php
  src/helpers/user-helper.php
  tests/unit/generators/schema/author-test.php
Labels: changelog: enhancement

#16708 P2-930 Add wordCount to Article schema
  src/generators/schema/article.php
  tests/unit/generators/schema/article-test.php
Labels: changelog: enhancement

#16941 P2-923 - Reintroduce job posting feature flag
  src/integrations/schema-blocks.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing

#16920 P3-472 Disappearing 'New' badges
  admin/menu/class-replacevar-editor.php
  admin/views/tabs/metas/paper-content/front-page-content.php
  js/src/initializers/search-appearance.js
  src/config/badge-group-names.php
  src/presenters/admin/badge-presenter.php
  tests/unit/config/badge-group-names-test.php
  tests/unit/presenters/admin/badge-presenter-test.php
Labels: changelog: non-user-facing

#16943 Adds the table of contents accessibility feature to the article piece…
  src/generators/schema-generator.php
  src/integrations/front-end/schema-accessibility-feature.php
Labels: changelog: enhancement

#16936 Prevent the displaying of an Organization schema piece if the logo is an unsupported image
  src/context/meta-tags-context.php
  tests/unit/context/meta-tags-context-test.php
Labels: changelog: bugfix

#16945 Composer: update dev dependencies
  composer.json
  composer.lock
Labels: changelog: non-user-facing, yoast cs/qa

#16959 QA: let static closures be static
  config/composer/actions.php
  config/dependency-injection/interface-injection-pass.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-utils.php
  lib/orm.php
  src/actions/indexing/indexable-post-type-archive-indexation-action.php
  src/generators/breadcrumbs-generator.php
  src/generators/schema/article.php
  src/integrations/front-end-integration.php
  src/integrations/front-end/wp-robots-integration.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/surfaces/values/meta.php
  tests/integration/formatter/test-metabox-formatter.php
  tests/integration/notifications/test-class-yoast-notification-center.php
  tests/unit/actions/indexing/indexable-post-type-archive-indexation-action-test.php
  tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
  tests/unit/generators/schema/article-test.php
  tests/unit/generators/schema/howto-test.php
  tests/unit/generators/schema/webpage-test.php
  tests/unit/generators/schema/website-test.php
  tests/unit/helpers/current-page-helper-test.php
  tests/unit/inc/options/option-social-test.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
  tests/unit/presentations/indexable-post-type-presentation/canonical-test.php
  tests/unit/presentations/indexable-static-home-page-presentation/canonical-test.php
  tests/unit/presenters/meta-description-presenter-test.php
  tests/unit/presenters/open-graph/description-presenter-test.php
  tests/unit/presenters/open-graph/title-presenter-test.php
  tests/unit/presenters/title-presenter-test.php
  tests/unit/presenters/twitter/title-presenter-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16960 CS: no yoda conditions
  admin/class-admin-asset-dev-server-location.php
  admin/class-admin.php
  admin/class-yoast-notifications.php
  inc/class-wpseo-rank.php
  inc/class-wpseo-statistics.php
  inc/sitemaps/class-sitemap-cache-data.php
  src/integrations/admin/link-count-columns-integration.php
  src/integrations/third-party/web-stories.php
Labels: changelog: non-user-facing, yoast cs/qa

#16961 CS: class constants before properties
  src/integrations/third-party/elementor.php
  src/integrations/third-party/wpml-wpseo-notification.php
Labels: changelog: non-user-facing, yoast cs/qa

#16962 Performance: use isset()
  admin/class-plugin-availability.php
Labels: changelog: non-user-facing, yoast cs/qa

#16963 QA: don't use `join()`
  lib/migrations/adapter.php
  lib/migrations/table.php
  lib/orm.php
Labels: changelog: non-user-facing, yoast cs/qa

#16964 CS/QA: various small fixes
  admin/class-yoast-form.php
  admin/class-yoast-network-admin.php
  inc/class-wpseo-replace-vars.php
  inc/sitemaps/class-sitemap-cache-data.php
  lib/orm.php
  src/builders/indexable-hierarchy-builder.php
  src/generators/schema/faq.php
  src/presentations/indexable-presentation.php
  tests/integration/doubles/wpseo-wp-rest-server-mock.php
  tests/integration/inc/test-class-wpseo-upgrade.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-cache-data.php
Labels: changelog: non-user-facing, yoast cs/qa

#16965 Modernize: use __DIR__
  tests/unit/bootstrap.php
Labels: changelog: non-user-facing, yoast cs/qa

#16966 QA: import all classes in namespaced files
  config/composer/unit-test-generator.php
  config/dependency-injection/inject-from-registry-pass.php
  config/dependency-injection/interface-injection-pass.php
  src/actions/semrush/semrush-phrases-action.php
  src/builders/indexable-post-builder.php
  src/config/semrush-client.php
  src/exceptions/indexable/indexable-exception.php
  src/exceptions/oauth/authentication-failed-exception.php
  src/exceptions/semrush/tokens/empty-property-exception.php
  src/exceptions/semrush/tokens/empty-token-exception.php
  src/exceptions/semrush/tokens/failed-storage-exception.php
  src/helpers/date-helper.php
  src/integrations/schema-blocks.php
  src/integrations/third-party/elementor.php
  src/routes/indexing-route.php
  tests/unit/actions/alert-dismissal-action-test.php
  tests/unit/doubles/admin/admin-gutenberg-compatibility-notification-double.php
  tests/unit/doubles/builders/indexable-post-builder-double.php
  tests/unit/doubles/integrations/watchers/indexable-post-watcher-double.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
  tests/unit/presenters/admin/badge-presenter-test.php
  tests/unit/routes/alert-dismissal-route-test.php
  tests/unit/routes/indexing-route-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16968 QA: remove redundant use statements
  src/generators/open-graph-image-generator.php
  src/generators/twitter-image-generator.php
  src/integrations/admin/helpscout-beacon.php
  src/presenters/debug/marker-open-presenter.php
  tests/unit/admin/metabox/metabox-collapsibles-section-test.php
  tests/unit/admin/paper-presenter-test.php
  tests/unit/admin/views/integration-toggles-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/doubles/models/indexable-double.php
  tests/unit/generators/schema/main-image-test.php
  tests/unit/inc/options/option-social-test.php
  tests/unit/integrations/exclude-oembed-cache-post-type-test.php
  tests/unit/integrations/third-party/elementor-exclude-post-types-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16969 Tests: minor tweaks
  tests/unit/doubles/inc/options/option-social-double.php
  tests/unit/routes/yoast-head-rest-field-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16967 QA: no FQN in non-namespaced files
  src/deprecated/admin/add-keyword-modal.php
  src/deprecated/admin/keyword-synonyms-modal.php
  src/deprecated/admin/multiple-keywords-modal.php
  src/deprecated/frontend/breadcrumbs.php
  src/deprecated/frontend/frontend.php
  src/deprecated/frontend/schema/class-schema-howto.php
  src/deprecated/frontend/schema/class-schema-main-image.php
  src/deprecated/frontend/schema/class-schema-person.php
  tests/integration/admin/test-class-yoast-network-admin.php
  tests/integration/formatter/test-metabox-formatter.php
Labels: changelog: non-user-facing, yoast cs/qa

#16970 CS: alphabetically ordered use statements
  admin/metabox/class-metabox.php
  src/integrations/third-party/wpml-wpseo-notification.php
  src/presentations/indexable-author-archive-presentation.php
  tests/unit/actions/alert-dismissal-action-test.php
  tests/unit/conditionals/estimated-reading-time-conditional-test.php
  tests/unit/conditionals/third-party/elementor-activated-conditional-test.php
  tests/unit/helpers/open-graph/values-helper-test.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
  tests/unit/integrations/exclude-oembed-cache-post-type-test.php
  tests/unit/integrations/third-party/elementor-exclude-post-types-test.php
  tests/unit/integrations/third-party/wpml-wpseo-notification-test.php
  tests/unit/integrations/watchers/addon-update-watcher-test.php
  tests/unit/integrations/watchers/auto-update-watcher-test.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/routes/indexing-route-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16971 QA: use FQN calls to global functions in namespaced files
  config/composer/actions.php
  config/dependency-injection/inject-from-registry-pass.php
  config/dependency-injection/schema-templates-loader.php
  src/builders/indexable-link-builder.php
  src/config/badge-group-names.php
  src/context/meta-tags-context.php
  src/deprecated/src/presenters/open-graph/fb-app-id-presenter.php
  src/generators/schema/article.php
  src/generators/schema/breadcrumb.php
  src/generators/schema/person.php
  src/helpers/request-helper.php
  src/helpers/url-helper.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/front-end-integration.php
  src/integrations/front-end/schema-accessibility-feature.php
  src/integrations/front-end/wp-robots-integration.php
  src/integrations/schema-blocks.php
  src/integrations/third-party/elementor.php
  src/integrations/third-party/wpml-wpseo-notification.php
  src/integrations/watchers/primary-category-quick-edit-watcher.php
  src/presenters/admin/badge-presenter.php
  src/presenters/admin/help-link-presenter.php
  src/presenters/admin/light-switch-presenter.php
  src/repositories/indexable-hierarchy-repository.php
  src/repositories/indexable-repository.php
  src/values/images.php
  tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
  tests/unit/conditionals/third-party/elementor-activated-conditional-test.php
  tests/unit/config/badge-group-names-test.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
  tests/unit/integrations/front-end/wp-robots-integration-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16972 QA: fix incorrect escaping
  admin/views/licenses.php
Labels: changelog: non-user-facing, yoast cs/qa

#16973 Docs: various fixes return tags
  admin/class-admin.php
  admin/class-helpscout.php
  admin/class-product-upsell-notice.php
  admin/config-ui/class-configuration-storage.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-fields-presenter.php
  admin/taxonomy/class-taxonomy.php
  config/composer/actions.php
  lib/orm.php
  src/commands/index-command.php
  src/conditionals/front-end-conditional.php
  src/conditionals/headless-rest-endpoints-enabled-conditional.php
  src/conditionals/jetpack-conditional.php
  src/conditionals/migrations-conditional.php
  src/conditionals/open-graph-conditional.php
  src/conditionals/primary-category-conditional.php
  src/conditionals/should-index-links-conditional.php
  src/conditionals/web-stories-conditional.php
  src/conditionals/woocommerce-conditional.php
  src/conditionals/yoast-admin-and-dashboard-conditional.php
  src/context/meta-tags-context.php
  src/deprecated/frontend/frontend.php
  src/deprecated/src/integrations/admin/indexation-integration.php
  src/deprecated/src/integrations/admin/link-count-notification-integration.php
  src/deprecated/src/integrations/admin/link-count-tools-integration.php
  src/deprecated/src/presenters/admin/link-count-indexing-list-item-presenter.php
  src/generators/breadcrumbs-generator.php
  src/integrations/admin/admin-columns-cache-integration.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/front-end-integration.php
  src/integrations/front-end/force-rewrite-title.php
  src/integrations/front-end/indexing-controls.php
  src/integrations/front-end/wp-robots-integration.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-date-archive-watcher.php
  src/integrations/watchers/indexable-home-page-watcher.php
  src/integrations/watchers/indexable-post-meta-watcher.php
  src/integrations/watchers/indexable-post-type-archive-watcher.php
  src/integrations/watchers/indexable-static-home-page-watcher.php
  src/integrations/watchers/indexable-system-page-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  src/presentations/archive-adjacent-trait.php
  src/presenters/admin/indexing-notification-presenter.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-renderer.php
  tests/unit/integrations/front-end/open-graph-oembed-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16975 Docs: `@param` tags should contain variable name
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
Labels: changelog: non-user-facing, yoast cs/qa

#16976 QA: use FQN global constants in namespaced files
  config/composer/unit-test-generator.php
  src/conditionals/admin/estimated-reading-time-conditional.php
  src/conditionals/third-party/elementor-edit-conditional.php
  src/helpers/date-helper.php
  src/helpers/input-helper.php
  src/helpers/request-helper.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/front-end/wp-robots-integration.php
  src/integrations/third-party/elementor.php
  src/repositories/indexable-repository.php
  tests/unit/conditionals/estimated-reading-time-conditional-test.php
  tests/unit/helpers/input-helper-test.php
  tests/unit/integrations/schema-blocks-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16978 Docs: various type fixes
  admin/class-premium-popup.php
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  admin/taxonomy/class-taxonomy.php
  config/dependency-injection/custom-loader.php
  src/builders/indexable-link-builder.php
  src/generators/breadcrumbs-generator.php
  src/integrations/admin/admin-columns-cache-integration.php
  src/models/seo-links.php
  tests/unit/conditionals/no-tool-selected-conditional-test.php
  tests/unit/conditionals/yoast-tools-page-conditional-test.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/helpers/url-helper-test.php
  tests/unit/integrations/watchers/primary-term-watcher-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16979 Docs: improve types in `@var` tags
  admin/class-yoast-form.php
  inc/class-addon-manager.php
  inc/class-wpseo-replace-vars.php
  inc/options/class-wpseo-option.php
  inc/options/class-wpseo-options.php
  src/deprecated/frontend/class-twitter.php
Labels: changelog: non-user-facing, yoast cs/qa

#16980 Docs: improve type order
  admin/class-database-proxy.php
  admin/class-option-tabs.php
  admin/class-remote-request.php
  admin/class-yoast-notification-center.php
  admin/class-yoast-notification.php
  admin/class-yoast-notifications.php
  admin/config-ui/class-configuration-options-adapter.php
  admin/config-ui/fields/class-field-multiple-authors.php
  admin/config-ui/fields/class-field-site-name.php
  admin/roles/class-abstract-role-manager.php
  admin/roles/class-role-manager.php
  admin/tracking/class-tracking-theme-data.php
  inc/class-upgrade-history.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-replace-vars.php
  inc/sitemaps/class-sitemaps-cache-validator.php
  inc/sitemaps/class-sitemaps-cache.php
  inc/wpseo-functions.php
  lib/abstract-main.php
  lib/model.php
  lib/orm.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/context/meta-tags-context.php
  src/deprecated/admin/extension-manager.php
  src/deprecated/frontend/class-opengraph-image.php
  src/deprecated/frontend/class-primary-category.php
  src/helpers/indexable-helper.php
  src/integrations/primary-category.php
  src/integrations/watchers/indexable-permalink-watcher.php
  src/repositories/indexable-repository.php
  src/values/images.php
  tests/integration/doubles/wpseo-configuration-service-mock.php
  tests/unit/doubles/builders/indexable-post-builder-double.php
  tests/unit/doubles/builders/indexable-term-builder-double.php
  tests/unit/doubles/models/indexable-double.php
Labels: changelog: non-user-facing, yoast cs/qa

#16981 Docs: fix missing/incorrect types in `@return` tags
  admin/class-admin-asset-yoast-components-l10n.php
  admin/class-admin-init.php
  admin/class-asset.php
  admin/class-product-upsell-notice.php
  admin/class-yoast-input-validation.php
  admin/class-yoast-notification-center.php
  admin/config-ui/components/class-component-mailchimp-signup.php
  admin/filters/class-cornerstone-filter.php
  admin/metabox/class-metabox-null-tab.php
  admin/ryte/class-ryte.php
  inc/class-addon-manager.php
  inc/class-wpseo-shortlinker.php
  lib/dependency-injection/container-registry.php
  lib/migrations/adapter.php
  lib/migrations/migration.php
  lib/model.php
  src/actions/alert-dismissal-action.php
  src/actions/indexing/abstract-link-indexing-action.php
  src/builders/indexable-author-builder.php
  src/deprecated/admin/class-social-admin.php
  src/deprecated/admin/links/class-link-compatibility-notifier.php
  src/deprecated/admin/links/class-link-table-accessible-notifier.php
  src/deprecated/admin/notifiers/class-post-type-archive-notification-handler.php
  src/deprecated/frontend/class-twitter.php
  src/helpers/author-archive-helper.php
  src/presentations/indexable-presentation.php
  src/routes/yoast-head-rest-field.php
Labels: changelog: non-user-facing, yoast cs/qa

#16982 QA: remove commented out code
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-taxonomy-meta.php
Labels: changelog: non-user-facing, yoast cs/qa

#16983 Docs: remove various tags
  admin/class-admin.php
  src/deprecated/frontend/schema/class-schema-howto.php
  tests/integration/admin/test-class-admin-asset-dev-server-location.php
Labels: changelog: non-user-facing, yoast cs/qa

#16984 QA: fix incorrect test file name
  tests/unit/actions/indexing/indexable-indexing-complete-action-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16985 QA/Tests: fix two incorrect namespaces
  tests/unit/dependency-injection/schema-templates-loader-test.php
  tests/unit/dependency-injection/schema-templates-pass-test.php
Labels: changelog: non-user-facing, yoast cs/qa

#16986 Docs: fix parameter doc alignment
  admin/class-yoast-form.php
  config/dependency-injection/inject-from-registry-pass.php
  src/commands/index-command.php
  src/generators/schema-generator.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/third-party/web-stories.php
  src/integrations/watchers/primary-category-quick-edit-watcher.php
  tests/integration/notifications/test-class-yoast-notification-center.php
  tests/unit/doubles/admin/admin-gutenberg-compatibility-notification-double.php
Labels: changelog: non-user-facing, yoast cs/qa

#16987 Docs: fix incorrect param types
  admin/class-admin-asset-dev-server-location.php
  admin/class-admin-asset-manager.php
  admin/class-customizer.php
  admin/class-database-proxy.php
  admin/class-meta-columns.php
  admin/class-paper-presenter.php
  admin/class-primary-term-admin.php
  admin/class-yoast-form.php
  admin/class-yoast-notification-center.php
  admin/menu/class-base-menu.php
  admin/taxonomy/class-taxonomy-columns.php
  config/dependency-injection/custom-loader.php
  inc/class-upgrade.php
  inc/class-wpseo-admin-bar-menu.php
  inc/class-wpseo-content-images.php
  inc/class-wpseo-image-utils.php
  inc/language-utils.php
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-option-wpseo.php
  inc/options/class-wpseo-option.php
  inc/options/class-wpseo-options.php
  inc/options/class-wpseo-taxonomy-meta.php
  lib/migrations/adapter.php
  lib/migrations/migration.php
  src/commands/index-command.php
  src/config/badge-group-names.php
  src/deprecated/admin/extension-manager.php
  src/deprecated/frontend/class-opengraph-image.php
  src/deprecated/frontend/class-primary-category.php
  src/deprecated/frontend/schema/class-schema-article.php
  src/helpers/indexable-helper.php
  src/helpers/meta-helper.php
  src/helpers/post-helper.php
  src/helpers/schema/article-helper.php
  src/helpers/url-helper.php
  src/integrations/primary-category.php
  src/integrations/third-party/woocommerce.php
  src/memoizers/meta-tags-context-memoizer.php
  src/memoizers/presentation-memoizer.php
  src/presentations/indexable-author-archive-presentation.php
  src/presenters/admin/badge-presenter.php
  src/repositories/indexable-repository.php
  src/surfaces/meta-surface.php
  tests/integration/doubles/class-upgrade-double.php
Labels: changelog: non-user-facing, yoast cs/qa

#16988 Docs: use full docblock format for properties
  src/presenters/admin/meta-fields-presenter.php
Labels: changelog: non-user-facing, yoast cs/qa

#16990 Docs: various minor tweaks
  admin/class-database-proxy.php
  admin/config-ui/class-configuration-page.php
  admin/formatter/class-metabox-formatter.php
  admin/import/plugins/class-import-jetpack.php
  admin/views/tabs/dashboard/webmaster-tools.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  config/dependency-injection/interface-injection-pass.php
  inc/class-upgrade.php
  inc/class-wpseo-replace-vars.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-option.php
  inc/sitemaps/class-sitemap-image-parser.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
  src/conditionals/admin/doing-post-quick-edit-save-conditional.php
  src/deprecated/admin/extension.php
  src/integrations/third-party/elementor.php
  src/integrations/watchers/primary-category-quick-edit-watcher.php
  src/presenters/breadcrumbs-presenter.php
  src/presenters/meta-description-presenter.php
  src/presenters/title-presenter.php
  src/values/open-graph/images.php
  tests/unit/conditionals/admin/doing-post-quick-edit-save-conditional-test.php
  tests/unit/conditionals/estimated-reading-time-conditional-test.php
  tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
  wp-seo-main.php
Labels: changelog: non-user-facing, yoast cs/qa

#16991 Composer: update CS thresholds
  composer.json
Labels: changelog: non-user-facing, yoast cs/qa

#16952 Consistently self-close enhanced twitter meta tags
  src/presenters/slack/enhanced-data-presenter.php
  tests/unit/presenters/slack/enhanced-data-presenter-test.php
Labels: changelog: enhancement, community-patch

#16882 add --no-git-push option to sync-gutenberg-versions grunt task
  config/grunt/custom-tasks/sync-gutenberg-version.js
Labels: changelog: non-user-facing

#16954 Change color and radius of adminbar notification
  css/src/adminbar.css
Labels: UI change, changelog: enhancement, community-patch

#16953 Increase Ryte sitecheck timeout
  admin/ryte/class-ryte-request.php
Labels: changelog: non-user-facing, community-patch

#16955 P3-584 do not restrict image types but avoid race condition
  src/context/meta-tags-context.php
  src/generators/schema/organization.php
  src/helpers/image-helper.php
  tests/unit/context/meta-tags-context-test.php
  tests/unit/generators/schema/organization-test.php
Labels: changelog: bugfix

#16999 P2-953 Fixed CS issues to match the threshold.
  src/deprecated/admin/onpage/class-onpage-option.php
  src/integrations/front-end-integration.php
Labels: changelog: non-user-facing

#16994 Fix path of the Yoast SEO icon image
  admin/class-premium-popup.php
  admin/class-yoast-notification.php
  css/src/dashboard.css
  css/src/yst_plugin_tools.css
  css/src/yst_plugin_tools.scss
  inc/health-check.php
  tests/unit/inc/health-check-test.php
Labels: changelog: non-user-facing

#17001 P3-589 Keep original frontpage Open Graph settings for downgrades
  admin/tracking/class-tracking-settings-data.php
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/social/facebook.php
  composer.json
  inc/class-upgrade.php
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-option-titles.php
  js/src/initializers/admin.js
  js/src/initializers/search-appearance.js
  src/builders/indexable-home-page-builder.php
  src/integrations/watchers/indexable-home-page-watcher.php
  tests/unit/builders/indexable-home-page-builder-test.php
  tests/unit/integrations/watchers/indexable-home-page-watcher-test.php
Labels: changelog: non-user-facing

#17009 Add extra path in grunt-task config for images inside the js package
  config/grunt/task-config/copy.js
Labels: changelog: non-user-facing

#17014 Remove the Global Social Templates upgrade routine.
  inc/class-upgrade.php
  js/src/initializers/admin.js
  src/builders/indexable-home-page-builder.php
  tests/unit/builders/indexable-home-page-builder-test.php
Labels: changelog: non-user-facing

#17015 P3-592 revert GST changes in presentations classes
  src/generators/open-graph-image-generator.php
  src/helpers/open-graph/values-helper.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/unit/generators/open-graph-image-generator-test.php
  tests/unit/helpers/open-graph/values-helper-test.php
  tests/unit/presentations/indexable-author-archive-presentation/open-graph-images-test.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-post-type-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-presentation/open-graph-title-test.php
  tests/unit/presentations/indexable-presentation/twitter-description-test.php
  tests/unit/presentations/indexable-presentation/twitter-title-test.php
  tests/unit/presentations/indexable-term-archive-presentation/open-graph-description-test.php
  tests/unit/presentations/presentation-instance-dependencies-trait.php
Labels: changelog: non-user-facing

#17017 skip the getParentSidebar test
  packages/js/package.json
  packages/schema-blocks/tests/functions/blocks/getParentSidebar.test.ts
Labels: changelog: non-user-facing

#17002 Add a feature flag for the addon installation project
  src/conditionals/addon-installation-conditional.php
  src/routes/supported-features-route.php
  tests/unit/routes/supported-features-route-test.php
Labels: changelog: non-user-facing

#17019 LINGO-819 Fix failing schema blocks tests
  packages/schema-blocks/tests/functions/blocks/getParentSidebar.test.ts
  packages/schema-blocks/tests/functions/presenters/BlockSuggestionsPresenter.test.ts
Labels: changelog: non-user-facing

#17021 Update readme file: remove leftovers from linking the monorepo
  README.md
Labels: changelog: non-user-facing

#17020 Change prop type that was causing a console error in the configuration wizard
  packages/configuration-wizard/src/Choice.js
Labels: changelog: non-user-facing

#17022 P2-948 - Move Schema analysis to metabox
  js/src/components/SchemaTab.js
  js/src/containers/SchemaTab.js
Labels: changelog: non-user-facing, component: innovation

#16992 PLAT-924 - Introduce the Addon Installation flow
  admin/class-admin-asset-manager.php
  admin/views/licenses.php
  config/dependency-injection/services.php
  config/webpack/paths.js
  inc/class-addon-manager.php
  packages/js/src/addon-installation.js
  packages/js/src/components/AddonInstallation.js
  src/actions/addon-installation/addon-activate-action.php
  src/actions/addon-installation/addon-install-action.php
  src/conditionals/admin/licenses-page-conditional.php
  src/exceptions/addon-installation/addon-activation-error-exception.php
  src/exceptions/addon-installation/addon-already-installed-exception.php
  src/exceptions/addon-installation/addon-installation-error-exception.php
  src/exceptions/addon-installation/user-cannot-activate-plugins-exception.php
  src/exceptions/addon-installation/user-cannot-install-plugins-exception.php
  src/helpers/require-file-helper.php
  src/integrations/admin/addon-installation/dialog-integration.php
  src/integrations/admin/addon-installation/installation-integration.php
  src/wordpress/wrapper.php
  tests/unit/actions/addon-installation/addon-activate-action-test.php
  tests/unit/actions/addon-installation/addon-install-action-test.php
  tests/unit/inc/addon-manager-test.php
  tests/unit/integrations/admin/addon-installation/dialog-integration-test.php
Labels: changelog: non-user-facing

#17031 QAK-2892 Ensure robots values are always congruent if noindex and or nofollow is set
  src/integrations/front-end/wp-robots-integration.php
  tests/unit/integrations/front-end/wp-robots-integration-test.php
Labels: changelog: bugfix

#16948 P3-582 improve presentations classes
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/unit/presentations/indexable-post-type-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-post-type-presentation/twitter-description-test.php
  tests/unit/presentations/indexable-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-presentation/open-graph-title-test.php
  tests/unit/presentations/indexable-presentation/twitter-description-test.php
  tests/unit/presentations/indexable-presentation/twitter-image-test.php
  tests/unit/presentations/indexable-presentation/twitter-title-test.php
  tests/unit/presentations/indexable-term-archive-presentation/open-graph-description-test.php
  tests/unit/presentations/indexable-term-archive-presentation/twitter-description-test.php
Labels: changelog: non-user-facing

#17024 P3-595 Social forms for homepage
  admin/views/class-view-utils.php
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/metas/paper-content/general-content.php
  admin/views/tabs/metas/paper-content/general/force-rewrite-title.php
  admin/views/tabs/metas/paper-content/general/homepage.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/metas/paper-content/general/title-separator.php
  admin/views/tabs/metas/post-types.php
  admin/views/tabs/social/facebook.php
  js/src/initializers/search-appearance.js
Labels: UI change, changelog: enhancement

#17040 P3-590 Change defaults for social title templates
  inc/class-upgrade.php
  inc/options/class-wpseo-option-titles.php
Labels: changelog: non-user-facing

#17046 Remove the Addon installation feature flag
  src/conditionals/addon-installation-conditional.php
  src/integrations/admin/addon-installation/dialog-integration.php
  src/integrations/admin/addon-installation/installation-integration.php
  src/routes/supported-features-route.php
  tests/unit/routes/supported-features-route-test.php
Labels: changelog: non-user-facing

#17047 Bump @yoast/grunt-plugin-tasks to version ^2.1.1
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#17039 P3-574 Update the social templates previews to include values from the global social templates
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
  js/src/elementor/containers/FacebookEditor.js
  js/src/elementor/containers/TwitterEditor.js
  js/src/elementor/replaceVars/general/excerpt.js
  js/src/redux/actions/facebookEditor.js
  js/src/redux/actions/twitterEditor.js
  js/src/redux/selectors/editorData.js
  js/src/redux/selectors/fallbacks.js
  js/tests/redux/selectors/analysisSelectors.test.js
  js/tests/redux/selectors/fallbackSelectors.test.js
  tests/integration/formatter/test-post-metabox-formatter.php
  tests/integration/formatter/test-term-metabox-formatter.php
  tests/unit/admin/formatter/post-metabox-formatter-test.php
Labels: changelog: non-user-facing

#17048 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#17032 P3-573 - Prevent creation of Social-related options for attachments
  inc/options/class-wpseo-option-titles.php
Labels: changelog: non-user-facing

#17050 Merge release 16.3
  apps/components/package.json
  apps/content-analysis/package.json
  packages/analysis-report/package.json
  packages/components/package.json
  packages/configuration-wizard/package.json
  packages/js/package.json
  packages/replacement-variable-editor/package.json
  packages/schema-blocks/package.json
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/package.json
  packages/yoast-components/package.json
  readme.txt
  yarn.lock
Labels: changelog: non-user-facing

#17054 Set the home social title default to the site title.
  inc/options/class-wpseo-option-titles.php
Labels: changelog: non-user-facing

#17056 Update Hungarian morphology data version
  apps/content-analysis/src/utils/getMorphologyData.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#17011 P3-588 Show notification about frontpage being hidden due to Open Graph settings
  admin/views/class-view-utils.php
  admin/views/tabs/metas/paper-content/front-page-content.php
Labels: changelog: bugfix

#16876 CS: Output escaping
  admin/views/form/fieldset.php
  admin/views/tabs/metas/paper-content/post_type/woocommerce-shop-page.php
  composer.json
  src/integrations/admin/migration-error-integration.php
  src/integrations/front-end/force-rewrite-title.php
Labels: changelog: non-user-facing

#16768 Add expect header to the MyYoast API requests
  inc/class-my-yoast-api-request.php
Labels: changelog: enhancement

#17055 P2-975 Updated typescript and typescript-parser to allow for visual feedback in VSCode
  package.json
  packages/schema-blocks/.eslintrc
  packages/schema-blocks/package.json
  packages/schema-blocks/src/core/Definition.ts
  packages/schema-blocks/src/core/Instruction.ts
  packages/schema-blocks/src/core/blocks/BlockDefinitionRepository.ts
  packages/schema-blocks/src/core/schema/SchemaDefinition.ts
  packages/schema-blocks/src/core/schema/SchemaInstruction.ts
  packages/schema-blocks/src/core/validation/BlockValidationResult.ts
  packages/schema-blocks/src/functions/BlockHelper.ts
  packages/schema-blocks/src/functions/blocks/recurseOverBlocks.ts
  packages/schema-blocks/src/functions/gutenberg/block.ts
  packages/schema-blocks/src/functions/gutenberg/filter.ts
  packages/schema-blocks/src/functions/gutenberg/inject-sidebar.tsx
  packages/schema-blocks/src/functions/gutenberg/storeBlockValidation.ts
  packages/schema-blocks/src/functions/gutenberg/watch.ts
  packages/schema-blocks/src/functions/gutenberg/watchers/removeObsoleteWarnings.ts
  packages/schema-blocks/src/functions/initialize.ts
  packages/schema-blocks/src/functions/logger.ts
  packages/schema-blocks/src/functions/presenters/BlockAppender.tsx
  packages/schema-blocks/src/functions/presenters/HeadingLevelDropdown.tsx
  packages/schema-blocks/src/functions/presenters/HeadingLevelIcon.tsx
  packages/schema-blocks/src/functions/presenters/SchemaAnalysis.tsx
  packages/schema-blocks/src/functions/presenters/VariationPickerPresenter.tsx
  packages/schema-blocks/src/functions/redux/initializeSchemaStore.ts
  packages/schema-blocks/src/functions/validators/getPresence.ts
  packages/schema-blocks/src/instructions/blocks/Heading.tsx
  packages/schema-blocks/src/instructions/blocks/VariationPicker.tsx
  packages/schema-blocks/src/type-adapters/ExtendedBlockConfiguration.ts
  packages/schema-blocks/tests/blocks/warning-block/edit.test.ts
  packages/schema-blocks/tests/functions/gutenberg/watchers/warningWatcher.test.ts
  yarn.lock
Labels: changelog: non-user-facing

#17058 Add recipe description block
  src/schema-templates/recipe-description.block.php
  src/schema-templates/recipe-description.schema.php
  src/schema-templates/recipe.block.php
  src/schema-templates/recipe.schema.php
  tests/unit/dependency-injection/schema-templates-loader-test.php
Labels: changelog: non-user-facing

#17065 Delete yst_plugin_tools.scss file already removed in 14.6
  css/src/yst_plugin_tools.scss
Labels: changelog: non-user-facing

#17077 Add missing space in feedback text
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper4.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper2.js
  packages/yoastseo/spec/scoring/assessments/seo/IntroductionKeywordAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js
Labels: changelog: bugfix

#17068 P3-616 show Global Social Templates in Free
  admin/menu/class-replacevar-editor.php
  admin/views/class-view-utils.php
  css/src/yst_plugin_tools.css
  css/src/yst_plugin_tools.scss
  packages/components/src/image-select/ImageSelect.js
  packages/components/src/image-select/ImageSelectButtons.js
  packages/components/tests/__snapshots__/ImageSelectButtonsTest.js.snap
  packages/components/tests/__snapshots__/ImageSelectTest.js.snap
  packages/js/src/components/ImageSelectComponent.js
  packages/js/src/components/SettingsReplacementVariableEditor.js
  packages/js/src/components/SettingsReplacementVariableEditors.js
  packages/js/src/components/portals/ImageSelectPortal.js
  packages/js/src/components/portals/SettingsEditorPortal.js
  packages/js/src/containers/FacebookEditor.js
  packages/js/src/initializers/search-appearance.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/SettingsSnippetEditor.js
  packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
  packages/replacement-variable-editor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
  src/integrations/admin/social-templates-integration.php
Labels: changelog: non-user-facing

#17069 P3-514 Make sure the Global Social Templates match the design
  admin/class-admin-editor-specific-replace-vars.php
  admin/class-yoast-form.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/dashboard/integrations.php
  admin/views/tabs/metas/archives.php
  admin/views/tabs/metas/paper-content/author-archive-settings.php
  admin/views/tabs/metas/paper-content/date-archives-settings.php
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/metas/paper-content/post-type-content.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  admin/views/tabs/metas/paper-content/taxonomy-content.php
  admin/views/tabs/metas/taxonomies/category-url.php
  admin/views/tabs/network/features.php
  admin/views/tabs/network/integrations.php
  admin/views/tabs/social/facebook.php
  admin/views/tabs/social/twitterbox.php
  css/src/search-appearance.css
  css/src/toggle-switch.css
  css/src/yst_plugin_tools.css
  packages/components/src/help-icon/help-icon.css
  packages/components/src/input/InputContainer.js
  packages/js/src/initializers/search-appearance.js
  packages/replacement-variable-editor/src/Mention.js
  packages/replacement-variable-editor/src/shared.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
  packages/style-guide/src/helpers.js
  src/presenters/admin/light-switch-presenter.php
  tests/integration/admin/test-class-admin-editor-specific-replace-vars.php
Labels: changelog: non-user-facing

#17063 P3 622 fix unsafe redirect in redirect helper
  src/helpers/redirect-helper.php
  src/integrations/front-end/redirects.php
  tests/unit/integrations/front-end/redirects-test.php
Labels: changelog: non-user-facing

#17082 Refactor the memoize function for collecting stems
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/buildTopicStems.js
Labels: changelog: non-user-facing

#17084 [QAK-2923] Add missing api-client dependency to editor scripts
  admin/class-admin-asset-manager.php
Labels: changelog: bugfix

#17078 Fix primary category not working for custom post type in Gutenberg editor
  admin/class-primary-term-admin.php
  composer.json
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/integrations/watchers/primary-category-quick-edit-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  tests/integration/test-class-primary-term-admin.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
  tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
  tests/unit/integrations/watchers/primary-term-watcher-test.php
Labels: changelog: bugfix

#17081 P3-623 Add Premium badge to social templates forms
  admin/menu/class-replacevar-editor.php
  packages/components/src/Label.js
  packages/components/src/badges/badge.css
  packages/components/src/field-group/FieldGroup.js
  packages/components/src/image-select/ImageSelect.js
  packages/components/src/index.js
  packages/components/src/new-badge/NewBadge.js
  packages/components/src/new-badge/index.js
  packages/components/src/new-badge/new-badge.css
  packages/components/src/premium-badge/PremiumBadge.js
  packages/components/src/premium-badge/index.js
  packages/components/src/premium-badge/premium-badge.css
  packages/js/src/components/ImageSelectComponent.js
  packages/js/src/components/SettingsReplacementVariableEditor.js
  packages/js/src/components/SettingsReplacementVariableEditors.js
  packages/js/src/components/portals/ImageSelectPortal.js
  packages/js/src/components/portals/SettingsEditorPortal.js
  packages/js/src/initializers/search-appearance.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
  packages/replacement-variable-editor/src/SettingsSnippetEditor.js
  packages/replacement-variable-editor/src/SettingsSnippetEditorFields.js
  packages/replacement-variable-editor/src/shared.js
  packages/social-metadata-forms/tests/__snapshots__/ImageSelectTest.js.snap
  src/integrations/admin/social-templates-integration.php
Labels: changelog: non-user-facing

#17083 Add classes for styling in other implementations
  packages/replacement-variable-editor/src/Mention.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
Labels: changelog: non-user-facing

#17043 Improve list of non-passive exceptions for Turkish passive voice
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/isPassiveSentenceSpec.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/internal/nonPassiveExceptions.js
Labels: changelog: enhancement

#17053 Clean up Spanish stemmer
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/stem.js
Labels: changelog: enhancement

#17030 Use mb_substr instead of substr to avoid multibyte character truncation
  src/models/indexable.php
Labels: community-patch

#17087 P3-639 Allow to save an empty Homepage Social title and trigger the fallback.
  inc/options/class-wpseo-option-titles.php
Labels: changelog: non-user-facing

#17089 Escape attributes in Search Appearance tabs
  admin/views/tabs/metas/general.php
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/metas/paper-content/post_type/post-type.php
  composer.json
Labels: changelog: non-user-facing

#17088 P3-628 Fix Twitter image tags
  src/presentations/indexable-presentation.php
  tests/unit/presentations/indexable-presentation/twitter-image-test.php
Labels: changelog: non-user-facing

#17091 P3-638 Add image validation warnings for social templates
  admin/views/tabs/metas/paper-content/front-page-content.php
  admin/views/tabs/social/facebook.php
  packages/components/src/image-select/ImageSelect.js
  packages/components/src/image-select/image-select.css
  packages/js/src/components/ImageSelectComponent.js
  packages/js/src/components/portals/ImageSelectPortal.js
  packages/js/src/initializers/search-appearance.js
  packages/js/src/initializers/social-settings.js
  src/integrations/admin/social-templates-integration.php
Labels: changelog: non-user-facing

#17096 LINGO-748 implement norwegian readability feature flag
  packages/yoastseo/src/languageProcessing/languages/nb/Researcher.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
Labels: changelog: non-user-facing
