Repository Yoast/wordpress-seo, pull requests merged in 2021-01, with the labels that each got.

#16524 P1-311 Fix usage of deprecated get_user_locale
  inc/language-utils.php
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#16525 P1 242 elementor social replacevars update
  js/src/elementor/components/fills/ElementorFill.js
  js/src/elementor/components/modals/editorModals/FacebookPreviewModal.js
  js/src/elementor/components/modals/editorModals/TwitterPreviewModal.js
  js/src/elementor/containers/FacebookEditor.js
  js/src/elementor/containers/TwitterEditor.js
Labels: changelog: enhancement

#16335 Correctly implemented count_posts call in indexable-author-archive-presentation.php
  src/presentations/indexable-author-archive-presentation.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-author-archive-presentation/robots-test.php
Labels: changelog: bugfix, community-patch

#16531 Fix docs in watchers
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-date-archive-watcher.php
  src/integrations/watchers/indexable-home-page-watcher.php
  src/integrations/watchers/indexable-homeurl-watcher.php
  src/integrations/watchers/indexable-permalink-watcher.php
  src/integrations/watchers/indexable-post-meta-watcher.php
  src/integrations/watchers/indexable-post-type-archive-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-static-home-page-watcher.php
  src/integrations/watchers/indexable-system-page-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  src/integrations/watchers/option-titles-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  src/loadable-interface.php
  tests/unit/integrations/watchers/indexable-static-home-page-watcher-test.php
  tests/unit/integrations/watchers/primary-term-watcher-test.php
Labels: changelog: non-user-facing, component: innovation

#16532 Fixes CS warnings on docs in the generator unit tests.
  composer.json
  tests/unit/generators/breadcrumbs-generator-test.php
  tests/unit/generators/open-graph-image-generator-test.php
  tests/unit/generators/schema/article-test.php
  tests/unit/generators/schema/faq-test.php
  tests/unit/generators/schema/howto-test.php
  tests/unit/generators/twitter-image-generator-test.php
Labels: changelog: non-user-facing

#16533 Add Turkish to languages with morphology and function words
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#16536 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16537 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16538 Add push after gutenberg compatibility version change
  config/grunt/custom-tasks/sync-gutenberg-version.js
Labels: build tooling, changelog: non-user-facing

#16541 Fix enhanced slack sharing bug when reading time is null
  src/presentations/indexable-presentation.php
  src/surfaces/values/meta.php
Labels: changelog: bugfix

#16543 P2-252 - Added `@wordpress/date` as an external WP JavaScript package in WebPack.
  config/webpack/externals.js
Labels: changelog: non-user-facing

#16551 Avoid race condition in get_role_caps(), fixes #16108
  admin/class-yoast-notification.php
  tests/integration/notifications/test-class-yoast-notification-center.php
Labels: changelog: bugfix, community-patch

#16555 Add missing docs to tests for helpers
  tests/unit/helpers/blocks-helper-test.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/helpers/primary-term-helper-test.php
  tests/unit/helpers/schema/html-helper-test.php
  tests/unit/helpers/twitter/image-helper-test.php
Labels: changelog: non-user-facing

#16556 Add descriptions to health-ryte-check-test
  tests/unit/inc/health-check-ryte-test.php
Labels: changelog: non-user-facing

#16557 Fix CS warning in docs for Indexable Repository Test
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing

#16561 Replace `@inheritDoc` with `{@inheritDoc}`
  admin/class-helpscout.php
  composer.json
  src/deprecated/frontend/class-opengraph-oembed.php
  src/integrations/admin/cron-integration.php
  src/integrations/admin/link-count-columns-integration.php
  src/integrations/admin/migration-error-integration.php
  src/integrations/blocks/abstract-dynamic-block.php
  src/integrations/blocks/block-categories.php
  src/integrations/blocks/structured-data-blocks.php
  src/main.php
  tests/unit/presentations/abstract-presentation-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/routes/indexables-head-route-test.php
Labels: changelog: non-user-facing

#16553 Removed the release notification
  admin/class-admin-init.php
  admin/class-yoast-notification-center.php
  config/grunt/task-config/copy.js
  inc/class-upgrade.php
  release-info.json
Labels: changelog: other

#16570 Temporarily disable the breadcrumbs block.
  src/integrations/blocks/breadcrumbs-block.php
Labels: changelog: non-user-facing

#16571 P3 318 fix semrush timestamp tests
  tests/unit/config/semrush-client-test.php
Labels: changelog: non-user-facing

#16576 Made type definitions added to the container automatically public
  config/dependency-injection/inject-from-registry-pass.php
Labels: changelog: non-user-facing

#16577 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16544 P1-314 add alert dismissal
  src/actions/alert-dismissal-action.php
  src/helpers/user-helper.php
  src/routes/alert-dismissal-route.php
  tests/unit/actions/alert-dismissal-action-test.php
  tests/unit/helpers/user-helper-test.php
  tests/unit/routes/alert-dismissal-route-test.php
Labels: changelog: non-user-facing, component: innovation

#16565 Fix link classifier
  src/helpers/url-helper.php
  tests/unit/helpers/url-helper-test.php
Labels: changelog: bugfix

#16583 Replace the security checker
  .travis.yml
Labels: build tooling, changelog: non-user-facing

#16566 Fix relative link detection
  src/builders/indexable-link-builder.php
  tests/unit/builders/indexable-link-builder-test.php
Labels: changelog: bugfix

#16586 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16578 Make wpseo-form class output optional and add ids to Modal buttons
  admin/metabox/class-metabox-section-additional.php
  css/src/metabox.css
  js/src/components/SidebarButton.js
  js/src/components/modals/editorModals/EditorModal.js
  js/src/components/modals/editorModals/FacebookPreviewModal.js
  js/src/components/modals/editorModals/GooglePreviewModal.js
  js/src/components/modals/editorModals/TwitterPreviewModal.js
  js/src/elementor/components/modals/editorModals/FacebookPreviewModal.js
  js/src/elementor/components/modals/editorModals/GooglePreviewModal.js
  js/src/elementor/components/modals/editorModals/TwitterPreviewModal.js
Labels: changelog: non-user-facing

#16590 Bump JS packages
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#16593 Add matching priority to pre_get_document_title filter removal
  src/presenters/title-presenter.php
Labels: community-patch, has patch

#16575 Replace image uploads with new ImageSelect component
  admin/class-config.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  admin/views/tabs/social/facebook.php
  js/src/components/ImageSelectComponent.js
  js/src/components/portals/ImageSelectPortal.js
  js/src/containers/FacebookEditor.js
  js/src/containers/TwitterEditor.js
  js/src/editor-modules.js
  js/src/helpers/selectMedia.js
  js/src/initializers/search-appearance.js
  js/src/initializers/social-settings.js
  js/src/settings.js
Labels: UI change, changelog: enhancement

#16594 Breadcrumbs block + other breadcrumbs changes
  admin/views/tabs/metas/paper-content/breadcrumbs-content.php
  inc/options/class-wpseo-option-titles.php
  js/src/initializers/admin.js
  readme.txt
  src/conditionals/breadcrumbs-enabled-conditional.php
  src/integrations/blocks/breadcrumbs-block.php
  src/integrations/breadcrumbs-integration.php
  tests/unit/conditionals/breadcrumbs-enabled-conditional-test.php
  tests/unit/integrations/breadcrumbs-integration-test.php
Labels: UI change, changelog: enhancement

#16595 P3-338 Add ability to make all Yoast_Form elements disabled
  admin/class-yoast-form.php
  composer.json
  css/src/toggle-switch.css
Labels: changelog: non-user-facing

#16580 Replace deprecated SQL && operators with AND
  admin/class-bulk-editor-list-table.php
  admin/filters/class-cornerstone-filter.php
Labels: changelog: enhancement, community-patch, has patch

#16605 Added pagination support for WooCommerce shop pages.
  src/integrations/third-party/woocommerce.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
  tests/unit/integrations/third-party/woocommerce-test.php
Labels: changelog: bugfix

#16606 P3-349 Fix light switch toggle disabled style.
  css/src/toggle-switch.css
Labels: changelog: bugfix

#16608 Fix static class map in custom loader
  config/dependency-injection/custom-loader.php
Labels: changelog: non-user-facing
