Repository Yoast/wordpress-seo, pull requests merged in 2021-08, with the labels that each got.

#17300 Use non-product-page values on store blog assessors
  packages/yoastseo/spec/scoring/storeBlog/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storeBlog/seoAssessorSpec.js
  packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storeBlog/seoAssessor.js
Labels: changelog: non-user-facing

#17296 Create image alt tags assessment for product pages
  packages/yoastseo/spec/scoring/assessments/seo/ImageAltTagsAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17285 Adjust the sentence length score boundaries for product pages
  packages/yoastseo/spec/languageProcessing/languages/pl/ResearcherSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/sentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/src/languageProcessing/languages/ca/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/es/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/he/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/hu/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/it/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/pl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/pl/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/sentenceLength.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/sentenceLength.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: enhancement

#17305 P2-1177 prevent error during indexing
  src/builders/indexable-link-builder.php
Labels: changelog: non-user-facing

#17304 Added keys to sidebar items
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
Labels: changelog: non-user-facing

#17292 Add keyphrase length assessment for product pages
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/de/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/de/config/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/nl/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/keyphraseLength.js
  packages/yoastseo/src/languageProcessing/languages/sv/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/sv/config/keyphraseLength.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17309 Delete images assessment from related keyphrase assessors
  packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
Labels: changelog: non-user-facing

#17310 Add shortlinks to the Lists assessment
  packages/yoastseo/spec/scoring/assessments/readability/ListAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
Labels: changelog: enhancement

#17306 Change readability assessments into classes
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/assessments/readability/PassiveVoiceAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceBeginningsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TextPresenceAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TransitionWordsAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/passiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/sentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/textPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/transitionWordsAssessment.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
Labels: changelog: non-user-facing

#17311 Lingo 972 add assessors for blog pages and posts
  apps/content-analysis/src/analysis.worker.js
  packages/yoastseo/spec/scoring/storePostsAndPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
Labels: changelog: enhancement

#17312 Implement collection pages assessors
  apps/content-analysis/src/analysis.worker.js
  packages/yoastseo/spec/scoring/collectionPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/collectionPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js
Labels: changelog: enhancement

#17294 Don't delete transients when no indexables have been created
  src/actions/indexing/abstract-link-indexing-action.php
  src/actions/indexing/indexable-post-indexation-action.php
  src/actions/indexing/indexable-post-type-archive-indexation-action.php
  src/actions/indexing/indexable-term-indexation-action.php
  src/actions/indexing/post-link-indexing-action.php
  src/actions/indexing/term-link-indexing-action.php
  tests/unit/actions/indexing/indexable-post-indexation-action-test.php
  tests/unit/actions/indexing/indexable-post-type-archive-indexation-action-test.php
  tests/unit/actions/indexing/indexable-term-indexation-action-test.php
  tests/unit/actions/indexing/post-link-indexing-action-test.php
  tests/unit/actions/indexing/term-link-indexing-action-test.php
Labels: changelog: enhancement

#17297 Check if there are changes to Yoast notifications before updating
  admin/class-yoast-notification-center.php
Labels: changelog: non-user-facing, community-patch

#16707 14845 Remove media purge related stuff
  admin/class-admin-media-purge-notification.php
  admin/class-admin.php
  admin/tracking/class-tracking-settings-data.php
  admin/views/tabs/metas/paper-content/media-content.php
  inc/options/class-wpseo-option-titles.php
  tests/unit/admin/admin-features-test.php
Labels: changelog: non-user-facing, community-patch, technical-debt

#17317 Add keyphrase distribution to product-related assessors
  packages/yoastseo/spec/scoring/collectionPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
Labels: changelog: enhancement

#17316 Remove flesch reading ease assessment from the blog posts and pages a…
  packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js
Labels: changelog: non-user-facing

#17318 Adjust recommended text length values for non-cornerstone collections pages
  packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
Labels: changelog: enhancement

#17313 Updated message for recommended addons with dependencies
  admin/class-admin-init.php
  admin/class-suggested-plugins.php
Labels: changelog: other

#17308 Add Spanish verb stem modifications
  packages/yoastseo/spec/languageProcessing/helpers/regex/searchAndReplaceWithOneRegexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/checkVerbStemModificationsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/languageProcessing/helpers/regex/searchAndReplaceWithOneRegex.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/checkVerbStemModifications.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/stem.js
Labels: changelog: enhancement

#17320 Add shortlinks to assessors
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storeBlog/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storeBlog/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/collectionPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
  packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storeBlog/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
Labels: changelog: enhancement

#17314 Delete orphaned entries from Yoast tables with a scheduled action
  inc/class-upgrade.php
  src/integrations/cleanup-integration.php
  tests/unit/integrations/cleanup-integration-test.php
Labels: changelog: non-user-facing

#17334 Also set custom options when setting the custom assessors
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: enhancement

#17339 Fix bulk editor `Save all` button and column update
  admin/class-bulk-editor-list-table.php
Labels: community-patch, changelog: bugfix

#17337 Replace assessment shortlinks in product assessors with variables
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/relatedKeywordAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: enhancement

#17343 Use the event's target value instead of the event itself when the slug has changed.
  packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
Labels: changelog: non-user-facing

#17342 P2-1212 Revert 17297
  admin/class-yoast-notification-center.php
Labels: changelog: non-user-facing

#17331 Set isRelatedKeyphrase to true in related keyword assessor for keyphrase length assesment
  packages/yoastseo/spec/scoring/cornerstone/relatedKeywordAssessorSpec.js
  packages/yoastseo/src/scoring/cornerstone/relatedKeywordAssessor.js
Labels: changelog: non-user-facing

#17338 Add common irregular and stem changing Italian verbs
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/it/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/stem.js
Labels: changelog: enhancement

#17344 Fix autoloading priority in development builds
  wp-seo-main.php
Labels: changelog: non-user-facing

#17355 Test filters correctly and get rid of a few partial mocks along the way
  tests/unit/helpers/open-graph/image-helper-test.php
  tests/unit/helpers/twitter/image-helper-test.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
  tests/unit/presentations/indexable-presentation/open-graph-locale-test.php
Labels: changelog: non-user-facing

#17353 Create insert_many() function for bulked INSERT INTO queries
  lib/orm.php
Labels: changelog: non-user-facing

#17249 Add feature flag for Farsi language support
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/languageProcessing/researches/getLinkStatisticsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getWordFormsSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/src/helpers/getLanguagesWithWordFormSupport.js
  packages/yoastseo/src/languageProcessing/languages/fa/helpers/getStemmer.js
  packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  src/conditionals/farsi-support-conditional.php
  src/helpers/language-helper.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#17350 Add support to the ORM for float columns.
  lib/model.php
Labels: changelog: non-user-facing

#17352 Register the web worker to allow setting custom assessors in addons
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: enhancement

#17359 P2-1225 Add short descriptions in doc comments
  composer.json
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/surfaces/meta-surface-test.php
Labels: changelog: non-user-facing

#17358 Fix Lists assessment
  apps/content-analysis/src/analysis.worker.js
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
Labels: changelog: bugfix

#17362 Adds time-related words to English, Dutch, Indonesian, Russian and Spanish function words
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/es/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/id/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/nl/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/functionWords.js
Labels: changelog: enhancement

#17364 P2 1229 insert many dirty fields
  lib/orm.php
  tests/unit/doubles/lib/orm-double.php
  tests/unit/repositories/orm-test.php
Labels: changelog: non-user-facing

#17357 P2-1131 Only update necessary links
  src/builders/indexable-link-builder.php
  src/repositories/seo-links-repository.php
  tests/unit/builders/indexable-link-builder-test.php
Labels: changelog: enhancement

#17368 Hide SEO Optimization notification on non-prod sites
  src/integrations/admin/indexing-notification-integration.php
  tests/unit/integrations/admin/indexing-notification-integration-test.php
Labels: changelog: enhancement

#17369 Do483 grunt plugins task update
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/build-qa-changelog.js
  config/grunt/task-config/extract-extra-pr-texts-from-yoast-cli-md.js
  config/grunt/task-config/update-changelog-with-latest-pr-texts.js
  config/grunt/task-config/update-package-changelog.js
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#17370 P1-535 Update text colors, sizes and separators on Google preview
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: UI change, changelog: enhancement

#17376 Expand function words list for Farsi
  packages/yoastseo/src/languageProcessing/languages/fa/config/functionWords.js
Labels: changelog: enhancement

#17335 Add full text specs for Product pages and Collection pages
  packages/yoastseo/package.json
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.html
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.html
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.html
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.html
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.html
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.html
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/index.js
Labels: changelog: non-user-facing

#17380 Add Farsi transition words
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper3.js
  packages/yoastseo/spec/languageProcessing/languages/fa/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fa/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/fa/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/fa/config/twoPartTransitionWords.js
Labels: changelog: enhancement

#17384 Fix an incorrect feedback string for the keyphrase length assessment
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
Labels: changelog: non-user-facing

#17381 Replace images assessment `countVideos` value in product assessors with a variable
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: non-user-facing

#17383 Change recommended maximum sentence length for Farsi to 25 words
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper1.js
  packages/yoastseo/spec/languageProcessing/languages/fa/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fa/config/sentenceLength.js
Labels: changelog: enhancement

#17391 Make Consecutive sentence, Passive voice and Transition words assessments available for Farsi
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/languageProcessing/languages/fa/Researcher.js
Labels: changelog: non-user-facing
