Repository Yoast/wordpress-seo, pull requests merged in 2021-10, with the labels that each got.

#17467 Travis: update the PHP Security Checker
  .travis.yml
Labels: yoast cs/qa, changelog: non-user-facing

#17468 CS: various fixes
  admin/class-admin-asset-manager.php
  admin/class-admin-asset-seo-location.php
  admin/class-yoast-notification-center.php
  config/composer/unit-test-generator.php
  config/dependency-injection/renamed-classes.php
  lib/orm.php
  src/actions/indexing/indexable-post-indexation-action.php
  src/actions/indexing/indexable-term-indexation-action.php
  src/builders/indexable-builder.php
  src/builders/indexable-link-builder.php
  src/config/researcher-languages.php
  src/generators/schema/breadcrumb.php
  src/helpers/current-page-helper.php
  src/integrations/admin/social-templates-integration.php
  src/integrations/cleanup-integration.php
  src/presenters/admin/indexing-failed-notification-presenter.php
  src/schema-templates/cooking-time.block.php
  src/schema-templates/preparation-time.block.php
  src/schema-templates/recipe-ingredients.block.php
  src/schema-templates/recipe-instructions.block.php
  src/services/indexables/indexable-version-manager.php
  tests/unit/builders/indexable-builder-test.php
  tests/unit/integrations/feature-flag-integration-test.php
  tests/unit/presenters/admin/indexing-error-presenter-test.php
  wp-seo-main.php
Labels: yoast cs/qa, changelog: non-user-facing

#17469 QA: don't use FQN in non-namespaced files
  src/schema-templates/cooking-time.block.php
  src/schema-templates/preparation-time.block.php
  src/schema-templates/recipe-description.block.php
  src/schema-templates/recipe-ingredients.block.php
  src/schema-templates/recipe-instructions.block.php
  src/schema-templates/recipe.block.php
Labels: yoast cs/qa, changelog: non-user-facing

#17470 QA: fix incorrectly named test classes
  tests/integration/admin/test-class-admin-asset-dev-server-location.php
  tests/integration/admin/test-class-admin-asset-seo-location.php
  tests/integration/capabilities/test-class-capability-manager-factory.php
  tests/integration/capabilities/test-class-capability-manager.php
  tests/integration/capabilities/test-class-register-capabilities.php
  tests/integration/config-ui/test-class-configuration-components.php
  tests/integration/notifications/test-class-yoast-notification.php
  tests/integration/sitemaps/test-class-wpseo-author-sitemap-provider.php
  tests/integration/sitemaps/test-class-wpseo-sitemap-provider-overlap.php
Labels: yoast cs/qa, changelog: non-user-facing

#17472 Docs: various fixes
  admin/class-admin-asset-seo-location.php
  admin/class-suggested-plugins.php
  admin/views/class-yoast-feature-toggle.php
  config/dependency-injection/renamed-classes.php
  inc/class-addon-manager.php
  lib/orm.php
  src/builders/indexable-builder.php
  src/conditionals/admin/licenses-page-conditional.php
  src/conditionals/news-conditional.php
  src/generators/schema-generator.php
  src/helpers/asset-helper.php
  src/integrations/admin/workouts-integration.php
  src/integrations/front-end-integration.php
  src/presenters/abstract-indexable-presenter.php
  src/presenters/admin/indexing-failed-notification-presenter.php
  src/routes/yoast-head-rest-field.php
  src/services/indexables/indexable-version-manager.php
  src/surfaces/values/meta.php
  tests/unit/actions/addon-installation/addon-install-action-test.php
  tests/unit/doubles/lib/orm-double.php
  tests/unit/repositories/indexable-repository-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17474 QA; fix incorrect `@covers` tags
  tests/unit/actions/indexing/indexable-term-indexation-action-test.php
  tests/unit/admin/import/plugins/import-aioseo-v4-test.php
  tests/unit/config/indexable-builder-versions-test.php
  tests/unit/generators/schema/main-image-test.php
  tests/unit/main-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17475 QA: use fully qualified constants and functions
  src/actions/addon-installation/addon-activate-action.php
  src/actions/addon-installation/addon-install-action.php
  src/actions/indexing/abstract-indexing-action.php
  src/actions/indexing/indexable-post-indexation-action.php
  src/builders/indexable-link-builder.php
  src/conditionals/premium-inactive-conditional.php
  src/deprecated/src/conditionals/farsi-support-conditional.php
  src/deprecated/src/conditionals/norwegian-readability-conditional.php
  src/deprecated/src/integrations/third-party/elementor.php
  src/generators/schema/faq.php
  src/helpers/asset-helper.php
  src/helpers/language-helper.php
  src/helpers/post-helper.php
  src/helpers/url-helper.php
  src/integrations/admin/addon-installation/dialog-integration.php
  src/integrations/admin/addon-installation/installation-integration.php
  src/integrations/admin/fix-news-dependencies-integration.php
  src/integrations/admin/menu-badge-integration.php
  src/integrations/admin/social-templates-integration.php
  src/integrations/admin/workouts-integration.php
  src/integrations/cleanup-integration.php
  src/integrations/third-party/elementor.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  src/presenters/admin/indexing-error-presenter.php
  src/services/indexables/indexable-version-manager.php
  tests/unit/actions/addon-installation/addon-activate-action-test.php
  tests/unit/actions/addon-installation/addon-install-action-test.php
  tests/unit/actions/indexing/indexable-post-indexation-action-test.php
  tests/unit/actions/indexing/indexable-term-indexation-action-test.php
  tests/unit/admin/admin-asset-analysis-worker-location-test.php
  tests/unit/admin/metabox/metabox-editor-test.php
  tests/unit/integrations/admin/addon-installation/dialog-integration-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/main-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#17476 Composer: update to YoastCS 2.2.0
  composer.json
  composer.lock
  phpcs.xml.dist
  src/integrations/third-party/wpml.php
  src/integrations/xmlrpc.php
Labels: yoast cs/qa, changelog: non-user-facing

#17465 Add Greek sentence beginning exception
  packages/yoastseo/spec/languageProcessing/languages/el/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/src/languageProcessing/languages/el/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/el/config/firstWordExceptions.js
  packages/yoastseo/src/languageProcessing/researches/getSentenceBeginnings.js
Labels: changelog: non-user-facing

#17460 Add transition words assessment for Greek
  packages/yoastseo/spec/languageProcessing/languages/el/ResearcherSpec.js
  packages/yoastseo/src/languageProcessing/languages/el/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/el/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/el/config/twoPartTransitionWords.js
Labels: changelog: non-user-facing

#17481 [IM-1356] Fix the open graph presenter to sanitize and display types
  src/presenters/open-graph/image-presenter.php
  tests/unit/presenters/open-graph/image-presenter-test.php
Labels: changelog: non-user-facing

#17480 Fix bug in search page schema
  src/generators/schema/webpage.php
  tests/unit/generators/schema-generator-test.php
Labels: changelog: bugfix

#17486 Added AiOSEO V4 feature flag.
  admin/import/plugins/class-importers.php
  src/conditionals/aioseo-v4-importer-conditional.php
  tests/unit/admin/import/plugins/importers-test.php
Labels: changelog: non-user-facing

#17479 Add filtering for schema article types
  inc/class-wpseo-meta.php
  src/config/schema-types.php
  src/context/meta-tags-context.php
Labels: changelog: non-user-facing
