Repository Yoast/wordpress-seo, pull requests merged in 2022-08, with the labels that each got.

#18763 Restyle Indexables Page
  packages/js/src/indexables-page.js
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/indexables-page.js
  tailwind.config.js
Labels: changelog: non-user-facing

#18750 PC-313 Deprecate the Ryte integrations
  admin/views/class-yoast-integration-toggles.php
  css/src/dashboard.css
  inc/class-upgrade.php
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  packages/js/images/ryte-logo.svg
  packages/js/src/integrations-page/integrations-grid.js
  src/actions/integrations-action.php
  src/deprecated/admin/ryte/class-ryte-option.php
  src/deprecated/admin/ryte/class-ryte-request.php
  src/deprecated/src/integrations/admin/ryte-integration.php
  src/deprecated/src/services/health-check/ryte-check.php
  src/deprecated/src/services/health-check/ryte-reports.php
  src/deprecated/src/services/health-check/ryte-runner.php
  src/integrations/admin/integrations-page.php
  tests/integration/inc/options/test-class-wpseo-option-wpseo.php
  tests/integration/ryte/test-class-ryte-option.php
  tests/integration/ryte/test-class-ryte-request.php
  tests/integration/ryte/test-class-ryte.php
  tests/unit/admin/views/integration-toggles-test.php
  tests/unit/services/health-check/ryte-check-test.php
  tests/unit/services/health-check/ryte-reports-test.php
  tests/unit/services/health-check/ryte-runner-test.php
Labels: changelog: other

#18744 PC-46 Add the search engines discouraged notice to the notification dashboard
  admin/class-admin-init.php
  packages/js/src/admin-global.js
  src/integrations/watchers/search-engines-discouraged-watcher.php
  src/presenters/admin/search-engines-discouraged-presenter.php
  tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
  tests/unit/presenters/admin/search-engines-discouraged-presenter-test.php
Labels: changelog: other

#18717 Introduce the filter `wpseo_sitemap_post_type_first_links`
  inc/sitemaps/class-post-type-sitemap-provider.php
Labels: community-patch

#18749 PC-318 - Fixes a bug where clicking on the SEO link inside of the Publish box in classic editor did not always scroll the SEO analysis into view
  packages/js/src/ui/publishBox.js
Labels: changelog: bugfix

#18767 Pc 344 fix type error classic editor replacement variables search
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/src/containers/SnippetEditor.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/actions/postId.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/reducers/postId.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/postId.js
Labels: changelog: non-user-facing

#18770 PC-351 Fix automated tests failing because of missing Ryte class
  tests/integration/doubles/onpage-option-mock.php
  tests/integration/doubles/wpseo-onpage-double.php
  tests/integration/doubles/wpseo-onpage-request-double.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#18768 Frontend inspector: fix inconsistent color indicators
  admin/class-meta-columns.php
  admin/taxonomy/class-taxonomy-columns.php
  css/src/adminbar.css
  inc/class-wpseo-admin-bar-menu.php
  inc/class-wpseo-utils.php
  packages/js/src/components/contentAnalysis/mapResults.js
  packages/js/src/ui/adminBar.js
  src/helpers/robots-helper.php
  src/helpers/score-icon-helper.php
  src/presenters/score-icon-presenter.php
  tests/integration/test-class-wpseo-utils.php
  tests/unit/helpers/robots-helper-test.php
  tests/unit/helpers/score-icon-helper-test.php
  tests/unit/presenters/score-icon-presenter-test.php
Labels: UI change, changelog: bugfix

#18774 Lib\Model::__debugInfo(): work-around for Mockery
  lib/model.php
Labels: yoast cs/qa, changelog: non-user-facing

#18776 Memoize the find custom fields function to prevent duplicate requests
  packages/js/src/containers/SnippetEditor.js
  packages/js/tests/containers/SnippetEditor.test.js
Labels: changelog: non-user-facing

#18779 Fix the wrong color of SEO/Readability scores indicators on post edit screen
  packages/js/src/components/contentAnalysis/mapResults.js
Labels: changelog: non-user-facing

#18781 Inclusive language: show only one feedback string for 'Third World country'
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
Labels: innovation, changelog: non-user-facing

#18780 PC-362 fix tokenizing quotation
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
Labels: changelog: bugfix, Shopify

#18721 Enable SKU assessment in Woo
  packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProductSKUDataSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/languageProcessing/researches/getProductIdentifierData.js
  packages/yoastseo/src/languageProcessing/researches/getProductSKUData.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: enhancement

#18784 QA-3613 revert performance fix
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  inc/class-wpseo-custom-fields.php
  packages/js/src/containers/SnippetEditor.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/actions/postId.js
  packages/js/src/redux/actions/snippetEditor.js
  packages/js/src/redux/controls/dismissedAlerts.js
  packages/js/src/redux/controls/index.js
  packages/js/src/redux/controls/snippetEditor.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/reducers/postId.js
  packages/js/src/redux/reducers/snippetEditor.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/postId.js
  packages/js/tests/containers/SnippetEditor.test.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
  src/integrations/third-party/elementor.php
  src/routes/meta-search-route.php
Labels: changelog: non-user-facing

#18786 Fixes an error when the note_when_disabled attribute is missing on a feature toggle.
  admin/class-yoast-form.php
Labels: changelog: non-user-facing

#18785 Improve inclusive language feedback for green bullet condition
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
Labels: innovation, UI change, changelog: non-user-facing

#18772 PC-325-add-notification-for-the-inclusive-language-feature
  admin/class-admin-init.php
  admin/class-inclusive-language-notice.php
  admin/class-yoast-notification.php
Labels: innovation, UI change, changelog: non-user-facing

#18793 PC-375 - When the google preview tab is closed a console error appears and the actionable buttons dont work
  packages/js/src/components/contentAnalysis/Results.js
Labels: changelog: non-user-facing

#18794 Composer: update PHPCS
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#18795 CS/QA: use fully qualified global function calls in namespaced files
  src/actions/configuration/first-time-configuration-action.php
  src/builders/indexable-post-builder.php
  src/config/oauth-client.php
  src/context/meta-tags-context.php
  src/deprecated/src/integrations/admin/ryte-integration.php
  src/deprecated/src/services/health-check/ryte-check.php
  src/deprecated/src/services/health-check/ryte-reports.php
  src/deprecated/src/services/health-check/ryte-runner.php
  src/generators/schema/webpage.php
  src/helpers/curl-helper.php
  src/helpers/score-icon-helper.php
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/admin/first-time-configuration-integration.php
  src/integrations/admin/import-integration.php
  src/integrations/admin/redirects-integration.php
  src/integrations/admin/social-profiles-helper.php
  src/integrations/front-end/redirects.php
  src/integrations/settings-integration.php
  src/presenters/admin/search-engines-discouraged-presenter.php
  src/services/health-check/curl-check.php
  src/services/health-check/curl-reports.php
  src/services/health-check/curl-runner.php
  src/services/health-check/default-tagline-check.php
  src/services/health-check/links-table-reports.php
  src/services/health-check/links-table-runner.php
  src/services/health-check/page-comments-check.php
  src/services/health-check/page-comments-reports.php
  src/services/health-check/page-comments-runner.php
  src/services/health-check/postname-permalink-check.php
  src/services/health-check/postname-permalink-reports.php
  src/services/health-check/postname-permalink-runner.php
Labels: yoast cs/qa, changelog: non-user-facing

#18796 QA: clean up use statements
  src/actions/importing/aioseo/aioseo-validate-data-action.php
  src/generators/schema/author.php
  src/helpers/aioseo-helper.php
  src/helpers/post-type-helper.php
  src/helpers/schema/image-helper.php
  src/integrations/admin/first-time-configuration-integration.php
  src/integrations/admin/old-configuration-integration.php
  src/integrations/admin/redirects-integration.php
  src/integrations/admin/workouts-integration.php
  src/integrations/front-end/feed-improvements.php
  src/integrations/front-end/robots-txt-integration.php
  src/integrations/third-party/coauthors-plus.php
  src/integrations/third-party/elementor.php
  src/integrations/third-party/woocommerce-post-edit.php
  src/integrations/third-party/wordproof.php
  src/presenters/meta-author-presenter.php
  tests/unit/actions/importing/aioseo-validate-data-action-test.php
  tests/unit/generators/schema/third-party/coauthor-test.php
  tests/unit/helpers/schema/image-helper-test.php
  tests/unit/helpers/score-icon-helper-test.php
  tests/unit/integrations/admin/crawl-settings-integration-test.php
  tests/unit/presenters/admin/search-engines-discouraged-presenter-test.php
  tests/unit/presenters/meta-author-presenter-test.php
  tests/unit/presenters/score-icon-presenter-test.php
  tests/unit/services/health-check/curl-check-test.php
  tests/unit/services/health-check/curl-runner-test.php
  tests/unit/services/health-check/links-table-reports-test.php
  tests/unit/services/health-check/links-table-runner-test.php
  tests/unit/services/health-check/postname-permalink-reports-test.php
  tests/unit/services/health-check/reports-trait-test.php
  tests/unit/services/importing/aioseo-robots-provider-service-test.php
  tests/unit/services/importing/aioseo-social-images-provider-service-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18797 CS: clean up after merges
  admin/class-yoast-form.php
  inc/class-wpseo-admin-bar-menu.php
  src/actions/configuration/first-time-configuration-action.php
  src/deprecated/src/actions/configuration/configuration-workout-action.php
  src/deprecated/src/routes/configuration-workout-route.php
  src/deprecated/src/services/health-check/ryte-reports.php
  src/integrations/front-end/robots-txt-integration.php
  src/services/health-check/curl-reports.php
  src/services/health-check/default-tagline-reports.php
  src/services/health-check/links-table-reports.php
  src/services/health-check/page-comments-reports.php
  src/services/health-check/postname-permalink-reports.php
  tests/unit/doubles/services/health-check/reports-trait-double.php
  tests/unit/integrations/third-party/woocommerce-post-edit-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18798 QA: fix incorrect output escaping
  inc/class-addon-manager.php
  src/schema-templates/cooking-time.block.php
  src/schema-templates/preparation-time.block.php
Labels: yoast cs/qa, changelog: bugfix

#18799 QA: fix some incorrect output escaping
  admin/class-yoast-form.php
Labels: yoast cs/qa, changelog: bugfix

#18800 QA: no reserved keyword as function parameter names
  src/builders/indexable-post-builder.php
  src/integrations/front-end/robots-txt-integration.php
  src/integrations/third-party/wordproof.php
  src/presenters/score-icon-presenter.php
  tests/unit/presenters/score-icon-presenter-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18801 QA: use `add_action()` when hooking into actions
  inc/sitemaps/class-post-type-sitemap-provider.php
  src/integrations/admin/link-count-columns-integration.php
Labels: yoast cs/qa, changelog: non-user-facing

#18802 CS: various doc fixes
  admin/class-database-proxy.php
  admin/class-inclusive-language-notice.php
  inc/options/class-wpseo-option-wpseo.php
  inc/sitemaps/class-sitemap-image-parser.php
  src/actions/configuration/first-time-configuration-action.php
  src/actions/importing/aioseo/aioseo-cleanup-action.php
  src/actions/importing/aioseo/aioseo-validate-data-action.php
  src/config/oauth-client.php
  src/config/wordproof-app-config.php
  src/deprecated/admin/ryte/class-ryte-option.php
  src/deprecated/src/services/health-check/ryte-check.php
  src/deprecated/src/services/health-check/ryte-reports.php
  src/deprecated/src/services/health-check/ryte-runner.php
  src/generators/schema/third-party/coauthor.php
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/admin/deactivated-premium-integration.php
  src/integrations/admin/first-time-configuration-integration.php
  src/integrations/admin/social-profiles-helper.php
  src/integrations/front-end/redirects.php
  src/integrations/front-end/robots-txt-integration.php
  src/integrations/settings-integration.php
  src/integrations/third-party/wordproof-integration-toggle.php
  src/integrations/third-party/wordproof.php
  src/services/health-check/curl-check.php
  src/services/health-check/curl-reports.php
  src/services/health-check/curl-runner.php
  src/services/health-check/default-tagline-check.php
  src/services/health-check/default-tagline-reports.php
  src/services/health-check/links-table-check.php
  src/services/health-check/links-table-reports.php
  src/services/health-check/links-table-runner.php
  src/services/health-check/myyoast-api-request-factory.php
  src/services/health-check/page-comments-check.php
  src/services/health-check/page-comments-reports.php
  src/services/health-check/postname-permalink-check.php
  src/services/health-check/postname-permalink-reports.php
  tests/unit/actions/configuration/first-time-configuration-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-validate-data-action-test.php
  tests/unit/config/indexable-builder-versions-test.php
  tests/unit/generators/schema/third-party/coauthor-test.php
  tests/unit/helpers/aioseo-helper-test.php
  tests/unit/helpers/score-icon-helper-test.php
  tests/unit/helpers/url-helper-test.php
  tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
  tests/unit/routes/first-time-configuration-route-test.php
  tests/unit/services/health-check/curl-check-test.php
  tests/unit/services/health-check/curl-reports-test.php
  tests/unit/services/health-check/myyoast-api-request-factory-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18803 CS/QA: use fully qualified global constants in namespaced files
  src/actions/configuration/first-time-configuration-action.php
  src/integrations/admin/integrations-page.php
  src/integrations/admin/redirects-integration.php
  src/integrations/third-party/wordproof.php
  src/services/health-check/links-table-runner.php
  tests/unit/services/health-check/links-table-runner-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18804 GH Actions/test: clean up script after dropping support for WP 5.9
  .github/workflows/integrationtest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#18805 PHPCS/ESlint: update thresholds
  composer.json
  packages/analysis-report/package.json
  packages/components/package.json
  packages/yoast-components/package.json
Labels: yoast cs/qa, changelog: non-user-facing

#18806 Add dependabot configuration file
  .github/dependabot.yml
Labels: yoast cs/qa, changelog: non-user-facing

#18787 Fixes and improvements for inclusive language feedback
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: innovation, changelog: non-user-facing

#18811 Check if Google preview collapsible is closed before clicking on it.
  packages/js/src/components/contentAnalysis/Results.js
Labels: changelog: non-user-facing

#18814 PHP 8.2 | Elementor_Exclude_Post_Types: fix for partially supported callback
  src/deprecated/src/integrations/third-party/elementor.php
Labels: yoast cs/qa, changelog: other

#18815 PHP 8.2 | Yoast_Notification_Center: bugfix for partially supported callback
  admin/class-yoast-notification-center.php
Labels: yoast cs/qa, changelog: other

#18816 PHP 8.2 | Various Tests: explicitly declare all properties
  tests/unit/builders/indexable-home-page-builder-test.php
  tests/unit/conditionals/estimated-reading-time-conditional-test.php
  tests/unit/helpers/wpdb-helper-test.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presenters/meta-author-presenter-test.php
  tests/unit/services/importing/importable-detector-service-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18817 PHP 8.2 | Classes_Surface: explicitly declare all properties
  src/surfaces/classes-surface.php
Labels: yoast cs/qa, changelog: other

#18818 PHP 8.2 | Import_Cursor_Helper: explicitly declare all properties
  src/helpers/import-cursor-helper.php
Labels: yoast cs/qa, changelog: other

#18819 PHP 8.2 | Tests: bug fix - typo in property name x 2
  tests/unit/presentations/indexable-static-posts-page-presentation/presentation-instance-builder-trait.php
  tests/unit/services/importing/aioseo-robots-transformer-service-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#18782 Improve feedback strings for SKU and Product identifier assessments
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: non-user-facing

#18788 PC-330-implement-shortlink-and-learn-more-links
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
Labels: innovation, changelog: non-user-facing

#18813 PC-371-inclusive-language-is-not-aligned-with-default-editor-in-pre-publishing-box
  packages/js/src/analysis/PostDataCollector.js
  packages/js/src/initializers/post-scraper.js
Labels: innovation, changelog: bugfix

#18789 PC-368 Update copy in the integrations page.
  packages/js/src/integrations-page/integrations-grid.js
Labels: UI change, changelog: non-user-facing

#18823 PC-385 - Do not show SKU or product identifier assessments when a simple product does not have a regular price
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: non-user-facing

#18820 PHP 8.2 | Indexable_*_Presentation: explicitly declare all properties
  src/presentations/archive-adjacent-trait.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-home-page-presentation.php
  src/presentations/indexable-post-type-archive-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/unit/presentations/archive-adjacent-test.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-date-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-home-page-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-static-posts-page-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/presentation-instance-dependencies-trait.php
Labels: yoast cs/qa, changelog: other

#18756 Distinguish between users that are able to see the lists in the Indexables page and users that are not
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-wpseo.php
  packages/js/images/icon-search.svg
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/configuration-indexation.js
  packages/js/src/indexables-page.js
  packages/js/src/indexables-page/components/indexables-context-provider.js
  packages/js/src/indexables-page/components/indexation-view.js
  packages/js/src/indexables-page/components/indexation.js
  packages/js/src/indexables-page/components/not-enough-analysed-content.js
  packages/js/src/indexables-page/components/not-enough-content.js
  packages/js/src/indexables-page/components/simple-card.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
  packages/js/src/indexation.js
  src/actions/indexables-page-action.php
  src/helpers/indexables-page-helper.php
  src/integrations/admin/indexables-page-integration.php
  src/routes/indexables-page-route.php
  tests/unit/actions/indexables-page-action-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: changelog: non-user-facing

#18792 Fix custom field replacement variables in social inputs
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  inc/class-wpseo-custom-fields.php
  packages/js/src/components/social/SocialForm.js
  packages/js/src/containers/FacebookEditor.js
  packages/js/src/containers/SnippetEditor.js
  packages/js/src/containers/TwitterEditor.js
  packages/js/src/helpers/getMemoizedFindCustomFields.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/actions/postId.js
  packages/js/src/redux/actions/snippetEditor.js
  packages/js/src/redux/controls/dismissedAlerts.js
  packages/js/src/redux/controls/index.js
  packages/js/src/redux/controls/snippetEditor.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/reducers/postId.js
  packages/js/src/redux/reducers/snippetEditor.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/postId.js
  packages/js/tests/containers/SnippetEditor.test.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
  src/integrations/third-party/elementor.php
  src/routes/meta-search-route.php
Labels: changelog: enhancement

#18831 Inclusive language cherrypick missing commits
  admin/class-yoast-form.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/tabs/network/features.php
  inc/class-upgrade.php
  inc/options/class-wpseo-option-ms.php
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
  src/helpers/language-helper.php
  tests/unit/admin/views/feature-toggles-test.php
  tests/unit/helpers/language-helper-test.php
Labels: changelog: non-user-facing

#18833 Fix error appearing when building the plugin
  packages/yoastseo/src/scoring/assessments/index.js
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#18832 PC-395-wpseo-variable-products-show-wrong-feedback-when-variants-are-deleted-in-woo
  packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProductSKUDataSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/languageProcessing/researches/getProductIdentifierData.js
  packages/yoastseo/src/languageProcessing/researches/getProductSKUData.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: non-user-facing

#18835 Make the inclusive language green bullet feedback link open in new tab
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
Labels: changelog: non-user-facing

#18834 Fix the wrong position of the ‘Track SEO performance’ tab
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/elementor/components/fills/ElementorFill.js
Labels: changelog: non-user-facing

#18775 PC-335 Fix image requests in elementor
  packages/js/src/helpers/firstImageUrlInContent.js
Labels: changelog: non-user-facing

#18844 PC-426 - Only show notification when Premium 19.2-RC1 or above is installed.
  admin/class-inclusive-language-notice.php
Labels: changelog: non-user-facing

#18843 Fix scrolling issue when many custom fields exist in the replacementvariable editor
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
Labels: changelog: non-user-facing

#18839 Do not add feature toggle if current installed Premium version does not support feature.
  admin/views/class-yoast-feature-toggle.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/network/features.php
Labels: changelog: non-user-facing

#18850 Do not redirect to the installation success pages on admin ajax calls
  src/integrations/admin/installation-success-integration.php
Labels: changelog: bugfix

#18826 PC-119 Change sidebar ad in yoast seo to the yoast.com sidebar ad
  admin/class-yoast-form.php
  admin/views/sidebar.php
  css/src/yst_plugin_tools.css
  packages/js/images/logo-g2-white.svg
  packages/js/images/star-rating-half.svg
  packages/js/images/star-rating-star.svg
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: other

#18851 Show alert informing user of disabled features
  packages/js/src/indexables-page/components/indexables-links-card.js
  packages/js/src/indexables-page/components/indexables-score-card.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
  src/actions/indexables-page-action.php
Labels: changelog: non-user-facing

#18852 Pc 435 implement lowest number of links assessment
  packages/js/src/indexables-page/assessment-functions.js
  packages/js/src/indexables-page/components/indexables-links-card.js
  packages/js/src/indexables-page/components/indexables-score-card.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
Labels: changelog: non-user-facing

#18848 Includes text title in inclusive language analysis
  packages/js/src/analysis/classicEditorData.js
  packages/js/src/analysis/collectAnalysisData.js
  packages/js/src/initializers/analysis.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/values/Paper.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#18837 Add missing shortlinks on inclusive language feature page
  admin/views/class-yoast-feature-toggles.php
Labels: changelog: non-user-facing

#18856 Pc 443 fix homepage social image validation
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/helpers/validation.js
  packages/js/src/settings/store/schema.js
  packages/js/src/settings/utils/index.js
Labels: changelog: non-user-facing

#18855 Add useMediaQuery hook to ui-library, use it to define single and double column view
  packages/js/src/indexables-page/components/indexables-links-card.js
  packages/js/src/indexables-page/components/indexables-score-card.js
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
  packages/ui-library/src/hooks/index.js
  packages/ui-library/src/hooks/use-media-query.js
  tests/unit/actions/indexables-page-action-test.php
Labels: changelog: non-user-facing

#18853 Make inclusive language feature enabled by default in Network admin
  inc/options/class-wpseo-option-ms.php
Labels: changelog: non-user-facing

#18860 Only posts and pages in the indexables lists
  src/actions/indexables-page-action.php
  tests/unit/actions/indexables-page-action-test.php
Labels: changelog: non-user-facing

#18859 Fix undefined url variable and translation of h3 title
  src/presenters/admin/sidebar-presenter.php
Labels: changelog: non-user-facing

#18847 Add ignore for sitemaps of a custom post type that have no posts
  inc/sitemaps/class-post-type-sitemap-provider.php
  tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
Labels: changelog: other

#18857 PC-436 - Inclusive language with wpml in the elementor editor
  admin/formatter/class-metabox-formatter.php
  packages/js/src/analysis/isMultilingualPluginActive.js
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  src/conditionals/third-party/polylang-conditional.php
  src/conditionals/third-party/translatepress-conditional.php
Labels: changelog: non-user-facing

#18863 PC-456 - Increase width of feature toggle labels.
  css/src/toggle-switch.css
Labels: changelog: non-user-facing

#18862 PC-413 Adapt inclusive language notification for subsites with feature disabled by admin
  admin/class-inclusive-language-notice.php
Labels: changelog: enhancement

#18866 PC-460 - Overwrite network feature toggle read more link with its premium version if it is a premium feature.
  admin/views/tabs/network/features.php
Labels: changelog: non-user-facing

#18865 Pc 457 add a filter on post sub types
  packages/js/src/indexables-page/components/not-enough-analysed-content.js
  src/actions/indexables-page-action.php
Labels: changelog: non-user-facing

#18871 Add support for composer/installers v1 and v2
  .github/workflows/integrationtest.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  composer.json
  composer.lock
Labels: changelog: non-user-facing

#18858 Revert label encoding on yoast form
  admin/class-yoast-form.php
Labels: changelog: non-user-facing

#18869 Simplify but uglify the render function of indexables page
  packages/js/src/indexables-page/assessment-functions.js
  packages/js/src/indexables-page/components/indexables-links-card.js
  packages/js/src/indexables-page/components/indexables-score-card.js
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/components/not-enough-analysed-content.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
Labels: changelog: non-user-facing

#18872 Fix typo in homepage social image preload
  packages/js/src/settings/initialize.js
Labels: changelog: non-user-facing

#18874 PC-468 - Link in inclusive language notification now opens in a new tab.
  admin/class-inclusive-language-notice.php
Labels: changelog: non-user-facing

#18875 PC-467 inclusive language tab is shown after downgrade
  admin/metabox/class-metabox-analysis-inclusive-language.php
Labels: changelog: non-user-facing

#18880 Use wp_filesize instead of filesize
  inc/class-wpseo-image-utils.php
Labels: changelog: bugfix

#18870 Remove 'new' badge from all wordproof toggles.
  packages/js/src/components/WordProofTimestampToggle.js
Labels: UI change, changelog: other

#18878 Pc 461 track state
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-wpseo.php
  src/actions/indexables-page-action.php
  tests/unit/actions/indexables-page-action-test.php
Labels: changelog: non-user-facing

#18877 Bypass Not Enough (Analyzed) Content screens when features are disabled
  packages/js/images/icon-adjustments.svg
  packages/js/src/indexables-page/components/all-features-disabled.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
Labels: changelog: non-user-facing

#18884 Select only columns that are used for indexables
  src/actions/indexables-page-action.php
  tests/unit/actions/indexables-page-action-test.php
Labels: changelog: non-user-facing

#18868 Make di container more robust
  src/loader.php
  tests/unit/loader-test.php
Labels: changelog: non-user-facing

#18891 PC 484 manage indexing errors
  css/src/admin-global.css
  packages/js/src/indexables-page/components/indexation.js
  packages/js/src/indexables-page/components/indexing-error.js
  src/integrations/admin/indexables-page-integration.php
Labels: changelog: non-user-facing

#18897 Indexables page: add undo hide for all indexables
  packages/js/src/indexables-page/indexables-page.js
  src/actions/indexables-page-action.php
  src/helpers/indexables-page-helper.php
  src/routes/indexables-page-route.php
  tests/unit/actions/indexables-page-action-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: changelog: non-user-facing

#18890 Pc 478 use stars in mostly linked table
  packages/js/src/indexables-page/assessment-functions.js
  packages/js/src/indexables-page/indexables-page.js
Labels: changelog: non-user-facing

#18889 Add error alert when list fetching fails
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/components/not-enough-content.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
  src/routes/indexables-page-route.php
Labels: changelog: non-user-facing

#18899 Removed duplicated WooCommerce code
  src/integrations/third-party/woocommerce.php
  tests/unit/integrations/third-party/woocommerce-test.php
Labels: changelog: non-user-facing

#18900 Pc 496 implement UI feedbacks
  packages/js/src/indexables-page/components/indexable-title-link.js
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/components/not-enough-analysed-content.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
Labels: changelog: non-user-facing

#18901 Enhance User Experience with separate restoring per indexables card
  css/src/notifications.css
  packages/js/src/indexables-page/components/indexable-title-link.js
  packages/js/src/indexables-page/components/indexables-card-options.js
  packages/js/src/indexables-page/components/indexables-card.js
  packages/js/src/indexables-page/indexables-page.js
Labels: changelog: non-user-facing

#18902 Add shortlinks
  packages/js/src/indexables-page/components/not-enough-content.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
  src/integrations/admin/indexables-page-integration.php
Labels: changelog: non-user-facing

#18904 PC 500 Make SKU and product identifier assessments price independent
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: non-user-facing

#18660 Create the indexables page
  admin/class-admin-asset-manager.php
  admin/tracking/class-tracking-settings-data.php
  admin/views/tabs/dashboard/dashboard.php
  config/webpack/paths.js
  css/src/admin-global.css
  css/src/notifications.css
  inc/options/class-wpseo-option-wpseo.php
  packages/js/images/icon-adjustments.svg
  packages/js/images/icon-search.svg
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/configuration-indexation.js
  packages/js/src/indexables-page.js
  packages/js/src/indexables-page/assessment-functions.js
  packages/js/src/indexables-page/components/all-features-disabled.js
  packages/js/src/indexables-page/components/indexable-title-link.js
  packages/js/src/indexables-page/components/indexables-card-options.js
  packages/js/src/indexables-page/components/indexables-card.js
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/components/indexation-view.js
  packages/js/src/indexables-page/components/indexation.js
  packages/js/src/indexables-page/components/indexing-error.js
  packages/js/src/indexables-page/components/not-enough-analysed-content.js
  packages/js/src/indexables-page/components/not-enough-content.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
  packages/js/src/indexation.js
  packages/ui-library/src/hooks/index.js
  packages/ui-library/src/hooks/use-media-query.js
  src/actions/indexables-page-action.php
  src/helpers/indexables-page-helper.php
  src/helpers/post-type-helper.php
  src/integrations/admin/indexables-page-integration.php
  src/routes/indexables-page-route.php
  tailwind.config.js
  tests/unit/actions/indexables-page-action-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: UI change, changelog: enhancement

#17442 Support taxonomies with default noindex in sitemap
  inc/sitemaps/class-taxonomy-sitemap-provider.php
Labels: community-patch, changelog: enhancement

#18553 Update ajax.php
  admin/ajax.php
Labels: community-patch, changelog: non-user-facing

#18854 Add helper for creating robots.txt file content
  config/dependency-injection/services.php
  css/src/admin-global.css
  inc/options/class-wpseo-option-wpseo.php
  src/helpers/robots-txt-helper.php
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/front-end/robots-txt-integration.php
  src/presenters/robots-txt-presenter.php
  src/values/robots/directive.php
  src/values/robots/user-agent-list.php
  src/values/robots/user-agent.php
  tests/unit/helpers/robots-txt-helper-test.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
  tests/unit/presenters/robots-txt-presenter-test.php
Labels: changelog: other

#18867 Pc 13 add support for blocking site search via robots txt
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: other

#18905 Do not show SKU assessment when we cannot retrieve SKU
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: non-user-facing

#18836 Don't load Yoast SEO on the login screen
  wp-seo-main.php
Labels: changelog: enhancement

#18906 PC-505 fix SEO/Readability when image is added to content in Classic Editor
  packages/js/src/analysis/classicEditorData.js
Labels: changelog: non-user-facing

#18908 Disable SKU assessment when variant SKU cannot be detected
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
Labels: changelog: non-user-facing

#18912 Allow adding submenu items in the admin bar via action
  inc/class-wpseo-admin-bar-menu.php
  inc/class-wpseo-meta.php
Labels: changelog: bugfix

#18913 PC-516 Add filters for the social templates in the metabox
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
Labels: changelog: enhancement

#18915 PC-518 Add filters for the keyphrases collected by Wincher
  src/actions/wincher/wincher-keyphrases-action.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
Labels: changelog: enhancement

#18919 PC-525 move WP-CLI redirect commands init to Premium
  inc/wpseo-functions-deprecated.php
  wp-seo-main.php
Labels: changelog: other

#18917 Add filter for related keyphrases
  admin/formatter/class-post-metabox-formatter.php
  inc/class-wpseo-meta.php
Labels: changelog: bugfix

#18923 Fix tests and CS on hotfix branch
  packages/js/src/analysis/PostDataCollector.js
  packages/js/src/analysis/TermDataCollector.js
  packages/js/tests/containers/mockSelectors.js
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-root-factory-1-snap.png
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/includesConsecutiveWordsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/includesWordsAtPositionSpec.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing
