Repository Yoast/wordpress-seo, pull requests merged in 2022-11, with the labels that each got.

#19109 Fix broken url
  admin/views/tabs/dashboard/webmaster-tools.php
Labels: community-patch

#19111 Change bold 'get' in sidebar ad
  packages/js/src/settings/components/sidebar-recommendations.js
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: non-user-facing

#19112 Pc 927 revert link suggestions upsell
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/link-suggestion.js
  packages/js/src/components/link-suggestions.js
  packages/js/src/editor-modules.js
  packages/js/src/elementor/components/fills/ElementorFill.js
Labels: changelog: reverted

#19113 Filter admin tracking data for Local SEO
  admin/tracking/class-tracking-addon-data.php
Labels: changelog: non-user-facing

#18773 PC-167 Add highlighting for subheadings distribution and new feedback string
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/src/ContentAnalysis.js
  packages/js/src/components/contentAnalysis/Results.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/html/getSubheadingTextsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getSubheadingTextLengthSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/getSubheadingTexts.js
  packages/yoastseo/src/languageProcessing/researches/getSubheadingTextLengths.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/values/Mark.js
Labels: changelog: enhancement, Shopify

#19114 Improve consistency with indexable builders
  inc/class-upgrade.php
  src/integrations/cleanup-integration.php
  tests/unit/integrations/cleanup-integration-test.php
Labels: changelog: non-user-facing

#19110 Remove Zapier upsell
  admin/class-expose-shortlinks.php
  packages/js/src/components/PostPublishZapierUpsell.js
  packages/js/src/initializers/block-editor-integration.js
  src/integrations/third-party/zapier-free.php
  tests/unit/integrations/third-party/zapier-free-test.php
Labels: UI change, changelog: bugfix

#19089 Only mark subheading title if subheading text is too long
  packages/js/src/decorator/gutenberg.js
  packages/js/src/decorator/helpers/getFieldsToMarkHelper.js
  packages/js/src/decorator/tinyMCE.js
  packages/js/tests/decorator/helpers/getFieldsToMarkHelper.test.js
  packages/yoastseo/spec/languageProcessing/helpers/html/getFieldsToMarkSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/values/MarkSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/getFieldsToMark.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/values/Mark.js
Labels: changelog: non-user-facing

#19081 PC-851 Adds script to export inclusive language configuration
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js
Labels: changelog: non-user-facing

#19122 Removes addon data tracking.
  admin/tracking/class-tracking.php
Labels: changelog: non-user-facing

#19126 Composer: update dependencies
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#19127 GH Actions: various tweaks
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/integrationtest.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#19128 CS/QA: silence a few deprecations
  admin/class-my-yoast-proxy.php
  admin/class-yoast-network-admin.php
  src/conditionals/admin/estimated-reading-time-conditional.php
  src/conditionals/third-party/elementor-edit-conditional.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/settings-integration.php
  src/integrations/third-party/elementor.php
  tests/integration/admin/test-class-yoast-network-admin.php
  tests/unit/conditionals/estimated-reading-time-conditional-test.php
  tests/unit/main-test.php
Labels: yoast cs/qa, changelog: other

#19130 CS/QA: import use and fqn fixes
  inc/class-upgrade.php
  src/actions/indexables-page-action.php
  src/actions/wincher/wincher-keyphrases-action.php
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/deprecated/admin/metabox/class-metabox-analysis-inclusive-language.php
  src/deprecated/admin/ryte/class-ryte-option.php
  src/deprecated/admin/ryte/class-ryte-request.php
  src/deprecated/src/integrations/admin/ryte-integration.php
  src/deprecated/src/services/health-check/curl-reports.php
  src/exceptions/indexable/post-not-built-exception.php
  src/exceptions/indexable/term-not-built-exception.php
  src/generators/schema/article.php
  src/helpers/indexables-page-helper.php
  src/helpers/indexing-helper.php
  src/initializers/woocommerce.php
  src/integrations/admin/indexables-exclude-taxonomy-integration.php
  src/integrations/admin/indexables-page-integration.php
  src/integrations/admin/installation-success-integration.php
  src/integrations/front-end/robots-txt-integration.php
  src/integrations/settings-integration.php
  src/integrations/third-party/elementor.php
  src/integrations/third-party/woocommerce.php
  src/integrations/watchers/indexable-author-archive-watcher.php
  src/integrations/watchers/indexable-post-type-change-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-taxonomy-change-watcher.php
  src/loader.php
  src/presenters/admin/sidebar-presenter.php
  src/presenters/robots-txt-presenter.php
  src/routes/indexables-page-route.php
  src/values/robots/user-agent-list.php
  src/values/robots/user-agent.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
  tests/unit/admin/import/plugins/import-aioseo-v4-test.php
  tests/unit/builders/indexable-builder-test.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/helpers/post-helper-test.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
  tests/unit/presentations/indexable-home-page-presentation/canonical-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19131 Tests: fix three loose comparisons
  tests/unit/helpers/robots-txt-helper-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19132 CS: various doc fixes
  admin/formatter/class-post-metabox-formatter.php
  admin/tracking/class-tracking-plugin-data.php
  config/dependency-injection/deprecated-classes.php
  inc/class-wpseo-admin-bar-menu.php
  src/actions/indexables-page-action.php
  src/deprecated/src/integrations/admin/ryte-integration.php
  src/deprecated/src/services/health-check/curl-check.php
  src/deprecated/src/services/health-check/curl-reports.php
  src/deprecated/src/services/health-check/ryte-check.php
  src/deprecated/src/services/health-check/ryte-reports.php
  src/helpers/post-helper.php
  src/helpers/robots-txt-helper.php
  src/integrations/admin/health-check-integration.php
  src/integrations/front-end/robots-txt-integration.php
  src/services/health-check/default-tagline-check.php
  src/services/health-check/default-tagline-reports.php
  src/services/health-check/links-table-check.php
  src/services/health-check/links-table-reports.php
  src/services/health-check/page-comments-check.php
  src/services/health-check/postname-permalink-check.php
  src/values/robots/directive.php
  src/values/robots/user-agent-list.php
  src/values/robots/user-agent.php
  tests/unit/helpers/robots-txt-helper-test.php
  tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
  tests/unit/presenters/robots-txt-presenter-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19133 CS/QA: various minor fixes
  admin/tracking/class-tracking-addon-data.php
  admin/views/tabs/dashboard/dashboard.php
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  inc/sitemaps/class-sitemap-image-parser.php
  src/actions/indexables-page-action.php
  src/routes/indexables-page-route.php
Labels: yoast cs/qa, changelog: non-user-facing

#19123 Don't overwrite author_id with indexable id
  src/builders/indexable-builder.php
Labels: changelog: non-user-facing

#19134 Remove notification from free
  admin/class-admin-init.php
Labels: changelog: enhancement

#19138 PC-848-add-support-for-website-name-to-first-time-configuration
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/helpers/index.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
  src/actions/configuration/first-time-configuration-action.php
  src/integrations/admin/first-time-configuration-integration.php
Labels: changelog: enhancement

#19022 PC-715 Do not use select2 for the breadcrumbs select and remove the library from the bundle
  admin/class-admin-asset-dev-server-location.php
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/metabox/class-metabox.php
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/webpack/paths.js
  css/src/admin-global.css
  css/src/metabox.css
  css/src/yst_plugin_tools.css
  packages/js/package.json
  packages/js/src/initializers/admin.js
  packages/js/tests/components/SEMrushCountrySelector.test.js
  src/integrations/third-party/elementor.php
  tests/integration/admin/test-class-admin-asset-dev-server-location.php
  yarn.lock
Labels: changelog: non-user-facing

#19146 Calculate posts of authors via the WP way
  src/builders/indexable-author-builder.php
  src/helpers/author-archive-helper.php
  tests/unit/builders/indexable-author-builder-test.php
Labels: changelog: non-user-facing

#19148 Change prepare to query to mitigate wp notices.
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#19140 PC-962 Remove beta badge from word complexity assessment
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
Labels: UI change, changelog: other, Shopify

#19150 DUPP-670 Fix filter_var for wpseo_set_ignore function
  admin/ajax.php
Labels: changelog: non-user-facing

#19164 Robots_Txt_[Helper|Integration]: fix line ending handling robots.txt
  config/dependency-injection/services.php
  src/integrations/front-end/robots-txt-integration.php
  src/presenters/robots-txt-presenter.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
  tests/unit/presenters/robots-txt-presenter-test.php
Labels: yoast cs/qa, changelog: bugfix

#19167 Add a CLI command to run a cleanup of our custom tables
  src/commands/cleanup-command.php
  src/integrations/cleanup-integration.php
Labels: changelog: enhancement

#19157 DUPP-670 Fix filter_input call for load_admin_page_class function
  admin/class-admin-init.php
Labels: changelog: non-user-facing

#19149 DUPP-670 Fix filter_var call for dismiss_notice
  admin/ajax/class-yoast-plugin-conflict-ajax.php
Labels: changelog: non-user-facing

#19171 Update changlog format (both in file and creation settings)
  config/grunt/task-config/update-changelog-to-latest.js
  readme.txt
Labels: changelog: non-user-facing

#19172 Remove unneeded repetitions
  src/integrations/watchers/indexable-post-type-change-watcher.php
  src/integrations/watchers/indexable-taxonomy-change-watcher.php
Labels: changelog: non-user-facing

#19143 fix highlighting in list blocks for wordpress 6.1
  packages/js/src/analysis/getApplyMarks.js
  packages/js/src/decorator/gutenberg.js
  packages/js/tests/decorator/gutenberg.test.js
Labels: changelog: bugfix

#19159 Remove Flesch reading ease move notice
  packages/analysis-report/src/AnalysisResult.js
  packages/components/src/insights-card/InsightsCard.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/insights/components/estimated-reading-time.js
  packages/js/src/insights/components/flesch-reading-ease.js
  packages/js/src/insights/components/text-length.js
Labels: UI change, changelog: other

#19170 PC-343 Fixes loading of the webworker while editing posts with the Web Stories plug-in
  packages/yoastseo/spec/worker/createWorkerSpec.js
  packages/yoastseo/src/worker/createWorker.js
  src/integrations/third-party/web-stories-post-edit.php
  tests/unit/integrations/third-party/web-stories-post-edit-test.php
Labels: changelog: bugfix

#19147 Deprecate all events calendar classes.
  config/dependency-injection/deprecated-classes.php
  src/conditionals/the-events-calendar-conditional.php
  src/deprecated/src/conditionals/the-events-calendar-conditional.php
  src/deprecated/src/generators/schema/third-party/events-calendar-schema.php
  src/deprecated/src/integrations/third-party/the-events-calendar.php
  src/generators/schema/third-party/events-calendar-schema.php
Labels: changelog: other

#19194 Merge Feature/subheading distribution highlight
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/src/ContentAnalysis.js
  packages/js/src/components/contentAnalysis/Results.js
  packages/js/src/decorator/gutenberg.js
  packages/js/src/decorator/helpers/getFieldsToMarkHelper.js
  packages/js/src/decorator/tinyMCE.js
  packages/js/tests/decorator/helpers/getFieldsToMarkHelper.test.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/html/getFieldsToMarkSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/html/getSubheadingTextsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getSubheadingTextLengthSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/values/MarkSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/getFieldsToMark.js
  packages/yoastseo/src/languageProcessing/helpers/html/getSubheadingTexts.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/researches/getSubheadingTextLengths.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/values/Mark.js
Labels: changelog: non-user-facing

#19163 Make it possible to override the admin environment
  admin/tracking/class-tracking.php
  inc/options/class-wpseo-option-wpseo.php
  inc/sitemaps/class-sitemaps-admin.php
  inc/wpseo-functions.php
  src/helpers/environment-helper.php
  tests/unit/admin/tracking/tracking-test.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
Labels: changelog: other

#19191 Adds community patch PHP 8.1 improvements and adds unit tests
  src/integrations/admin/installation-success-integration.php
  src/integrations/admin/old-configuration-integration.php
  src/integrations/settings-integration.php
  tests/unit/integrations/admin/installation-success-integration-test.php
  tests/unit/integrations/admin/old-configuration-integration-test.php
  tests/unit/integrations/settings-integration-test.php
Labels: changelog: non-user-facing

#19186 Update class-wpseo-admin-bar-menu.php
  inc/class-wpseo-admin-bar-menu.php
Labels: changelog: other

#19180 DUPP-689 Settings UI: Settings UI: Add 'Create new user' option in person user select dropdown on Site representation
  packages/js/src/settings/components/formik-user-select-field.js
  packages/js/src/settings/routes/site-representation.js
  packages/ui-library/src/components/autocomplete-field/style.css
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing

#19166 Remove our Yoast i18n composer dependency
  composer.json
  composer.lock
Labels: changelog: other

#19208 Composer: update test utilities
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#19145 Enable tracking and add woocommerce check
  admin/tracking/class-tracking-addon-data.php
  admin/tracking/class-tracking.php
Labels: changelog: non-user-facing

#19205 Settings UI: change site representation user rights notifications
  packages/js/src/settings/routes/site-representation.js
Labels: innovation, changelog: non-user-facing

#19213 Docs: minor fix
  src/presentations/indexable-presentation.php
Labels: yoast cs/qa, changelog: non-user-facing

#19216 PHP 8.2 | Indexables_Page_Helper: declare a missing property
  src/helpers/indexables-page-helper.php
Labels: yoast cs/qa, changelog: other

#19217 PHP 8.2 | Tests: improve Indexable_Mock & use in more places
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/doubles/models/indexable-mock.php
  tests/unit/integrations/watchers/indexable-post-watcher-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19218 PHP 8.2 | Tests: improve Meta_Tags_Context_Mock & use in more places
  src/context/meta-tags-context.php
  tests/unit/doubles/context/meta-tags-context-mock.php
  tests/unit/helpers/schema/id-helper-test.php
  tests/unit/integrations/front-end-integration-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19219 Tests/SEO_Links_Mock: sync the list of declared properties
  tests/unit/doubles/models/seo-links-mock.php
Labels: yoast cs/qa, changelog: non-user-facing

#19220 PHP 8.2 | Tests: improve Primary_Term_Mock & use in more places
  tests/unit/doubles/models/primary-term-mock.php
  tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19185 Add a transition when a route changes
  packages/js/src/settings/app.js
  packages/js/src/settings/components/route-layout.js
Labels: innovation, changelog: non-user-facing

#19221 PHP 8.2 | Indexable_Presentation: work around dynamic properties
  src/presentations/indexable-presentation.php
  tests/unit/doubles/presentations/indexable-presentation-mock.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/breadcrumb-test.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
  tests/unit/integrations/breadcrumbs-integration-test.php
  tests/unit/integrations/third-party/woocommerce-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19222 PHP 8.2 | Indexable_Hierarchy: work around dynamic properties
  tests/unit/doubles/models/indexable-hierarchy-mock.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19223 Description_Presenter_Test: declare known property
  tests/unit/presenters/open-graph/description-presenter-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19224 WebPage_Test: remove stray property assignments
  tests/unit/generators/schema/webpage-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19227 Tests: use named mocks for YoastSEO native classes
  tests/unit/actions/indexables/indexable-head-action-test.php
  tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
  tests/unit/builders/indexable-link-builder-test.php
  tests/unit/builders/primary-term-builder-test.php
  tests/unit/dependency-injection/schema-templates-pass-test.php
  tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
  tests/unit/integrations/watchers/primary-term-watcher-test.php
  tests/unit/models/indexable-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19226 Schema_Generator/Abstract_Schema_Piece: improve handling of optional identifiers
  src/generators/schema-generator.php
  src/generators/schema/abstract-schema-piece.php
Labels: yoast cs/qa, changelog: other

#19229 Tests: use named mocks for WP native classes
  tests/unit/actions/importing/aioseo-cleanup-action-test.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/actions/importing/aioseo-validate-data-action-test.php
  tests/unit/actions/indexing/abstract-link-indexing-action-test.php
  tests/unit/actions/indexing/indexable-post-indexation-action-test.php
  tests/unit/actions/indexing/indexable-term-indexation-action-test.php
  tests/unit/actions/indexing/post-link-indexing-action-test.php
  tests/unit/actions/indexing/term-link-indexing-action-test.php
  tests/unit/admin/capabilities/capabilities-utils-test.php
  tests/unit/admin/formatter/post-metabox-formatter-test.php
  tests/unit/admin/formatter/term-metabox-formatter-test.php
  tests/unit/admin/import/plugins/import-aioseo-v4-test.php
  tests/unit/bootstrap.php
  tests/unit/builders/indexable-author-builder-test.php
  tests/unit/builders/indexable-home-page-builder-test.php
  tests/unit/builders/indexable-post-type-archive-builder-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/commands/index-command-test.php
  tests/unit/database/migration-runner-test.php
  tests/unit/helpers/aioseo-helper-test.php
  tests/unit/helpers/current-page-helper-test.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/helpers/schema/id-helper-test.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/integrations/front-end/handle-404-test.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
  tests/unit/integrations/third-party/woocommerce-post-edit-test.php
  tests/unit/integrations/watchers/indexable-post-watcher-test.php
  tests/unit/integrations/watchers/option-titles-watcher-test.php
  tests/unit/main-test.php
  tests/unit/presentations/indexable-presentation/canonical-test.php
  tests/unit/presentations/indexable-term-archive-presentation/canonical-test.php
  tests/unit/presentations/indexable-term-archive-presentation/robots-test.php
  tests/unit/presenters/open-graph/image-presenter-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/repositories/indexable-repository-test.php
  tests/unit/routes/abstract-indexation-route-test.php
  tests/unit/routes/alert-dismissal-route-test.php
  tests/unit/routes/first-time-configuration-route-test.php
  tests/unit/routes/importing-route-test.php
  tests/unit/routes/indexables-head-route-test.php
  tests/unit/routes/indexables-page-route-test.php
  tests/unit/routes/indexing-route-test.php
  tests/unit/routes/semrush-route-test.php
  tests/unit/routes/supported-features-route-test.php
  tests/unit/routes/wincher-route-test.php
  tests/unit/services/importing/importable-detector-service-test.php
  tests/unit/surfaces/meta-surface-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19230 Tests: use named mocks for WP_CLI native classes
  tests/unit/commands/index-command-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19206 DUPP-755 - PHP 8.1 compat: Use array to pass parameters to schedule a cron job to send tracking data after core update
  admin/tracking/class-tracking.php
Labels: changelog: bugfix

#18122 Update integration tests for sitemap router to cover when scheme is none
  tests/integration/sitemaps/test-class-wpseo-sitemaps-router.php
Labels: changelog: non-user-facing

#19214 Enforce displaying title tags for web stories
  src/integrations/third-party/web-stories.php
  tests/unit/integrations/third-party/web-stories-test.php
Labels: community-patch, changelog: bugfix

#19231 PHP 8.2 | Abstract_Main and surface helpers: Fix use of dynamic properties
  lib/abstract-main.php
  src/exceptions/forbidden-property-mutation-exception.php
  src/surfaces/helpers-surface.php
  src/surfaces/open-graph-helpers-surface.php
  src/surfaces/schema-helpers-surface.php
  src/surfaces/twitter-helpers-surface.php
  tests/unit/TestCase.php
  tests/unit/admin/admin-features-test.php
  tests/unit/admin/tracking/tracking-test.php
  tests/unit/admin/views/feature-toggles-test.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/helpers/wincher-helper-test.php
  tests/unit/inc/addon-manager-test.php
  tests/unit/inc/language-utils-test.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
  tests/unit/integrations/admin/deactivated-premium-integration-test.php
  tests/unit/integrations/admin/migration-error-integration-test.php
  tests/unit/integrations/watchers/option-wpseo-watcher-test.php
  tests/unit/main-test.php
  tests/unit/presenters/admin/migration-error-presenter-test.php
  tests/unit/presenters/admin/notice-presenter-test.php
  tests/unit/surfaces/classes-surface-test.php
  tests/unit/surfaces/helpers-surface-test.php
  tests/unit/surfaces/meta-surface-test.php
  tests/unit/surfaces/open-graph-helpers-surface-test.php
  tests/unit/surfaces/schema-helpers-surface-test.php
  tests/unit/surfaces/twitter-helpers-surface-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#19202 Settings UI: crawl cleanup robots txt modification rules should be disabled on multisite
  packages/js/src/settings/hocs/with-disabled-message-support.js
  packages/js/src/settings/routes/crawl-optimization.js
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing

#19207 Adds upsell data attributes to php templates.
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-form.php
  admin/views/licenses.php
  admin/views/redirects.php
  packages/js/src/components/AnalysisUpsell.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/modals/MultipleKeywords.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/components/social/SocialUpsell.js
  packages/js/src/insights/components/prominent-words.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/workouts/components/WorkoutCard.js
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/admin/social-templates-integration.php
  src/presenters/admin/sidebar-presenter.php
Labels: changelog: non-user-facing

#19233 Add upsell configuration to buy buttons
  packages/js/src/settings/app.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/crawl-optimization.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/site-features.js
  packages/js/src/settings/routes/templates/post-type.js
  packages/js/src/settings/routes/templates/taxonomy.js
  packages/js/src/settings/store/default-settings.js
  packages/ui-library/src/components/feature-upsell/index.js
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#19212 PC-989 Add a safeguard to check if wpseoAdminL10n is defined in the worker
  packages/yoastseo/src/worker/createWorker.js
Labels: changelog: non-user-facing, Shopify

#19234 Surfaces\Values\Meta: fix dynamic property setting in magic methods
  src/surfaces/values/meta.php
  tests/unit/surfaces/values/meta-test.php
Labels: yoast cs/qa, changelog: other

#19235 Change new settings UI page id
  packages/js/src/settings/helpers/submit.js
  src/integrations/settings-integration.php
  tests/unit/integrations/settings-integration-test.php
Labels: changelog: non-user-facing

#19139 PC-961 inclusive language analysis is not loaded when premium is activated
  admin/metabox/class-metabox-analysis-inclusive-language.php
Labels: changelog: non-user-facing

#19236 PHP 8.2 | utf8_decode deprecation
  inc/class-wpseo-replace-vars.php
  tests/integration/test-wpseo-functions.php
Labels: changelog: non-user-facing

#19251 Abstract_Presentation: brute force allow dynamic properties
  src/presentations/abstract-presentation.php
Labels: yoast cs/qa, changelog: other

#19255 GH Actions: run the tests against PHP 8.2
  .github/workflows/integrationtest.yml
  .github/workflows/unittest.yml
Labels: yoast cs/qa, changelog: non-user-facing

#19237 Settings UI: site features on network admin
  packages/js/src/settings/app.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/settings/hocs/with-disabled-message-support.js
  packages/js/src/settings/hooks/index.js
  packages/js/src/settings/hooks/use-disabled-message.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/crawl-optimization.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/site-features.js
  packages/js/src/settings/routes/templates/post-type.js
  packages/js/src/settings/routes/templates/taxonomy.js
  packages/js/src/settings/store/default-settings.js
  packages/js/src/settings/store/preferences.js
  packages/ui-library/src/components/card/style.css
  packages/ui-library/src/components/feature-upsell/index.js
  packages/ui-library/src/elements/badge/style.css
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing

#19250 Settings UI: only save the user profiles when allowed and when the user ID is a number of 1 or higher
  packages/js/src/settings/helpers/submit.js
Labels: innovation, changelog: non-user-facing

#19248 Settings UI: rename default settings to something more specific
  packages/js/src/settings/hocs/with-formik-dummy-field.js
  packages/js/src/settings/store/default-setting-values.js
  packages/js/src/settings/store/default-settings.js
  packages/js/src/settings/store/index.js
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing

#19168 Unit tests for the viewability watchers
  tests/unit/integrations/watchers/indexable-post-type-change-watcher-test.php
  tests/unit/integrations/watchers/indexable-taxonomy-change-watcher-test.php
Labels: changelog: non-user-facing

#19247 Dupp 683 new settings UI responsive improvements
  css/src/new-settings.css
  packages/js/src/settings/app.js
  packages/js/src/settings/components/fieldset-layout.js
  packages/js/src/settings/components/search.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/settings/routes/site-basics.js
  packages/js/src/settings/routes/site-features.js
  packages/postcss-preset/package.json
  packages/tailwindcss-preset/package.json
  packages/ui-library/package.json
  packages/ui-library/src/components/sidebar-navigation/index.js
  packages/ui-library/src/components/sidebar-navigation/style.css
  tailwind.config.js
  yarn.lock
Labels: innovation, changelog: non-user-facing

#19262 DUPP-668 Use WHIP to deprecate PHP < 7.2
  composer.json
  composer.lock
  src/integrations/admin/unsupported-php-version.php
Labels: changelog: other

#19256 DUPP-730-add-the-events-calendar-to-the-integrations-page
  packages/js/images/tec-logo.svg
  packages/js/src/integrations-page/acf-integration.js
  packages/js/src/integrations-page/algolia-integration.js
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/plugin-integration.js
  packages/js/src/integrations-page/plugin-integrations.js
  packages/js/src/integrations-page/schema-api-integrations.js
  packages/js/src/integrations-page/seo-tools-integrations.js
  packages/js/src/integrations-page/simple-integration.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/integrations-page/woocommerce-integration.js
  src/integrations/admin/integrations-page.php
Labels: UI change, changelog: enhancement

#19136 Admin bar improvements
  css/src/adminbar.css
  inc/class-wpseo-admin-bar-menu.php
  tests/integration/inc/test-class-wpseo-admin-bar-menu.php
Labels: UI change, changelog: enhancement

#19266 Settings UI: add support for website name and alternate name for both website and organization
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/helpers/submit.js
  packages/js/src/settings/routes/site-basics.js
  packages/js/src/settings/routes/site-representation.js
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing

#19269 DUPP-777 Change claim messages and logo links for integrations
  packages/js/src/integrations-page/plugin-integrations.js
  packages/js/src/integrations-page/seo-tools-integrations.js
Labels: UI change, changelog: non-user-facing

#19271 Add hotkey for opening search in new settings UI
  packages/js/package.json
  packages/js/src/settings/components/search.js
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/hocs/with-disabled-message-support.js
  packages/js/src/settings/hooks/index.js
  packages/js/src/settings/hooks/use-parsed-user-agent.js
  packages/js/src/settings/routes/special-pages.js
  packages/js/src/settings/store/breadcrumbs.js
  src/integrations/settings-integration.php
  yarn.lock
Labels: innovation, changelog: non-user-facing

#19272 Update social preview short links and add context
  admin/class-expose-shortlinks.php
  packages/js/src/components/contexts/root.js
  packages/js/src/components/contexts/use-root-context.js
  packages/js/src/components/social/SocialUpsell.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/helpers/classicEditor.js
  packages/js/src/initializers/block-editor-integration.js
  packages/js/src/initializers/elementor-editor-integration.js
Labels: changelog: non-user-facing

#19278 Fix minor CSS issues in new settings UI
  css/src/new-settings.css
Labels: innovation, changelog: non-user-facing

#19270 DUPP-710-unit-test-for-search-functionality-in-feature-new-settings-ui_clean
  README.md
  packages/js/jest.config.js
  packages/js/package.json
  packages/js/tests/settings/__snapshots__/search.test.js.snap
  packages/js/tests/settings/search.test.js
Labels: changelog: non-user-facing

#19181 DUPP-670 Replace filter_input calls for PHP 8.1 compatibility
  admin/class-meta-columns.php
  tests/integration/doubles/wpseo-meta-columns-double.php
  tests/integration/test-class-wpseo-meta-columns.php
Labels: changelog: non-user-facing

#19280 Update copy of license page
  admin/views/licenses.php
  images/local_plugin_assistant.svg
  images/plugin_subscription.svg
  images/woo_plugin_assistant.svg
Labels: UI change, changelog: non-user-facing

#19174 Performance issues happen due to whitespace blocks with NULL value as blockName
  src/helpers/blocks-helper.php
Labels: community-patch, changelog: bugfix, PHP 8.1

#19265 DUPP-670 Fix PHP 8.1 compatibility for elementor-edit-conditional class
  src/conditionals/third-party/elementor-edit-conditional.php
  tests/unit/conditionals/third-party/elementor-edit-conditional-test.php
Labels: changelog: non-user-facing

#19276 Dupp 793 settings UI last run ux feedback
  css/src/new-settings.css
  packages/js/src/settings/components/search.js
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/breadcrumbs.js
  packages/js/src/settings/routes/crawl-optimization.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/media.js
  packages/js/src/settings/routes/rss.js
  packages/js/src/settings/routes/site-basics.js
  packages/js/src/settings/routes/site-features.js
  packages/js/src/settings/routes/site-representation.js
  packages/js/src/settings/routes/templates/post-type.js
  packages/js/src/settings/routes/templates/taxonomy.js
  packages/js/tests/settings/__snapshots__/search.test.js.snap
  packages/js/tests/settings/search.test.js
  packages/ui-library/src/components/toggle-field/style.css
  packages/ui-library/src/elements/autocomplete/style.css
  packages/ui-library/src/elements/code/style.css
  packages/ui-library/src/elements/select/style.css
  packages/ui-library/src/elements/table/index.js
Labels: innovation, changelog: non-user-facing

#19282 Edit spec file to fix failing tests for Inclusive Language
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
Labels: changelog: non-user-facing

#19287 Dupp 684 revisit disabled fields and sections
  packages/js/src/settings/components/formik-media-select-field.js
  packages/js/src/settings/components/formik-replacement-variable-editor-field.js
  packages/js/src/settings/hocs/with-formik-dummy-field.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/crawl-optimization.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/media.js
  packages/js/src/settings/routes/templates/post-type.js
  packages/js/src/settings/routes/templates/taxonomy.js
  packages/ui-library/src/components/feature-upsell/index.js
  packages/ui-library/src/components/select-field/index.js
  packages/ui-library/src/components/select-field/style.css
  packages/ui-library/src/elements/select/index.js
  packages/ui-library/src/elements/select/style.css
Labels: innovation, changelog: non-user-facing

#19283 Dupp 736 create better file input stories
  packages/ui-library/src/elements/file-input/stories.js
Labels: changelog: non-user-facing

#19290 Remove AAVE term from Inclusive language targeted phrases
  admin/metabox/class-metabox-analysis-inclusive-language.php
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
Labels: innovation, changelog: enhancement

#19294 Implement toggle deps for author archives and crawl optimization
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/breadcrumbs.js
  packages/js/src/settings/routes/crawl-optimization.js
  packages/ui-library/src/elements/code/style.css
  packages/ui-library/src/elements/label/style.css
Labels: innovation, changelog: non-user-facing

#19296 Dupp 806 improve search index
  packages/js/src/settings/components/search.js
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/breadcrumbs.js
  packages/js/src/settings/routes/crawl-optimization.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/media.js
  packages/js/src/settings/routes/site-basics.js
  packages/js/src/settings/routes/site-features.js
  packages/js/src/settings/routes/templates/post-type.js
  packages/js/src/settings/routes/templates/taxonomy.js
  packages/js/src/settings/store/breadcrumbs.js
  packages/ui-library/src/elements/autocomplete/index.js
  packages/ui-library/src/elements/select/index.js
  packages/ui-library/src/elements/toggle/index.js
Labels: innovation, changelog: non-user-facing

#19245 Allow overriding of WordPress shortlinks for inclusive language in Shopify
  packages/yoastseo/spec/scoring/InclusiveLanguageAssessorSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/inclusiveLanguageAssessor.js
Labels: changelog: non-user-facing

#19292 Settings UI: allow using arrow up down to navigate through search results with keyboard command palette
  css/src/new-settings.css
  packages/js/src/settings/components/search.js
  packages/js/tests/settings/__snapshots__/search.test.js.snap
  packages/js/tests/settings/search.test.js
  packages/ui-library/src/components/modal/style.css
Labels: innovation, changelog: non-user-facing

#19298 Do fix worpdress org format
  config/grunt/task-config/update-changelog-to-latest.js
  readme.txt
Labels: changelog: non-user-facing

#19288 Add context parameter to upsell buttons
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/modals/MultipleKeywords.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/components/social/SocialUpsell.js
  packages/js/src/externals/contexts.js
  packages/js/src/helpers/classicEditor.js
  packages/js/src/initializers/block-editor-integration.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/insights/components/prominent-words.js
Labels: changelog: non-user-facing

#19279 Schema integration improvements
  packages/js/images/ssp-logo.svg
  packages/js/images/wp-recipemaker-logo.svg
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/recommended-integrations.js
  packages/js/src/integrations-page/schema-api-integrations.js
  src/integrations/admin/integrations-page.php
Labels: UI change, changelog: enhancement

#19228 PC-247 Target non-inclusive phrases with rules based on function words, participles, and/or punctuation marks
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedByExceptionSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticipleSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/regularParticiplesRegex.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticiple.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/notInclusiveWhenStandalone.js
Labels: innovation, changelog: enhancement

#19313 Dupp 808 settings UI bugs found in alpha test
  css/src/new-settings.css
  packages/js/package.json
  packages/js/src/settings/app.js
  packages/js/src/settings/components/error-fallback.js
  packages/js/src/settings/components/search.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/settings/routes/site-features.js
  packages/ui-library/src/components/modal/style.css
  packages/ui-library/src/elements/select/index.js
  yarn.lock
Labels: innovation, changelog: non-user-facing

#19317 Settings UI: Load in the person social profiles when the switching to represent a person
  packages/js/src/settings/routes/site-representation.js
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing
