Repository Yoast/wordpress-seo, pull requests merged in 2022-06, with the labels that each got.

#18510 LINGO-1462 - Marking a post as cornerstone content does not change the readability analysis
  packages/js/src/classic-editor/components/cornerstone-content.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/src/classic-editor/watcher.js
  packages/js/tests/classic-editor/initial-state.test.js
  packages/seo-integration/src/analysis/analysis.js
  packages/seo-integration/src/analysis/analyze.js
  packages/seo-integration/src/analysis/createAnalysisConfiguration.js
  packages/seo-integration/src/google-preview/containers/google-preview-container.js
  packages/seo-store/src/analysis/slice/config.js
  packages/seo-store/src/form/slice/seo.js
  packages/seo-store/tests/analysis/hooks.test.js
  packages/seo-store/tests/analysis/slice/config.test.js
  packages/seo-store/tests/analysis/slice/results.test.js
  packages/seo-store/tests/form/slice/seo.test.js
Labels: innovation, changelog: non-user-facing

#18516 LINGO-1456 - Provide the right formatted date for the Google Preview and the analysis
  packages/seo-integration/src/analysis/analyze.js
  packages/seo-integration/src/google-preview/containers/google-preview-container.js
  packages/seo-integration/src/helpers/formatDate.js
  packages/seo-integration/tests/helpers/formatDate.test.js
Labels: innovation, changelog: non-user-facing

#18519 Set disabled upsell crawl settings toggle to "allow_control"
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: non-user-facing

#18522 P1 1409 webinar banners
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/class-yoast-form.php
  css/src/admin-global.css
  css/src/notifications.css
  images/succes_marieke_bubble_optm.svg
  packages/js/src/components/WebinarPromoNotification.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/containers/PersistentDismissableAlert.js
  packages/js/src/containers/PersistentDismissableNotification.js
  packages/js/src/containers/withPersistentDismiss.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/initializers/settings-header.js
  packages/js/src/initializers/settings-store.js
  packages/js/src/redux/actions/dismissedAlerts.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/actions/isPremium.js
  packages/js/src/redux/reducers/dismissedAlerts.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/reducers/isPremium.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/isPremium.js
  packages/js/src/settings.js
  src/integrations/alerts/webinar-promo-notification.php
Labels: changelog: other

#18523 Revert to Allow Control for Post Comment feeds upon upgrade to 19.1
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#18525 Return initial behavior for premium users in first time configuration
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
Labels: changelog: non-user-facing

#18340 Replace filter_input with sanitize_text_field
  admin/ajax/class-shortcode-filter.php
  tests/unit/admin/ajax/shortcode-filter-test.php
Labels: changelog: non-user-facing

#18529 Return initial behavior for free users in first time configuration
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
Labels: changelog: non-user-facing

#18469 DUPP-573 Allow changing the check url for the Ryte integration
  src/integrations/admin/ryte-integration.php
Labels: changelog: enhancement

#18533 Post overview: sortable SEO and readability score columns
  admin/class-meta-columns.php
  composer.json
  css/src/admin-global.css
Labels: changelog: enhancement

#18509 Create defaultblog option validator for network admin
  src/exceptions/validation/invalid-blog-id-exception.php
  src/services/options/network-admin-options-service.php
  src/validators/blog-id-validator.php
  tests/unit/validators/blog-id-validator-test.php
Labels: changelog: non-user-facing

#18527 LR-7 Improves sentence detection for sentences with initials
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
Labels: changelog: enhancement, Shopify

#18538 Add the shortlinks to the webinar promo banner and notification
  admin/class-config.php
  admin/metabox/class-metabox.php
  composer.json
  packages/js/src/components/WebinarPromoNotification.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
  packages/js/src/initializers/settings-header.js
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#18545 Fix webp support
  packages/helpers/src/social-preview-image-validation/facebookValidation.js
  packages/helpers/tests/social-preview-image-validation/facebookValidationTest.js
  src/helpers/image-helper.php
Labels: changelog: enhancement

#18505 LR-8 Improves sentence detection in sentences containing abbreviations
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/config/abbreviationsSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
  packages/yoastseo/src/languageProcessing/languages/en/config/abbreviations.js
Labels: changelog: enhancement, Shopify

#18542 Fix author detection on Pinterest Rich Article pins
  src/generators/schema/article.php
  tests/unit/generators/schema/article-test.php
Labels: changelog: enhancement

#18549 Don't encode ampersands in URLs
  src/presenters/abstract-indexable-tag-presenter.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/twitter/image-presenter.php
Labels: changelog: bugfix

#18536 Lingo-1521 - SEO and Readability assessments are not shown on taxonomy pages
  packages/js/src/classic-editor/watcher.js
  packages/seo-integration/src/analysis/analyze.js
  packages/seo-integration/src/google-preview/containers/google-preview-container.js
  packages/seo-integration/src/helpers/formatDate.js
  packages/seo-integration/src/replacement-variables/configurations.js
  packages/seo-integration/tests/helpers/formatDate.test.js
  packages/seo-store/src/analysis/slice/index.js
  packages/seo-store/src/editor/selectors/selectFormattedDate.js
  packages/seo-store/src/editor/slice.js
  packages/seo-store/tests/analysis/slice/index.test.js
  packages/seo-store/tests/editor/helpers/selectFormattedDate.test.js
Labels: innovation, changelog: non-user-facing

#18528 LR-17 Exclude blockquotes from content analysis
  packages/js/src/decorator/gutenberg.js
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlParserSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/htmlParser.js
Labels: changelog: enhancement, Shopify

#18434 P1-1347 make yoast form use the new options framework
  admin/class-option-tab.php
  admin/class-yoast-form.php
  admin/class-yoast-network-admin.php
  admin/google_search_console/class-gsc.php
  admin/google_search_console/views/gsc-display.php
  admin/pages/dashboard.php
  admin/pages/metas.php
  admin/pages/network.php
  admin/pages/social.php
  admin/views/tool-file-editor.php
  composer.json
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option.php
  inc/options/class-wpseo-options.php
  inc/options/class-wpseo-taxonomy-meta.php
  src/actions/options/network-admin-options-action.php
  src/actions/options/options-action.php
  src/exceptions/option/form-invalid-exception.php
  src/helpers/input-helper.php
  src/helpers/options-helper.php
  src/initializers/options-initializer.php
  src/integrations/options-form-integration.php
  src/routes/network-admin-options-route.php
  src/routes/options-route.php
  src/services/options/abstract-options-service.php
  src/services/options/site-options-service.php
  src/services/options/taxonomy-metadata-service.php
  tests/integration/admin/test-class-option-tab.php
  tests/integration/admin/test-class-yoast-network-admin.php
  tests/unit/actions/options/network-admin-options-action-test.php
  tests/unit/actions/options/options-action-test.php
  tests/unit/helpers/options-helper-test.php
  tests/unit/initializers/options-initializer-test.php
  tests/unit/integrations/options-form-integration-test.php
  tests/unit/integrations/third-party/wincher-test.php
  tests/unit/routes/network-admin-options-route-test.php
  tests/unit/routes/options-route-test.php
  tests/unit/services/options/multisite-options-service-test.php
  tests/unit/services/options/network-admin-options-service-test.php
  tests/unit/services/options/site-options-service-test.php
  tests/unit/services/options/taxonomy-metadata-service-test.php
Labels: changelog: non-user-facing

#18551 Update notifications counters only when present
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
Labels: changelog: bugfix

#18552 Require Guzzle 6.5.7
  composer.json
  composer.lock
Labels: changelog: non-user-facing

#18515 Fixed typo in OAuthToken class
  src/values/oauth/oauth-token.php
  tests/unit/values/oauth/oauth-token-test.php
Labels: changelog: non-user-facing

#18079 Make the og:description getter more like the default description getter
  src/presenters/open-graph/description-presenter.php
  tests/unit/presenters/open-graph/description-presenter-test.php
Labels: community-patch, changelog: bugfix

#18543 Introduce new meta author presenter
  src/integrations/front-end-integration.php
  src/presenters/meta-author-presenter.php
  tests/unit/integrations/front-end-integration-test.php
  tests/unit/presenters/meta-author-presenter-test.php
Labels: changelog: enhancement

#18530 LR-9 Improve sentence detection for declarative sentences in quotation marks
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
Labels: changelog: enhancement, Shopify

#18557 Don't encode ampersands in URLs
  inc/sitemaps/class-sitemap-image-parser.php
  inc/sitemaps/class-sitemaps-renderer.php
  tests/integration/sitemaps/test-class-wpseo-sitemaps-renderer.php
Labels: changelog: bugfix

#18535 Add clean permalink features to options
  admin/class-yoast-form.php
  admin/tracking/class-tracking-settings-data.php
  css/src/admin-global.css
  css/src/yst_plugin_tools.css
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: non-user-facing

#18568 Jdv/clean permalinks restored
  admin/class-yoast-form.php
  admin/tracking/class-tracking-settings-data.php
  css/src/admin-global.css
  css/src/yst_plugin_tools.css
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: non-user-facing

#18566 Change the first sort of the post score columns from red to green
  admin/class-meta-columns.php
Labels: changelog: non-user-facing

#18563 Create a css specificity solution in UI library so it can be used in opinionated environments
  packages/tailwindcss-preset/index.js
  packages/ui-library/.storybook/preview.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/package.json
  packages/ui-library/readme.md
  packages/ui-library/scripts/build-css.js
  packages/ui-library/src/base.css
  packages/ui-library/src/components/checkbox-group/style.css
  packages/ui-library/src/components/file-import/style.css
  packages/ui-library/src/components/modal/index.js
  packages/ui-library/src/components/modal/style.css
  packages/ui-library/src/components/radio-group/style.css
  packages/ui-library/src/components/root/stories.js
  packages/ui-library/src/components/root/style.css
  packages/ui-library/src/components/select-field/style.css
  packages/ui-library/src/components/text-field/style.css
  packages/ui-library/src/components/textarea-field/style.css
  packages/ui-library/src/components/toggle-field/index.js
  packages/ui-library/src/components/toggle-field/style.css
  packages/ui-library/src/elements/alert/style.css
  packages/ui-library/src/elements/badge/style.css
  packages/ui-library/src/elements/button/style.css
  packages/ui-library/src/elements/checkbox/style.css
  packages/ui-library/src/elements/label/style.css
  packages/ui-library/src/elements/link/style.css
  packages/ui-library/src/elements/progress-bar/style.css
  packages/ui-library/src/elements/radio/style.css
  packages/ui-library/src/elements/select/style.css
  packages/ui-library/src/elements/text-input/style.css
  packages/ui-library/src/elements/textarea/style.css
  packages/ui-library/src/elements/title/style.css
  packages/ui-library/src/elements/toggle/style.css
  packages/ui-library/src/hooks/index.js
  packages/ui-library/src/index.js
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-root-factory-1-snap.png
Labels: changelog: enhancement

#18570 Improve UX
  css/src/admin-global.css
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: non-user-facing

#18572 DUPP-593 Use generic class for help text
  css/src/admin-global.css
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: non-user-facing

#18453 LR-5/LINGO-1162 Adjust the applicability of some readability assessments
  packages/yoastseo/spec/scoring/assessments/assessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ListAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/PassiveVoiceAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceBeginningsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/fleschReadingEaseAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/wordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/contentAssessorSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/assessment.js
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/fleschReadingEaseAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/wordComplexityAssessment.js
Labels: changelog: enhancement, Shopify

#18573 Fixes a bug where the focus keyphrase was not recognized in the Wincher table (and thus did not get marked with an asterisk).
  packages/js/src/components/WincherKeyphrasesTable.js
  packages/js/tests/components/WincherKeyphrasesTable.test.js
Labels: changelog: bugfix

#18569 LINGO-1496 Remove unnecessary SEO assessments in taxonomies and custom taxonomies
  packages/js/src/analysis/isTaxonomyAnalysisActive.js
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/getAnalysisConfiguration.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/tests/analysis/isTaxonomyAnalysisActive.test.js
  packages/js/tests/classic-editor/getAnalysisConfiguration.test.js
  packages/js/tests/classic-editor/initial-state.test.js
Labels: innovation, changelog: non-user-facing

#18581 Lr 45 sentence tokenizer clash between initials and quotes
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
Labels: changelog: non-user-facing

#18558 Change the main schema ID
  src/config/schema-ids.php
  src/context/meta-tags-context.php
  src/deprecated/frontend/schema/class-schema-howto.php
  src/deprecated/frontend/schema/class-schema-ids.php
  src/generators/schema/article.php
  src/generators/schema/author.php
  src/generators/schema/howto.php
  src/generators/schema/third-party/events-calendar-schema.php
  src/generators/schema/webpage.php
  src/helpers/schema/replace-vars-helper.php
  src/integrations/third-party/woocommerce.php
  src/presentations/archive-adjacent-trait.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-home-page-presentation.php
  src/presentations/indexable-post-type-archive-presentation.php
  src/presentations/indexable-post-type-presentation.php
  src/presentations/indexable-presentation.php
  src/presentations/indexable-static-posts-page-presentation.php
  src/presentations/indexable-term-archive-presentation.php
  tests/unit/doubles/context/meta-tags-context-mock.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/article-test.php
  tests/unit/generators/schema/author-test.php
  tests/unit/generators/schema/webpage-test.php
  tests/unit/helpers/schema/replace-vars-helper-test.php
  tests/unit/integrations/third-party/woocommerce-test.php
  tests/unit/presentations/indexable-presentation/permalink-test.php
Labels: changelog: enhancement

#18577 Fix help link and copy of the IndexNow feature toggle
  admin/views/class-yoast-feature-toggles.php
Labels: changelog: non-user-facing

#18564 Remove date parameters from URLs when date archives are disabled
  src/helpers/url-helper.php
  src/integrations/front-end/redirects.php
  tests/unit/integrations/front-end/redirects-test.php
Labels: changelog: enhancement

#18567 LINGO-1083 - Add inactive keyword distribution check
  admin/class-expose-shortlinks.php
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/src/ContentAnalysis.js
  packages/analysis-report/tests/AnalysisListTest.js
  packages/analysis-report/tests/AnalysisResultTest.js
  packages/analysis-report/tests/ContentAnalysisTest.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/js/src/components/contentAnalysis/Results.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
Labels: UI change, changelog: other

#18578 Changes to IndexNow and pinging search engines
  inc/options/class-wpseo-option-wpseo.php
  inc/sitemaps/class-sitemaps-admin.php
  inc/sitemaps/class-sitemaps.php
  tests/unit/inc/sitemaps/sitemaps-admin-test.php
  tests/unit/integrations/front-end/category-term-description-test.php
  tests/unit/integrations/front-end/comment-link-fixer-test.php
  tests/unit/integrations/front-end/indexing-controls-test.php
  tests/unit/integrations/front-end/redirects-test.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
  tests/unit/integrations/front-end/rss-footer-embed-test.php
  tests/unit/integrations/front-end/theme-titles-test.php
  tests/unit/integrations/third-party/amp-test.php
  tests/unit/integrations/third-party/bbpress-test.php
  tests/unit/integrations/third-party/jetpack-test.php
  tests/unit/integrations/third-party/wpml-test.php
  tests/unit/loader-test.php
Labels: changelog: enhancement

#18580 WordProof endpoint fix
  composer.json
  composer.lock
  src/conditionals/third-party/wordproof-integration-active-conditional.php
  src/integrations/third-party/wordproof.php
Labels: changelog: non-user-facing

#18583 Updated caniuse-lite database for browserslist.
  yarn.lock
Labels: changelog: non-user-facing

#18555 Bring several small improvements to WordPress RSS feeds
  src/integrations/front-end/feed-improvements.php
Labels: changelog: enhancement

#18596 Fix small bug in the WordProof certificate
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#18582 P1-1410 add insights collapsible in post editor in free
  admin/class-expose-shortlinks.php
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/views/class-yoast-feature-toggles.php
  css/src/metabox.css
  packages/components/src/insights-card/insightscard.css
  packages/js/src/analysis/blockEditorData.js
  packages/js/src/analysis/classicEditorData.js
  packages/js/src/analysis/refreshAnalysis.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/modals/editorModals/EditorModal.js
  packages/js/src/editor-modules.js
  packages/js/src/elementor.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/containers/SnippetEditor.js
  packages/js/src/helpers/create-watcher.js
  packages/js/src/helpers/fields/EstimatedReadingTimeFields.js
  packages/js/src/initializers/estimated-reading-time.js
  packages/js/src/insights/components/data-model.js
  packages/js/src/insights/components/estimated-reading-time.js
  packages/js/src/insights/components/flesch-reading-ease.js
  packages/js/src/insights/components/insights-collapsible.js
  packages/js/src/insights/components/insights-modal.js
  packages/js/src/insights/components/prominent-words.js
  packages/js/src/insights/components/word-count.js
  packages/js/src/insights/initializer.js
  packages/js/src/insights/redux/actions.js
  packages/js/src/insights/redux/reducer.js
  packages/js/src/insights/redux/selectors.js
  packages/js/src/post-edit.js
  packages/js/src/redux/actions/editorData.js
  packages/js/src/redux/actions/estimatedReadingTime.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/reducers/estimatedReadingTime.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/reducers/preferences.js
  packages/js/src/redux/selectors/editorData.js
  packages/js/src/redux/selectors/estimatedReadingTime.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/preferences.js
  packages/js/src/term-edit.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/src/values/Paper.js
  src/integrations/third-party/elementor.php
Labels: UI change, changelog: enhancement

#18597 PC-70 clean permalinks disabled opacity
  css/src/admin-global.css
Labels: changelog: non-user-facing

#18590 Default to site logo for org and person logo, and site name for org name
  src/context/meta-tags-context.php
Labels: changelog: enhancement

#18602 PC-78 Require Guzzle 6.5.8
  composer.json
  composer.lock
Labels: changelog: non-user-facing

#18591 Change schema image logic
  src/generators/schema/main-image.php
  tests/unit/generators/schema/main-image-test.php
Labels: changelog: enhancement

#18593 Add upsell for Premium SEO Analysis in the post sidebar
  admin/class-expose-shortlinks.php
  packages/js/src/components/KeywordUpsell.js
  packages/js/src/components/SidebarButton.js
  packages/js/src/components/UpsellBox.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/modals/PremiumSEOAnalysisModal.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/elementor/components/fills/ElementorFill.js
Labels: UI change, changelog: other

#18595 add add_manage_privacy_options capability to seo manager
  admin/capabilities/class-register-capabilities.php
Labels: changelog: non-user-facing

#18603 only return the yoast meta key to be timestamped
  composer.json
  composer.lock
  src/integrations/third-party/wordproof.php
Labels: changelog: non-user-facing

#18607 [PC-73] Add notice for premium deactivated
  css/src/admin-global.css
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/deactivated-premium-integration.php
  tests/unit/integrations/admin/deactivated-premium-integration-test.php
Labels: changelog: enhancement

#18611 PC-72 - Fix flesch reading ease score in insights and remove Flesch reading ease assessment
  packages/js/src/insights/components/flesch-reading-ease.js
  packages/js/src/insights/redux/actions.js
  packages/js/src/insights/redux/reducer.js
  packages/js/src/insights/redux/selectors.js
  packages/js/tests/insights/components/flesch-reading-ease.test.js
  packages/js/tests/insights/redux/reducer.test.js
  packages/js/tests/insights/redux/selectors.test.js
  packages/yoastseo/index.js
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/researches/getFleschReadingScoreSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/fleschReadingEaseAssessmentSpec.js
  packages/yoastseo/spec/scoring/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/cornerstone/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/contentAssessorSpec.js
  packages/yoastseo/spec/scoring/storePostsAndPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/src/languageProcessing/researches/getFleschReadingScore.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/readability/fleschReadingEaseAssessment.js
  packages/yoastseo/src/scoring/contentAssessor.js
  packages/yoastseo/src/scoring/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js
Labels: changelog: enhancement

#18601 PC-16 Upsell from 'NewsArticle' schema article type selection
  admin/class-expose-shortlinks.php
  packages/js/src/components/SchemaTab.js
  packages/js/src/containers/SchemaTab.js
  packages/js/src/redux/reducers/preferences.js
Labels: UI change, changelog: other

#18615 PC-85 - PC-85-notication-headings-too-big-on-premium-page-and-structurally-wrong-everywhere
  css/src/admin-global.css
  packages/js/src/containers/PersistentDismissableNotification.js
  src/presenters/admin/notice-presenter.php
  tests/unit/presenters/admin/notice-presenter-test.php
Labels: changelog: bugfix

#18614 [PC-87] Do not show premium deactivated notice on upload plugin pages
  src/integrations/admin/deactivated-premium-integration.php
  tests/unit/integrations/admin/deactivated-premium-integration-test.php
Labels: changelog: non-user-facing

#18616 [PC-92] Fix the name of the filter function for wordproof_timestamp_post_types
  src/integrations/third-party/wordproof.php
Labels: changelog: non-user-facing

#18617 Fix yoast-premium-deactivated-notice when shown in privacy page
  css/src/admin-global.css
Labels: changelog: enhancement

#18618 PC-90 - Do not show Flesch reading ease inside of the insights tab when it is not available.
  packages/js/src/insights/components/insights-collapsible.js
  packages/js/src/insights/components/insights-modal.js
  packages/js/src/insights/initializer.js
  packages/js/src/insights/redux/reducer.js
  packages/js/src/insights/redux/selectors.js
  packages/js/tests/insights/components/insights-collapsible.test.js
  packages/js/tests/insights/components/insights-modal.test.js
  packages/js/tests/insights/redux/selectors.test.js
Labels: UI change, changelog: non-user-facing

#18612 PC-94 Fix permalink generation for date archives
  src/presentations/indexable-presentation.php
  tests/unit/presentations/archive-adjacent-test.php
  tests/unit/presentations/indexable-author-archive-presentation/canonical-test.php
  tests/unit/presentations/indexable-author-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-home-page-presentation/canonical-test.php
  tests/unit/presentations/indexable-post-type-archive-presentation/canonical-test.php
  tests/unit/presentations/indexable-post-type-archive-presentation/presentation-instance-builder-trait.php
  tests/unit/presentations/indexable-post-type-presentation/canonical-test.php
  tests/unit/presentations/indexable-presentation/canonical-test.php
  tests/unit/presentations/indexable-presentation/open-graph-url-test.php
  tests/unit/presentations/indexable-presentation/permalink-test.php
  tests/unit/presentations/indexable-static-home-page-presentation/canonical-test.php
  tests/unit/presentations/indexable-static-posts-page-presentation/canonical-test.php
  tests/unit/presentations/indexable-static-posts-page-presentation/open-graph-url-test.php
  tests/unit/presentations/indexable-term-archive-presentation/canonical-test.php
Labels: changelog: non-user-facing

#18622 PC-91 Output character counts for languages that use character count for text length calculation
  packages/js/src/insights/components/insights-collapsible.js
  packages/js/src/insights/components/insights-modal.js
  packages/js/src/insights/components/text-length.js
  packages/js/src/insights/components/word-count.js
  packages/js/src/insights/initializer.js
  packages/js/src/insights/redux/actions.js
  packages/js/src/insights/redux/reducer.js
  packages/js/src/insights/redux/selectors.js
  packages/js/tests/insights/components/insights-collapsible.test.js
  packages/js/tests/insights/components/insights-modal.test.js
  packages/js/tests/insights/components/text-length.test.js
  packages/js/tests/insights/redux/reducer.test.js
  packages/js/tests/insights/redux/selectors.test.js
  packages/yoastseo/spec/languageProcessing/AbstractResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/textLengthSpec.js
  packages/yoastseo/spec/languageProcessing/researches/wordCountInTextSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/taxonomyTextLengthSpec.js
  packages/yoastseo/src/languageProcessing/helpers/word/countWords.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/textLength.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/countCharacters.js
  packages/yoastseo/src/languageProcessing/researches/readingTime.js
  packages/yoastseo/src/languageProcessing/researches/wordCountInText.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
Labels: changelog: non-user-facing

#18620 Add the UI library, used the first time configuration.
  admin/class-admin-asset-manager.php
  admin/views/tabs/dashboard/first-time-configuration.php
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/postcss.js
  config/grunt/task-config/shell.js
  config/webpack/webpack.config.base.js
  css/src/tailwind.css
  package.json
  packages/babel-preset/index.js
  packages/babel-preset/package.json
  packages/js/package.json
  packages/js/src/first-time-configuration.js
  packages/js/src/first-time-configuration/tailwind-components/base/alert.js
  packages/postcss-preset/index.js
  packages/postcss-preset/package.json
  packages/tailwindcss-preset/index.js
  packages/tailwindcss-preset/package.json
  packages/ui-library/package.json
  postcss.config.js
  tailwind.config.js
  yarn.lock
Labels: changelog: non-user-facing

#18626 Add undetected first time configuration assets
  admin/class-admin-asset-manager.php
Labels: changelog: non-user-facing

#18629 Fix order of the metabox in Firefox
  packages/js/src/components/fills/MetaboxFill.js
Labels: changelog: non-user-facing

#18631 Pc 110 only show flesch reading ease score when there is enough content
  packages/components/src/insights-card/InsightsCard.js
  packages/js/src/insights/components/flesch-reading-ease.js
  packages/yoastseo/spec/languageProcessing/researches/getFleschReadingScoreSpec.js
  packages/yoastseo/src/languageProcessing/researches/getFleschReadingScore.js
Labels: UI change, changelog: non-user-facing

#18621 Frontend inspector requirements
  config/webpack/paths.js
  css/src/adminbar.css
  inc/class-wpseo-admin-bar-menu.php
  packages/components/src/SvgIcon.js
  packages/js/src/components/contentAnalysis/mapResults.js
  packages/js/src/frontend-inspector-resources.js
  src/presenters/abstract-indexable-tag-presenter.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/slack/enhanced-data-presenter.php
  tests/unit/presenters/canonical-presenter-test.php
  tests/unit/presenters/meta-author-presenter-test.php
  tests/unit/presenters/meta-description-presenter-test.php
  tests/unit/presenters/open-graph/article-author-presenter-test.php
  tests/unit/presenters/open-graph/article-modified-time-presenter-test.php
  tests/unit/presenters/open-graph/article-published-time-presenter-test.php
  tests/unit/presenters/open-graph/article-publisher-presenter-test.php
  tests/unit/presenters/open-graph/description-presenter-test.php
  tests/unit/presenters/open-graph/image-presenter-test.php
  tests/unit/presenters/open-graph/locale-presenter-test.php
  tests/unit/presenters/open-graph/site-name-presenter-test.php
  tests/unit/presenters/open-graph/title-presenter-test.php
  tests/unit/presenters/open-graph/type-presenter-test.php
  tests/unit/presenters/open-graph/url-presenter-test.php
  tests/unit/presenters/rel-next-presenter-test.php
  tests/unit/presenters/rel-prev-presenter-test.php
  tests/unit/presenters/slack/enhanced-data-presenter-test.php
  tests/unit/presenters/twitter/card-presenter-test.php
  tests/unit/presenters/twitter/creator-presenter-test.php
  tests/unit/presenters/twitter/description-presenter-test.php
  tests/unit/presenters/twitter/image-presenter-test.php
  tests/unit/presenters/twitter/site-presenter-test.php
  tests/unit/presenters/twitter/title-presenter-test.php
  tests/unit/presenters/webmaster/baidu-presenter-test.php
  tests/unit/presenters/webmaster/bing-presenter-test.php
  tests/unit/presenters/webmaster/google-presenter-test.php
  tests/unit/presenters/webmaster/pinterest-presenter-test.php
  tests/unit/presenters/webmaster/yandex-presenter-test.php
Labels: UI change, changelog: non-user-facing

#18632 PC-27 - don't show date in meta description in certain shopify content types and woo product pages
  admin/formatter/class-post-metabox-formatter.php
  packages/yoastseo/src/scoring/assessments/SCORING SEO.md
  src/integrations/third-party/woocommerce-post-edit.php
  tests/unit/integrations/third-party/woocommerce-post-edit-test.php
Labels: UI change, changelog: enhancement

#18635 Move PC 83 to release/19.3
  admin/class-config.php
  packages/js/src/components/SchemaSettings.js
Labels: changelog: non-user-facing

#18634 PC-122 Prevent warning if no user data is available
  src/presenters/meta-author-presenter.php
  tests/unit/presenters/meta-author-presenter-test.php
Labels: changelog: bugfix

#18599 Improve archive template / CollectionPage schema properties
  src/context/meta-tags-context.php
  src/generators/schema/main-image.php
  src/generators/schema/webpage.php
  tests/unit/generators/schema-generator-test.php
  tests/unit/generators/schema/main-image-test.php
  tests/unit/generators/schema/webpage-test.php
Labels: changelog: enhancement

#18633 An error occurred in the word complexity assessment in product pages in Woo
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
Labels: changelog: non-user-facing, Shopify

#18637 Dont show news seo upsell when news seo is active
  inc/class-wpseo-utils.php
  packages/js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#18630 Fix inactive setting toggles get a false value upon saving the settings form
  admin/class-yoast-form.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/dashboard/integrations.php
  css/src/admin-global.css
  inc/class-upgrade.php
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: bugfix

#18640 Fix meta author presenter test
  tests/unit/presenters/meta-author-presenter-test.php
Labels: changelog: non-user-facing

#18639 PC-62 Applies marks to Classic editor blocks inside the Block/Gutenberg editor
  admin/class-admin-asset-manager.php
  admin/metabox/class-metabox-editor.php
  packages/js/src/analysis/getApplyMarks.js
Labels: changelog: enhancement
