Repository Yoast/wordpress-seo, pull requests merged in 2022-12, with the labels that each got.

#19326 Removes any persisting notification about incomplete translations
  admin/class-admin-init.php
Labels: changelog: non-user-facing

#19325 Settings UI: when globally disabling an archive type, uncheck show in search results toggle
  packages/js/package.json
  packages/js/src/settings/app.js
  packages/js/src/settings/components/formik-replacement-variable-editor-field.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/homepage.js
  packages/js/src/settings/routes/index.js
  packages/js/src/settings/routes/media-pages.js
Labels: innovation, changelog: non-user-facing

#19331 Reinstate some CSS rules to fix wrong styling in Local SEO
  css/src/yst_plugin_tools.css
Labels: changelog: non-user-facing

#19336 Hide the "all the Yoast plugins" card if the user already has all the plugins active
  admin/views/licenses.php
Labels: changelog: non-user-facing

#19337 Remove duplicated integration cards
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/seo-tools-integrations.js
Labels: changelog: non-user-facing

#19343 Dupp 737 improve radio element stories for is label dangerous html prop
  packages/ui-library/src/elements/radio/stories.js
Labels: changelog: non-user-facing

#19301 PC-818 move the word "oriental" to context specific orange cases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
Labels: changelog: enhancement

#19344 UI library: fix unique key prop warning
  packages/ui-library/src/components/children-limiter/stories.js
Labels: changelog: non-user-facing

#19306 UI library: docs: table element stories
  packages/ui-library/src/elements/table/stories.js
Labels: changelog: non-user-facing

#19341 Upsell: add upsell data attributes to admin bar and plugins page
  admin/class-admin.php
  inc/class-wpseo-admin-bar-menu.php
Labels: changelog: non-user-facing

#19342 Pass the shortlinker as a parameter to the constructor
  inc/class-wpseo-admin-bar-menu.php
Labels: changelog: non-user-facing

#19295 Dupp 731 create card stories
  packages/ui-library/src/components/card/index.js
  packages/ui-library/src/components/card/stories.js
Labels: innovation, changelog: non-user-facing

#19345 Add deprecated class to prevent fatal error from removing the I18n package.
  src/deprecated/i18n/i18n-v3.php
Labels: changelog: non-user-facing

#19340 Lowercase query before searching in new settings UI
  packages/js/src/settings/components/search.js
  packages/js/src/settings/helpers/i18n.js
  packages/js/src/settings/helpers/index.js
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/author-archives.js
  packages/js/src/settings/routes/date-archives.js
  packages/js/src/settings/routes/format-archives.js
  packages/js/src/settings/routes/media-pages.js
  packages/js/src/settings/routes/site-basics.js
  packages/js/src/settings/routes/templates/post-type.js
  packages/js/src/settings/routes/templates/taxonomy.js
  packages/js/src/settings/store/search.js
  src/integrations/settings-integration.php
Labels: innovation, changelog: non-user-facing

#19137 Exclude links and email addresses from prominent words analysis
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removeEmailAddressesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removeURLsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/sentencesLengthSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/countCharactersSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInsightsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removeEmailAddresses.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removeURLs.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/countCharacters.js
  packages/yoastseo/src/languageProcessing/researches/getProminentWordsForInsights.js
  packages/yoastseo/src/languageProcessing/researches/getProminentWordsForInternalLinking.js
Labels: changelog: enhancement, Shopify

#19328 Move exotic to context-dependent words in the Inclusive language analysis and add exceptions
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: changelog: enhancement

#19293 fix: used Badge component in TagInput and style it.
  packages/ui-library/src/elements/tag-input/index.js
  packages/ui-library/src/elements/tag-input/stories.js
  packages/ui-library/src/elements/tag-input/style.css
Labels: changelog: non-user-facing

#19268 UI library: DUPP-718-revisit-stories-for-select-component
  packages/ui-library/src/components/select-field/stories.js
  packages/ui-library/src/elements/select/stories.js
Labels: changelog: non-user-facing

#19300 UI library: improve stories for form field components that render options as children checkbox group radio group select autocomplete
  packages/ui-library/src/components/autocomplete-field/stories.js
  packages/ui-library/src/components/checkbox-group/stories.js
  packages/ui-library/src/components/radio-group/stories.js
Labels: changelog: non-user-facing

#19332 Bugfix: Create indexable hierarchy the first time an indexable is created
  src/builders/indexable-builder.php
  tests/integration/admin/watchers/test-class-indexable-post-watcher.php
  tests/unit/builders/indexable-builder-test.php
Labels: changelog: bugfix

#19347 Settings UI: Remove code blocks from breadcrumb settings for post type or tax in s…
  packages/js/src/settings/components/search.js
  packages/js/src/settings/helpers/search.js
Labels: innovation, changelog: non-user-facing

#19327 Inclusive Language Should have: target OCD
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isPrecededByExceptionSpec.js
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isPrecededByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/notInclusiveWhenStandalone.js
Labels: changelog: enhancement

#19324 Set minimal compatibility to wp 6.0
  .github/workflows/integrationtest.yml
  tests/unit/bootstrap.php
  tests/unit/inc/addon-manager-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#19162 PC-965 Fixes highlights when inline HTML tags are present in Classic editor
  packages/js/src/decorator/tinyMCE.js
  packages/yoastseo/spec/languageProcessing/helpers/html/replaceQuotesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/getFieldsToMark.js
  packages/yoastseo/src/languageProcessing/helpers/html/replaceQuotes.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
  packages/yoastseo/src/languageProcessing/index.js
Labels: changelog: bugfix, Shopify

#19338 PC-981 Adds 'stupid' to non-inclusive phrases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: changelog: enhancement

#19365 Add new WP Recipe Maker logo in the Integrations page
  packages/js/images/wp-recipe-maker-logo.svg
  packages/js/images/wp-recipemaker-logo.svg
  packages/js/src/integrations-page/schema-api-integrations.js
Labels: changelog: non-user-facing

#19372 Fix Fatal Error when trying to create breadcrumbs with unindexable items
  src/generators/breadcrumbs-generator.php
  src/integrations/third-party/woocommerce.php
  tests/unit/integrations/third-party/woocommerce-test.php
Labels: changelog: bugfix

#19291 Inclusive language should haves: adapt feedback for 'fat' and 'obese'.
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/scores.js
Labels: changelog: non-user-facing

#19360 Adds the possibility to add options to the Inclusive language assessor.
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#19374 PC-1025 Don't target 'the minority'
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
Labels: changelog: non-user-facing

#19354 Add phrases with normal and abnormal to non-inclusive phrases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
Labels: changelog: enhancement

#19373 PC-1029-anchors-containing-square-brackets-in-content-lead-to-errors-with-classic-editor
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
Labels: changelog: non-user-facing

#19353 UI library: update storybook and all other dependencies as far as possible
  packages/js/package.json
  packages/postcss-preset/package.json
  packages/tailwindcss-preset/package.json
  packages/ui-library/.storybook/main.js
  packages/ui-library/.storybook/preview.js
  packages/ui-library/package.json
  packages/ui-library/readme.md
  packages/ui-library/src/components/autocomplete-field/stories.js
  packages/ui-library/src/components/card/stories.js
  packages/ui-library/src/components/checkbox-group/stories.js
  packages/ui-library/src/components/children-limiter/stories.js
  packages/ui-library/src/components/feature-upsell/stories.js
  packages/ui-library/src/components/file-import/stories.js
  packages/ui-library/src/components/modal/stories.js
  packages/ui-library/src/components/notifications/stories.js
  packages/ui-library/src/components/radio-group/stories.js
  packages/ui-library/src/components/root/stories.js
  packages/ui-library/src/components/select-field/stories.js
  packages/ui-library/src/components/tag-field/stories.js
  packages/ui-library/src/components/text-field/stories.js
  packages/ui-library/src/components/textarea-field/stories.js
  packages/ui-library/src/components/toggle-field/stories.js
  packages/ui-library/src/elements/alert/stories.js
  packages/ui-library/src/elements/autocomplete/stories.js
  packages/ui-library/src/elements/badge/stories.js
  packages/ui-library/src/elements/button/stories.js
  packages/ui-library/src/elements/checkbox/stories.js
  packages/ui-library/src/elements/code/stories.js
  packages/ui-library/src/elements/error-boundary/stories.js
  packages/ui-library/src/elements/file-input/stories.js
  packages/ui-library/src/elements/label/stories.js
  packages/ui-library/src/elements/link/stories.js
  packages/ui-library/src/elements/progress-bar/stories.js
  packages/ui-library/src/elements/radio/stories.js
  packages/ui-library/src/elements/select/stories.js
  packages/ui-library/src/elements/table/stories.js
  packages/ui-library/src/elements/tag-input/stories.js
  packages/ui-library/src/elements/text-input/stories.js
  packages/ui-library/src/elements/textarea/stories.js
  packages/ui-library/src/elements/title/stories.js
  packages/ui-library/src/elements/toggle/stories.js
  yarn.lock
Labels: changelog: non-user-facing

#19349 PC-1015 Improve categorization of inclusive language phrases
  packages/yoastseo/spec/scoring/InclusiveLanguageAssessorSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/index.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessments.js
Labels: changelog: other

#19232 Update Bug_report.md
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: changelog: non-user-facing

#19355 inclusive language should haves: fix unreleased bug that phrases with hyphens were not recognized
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
Labels: changelog: non-user-facing

#19378 Feature/should haves for inclusive language
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsSpec.js
  packages/yoastseo/spec/scoring/InclusiveLanguageAssessorSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedByExceptionSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticipleSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isPrecededByExceptionSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/regularParticiplesRegex.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/index.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/scores.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticiple.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isPrecededByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/notInclusiveWhenStandalone.js
Labels: changelog: enhancement

#19381 UI library: docs: add stories to spinner element
  packages/ui-library/src/elements/spinner/index.js
  packages/ui-library/src/elements/spinner/stories.js
Labels: changelog: non-user-facing

#19384 UI library: Dupp 753 document other exports in storybook 2
  packages/ui-library/.storybook/preview.js
  packages/ui-library/src/hooks/hooks.stories.mdx
  packages/ui-library/src/hooks/readme.md
  packages/ui-library/src/hooks/use-svg-aria.js
  packages/ui-library/src/introduction.stories.mdx
Labels: changelog: non-user-facing

#19368 UI library: Dupp 719 prepare sidebar navigation component for release
  packages/ui-library/.storybook/style.css
  packages/ui-library/src/components/sidebar-navigation/index.js
  packages/ui-library/src/components/sidebar-navigation/menu-item.js
  packages/ui-library/src/components/sidebar-navigation/mobile.js
  packages/ui-library/src/components/sidebar-navigation/sidebar.js
  packages/ui-library/src/components/sidebar-navigation/stories.js
  packages/ui-library/src/components/sidebar-navigation/style.css
  packages/ui-library/src/components/sidebar-navigation/submenu-item.js
Labels: changelog: non-user-facing

#19316 Remove prominent words when its indexable gets deleted
  inc/class-upgrade.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
Labels: innovation, changelog: non-user-facing

#19380 Block editor: DUPP-850 fix error with gutenberg trunk
  packages/js/src/initializers/block-editor-integration.js
Labels: changelog: enhancement

#19348 Inclusive-language: Adds word forms support for some non-inclusive phrases
  packages/yoastseo/package.json
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/testHelpers/testHelpers.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
Labels: changelog: enhancement

#19376 Dupp 729 validation variants
  packages/js/src/settings/hocs/with-formik-error.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/.storybook/theme.js
  packages/ui-library/src/components/autocomplete-field/index.js
  packages/ui-library/src/components/autocomplete-field/stories.js
  packages/ui-library/src/components/autocomplete-field/style.css
  packages/ui-library/src/components/file-import/index.js
  packages/ui-library/src/components/notifications/index.js
  packages/ui-library/src/components/notifications/style.css
  packages/ui-library/src/components/select-field/index.js
  packages/ui-library/src/components/select-field/stories.js
  packages/ui-library/src/components/select-field/style.css
  packages/ui-library/src/components/tag-field/index.js
  packages/ui-library/src/components/tag-field/stories.js
  packages/ui-library/src/components/tag-field/style.css
  packages/ui-library/src/components/text-field/index.js
  packages/ui-library/src/components/text-field/stories.js
  packages/ui-library/src/components/text-field/style.css
  packages/ui-library/src/components/textarea-field/index.js
  packages/ui-library/src/components/textarea-field/stories.js
  packages/ui-library/src/components/textarea-field/style.css
  packages/ui-library/src/constants/index.js
  packages/ui-library/src/elements/alert/index.js
  packages/ui-library/src/elements/alert/style.css
  packages/ui-library/src/elements/autocomplete/index.js
  packages/ui-library/src/elements/autocomplete/stories.js
  packages/ui-library/src/elements/autocomplete/style.css
  packages/ui-library/src/elements/label/index.js
  packages/ui-library/src/elements/select/index.js
  packages/ui-library/src/elements/select/stories.js
  packages/ui-library/src/elements/select/style.css
  packages/ui-library/src/elements/validation/constants.js
  packages/ui-library/src/elements/validation/index.js
  packages/ui-library/src/elements/validation/style.css
  packages/ui-library/src/elements/validation/validation-icon.js
  packages/ui-library/src/elements/validation/validation-input.js
  packages/ui-library/src/elements/validation/validation-message.js
  packages/ui-library/src/index.js
Labels: changelog: non-user-facing

#19391 Add location context to synonyms upsell.
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
Labels: changelog: non-user-facing

#19382 Inclusive language: change string for the inclusive language orange bullet in pre publish box
  admin/formatter/class-metabox-formatter.php
  css/src/metabox.css
  packages/js/src/analysis/getIndicatorForScore.js
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/helpers/addCheckToChecklist.js
  packages/js/src/ui/publishBox.js
Labels: UI change, changelog: enhancement

#19383 Settings UI: Update react-hotkeys-hook dep to 4.0.5 version
  packages/js/package.json
  packages/js/src/settings/components/search.js
  yarn.lock
Labels: innovation, changelog: non-user-facing

#19398 GH Actions: improve performance of the CS step
  config/composer/actions.php
Labels: yoast cs/qa, changelog: non-user-facing

#19401 Settings UI: Introduce a notification urging for upgrade Premium if < 20.0
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/old-premium-integration.php
  tests/unit/integrations/admin/old-premium-integration-test.php
Labels: changelog: other

#19403 Update Twitter field label in the Person social URLs
  packages/js/src/settings/routes/site-representation.js
Labels: changelog: non-user-facing

#19412 Reverts changes to the highlighting feature
  packages/js/src/decorator/tinyMCE.js
  packages/yoastseo/spec/languageProcessing/helpers/html/replaceQuotesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/getFieldsToMark.js
  packages/yoastseo/src/languageProcessing/helpers/html/replaceQuotes.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
  packages/yoastseo/src/languageProcessing/index.js
Labels: changelog: non-user-facing

#19408 Settings-UI: DUPP-864-settings-ui-inclusive-language-issues
  packages/js/src/settings/hooks/use-disabled-message.js
  packages/js/src/settings/routes/site-features.js
  src/helpers/language-helper.php
  src/integrations/settings-integration.php
  tests/unit/integrations/settings-integration-test.php
Labels: UI change, changelog: non-user-facing

#19417 Settings UI: hide old settings and redirect features tab requests
  admin/class-admin-asset-manager.php
  admin/menu/class-admin-menu.php
  admin/pages/dashboard.php
  config/webpack/paths.js
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/initializers/admin.js
  packages/js/src/redirect-old-features-tab.js
  src/conditionals/admin/non-network-admin-conditional.php
  src/conditionals/settings-conditional.php
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/admin/redirect-old-features-tab-integration.php
Labels: changelog: non-user-facing

#19472 DUPP-865-settings-ui-catch-a-11-y-skip-to-links-before-they-break-hash-routing
  packages/js/src/settings/app.js
  packages/js/src/settings/components/search.js
  packages/js/src/settings/initialize.js
Labels: changelog: non-user-facing

#19407 Update old settings links and redirect for add-on links
  admin/class-config.php
  admin/class-plugin-conflict.php
  admin/class-schema-person-upgrade-notification.php
  admin/views/tabs/social/facebook.php
  packages/js/src/components/SchemaTab.js
  src/integrations/admin/redirect-integration.php
  src/integrations/admin/redirects-page-integration.php
  src/integrations/watchers/indexable-post-type-change-watcher.php
  src/integrations/watchers/indexable-taxonomy-change-watcher.php
  src/presenters/meta-description-presenter.php
  tests/unit/integrations/admin/redirect-integration-test.php
  tests/unit/integrations/admin/redirects-page-integration-test.php
  tests/unit/presenters/meta-description-presenter-test.php
Labels: changelog: non-user-facing

#19361 Remove browser field from package.json (packages/yoastseo)
  packages/yoastseo/CHANGELOG.md
  packages/yoastseo/package.json
Labels: community-patch, changelog: bugfix

#19469 Settings UI: Add introduction modal
  css/src/new-settings.css
  images/settings-intro_thumb0.jpg
  images/settings-intro_thumb1.jpg
  images/settings-intro_thumb2.jpg
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/settings/app.js
  packages/js/src/settings/components/form-layout.js
  packages/js/src/settings/components/introduction.js
  packages/js/src/settings/components/search.js
  packages/js/src/settings/constants/index.js
  packages/js/src/settings/store/index.js
  packages/js/src/settings/store/introduction.js
  packages/ui-library/src/components/modal/hooks.js
  packages/ui-library/src/components/modal/index.js
  packages/ui-library/src/components/modal/stories.js
  packages/ui-library/src/components/modal/style.css
  packages/ui-library/src/hooks/index.js
  src/actions/settings-introduction-action.php
  src/integrations/settings-integration.php
  src/routes/settings-introduction-route.php
  tests/unit/actions/settings-introduction-action-test.php
  tests/unit/integrations/settings-integration-test.php
  tests/unit/routes/settings-introduction-route-test.php
Labels: changelog: non-user-facing

#19482 Settings: Add redirect search pretty URLs
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/crawl-optimization.js
Labels: UI change, changelog: non-user-facing

#19483 Settings: Remove the minimum form height
  packages/js/src/settings/components/form-layout.js
Labels: UI change, changelog: non-user-facing

#19484 UI library: remove no wrap from the table cell
  packages/ui-library/src/elements/table/index.js
Labels: UI change, changelog: non-user-facing

#19474 Expands list of transition words for Portuguese
  packages/yoastseo/src/languageProcessing/languages/pt/config/transitionWords.js
Labels: changelog: enhancement, Shopify

#19492 Settings UI: Change minimum query characters depending on the user locale
  packages/js/src/settings/components/search.js
Labels: changelog: non-user-facing

#19496 Settings UI: Improve the navigation menu accessibility
  packages/js/src/settings/app.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/src/components/children-limiter/index.js
  packages/ui-library/src/components/sidebar-navigation/index.js
  packages/ui-library/src/components/sidebar-navigation/menu-item.js
  packages/ui-library/src/components/sidebar-navigation/mobile.js
  packages/ui-library/src/components/sidebar-navigation/sidebar.js
  packages/ui-library/src/components/sidebar-navigation/stories.js
  packages/ui-library/src/components/sidebar-navigation/style.css
  packages/ui-library/src/components/sidebar-navigation/submenu-item.js
Labels: changelog: non-user-facing

#19411 Updates participle forms for Portuguese
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js
Labels: changelog: enhancement, Shopify
