Repository Yoast/wordpress-seo, pull requests merged in 2022-01, with the labels that each got.

#17905 Travis: remove "Fix PHP 8.0 build after composer update"
  .travis.yml
Labels: yoast cs/qa, changelog: non-user-facing

#17877 Add Japanese full text test
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper4.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper2.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/index.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
Labels: changelog: non-user-facing

#17906 Introduce 2 conditionals and apply them to indexing-notification-integration
  src/conditionals/not-admin-ajax-conditional.php
  src/conditionals/user-can-manage-wpseo-options-conditional.php
  src/integrations/admin/indexing-notification-integration.php
  tests/unit/integrations/admin/indexing-notification-integration-test.php
Labels: community-patch, changelog: enhancement

#17907 Adapt the recommended meta description length for Japanese
  inc/class-wpseo-replace-vars.php
  packages/js/src/analysis/blockEditorData.js
  packages/js/src/analysis/classicEditorData.js
  packages/js/src/containers/SnippetEditor.js
  packages/js/src/elementor/containers/SnippetEditor.js
  packages/js/src/redux/selectors/editorData.js
  packages/js/tests/containers/SnippetEditor.test.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/yoastseo/spec/languageProcessing/languages/ja/ResearcherSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionLengthAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/metaDescriptionLength.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
Labels: changelog: enhancement

#17751 Automatically loop over importing chunks
  config/webpack/paths.js
  packages/js/src/import.js
  packages/js/src/services/IndexingService.js
  packages/js/tests/services/IndexingService.test.js
  src/conditionals/import-tool-selected-conditional.php
  src/integrations/admin/import-integration.php
  tests/unit/conditionals/import-tool-selected-conditional-test.php
  tests/unit/integrations/admin/import-integration-test.php
Labels: changelog: non-user-facing

#17911 Added support for global YoastSEO api's in the classic editor for compatibility with add-ons.
  packages/js/src/classic-editor.js
  packages/seo-integration/src/analyze.js
Labels: innovation, changelog: non-user-facing

#17903 make a hard split between post and term logic
  admin/class-config.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/src/classic-editor/shortcodes.js
  packages/js/src/classic-editor/watcher.js
  packages/js/src/initializers/tiny-mce.js
  packages/js/src/ui/publishBox.js
  packages/seo-integration/src/replacement-variables/configurations.js
  src/integrations/third-party/elementor.php
Labels: innovation, changelog: non-user-facing

#17914 Fixes the failing Japanese full text test
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
Labels: changelog: non-user-facing

#17910 P1-1128 - Fix featured image with first image in content fallback in Google Preview container
  packages/js/src/classic-editor/components/google-preview.js
Labels: innovation, changelog: non-user-facing

#17913 Lingo 1210 fix paragraph highlighting bug
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/sanitizeLineBreakTagSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeLineBreakTag.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
Labels: changelog: bugfix

#17918 P1 987 seo-integration docs
  packages/seo-integration/readme.md
Labels: innovation, changelog: non-user-facing

#17919 P1-1130 - Cleanup Classic Editor specific files that have become obsolete with new integration
  admin/class-admin-asset-manager.php
  packages/js/.babelrc
  packages/js/babel.config.json
  packages/js/package.json
  packages/js/src/analysis/classicEditorData.js
  packages/js/src/helpers/classicEditor.js
  packages/js/src/initializers/classic-editor-integration.js
  packages/js/tests/edit.test.js
  packages/replacement-variables/yarn.lock
  yarn.lock
Labels: innovation, changelog: non-user-facing

#17892 Handle focus loss by disappearing button in ImageSelect
  packages/components/src/image-select/ImageSelectButtons.js
Labels: changelog: bugfix

#17923 Add upgrade 17.9 routine to set wincher active to true
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#17921 P1 980 seo store docs
  packages/replacement-variables/readme.md
  packages/seo-integration/readme.md
  packages/seo-store/readme.md
Labels: innovation, changelog: non-user-facing

#17840 Added featured image plugin.
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/plugins/featured-image.js
  packages/js/src/classic-editor/plugins/shortcodes.js
Labels: innovation, changelog: non-user-facing

#17924 Fix wordpress.org translation parsing
  .travis.yml
  admin/class-admin-asset-manager.php
  config/webpack/webpack.config.js
  yarn.lock
Labels: changelog: non-user-facing

#17925 Fix untranslated string for the Keyphrase in title assessment
  packages/yoastseo/src/scoring/assessments/seo/TitleKeywordAssessment.js
Labels: changelog: non-user-facing

#17922 P1-1140 Fix title width and primary category plugins
  admin/class-primary-term-admin.php
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/plugins/seo-title-width.js
  src/integrations/admin/fix-news-dependencies-integration.php
Labels: innovation, changelog: non-user-facing

#17926 P1-1139 - Create build script in wordpress-seo
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/shell.js
  packages/replacement-variables/package.json
  packages/seo-integration/package.json
  packages/seo-store/package.json
Labels: innovation, changelog: non-user-facing

#17930 P1 1109 markdown plugin
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/plugins/featured-image.js
  packages/js/src/classic-editor/plugins/index.js
  packages/js/src/classic-editor/plugins/markdown.js
  packages/js/src/classic-editor/plugins/shortcodes.js
Labels: innovation, changelog: non-user-facing

#17927 Add Tailwind to Yoast SEO
  Gruntfile.js
  config/grunt/task-config/postcss.js
  css/src/workouts.css
  package.json
  packages/js/package.json
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/StepsTest.js
  packages/yoast-components/package.json
  packages/yoast-social-previews/package.json
  packages/yoastseo/package.json
  tailwind.config.js
  yarn.lock
Labels: changelog: non-user-facing

#17936 P1-1149 seo integration translations pipeline
  Gruntfile.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/copy.js
  config/grunt/task-config/shell.js
  package.json
  yarn.lock
Labels: innovation, changelog: non-user-facing

#17933 P1-1152 Fix post date timezone in name format
  packages/js/src/classic-editor/helpers/dom.js
Labels: innovation, changelog: non-user-facing

#17928 Lingo 1247 fix matching keyphrase enclosed in double quotes in japanese
  packages/yoastseo/spec/languageProcessing/helpers/match/processExactMatchRequestSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/matchTextWithWordSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getLinkStatisticsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/IntroductionKeywordAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInImageTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionKeywordAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/SubHeadingsKeywordAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/match/findKeywordInUrl.js
  packages/yoastseo/src/languageProcessing/helpers/match/matchTextWithArray.js
  packages/yoastseo/src/languageProcessing/helpers/match/matchTextWithWord.js
  packages/yoastseo/src/languageProcessing/helpers/match/processExactMatchRequest.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/doubleQuotes.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/quotes.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getWordForms.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/matchTextWithWord.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInPageTitle.js
  packages/yoastseo/src/languageProcessing/researches/functionWordsInKeyphrase.js
  packages/yoastseo/src/languageProcessing/researches/getLinkStatistics.js
  packages/yoastseo/src/languageProcessing/researches/keyphraseDistribution.js
  packages/yoastseo/src/languageProcessing/researches/keywordCount.js
  packages/yoastseo/src/languageProcessing/researches/metaDescriptionKeyword.js
Labels: changelog: bugfix

#17943 Set WP tested up to to 5.9
  readme.txt
  tests/unit/bootstrap.php
  wp-seo-main.php
Labels: changelog: other

#17940 LINGO-1253 Fixes incorrect assessments for keyphrases only consisting of function words
  packages/yoastseo/spec/languageProcessing/languages/ja/customResearches/getWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/getWordForms.js
Labels: changelog: bugfix

#17935 Pin `colors` package to safe version 1.4.0
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#17939 Account for a failed query and return early.
  composer.json
  src/repositories/seo-links-repository.php
Labels: community-patch, changelog: bugfix

#17956 Set tested up to WC to 6.1
  wp-seo.php
Labels: changelog: other

#17941 Change the overall SEO score on the posts/pages/movies/books overview page to red when no keyphrase is set
  admin/class-meta-columns.php
Labels: UI change, changelog: enhancement

#17963 title-tag: compatibility with block-based themes
  src/integrations/front-end-integration.php
Labels: changelog: bugfix

#17964 [QA-2801] Fix infinite loop involving the document title
  src/integrations/front-end-integration.php
Labels: changelog: non-user-facing

#17915 Remove script translations
  Gruntfile.js
  admin/class-admin-asset-manager.php
  admin/class-admin-asset-yoast-components-l10n.php
  admin/class-config.php
  admin/class-yoast-dashboard-widget.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  config/grunt/custom-tasks/convert-pot-to-wp.js
  config/grunt/custom-tasks/i18n-clean-json.js
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/clean.js
  config/grunt/task-config/copy.js
  config/grunt/task-config/glotpress_download.js
  config/grunt/task-config/makepot.js
  config/grunt/task-config/po2json.js
  config/grunt/task-config/shell.js
  package.json
  packages/js/src/dashboard-widget.js
  packages/js/src/elementor.js
  packages/js/src/helpers/i18n.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/initializers/search-appearance.js
  packages/js/src/initializers/term-scraper.js
  packages/js/src/installation-success.js
  packages/js/src/workouts.js
  src/integrations/admin/workouts-integration.php
  src/integrations/schema-blocks.php
  src/integrations/third-party/elementor.php
  yarn.lock
Labels: changelog: non-user-facing

#17965 IM-1662 Lowercase keyphrases in getWincherTrackableKeyphrases
  packages/js/src/redux/selectors/WincherSEOPerformance.js
Labels: changelog: bugfix

#17942 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: non-user-facing

#17954 Wincher: don't send API request when no keyphrases
  src/actions/wincher/wincher-keyphrases-action.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
Labels: changelog: non-user-facing

#17952 Wincher: don't send access token in GET parameters
  src/config/oauth-client.php
  src/config/semrush-client.php
  src/config/wincher-client.php
Labels: changelog: non-user-facing

#17968 LINGO-1242 Refactor content type configuration
  apps/seo-integration/src/index.js
  packages/js/src/classic-editor.js
  packages/js/src/classic-editor/analysis.js
  packages/js/src/classic-editor/content-types.js
  packages/js/tests/classic-editor/content-types.test.js
  packages/seo-integration/readme.md
  packages/seo-integration/src/index.js
Labels: changelog: non-user-facing

#17958 Support fallbacks for title and meta description
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/tests/classic-editor/helpers/dom.test.js
  packages/js/tests/classic-editor/initial-state.test.js
  packages/seo-integration/src/google-preview-container.js
  packages/seo-integration/src/replacement-variables/configurations.js
Labels: changelog: non-user-facing

#17917 Import noindex and nofollow for individual posts
  inc/class-wpseo-meta.php
  src/actions/importing/abstract-aioseo-settings-importing-action.php
  src/actions/importing/abstract-importing-action.php
  src/actions/importing/aioseo-custom-archive-settings-importing-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  src/actions/importing/deactivate-conflicting-plugins-action.php
  src/helpers/indexable-to-postmeta-helper.php
  src/helpers/meta-helper.php
  src/services/importing/aioseo-robots-provider-service.php
  src/services/importing/aioseo-robots-transformer-service.php
  tests/unit/actions/importing/abstract-aioseo-settings-importing-action-test.php
  tests/unit/actions/importing/abstract-importing-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
  tests/unit/actions/importing/import-cursor-manager-trait-test.php
  tests/unit/doubles/actions/importing/abstract-aioseo-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/abstract-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-custom-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-default-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-general-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-posttype-defaults-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-taxonomy-settings-importing-action-double.php
  tests/unit/helpers/indexable-to-postmeta-helper-test.php
  tests/unit/services/importing/aioseo-robots-provider-service-test.php
  tests/unit/services/importing/aioseo-robots-transformer-service-test.php
  tests/unit/services/importing/importable-detector-test.php
  tests/unit/services/importing/importer-action-filter-trait-test.php
Labels: changelog: non-user-facing

#17957 Improve import UX
  packages/js/src/import.js
  src/integrations/admin/import-integration.php
  tests/unit/integrations/admin/import-integration-test.php
Labels: changelog: non-user-facing

#17972 Delay a call to `get_plugins()` until after all plugins are loaded
  inc/class-addon-manager.php
Labels: community-patch, changelog: bugfix

#17912 Indexable sitemaps improvements
  inc/sitemaps/abstract-class-indexable-sitemap-provider.php
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
  src/builders/indexable-author-builder.php
  src/config/migrations/20211108133106_AddIsPubliclyViewableToIndexables.php
  src/integrations/watchers/indexable-author-watcher.php
  src/repositories/indexable-repository.php
  tests/integration/sitemaps/test-class-wpseo-author-sitemap-provider.php
  tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
  tests/unit/builders/indexable-author-builder-test.php
  tests/unit/integrations/watchers/indexable-static-home-page-watcher-test.php
  tests/unit/repositories/indexable-repository-test.php
Labels: changelog: non-user-facing

#17948 Fix Integration tests
  inc/sitemaps/class-author-sitemap-provider.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
  src/integrations/watchers/indexable-post-watcher.php
  tests/integration/framework/class-wpseo-unit-test-case.php
  tests/integration/frontend/test-class-wpseo-image-utils.php
Labels: changelog: non-user-facing

#17970 Exclude URLs from character count in Japanese
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/countCharactersSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripSpaces.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/countCharacters.js
Labels: changelog: bugfix

#17966 Improve ux for import failures
  packages/js/src/import.js
  src/integrations/admin/import-integration.php
  tests/unit/integrations/admin/import-integration-test.php
Labels: changelog: non-user-facing

#17947 Rename parameters with reserved names in String_Helper
  src/helpers/string-helper.php
Labels: changelog: non-user-facing

#17944 Rename parameters with reserved names in Options_Helper
  src/helpers/options-helper.php
Labels: changelog: non-user-facing

#17977 Dupp 196 add stepper button animations
  packages/js/package.json
  packages/js/src/workouts/components/Stepper.js
  yarn.lock
Labels: changelog: non-user-facing

#17937 Plugin 1426 sanitize aioseo data before import
  src/actions/importing/abstract-importing-action.php
  src/actions/importing/aioseo-custom-archive-settings-importing-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  src/actions/importing/deactivate-conflicting-plugins-action.php
  src/helpers/sanitization-helper.php
  tests/unit/actions/importing/abstract-aioseo-settings-importing-action-test.php
  tests/unit/actions/importing/abstract-importing-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
  tests/unit/services/importing/importable-detector-test.php
  tests/unit/services/importing/importer-action-filter-trait-test.php
Labels: changelog: non-user-facing

#17754 Plugin 1411 implement new health check design
  admin/class-admin-init.php
  inc/health-check-default-tagline.php
  src/integrations/admin/health-check-integration.php
  src/services/health-check/default-tagline-check.php
  src/services/health-check/default-tagline-report-builder.php
  src/services/health-check/default-tagline-runner.php
  src/services/health-check/health-check.php
  src/services/health-check/report-builder-factory.php
  src/services/health-check/report-builder.php
  src/services/health-check/runner-interface.php
  tests/unit/doubles/services/health-check/health-check-double.php
  tests/unit/inc/health-check-default-tagline-test.php
  tests/unit/integrations/admin/health-check-integration-test.php
  tests/unit/services/health-check/default-tagline-check-test.php
  tests/unit/services/health-check/default-tagline-report-builder-test.php
  tests/unit/services/health-check/default-tagline-runner-test.php
  tests/unit/services/health-check/health-check-test.php
  tests/unit/services/health-check/report-builder-factory-test.php
  tests/unit/services/health-check/report-builder-test.php
Labels: technical-debt, changelog: non-user-facing, cleanup

#17976 Import canonical url
  src/actions/importing/abstract-importing-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  src/helpers/indexable-to-postmeta-helper.php
  src/helpers/sanitization-helper.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/helpers/indexable-to-postmeta-helper-test.php
Labels: changelog: non-user-facing

#17969 Add featured images to indexable sitemaps
  inc/sitemaps/abstract-class-indexable-sitemap-provider.php
  src/helpers/xml-sitemap-helper.php
Labels: changelog: non-user-facing

#17980 Add a max-width to our FAQ and HowTo Block IMG's
  packages/js/src/structured-data-blocks/faq/components/Question.js
  packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
Labels: changelog: bugfix

#17946 Rename parameters with reserved names in Post_Helper
  src/helpers/post-helper.php
Labels: changelog: non-user-facing

#17974 Add helper magic isset method
  src/surfaces/helpers-surface.php
  src/surfaces/open-graph-helpers-surface.php
  src/surfaces/schema-helpers-surface.php
  src/surfaces/twitter-helpers-surface.php
Labels: community-patch, changelog: other

#17981 Improve stemming of Turkish word forms that include apostrophes
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper3.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/tr/helpers/internal/stemmerCoverage/goldStandardStems.json
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInPageTitleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/metaDescriptionKeywordSpec.js
  packages/yoastseo/src/languageProcessing/languages/tr/helpers/internal/stem.js
Labels: changelog: enhancement

#17984 Dupp 213 add unsaved changes modal component
  css/src/workouts.css
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/TailwindModal.js
  packages/js/src/workouts/components/UnsavedChangesModal.js
Labels: changelog: non-user-facing

#17986 Expand the first incomplete step on entering the workout
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/Stepper.js
Labels: changelog: non-user-facing

#17973 LINGO-1249 - Add categories to editor watcher
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/src/classic-editor/replacement-variables/configurations.js
  packages/js/src/classic-editor/watcher.js
  packages/seo-store/src/editor/slice.js
  packages/seo-store/src/editor/tests.js
Labels: innovation, changelog: non-user-facing

#17987 P1-1155 create concrete options class for single site options
  src/exceptions/option/abstract-option-exception.php
  src/exceptions/option/missing-configuration-key-exception.php
  src/exceptions/option/unknown-exception.php
  src/exceptions/validation/abstract-validation-exception.php
  src/exceptions/validation/empty-url-exception.php
  src/exceptions/validation/invalid-empty-string-exception.php
  src/exceptions/validation/invalid-type-exception.php
  src/exceptions/validation/invalid-url-exception.php
  src/helpers/validation-helper.php
  src/sanitizers/boolean-sanitizer.php
  src/sanitizers/integer-sanitizer.php
  src/sanitizers/sanitizer-interface.php
  src/sanitizers/text-sanitizer.php
  src/sanitizers/url-sanitizer.php
  src/services/options/abstract-options-service.php
  src/services/options/multisite-options-service.php
  src/services/options/site-options-service.php
  src/validators/empty-string-validator.php
  src/validators/string-validator.php
  src/validators/url-validator.php
  src/validators/validator-interface.php
  tests/unit/helpers/validation-helper-test.php
  tests/unit/services/options/site-options-service-test.php
  tests/unit/validators/url-validator-test.php
Labels: changelog: non-user-facing

#17992 Display the most recent last-modified date for every page in the sitemap
  inc/sitemaps/abstract-class-indexable-sitemap-provider.php
  inc/sitemaps/class-author-sitemap-provider.php
Labels: changelog: non-user-facing

#17993 Restore WPSEO_Sitemaps_Cache to prevent fatal errors
  inc/sitemaps/class-sitemaps-cache.php
Labels: changelog: non-user-facing

#17999 Fix structured data blocks deprecation warning
  packages/js/src/structured-data-blocks/faq/components/Question.js
Labels: changelog: bugfix

#18005 Also load translations in the web worker
  packages/js/src/analysis-worker.js
  packages/js/src/analysis/worker.js
Labels: changelog: non-user-facing

#17997 LINGO-1287 Update category replacement variable when selecting from most used categories
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/watcher.js
  packages/js/tests/classic-editor/helpers/dom.test.js
  packages/js/tests/classic-editor/initial-state.test.js
Labels: innovation, changelog: non-user-facing

#18009 Use the best suiting version for PHPUnit with WP 5.9
  .travis.yml
Labels: changelog: non-user-facing

#17994 Lingo 1250 support primary category pluggable replacement variable
  packages/js/src/classic-editor/replacement-variables/configurations.js
  packages/js/tests/classic-editor/replacement-variables/configurations.test.js
Labels: innovation, changelog: non-user-facing
