Repository Yoast/wordpress-seo, pull requests merged in 2022-07, with the labels that each got.

#18643 Update logo to the new design
  packages/components/src/YoastSeoIcon.js
  packages/components/tests/__snapshots__/IconTest.js.snap
Labels: UI change, changelog: enhancement

#18644 Pc 133 incorrect singular in feedback string for word complexity assessment v2
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
Labels: changelog: bugfix, changelog: non-user-facing

#18623 Upsell inactive premium toggles
  admin/class-yoast-form.php
  admin/views/class-yoast-feature-toggle.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/class-yoast-integration-toggles.php
  admin/views/tabs/dashboard/features.php
  admin/views/tabs/dashboard/integrations.php
  admin/views/tabs/network/features.php
  admin/views/tabs/network/integrations.php
  css/src/toggle-switch.css
Labels: changelog: non-user-facing

#18609 Add assessment for product identifiers
  packages/js/src/analysis/collectAnalysisData.js
  packages/js/src/redux/selectors/isPremium.js
  packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/researches/getProductIdentifierData.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
  packages/yoastseo/src/values/Paper.js
Labels: changelog: non-user-facing, Shopify

#18646 PC-135 Add beta badge to the word complexity assessment
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/tests/AnalysisResultTest.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/beta-badge/BetaBadge.js
  packages/components/src/beta-badge/beta-badge.css
  packages/components/src/beta-badge/index.js
  packages/components/src/index.js
  packages/js/src/components/contentAnalysis/mapResults.js
  packages/js/tests/components/contentAnalysis/mapResults.test.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/values/AssessmentResultSpec.js
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
  packages/yoastseo/src/values/AssessmentResult.js
Labels: innovation, UI change, changelog: non-user-facing

#18651 PC-88 PC-142 Improve meta author presenter
  src/presenters/meta-author-presenter.php
  tests/unit/presenters/meta-author-presenter-test.php
Labels: changelog: enhancement

#18653 Fix failing unit tests
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
Labels: changelog: non-user-facing

#18656 Add an SKU assessment for product pages
  packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProductSKUSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductSKUAssessmentSpec.js
  packages/yoastseo/spec/scoring/productPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/seoAssessorSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/researches/getProductSKUData.js
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: non-user-facing, Shopify

#18658 PC-148 Make word complexity and keyphrase distribution premium upsell is available for products
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#18665 PC-160 - Fixes marking words in text for strings that contain regex control characters
  packages/yoastseo/spec/markers/addMarkSpec.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
  packages/yoastseo/src/markers/addMarkSingleWord.js
Labels: changelog: bugfix, Shopify

#18667 PC-154 exclude plurals of non complex nouns from the word complexity assessment
  packages/yoastseo/spec/languageProcessing/languages/en/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/languages/en/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/wordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
Labels: innovation, changelog: non-user-facing, Shopify

#18664 Pc 43 fix discrepancies between elementor classic editor v2
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/quotesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/quotes.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/removePunctuation.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
Labels: changelog: enhancement, Shopify

#18671 Fix a failing unit test
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
Labels: changelog: non-user-facing

#18670 Rename SEO Analysis to Premium SEO Analysis when Premium is active
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/helpers/addCheckToChecklist.js
Labels: UI change, changelog: non-user-facing

#18677 Added note to the readability analysis that tells users that the Flesch reading ease score has moved to the insights section.
  packages/analysis-report/src/AnalysisResult.js
  packages/components/src/insights-card/InsightsCard.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/insights/components/estimated-reading-time.js
  packages/js/src/insights/components/flesch-reading-ease.js
  packages/js/src/insights/components/text-length.js
Labels: UI change, changelog: non-user-facing

#18659 PC-47 - Adds support for additional Draft.js plugins
  packages/analysis-report/tests/__mocks__/@wordpress/i18n.js
  packages/js/src/initializers/search-appearance.js
  packages/replacement-variable-editor/src/ReplacementVariableEditor.js
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/helpers/serialization.js
  packages/search-metadata-previews/tests/__mocks__/@wordpress/i18n.js
  packages/social-metadata-forms/jest/__mocks__/@wordpress/i18n.js
Labels: changelog: non-user-facing

#18679 Fix insights link in sidebar
  admin/class-expose-shortlinks.php
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
Labels: changelog: non-user-facing

#18680 PC-198 only show word complexity upsell for languages that support word complexity
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/helpers/assessmentUpsellHelpers.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordComplexitySpec.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordFormSupportSpec.js
  packages/yoastseo/src/helpers/getLanguagesWithWordComplexity.js
  packages/yoastseo/src/helpers/index.js
  packages/yoastseo/src/languageProcessing/index.js
Labels: changelog: non-user-facing

#18681 Fixed insights link in Elementor editor.
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
Labels: changelog: non-user-facing

#18683 Add upsell for Spanish and German word complexity
  packages/yoastseo/spec/helpers/getLanguagesWithWordComplexitySpec.js
  packages/yoastseo/src/helpers/getLanguagesWithWordComplexity.js
Labels: changelog: non-user-facing

#18685 PC-207-cherrypick-fix-mistake-in-spanish-word-complexity
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/frequencyList.json
Labels: changelog: non-user-facing, Shopify

#18684 PC-165 french word complexity assessment new
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/helpers/getLanguagesWithWordComplexitySpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/src/helpers/getLanguagesWithWordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/fr/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/wordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/checkIfWordIsComplex.js
Labels: innovation, changelog: enhancement, Shopify

#18686 PC-49-integrations-page
  admin/class-admin-asset-manager.php
  admin/views/tabs/dashboard/integrations.php
  config/webpack/paths.js
  packages/js/images/algolia-logo.svg
  packages/js/images/elementor-logo.svg
  packages/js/images/jetpack-logo.svg
  packages/js/images/ryte-logo.svg
  packages/js/images/semrush-logo.svg
  packages/js/images/wincher-logo.svg
  packages/js/images/woocommerce-logo.svg
  packages/js/images/wordproof-logo.svg
  packages/js/images/zapier-logo.svg
  packages/js/src/integrations-page.js
  packages/js/src/integrations-page/tailwind-components/card.js
  packages/js/src/integrations-page/tailwind-components/integrations-grid.js
  packages/js/src/workouts/components/WorkoutsPage.js
  packages/postcss-preset/package.json
  packages/tailwindcss-preset/package.json
  packages/ui-library/package.json
  src/actions/integrations-action.php
  src/integrations/admin/integrations-page.php
  src/routes/integrations-route.php
  tailwind.config.js
  yarn.lock
Labels: UI change, changelog: enhancement

#18695 PC- 218 Integrations page UX improvements
  packages/js/src/integrations-page.js
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/tailwind-components/card.js
  src/actions/integrations-action.php
  src/integrations/admin/integrations-page.php
  src/routes/integrations-route.php
Labels: changelog: non-user-facing

#18692 Change order of schema pieces to ensure parsing as one graph
  src/generators/schema-generator.php
  tests/unit/generators/schema-generator-test.php
Labels: component: schema (JSON+LD), changelog: enhancement

#18674 Add an edit icon next to assessments
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/src/ContentAnalysis.js
  packages/analysis-report/tests/AnalysisListTest.js
  packages/analysis-report/tests/AnalysisResultTest.js
  packages/analysis-report/tests/ContentAnalysisTest.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/IconCTAEditButton.js
  packages/components/src/index.js
  packages/components/tests/IconCTAEditButtonTest.js
  packages/components/tests/__snapshots__/IconCTAEditButtonTest.js.snap
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/Results.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/contentAnalysis/mapResults.js
  packages/js/src/containers/Results.js
  packages/js/tests/components/contentAnalysis/mapResults.test.js
  packages/yoastseo/spec/scoring/assessments/seo/FunctionWordsInKeyphraseAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInSEOTitleAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionKeywordAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/MetaDescriptionLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/PageTitleWidthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/UrlKeywordAssessmentSpec.js
  packages/yoastseo/spec/values/AssessmentResultSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/scoring/assessments/seo/FunctionWordsInKeyphraseAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInSEOTitleAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
  packages/yoastseo/src/values/AssessmentResult.js
Labels: UI change, changelog: enhancement

#18700 Add network level management for Algolia
  inc/options/class-wpseo-option-ms.php
Labels: changelog: bugfix

#18701 Normalize single quotes before removing contractions in the French word complexity assessment.
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/checkIfWordIsComplex.js
Labels: changelog: non-user-facing

#18702 PC-221 fix SERVER_NAME warning
  src/helpers/url-helper.php
  src/integrations/front-end/redirects.php
  tests/unit/helpers/url-helper-test.php
  tests/unit/integrations/front-end/redirects-test.php
Labels: changelog: bugfix

#18699 Replace action with a filter to add additional draft-js-plugins
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
Labels: changelog: non-user-facing

#18698 Enable the product identifiers assessment in WooCommerce
  packages/yoastseo/spec/languageProcessing/researches/getProductIdentifierDataSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/ProductIdentifiersAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/researches/getProductIdentifierData.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
Labels: changelog: enhancement

#18710 Put front-end inspector behind feature flag.
  inc/class-wpseo-admin-bar-menu.php
  src/conditionals/front-end-inspector-conditional.php
Labels: changelog: non-user-facing

#18711 PC-273 - 19.4 Yoast SEO: styling issues
  css/src/toggle-switch.css
  css/src/yst_plugin_tools.css
Labels: changelog: non-user-facing

#18480 Add apply replacement variables prop to google preview
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
Labels: changelog: non-user-facing

#18705 PC-59 Adds support for organization / person fallback image.
  admin/views/tabs/metas/paper-content/general/knowledge-graph.php
  composer.json
  inc/language-utils.php
  packages/components/src/image-select/ImageSelect.js
  packages/js/src/components/CompanyInfoMissing.js
  packages/js/src/components/ImageSelectComponent.js
  packages/js/src/components/PersonImageFallbackInfoMissing.js
  packages/js/src/components/portals/ImageSelectPortal.js
  packages/js/src/components/portals/PersonImageFallbackInfoPortal.js
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/base/image-select.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/organization-section.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/person-section.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
  packages/js/src/initializers/search-appearance.js
  src/context/meta-tags-context.php
  src/integrations/admin/first-time-configuration-integration.php
  tests/unit/inc/language-utils-test.php
Labels: UI change, changelog: enhancement

#18718 PC-276 Improve look of the cards
  packages/js/images/acf-logo.svg
  packages/js/images/algolia-logo.svg
  packages/js/images/elementor-logo.svg
  packages/js/images/jetpack-logo.svg
  packages/js/images/ryte-logo.svg
  packages/js/src/integrations-page/acf-integration.js
  packages/js/src/integrations-page/algolia-integration.js
  packages/js/src/integrations-page/helper.js
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/plugin-integration.js
  packages/js/src/integrations-page/simple-integration.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/integrations-page/woocommerce-integration.js
  src/integrations/admin/integrations-page.php
Labels: changelog: non-user-facing

#18727 PC-288 Add links to integration images + Use PNG logo for ACF
  images/acf-logo.png
  packages/js/images/acf-logo.svg
  packages/js/src/integrations-page/acf-integration.js
  packages/js/src/integrations-page/algolia-integration.js
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/simple-integration.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/integrations-page/woocommerce-integration.js
  src/integrations/admin/integrations-page.php
Labels: changelog: non-user-facing

#18724 Alter Edit button URL for indexables page
  packages/js/src/indexables-page/components/indexables-table.js
Labels: changelog: non-user-facing

#18731 PC-294 Prevent error in Chrome console for SVG
  packages/js/images/wincher-logo.svg
  packages/js/images/wordproof-logo.svg
  packages/js/images/zapier-logo.svg
Labels: changelog: non-user-facing

#18734 Revert revert of front end inspector
  inc/class-wpseo-admin-bar-menu.php
  src/deprecated/src/conditionals/front-end-inspector-conditional.php
  src/presenters/abstract-indexable-tag-presenter.php
  src/presenters/open-graph/image-presenter.php
  src/presenters/slack/enhanced-data-presenter.php
  tests/unit/presenters/canonical-presenter-test.php
  tests/unit/presenters/meta-author-presenter-test.php
  tests/unit/presenters/meta-description-presenter-test.php
  tests/unit/presenters/open-graph/article-author-presenter-test.php
  tests/unit/presenters/open-graph/article-modified-time-presenter-test.php
  tests/unit/presenters/open-graph/article-published-time-presenter-test.php
  tests/unit/presenters/open-graph/article-publisher-presenter-test.php
  tests/unit/presenters/open-graph/description-presenter-test.php
  tests/unit/presenters/open-graph/image-presenter-test.php
  tests/unit/presenters/open-graph/locale-presenter-test.php
  tests/unit/presenters/open-graph/site-name-presenter-test.php
  tests/unit/presenters/open-graph/title-presenter-test.php
  tests/unit/presenters/open-graph/type-presenter-test.php
  tests/unit/presenters/open-graph/url-presenter-test.php
  tests/unit/presenters/rel-next-presenter-test.php
  tests/unit/presenters/rel-prev-presenter-test.php
  tests/unit/presenters/slack/enhanced-data-presenter-test.php
  tests/unit/presenters/twitter/card-presenter-test.php
  tests/unit/presenters/twitter/creator-presenter-test.php
  tests/unit/presenters/twitter/description-presenter-test.php
  tests/unit/presenters/twitter/image-presenter-test.php
  tests/unit/presenters/twitter/site-presenter-test.php
  tests/unit/presenters/twitter/title-presenter-test.php
  tests/unit/presenters/webmaster/baidu-presenter-test.php
  tests/unit/presenters/webmaster/bing-presenter-test.php
  tests/unit/presenters/webmaster/google-presenter-test.php
  tests/unit/presenters/webmaster/pinterest-presenter-test.php
  tests/unit/presenters/webmaster/yandex-presenter-test.php
Labels: changelog: non-user-facing

#18738 PC-297 Hide submit button in integrations tab
  admin/pages/dashboard.php
Labels: UI change, changelog: other

#18726 PC 162 Exclude estimated reading time from the analysis
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeEstimatedReadingTimeSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeEstimatedReadingTime.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeString.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInFirstParagraph.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
Labels: changelog: enhancement

#18739 Fix eye highlighter not working for text containing the &nbsp; character 2nd edition
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
Labels: changelog: non-user-facing

#18735 Repopulate lists when ignoring and undoing
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/indexables-page.js
  src/helpers/indexables-page-helper.php
  src/integrations/admin/indexables-page-integration.php
  src/routes/indexables-route.php
Labels: changelog: non-user-facing

#18746 Handle getting custom fields replace vars when no indexable exists
  admin/metabox/class-metabox.php
Labels: changelog: non-user-facing

#18737 PC-296 Refactor routes into actions and add unit tests for integrations page
  src/actions/indexables-page-action.php
  src/routes/indexables-page-route.php
  src/routes/indexables-route.php
  tests/unit/actions/indexables-page-action-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: changelog: non-user-facing

#18741 Add five checkboxes about relevant testing scenarios
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: non-user-facing

#18720 P1 1425 file import component feedback
  packages/ui-library/.storybook/preview.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/src/components/file-import/index.js
  packages/ui-library/src/components/file-import/stories.js
  packages/ui-library/src/components/file-import/style.css
  packages/ui-library/src/components/root/index.js
  packages/ui-library/src/constants/index.js
  packages/ui-library/src/elements/alert/index.js
  packages/ui-library/src/elements/file-input/index.js
  packages/ui-library/src/elements/file-input/stories.js
  packages/ui-library/src/elements/file-input/style.css
  packages/ui-library/src/index.js
Labels: changelog: non-user-facing

#18748 PC-314 Set Algolia as disabled when not allowed at network level
  inc/options/class-wpseo-option-wpseo.php
Labels: changelog: non-user-facing

#18747 Pc 289 suggested links modal
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/indexables-page.js
  src/helpers/indexables-page-helper.php
  src/integrations/admin/indexables-page-integration.php
Labels: changelog: non-user-facing

#18740 PC-283 Adds support te remove an entire unicode emoji
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/src/helpers/replaceText.js
Labels: changelog: non-user-facing

#18751 Create new endpoint with useful setup info
  src/actions/indexables-page-action.php
  src/helpers/indexables-page-helper.php
  src/helpers/post-type-helper.php
  src/routes/indexables-page-route.php
  tests/unit/actions/indexables-page-action-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: changelog: non-user-facing

#18752 PC-320 Aligns behaviour in FTC with search appearance
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
Labels: changelog: non-user-facing

#18755 Remove user data request from settings integration
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#18761 Set minimum WP version to 5.9
  .github/workflows/integrationtest.yml
  tests/unit/bootstrap.php
  tests/unit/inc/addon-manager-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#18758 Do not continually load images when the content changes
  packages/js/src/analysis/blockEditorData.js
  packages/js/src/analysis/classicEditorData.js
Labels: changelog: enhancement

#18762 Pc 339 replacement fields suggestions not showing in metabox description field
  packages/search-metadata-previews/src/snippet-editor/SnippetEditorFields.js
  src/routes/meta-search-route.php
Labels: changelog: non-user-facing
