Repository Yoast/wordpress-seo, pull requests merged in 2022-02, with the labels that each got.

#18006 DUPP-248 Remove reference to `WPSEO_Admin_Asset_Yoast_Components_L10n`
  src/integrations/admin/installation-success-integration.php
Labels: changelog: non-user-facing

#18002 Dupp 215 add finish functionality stepper
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/Stepper.js
Labels: changelog: non-user-facing

#18019 Fix the jest configuration for seo integration package
  packages/helpers/src/index.js
  packages/helpers/src/replacement-variables/extractExcerptFromContent.js
  packages/seo-integration/package.json
  packages/seo-integration/src/replacement-variables/configurations.js
  packages/seo-integration/tests/replacement-variables/configurations.test.js
  yarn.lock
Labels: innovation, changelog: non-user-facing

#18014 Recognise internal link if link host is same as the user's site domain
  packages/yoastseo/spec/languageProcessing/helpers/url/urlSpec.js
  packages/yoastseo/src/languageProcessing/helpers/link/getLinkType.js
  packages/yoastseo/src/languageProcessing/helpers/url/url.js
Labels: changelog: non-user-facing

#18012 Animation tweaks and hopefully easier tuning of animations
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/StepCircle.js
  packages/js/src/workouts/components/Stepper.js
  packages/js/src/workouts/stepper-helper.js
Labels: changelog: non-user-facing

#18025 Add back build commands for seo-integration package after they were accidentally removed
  config/grunt/task-config/shell.js
Labels: innovation, changelog: non-user-facing

#18022 Fix the fallback value when there's no aioseo option to avoid PHP war…
  src/actions/importing/abstract-aioseo-settings-importing-action.php
  src/services/importing/aioseo-robots-provider-service.php
  src/services/importing/aioseo-robots-transformer-service.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/services/importing/aioseo-robots-provider-service-test.php
  tests/unit/services/importing/aioseo-robots-transformer-service-test.php
Labels: changelog: non-user-facing

#17990 Import social images from AIOSEO
  src/actions/importing/aioseo-posts-importing-action.php
  src/helpers/indexable-to-postmeta-helper.php
  src/services/importing/aioseo-social-images-provider-service.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
  tests/unit/helpers/indexable-to-postmeta-helper-test.php
  tests/unit/services/importing/aioseo-social-images-provider-service-test.php
  tests/unit/services/importing/importable-detector-test.php
  tests/unit/services/importing/importer-action-filter-trait-test.php
Labels: changelog: non-user-facing

#18027 P1 1189 create array of type validator
  src/validators/array-validator.php
  src/validators/news-sitemap-content-type-validator.php
  tests/unit/validators/news-sitemap-content-type-validator-test.php
Labels: changelog: non-user-facing

#18000 Facebook and Twitter preview images should use images, not backgrounds
  packages/js/src/containers/FacebookEditor.js
  packages/js/src/containers/TwitterEditor.js
  packages/js/src/helpers/selectMedia.js
  packages/social-metadata-previews/src/index.js
  packages/social-metadata-previews/src/shared/SocialImage.js
Labels: changelog: enhancement

#18008 Cleanup AIOSEO data
  admin/import/plugins/class-import-aioseo-v4.php
  packages/js/src/import.js
  src/actions/importing/aioseo-cleanup-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  src/integrations/admin/import-integration.php
  src/integrations/admin/indexing-tool-integration.php
  src/services/importing/importable-detector.php
  tests/unit/actions/importing/aioseo-cleanup-action-test.php
  tests/unit/integrations/admin/import-integration-test.php
  tests/unit/integrations/admin/indexing-tool-integration-test.php
  tests/unit/services/importing/importable-detector-test.php
Labels: changelog: non-user-facing

#18021 Check if default values in indexable fields before importing
  src/actions/importing/aioseo-posts-importing-action.php
  src/helpers/indexable-helper.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/helpers/indexable-helper-test.php
  tests/unit/services/importing/importable-detector-test.php
  tests/unit/services/importing/importer-action-filter-trait-test.php
Labels: changelog: non-user-facing

#18028 Plugin 1439 import wording changes
  admin/pages/tools.php
  admin/views/tabs/tool/import-seo.php
  packages/js/src/import.js
  src/integrations/admin/import-integration.php
  tests/unit/integrations/admin/import-integration-test.php
Labels: changelog: non-user-facing

#18031 Issue #17008 WPCOM CSS update to allow differing admin menu widths.
  css/src/admin-global.css
Labels: community-patch, changelog: bugfix

#18029 Plugin 1441 use fb data for twitter
  src/actions/importing/abstract-importing-action.php
  src/actions/importing/aioseo-posts-importing-action.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
Labels: changelog: non-user-facing

#18030 Optimize faq and how to images
  admin/tracking/class-tracking-default-data.php
  packages/js/src/structured-data-blocks/faq/components/Question.js
  packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: enhancement

#17989 wp-cron indexing
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-wpseo.php
  patchwork.json
  src/conditionals/wp-cron-enabled-conditional.php
  src/helpers/indexing-helper.php
  src/integrations/admin/background-indexing-integration.php
  src/values/indexables/indexable-builder-versions.php
  tests/unit/generators/schema/webpage-test.php
  tests/unit/helpers/indexing-helper-test.php
  tests/unit/integrations/admin/background-indexing-integration-test.php
Labels: changelog: enhancement

#18017 Add email validator
  src/exceptions/validation/invalid-email-exception.php
  src/validators/email-validator.php
  tests/unit/validators/email-validator-test.php
Labels: changelog: non-user-facing

#18018 P1-1191 create boolean validator
  src/services/options/site-options-service.php
  src/validators/boolean-validator.php
  tests/unit/validators/boolean-validator-test.php
Labels: changelog: non-user-facing

#18035 LINGO-1267 Adjusts the meta description length limit for Japanese
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/tests/classic-editor/helpers/dom.test.js
  packages/js/tests/classic-editor/initial-state.test.js
  packages/seo-integration/src/replacement-variables/configurations.js
  packages/seo-integration/tests/replacement-variables/configurations.test.js
  packages/seo-store/src/editor/slice.js
  packages/seo-store/src/editor/tests.js
Labels: innovation, changelog: non-user-facing

#18015 P1-1193 create integer validator
  src/exceptions/option/missing-configuration-key-exception.php
  src/exceptions/option/unknown-exception.php
  src/services/options/site-options-service.php
  src/validators/integer-validator.php
  tests/unit/validators/empty-string-validator-test.php
  tests/unit/validators/integer-validator-test.php
  tests/unit/validators/string-validator-test.php
  tests/unit/validators/url-validator-test.php
Labels: changelog: non-user-facing

#18041 Dupp 216 add edit buttons and logic
  css/src/tailwind.css
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/components/StepHeader.js
  packages/js/src/workouts/components/Stepper.js
Labels: changelog: non-user-facing

#18044 Never filter the title presenter on a REST request
  src/integrations/front-end-integration.php
  tests/unit/integrations/front-end-integration-test.php
Labels: community-patch, changelog: bugfix

#18039 Dupp 242 tailwindify indexation step
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/tailwind-components/ConfigurationIndexation.js
  packages/js/src/workouts/tailwind-components/Indexation.js
  packages/js/src/workouts/tailwind-components/IndexingError.js
  packages/js/src/workouts/tailwind-components/StepCircle.js
  packages/js/src/workouts/tailwind-components/StepHeader.js
  packages/js/src/workouts/tailwind-components/Stepper.js
  packages/js/src/workouts/tailwind-components/TailwindModal.js
  packages/js/src/workouts/tailwind-components/UnsavedChangesModal.js
  packages/js/src/workouts/tailwind-components/alert.js
Labels: changelog: non-user-facing

#18050 Fix failing tests with partial mocks with functions that take reference args
  patchwork.json
  src/integrations/admin/background-indexing-integration.php
  tests/unit/integrations/admin/background-indexing-integration-test.php
Labels: changelog: non-user-facing

#18054 Fix broken replacevar tags
  src/services/importing/aioseo-replacevar-handler.php
  tests/unit/services/importing/aioseo-replacevar-handler-test.php
Labels: changelog: non-user-facing

#18051 Should index filter
  src/helpers/indexable-helper.php
Labels: changelog: enhancement

#18062 [QA-2893] Do not optimize images if no post
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: non-user-facing

#18060 Remove keepPlaceholderOnFocus as it's now default behavior
  packages/js/src/structured-data-blocks/faq/components/Question.js
  packages/js/src/structured-data-blocks/how-to/components/HowTo.js
  packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
Labels: changelog: bugfix

#18020 P1-1195 create is equal validator
  src/exceptions/validation/invalid-value-exception.php
  src/services/options/site-options-service.php
  src/validators/array-validator.php
  src/validators/boolean-validator.php
  src/validators/email-validator.php
  src/validators/empty-string-validator.php
  src/validators/integer-validator.php
  src/validators/is-equal-validator.php
  src/validators/news-sitemap-content-type-validator.php
  src/validators/string-validator.php
  src/validators/url-validator.php
  src/validators/validator-interface.php
  tests/unit/helpers/validation-helper-test.php
  tests/unit/validators/is-equal-validator-test.php
Labels: changelog: non-user-facing

#18066 Add missing assignment and type check
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: non-user-facing

#18069 Refactor Stepper to use a Compound Component pattern
  packages/js/package.json
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/tailwind-components/ConfigurationStepperButtons.js
  packages/js/src/workouts/tailwind-components/StepCircle.js
  packages/js/src/workouts/tailwind-components/StepHeader.js
  packages/js/src/workouts/tailwind-components/Stepper.js
Labels: changelog: non-user-facing

#18072 Add extra check to prevent accessing non-existent array element
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: non-user-facing

#18033 P1-1197 create text validator
  src/services/options/site-options-service.php
  src/validators/text-field-validator.php
  tests/unit/validators/text-field-validator-test.php
Labels: changelog: non-user-facing

#18067 Add a fallback value when no primary category is explicitly selected
  packages/js/src/classic-editor/replacement-variables/configurations.js
  packages/js/tests/classic-editor/replacement-variables/configurations.test.js
Labels: innovation, changelog: non-user-facing

#18077 [QA-2898] Add max-width: 100% to images in structured data blocks
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: non-user-facing

#18073 Don't import social image url if featured image is selected
  src/actions/importing/aioseo-posts-importing-action.php
  src/helpers/indexable-to-postmeta-helper.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/helpers/indexable-to-postmeta-helper-test.php
Labels: changelog: non-user-facing

#18081 [QA-2900] Add height auto to structured data imgaes
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: non-user-facing

#18071 P1-1058 console warning image alt text is undefined
  packages/components/src/image-select/ImageSelect.js
  packages/js/package.json
  packages/js/src/components/ImageSelectComponent.js
  packages/js/src/components/social/SocialForm.js
  packages/js/src/containers/FacebookEditor.js
  packages/js/src/containers/TwitterEditor.js
  packages/js/src/elementor/containers/FacebookEditor.js
  packages/js/src/elementor/containers/TwitterEditor.js
  packages/js/src/helpers/selectMedia.js
  packages/js/src/redux/reducers/facebookEditor.js
  packages/js/src/redux/reducers/twitterEditor.js
  packages/js/src/redux/selectors/facebookEditor.js
  packages/js/src/redux/selectors/twitterEditor.js
  packages/js/src/settings.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
Labels: changelog: bugfix

#18078 LINGO-1294 Move seo-store tests to separate directory and add coverage report
  packages/seo-integration/readme.md
  packages/seo-store/package.json
  packages/seo-store/readme.md
  packages/seo-store/src/analysis/tests.js
  packages/seo-store/tests/analysis/hooks.test.js
  packages/seo-store/tests/analysis/slice/config.test.js
  packages/seo-store/tests/analysis/slice/index.test.js
  packages/seo-store/tests/analysis/slice/results.test.js
  packages/seo-store/tests/common/hooks.test.js
  packages/seo-store/tests/editor/slice.test.js
  packages/seo-store/tests/form/slice/keyphrases.test.js
  packages/seo-store/tests/form/slice/seo.test.js
Labels: changelog: non-user-facing

#18047 Refactor the new importing framework
  admin/import/plugins/class-import-aioseo-v4.php
  src/actions/importing/abstract-aioseo-importing-action.php
  src/actions/importing/aioseo/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-cleanup-action.php
  src/actions/importing/aioseo/aioseo-custom-archive-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-default-archive-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-general-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-posts-importing-action.php
  src/actions/importing/aioseo/aioseo-posttype-defaults-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-taxonomy-settings-importing-action.php
  src/actions/importing/deactivate-conflicting-plugins-action.php
  src/actions/importing/import-cursor-manager-trait.php
  src/helpers/import-cursor-helper.php
  src/integrations/admin/import-integration.php
  src/integrations/admin/indexing-tool-integration.php
  src/routes/importing-route.php
  src/services/importing/aioseo/aioseo-replacevar-service.php
  src/services/importing/aioseo/aioseo-robots-provider-service.php
  src/services/importing/aioseo/aioseo-robots-transformer-service.php
  src/services/importing/aioseo/aioseo-social-images-provider-service.php
  src/services/importing/importable-detector-service.php
  src/services/importing/importer-action-filter-trait.php
  tests/unit/actions/importing/abstract-aioseo-importing-action-test.php
  tests/unit/actions/importing/abstract-aioseo-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-cleanup-action-test.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/actions/importing/deactivate-conflicting-plugins-action-test.php
  tests/unit/doubles/actions/importing/abstract-aioseo-importing-action-double.php
  tests/unit/doubles/actions/importing/abstract-aioseo-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-custom-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-default-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-general-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-posts-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-posttype-defaults-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-taxonomy-settings-importing-action-double.php
  tests/unit/doubles/services/importing/importable-detector-service-double.php
  tests/unit/helpers/import-cursor-helper-test.php
  tests/unit/integrations/admin/import-integration-test.php
  tests/unit/integrations/admin/indexing-tool-integration-test.php
  tests/unit/routes/importing-route-test.php
  tests/unit/services/importing/aioseo-replacevar-service-test.php
  tests/unit/services/importing/aioseo-robots-provider-service-test.php
  tests/unit/services/importing/aioseo-robots-transformer-service-test.php
  tests/unit/services/importing/aioseo-social-images-provider-service-test.php
  tests/unit/services/importing/conflicting-plugins-service-test.php
  tests/unit/services/importing/importable-detector-service-test.php
  tests/unit/services/importing/importer-action-filter-trait-test.php
Labels: changelog: non-user-facing

#18082 Dupp 272 leftovers indexation step
  css/src/tailwind.css
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/tailwind-components/ConfigurationIndexation.js
  packages/js/src/workouts/tailwind-components/Indexation.js
  packages/js/src/workouts/tailwind-components/indexation-step.js
Labels: changelog: non-user-facing

#18087 Fix more broken replacevars in taxonomies
  src/actions/importing/aioseo/aioseo-taxonomy-settings-importing-action.php
  src/services/importing/aioseo/aioseo-replacevar-service.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/services/importing/aioseo-replacevar-service-test.php
Labels: changelog: non-user-facing

#18057 Rename parameters with reserved names in Taxonomy_Helper
  src/helpers/taxonomy-helper.php
Labels: changelog: non-user-facing

#18068 Facilitate removing partial mocks from the new import framework
  src/actions/importing/aioseo/abstract-aioseo-settings-importing-action.php
  src/helpers/import-helper.php
  tests/unit/actions/importing/aioseo-custom-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-default-archive-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-posttype-defaults-settings-importing-action-test.php
  tests/unit/actions/importing/aioseo-taxonomy-settings-importing-action-test.php
  tests/unit/doubles/actions/importing/aioseo-custom-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-default-archive-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-general-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-posttype-defaults-settings-importing-action-double.php
  tests/unit/doubles/actions/importing/aioseo-taxonomy-settings-importing-action-double.php
  tests/unit/helpers/import-helper-test.php
Labels: changelog: non-user-facing

#18086 P1-1232 create link element
  packages/ui-library/.gitignore
  packages/ui-library/.storybook/main.js
  packages/ui-library/.storybook/preview.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/package.json
  packages/ui-library/scripts/css.copy.js
  packages/ui-library/src/base.css
  packages/ui-library/src/elements/index.ts
  packages/ui-library/src/elements/link/index.js
  packages/ui-library/src/elements/link/link.css
  packages/ui-library/src/elements/link/stories.js
  packages/ui-library/src/introduction.stories.mdx
Labels: changelog: non-user-facing

#18089 Add Print QR code functionality
  admin/views/class-yoast-feature-toggles.php
  composer.json
  composer.lock
  config/php-scoper/php-qrcode.inc.php
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  src/conditionals/print-qrcode-enabled-conditional.php
  src/integrations/front-end/print-qrcode-embed.php
  src/integrations/front-end/print-qrcode-render.php
  tests/unit/admin/views/feature-toggles-test.php
Labels: UI change, changelog: enhancement

#18059 Remove the feature flag for AIOSEO importer
  admin/import/plugins/class-importers.php
  src/actions/importing/aioseo/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-cleanup-action.php
  src/actions/importing/aioseo/aioseo-posts-importing-action.php
  src/actions/importing/deactivate-conflicting-plugins-action.php
  src/conditionals/aioseo-v4-importer-conditional.php
  src/conditionals/updated-importer-framework-conditional.php
  src/integrations/admin/import-integration.php
  src/routes/importing-route.php
  tests/integration/admin/import/test-class-importers.php
  tests/unit/admin/import/plugins/importers-test.php
  tests/unit/integrations/admin/import-integration-test.php
  tests/unit/routes/importing-route-test.php
Labels: changelog: enhancement

#18097 Don't import social image url if auto image is selected and there is …
  src/actions/importing/aioseo/aioseo-posts-importing-action.php
  src/services/importing/aioseo/aioseo-social-images-provider-service.php
  tests/unit/actions/importing/aioseo-posts-importing-action-test.php
Labels: changelog: non-user-facing

#18101 UI library nolle
  packages/postcss-preset/index.js
  packages/tailwindcss-preset/index.js
  packages/tailwindcss-preset/package.json
  packages/ui-library/.storybook/main.js
  packages/ui-library/.storybook/preview.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/README.md
  packages/ui-library/package.json
  packages/ui-library/scripts/css.copy.js
  packages/ui-library/src/base.css
  packages/ui-library/src/components/checkbox-group/index.js
  packages/ui-library/src/components/checkbox-group/stories.js
  packages/ui-library/src/components/checkbox-group/style.css
  packages/ui-library/src/components/radio-group/index.js
  packages/ui-library/src/components/radio-group/stories.js
  packages/ui-library/src/components/radio-group/style.css
  packages/ui-library/src/components/toggle-field/index.js
  packages/ui-library/src/components/toggle-field/stories.js
  packages/ui-library/src/components/toggle-field/style.css
  packages/ui-library/src/elements/Button/button.css
  packages/ui-library/src/elements/Button/index.js
  packages/ui-library/src/elements/Button/stories.js
  packages/ui-library/src/elements/Button/style.css
  packages/ui-library/src/elements/Spinner/index.js
  packages/ui-library/src/elements/Title/stories.js
  packages/ui-library/src/elements/Title/style.css
  packages/ui-library/src/elements/alert/index.js
  packages/ui-library/src/elements/alert/stories.js
  packages/ui-library/src/elements/alert/style.css
  packages/ui-library/src/elements/badge/index.js
  packages/ui-library/src/elements/badge/stories.js
  packages/ui-library/src/elements/badge/style.css
  packages/ui-library/src/elements/checkbox/index.js
  packages/ui-library/src/elements/checkbox/stories.js
  packages/ui-library/src/elements/checkbox/style.css
  packages/ui-library/src/elements/label/index.js
  packages/ui-library/src/elements/label/stories.js
  packages/ui-library/src/elements/label/style.css
  packages/ui-library/src/elements/link/link.css
  packages/ui-library/src/elements/link/stories.js
  packages/ui-library/src/elements/link/style.css
  packages/ui-library/src/elements/radio/index.js
  packages/ui-library/src/elements/radio/stories.js
  packages/ui-library/src/elements/radio/style.css
  packages/ui-library/src/elements/toggle/index.js
  packages/ui-library/src/elements/toggle/stories.js
  packages/ui-library/src/elements/toggle/style.css
  yarn.lock
Labels: changelog: non-user-facing

#18080 Move documentation from wiki to readme files on repo
  packages/yoastseo/MORPHOLOGY.md
  packages/yoastseo/README.md
  packages/yoastseo/src/scoring/README.md
  packages/yoastseo/src/scoring/assessments/README.md
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/SCORING SEO.md
Labels: changelog: non-user-facing

#18102 P1-1239 create input element component
  packages/ui-library/.storybook/style.css
  packages/ui-library/src/components/text-field/index.js
  packages/ui-library/src/components/text-field/stories.js
  packages/ui-library/src/components/text-field/style.css
  packages/ui-library/src/elements/text-input/index.js
  packages/ui-library/src/elements/text-input/stories.js
  packages/ui-library/src/elements/text-input/style.css
Labels: changelog: non-user-facing

#18105 P1-1240: create select element
  packages/ui-library/src/components/select-field/index.js
  packages/ui-library/src/components/select-field/stories.js
  packages/ui-library/src/components/select-field/style.css
  packages/ui-library/src/elements/select/index.js
  packages/ui-library/src/elements/select/stories.js
  packages/ui-library/src/elements/select/style.css
Labels: changelog: non-user-facing

#18096 Fix updating for excerpt from content in Google preview
  packages/js/src/classic-editor/helpers/dom.js
  packages/js/src/classic-editor/initial-state.js
  packages/js/tests/classic-editor/helpers/dom.test.js
  packages/js/tests/classic-editor/initial-state.test.js
  packages/seo-integration/src/replacement-variables/configurations.js
Labels: innovation, changelog: non-user-facing

#18113 Fix detecting images as external when they are not
  .travis.yml
  inc/class-upgrade.php
  src/helpers/image-helper.php
Labels: changelog: bugfix

#18117 Trigger update routine for 18.3-RC3
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#18120 Composer/CS/QA: minor tweaks
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#18112 Remove QR code after print and only display if there is a URL
  src/integrations/front-end/print-qrcode-embed.php
Labels: changelog: non-user-facing

#18127 Dupp 297 fix how to images custom width
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: bugfix

#18023 P1-1196 create regex validator
  src/exceptions/validation/missing-settings-key-exception.php
  src/exceptions/validation/no-regex-groups-exception.php
  src/exceptions/validation/no-regex-match-exception.php
  src/services/options/site-options-service.php
  src/validators/regex-validator.php
  tests/unit/validators/regex-validator-test.php
Labels: changelog: non-user-facing

#18111 Move step to tailwind-components and temporarily import non-tailwind …
  .eslintrc
  css/src/tailwind.css
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/tailwind-components/ConfigurationStepperButtons.js
  packages/js/src/workouts/tailwind-components/StepCircle.js
  packages/js/src/workouts/tailwind-components/StepHeader.js
  packages/js/src/workouts/tailwind-components/Stepper.js
  packages/js/src/workouts/tailwind-components/TailwindModal.js
  packages/js/src/workouts/tailwind-components/UnsavedChangesModal.js
  packages/js/src/workouts/tailwind-components/base/alert.js
  packages/js/src/workouts/tailwind-components/base/image-select.js
  packages/js/src/workouts/tailwind-components/base/multi-line-text.js
  packages/js/src/workouts/tailwind-components/base/single-select.js
  packages/js/src/workouts/tailwind-components/base/spinner.js
  packages/js/src/workouts/tailwind-components/base/text-input.js
  packages/js/src/workouts/tailwind-components/helpers/index.js
  packages/js/src/workouts/tailwind-components/steps/indexation/ConfigurationIndexation.js
  packages/js/src/workouts/tailwind-components/steps/indexation/Indexation.js
  packages/js/src/workouts/tailwind-components/steps/indexation/IndexingError.js
  packages/js/src/workouts/tailwind-components/steps/indexation/indexation-step.js
  packages/js/src/workouts/tailwind-components/steps/site-representation/organization-section.js
  packages/js/src/workouts/tailwind-components/steps/site-representation/person-section.js
  packages/js/src/workouts/tailwind-components/steps/site-representation/site-representation-step.js
  packages/js/src/workouts/tailwind-components/steps/site-representation/user-selector.js
  src/integrations/admin/configuration-workout-integration.php
  tailwind.config.js
Labels: changelog: non-user-facing

#18129 Change Indexation step success alert copy
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/tailwind-components/Stepper.js
  packages/js/src/workouts/tailwind-components/steps/indexation/ConfigurationIndexation.js
  packages/js/src/workouts/tailwind-components/steps/indexation/Indexation.js
  packages/js/src/workouts/tailwind-components/steps/indexation/indexation-step.js
Labels: changelog: non-user-facing

#18115 Dupp 283 modal for when indexation is running
  packages/js/src/workouts/components/ConfigurationWorkout.js
  packages/js/src/workouts/tailwind-components/unsaved-changes-modal.js
Labels: changelog: non-user-facing

#18125 P1 1246 storyshots
  packages/jest-preset/jest-preset.js
  packages/jest-preset/package.json
  packages/ui-library/.storybook/preview.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/jest.config.js
  packages/ui-library/package.json
  packages/ui-library/scripts/build-css.js
  packages/ui-library/src/components/checkbox-group/stories.js
  packages/ui-library/src/elements/alert/stories.js
  packages/ui-library/src/elements/button/stories.js
  packages/ui-library/src/elements/button/style.css
  packages/ui-library/src/introduction.stories.mdx
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-alert-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-alert-variants-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-badge-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-badge-variants-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-button-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-button-sizes-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-button-states-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-button-variants-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-checkbox-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-label-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-link-anchor-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-link-button-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-link-custom-component-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-link-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-radio-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-radio-variants-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-select-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-select-states-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-text-input-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-title-as-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-title-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-title-sizes-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-toggle-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-checkbox-group-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-checkbox-group-with-label-and-description-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-checkbox-group-with-values-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-input-field-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-input-field-with-error-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-input-field-with-label-and-description-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-radio-group-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-radio-group-variants-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-radio-group-with-label-and-description-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-radio-group-with-value-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-select-field-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-select-field-with-error-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-select-field-with-label-and-description-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-toggle-field-checked-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-toggle-field-factory-1-snap.png
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-2-components-toggle-field-with-label-and-description-1-snap.png
  packages/ui-library/tests/mocks/mdx.js
  packages/ui-library/tests/storyshots.js
  yarn.lock
Labels: changelog: non-user-facing
