Repository Yoast/wordpress-seo, pull requests merged in 2023-11, with the labels that each got.

#20816 154 add notification when new woo product editor is switched on
  src/integrations/watchers/woocommerce-beta-editor-watcher.php
  src/presenters/admin/woocommerce-beta-editor-presenter.php
  tests/unit/integrations/watchers/woocommerce-beta-editor-watcher-test.php
  tests/unit/presenters/admin/woocommerce-beta-editor-presenter-test.php
Labels: UI change, changelog: other

#20817 fix introduction modal for admin pages
  packages/js/src/ai-generator/components/modal-content.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
Labels: changelog: non-user-facing

#20815 Add unit tests for parseBlocks.js inside yoastseo#191
  packages/yoastseo/spec/parse/build/private/parseBlocksSpec.js
Labels: technical-debt, changelog: non-user-facing

#20822 Toggle notices and upsell ads in FTC
  packages/js/src/initializers/admin.js
Labels: UI change, changelog: non-user-facing

#20813 Improve new installation screen
  images/man_with_tablet.png
  packages/js/src/first-time-configuration/tailwind-components/step-circle.js
  packages/js/src/installation-success.js
Labels: UI change, changelog: non-user-facing

#20823 Fix initial state for site name based on fallback
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
Labels: changelog: bugfix

#20800 Avoid storing the full user object in notifications meta
  admin/class-yoast-notification-center.php
  admin/class-yoast-notification.php
  tests/integration/notifications/test-class-yoast-notification-center.php
  tests/integration/notifications/test-class-yoast-notification.php
  tests/unit/admin/admin-features-test.php
  tests/unit/admin/admin-gutenberg-compatibility-notification-test.php
  tests/unit/content-type-visibility/application/content-type-visibility-watcher-actions-test.php
  tests/unit/inc/addon-manager-test.php
  tests/unit/integrations/admin/indexing-notification-integration-test.php
  tests/unit/integrations/third-party/wpml-wpseo-notification-test.php
  tests/unit/integrations/watchers/search-engines-discouraged-watcher-test.php
Labels: changelog: non-user-facing

#20825 Add indexation disabled check before showing user an alert
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
Labels: changelog: enhancement

#20814 Improves translatability of social appearance upsell label
  packages/js/src/components/social/SocialUpsell.js
Labels: changelog: non-user-facing

#20828 Replace metabox open modal button
  packages/js/src/components/WincherSEOPerformanceModal.js
Labels: UI change, changelog: non-user-facing

#20827 Use the Person piece only for publishers.
  src/generators/schema/person.php
  tests/unit/generators/schema/person-test.php
Labels: changelog: bugfix

#20824 Wincher/fix modal issues
  packages/js/src/components/WincherRankingHistoryChart.js
  packages/js/src/components/WincherSEOPerformance.js
Labels: community-patch, fix-before-release

#20830 Fix test_manage_woocommerce_beta_editor_notification_not_active_and_…
  tests/unit/integrations/watchers/woocommerce-beta-editor-watcher-test.php
Labels: changelog: non-user-facing

#20833 Fix the spacing in the Wincher modal
  css/src/modal.css
  packages/js/src/components/WincherSEOPerformanceModal.js
Labels: changelog: non-user-facing

#20836 Adds extra security to new API Endpoint.
  src/introductions/application/introductions-collector.php
  src/introductions/user-interface/introductions-seen-route.php
  tests/unit/introductions/application/introductions-collector-test.php
  tests/unit/introductions/user-interface/introductions-seen-route-test.php
Labels: changelog: non-user-facing

#20837 Add target and rel to the Wincher "View" button
  packages/js/src/components/WincherTableRow.js
Labels: changelog: non-user-facing

#20842 Fix title alignment
  packages/js/src/components/MetaboxButton.js
Labels: changelog: non-user-facing

#20844 No longer presume the event is defined
  packages/js/src/components/modals/editorModals/EditorModal.js
Labels: changelog: non-user-facing

#20845 Insights: Watches all data/modifications instead of just the editor content
  packages/js/src/elementor.js
  packages/js/src/elementor/containers/SnippetEditor.js
  packages/js/src/elementor/redux/selectors/analysis.js
  packages/js/src/elementor/replaceVars/elementor-replacevar-plugin.js
  packages/js/src/initializers/analysis.js
  packages/js/src/initializers/pluggable.js
  packages/js/src/insights/initializer.js
Labels: changelog: bugfix

#20851 Wincher modal fixes
  packages/js/src/components/WincherSEOPerformance.js
  packages/js/src/components/WincherTableRow.js
Labels: community-patch, changelog: bugfix

#20854 Tests/Integration - WPSEO_UnitTestCase: remove `expect_reflection_deprecation_warning_php74()`
  tests/integration/admin/services/test-class-file-size.php
  tests/integration/admin/test-class-plugin-suggestions.php
  tests/integration/framework/class-wpseo-unit-test-case.php
  tests/integration/framework/reflectiontostring-deprecation-handler-trait.php
  tests/integration/inc/test-class-wpseo-admin-bar-menu.php
  tests/integration/notifications/test-class-yoast-notification-center.php
  tests/integration/notifiers/test-class-dismissible-notification.php
  tests/integration/test-class-admin-asset-manager.php
Labels: yoast cs/qa, changelog: non-user-facing

#20856 GH Actions: enable linting and testing against PHP 8.3
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: other

#20812 Provide a filter to parse shortcodes
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/src/analysis/plugins/shortcode-plugin.js
  packages/js/src/components/contentAnalysis/Results.js
  packages/js/src/containers/Results.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/initializers/term-scraper.js
  packages/js/src/lib/tinymce.js
  packages/js/src/redux/actions/analysis.js
  packages/js/src/redux/reducers/analysisData.js
  packages/js/src/redux/selectors/analysis.js
  packages/js/tests/analysis/plugins/shortcode-plugin.test.js
  packages/js/tests/redux/reducers/analysisData.test.js
  packages/yoastseo/src/pluggable.js
  src/integrations/third-party/elementor.php
Labels: changelog: other

#20859 Tests/WP: remove some redundant skip conditions
  tests/integration/admin/import/test-class-import-settings.php
Labels: yoast cs/qa, changelog: non-user-facing

#20861 Tests/Integration: clean up test doubles/mocks
  tests/Unit/Admin/Roles/Role_Manager_Test.php
  tests/Unit/Doubles/Admin/Role_Manager_Mock.php
  tests/integration/doubles/class-opengraph-image-double.php
  tests/integration/doubles/wpseo-option-xml-double.php
  tests/integration/doubles/wpseo-wp-rest-server-mock.php
Labels: yoast cs/qa, changelog: non-user-facing

#20846 Add upsell for the highlighting feature in Elementor
  admin/class-expose-shortlinks.php
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/src/ContentAnalysis.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/Results.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/initializers/editor-store.js
Labels: changelog: non-user-facing

#20876 Composer.json: add link to security policy
  .github/SECURITY.md
  composer.json
Labels: yoast cs/qa, changelog: other

#20877 GH Actions: switch to Coveralls action runner to upload reports
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: non-user-facing

#20878 GH Actions: update a few links in inline comments
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: non-user-facing

#20863 Removes certain Elementor widgets from our content analysis
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlParserSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeEstimatedReadingTimeSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeTableOfContentsTagSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/sanitizeStringSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/countCharactersSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/getWordsSpec.js
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/filterTreeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/htmlParser.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeEstimatedReadingTime.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeTableOfContentsTag.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeString.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/countCharacters.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/getWords.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
  packages/yoastseo/src/languageProcessing/researches/getSubheadingTextLengths.js
  packages/yoastseo/src/languageProcessing/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/parse/build/private/alwaysFilterElements.js
  packages/yoastseo/src/parse/build/private/filterTree.js
Labels: changelog: other

#20858 Various copy improvements in the FTC
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/configuration-indexation.js
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation-step.js
  packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
  packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/personal-preferences-step.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/site-representation-step.js
  packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-profiles-step.js
Labels: changelog: other

#20873 Centers the eye icon in the highlighting button using CSS flexbox
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/IconButtonToggle.js
  packages/components/tests/__snapshots__/IconButtonToggleTest.js.snap
Labels: UI change, changelog: enhancement

#20875 Improves the test coverage for our base Assessment class
  packages/yoastseo/spec/scoring/assessments/assessmentSpec.js
  packages/yoastseo/src/scoring/assessments/assessment.js
  packages/yoastseo/src/scoring/assessments/index.js
Labels: changelog: non-user-facing
