Repository Yoast/wordpress-seo, pull requests merged in 2023-05, with the labels that each got.

#20226 Fix fatal error on Yoast admin pages with WooCommerce SEO
  admin/tracking/class-tracking-addon-data.php
Labels: changelog: bugfix

#20146 Add check for archive pages to make sure indexables are only built when needed.
  inc/class-upgrade.php
  src/actions/indexing/indexable-post-type-archive-indexation-action.php
  src/analytics/application/to-be-cleaned-indexables-collector.php
  src/builders/indexable-post-type-archive-builder.php
  src/exceptions/indexable/post-type-not-built-exception.php
  src/helpers/post-helper.php
  src/helpers/post-type-helper.php
  src/integrations/cleanup-integration.php
  src/repositories/indexable-cleanup-repository.php
  tests/unit/actions/indexing/indexable-post-type-archive-indexation-action-test.php
  tests/unit/analytics/application/to-be-cleaned-indexables-collector-test.php
  tests/unit/builders/indexable-post-type-archive-builder-test.php
  tests/unit/helpers/post-type-helper-test.php
  tests/unit/integrations/academy-integration-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/repositories/indexable-cleanup-repository-test.php
Labels: innovation, changelog: bugfix

#20212 Exclude text within text area tags from the content analysis
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlParserSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/htmlParser.js
Labels: changelog: enhancement

#20216 Fix Elementor 3.13 compatibility
  css/src/elementor.css
  packages/js/src/initializers/elementor-editor-integration.js
Labels: changelog: enhancement

#20237 Set wpdb registration in the container public
  config/dependency-injection/services.php
Labels: changelog: non-user-facing

#20213 Update feedback strings for assessments that use both the focus and related keyphrases
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/scoring/assessments/SCORING SEO.md
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
Labels: changelog: enhancement, Shopify

#20222 Seo links repository tests
  tests/integration/repositories/seo-links-repository-test.php
  tests/unit/integrations/academy-integration-test.php
  tests/unit/repositories/seo-links-repository-test.php
Labels: changelog: non-user-facing

#20238 Unlock courses in the Academy page when relevant add-on is installed
  packages/js/src/academy/app.js
  src/integrations/academy-integration.php
  tests/unit/integrations/academy-integration-test.php
Labels: changelog: non-user-facing

#20157 Adds the inclusive language score as an indexable column
  inc/class-wpseo-rank.php
  packages/js/src/helpers/fields/AnalysisFields.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/initializers/term-scraper.js
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/config/migrations/20230417083836_AddInclusiveLanguageScore.php
  src/helpers/score-icon-helper.php
  src/models/indexable.php
  tests/integration/test-class-wpseo-rank.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/doubles/models/indexable-mock.php
  tests/unit/helpers/score-icon-helper-test.php
Labels: changelog: non-user-facing

#20248 Use the Addon_Manager to check if addons are activated
  src/integrations/academy-integration.php
  tests/unit/integrations/academy-integration-test.php
Labels: changelog: non-user-facing

#20250 Merge feature branch into trunk
  inc/class-wpseo-rank.php
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/contentAnalysis/mapResults.js
  packages/js/src/components/portals/ScoreIconPortal.js
  packages/js/src/helpers/fields/AnalysisFields.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/initializers/term-scraper.js
  packages/js/tests/components/contentAnalysis/mapResults.test.js
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper1.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper3.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlParserSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/helpers/html/htmlParser.js
  packages/yoastseo/src/scoring/assessments/SCORING SEO.md
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  src/builders/indexable-post-builder.php
  src/builders/indexable-term-builder.php
  src/config/migrations/20230417083836_AddInclusiveLanguageScore.php
  src/helpers/score-icon-helper.php
  src/models/indexable.php
  tests/integration/test-class-wpseo-rank.php
  tests/unit/builders/indexable-post-builder-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/doubles/models/indexable-mock.php
  tests/unit/helpers/score-icon-helper-test.php
Labels: changelog: non-user-facing

#20251 Remove Zapier integration from readme
  readme.txt
Labels: community-patch, changelog: non-user-facing

#20069 Tests for Indexable_Link_Builder
  .gitignore
  src/builders/indexable-link-builder.php
  src/generators/schema/webpage.php
  tests/patchwork.json
  tests/unit/builders/indexable-link-builder/abstract-indexable-link-builder-testcase.php
  tests/unit/builders/indexable-link-builder/build-test.php
  tests/unit/builders/indexable-link-builder/create-internal-link-test.php
  tests/unit/builders/indexable-link-builder/delete-test.php
  tests/unit/builders/indexable-link-builder/get-permalink-test.php
  tests/unit/builders/indexable-link-builder/patch-seo-links-test.php
  tests/unit/builders/indexable-link-builder/update-incoming-links-for-related-test.php
  tests/unit/doubles/builders/indexable-link-builder-double.php
Labels: changelog: non-user-facing

#20259 Adds a grouping array around the new indexable tracking info.
  src/analytics/application/missing-indexables-collector.php
  src/analytics/application/to-be-cleaned-indexables-collector.php
  tests/unit/analytics/application/missing-indexables-collector-test.php
  tests/unit/analytics/application/to-be-cleaned-indexables-collector-test.php
Labels: changelog: non-user-facing

#20261 Added key to taxonomy submenu items
  packages/js/src/settings/app.js
Labels: changelog: bugfix

#20268 Reverts Cron indexation
  src/commands/index-command.php
  src/conditionals/wp-cron-enabled-conditional.php
  src/helpers/indexing-helper.php
  src/integrations/admin/background-indexing-integration.php
  tests/unit/commands/index-command-test.php
  tests/unit/conditionals/wp-cron-enabled-conditional-test.php
  tests/unit/generators/schema/webpage-test.php
  tests/unit/helpers/indexing-helper-test.php
  tests/unit/integrations/admin/background-indexing-integration-test.php
Labels: changelog: non-user-facing

#20272 Composer: update test dependencies
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#20273 Integration tests: update script to install WP
  config/scripts/install-wp-tests.sh
Labels: yoast cs/qa, changelog: non-user-facing

#20274 GH Actions: fix minor spelling snafu
  .github/workflows/cs.yml
Labels: yoast cs/qa, changelog: non-user-facing

#20275 Tests: `TestCase` classes should be abstract
  tests/unit/builders/indexable-link-builder/abstract-indexable-link-builder-testcase.php
Labels: yoast cs/qa, changelog: non-user-facing

#20276 Dependabot: add reviewer config
  .github/dependabot.yml
Labels: yoast cs/qa, changelog: non-user-facing

#20278 Re-enable indexing.
  admin/tracking/class-tracking.php
Labels: changelog: non-user-facing

#20270 20015 difficulty in adding a link in the editor as the box positioning is off
  packages/js/package.json
  packages/js/src/inline-links/inline.js
Labels: UI change, changelog: bugfix

#20287 CS/QA: fix up import `use` statements
  admin/class-config.php
  admin/metabox/class-metabox-section-inclusive-language.php
  config/dependency-injection/services.php
  lib/abstract-main.php
  lib/migrations/adapter.php
  src/analytics/user-interface/last-completed-indexation-integration.php
  src/builders/indexable-post-type-archive-builder.php
  src/commands/cleanup-command.php
  src/conditionals/third-party/jetpack-boost-not-premium-conditional.php
  src/deprecated/src/integrations/admin/redirect-old-features-tab-integration.php
  src/deprecated/src/integrations/third-party/the-events-calendar.php
  src/generators/schema/article.php
  src/helpers/crawl-cleanup-helper.php
  src/helpers/wincher-helper.php
  src/initializers/crawl-cleanup-permalinks.php
  src/integrations/academy-integration.php
  src/integrations/admin/activation-cleanup-integration.php
  src/integrations/admin/first-time-configuration-notice-integration.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/admin/integrations-page.php
  src/integrations/alerts/jetpack-boost-pre-publish.php
  src/integrations/cleanup-integration.php
  src/integrations/front-end/crawl-cleanup-searches.php
  src/integrations/settings-integration.php
  src/integrations/third-party/elementor.php
  src/integrations/watchers/indexable-attachment-watcher.php
  src/repositories/indexable-cleanup-repository.php
  tests/integration/repositories/seo-links-repository-test.php
  tests/unit/actions/indexing/indexable-post-type-archive-indexation-action-test.php
  tests/unit/admin/admin-user-profile-test.php
  tests/unit/admin/import/import-settings-test.php
  tests/unit/analytics/user-interface/last-completed-indexation-integration-test.php
  tests/unit/builders/indexable-builder/build-test.php
  tests/unit/builders/indexable-link-builder/build-test.php
  tests/unit/builders/indexable-link-builder/create-internal-link-test.php
  tests/unit/builders/indexable-link-builder/delete-test.php
  tests/unit/builders/indexable-link-builder/get-permalink-test.php
  tests/unit/builders/indexable-link-builder/patch-seo-links-test.php
  tests/unit/builders/indexable-link-builder/update-incoming-links-for-related-test.php
  tests/unit/builders/indexable-post-type-archive-builder-test.php
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/conditionals/third-party/elementor-edit-conditional-test.php
  tests/unit/doubles/actions/indexing/abstract-indexing-action-double.php
  tests/unit/generators/schema/article-test.php
  tests/unit/helpers/crawl-cleanup-helper-test.php
  tests/unit/helpers/post-type-helper-test.php
  tests/unit/initializers/crawl-cleanup-permalinks-test.php
  tests/unit/integrations/academy-integration-test.php
  tests/unit/integrations/admin/activation-cleanup-integration-test.php
  tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
  tests/unit/integrations/admin/old-configuration-integration-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/integrations/front-end/crawl-cleanup-searches-test.php
  tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
  tests/unit/integrations/watchers/indexable-taxonomy-change-watcher-test.php
  tests/unit/integrations/watchers/primary-category-quick-edit-watcher-test.php
  tests/unit/presenters/admin/migration-error-presenter-test.php
  tests/unit/repositories/indexable-cleanup-repository-test.php
  tests/unit/repositories/indexable-hierarchy-repository-test.php
  tests/unit/repositories/seo-links-repository-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20288 Tests: fix some tests which werent being run
  tests/integration/admin/watchers/test-class-indexable-post-watcher.php
  tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20289 Tests: `set_up()` methods cannot "cover" anything
  tests/unit/helpers/crawl-cleanup-helper-test.php
  tests/unit/initializers/crawl-cleanup-permalinks-test.php
  tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20290 Tests: sync `Addon_Manager_Double` with parent class
  tests/unit/doubles/inc/addon-manager-double.php
  tests/unit/inc/addon-manager-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20291 QA: various parameter name fixes
  config/dependency-injection/deprecated-classes.php
  src/loader.php
  tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20292 CS/QA: static closures should be declared as static
  src/analytics/domain/missing-indexable-bucket.php
  src/analytics/domain/to-be-cleaned-indexable-bucket.php
  src/generators/breadcrumbs-generator.php
  src/repositories/indexable-cleanup-repository.php
  tests/integration/test-wpseo-functions.php
Labels: yoast cs/qa, changelog: non-user-facing

#20293 CS/QA: use the appropriate PHP native function
  inc/class-wpseo-meta.php
Labels: yoast cs/qa, changelog: non-user-facing

#20294 CS/QA: use `self` when refering to current class
  src/exceptions/indexable/author-not-built-exception.php
  src/exceptions/indexable/not-built-exception.php
  src/exceptions/indexable/post-not-built-exception.php
  src/exceptions/indexable/post-type-not-built-exception.php
  src/exceptions/indexable/term-not-built-exception.php
Labels: yoast cs/qa, changelog: non-user-facing

#20295 QA: fix various unused/undeclared variable issues
  admin/import/plugins/class-import-seopressor.php
  inc/class-upgrade.php
  inc/class-wpseo-meta.php
  inc/options/class-wpseo-options.php
  inc/sitemaps/class-sitemap-image-parser.php
  inc/sitemaps/class-sitemaps-renderer.php
  lib/migrations/table.php
  lib/model.php
  src/actions/wincher/wincher-keyphrases-action.php
  src/generators/schema/faq.php
  src/presenters/open-graph/image-presenter.php
  tests/integration/admin/test-class-database-proxy.php
  tests/integration/repositories/seo-links-repository-test.php
  tests/integration/test-class-rewrite.php
  tests/unit/actions/importing/abstract-aioseo-importing-action-test.php
  tests/unit/actions/importing/aioseo-general-settings-importing-action-test.php
  tests/unit/admin/admin-features-test.php
  tests/unit/builders/indexable-builder/maybe-build-author-indexable-test.php
  tests/unit/helpers/crawl-cleanup-helper-test.php
  tests/unit/helpers/social-profiles-helper-test.php
  tests/unit/repositories/orm-test.php
  tests/unit/surfaces/helpers-surface-test.php
  tests/unit/surfaces/open-graph-helpers-surface-test.php
  tests/unit/surfaces/schema-helpers-surface-test.php
  tests/unit/surfaces/twitter-helpers-surface-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20297 CS/QA: use fully qualified function calls/constants in the right places
  config/dependency-injection/loader-pass.php
  src/analytics/application/missing-indexables-collector.php
  src/commands/cleanup-command.php
  src/deprecated/i18n/i18n-v3.php
  src/deprecated/src/integrations/admin/social-templates-integration.php
  src/generators/schema/howto.php
  src/helpers/redirect-helper.php
  src/helpers/short-link-helper.php
  src/integrations/admin/activation-cleanup-integration.php
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/admin/integrations-page.php
  src/integrations/blocks/structured-data-blocks.php
  src/integrations/front-end/open-graph-oembed.php
  src/integrations/third-party/wincher.php
  src/integrations/third-party/wordproof-integration-toggle.php
  src/integrations/watchers/indexable-attachment-watcher.php
  src/repositories/indexable-cleanup-repository.php
  tests/integration/admin/watchers/test-class-indexable-post-watcher.php
  tests/unit/helpers/short-link-helper-test.php
  tests/unit/integrations/admin/activation-cleanup-integration-test.php
  tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
  tests/unit/repositories/indexable-cleanup-repository-test.php
  wp-seo-main.php
Labels: yoast cs/qa, changelog: non-user-facing

#20296 CS/QA: update some ignore annotations
  inc/wpseo-functions-deprecated.php
  lib/abstract-main.php
  src/surfaces/helpers-surface.php
  src/surfaces/open-graph-helpers-surface.php
  src/surfaces/schema-helpers-surface.php
  src/surfaces/twitter-helpers-surface.php
  src/surfaces/values/meta.php
Labels: yoast cs/qa, changelog: non-user-facing

#20300 CS/QA: don't pass parameter which doesn't exist
  src/integrations/admin/crawl-settings-integration.php
Labels: yoast cs/qa, changelog: non-user-facing

#20286 20103 tighten crawl optimization site search blocking rules
  packages/js/src/settings/routes/crawl-optimization.js
  src/integrations/front-end/robots-txt-integration.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
Labels: changelog: enhancement

#20305 Background cron indexation
  src/commands/index-command.php
  src/conditionals/wp-cron-enabled-conditional.php
  src/helpers/indexing-helper.php
  src/integrations/admin/background-indexing-integration.php
  tests/unit/commands/index-command-test.php
  tests/unit/conditionals/wp-cron-enabled-conditional-test.php
  tests/unit/generators/schema/webpage-test.php
  tests/unit/helpers/indexing-helper-test.php
  tests/unit/integrations/admin/background-indexing-integration-test.php
Labels: changelog: enhancement

#20302 Tests: add missing assertions
  tests/unit/builders/indexable-term-builder-test.php
  tests/unit/repositories/seo-links-repository-test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20303 CS/QA: fix inconsistent return types
  src/helpers/current-page-helper.php
Labels: yoast cs/qa, changelog: other

#20309 GH Actions: merge unit and integration test workflows
  .github/workflows/test.yml
  .github/workflows/unittest.yml
  README.md
Labels: yoast cs/qa, changelog: non-user-facing

#20310 CI/QA: start recording code coverage
  .github/workflows/test.yml
  .gitignore
  README.md
  composer.json
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#20311 CS/QA: lower thresholds
  composer.json
  packages/yoastseo/grunt/config/eslint.js
Labels: yoast cs/qa, changelog: non-user-facing

#20312 PHP 8.2 | Indexable_*_Presentation: declare the property in the trait instead
  src/presentations/archive-adjacent-trait.php
  src/presentations/indexable-author-archive-presentation.php
  src/presentations/indexable-home-page-presentation.php
  src/presentations/indexable-post-type-archive-presentation.php
  src/presentations/indexable-term-archive-presentation.php
Labels: yoast cs/qa, changelog: non-user-facing

#20257 Don't introduce expensive queries in new places in the admin
  src/integrations/admin/background-indexing-integration.php
  src/integrations/admin/indexing-notification-integration.php
  tests/unit/integrations/admin/background-indexing-integration-test.php
  tests/unit/integrations/admin/indexing-notification-integration-test.php
Labels: changelog: non-user-facing

#20336 Prevents metabox crashing when the additional keywords objects are malformed
  packages/js/src/redux/selectors/WincherSEOPerformance.js
Labels: changelog: bugfix

#20284 Remove usage of yoast-components
  admin/class-admin-asset-manager.php
  css/src/notifications-new.css
  css/src/notifications.css
  css/src/yoast-components.css
  packages/js/src/analysis/refreshAnalysis.js
  packages/js/src/components/contentAnalysis/KeywordInput.js
  packages/js/src/components/contentAnalysis/KeywordInputComponent.js
  packages/js/src/helpers/fields/AnalysisFields.js
  packages/js/src/redux/actions/contentAnalysis.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/reducers/contentAnalysis/inclusiveLanguageResultsReducer.js
  packages/js/src/redux/reducers/contentAnalysis/index.js
  packages/js/src/redux/reducers/contentAnalysis/keywordResultsReducer.js
  packages/js/src/redux/reducers/contentAnalysis/readabilityResultsReducer.js
  packages/js/src/redux/reducers/index.js
  packages/js/tests/blockEditorData.test.js
  packages/js/tests/helpers/fields/AnalysisFields.test.js
  packages/js/tests/redux/actions/contentAnalysis.test.js
  packages/js/tests/redux/reducers/contentAnalysis/contentAnalysisReducer.test.js
  packages/js/tests/redux/reducers/contentAnalysis/inclusiveLanguageResultsReducer.test.js
  packages/js/tests/redux/reducers/contentAnalysis/keywordResultsReducer.test.js
  packages/js/tests/redux/reducers/contentAnalysis/readabilityResultsReducer.test.js
Labels: changelog: non-user-facing

#20316 GH Actions: run workflows more selectively
  .github/workflows/cs.yml
  .github/workflows/jslint.yml
  .github/workflows/jstest.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: non-user-facing

#20358 fix mistake where it was impossible to undo highlighting.
  packages/js/src/decorator/helpers/markTinyMCE.js
  packages/js/tests/decorator/helpers/markTinyMCE.test.js
Labels: innovation, changelog: non-user-facing, Shopify

#20361 Don't add terms with custom canonical URLs in the sitemap
  inc/sitemaps/class-taxonomy-sitemap-provider.php
Labels: changelog: bugfix

#20368 Don't add sitemap rewrite rules when Yoast SEO is being deactivated
  inc/sitemaps/class-sitemaps-router.php
  src/conditionals/deactivating-yoast-seo-conditional.php
  tests/unit/conditionals/deactivating-yoast-seo-conditional-test.php
Labels: changelog: bugfix

#19883 Deprecate the integration to display a notification when Premium is not up-to-date
  config/dependency-injection/deprecated-classes.php
  inc/options/class-wpseo-option-wpseo.php
  src/deprecated/src/integrations/admin/old-premium-integration.php
  src/integrations/admin/old-premium-integration.php
  tests/unit/integrations/admin/old-premium-integration-test.php
Labels: changelog: other

#20378 Fix wincher blank box when no keywords are tracked
  packages/js/src/components/WincherPerformanceReport.js
Labels: community-patch, changelog: non-user-facing
