Repository Yoast/wordpress-seo, pull requests merged in 2023-09, with the labels that each got.

#20614 Tests/first time configuration notice helper
  tests/integration/helpers/test-first-time-configuration-notice-helper.php
Labels: changelog: non-user-facing

#20598 182 add position information for implicit paragraphs without parent elements
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesFromTreeSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsForHTMLParserSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getAnchorsWithKeyphraseSpec.js
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/adaptSpec.js
  packages/yoastseo/spec/parse/build/private/combineIntoImplicitParagraphsSpec.js
  packages/yoastseo/spec/parse/build/private/filterBeforeTokenizingSpec.js
  packages/yoastseo/spec/parse/build/private/filterTreeSpec.js
  packages/yoastseo/spec/parse/build/private/getTextElementPositionsSpec.js
  packages/yoastseo/spec/parse/build/private/tokenizeSpec.js
  packages/yoastseo/spec/parse/structure/NodeSpec.js
  packages/yoastseo/spec/parse/structure/TextSpec.js
  packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/src/parse/build/build.js
  packages/yoastseo/src/parse/build/private/adapt.js
  packages/yoastseo/src/parse/build/private/combineIntoImplicitParagraphs.js
  packages/yoastseo/src/parse/build/private/getTextElementPositions.js
  packages/yoastseo/src/parse/structure/Text.js
Labels: innovation, changelog: non-user-facing

#20617 Introduce the promotions helper
  src/promotions/application/promotion-manager-interface.php
  src/promotions/application/promotion-manager.php
  src/promotions/domain/abstract-promotion.php
  src/promotions/domain/black-friday-promotion.php
  src/promotions/domain/promotion-interface.php
  src/promotions/domain/time-interval.php
  tests/unit/promotions/application/fake-expired-promotion.php
  tests/unit/promotions/application/fake-promotion.php
  tests/unit/promotions/application/promotion-manager-test.php
  tests/unit/promotions/domain/time-interval-test.php
Labels: changelog: non-user-facing

#20618 Merges the feature branch into trunk
  admin/watchers/class-slug-change-watcher.php
  inc/options/class-wpseo-option-titles.php
  packages/yoastseo/languages/yoast-seo.pot
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
  packages/yoastseo/src/parsedPaper/assess/TreeAssessor.js
  packages/yoastseo/src/scoring/assessments/SCORING SEO.md
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextAlignmentAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/FunctionWordsInKeyphraseAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ImageCountAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/InternalLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInImageTextAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInSEOTitleAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/OutboundLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SingleH1Assessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextCompetingLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
  packages/yoastseo/src/scoring/assessor.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#20621 New search and social appearance
  apps/components/SocialPreviewEditorWrapper.js
  apps/components/SocialPreviewFormWrapper.js
  packages/js/src/components/ModalCollapsible.js
  packages/js/src/components/SidebarItem.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/modals/editorModals/FacebookPreviewModal.js
  packages/js/src/components/modals/editorModals/GooglePreviewModal.js
  packages/js/src/components/modals/editorModals/SearchAppearanceModal.js
  packages/js/src/components/modals/editorModals/SocialAppearanceModal.js
  packages/js/src/components/modals/editorModals/TwitterPreviewModal.js
  packages/js/src/components/social/FacebookWrapper.js
  packages/js/src/components/social/SocialMetadata.js
  packages/js/src/components/social/SocialUpsell.js
  packages/js/src/components/social/TwitterWrapper.js
  packages/js/src/containers/FacebookEditor.js
  packages/js/src/containers/SocialMetadata.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/components/modals/editorModals/FacebookPreviewModal.js
  packages/js/src/elementor/components/modals/editorModals/SearchAppearanceModal.js
  packages/js/src/elementor/components/modals/editorModals/SocialAppearanceModal.js
  packages/js/src/elementor/components/modals/editorModals/TwitterPreviewModal.js
  packages/js/src/elementor/containers/FacebookEditor.js
  packages/js/src/helpers/styledDescription.js
  packages/js/src/redux/reducers/preferences.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
  packages/yoastseo/src/snippetPreview/snippetPreview.js
Labels: changelog: non-user-facing

#20620 Add black friday checklist promotion in product editor
  admin/metabox/class-metabox.php
  css/src/admin-global.css
  packages/js/src/components/TimeConstrainedNotification.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/helpers/isWooCommerceActive.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/redux/actions/currentPromotions.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/reducers/currentPromotions.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/selectors/currentPromotions.js
  packages/js/src/redux/selectors/editorContext.js
  packages/js/src/redux/selectors/index.js
  src/integrations/alerts/time-constrained-notification.php
  src/promotions/application/promotion-manager.php
  src/promotions/domain/black-friday-checklist-promotion.php
  tests/unit/promotions/application/promotion-manager-test.php
Labels: changelog: non-user-facing

#20619 Add upsell when promotion is on.
  admin/class-premium-upsell-admin-block.php
  css/src/yst_plugin_tools.css
Labels: UI change, changelog: non-user-facing

#20616 123 improve upsell for social previews
  admin/class-expose-shortlinks.php
  packages/js/src/components/social/SocialUpsell.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
Labels: UI change, changelog: non-user-facing

#20615 4070 promo msg for black friday woocommerce checklist
  admin/class-config.php
  admin/metabox/class-metabox.php
  css/src/admin-global.css
  packages/js/src/components/BlackFridayProductEditorChecklistPromo.js
  packages/js/src/components/BlackFridayPromoNotification.js
  packages/js/src/components/TimeConstrainedNotification.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/initializers/settings-header.js
  src/integrations/alerts/black-friday-product-editor-checklist-notification.php
  src/integrations/alerts/black-friday-promo-notification.php
  src/integrations/alerts/time-constrained-notification.php
  src/integrations/third-party/elementor.php
  src/promotions/domain/black-friday-checklist-promotion.php
  tests/unit/admin/metabox/metabox-test.php
Labels: changelog: non-user-facing

#20628 Add Black Friday sales banner to sidebar ad
  css/src/yst_plugin_tools.css
  packages/js/images/g2_logo_white_optm.svg
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: other

#20631 Fix prev query loop
  src/integrations/front-end-integration.php
  tests/integration/doubles/front-end-integration-double.php
  tests/integration/frontend/test-front-end-integration.php
  tests/unit/integrations/front-end-integration-test.php
Labels: changelog: non-user-facing

#20623 Add upsell when promotion is on.
  inc/class-addon-manager.php
Labels: changelog: non-user-facing

#20622 Add upsell when promotion is on.
  admin/views/licenses.php
  css/src/yoast-extensions.css
Labels: changelog: non-user-facing

#20635 Bf plugin ad 4 sidebar metabox
  admin/class-config.php
  admin/class-premium-upsell-admin-block.php
  admin/metabox/class-metabox.php
  css/src/admin-global.css
  packages/js/src/components/BlackFridayProductEditorChecklistPromotion.js
  packages/js/src/components/BlackFridayPromoNotification.js
  packages/js/src/components/BlackFridayPromotion.js
  packages/js/src/components/BlackFridaySidebarChecklistPromotion.js
  packages/js/src/components/TimeConstrainedNotification.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/higherorder/withMetaboxWarningsCheck.js
  packages/js/src/containers/PersistentDismissableNotification.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/helpers/checkForMetaboxWarnings.js
  packages/js/src/helpers/shouldShowWebinarPromotionNotification.js
  packages/js/src/initializers/settings-header.js
  packages/js/src/initializers/settings-store.js
  src/integrations/alerts/black-friday-promotion-notification.php
  src/integrations/alerts/black-friday-sidebar-checklist-notification.php
  src/integrations/third-party/elementor.php
  src/promotions/domain/black-friday-checklist-promotion.php
  src/promotions/domain/black-friday-promotion.php
Labels: changelog: non-user-facing

#20639 Bf plugin ad 7 yoast menu
  admin/menu/class-base-menu.php
  css/src/admin-global.css
Labels: changelog: non-user-facing

#20640 add plurals morphology support for English word complexity
  packages/yoastseo/spec/languageProcessing/languages/en/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
Labels: changelog: enhancement, Shopify

#20645 Fix notifications counter style in the admin bar on the frontend
  css/src/adminbar.css
Labels: changelog: bugfix

#20380 Improve performance of link building
  src/builders/indexable-link-builder.php
  src/helpers/image-helper.php
  tests/unit/builders/indexable-link-builder/build-test.php
  tests/unit/helpers/image-helper-test.php
Labels: innovation, changelog: enhancement

#20646 Fix support for drag-and-drop in `FileInput` and `FileImport`
  packages/ui-library/src/components/file-import/docs/aborted.md
  packages/ui-library/src/components/file-import/docs/component.md
  packages/ui-library/src/components/file-import/docs/error.md
  packages/ui-library/src/components/file-import/docs/index.js
  packages/ui-library/src/components/file-import/docs/loading.md
  packages/ui-library/src/components/file-import/docs/selected.md
  packages/ui-library/src/components/file-import/index.js
  packages/ui-library/src/components/file-import/stories.js
  packages/ui-library/src/elements/file-input/docs/component.md
  packages/ui-library/src/elements/file-input/index.js
  packages/ui-library/src/introduction.md
Labels: changelog: bugfix

#20599 add filter to allow building hierarchy
  src/builders/indexable-hierarchy-builder.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
Labels: changelog: non-user-facing

#20647 Update UI library to release version 3.2.1
  packages/js/package.json
  packages/ui-library/changelog.md
  packages/ui-library/package.json
Labels: changelog: non-user-facing

#20624 Fix for resource_hints_plain_cleanup
  src/integrations/front-end/crawl-cleanup-basic.php
Labels: community-patch, changelog: bugfix

#20656 Use useselect hook instead of select for invoking selectors
  packages/js/src/components/BlackFridayProductEditorChecklistPromotion.js
  packages/js/src/components/BlackFridayPromotion.js
  packages/js/src/components/BlackFridaySidebarChecklistPromotion.js
Labels: changelog: non-user-facing

#20658 Updated caniuse-lite database for browserslist
  yarn.lock
Labels: changelog: non-user-facing

#20655 Improve upsells
  admin/class-admin-asset-manager.php
  admin/class-expose-shortlinks.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/src/components/KeywordUpsell.js
  packages/js/src/components/MetaboxButton.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/modals/InternalLinkingSuggestionsUpsell.js
  packages/js/src/components/modals/KeywordSynonyms.js
  packages/js/src/components/modals/KeywordUpsell.js
  packages/js/src/components/modals/MultipleKeywords.js
  packages/js/src/components/modals/PremiumSEOAnalysisModal.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  tailwind.config.js
Labels: UI change, changelog: non-user-facing

#20595 Fix position-based highlighting when a text contains ampersand and other reserved HTML entities
  packages/js/src/decorator/helpers/positionBasedAnnotationHelper.js
  packages/js/src/lib/tinymce.js
  packages/js/tests/decorator/helpers/positionBasedAnnotationHelper.test.js
  packages/yoastseo/spec/helpers/htmlEntitiesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsForHTMLParserSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/tokenizeSpec.js
  packages/yoastseo/spec/specHelpers/parse/buildTree.js
  packages/yoastseo/src/helpers/htmlEntities.js
  packages/yoastseo/src/helpers/index.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWordsForHTMLParser.js
  packages/yoastseo/src/parse/build/build.js
  packages/yoastseo/src/parse/build/private/tokenize.js
Labels: changelog: non-user-facing, Shopify

#20662 Fixes a bug in paragraph detection
  packages/yoastseo/src/languageProcessing/researches/getParagraphs.js
Labels: changelog: bugfix, Shopify

#20666 Change textdomain
  packages/js/src/first-time-configuration/tailwind-components/base/image-select.js
  packages/js/src/first-time-configuration/tailwind-components/tailwind-modal.js
Labels: changelog: bugfix

#20649 HTML Parser: Fix the error shown for Single title assessment when one H1 doesn't have text
  packages/yoastseo/spec/languageProcessing/researches/h1sSpec.js
  packages/yoastseo/src/languageProcessing/researches/h1s.js
Labels: changelog: non-user-facing

#20663 Fix crash for Single title assessment when one of the H1s doesn't have text
  packages/yoastseo/spec/languageProcessing/researches/h1sSpec.js
  packages/yoastseo/src/languageProcessing/researches/h1s.js
Labels: changelog: bugfix, Shopify

#20681 Migrate indexation tests
  packages/js/src/components/Indexation.js
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation.js
  packages/js/tests/indexation.test.js
Labels: changelog: non-user-facing

#20683 Migrate PrePublish tests
  packages/js/tests/components/PrePublish.test.js
Labels: changelog: non-user-facing

#20682 Migrate AnalysisCheckList tests
  packages/js/tests/components/AnalysisCheckList.test.js
Labels: changelog: non-user-facing

#20679 73 change the copy on the sticky sidebar and sticky footer bar to claim your 30 off now
  admin/class-admin-asset-manager.php
  admin/class-premium-upsell-admin-block.php
  css/src/black-friday-banner.css
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/shared-admin/components/premium-upsell-card.js
  packages/js/src/support/app.js
  src/integrations/settings-integration.php
  src/integrations/support-integration.php
  src/presenters/admin/sidebar-presenter.php
  tests/unit/integrations/support-integration-test.php
Labels: UI change, changelog: non-user-facing

#20650 HTML parser: Fix matching of words with apostrophes when different types of single quotes are used
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/matchTextWithWordSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/spec/parse/structure/TokenSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/matchTextWithWord.js
  packages/yoastseo/src/parse/structure/Token.js
Labels: innovation, changelog: enhancement, Shopify

#20667 Fixes highlighting behaviour for posts converted from Classic to Gutenberg
  packages/js/src/analysis/blockEditorData.js
  packages/js/tests/blockEditorData.test.js
Labels: changelog: non-user-facing

#20690 Composer: normalize the file, add script descriptions
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#20691 PHPUnit config: update schema reference
  phpunit-integration.xml.dist
  phpunit.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#20692 Composer/Tests: update test dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#20660 Add a new frequency list for Word complexity in English
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/en/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/frequencyList.json
Labels: changelog: enhancement

#20686 Migrate Semrush tests
  packages/js/jest.config.js
  packages/js/tests/__mocks__/@wordpress/components.js
  packages/js/tests/__mocks__/svgMock.js
  packages/js/tests/components/SEMrushCountrySelector.test.js
  packages/js/tests/components/SEMrushKeyphrasesTable.test.js
  packages/js/tests/components/SEMrushRelatedKeyphrasesModal.test.js
Labels: changelog: non-user-facing

#20699 Make sure that slug is available before trying to return it
  packages/js/src/analysis/PostDataCollector.js
Labels: changelog: bugfix

#20689 Mark translations that are only for screen readers
  admin/class-admin-utils.php
  admin/class-bulk-editor-list-table.php
  admin/class-meta-columns.php
  admin/class-premium-popup.php
  admin/class-premium-upsell-admin-block.php
  admin/class-suggested-plugins.php
  admin/class-yoast-form.php
  admin/formatter/class-metabox-formatter.php
  admin/menu/class-admin-menu.php
  admin/taxonomy/class-taxonomy-columns.php
  admin/views/js-templates-primary-term.php
  admin/views/licenses.php
  admin/views/partial-notifications-template.php
  admin/views/tabs/network/features.php
  admin/views/tabs/network/integrations.php
  admin/watchers/class-slug-change-watcher.php
  composer.json
  inc/class-wpseo-admin-bar-menu.php
  packages/components/src/Alert.js
  packages/components/src/data-model/DataModel.js
  packages/components/src/help-icon/HelpIcon.js
  packages/helpers/src/makeOutboundLink.js
  packages/js/src/academy/app.js
  packages/js/src/components/AdvancedSettings.js
  packages/js/src/components/JetpackBoost.js
  packages/js/src/components/PostPublish.js
  packages/js/src/components/SEMrushRelatedKeyphrasesModal.js
  packages/js/src/components/SchemaTab.js
  packages/js/src/components/WincherPostPublish.js
  packages/js/src/components/WincherSEOPerformance.js
  packages/js/src/components/WordProofTimestampToggle.js
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/components/contentAnalysis/KeywordInput.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/modals/SEMrushKeyphrasesTable.js
  packages/js/src/containers/PersistentDismissableNotification.js
  packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-field-array.js
  packages/js/src/inline-links/inline.js
  packages/js/src/insights/components/estimated-reading-time.js
  packages/js/src/insights/components/flesch-reading-ease.js
  packages/js/src/insights/components/prominent-words.js
  packages/js/src/insights/components/text-formality.js
  packages/js/src/insights/components/text-length.js
  packages/js/src/integrations-page/algolia-integration.js
  packages/js/src/integrations-page/jetpack-boost-integration.js
  packages/js/src/integrations-page/simple-integration.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/integrations-page/woocommerce-integration.js
  packages/js/src/settings/app.js
  packages/js/src/settings/components/formik-page-select-field.js
  packages/js/src/settings/components/notifications.js
  packages/js/src/settings/routes/site-features.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
  packages/js/src/shared-admin/components/outbound-link.js
  packages/js/src/structured-data-blocks/how-to/components/HowTo.js
  packages/js/src/support/components/resource-card.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  src/integrations/admin/link-count-columns-integration.php
  src/integrations/admin/workouts-integration.php
  src/presenters/admin/help-link-presenter.php
Labels: changelog: non-user-facing
