Repository Yoast/wordpress-seo, pull requests merged in 2023-03, with the labels that each got.

#19928 Cleanup old settings: remove old social page
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/class-plugin-conflict.php
  admin/menu/class-menu.php
  admin/pages/social.php
  admin/views/tabs/social/accounts.php
  admin/views/tabs/social/facebook.php
  admin/views/tabs/social/pinterest.php
  admin/views/tabs/social/twitterbox.php
  css/src/search-appearance.css
  css/src/yst_plugin_tools.css
  inc/class-wpseo-utils.php
  packages/js/src/components/WordPressUserSelector.js
  packages/js/src/initializers/social-settings.js
  packages/js/src/settings.js
  packages/js/tests/components/WordPressUserSelector.test.js
  src/integrations/admin/helpscout-beacon.php
Labels: changelog: non-user-facing

#19947 Add meta from post indexable only when indexable exists
  src/integrations/front-end/open-graph-oembed.php
  tests/unit/integrations/front-end/open-graph-oembed-test.php
Labels: changelog: bugfix

#19921 Restructuring yoastseo: improve the js bundle in woocommerce and shopify
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/collectionPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
  packages/yoastseo/src/scoring/storeBlog/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storeBlog/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/storePostsAndPages/seoAssessor.js
Labels: changelog: non-user-facing, Shopify

#19680 Previously used keyphrase warning being received for related keyphrases but the link goes to blank page
  admin/class-meta-columns.php
Labels: changelog: bugfix

#19800 Fixes a bug where clicking the link in _previously used keyword assessment_ led to an empty page of results.
  admin/ajax.php
  admin/formatter/class-post-metabox-formatter.php
  admin/metabox/class-metabox.php
  inc/class-wpseo-meta.php
  packages/js/src/analysis/usedKeywords.js
  packages/js/src/elementor/initializers/used-keywords-assessment.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/used-keywords-assessment.js
  packages/yoastseo/spec/bundledPlugins/previouslyUsedKeywordsSpec.js
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
Labels: UI change, changelog: bugfix

#19927 Remove old features tab
  admin/views/tabs/dashboard/features.php
  src/deprecated/src/integrations/admin/redirect-old-features-tab-integration.php
Labels: changelog: non-user-facing

#19931 17 restructuring yoastseo correctly bundle the title assessment
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/scoring/assessments/seo/TextTitleAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js
Labels: changelog: other

#19956 Make upsell links for keyphrase distribution and word complexity assessments open in a new tab
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
Labels: UI change, changelog: other

#19929 Remove old dashboard tabs
  admin/views/tabs/dashboard/crawl-settings.php
  admin/views/tabs/dashboard/integrations.php
  admin/views/tabs/dashboard/webmaster-tools.php
  src/integrations/admin/crawl-settings-integration.php
Labels: changelog: non-user-facing

#19963 Change every `WPSEO` in deprecation messages to `Yoast SEO`
  admin/class-config.php
  admin/class-helpscout.php
  admin/google_search_console/views/gsc-redirect-nopremium.php
  admin/roles/class-role-manager-vip.php
  inc/class-wpseo-utils.php
  inc/language-utils.php
  inc/sitemaps/class-sitemaps.php
  inc/wpseo-functions-deprecated.php
  src/config/schema-types.php
  src/deprecated/admin/ryte/class-ryte.php
  src/deprecated/admin/views/class-view-utils.php
  src/deprecated/frontend/frontend.php
  src/deprecated/i18n/i18n-v3.php
  src/deprecated/src/conditionals/front-end-inspector-conditional.php
  src/deprecated/src/conditionals/japanese-support-conditional.php
  src/deprecated/src/conditionals/the-events-calendar-conditional.php
  src/deprecated/src/conditionals/third-party/coauthors-plus-activated-conditional.php
  src/deprecated/src/generators/schema/third-party/coauthor.php
  src/deprecated/src/generators/schema/third-party/events-calendar-schema.php
  src/deprecated/src/helpers/input-helper.php
  src/deprecated/src/integrations/admin/social-templates-integration.php
  src/deprecated/src/integrations/third-party/coauthors-plus.php
  src/deprecated/src/integrations/third-party/the-events-calendar.php
  src/deprecated/src/presenters/admin/auto-update-notification-presenter.php
  src/deprecated/src/routes/configuration-workout-route.php
  src/integrations/third-party/wincher.php
  src/integrations/third-party/wordproof-integration-toggle.php
  src/repositories/indexable-repository.php
Labels: technical-debt, changelog: non-user-facing

#19969 Remove configuration wizard package
  .eslintrc
  .github/ISSUE_TEMPLATE/Shortlink.md
  .github/workflows/jstest.yml
  Gruntfile.js
  css/src/notifications-new.css
  css/src/notifications.css
  packages/README.md
  packages/components/src/configuration-wizard/configuration-wizard.css
  packages/configuration-wizard/.babelrc
  packages/configuration-wizard/CHANGELOG.md
  packages/configuration-wizard/README.md
  packages/configuration-wizard/package.json
  packages/configuration-wizard/src/Choice.js
  packages/configuration-wizard/src/ConfigurationWizard.js
  packages/configuration-wizard/src/Header.js
  packages/configuration-wizard/src/Html.js
  packages/configuration-wizard/src/LoadingIndicator.js
  packages/configuration-wizard/src/MessageBox.js
  packages/configuration-wizard/src/ProgressIndicator.js
  packages/configuration-wizard/src/Step.js
  packages/configuration-wizard/src/StepButton.js
  packages/configuration-wizard/src/StepIndicator.js
  packages/configuration-wizard/src/helpers/_colors.scss
  packages/configuration-wizard/src/index.js
  packages/configuration-wizard/src/yoast-theme.js
  packages/configuration-wizard/tests/__mocks__/@wordpress/i18n.js
  packages/configuration-wizard/tests/progressIndicatorTest.js
  packages/configuration-wizard/tests/stepTest.js
  packages/configuration-wizard/tests/wizardTest.js
  packages/configuration-wizard/tools/config/api-config.js
  packages/configuration-wizard/tools/config/interfaces/ConnectGoogleSearchConsole.js
  packages/configuration-wizard/tools/config/interfaces/MailchimpSignup.js
  packages/configuration-wizard/tools/config/interfaces/PostTypeVisibility.js
  packages/configuration-wizard/tools/config/interfaces/PublishingEntity.js
  packages/configuration-wizard/tools/config/production-config.js
  packages/configuration-wizard/tools/config/test-configuration.js
  packages/configuration-wizard/tools/jest/CSSStub.js
  packages/configuration-wizard/tools/jest/setupTests.js
  packages/js/src/components/FinalStep.js
  packages/yoast-components/package.json
  yarn.lock
Labels: changelog: non-user-facing

#19977 Revert #19399 highlighting support in captions in classic editor
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
Labels: changelog: non-user-facing

#19985 Add type check
  packages/js/src/settings/components/formik-tag-field.js
Labels: changelog: non-user-facing

#19943 Move crawl cleanup to free
  admin/class-admin-asset-manager.php
  admin/pages/network.php
  config/webpack/paths.js
  packages/js/src/crawl-settings.js
  packages/js/src/settings/app.js
  packages/js/src/settings/routes/crawl-optimization.js
  src/initializers/crawl-cleanup-permalinks.php
  src/integrations/admin/crawl-settings-integration.php
  src/integrations/front-end/crawl-cleanup-basic.php
  src/integrations/front-end/crawl-cleanup-rss.php
  src/integrations/front-end/crawl-cleanup-searches.php
  src/integrations/front-end/robots-txt-integration.php
  tests/unit/integrations/admin/crawl-settings-integration-test.php
  tests/unit/integrations/front-end/crawl-cleanup-basic-test.php
  tests/unit/integrations/front-end/crawl-cleanup-rss-test.php
  tests/unit/integrations/front-end/crawl-cleanup-searches-test.php
  tests/unit/integrations/front-end/robots-txt-integration-test.php
Labels: changelog: enhancement

#19954 fix php warnings undefined array key in export settings
  admin/class-export.php
Labels: changelog: bugfix

#19989 Merge feature branch into trunk
  admin/ajax.php
  admin/class-meta-columns.php
  admin/formatter/class-post-metabox-formatter.php
  admin/metabox/class-metabox.php
  inc/class-wpseo-meta.php
  packages/analysis-report/src/AnalysisResult.js
  packages/js/src/analysis/usedKeywords.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/elementor/initializers/used-keywords-assessment.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/used-keywords-assessment.js
  packages/yoastseo/spec/bundledPlugins/previouslyUsedKeywordsSpec.js
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
Labels: changelog: non-user-facing

#19912 Make hasResearch, hasConfig and hasHelper usable in tests in Premium
  packages/yoastseo/spec/specHelpers/factory.js
Labels: changelog: non-user-facing

#19990 19892 check for dead code related to old wp versions
  admin/class-admin.php
  admin/formatter/class-term-metabox-formatter.php
  admin/taxonomy/class-taxonomy.php
  inc/sitemaps/class-author-sitemap-provider.php
  src/integrations/blocks/block-categories.php
  tests/integration/admin/test-class-yoast-network-admin.php
  tests/integration/formatter/test-term-metabox-formatter.php
  tests/integration/notifications/test-class-yoast-notification-center.php
  tests/integration/notifications/test-class-yoast-notification.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#19970 Deprecate indexables page
  admin/class-admin-asset-manager.php
  admin/class-yoast-notifications.php
  admin/views/tabs/dashboard/dashboard.php
  config/dependency-injection/deprecated-classes.php
  config/webpack/paths.js
  css/src/notifications-new.css
  packages/js/images/icon-adjustments.svg
  packages/js/images/icon-search.svg
  packages/js/src/indexables-page.js
  packages/js/src/indexables-page/assessment-functions.js
  packages/js/src/indexables-page/components/all-features-disabled.js
  packages/js/src/indexables-page/components/indexable-title-link.js
  packages/js/src/indexables-page/components/indexables-card-options.js
  packages/js/src/indexables-page/components/indexables-card.js
  packages/js/src/indexables-page/components/indexables-table.js
  packages/js/src/indexables-page/components/indexation-view.js
  packages/js/src/indexables-page/components/indexation.js
  packages/js/src/indexables-page/components/indexing-error.js
  packages/js/src/indexables-page/components/not-enough-analysed-content.js
  packages/js/src/indexables-page/components/not-enough-content.js
  packages/js/src/indexables-page/components/refresh-button.js
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/indexables-page/indexables-page.js
  packages/js/src/indexables-page/landing-page.js
  src/deprecated/src/actions/indexables-page-action.php
  src/deprecated/src/conditionals/indexables-page-conditional.php
  src/deprecated/src/helpers/indexables-page-helper.php
  src/deprecated/src/integrations/admin/indexables-page-integration.php
  src/deprecated/src/routes/indexables-page-route.php
  src/presenters/admin/notice-presenter.php
  tests/unit/actions/indexables-page-action-test.php
  tests/unit/integrations/admin/deactivated-premium-integration-test.php
  tests/unit/integrations/admin/old-premium-integration-test.php
  tests/unit/presenters/admin/notice-presenter-test.php
  tests/unit/routes/indexables-page-route-test.php
Labels: changelog: non-user-facing

#19936 Add the box in the Pre-publish panel
  admin/class-admin-asset-manager.php
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  css/src/editor.css
  packages/js/images/jetpack-boost-logo.svg
  packages/js/images/yoast-seo-simple-logo.svg
  packages/js/src/components/JetpackBoost.js
  packages/js/src/initializers/block-editor-integration.js
  src/conditionals/third-party/jetpack-boost-not-premium-conditional.php
  src/helpers/url-helper.php
  src/integrations/alerts/jetpack-boost-pre-publish.php
  tests/unit/helpers/url-helper-test.php
Labels: UI change, changelog: non-user-facing

#19889 Add Jetpack Boost integration
  packages/js/images/jetpack-boost-integration-logo.svg
  packages/js/src/integrations-page/recommended-integrations.js
  packages/js/src/integrations-page/simple-integration.js
  src/integrations/admin/integrations-page.php
Labels: UI change, changelog: other

#20002 Send extra information to the newsletter subscription
  packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
Labels: changelog: non-user-facing

#20013 Improve deprecation of WPSEO_HelpScout and move it to the deprecated folder
  src/deprecated/admin/class-helpscout.php
Labels: changelog: bugfix, fix before release

#20012 Remove the encoded slug
  packages/js/src/analysis/blockEditorData.js
Labels: changelog: bugfix

#19991 Refactor indexables logic for posts with reassigned authors
  src/integrations/cleanup-integration.php
  src/integrations/watchers/indexable-author-watcher.php
  tests/unit/integrations/admin/activation-cleanup-integration-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/integrations/watchers/indexable-author-watcher-test.php
Labels: changelog: bugfix

#19996 Remove unused dependencies on `yoastseo`
  packages/replacement-variable-editor/package.json
  packages/yoast-components/package.json
Labels: changelog: non-user-facing

#20017 Advanced crawl cleanup improvements
  packages/js/src/settings/routes/crawl-optimization.js
  src/initializers/crawl-cleanup-permalinks.php
Labels: UI change, changelog: non-user-facing, fix-before-release

#20006 HTML parser - review of initial implementation + specs
  packages/yoastseo/spec/parse/build/private/adaptSpec.js
  packages/yoastseo/spec/parse/build/private/combineIntoImplicitParagraphsSpec.js
  packages/yoastseo/spec/parse/build/private/isPhrasingContentSpec.js
  packages/yoastseo/spec/parse/structure/HeadingSpec.js
  packages/yoastseo/spec/parse/structure/NodeSpec.js
  packages/yoastseo/spec/parse/structure/ParagraphSpec.js
  packages/yoastseo/spec/parse/structure/SentenceSpec.js
  packages/yoastseo/spec/parse/structure/TextSpec.js
  packages/yoastseo/spec/parse/structure/TokenSpec.js
  packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js
  packages/yoastseo/spec/parse/traverse/innerTextSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/src/parse/traverse/innerText.js
Labels: innovation, changelog: non-user-facing

#20020 Improve jetpack Boost ads
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  packages/js/src/components/JetpackBoost.js
  packages/js/src/integrations-page/jetpack-boost-integration.js
  packages/js/src/integrations-page/recommended-integrations.js
  packages/js/src/integrations-page/simple-integration.js
  src/conditionals/third-party/jetpack-boost-active-conditional.php
  src/conditionals/third-party/jetpack-boost-not-premium-conditional.php
  src/integrations/admin/integrations-page.php
  src/integrations/alerts/jetpack-boost-pre-publish.php
Labels: changelog: non-user-facing

#19979 Highlighting feature: fix highlighting the first sentence of the text and caption
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getParagraphLengthSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TransitionWordsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseDistributionAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
Labels: changelog: bugfix

#20027 Update google desktop preview
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: UI change, changelog: enhancement

#20031 Google preview: custom post type double slug
  packages/js/src/analysis/blockEditorData.js
Labels: changelog: non-user-facing

#20036 Changes to jetpack boost integration card
  packages/js/src/integrations-page/jetpack-boost-integration.js
  src/integrations/admin/integrations-page.php
Labels: changelog: non-user-facing

#20033 Updates notification copy.
  packages/js/src/components/WebinarPromoNotification.js
Labels: UI change, changelog: other

#20039 Fixes a bug where the previously used keyphrase analysis did not work in Elementor.
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#19816 Fix exact keyword matching for keyphrases containing a period in the keyphrase in title assessment
  packages/helpers/src/strings/stripSpaces.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripSpacesSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeyphraseInSEOTitleSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInSEOTitleAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripSpaces.js
  packages/yoastseo/src/languageProcessing/researches/findKeyphraseInSEOTitle.js
Labels: changelog: enhancement, Shopify

#20037 Google preview: fix breadcrumb duplicate slug when it includes encoded parts
  packages/js/src/analysis/blockEditorData.js
  packages/js/tests/blockEditorData.test.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: bugfix

#20045 Sets the WordPress tested up to version to 6.2
  readme.txt
  tests/unit/bootstrap.php
  wp-seo-main.php
Labels: changelog: other

#20025 Restructuring yoastseo: unbundle the ecommerce assessments from the free assessments module
  packages/yoastseo/src/scoring/assessments/index.js
  packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
  packages/yoastseo/src/scoring/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/productPages/seoAssessor.js
Labels: changelog: other

#20042 Jetpack boost ad tweaking
  admin/metabox/class-metabox.php
  admin/tracking/class-tracking-settings-data.php
  inc/class-upgrade.php
  inc/options/class-wpseo-option-wpseo.php
  packages/js/src/components/JetpackBoost.js
Labels: changelog: non-user-facing

#20032 19988 crawl cleanup permalink unit tests
  src/helpers/crawl-cleanup-helper.php
  src/helpers/redirect-helper.php
  src/helpers/url-helper.php
  src/initializers/crawl-cleanup-permalinks.php
  tests/unit/helpers/crawl-cleanup-helper-test.php
  tests/unit/initializers/crawl-cleanup-permalinks-test.php
Labels: changelog: non-user-facing

#19948 Drop compatibility with PHP 5.6, 7.0 and 7.1
  .github/workflows/integrationtest.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  composer.json
  composer.lock
  inc/class-upgrade.php
  readme.txt
  src/README.md
  src/deprecated/src/integrations/admin/unsupported-php-version.php
  src/integrations/admin/unsupported-php-version.php
  src/loader.php
  tests/unit/bootstrap.php
  tests/unit/inc/addon-manager-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#20050 Add the 'New' badge to the integration
  packages/js/src/integrations-page/jetpack-boost-integration.js
Labels: UI change, changelog: non-user-facing

#20026 HTML parser - Add position information to the tree
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/filterTreeSpec.js
  packages/yoastseo/spec/parse/structure/NodeSpec.js
  packages/yoastseo/spec/parse/structure/SourceCodeLocationSpec.js
  packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js
  packages/yoastseo/spec/values/MarkSpec.js
  packages/yoastseo/src/parse/build/build.js
  packages/yoastseo/src/parse/build/private/adapt.js
  packages/yoastseo/src/parse/build/private/combineIntoImplicitParagraphs.js
  packages/yoastseo/src/parse/build/private/filterTree.js
  packages/yoastseo/src/parse/structure/Heading.js
  packages/yoastseo/src/parse/structure/Node.js
  packages/yoastseo/src/parse/structure/Paragraph.js
  packages/yoastseo/src/parse/structure/SourceCodeLocation.js
  packages/yoastseo/src/values/Mark.js
Labels: innovation, changelog: non-user-facing

#20048 Merge feature branch into trunk
  packages/helpers/src/strings/stripSpaces.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/removePunctuationSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/stripSpacesSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeyphraseInSEOTitleSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getParagraphLengthSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TransitionWordsAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseDistributionAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInSEOTitleAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/stripSpaces.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/researches/findKeyphraseInSEOTitle.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
Labels: changelog: non-user-facing

#20049 19988 crawl settings integration unit tests
  tests/unit/integrations/admin/crawl-settings-integration-test.php
Labels: changelog: non-user-facing

#20055 Improve webinar registration button in ftc
  admin/class-config.php
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/step-header.js
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
  packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
  packages/js/src/first-time-configuration/tailwind-components/tailwind-modal.js
Labels: UI change, changelog: other

#20014 Improves copy of notifications.
  css/src/admin-global.css
  inc/class-addon-manager.php
Labels: UI change, changelog: enhancement

#20053 update bulk editor js.
  packages/js/src/bulk-editor.js
Labels: changelog: non-user-facing

#20054 Remove old unused function.
  packages/js/src/initializers/admin.js
Labels: changelog: non-user-facing

#20061 Feature/indexables sitemap prerequisites part 1
  inc/class-upgrade.php
  src/conditionals/traits/admin-conditional-trait.php
  src/integrations/admin/activation-cleanup-integration.php
  src/integrations/cleanup-integration.php
  src/integrations/watchers/indexable-author-watcher.php
  tests/unit/integrations/admin/activation-cleanup-integration-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/integrations/watchers/indexable-author-watcher-test.php
Labels: changelog: non-user-facing

#20088 Fix vertical dots in preview for long breadcrumbs
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: non-user-facing, Shopify

#19881 Add Alignment assessment to the Readability analysis
  packages/js/src/analysis/collectAnalysisData.js
  packages/js/src/analysis/getWritingDirection.js
  packages/js/tests/analysis/getWritingDirection.test.js
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/researches/getLongCenterAlignedTextsSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TextAlignmentAssessmentSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/index.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/researches/getLongCenterAlignedTexts.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/readability/TextAlignmentAssessment.js
  packages/yoastseo/src/values/Paper.js
Labels: changelog: enhancement

#20090 Fix fatal on upgrade with Local SEO
  admin/tracking/class-tracking-addon-data.php
Labels: changelog: bugfix

#20095 Update cleanup routine query to take object_type into account.
  src/integrations/cleanup-integration.php
  tests/unit/integrations/cleanup-integration-test.php
Labels: changelog: non-user-facing

#20075 HTML parser - Don't tokenize elements that should always be filtered out
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/filterTreeSpec.js
  packages/yoastseo/src/parse/build/build.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: innovation, changelog: non-user-facing

#20087 Add sentence tokenization
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/language/LanguageProcessorSpec.js
  packages/yoastseo/spec/parse/structure/NodeSpec.js
  packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js
  packages/yoastseo/src/parse/language/LanguageProcessor.js
Labels: innovation, changelog: non-user-facing
