Repository Yoast/wordpress-seo, pull requests merged in 2023-10, with the labels that each got.

#20685 20675 replacement variable editor replacement variable editortestsreplacementvariableeditortestjs
  .eslintrc
  packages/replacement-variable-editor/.eslintrc.js
  packages/replacement-variable-editor/package.json
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/replacement-variable-editor/tests/ReplacementVariableEditorTest.js
  packages/replacement-variable-editor/tests/__snapshots__/ReplacementVariableEditorTest.js.snap
  packages/replacement-variable-editor/tests/test-utils.js
Labels: changelog: non-user-facing

#20684 HTML Parser: Improves handling of line breaks
  packages/yoastseo/spec/parse/build/private/adaptSpec.js
  packages/yoastseo/spec/parse/build/private/combineIntoImplicitParagraphsSpec.js
  packages/yoastseo/spec/parse/structure/ParagraphSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/src/parse/build/private/adapt.js
  packages/yoastseo/src/parse/build/private/combineIntoImplicitParagraphs.js
  packages/yoastseo/src/parse/build/private/tokenize.js
  packages/yoastseo/src/parse/structure/Paragraph.js
Labels: changelog: non-user-facing

#20688 Add mysql 8 custom query to make sure it is BC.
  inc/sitemaps/class-post-type-sitemap-provider.php
  tests/integration/sitemaps/test-class-wpseo-post-type-sitemap-provider.php
Labels: changelog: bugfix

#20710 Upsell updates
  admin/class-admin-asset-manager.php
  admin/class-config.php
  admin/class-premium-upsell-admin-block.php
  admin/menu/class-base-menu.php
  admin/metabox/class-metabox.php
  admin/views/licenses.php
  css/src/admin-global.css
  css/src/adminbar.css
  css/src/black-friday-banner.css
  css/src/yoast-extensions.css
  css/src/yst_plugin_tools.css
  inc/class-addon-manager.php
  inc/class-wpseo-admin-bar-menu.php
  packages/js/images/g2_logo_white_optm.svg
  packages/js/src/components/BlackFridayProductEditorChecklistPromotion.js
  packages/js/src/components/BlackFridayPromoNotification.js
  packages/js/src/components/BlackFridayPromotion.js
  packages/js/src/components/BlackFridaySidebarChecklistPromotion.js
  packages/js/src/components/TimeConstrainedNotification.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/higherorder/withMetaboxWarningsCheck.js
  packages/js/src/containers/PersistentDismissableNotification.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/helpers/checkForMetaboxWarnings.js
  packages/js/src/helpers/shouldShowWebinarPromotionNotification.js
  packages/js/src/initializers/settings-header.js
  packages/js/src/initializers/settings-store.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/shared-admin/components/premium-upsell-card.js
  packages/js/src/support/app.js
  src/integrations/alerts/black-friday-promotion-notification.php
  src/integrations/alerts/black-friday-sidebar-checklist-notification.php
  src/integrations/settings-integration.php
  src/integrations/support-integration.php
  src/integrations/third-party/elementor.php
  src/presenters/admin/sidebar-presenter.php
  src/promotions/domain/black-friday-checklist-promotion.php
  src/promotions/domain/black-friday-promotion.php
  tests/unit/integrations/support-integration-test.php
Labels: changelog: non-user-facing

#20707 Fixes the recognition of highlighting keyphrases in image captions
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsForHTMLParserSpec.js
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/getTextElementPositionsSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/filterShortcodesFromTree.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWordsForHTMLParser.js
  packages/yoastseo/src/parse/build/private/combineIntoImplicitParagraphs.js
  packages/yoastseo/src/parse/build/private/getTextElementPositions.js
Labels: changelog: non-user-facing

#20694 Improve primary term helper performance
  inc/class-wpseo-primary-term.php
Labels: community-patch, changelog: enhancement

#20708 Fix console error and eslint warnings for Primary Taxonomy picker
  packages/js/package.json
  packages/js/src/components/PrimaryTaxonomyFilter.js
  packages/js/src/components/PrimaryTaxonomyPicker.js
  packages/js/src/components/TaxonomyPicker.js
Labels: changelog: non-user-facing

#20693 131 remove automatic rel on rss links
  src/integrations/front-end/rss-footer-embed.php
Labels: changelog: enhancement

#20715 Address integrations page warnings
  packages/js/src/integrations-page/acf-integration.js
  packages/js/src/integrations-page/algolia-integration.js
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/mastodon-integration.js
  packages/js/src/integrations-page/plugin-integration.js
  packages/js/src/integrations-page/schema-api-integrations.js
  packages/js/src/integrations-page/simple-integration.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/integrations-page/woocommerce-integration.js
Labels: changelog: bugfix

#20716 Fix condition to avoid showing promotion badge when Premium is installed
  admin/menu/class-base-menu.php
  css/src/adminbar.css
Labels: changelog: non-user-facing

#20717 Don't return the shortcodes if it's not available in the window
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/src/analysis/collectAnalysisData.js
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#20727 Add Yoast icon to Premium plugin card
  admin/views/licenses.php
  css/src/yoast-extensions.css
Labels: changelog: non-user-facing

#20720 Avoid showing the internal linking suggestions upsell in term and cat…
  packages/js/src/components/fills/MetaboxFill.js
Labels: changelog: non-user-facing

#20725 Add black Friday banner to upsell block in settings
  packages/js/src/settings/app.js
Labels: changelog: non-user-facing

#20724 Fix small BF issues
  packages/js/src/components/BlackFridayPromotion.js
Labels: changelog: non-user-facing

#20728 1080 minor errors with stretched out sidebar ad on ipad screen resolution
  css/src/yst_plugin_tools.css
Labels: UI change, changelog: non-user-facing

#20732 Remove BF badge when user has valid subscription in premium page
  admin/views/licenses.php
Labels: changelog: non-user-facing

#20718 80 add price and banner to upsell modals in plugin
  css/src/icons.css
  css/src/modal.css
  packages/components/src/base/icons.css
  packages/js/src/components/UpsellBox.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/modals/Container.js
  packages/js/src/components/modals/InternalLinkingSuggestionsUpsell.js
  packages/js/src/components/modals/KeywordSynonyms.js
  packages/js/src/components/modals/KeywordUpsell.js
  packages/js/src/components/modals/MultipleKeywords.js
  packages/js/src/components/modals/PremiumSEOAnalysisModal.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
Labels: changelog: non-user-facing

#20736 1090 trivial black friday ad looks weird on first time configuration
  admin/class-premium-upsell-admin-block.php
  css/src/yst_plugin_tools.css
Labels: changelog: non-user-facing

#20734 Fixes incorrect highlighting for H1s with mark-up in the block editor
  packages/js/src/decorator/gutenberg.js
  packages/yoastseo/spec/scoring/assessments/seo/SingleH1AssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/SingleH1Assessment.js
Labels: changelog: non-user-facing

#20743 Fix major errors in case post was created in elementor and switched to block editor
  packages/js/src/analysis/collectAnalysisData.js
  packages/yoastseo/src/pluggable.js
Labels: changelog: non-user-facing

#20747 Revert 20599 100 investigate wp set object terms doesnt add term into a breadcrumbs
  src/builders/indexable-hierarchy-builder.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  tests/unit/integrations/watchers/indexable-ancestor-watcher-test.php
Labels: changelog: reverted

#20740 20729 wp 64 pattern categories are displayed in settings and sitemap
  inc/sitemaps/class-taxonomy-sitemap-provider.php
  src/integrations/admin/indexables-exclude-taxonomy-integration.php
  tests/integration/sitemaps/test-class-wpseo-taxonomy-sitemap-provider.php
Labels: changelog: other

#20744 Support script strategy
  src/integrations/third-party/wordproof.php
Labels: community-patch

#20709 Refactor snippeteditor tests
  .eslintrc
  packages/search-metadata-previews/.eslintrc.js
  packages/search-metadata-previews/package.json
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
  packages/search-metadata-previews/tests/HelpTextWrapperTest.js
  packages/search-metadata-previews/tests/SnippetEditorTest.js
  packages/search-metadata-previews/tests/SnippetPreviewTest.js
  packages/search-metadata-previews/tests/__snapshots__/HelpTextWrapperTest.js.snap
  packages/search-metadata-previews/tests/__snapshots__/SnippetEditorTest.js.snap
  packages/search-metadata-previews/tests/test-utils.js
Labels: changelog: non-user-facing

#20711 20421 breadcrumbs field is supplied wrong type
  packages/js/src/settings/routes/breadcrumbs.js
Labels: changelog: non-user-facing

#20751 Filters shortcode before getting the sentences for Japanese
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/src/languageProcessing/researches/keywordCount.js
Labels: changelog: non-user-facing

#20750 Docs: Correct some typos in `class-wpseo-option.php`.
  inc/options/class-wpseo-option.php
Labels: community-patch, changelog: other

#20756 Fix error when adding image caption and highlighting not working in Yoast blocks
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesFromTreeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentencesFromTree.js
  packages/yoastseo/src/parse/structure/Node.js
  packages/yoastseo/src/parse/traverse/findAllInTree.js
Labels: changelog: non-user-facing

#20135 Update block.js
  packages/js/src/structured-data-blocks/faq/block.js
Labels: community-patch, changelog: other

#20760 Inclusive language: Adds Roma as a suggested alternative to 'gypsy'
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
Labels: changelog: enhancement, Shopify

#20761 Inclusive language: Improves the feedback for 'normal' and 'abnormal'
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
Labels: changelog: enhancement, Shopify

#20763 Merges the feature/word-complexity-improvement branch into trunk
  apps/content-analysis/src/analysis.worker.js
  apps/content-analysis/src/utils/registerPremiumAssessments.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/languageProcessing/languages/de/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js
  packages/yoastseo/spec/scoring/assessments/readability/WordComplexityAssessmentSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/de/config/wordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/en/config/wordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/es/config/wordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/fr/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/fr/config/wordComplexity.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
Labels: changelog: non-user-facing

#20746 Add options/upsells to block unwanted bots
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-wpseo.php
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/crawl-optimization.js
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#20678 Add hiive html attributes to ftc
  packages/js/src/first-time-configuration/constants.js
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/base/image-select.js
  packages/js/src/first-time-configuration/tailwind-components/configuration-stepper-buttons.js
  packages/js/src/first-time-configuration/tailwind-components/steps/finish/finish-step.js
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexation.js
  packages/js/src/first-time-configuration/tailwind-components/steps/personal-preferences/newsletter-signup.js
  packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-field-array.js
  packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-profiles-step.js
  packages/js/src/installation-success.js
  src/actions/configuration/first-time-configuration-action.php
  src/helpers/social-profiles-helper.php
  tests/unit/actions/configuration/first-time-configuration-action-test.php
Labels: changelog: non-user-facing

#20757 Set the `wp_attachment_pages_enabled` option (WP 6.4) when switching "Enable media pages"
  src/integrations/watchers/indexable-attachment-watcher.php
  tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
Labels: changelog: enhancement

#20766 Inclusive language: Align traffic light color and feedback for all phrases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessments.js
Labels: changelog: enhancement

#20767 Inclusive language: Change the feedback strings for overgeneralizing cases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
Labels: changelog: enhancement, Shopify

#20765 Migrate KeywordInput tests
  packages/js/tests/components/contentAnalysis/KeywordInput.test.js
Labels: changelog: non-user-facing

#20494 Use sanitize_url to sanitize canonical field in the taxonomy metabox
  admin/taxonomy/class-taxonomy.php
Labels: community-patch, changelog: bugfix

#20770 Adds defensive coding to make sure warnings don't happen.
  src/helpers/current-page-helper.php
  src/presentations/indexable-term-archive-presentation.php
Labels: changelog: non-user-facing

#20771 Migrate insights feature tests
  packages/js/src/components/modals/editorModals/EditorModal.js
  packages/js/tests/__mocks__/@yoast/externals/contexts.js
  packages/js/tests/insights/components/flesch-reading-ease.test.js
  packages/js/tests/insights/components/insights-collapsible.test.js
  packages/js/tests/insights/components/insights-modal.test.js
  packages/js/tests/insights/components/text-formality.test.js
  packages/js/tests/insights/components/text-length.test.js
Labels: changelog: non-user-facing

#20777 Fix inconsistent copy
  packages/js/src/components/UpsellBox.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
Labels: UI change, changelog: non-user-facing

#20779 Fix JQuery deprecation warning
  packages/js/src/initializers/admin.js
Labels: changelog: non-user-facing

#20522 Feature/wincher modal improvements
  admin/class-admin-asset-manager.php
  config/webpack/externals.js
  config/webpack/webpack.config.base.js
  packages/babel-preset/index.js
  packages/babel-preset/package.json
  packages/js/package.json
  packages/js/src/components/WincherKeyphrasesTable.js
  packages/js/src/components/WincherPerformanceReport.js
  packages/js/src/components/WincherRankingHistoryChart.js
  packages/js/src/components/WincherSEOPerformance.js
  packages/js/src/components/WincherSEOPerformanceModal.js
  packages/js/src/components/WincherTableRow.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/modals/WincherUpgradeCallout.js
  packages/js/src/containers/MetaboxFill.js
  packages/js/src/containers/WincherKeyphrasesTable.js
  packages/js/src/containers/WincherSEOPerformance.js
  packages/js/src/helpers/wincherEndpoints.js
  packages/js/src/redux/reducers/WincherRequest.js
  packages/js/src/redux/selectors/WincherRequest.js
  packages/js/src/redux/selectors/WincherSEOPerformance.js
  packages/js/tests/components/WincherKeyphrasesTable.test.js
  packages/js/tests/components/WincherTableRow.test.js
  src/actions/wincher/wincher-account-action.php
  src/actions/wincher/wincher-keyphrases-action.php
  src/routes/wincher-route.php
  tests/unit/actions/wincher/wincher-account-action-test.php
  tests/unit/actions/wincher/wincher-keyphrases-action-test.php
  tests/unit/routes/wincher-route-test.php
  yarn.lock
Labels: community-patch, changelog: enhancement

#20634 Fix get_upgrade_campaign causing undefined array key warnings
  src/actions/wincher/wincher-account-action.php
  tests/unit/actions/wincher/wincher-account-action-test.php
Labels: changelog: bugfix

#20783 Sets the WordPress tested up to version to 6.4
  readme.txt
  tests/unit/bootstrap.php
  wp-seo-main.php
Labels: changelog: other

#20784 Changes the default value for the ai option and introduces a new option.
  inc/options/class-wpseo-option-wpseo.php
Labels: changelog: non-user-facing

#20786 81 create upsell for ai on woocommerce product pages
  admin/metabox/class-metabox.php
  packages/js/src/ai-generator/components/modal-content.js
  packages/js/src/ai-generator/initialize.js
  packages/js/src/post-edit.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/isWooSEO.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
Labels: UI change, changelog: non-user-facing

#20790 Remove version constraint for showing the ai introduction modal
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  tests/unit/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell-test.php
Labels: changelog: non-user-facing

#20787 84 improvements to the introduction modal
  css/src/introductions.css
  packages/js/src/ai-generator/initialize.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
  src/user-profiles-additions/user-interface/user-profiles-additions-ui.php
  tests/unit/user-profiles-additions/user-interface/user-profiles-additions-ui-test.php
Labels: changelog: non-user-facing

#20776 API: expose the KeywordInputComponent
  packages/js/src/editor-modules.js
Labels: changelog: non-user-facing

#20793 Fix redirects upsell link
  admin/views/redirects.php
Labels: changelog: non-user-facing

#20798 fix header border bottom in product page upsell modal
  css/src/modal.css
Labels: changelog: non-user-facing

#20794 Remove makePublic from non-public classes
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/introductions/application/introductions-collector.php
  src/introductions/user-interface/wistia-embed-permission-route.php
  src/promotions/application/promotion-manager-interface.php
  src/promotions/domain/black-friday-checklist-promotion.php
  src/promotions/domain/black-friday-promotion.php
Labels: technical-debt, changelog: non-user-facing

#20802 Remove unused Jenkins config
  config/jenkins/Jenkinsfile_artifact
Labels: changelog: non-user-facing

#20791 Add introductions seen route
  packages/js/src/introductions/components/introduction.js
  packages/js/src/introductions/components/provider.js
  packages/js/src/introductions/store/introductions.js
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/introductions/application/introductions-collector.php
  src/introductions/domain/introduction-interface.php
  src/introductions/domain/introduction-item.php
  src/introductions/domain/invalid-user-id-exception.php
  src/introductions/infrastructure/introductions-seen-repository.php
  src/introductions/readme.md
  src/introductions/user-interface/introductions-integration.php
  src/introductions/user-interface/introductions-seen-route.php
  tests/unit/doubles/introductions/introduction-mock.php
  tests/unit/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell-test.php
  tests/unit/introductions/application/introductions-collector-test.php
  tests/unit/introductions/domain/introduction-item-test.php
  tests/unit/introductions/domain/introductions-bucket-test.php
  tests/unit/introductions/infrastructure/introductions-seen-repository-test.php
  tests/unit/introductions/user-interface/introductions-seen-route-test.php
Labels: innovation, changelog: non-user-facing

#20804 Improve translation strings for advanced settings
  packages/js/src/components/AdvancedSettings.js
Labels: changelog: non-user-facing

#20687 Improve plural form recognition for French word complexity
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/checkIfWordIsComplex.js
Labels: changelog: enhancement, Shopify

#20806 update copy in ai introduction modal for products
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
Labels: changelog: non-user-facing

#20805 19867 replacing componentwillreceiveprops
  packages/replacement-variable-editor/src/ReplacementVariableEditorStandalone.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: non-user-facing

#20795 Remove re-exports of @yoast/replacement-variable-editor
  packages/search-metadata-previews/src/index.js
Labels: changelog: non-user-facing

#20799 20672 wincher tests
  packages/js/tests/components/WincherKeyphrasesTable.test.js
  packages/js/tests/components/WincherTableRow.test.js
Labels: changelog: non-user-facing

#20810 Merges feature/enable-ai-products to trunk
  admin/metabox/class-metabox.php
  packages/js/src/ai-generator/components/modal-content.js
  packages/js/src/ai-generator/initialize.js
  packages/js/src/post-edit.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/isWooSEO.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
Labels: changelog: non-user-facing

#20811 Merges feature/ai-plugin-default-on to trunk
  inc/options/class-wpseo-option-wpseo.php
  packages/js/src/introductions/components/introduction.js
  packages/js/src/introductions/components/provider.js
  packages/js/src/introductions/store/introductions.js
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/introductions/application/introductions-collector.php
  src/introductions/domain/introduction-interface.php
  src/introductions/domain/introduction-item.php
  src/introductions/domain/invalid-user-id-exception.php
  src/introductions/infrastructure/introductions-seen-repository.php
  src/introductions/readme.md
  src/introductions/user-interface/introductions-integration.php
  src/introductions/user-interface/introductions-seen-route.php
  tests/unit/doubles/introductions/introduction-mock.php
  tests/unit/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell-test.php
  tests/unit/introductions/application/introductions-collector-test.php
  tests/unit/introductions/domain/introduction-item-test.php
  tests/unit/introductions/domain/introductions-bucket-test.php
  tests/unit/introductions/infrastructure/introductions-seen-repository-test.php
  tests/unit/introductions/user-interface/introductions-seen-route-test.php
Labels: changelog: non-user-facing
