Repository Yoast/wordpress-seo, pull requests merged in 2023-04, with the labels that each got.

#20068 HTML parser - Add position information for sentences
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/getSentencePositionsSpec.js
  packages/yoastseo/spec/parse/language/LanguageProcessorSpec.js
  packages/yoastseo/spec/parse/structure/NodeSpec.js
  packages/yoastseo/spec/parse/structure/SentenceSpec.js
  packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js
  packages/yoastseo/spec/parse/traverse/innerTextSpec.js
  packages/yoastseo/src/parse/build/private/getSentencePositions.js
  packages/yoastseo/src/parse/build/private/tokenize.js
  packages/yoastseo/src/parse/structure/Sentence.js
Labels: innovation, changelog: non-user-facing

#20111 Performance improvement for author_has_public_posts_wp
  src/helpers/author-archive-helper.php
Labels: changelog: enhancement

#20122 Merge feature branch into trunk
  packages/js/src/analysis/collectAnalysisData.js
  packages/js/src/analysis/getWritingDirection.js
  packages/js/tests/analysis/getWritingDirection.test.js
  packages/yoastseo/spec/fullTextTests/runFullTextTests.js
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/cs/czechPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/it/italianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nl/dutchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ru/russianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sv/swedishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/researches/getLongCenterAlignedTextsSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/TextAlignmentAssessmentSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/index.js
  packages/yoastseo/src/languageProcessing/index.js
  packages/yoastseo/src/languageProcessing/researches/getLongCenterAlignedTexts.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
  packages/yoastseo/src/scoring/assessments/readability/TextAlignmentAssessment.js
  packages/yoastseo/src/values/Paper.js
Labels: changelog: non-user-facing

#20073 Implement position-based highlighting
  packages/js/src/decorator/helpers/markTinyMCE.js
  packages/js/src/decorator/tinyMCE.js
  packages/js/tests/decorator/helpers/markTinyMCE.test.js
  packages/yoastseo/spec/values/MarkSpec.js
  packages/yoastseo/src/values/Mark.js
Labels: innovation, changelog: non-user-facing

#20121 HTML parser: Make it possible to get sentences from nodes that have descendant nodes without a closing tag
  packages/yoastseo/spec/parse/build/private/getSentencePositionsSpec.js
  packages/yoastseo/src/parse/build/private/getSentencePositions.js
Labels: innovation, changelog: non-user-facing

#20072 HTML parser: Adapt competing links assessment
  packages/yoastseo/spec/languageProcessing/helpers/match/findKeywordInUrlSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getAnchorsWithKeyphraseSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getLinkStatisticsSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/TextCompetingLinksAssessmentSpec.js
  packages/yoastseo/src/languageProcessing/AbstractResearcher.js
  packages/yoastseo/src/languageProcessing/helpers/match/findKeywordInUrl.js
  packages/yoastseo/src/languageProcessing/researches/getAnchorsWithKeyphrase.js
  packages/yoastseo/src/languageProcessing/researches/getLinkStatistics.js
  packages/yoastseo/src/scoring/assessments/seo/TextCompetingLinksAssessment.js
Labels: innovation, changelog: non-user-facing

#20131 HTML Parser - Adds position information for tokens
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/getTextElementPositionsSpec.js
  packages/yoastseo/spec/parse/language/LanguageProcessorSpec.js
  packages/yoastseo/spec/parse/structure/NodeSpec.js
  packages/yoastseo/spec/parse/structure/TokenSpec.js
  packages/yoastseo/spec/parse/traverse/findAllInTreeSpec.js
  packages/yoastseo/src/parse/build/private/getSentencePositions.js
  packages/yoastseo/src/parse/build/private/getTextElementPositions.js
  packages/yoastseo/src/parse/build/private/tokenize.js
  packages/yoastseo/src/parse/structure/Token.js
Labels: innovation, changelog: non-user-facing

#20051 Score icon should always show a smiley
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/contentAnalysis/mapResults.js
  packages/js/src/components/portals/ScoreIconPortal.js
  packages/js/tests/components/contentAnalysis/mapResults.test.js
Labels: UI change, changelog: bugfix

#20132 Improve word casing in the Yoast UI library storybook
  packages/ui-library/.storybook/manager.js
  packages/ui-library/contributing.md
  packages/ui-library/readme.md
  packages/ui-library/src/components/autocomplete-field/stories.js
  packages/ui-library/src/components/card/stories.js
  packages/ui-library/src/components/checkbox-group/stories.js
  packages/ui-library/src/components/children-limiter/stories.js
  packages/ui-library/src/components/feature-upsell/stories.js
  packages/ui-library/src/components/file-import/stories.js
  packages/ui-library/src/components/modal/stories.js
  packages/ui-library/src/components/notifications/stories.js
  packages/ui-library/src/components/radio-group/stories.js
  packages/ui-library/src/components/root/stories.js
  packages/ui-library/src/components/select-field/stories.js
  packages/ui-library/src/components/sidebar-navigation/stories.js
  packages/ui-library/src/components/tag-field/stories.js
  packages/ui-library/src/components/text-field/stories.js
  packages/ui-library/src/components/textarea-field/stories.js
  packages/ui-library/src/components/toggle-field/stories.js
  packages/ui-library/src/elements/alert/stories.js
  packages/ui-library/src/elements/autocomplete/stories.js
  packages/ui-library/src/elements/badge/stories.js
  packages/ui-library/src/elements/button/stories.js
  packages/ui-library/src/elements/code/stories.js
  packages/ui-library/src/elements/error-boundary/stories.js
  packages/ui-library/src/elements/file-input/stories.js
  packages/ui-library/src/elements/label/stories.js
  packages/ui-library/src/elements/link/stories.js
  packages/ui-library/src/elements/progress-bar/stories.js
  packages/ui-library/src/elements/radio/stories.js
  packages/ui-library/src/elements/select/stories.js
  packages/ui-library/src/elements/table/stories.js
  packages/ui-library/src/elements/tag-input/stories.js
  packages/ui-library/src/elements/text-input/stories.js
  packages/ui-library/src/elements/title/stories.js
  packages/ui-library/src/hooks/readme.md
  packages/ui-library/src/installation.md
  packages/ui-library/src/introduction.md
Labels: changelog: non-user-facing

#20064 UI library: Add documentation to certain elements
  packages/ui-library/src/elements/alert/docs/component.md
  packages/ui-library/src/elements/alert/docs/index.js
  packages/ui-library/src/elements/alert/docs/variants.md
  packages/ui-library/src/elements/alert/stories.js
  packages/ui-library/src/elements/badge/docs/component.md
  packages/ui-library/src/elements/badge/docs/index.js
  packages/ui-library/src/elements/badge/docs/sizes.md
  packages/ui-library/src/elements/badge/docs/variants.md
  packages/ui-library/src/elements/badge/stories.js
  packages/ui-library/src/elements/button/docs/component.md
  packages/ui-library/src/elements/button/docs/index.js
  packages/ui-library/src/elements/button/docs/sizes.md
  packages/ui-library/src/elements/button/docs/states.md
  packages/ui-library/src/elements/button/docs/variants.md
  packages/ui-library/src/elements/button/stories.js
  packages/ui-library/src/elements/checkbox/docs/component.md
  packages/ui-library/src/elements/checkbox/docs/disabled.md
  packages/ui-library/src/elements/checkbox/docs/index.js
  packages/ui-library/src/elements/checkbox/stories.js
  packages/ui-library/src/elements/radio/docs/component.md
  packages/ui-library/src/elements/radio/docs/dangerous-label.md
  packages/ui-library/src/elements/radio/docs/index.js
  packages/ui-library/src/elements/radio/docs/variants.md
  packages/ui-library/src/elements/radio/stories.js
  packages/ui-library/src/elements/toggle/docs/component.md
  packages/ui-library/src/elements/toggle/docs/index.js
  packages/ui-library/src/elements/toggle/stories.js
Labels: changelog: other

#20148 20105 add nonce verification to ftc notice dismissal
  src/integrations/admin/first-time-configuration-notice-integration.php
  tests/unit/integrations/admin/first-time-configuration-notice-integration-test.php
Labels: changelog: non-user-facing

#20149 Remove zapier card
  admin/views/class-yoast-integration-toggles.php
  packages/js/images/zapier-logo.svg
  packages/js/src/initializers/block-editor-integration.js
  packages/js/src/integrations-page/other-integrations.js
  src/integrations/admin/integrations-page.php
  tests/unit/admin/views/integration-toggles-test.php
Labels: UI change, changelog: other

#20155 Assigns translation strings in Premium- and product-specific assessments to their proper domain
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextAlignmentAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js
Labels: changelog: non-user-facing

#20159 Remove settings introduction modal
  css/src/new-settings.css
  images/settings-intro_thumb0.jpg
  images/settings-intro_thumb1.jpg
  images/settings-intro_thumb2.jpg
  inc/class-upgrade.php
  packages/js/src/settings/app.js
  packages/js/src/settings/components/introduction.js
  packages/js/src/settings/constants/index.js
  packages/js/src/settings/store/index.js
  packages/js/src/settings/store/introduction.js
  src/deprecated/src/actions/settings-introduction-action.php
  src/deprecated/src/routes/settings-introduction-route.php
  src/integrations/settings-integration.php
  tests/unit/actions/settings-introduction-action-test.php
  tests/unit/integrations/settings-integration-test.php
  tests/unit/routes/settings-introduction-route-test.php
Labels: UI change, changelog: other

#20086 19957 Review usage of dangerouslySetInnerHTML
  packages/analysis-report/src/AnalysisResult.js
  packages/components/src/ScoreAssessments.js
  packages/helpers/src/strings/index.js
  packages/helpers/src/strings/stripTagsFromHtmlString.js
  packages/helpers/tests/strings/stripTagsFromHtmlStringTest.js
  packages/js/src/components/IndexingError.js
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/first-time-configuration/tailwind-components/steps/indexation/indexing-error.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: non-user-facing, Shopify

#19887 Featurethon: academy in plugin
  admin/class-admin-asset-manager.php
  admin/class-config.php
  config/webpack/paths.js
  css/src/academy.css
  images/academy/all_around_seo.png
  images/academy/block_editor.png
  images/academy/copywriting.png
  images/academy/crawlability.png
  images/academy/ecommerce.png
  images/academy/hosting_and_server.png
  images/academy/keyword_research.png
  images/academy/local.png
  images/academy/multilingual.png
  images/academy/seo_for_beginners.png
  images/academy/seo_for_wp.png
  images/academy/site_structure.png
  images/academy/structured_data_for_beginners.png
  images/academy/understanding_structured_data.png
  images/academy/wp_for_beginners.png
  packages/js/src/academy/app.js
  packages/js/src/academy/constants/index.js
  packages/js/src/academy/hooks/index.js
  packages/js/src/academy/hooks/use-dispatch-academy.js
  packages/js/src/academy/hooks/use-select-academy.js
  packages/js/src/academy/initialize.js
  packages/js/src/academy/store/index.js
  packages/js/src/academy/store/link-params.js
  packages/js/src/academy/store/preferences.js
  src/integrations/academy-integration.php
  src/integrations/admin/helpscout-beacon.php
  src/integrations/admin/integrations-page.php
  tests/unit/integrations/academy-integration-test.php
Labels: UI change, changelog: enhancement

#20188 Set the minimum supported WooCommerce version to 7.1.
  wp-seo.php
Labels: changelog: other

#20171 Set the minimum supported WordPress version to 6.1
  .github/workflows/integrationtest.yml
  tests/unit/bootstrap.php
  tests/unit/inc/addon-manager-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#20183 Add a link to the taxonomy edit page when there are no public post types associated to it
  packages/js/src/settings/routes/templates/taxonomy.js
  src/integrations/settings-integration.php
Labels: changelog: enhancement

#20204 Adds a function to add translations for other domains to the webworker
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing

#20211 Fix console error related to translations for English sites
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: bugfix

#20203 Indexable attachment watcher unit tests
  src/integrations/watchers/indexable-attachment-watcher.php
  tests/unit/integrations/watchers/indexable-attachment-watcher-test.php
Labels: changelog: non-user-facing

#20209 Merge shortlink helper with wpseo shortlinker
  inc/class-wpseo-shortlinker.php
  src/helpers/short-link-helper.php
  tests/integration/inc/test-class-wpseo-shortlinker.php
  tests/unit/admin/admin-features-test.php
  tests/unit/admin/views/feature-toggles-test.php
  tests/unit/doubles/helpers/short-link-helper-double.php
  tests/unit/doubles/shortlinker-double.php
  tests/unit/helpers/short-link-helper-test.php
  tests/unit/integrations/admin/migration-error-integration-test.php
  tests/unit/presenters/admin/migration-error-presenter-test.php
Labels: changelog: non-user-facing

#20078 Make Sybre happy
  admin/import/plugins/class-import-seo-framework.php
  tests/integration/admin/import/test-class-import-seo-framework.php
Labels: changelog: other

#20224 Add params and data attributes to upsell link in the Academy page
  packages/js/src/academy/app.js
Labels: changelog: non-user-facing
