Repository Yoast/wordpress-seo, pull requests merged in 2023-08, with the labels that each got.

#20526 Add a target="_blank" parameter to the 'See who contributed to' link
  admin/views/tabs/dashboard/dashboard.php
Labels: community-patch, changelog: non-user-facing

#20552 Remove image from a notification displayed only if you have Premium < 17.7
  images/Assistent_Time_bubble_500x570.png
  src/integrations/admin/workouts-integration.php
Labels: changelog: non-user-facing

#20545 239 update the copy of existing ads so that it mentions ai
  admin/class-premium-upsell-admin-block.php
  admin/views/licenses.php
  packages/js/src/components/modals/KeywordSynonyms.js
  packages/js/src/components/modals/MultipleKeywords.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/settings/app.js
  packages/js/src/shared-admin/components/premium-upsell-card.js
  src/presenters/admin/sidebar-presenter.php
Labels: changelog: non-user-facing

#20539 20029 special characters as title separator breaks rss feed
  inc/options/class-wpseo-option-titles.php
Labels: changelog: bugfix

#20561 Change badge from premium to beta
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
Labels: changelog: non-user-facing

#20560 AI introduction video
  admin/metabox/class-metabox.php
  config/webpack/externals.js
  images/ai-generator-preview.png
  packages/js/src/ai-generator/components/modal-content.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/introductions/components/content.js
  packages/js/src/introductions/initialize.js
  packages/js/src/introductions/store/index.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/controls/index.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/settings/components/formik-page-select-field.js
  packages/js/src/settings/components/formik-user-select-field.js
  packages/js/src/settings/constants/index.js
  packages/js/src/settings/store/media.js
  packages/js/src/settings/store/pages.js
  packages/js/src/settings/store/users.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
  packages/js/src/shared-admin/components/index.js
  packages/js/src/shared-admin/components/video-flow.js
  packages/js/src/shared-admin/constants/index.js
  packages/js/src/shared-admin/store/index.js
  packages/js/src/shared-admin/store/wistia-embed-permission.js
  src/integrations/third-party/elementor.php
  src/introductions/infrastructure/wistia-embed-permission-repository.php
  src/introductions/user-interface/introductions-integration.php
  src/introductions/user-interface/wistia-embed-permission-route.php
  tests/unit/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell-test.php
  tests/unit/introductions/infrastructure/wistia-embed-permission-repository-test.php
  tests/unit/introductions/user-interface/introductions-integration-test.php
  tests/unit/introductions/user-interface/wistia-embed-permission-route-test.php
Labels: changelog: non-user-facing

#20566 change video background to white
  packages/js/src/shared-admin/components/video-flow.js
Labels: changelog: non-user-facing

#20571 Removes purple visited color in FTC final step
  css/src/first-time-configuration.css
Labels: changelog: non-user-facing

#20573 Change option and change label.
  inc/options/class-wpseo-option-wpseo.php
  packages/js/src/settings/routes/site-features.js
Labels: changelog: non-user-facing

#20576 Adds option to hide premium badge but show the premium upsell.
  packages/js/src/settings/routes/site-features.js
Labels: changelog: non-user-facing

#20563 Update upsell copy for Social appearance previews #20551
  packages/js/src/components/social/SocialUpsell.js
Labels: UI change, changelog: other

#20572 Improve translation commments in yoastseo package
  packages/yoastseo/languages/yoast-seo.pot
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
  packages/yoastseo/src/parsedPaper/assess/TreeAssessor.js
  packages/yoastseo/src/scoring/assessments/readability/ListAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextAlignmentAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TextPresenceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/FunctionWordsInKeyphraseAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ImageAltTagsAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ImageCountAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/InternalLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInImageTextAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInSEOTitleAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/OutboundLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductIdentifiersAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ProductSKUAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SingleH1Assessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextCompetingLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
  packages/yoastseo/src/scoring/assessor.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: technical-debt, changelog: non-user-facing

#20581 Fix multisite control of the AI generator feature
  inc/options/class-wpseo-option-wpseo.php
Labels: changelog: non-user-facing

#20580 Update documentation for keyphrase in image assessment
  packages/yoastseo/src/scoring/assessments/SCORING SEO.md
Labels: changelog: other

#20583 Merge the feature branch feature/plugin-fixes into trunk
  admin/views/tabs/dashboard/dashboard.php
  src/analytics/application/to-be-cleaned-indexables-collector.php
  src/content-type-visibility/application/content-type-visibility-dismiss-notifications.php
  src/content-type-visibility/application/content-type-visibility-watcher-actions.php
  src/integrations/admin/admin-columns-cache-integration.php
  src/integrations/cleanup-integration.php
  src/integrations/watchers/indexable-post-type-change-watcher.php
  src/integrations/watchers/indexable-taxonomy-change-watcher.php
  src/repositories/indexable-cleanup-repository.php
  tests/unit/analytics/application/to-be-cleaned-indexables-collector-test.php
  tests/unit/content-type-visibility/application/content-type-visibility-dismiss-notifications-test.php
  tests/unit/integrations/admin/admin-columns-cache-integration-test.php
  tests/unit/integrations/cleanup-integration-test.php
  tests/unit/integrations/watchers/indexable-post-type-change-watcher-test.php
  tests/unit/integrations/watchers/indexable-taxonomy-change-watcher-test.php
  tests/unit/repositories/indexable-cleanup-repository-test.php
Labels: changelog: non-user-facing

#20585 Sanitisation for first time configuration window object
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  src/integrations/admin/first-time-configuration-integration.php
Labels: changelog: non-user-facing

#20586 replace not needed prepare for direct query.
  src/repositories/indexable-cleanup-repository.php
Labels: changelog: non-user-facing

#20587 Add JS tests for issue 4036
  packages/js/src/shared-admin/store/wistia-embed-permission.js
  packages/js/tests/__mocks__/@wordpress/api-fetch.js
  packages/js/tests/components/SEMrushCountrySelector.test.js
  packages/js/tests/components/SEMrushRelatedKeyphrasesModal.test.js
  packages/js/tests/shared-admin/store/wistia-embed-permission.test.js
Labels: changelog: non-user-facing

#20584 Deleting tags has prompt showing "posts" instead of "tags"#20575
  admin/watchers/class-slug-change-watcher.php
Labels: UI change, changelog: bugfix

#20565 UI library 3.2.0 release
  package.json
  packages/analysis-report/package.json
  packages/eslint/CHANGELOG.md
  packages/eslint/package.json
  packages/js/package.json
  packages/tailwindcss-preset/changelog.md
  packages/tailwindcss-preset/package.json
  packages/ui-library/changelog.md
  packages/ui-library/package.json
  yarn.lock
Labels: changelog: non-user-facing

#20542 20313 wrong canonicalnextprev header tags with custom query loop block
  src/helpers/pagination-helper.php
  src/integrations/front-end-integration.php
  tests/unit/helpers/pagination-helper-test.php
  tests/unit/integrations/front-end-integration-test.php
Labels: changelog: bugfix

#20610 Set the minimum supported WordPress version to 6.2.
  .github/workflows/test.yml
  tests/unit/bootstrap.php
  tests/unit/inc/addon-manager-test.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other
