Repository Yoast/wordpress-seo, pull requests merged in 2023-12, with the labels that each got.

#20905 Update styling of replacement variable editor content.
  packages/replacement-variable-editor/src/Mention.js
Labels: changelog: enhancement, Shopify

#20907 Re-order menu items to be consistent throughout various editors.
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/elementor/components/fills/ElementorFill.js
Labels: changelog: other

#20899 Fix typos in inclusive language feedback
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: changelog: enhancement

#20910 Reimplement proof-of-concept for highlighting in Elementor#4125
  packages/js/src/helpers/elementorHook.js
  packages/js/src/watchers/elementorWatcher.js
Labels: changelog: non-user-facing

#20933 Merges feature/elementor-highlighting to trunk
  admin/class-expose-shortlinks.php
  packages/analysis-report/src/AnalysisList.js
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/src/ContentAnalysis.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/IconButtonToggle.js
  packages/components/tests/__snapshots__/IconButtonToggleTest.js.snap
  packages/js/src/analysis/getApplyMarks.js
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/Results.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/helpers/elementorHook.js
  packages/js/src/initializers/analysis.js
  packages/js/src/watchers/elementorWatcher.js
  packages/yoastseo/spec/languageProcessing/helpers/html/htmlParserSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeEstimatedReadingTimeSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/excludeTableOfContentsTagSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sanitize/sanitizeStringSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/countCharactersSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/getWordsSpec.js
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/spec/parse/build/private/filterTreeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/htmlParser.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeEstimatedReadingTime.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/excludeTableOfContentsTag.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/sanitizeString.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/countCharacters.js
  packages/yoastseo/src/languageProcessing/languages/ja/helpers/getWords.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
  packages/yoastseo/src/languageProcessing/researches/getSubheadingTextLengths.js
  packages/yoastseo/src/languageProcessing/researches/matchKeywordInSubheadings.js
  packages/yoastseo/src/parse/build/private/alwaysFilterElements.js
  packages/yoastseo/src/parse/build/private/filterTree.js
Labels: changelog: non-user-facing

#20930 Prompt users to review Yoast on Trustpilot
  packages/js/src/components/TimeConstrainedNotification.js
  packages/js/src/components/WebinarPromoNotification.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/trustpilot-review-notification/constants.js
  packages/js/src/components/trustpilot-review-notification/hooks.js
  packages/js/src/components/trustpilot-review-notification/index.js
  packages/js/src/components/trustpilot-review-notification/trustpilot-review-notification.js
  packages/js/src/containers/PersistentDismissableNotification.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/hooks/use-first-eligible-notification.js
  packages/js/src/shared-admin/store/link-params.js
  packages/js/tests/shared-admin/store/link-params.test.js
  src/integrations/alerts/trustpilot-review-notification.php
Labels: changelog: other

#20913 19098 custom filter image url for taxonomy sitemap images
  inc/sitemaps/class-sitemap-image-parser.php
Labels: changelog: non-user-facing

#20943 Decrease the waiting time for refreshing the analysis in Elementor
  packages/js/src/watchers/elementorWatcher.js
Labels: innovation, changelog: non-user-facing

#20934 Improve copy of plugin ads
  admin/class-premium-upsell-admin-block.php
  admin/views/licenses.php
  css/src/yoast-extensions.css
  packages/js/src/ai-generator/components/modal-content.js
  packages/js/src/components/AnalysisUpsell.js
  packages/js/src/components/UpsellBox.js
  packages/js/src/components/modals/InternalLinkingSuggestionsUpsell.js
  packages/js/src/components/modals/KeywordSynonyms.js
  packages/js/src/components/modals/MultipleKeywords.js
  packages/js/src/components/modals/PremiumSEOAnalysisUpsell.js
  packages/js/src/components/modals/SEMrushUpsellAlert.js
  packages/js/src/helpers/get-premium-benefits.js
  packages/js/src/settings/app.js
  packages/js/src/settings/routes/site-features.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
  packages/js/src/shared-admin/components/premium-upsell-card.js
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: non-user-facing

#20942 Add filter for adding image to front page sitemap
  inc/sitemaps/class-post-type-sitemap-provider.php
  inc/sitemaps/class-sitemap-image-parser.php
Labels: changelog: enhancement

#20948 Fix missing words ads
  admin/views/licenses.php
  packages/js/src/settings/routes/site-features.js
Labels: changelog: non-user-facing

#20916 Phantom dependencies
  .eslintrc
  packages/feature-flag/package.json
  packages/helpers/package.json
  packages/js/package.json
  packages/replacement-variable-editor/package.json
  packages/yoastseo/package.json
  yarn.lock
Labels: changelog: non-user-facing

#20921 Invalidate the Yoast SEO PHP files and directories instead of flushin…
  wp-seo-main.php
Labels: changelog: non-user-facing

#20931 Add rules to avoid false positives in medical contexts
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: changelog: non-user-facing, Shopify

#20951 Remove code deprecated up to 19.12
  admin/pages/tools.php
  admin/roles/class-role-manager-vip.php
  admin/views/tabs/dashboard/site-analysis.php
  admin/views/tabs/tool/import-seo.php
  config/dependency-injection/deprecated-classes.php
  inc/class-wpseo-utils.php
  src/config/schema-ids.php
  src/config/schema-types.php
  src/deprecated/i18n/i18n-v3.php
  src/deprecated/src/conditionals/the-events-calendar-conditional.php
  src/deprecated/src/conditionals/third-party/coauthors-plus-activated-conditional.php
  src/deprecated/src/conditionals/third-party/coauthors-plus-flag-conditional.php
  src/deprecated/src/generators/schema/third-party/coauthor.php
  src/deprecated/src/generators/schema/third-party/events-calendar-schema.php
  src/deprecated/src/integrations/schema-blocks.php
  src/deprecated/src/integrations/third-party/coauthors-plus.php
  src/deprecated/src/integrations/third-party/the-events-calendar.php
Labels: changelog: non-user-facing

#20947 Makes sure keyphrase occurrences with different types of apostrophes are highlighted in keyphrase distribution assessment
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/src/languageProcessing/helpers/sanitize/quotes.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
Labels: innovation, changelog: bugfix, Shopify

#20918 Inclusive language: Improve feedback for 'normal/abnormal people' and 'mentally normal/abnormal'
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
Labels: changelog: non-user-facing, Shopify

#20775 Remove flush rewrite rules on option save
  inc/class-yoast-dynamic-rewrites.php
  inc/options/class-wpseo-option.php
  inc/sitemaps/class-sitemaps-router.php
  inc/sitemaps/class-sitemaps.php
  src/integrations/watchers/indexable-category-permalink-watcher.php
  tests/Unit/Inc/Sitemaps/WPSEO_Sitemaps_Router.php
  tests/Unit/Inc/Yoast_Dynamic_Rewrites_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Category_Permalink_Watcher_Test.php
  tests/WP/Inc/Yoast_Dynamic_Rewrites_Test.php
  wp-seo-main.php
Labels: changelog: enhancement

#20957 Composer: update suggested PHP extensions
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: other

#20958 Composer: update CS menu functions
  config/composer/actions.php
  phpcs.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#20959 PHPCS: Rename PHPCS configuration file
  .phpcs.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#20961 CS/QA: modernize function calls to dirname()
  tests/Unit/bootstrap.php
  tests/WP/bootstrap.php
Labels: yoast cs/qa, changelog: non-user-facing

#20963 Modernize: use magic `::class` keyword for name resolution
  admin/class-plugin-conflict.php
  admin/class-yoast-notifications.php
  admin/class-yoast-plugin-conflict.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-replace-vars.php
  inc/class-wpseo-utils.php
  inc/class-yoast-dynamic-rewrites.php
  inc/sitemaps/class-sitemaps-cache.php
  lib/model.php
  src/actions/importing/abstract-aioseo-importing-action.php
  src/services/health-check/health-check.php
  tests/Unit/Routes/Importing_Route_Test.php
  tests/Unit/Routes/Indexables_Head_Route_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20964 CS/QA: no "lonely if"
  admin/class-yoast-notification-center.php
  admin/taxonomy/class-taxonomy-columns.php
  inc/class-wpseo-replace-vars.php
  inc/options/class-wpseo-option-titles.php
  lib/migrations/adapter.php
  lib/migrations/table.php
  lib/orm.php
  src/integrations/front-end/crawl-cleanup-basic.php
Labels: yoast cs/qa, changelog: non-user-facing

#20965 CS/QA: use `printf()`, not `echo sprintf()`
  admin/views/tabs/network/crawl-settings.php
  admin/views/tabs/network/features.php
  admin/views/tabs/network/integrations.php
  src/integrations/admin/crawl-settings-integration.php
Labels: yoast cs/qa, changelog: non-user-facing

#20966 CS/QA: upgrade calls to get_terms()
  admin/import/plugins/class-import-wpseo.php
  inc/sitemaps/class-taxonomy-sitemap-provider.php
Labels: yoast cs/qa, changelog: non-user-facing

#20967 CS/QA: fix use of duplicate array keys
  tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Watcher_Actions_Test.php
  tests/Unit/Integrations/Admin/Admin_Columns_Cache_Integration_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20969 CS/QA: static closures should be static
  src/integrations/third-party/wordproof.php
  tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20970 CS/QA: don't use static calls to assertion methods
  tests/Unit/Actions/Indexing/Abstract_Link_Indexing_Action_Test.php
  tests/Unit/Actions/Indexing/Post_Link_Indexing_Action_Test.php
  tests/Unit/Actions/Indexing/Term_Link_Indexing_Action_Test.php
  tests/Unit/Conditionals/WP_Robots_Conditional_Test.php
  tests/Unit/Generators/Schema_Generator_Test.php
  tests/Unit/Helpers/Date_Helper_Test.php
  tests/Unit/Helpers/Indexing_Helper_Test.php
  tests/Unit/Helpers/String_Helper_Test.php
  tests/Unit/Integrations/Academy_Integration_Test.php
  tests/Unit/Integrations/Admin/Activation_Cleanup_Integration_Test.php
  tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php
  tests/Unit/Integrations/Admin/Crawl_Settings_Integration_Test.php
  tests/Unit/Integrations/Admin/Cron_Integration_Test.php
  tests/Unit/Integrations/Admin/Import_Integration_Test.php
  tests/Unit/Integrations/Admin/Indexing_Notification_Integration_Test.php
  tests/Unit/Integrations/Admin/Indexing_Tool_Integration_Test.php
  tests/Unit/Integrations/Admin/Installation_Success_Integration_Test.php
  tests/Unit/Integrations/Admin/Old_Configuration_Integration_Test.php
  tests/Unit/Integrations/Admin/Redirect_Integration_Test.php
  tests/Unit/Integrations/Admin/Redirects_Page_Integration_Test.php
  tests/Unit/Integrations/Blocks/Structured_Data_Blocks_Test.php
  tests/Unit/Integrations/Cleanup_Integration_Test.php
  tests/Unit/Integrations/Estimated_Reading_Time_Test.php
  tests/Unit/Integrations/Front_End/WP_Robots_Integration_Test.php
  tests/Unit/Integrations/Front_End_Integration_Test.php
  tests/Unit/Integrations/Settings_Integration_Test.php
  tests/Unit/Integrations/Support_Integration_Test.php
  tests/Unit/Integrations/Third_Party/WooCommerce_Permalinks_Test.php
  tests/Unit/User_Profiles_Additions/User_Interface/User_Profiles_Additions_Ui_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20971 CS/QA: use fully qualified global functions and constants in namespaced files
  config/dependency-injection/loader-pass.php
  lib/abstract-main.php
  lib/migrations/adapter.php
  lib/orm.php
  src/builders/indexable-link-builder.php
  src/conditionals/wp-cron-enabled-conditional.php
  src/content-type-visibility/application/content-type-visibility-dismiss-notifications.php
  src/content-type-visibility/user-interface/content-type-visibility-dismiss-new-route.php
  src/helpers/current-page-helper.php
  src/integrations/admin/background-indexing-integration.php
  src/integrations/blocks/structured-data-blocks.php
  src/integrations/front-end-integration.php
  src/integrations/settings-integration.php
  src/integrations/support-integration.php
  src/integrations/third-party/wordproof.php
  src/integrations/watchers/indexable-post-type-change-watcher.php
  src/integrations/watchers/indexable-taxonomy-change-watcher.php
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/presentations/indexable-term-archive-presentation.php
  src/presenters/admin/sidebar-presenter.php
  tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
  tests/Unit/Doubles/Introductions/Introduction_Mock.php
  tests/Unit/Inc/Sitemaps/WPSEO_Sitemaps_Router.php
  tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php
  tests/WP/Builders/Indexable_Author_Builder_Test.php
  tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
  tests/WP/Builders/Indexable_Post_Type_Archive_Builder_Test.php
  tests/WP/Builders/Indexable_Term_Builder_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20972 CS: consistently have concat operator at start of line
  admin/class-bulk-editor-list-table.php
  admin/class-meta-columns.php
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-form.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-columns.php
  admin/taxonomy/class-taxonomy-fields-presenter.php
  config/composer/actions.php
  inc/class-addon-manager.php
  src/integrations/admin/addon-installation/dialog-integration.php
  src/integrations/admin/menu-badge-integration.php
  src/presenters/meta-description-presenter.php
  tests/Unit/Integrations/Admin/Indexing_Tool_Integration_Test.php
  tests/Unit/Integrations/Blocks/Structured_Data_Blocks_Test.php
  tests/Unit/Presenters/Admin/Indexing_Error_Presenter_Test.php
  tests/Unit/Presenters/Admin/Indexing_Failed_Notification_Presenter_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20974 QA: import use statements
  admin/class-config.php
  admin/metabox/class-metabox.php
  config/dependency-injection/deprecated-classes.php
  config/dependency-injection/loader-pass.php
  inc/class-upgrade.php
  lib/abstract-main.php
  lib/model.php
  lib/orm.php
  src/actions/wincher/wincher-account-action.php
  src/builders/indexable-home-page-builder.php
  src/conditionals/admin/yoast-admin-conditional.php
  src/config/wincher-pkce-provider.php
  src/content-type-visibility/application/content-type-visibility-watcher-actions.php
  src/content-type-visibility/user-interface/content-type-visibility-dismiss-new-route.php
  src/integrations/settings-integration.php
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/routes/importing-route.php
  src/user-profiles-additions/user-interface/user-profiles-additions-ui.php
  tests/Unit/Admin/Metabox/Metabox_Test.php
  tests/Unit/Admin/Tracking/Tracking_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Conditionals/Admin/Yoast_Admin_Conditional_Test.php
  tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Dismiss_Notifications_Test.php
  tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Watcher_Actions_Test.php
  tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
  tests/Unit/Helpers/Image_Helper_Test.php
  tests/Unit/Inc/Addon_Manager_Test.php
  tests/Unit/Inc/Yoast_Dynamic_Rewrites_Test.php
  tests/Unit/Integrations/Admin/Admin_Columns_Cache_Integration_Test.php
  tests/Unit/Integrations/Blocks/Structured_Data_Blocks_Test.php
  tests/Unit/Integrations/Front_End_Integration_Test.php
  tests/Unit/Integrations/Settings_Integration_Test.php
  tests/Unit/Integrations/Watchers/Woocommerce_Beta_Editor_Watcher_Test.php
  tests/Unit/Introductions/Application/Ai_Generate_Titles_And_Descriptions_Introduction_Upsell_Test.php
  tests/Unit/Introductions/Infrastructure/Introductions_Seen_Repository_Test.php
  tests/Unit/Introductions/Infrastructure/Wistia_Embed_Permission_Repository_Test.php
  tests/Unit/Introductions/User_Interface/Introductions_Integration_Test.php
  tests/Unit/Introductions/User_Interface/Introductions_Seen_Route_Test.php
  tests/Unit/Introductions/User_Interface/Wistia_Embed_Permission_Route_Test.php
  tests/Unit/Presenters/Admin/Woocommerce_Beta_Editor_Presenter_Test.php
  tests/Unit/Promotions/Domain/Time_Interval_Test.php
  tests/Unit/Repositories/Orm_Test.php
  tests/Unit/User_Profiles_Additions/User_Interface/User_Profiles_Additions_Ui_Test.php
  tests/WP/Builders/Indexable_Author_Builder_Test.php
  tests/WP/Builders/Indexable_Term_Builder_Test.php
  tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php
  tests/WP/Frontend/Front_End_Integration_Test.php
  tests/WP/Inc/Yoast_Dynamic_Rewrites_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20975 CS/QA: don't use fully qualified global functions and constants in non-namespaced files
  admin/class-admin-asset-manager.php
  admin/class-admin-init.php
  admin/class-admin.php
  admin/class-config.php
  admin/class-meta-columns.php
  admin/class-premium-upsell-admin-block.php
  admin/class-yoast-form.php
  admin/class-yoast-notification-center.php
  admin/class-yoast-notification.php
  admin/class-yoast-plugin-conflict.php
  admin/formatter/class-metabox-formatter.php
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  admin/import/plugins/class-import-aioseo-v4.php
  admin/metabox/class-metabox-analysis-inclusive-language.php
  admin/metabox/class-metabox.php
  admin/statistics/class-statistics-service.php
  admin/taxonomy/class-taxonomy.php
  admin/tracking/class-tracking-addon-data.php
  admin/tracking/class-tracking-plugin-data.php
  admin/views/class-yoast-feature-toggles.php
  admin/views/class-yoast-integration-toggles.php
  admin/views/redirects.php
  admin/views/tabs/network/features.php
  admin/watchers/class-slug-change-watcher.php
  inc/class-upgrade.php
  inc/class-wpseo-content-images.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-replace-vars.php
  inc/class-wpseo-utils.php
  inc/options/class-wpseo-option-wpseo.php
  inc/sitemaps/class-sitemaps-admin.php
  inc/sitemaps/class-sitemaps.php
Labels: yoast cs/qa, changelog: non-user-facing

#20976 CS/QA: remove unnecessary unused parameters
  tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20977 Tests: use `willReturn()`
  tests/Unit/Admin/MyYoast_Proxy_Test.php
  tests/Unit/Repositories/SEO_Links_Repository_Test.php
  tests/WP/Admin/Asset_Manager_Test.php
  tests/WP/Admin/Editor_Specific_Replace_Vars_Test.php
  tests/WP/Admin/Gutenberg_Compatibility_Test.php
  tests/WP/Admin/Import/AIOSEO_Test.php
  tests/WP/Admin/Import/Premium_SEO_Pack_Test.php
  tests/WP/Admin/Import/Smartcrawl_SEO_Test.php
  tests/WP/Admin/Import/Squirrly_Test.php
  tests/WP/Admin/Meta_Columns_Test.php
  tests/WP/Admin/Metabox/Metabox_Test.php
  tests/WP/Admin/Network_Admin_Test.php
  tests/WP/Admin/Primary_Term_Admin_Test.php
  tests/WP/Admin/Services/File_Size_Service_Test.php
  tests/WP/Inc/Admin_Bar_Menu_Test.php
  tests/WP/Inc/MyYoast_Api_Request_Test.php
  tests/WP/Notifiers/Dismissible_Notification_Test.php
  tests/WP/Sitemaps/Image_Parser_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20978 Tests: WP tests should use snake case fixture methods
  tests/WP/Builders/Indexable_Author_Builder_Test.php
  tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
  tests/WP/Builders/Indexable_Post_Type_Archive_Builder_Test.php
  tests/WP/Builders/Indexable_Term_Builder_Test.php
  tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php
  tests/WP/Frontend/Front_End_Integration_Test.php
  tests/WP/Helpers/First_Time_Configuration_Notice_Helper_Test.php
  tests/WP/Repositories/SEO_Links_Repository_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20979 Modernize: use nullable types
  admin/class-admin-asset-manager.php
  admin/class-database-proxy.php
  admin/class-yoast-dashboard-widget.php
  inc/class-wpseo-admin-bar-menu.php
  src/integrations/third-party/wordproof.php
Labels: yoast cs/qa, changelog: non-user-facing

#20980 Tests: fix some `@covers`
  tests/Unit/Builders/Indexable_Home_Page_Builder_Test.php
  tests/Unit/Builders/Indexable_Post_Type_Archive_Builder_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20981 Docs: various fixes
  admin/watchers/class-slug-change-watcher.php
  config/composer/unit-test-generator.php
  inc/options/class-wpseo-option.php
  src/content-type-visibility/application/content-type-visibility-watcher-actions.php
  src/integrations/blocks/structured-data-blocks.php
  src/integrations/settings-integration.php
  src/integrations/third-party/elementor.php
  src/integrations/watchers/search-engines-discouraged-watcher.php
  src/integrations/watchers/woocommerce-beta-editor-watcher.php
  src/introductions/domain/invalid-user-id-exception.php
  src/promotions/domain/time-interval.php
  src/repositories/indexable-cleanup-repository.php
  tests/Unit/Actions/Importing/Abstract_Aioseo_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Custom_Archive_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Default_Archive_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_General_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Posts_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Posttype_Defaults_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Taxonomy_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Validate_Data_Action_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Dismiss_Notifications_Test.php
  tests/Unit/Helpers/Aioseo_Helper_Test.php
  tests/Unit/Helpers/Pagination_Helper_Test.php
  tests/Unit/Inc/Sitemaps/WPSEO_Sitemaps_Router.php
  tests/Unit/Inc/Yoast_Dynamic_Rewrites_Test.php
  tests/Unit/Integrations/Blocks/Structured_Data_Blocks_Test.php
  tests/Unit/Integrations/Exclude_Attachment_Post_Type_Test.php
  tests/Unit/Integrations/Exclude_Oembed_Cache_Post_Type_Test.php
  tests/Unit/Integrations/Front_End_Integration_Test.php
  tests/Unit/Integrations/Settings_Integration_Test.php
  tests/Unit/Integrations/Support_Integration_Test.php
  tests/Unit/Introductions/Infrastructure/Introductions_Seen_Repository_Test.php
  tests/Unit/Introductions/Infrastructure/Wistia_Embed_Permission_Repository_Test.php
  tests/Unit/Services/Importing/Aioseo_Robots_Provider_Service_Test.php
  tests/Unit/Services/Importing/Aioseo_Robots_Transformer_Service_Test.php
  tests/Unit/Services/Importing/Aioseo_Social_Images_Provider_Service_Test.php
  tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php
  tests/WP/Helpers/First_Time_Configuration_Notice_Helper_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20982 QA: more modern class references
  tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
  tests/WP/Builders/Indexable_Term_Builder_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20983 Modernize: use null coalesce
  admin/class-export.php
  admin/class-yoast-form.php
  admin/import/plugins/class-abstract-plugin-importer.php
  admin/taxonomy/class-taxonomy-fields-presenter.php
  inc/class-addon-manager.php
  inc/class-upgrade.php
  inc/options/class-wpseo-option-titles.php
  inc/options/class-wpseo-taxonomy-meta.php
  lib/orm.php
  src/actions/wincher/wincher-account-action.php
  src/config/oauth-client.php
  src/generators/schema/person.php
  src/integrations/front-end/wp-robots-integration.php
Labels: yoast cs/qa, changelog: non-user-facing

#20985 CS: various minor tweaks
  admin/views/licenses.php
  inc/sitemaps/class-post-type-sitemap-provider.php
  src/helpers/crawl-cleanup-helper.php
  src/integrations/settings-integration.php
  src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/introductions/application/version-trait.php
  tests/Unit/Admin/Import/Import_Settings_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Helpers/Short_Link_Helper_Test.php
  tests/Unit/Inc/Yoast_Dynamic_Rewrites_Test.php
  tests/WP/Builders/Indexable_Author_Builder_Test.php
  tests/WP/Builders/Indexable_Home_Page_Builder_Test.php
  tests/WP/Builders/Indexable_Post_Type_Archive_Builder_Test.php
  tests/WP/Builders/Indexable_Term_Builder_Test.php
  tests/WP/Inc/Yoast_Dynamic_Rewrites_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20986 QA: remove redundant global variable import
  tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20987 Docs: more fixes
  inc/sitemaps/class-post-type-sitemap-provider.php
  src/content-type-visibility/application/content-type-visibility-dismiss-notifications.php
  src/content-type-visibility/application/content-type-visibility-watcher-actions.php
  src/introductions/infrastructure/introductions-seen-repository.php
  src/introductions/infrastructure/wistia-embed-permission-repository.php
  tests/Unit/Content_Type_Visibility/Application/Content_Type_Visibility_Dismiss_Notifications_Test.php
  tests/Unit/Content_Type_Visibility/User_Interface/Content_Type_Visibility_Dismiss_New_Route_Test.php
  tests/WP/Content_Type_Visibility/Dismiss_New_Route_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20988 Tests: unit tests should use snake case fixture methods
  tests/Unit/Analytics/Domain/Missing_Indexable_Bucket_Test.php
  tests/Unit/Analytics/Domain/Missing_Indexable_Count_Test.php
  tests/Unit/Analytics/Domain/To_Be_Cleaned_Indexable_Bucket_Test.php
  tests/Unit/Analytics/Domain/To_Be_Cleaned_Indexable_Count_Test.php
  tests/Unit/Analytics/User_Interface/Last_Completed_Indexation_Integration_Test.php
  tests/Unit/Helpers/Post_Type_Helper_Test.php
  tests/Unit/Repositories/SEO_Links_Repository_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#20990 Composer/PHPCS: update to YoastCS 3.0.0
  .github/workflows/cs.yml
  .phpcs.xml.dist
  admin/class-product-upsell-notice.php
  admin/class-yoast-notification-center.php
  admin/class-yoast-plugin-conflict.php
  admin/import/plugins/class-import-aioseo-v4.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-columns.php
  admin/taxonomy/class-taxonomy.php
  admin/views/tabs/tool/wpseo-export.php
  composer.json
  composer.lock
  config/dependency-injection/deprecated-classes.php
  config/dependency-injection/renamed-classes.php
  inc/class-addon-manager.php
  inc/class-wpseo-utils.php
  inc/sitemaps/class-sitemaps.php
  lib/dependency-injection/container-registry.php
  lib/orm.php
  src/conditionals/third-party/elementor-edit-conditional.php
  src/helpers/crawl-cleanup-helper.php
  src/helpers/current-page-helper.php
  src/helpers/pagination-helper.php
  src/helpers/wpdb-helper.php
  src/integrations/admin/deactivated-premium-integration.php
  src/introductions/application/current-page-trait.php
  src/repositories/indexable-cleanup-repository.php
  tests/Unit/Actions/Importing/Abstract_Aioseo_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Custom_Archive_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Default_Archive_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_General_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Posts_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Posttype_Defaults_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Taxonomy_Settings_Importing_Action_Test.php
  tests/Unit/Actions/Importing/Aioseo_Validate_Data_Action_Test.php
  tests/Unit/Admin/Asset_Analysis_Worker_Location_Test.php
  tests/Unit/Admin/Metabox/Metabox_Editor_Test.php
  tests/Unit/Builders/Indexable_Post_Builder_Test.php
  tests/Unit/Builders/Indexable_Social_Image_Trait_Test.php
  tests/Unit/Builders/Indexable_Term_Builder_Test.php
  tests/Unit/Helpers/Aioseo_Helper_Test.php
  tests/Unit/README.md
  tests/Unit/Services/Importing/Aioseo_Robots_Provider_Service_Test.php
  tests/Unit/Services/Importing/Aioseo_Robots_Transformer_Service_Test.php
  tests/Unit/Services/Importing/Aioseo_Social_Images_Provider_Service_Test.php
  wp-seo-main.php
Labels: yoast cs/qa, changelog: non-user-facing

#20949 Set the minimum supported WordPress version to 6.3.
  .github/workflows/test.yml
  tests/Unit/Inc/Addon_Manager_Test.php
  tests/Unit/bootstrap.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#20993 Composer: update dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#20956 Force page type to itempage for products
  admin/metabox/class-metabox.php
  packages/components/src/select/Select.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
  packages/js/src/components/SchemaTab.js
  packages/js/src/settings/routes/templates/post-type.js
  src/integrations/settings-integration.php
Labels: changelog: other

#20997 Prevent failing finish-coveralls workflow
  .github/workflows/finish-coveralls.yml
  .github/workflows/jstest.yml
  .github/workflows/test.yml
Labels: changelog: non-user-facing

#20991 Improve the feedback for the non-inclusive phrase aging dependants
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
Labels: changelog: enhancement, Shopify

#21002 Carryforward yoastseo test results
  .github/workflows/finish-coveralls.yml
Labels: changelog: non-user-facing

#20998 Improve function descriptions for Inclusive language helpers
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesConsecutiveWords.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesWordsAtPosition.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticiple.js
Labels: technical-debt, changelog: non-user-facing

#20950 Improves handling of &nbsp; characters
  packages/js/src/watchers/elementorWatcher.js
  packages/js/tests/decorator/gutenberg.test.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getWordsForHTMLParserSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keywordCountSpec.js
  packages/yoastseo/spec/parse/build/buildSpec.js
  packages/yoastseo/src/helpers/htmlEntities.js
  packages/yoastseo/src/languageProcessing/helpers/word/getWordsForHTMLParser.js
Labels: innovation, changelog: non-user-facing, Shopify

#20952 Fixes grunt check warnings in yoastseo
  packages/yoastseo/package.json
  packages/yoastseo/spec/appSpec.js
  packages/yoastseo/spec/config/getTransliterationsSpec.js
  packages/yoastseo/spec/helpers/formatNumberSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/buildTopicStemsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/createRegexFromArraySpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/createWordRegexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/matchStringWithRegexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/internal/detectAndStemRegularParticipleSpec.js
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ja/helpers/customGetStemmerSpec.js
  packages/yoastseo/spec/parse/build/private/getTextElementPositionsSpec.js
  packages/yoastseo/spec/scoring/InclusiveLanguageAssessorSpec.js
  packages/yoastseo/spec/scoring/assessments/assessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByExceptionSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedByExceptionSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticipleSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isPrecededByExceptionSpec.js
  packages/yoastseo/spec/values/PaperSpec.js
  packages/yoastseo/spec/worker/createWorkerSpec.js
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
  packages/yoastseo/src/config/getTransliterations.js
  packages/yoastseo/src/languageProcessing/helpers/transliterate/transliterate.js
  packages/yoastseo/src/languageProcessing/helpers/word/addWordboundary.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/PassiveVoiceAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/TransitionWordsAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/WordComplexityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/FunctionWordsInKeyphraseAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/ImageCountAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/IntroductionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseDistributionAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInImageTextAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseInSEOTitleAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeyphraseLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/MetaDescriptionLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SingleH1Assessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextCompetingLinksAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/TextTitleAssessment.js
  packages/yoastseo/src/values/Mark.js
  yarn.lock
Labels: changelog: other

#21009 Docs: fix some filter docblocks
  inc/class-wpseo-content-images.php
  src/actions/configuration/first-time-configuration-action.php
  src/builders/indexable-builder.php
  src/generators/schema-generator.php
  src/helpers/schema/language-helper.php
  src/integrations/front-end-integration.php
  src/presenters/schema-presenter.php
Labels: yoast cs/qa, changelog: non-user-facing

#21010 PHP 8.2: prevent dynamic property deprecations
  admin/class-bulk-editor-list-table.php
  admin/class-database-proxy.php
Labels: yoast cs/qa, changelog: other

#20936 Change the plugin name showing on the notification from 'Yoast SEO Multilingual' to 'WPML SEO'
  src/integrations/third-party/wpml-wpseo-notification.php
Labels: changelog: non-user-facing
