Repository Yoast/wordpress-seo, pull requests merged in 2023-01, with the labels that each got.

#19491 Add ariaLabel to logo and focus style
  packages/js/src/settings/app.js
Labels: UI change, changelog: non-user-facing

#19489 DUPP-884-improve-the-discard-all-changes-dialog-a-11-y
  packages/js/src/settings/components/form-layout.js
  packages/js/src/settings/components/introduction.js
  packages/js/src/settings/components/search.js
  packages/ui-library/src/components/modal/index.js
  packages/ui-library/src/components/modal/stories.js
  packages/ui-library/src/elements/title/index.js
  packages/ui-library/src/elements/title/style.css
Labels: changelog: non-user-facing

#19500 Settings UI: mirror arrows in rtl language #295
  css/src/admin-global.css
  packages/js/src/indexables-page/components/suggested-links-modal.js
  packages/js/src/integrations-page/algolia-integration.js
  packages/js/src/integrations-page/simple-integration.js
  packages/js/src/integrations-page/toggleable-integration.js
  packages/js/src/settings/app.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/settings/routes/site-features.js
Labels: UI change, changelog: other

#19507 Settings-UI: #317 improve description for additional url parameters to allow
  packages/js/src/settings/routes/crawl-optimization.js
Labels: changelog: non-user-facing

#19497 Settings UI: Mobile view: Fix detected mobile view issues
  css/src/new-settings.css
  packages/js/package.json
  packages/js/src/settings/app.js
  packages/js/src/settings/components/search.js
  packages/js/src/settings/components/sidebar-navigation.js
  packages/js/src/settings/initialize.js
  packages/ui-library/package.json
  packages/ui-library/src/components/notifications/style.css
  packages/ui-library/src/components/sidebar-navigation/index.js
  packages/ui-library/src/components/sidebar-navigation/mobile.js
  packages/ui-library/src/components/sidebar-navigation/stories.js
  packages/ui-library/src/components/sidebar-navigation/submenu-item.js
  packages/ui-library/src/index.js
  yarn.lock
Labels: changelog: non-user-facing

#19503 #301 get premium title formating
  css/src/yst_plugin_tools.css
  packages/js/src/settings/components/sidebar-recommendations.js
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: other

#19511 Settings UI: change description of the media pages toggle
  packages/js/src/settings/routes/media-pages.js
Labels: changelog: non-user-facing

#19399 Highlighting feature: Also highlight image caption in Classic editor
  packages/js/src/decorator/gutenberg.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/image/imageInTextSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/regex/matchStringWithRegexSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesSpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/helpers/html/findEmptyDivisions.js
  packages/yoastseo/src/languageProcessing/helpers/image/imageInText.js
  packages/yoastseo/src/languageProcessing/helpers/regex/matchStringWithRegex.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentences.js
Labels: changelog: bugfix

#19498 Simplifies lexicon for Portuguese participles
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/languageProcessing/languages/pt/helpers/internal/getParticiplesSpec.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/internal/getParticiples.js
Labels: changelog: non-user-facing, Shopify

#19537 settings-ui: fix WP content height to match WP menu
  packages/js/src/settings/initialize.js
Labels: changelog: non-user-facing

#19538 settings-ui: 341 update intro modal copy
  packages/js/src/settings/components/introduction.js
Labels: changelog: non-user-facing

#19535 19436 make sure all links do have a focus style
  packages/js/src/settings/app.js
  packages/js/src/settings/components/formik-media-select-field.js
  packages/js/src/settings/components/sidebar-recommendations.js
  packages/js/src/settings/routes/site-features.js
  packages/ui-library/src/components/root/style.css
  packages/ui-library/src/components/sidebar-navigation/submenu-item.js
  packages/ui-library/src/elements/button/style.css
  packages/ui-library/src/elements/link/style.css
  packages/ui-library/src/elements/tag-input/index.js
  packages/ui-library/src/elements/validation/style.css
Labels: changelog: enhancement

#19402 Pc 701 improve inclusive alternatives for different meanings of crazy
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByExceptionSpec.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityRulesData.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByException.js
Labels: changelog: enhancement

#19527 [ES] Improve passive voice detection
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/getParticiples.js
Labels: changelog: non-user-facing, Shopify

#19580 update date format in readme.txt
  readme.txt
Labels: changelog: non-user-facing

#19539 update plugin-grunt-tasks to 2.4
  package.json
  yarn.lock
Labels: changelog: non-user-facing

#19592 Minor: [Search functionality] Fix the font styles in the search results box.
  packages/js/src/settings/components/search.js
  packages/ui-library/src/elements/title/index.js
  packages/ui-library/src/elements/title/style.css
Labels: UI change, changelog: other

#19586 settings ui: 344 minor missing validation in max number of characters to allow in searches
  packages/js/src/settings/helpers/validation.js
  packages/js/src/settings/routes/crawl-optimization.js
Labels: changelog: non-user-facing

#19593 Composer: update YoastCS and dependencies
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#19596 Settings: remove required validation rule for other social profiles
  packages/js/src/settings/helpers/validation.js
Labels: changelog: non-user-facing

#19591 Settings UI: remove user social profile fields
  packages/js/src/settings/components/formik-user-select-field.js
  packages/js/src/settings/helpers/index.js
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/helpers/submit.js
  packages/js/src/settings/helpers/user-social-profiles.js
  packages/js/src/settings/helpers/validation.js
  packages/js/src/settings/routes/site-representation.js
  packages/js/src/settings/store/users.js
  src/integrations/settings-integration.php
  tests/unit/integrations/settings-integration-test.php
Labels: UI change, changelog: non-user-facing

#19589 Make an ability to clear tags.
  packages/js/src/settings/components/formik-tag-field.js
  packages/ui-library/src/elements/tag-input/index.js
  packages/ui-library/src/elements/tag-input/stories.js
Labels: changelog: non-user-facing

#19536 settings ui 19521 improve the feature cards accessibility
  packages/js/src/settings/components/form-layout.js
  packages/js/src/settings/components/introduction.js
  packages/js/src/settings/components/search.js
  packages/js/src/settings/routes/site-features.js
  packages/ui-library/src/components/card/index.js
  packages/ui-library/src/components/modal/index.js
  packages/ui-library/src/components/modal/stories.js
  packages/ui-library/src/components/toggle-field/index.js
  packages/ui-library/src/elements/link/stories.js
  packages/ui-library/src/elements/title/index.js
  packages/ui-library/src/elements/title/style.css
Labels: changelog: non-user-facing

#19601 19598 minor update upsell title design in settings
  packages/js/src/settings/app.js
  packages/js/src/settings/components/sidebar-recommendations.js
Labels: UI change, changelog: non-user-facing

#19611 Use shortlinks for Wincher links in popup
  src/helpers/wincher-helper.php
Labels: changelog: non-user-facing

#19615 19520 improve navigation experience a11y
  packages/js/package.json
  packages/js/src/settings/components/route-layout.js
  yarn.lock
Labels: changelog: non-user-facing

#19609 310 minor validation rest error may block new settings from saving
  packages/js/src/settings/components/formik-media-select-field.js
  packages/js/src/settings/helpers/validation.js
  packages/js/src/settings/store/media.js
Labels: changelog: non-user-facing

#19512 fix: remove black Friday and cyber Monday sales code
  css/src/yst_plugin_tools.css
  src/presenters/admin/sidebar-presenter.php
Labels: changelog: non-user-facing

#19613 Avoid duplicate unindexed entries in indexable table
  inc/class-upgrade.php
  src/builders/indexable-builder.php
Labels: changelog: non-user-facing

#19622 Settings: add search keywords
  packages/js/src/settings/helpers/search.js
Labels: changelog: non-user-facing

#19390 PC-173-disregard-function-words-for-word-complexity
  packages/yoastseo/spec/languageProcessing/languages/es/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/languages/fr/helpers/checkIfWordIsComplexSpec.js
  packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js
  packages/yoastseo/spec/scoring/collectionPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/src/languageProcessing/languages/de/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/de/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/frequencyList.json
  packages/yoastseo/src/languageProcessing/languages/en/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/languages/fr/helpers/checkIfWordIsComplex.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
Labels: changelog: enhancement, Shopify

#19597 Add specs for each non-inclusive phrase in the Inclusive language assessment
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/testHelpers/testHelper.js
Labels: changelog: non-user-facing

#19630 added link to organisation/person radio button description
  packages/js/src/settings/routes/site-representation.js
Labels: changelog: non-user-facing

#19604 settings-ui: 19523 improve mobile navigation a11y
  packages/js/src/settings/app.js
  packages/ui-library/src/components/sidebar-navigation/mobile.js
Labels: changelog: non-user-facing

#19519 Allows highlighting in captions
  packages/js/src/decorator/gutenberg.js
Labels: changelog: enhancement

#19610 [IT] Improve passive voice detection
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/src/languageProcessing/languages/it/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/getParticiples.js
Labels: changelog: non-user-facing, Shopify

#19640 Settings: fix post types data for JS
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#19633 Settings UI: 19533 settings UI UI library fix focus style for radio inline block variant
  packages/ui-library/src/elements/radio/style.css
Labels: changelog: non-user-facing

#19608 Settings / UI library: increase the Toggle contrast a little
  packages/ui-library/src/elements/toggle/style.css
Labels: changelog: non-user-facing

#19642 fix upsell title on general page
  css/src/yst_plugin_tools.css
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: non-user-facing

#19650 Dupp 900 introduction modal dialog accessibility
  packages/js/src/settings/components/introduction.js
  packages/js/tests/settings/__snapshots__/search.test.js.snap
  packages/ui-library/src/components/modal/index.js
Labels: changelog: non-user-facing

#19628 Settings ui: 337 minor issue with inconsistent search behavior
  packages/js/src/settings/hooks/use-router-scroll-restore.js
Labels: changelog: non-user-facing

#19646 Settings: fix skip to main content
  packages/js/src/settings/app.js
  packages/js/src/settings/initialize.js
  packages/ui-library/src/components/sidebar-navigation/mobile.js
Labels: changelog: non-user-facing

#19470 Add EDD integration
  packages/js/images/edd-logo.svg
  packages/js/src/integrations-page/schema-api-integrations.js
  src/conditionals/third-party/edd-conditional.php
  src/integrations/admin/integrations-page.php
  src/integrations/third-party/edd.php
Labels: UI change, changelog: enhancement

#19658 Settings: optional vertical scroll for notifications
  css/src/new-settings.css
  packages/ui-library/src/components/notifications/style.css
Labels: changelog: non-user-facing

#19657 Settings: always require a value for the search character limit
  packages/js/src/settings/helpers/validation.js
Labels: changelog: non-user-facing

#19653 19531 add link to plugin overview to premium update notice
  src/integrations/admin/old-premium-integration.php
  tests/unit/integrations/admin/old-premium-integration-test.php
Labels: UI change, changelog: non-user-facing

#19406 DUPP-822-update-mobile-previews-to-account-for-site-name
  admin/formatter/class-metabox-formatter.php
  packages/js/src/containers/SnippetEditor.js
  packages/js/tests/containers/SnippetEditor.test.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: enhancement

#19662 Revert "DUPP-822-update-mobile-previews-to-account-for-site-name"
  admin/formatter/class-metabox-formatter.php
  packages/js/src/containers/SnippetEditor.js
  packages/js/tests/containers/SnippetEditor.test.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: non-user-facing

#19663 Revert "Revert "DUPP-822-update-mobile-previews-to-account-for-site-name""
  admin/formatter/class-metabox-formatter.php
  packages/js/src/containers/SnippetEditor.js
  packages/js/tests/containers/SnippetEditor.test.js
  packages/search-metadata-previews/src/snippet-editor/SnippetEditor.js
  packages/search-metadata-previews/src/snippet-preview/SnippetPreview.js
Labels: changelog: enhancement

#19666 19665 new public post types taxonomies notifications cannot be dismissed
  admin/views/tabs/metas/post-types.php
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#19366 Adds Extra link in the plugin overview.
  admin/class-admin.php
  src/helpers/first-time-configuration-notice-helper.php
  src/integrations/admin/first-time-configuration-notice-integration.php
  src/surfaces/helpers-surface.php
Labels: UI change, changelog: enhancement

#19668 Disallow loading wp-polyfill-inert dependency in web worker.
  packages/js/src/analysis-worker.js
Labels: changelog: non-user-facing

#19676 Merge the inclusive language improvements to trunk
  admin/formatter/class-metabox-formatter.php
  css/src/metabox.css
  packages/js/src/analysis/getIndicatorForScore.js
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
  packages/js/src/helpers/addCheckToChecklist.js
  packages/js/src/ui/publishBox.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/indexSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByExceptionSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/testHelpers/testHelper.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityRulesData.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByException.js
Labels: changelog: non-user-facing

#19675 3793 move edd integration to premium
  packages/js/src/integrations-page/schema-api-integrations.js
  packages/js/src/integrations-page/simple-integration.js
  src/conditionals/third-party/edd-conditional.php
  src/integrations/third-party/edd.php
Labels: UI change, changelog: enhancement

#19673 Make using the SEO Link table as optional, when generating schema for an image based on its URL
  src/helpers/image-helper.php
  src/helpers/schema/image-helper.php
  tests/unit/helpers/schema/image-helper-test.php
Labels: changelog: non-user-facing

#19678 [PT][ES] Optimizes participle detection for Portuguese and Spanish
  packages/yoastseo/src/languageProcessing/languages/es/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/es/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/it/helpers/internal/getParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/internal/passiveVoiceParticiples.js
  packages/yoastseo/src/languageProcessing/languages/pt/helpers/internal/getParticiples.js
Labels: changelog: non-user-facing, Shopify

#19688 [IM] Highlighting feature: Enable highlighting text containing html tags in Classic editor and make sure yoastmark doesn't corrupt anchor tags in Shopify
  packages/js/src/decorator/gutenberg.js
  packages/js/src/decorator/tinyMCE.js
  packages/yoastseo/spec/fullTextTests/testTexts/ar/arabicPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/de/germanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/hu/hungarianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/id/indonesianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/nb/norwegianPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/tr/turkishPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/html/normalizeHTMLSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/SentenceTokenizerSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/markWordsInSentenceSpec.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/src/languageProcessing/helpers/html/getFieldsToMark.js
  packages/yoastseo/src/languageProcessing/helpers/html/normalizeHTML.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/SentenceTokenizer.js
  packages/yoastseo/src/languageProcessing/helpers/word/markWordsInSentences.js
  packages/yoastseo/src/languageProcessing/index.js
Labels: changelog: bugfix, Shopify

#19693 fix og:image for same size as custom size
  inc/class-wpseo-image-utils.php
Labels: changelog: bugfix

#19679 Mastodon integration
  admin/class-config.php
  admin/tracking/class-tracking-settings-data.php
  inc/options/class-wpseo-option-social.php
  packages/js/images/mastodon-logo.svg
  packages/js/src/integrations-page/helper.js
  packages/js/src/integrations-page/integrations-grid.js
  packages/js/src/integrations-page/mastodon-integration.js
  packages/js/src/integrations-page/other-integrations.js
  packages/js/src/settings/routes/site-representation.js
  src/actions/configuration/first-time-configuration-action.php
  src/actions/integrations-action.php
  src/generators/schema/organization.php
  src/helpers/social-profiles-helper.php
  src/integrations/admin/first-time-configuration-integration.php
  src/integrations/admin/integrations-page.php
  src/integrations/front-end-integration.php
  src/routes/integrations-route.php
  src/surfaces/helpers-surface.php
  tests/unit/actions/configuration/first-time-configuration-action-test.php
  tests/unit/generators/schema/organization-test.php
  tests/unit/helpers/social-profiles-helper-test.php
Labels: UI change, changelog: non-user-facing

#19677 19452 fix richtext notices in block editor
  packages/js/src/structured-data-blocks/faq/components/FAQ.js
  packages/js/src/structured-data-blocks/faq/components/Question.js
  packages/js/src/structured-data-blocks/how-to/components/HowTo.js
  packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
Labels: changelog: non-user-facing

#19696 Settings: fix media pages when not indexing attachments
  src/helpers/post-type-helper.php
  src/helpers/taxonomy-helper.php
  src/integrations/settings-integration.php
Labels: changelog: bugfix

#19700 Settings: 19699 format archives settings page bug
  src/helpers/post-type-helper.php
  src/helpers/taxonomy-helper.php
  src/integrations/settings-integration.php
Labels: changelog: bugfix

#19708 Fix translations settings
  packages/js/src/settings/components/route-layout.js
  packages/js/src/settings/routes/site-connections.js
Labels: changelog: other

#19475 Highlighting feature: Support annotation in Yoast FAQ and How-To blocks
  packages/js/src/decorator/gutenberg.js
  packages/js/src/structured-data-blocks/faq/components/Question.js
  packages/js/src/structured-data-blocks/how-to/components/HowTo.js
  packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
  packages/js/tests/decorator/gutenberg.test.js
  packages/yoastseo/spec/fullTextTests/testTexts/ca/catalanPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pt/portuguesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/scoring/productPages/fullTextTests/testTexts/en/englishPaper3.js
Labels: innovation, changelog: enhancement

#19704 Add validation and search tags for Mastodon field
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/helpers/validation.js
Labels: changelog: non-user-facing

#19629 Add defensive coding for find_* functions for indexable creation
  admin/class-meta-columns.php
  src/actions/indexing/abstract-link-indexing-action.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/repositories/indexable-repository.php
  src/surfaces/meta-surface.php
Labels: innovation, changelog: non-user-facing

#19703 19453 fix notice in the block editor for faq and how to blocks
  packages/js/src/structured-data-blocks/convertValueToStringRichText.js
  packages/js/src/structured-data-blocks/faq/components/Question.js
  packages/js/src/structured-data-blocks/how-to/block.js
  packages/js/src/structured-data-blocks/how-to/components/HowToStep.js
  src/generators/schema/howto.php
  src/integrations/blocks/structured-data-blocks.php
Labels: changelog: non-user-facing

#19720 Non-inclusive phrase "ex-offenders" returns with two feedback strings
  packages/yoastseo/spec/scoring/InclusiveLanguageAssessorSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
Labels: changelog: non-user-facing

#19733 fix site name missing in mobile preview in elementor
  packages/js/src/elementor/containers/SnippetEditor.js
Labels: changelog: bugfix

#19741 Fix notices about social inputs in FTC
  src/generators/schema/organization.php
  src/helpers/social-profiles-helper.php
  tests/unit/generators/schema/organization-test.php
Labels: changelog: non-user-facing

#19735 Mastodon: bump the minimum version in the notification urging to update Premium and update shortlink
  packages/js/src/settings/routes/site-representation.js
  src/integrations/admin/old-premium-integration.php
Labels: changelog: non-user-facing

#19388 Dupp 820 when attachment setting is toggled
  inc/class-upgrade.php
  src/builders/indexable-builder.php
  src/builders/indexable-link-builder.php
  src/config/indexing-reasons.php
  src/helpers/attachment-cleanup-helper.php
  src/integrations/watchers/indexable-attachment-watcher.php
  src/presenters/admin/indexing-notification-presenter.php
  src/repositories/seo-links-repository.php
  tests/unit/builders/indexable-builder-test.php
  tests/unit/helpers/attachment-cleanup-helper-test.php
Labels: changelog: non-user-facing

#19736 Inclusive language: improve feedback string for some non-inclusive phrases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: changelog: non-user-facing, Shopify

#19714 Release of package Yoastseo 1.91.1
  packages/js/package.json
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/package.json
  packages/yoast-components/package.json
  packages/yoastseo/CHANGELOG.md
  packages/yoastseo/package.json
Labels: changelog: non-user-facing

#19712 Adds a filter to allow developers the option to manipulate which post…
  src/helpers/post-type-helper.php
Labels: innovation, changelog: other

#19395 Document primary libraries and concepts used in new settings UI
  packages/js/src/settings/readme.md
Labels: changelog: non-user-facing

#19749 19590 first time configuration remove user social profiles
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/helpers/index.js
  packages/js/src/first-time-configuration/tailwind-components/steps/site-representation/person-section.js
  packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-input-person-section.js
  packages/js/src/first-time-configuration/tailwind-components/steps/social-profiles/social-profiles-step.js
  src/actions/configuration/first-time-configuration-action.php
  src/helpers/social-profiles-helper.php
  src/integrations/admin/first-time-configuration-integration.php
  src/routes/first-time-configuration-route.php
  tests/unit/actions/configuration/first-time-configuration-action-test.php
  tests/unit/routes/first-time-configuration-route-test.php
Labels: UI change, changelog: enhancement

#19772 Introduce and use a new option to keep track when a notice to update Premium has been dismissed
  inc/options/class-wpseo-option-wpseo.php
  src/integrations/admin/old-premium-integration.php
  tests/unit/integrations/admin/old-premium-integration-test.php
Labels: changelog: non-user-facing
