Repository Yoast/wordpress-seo, pull requests merged in 2024-03, with the labels that each got.

#21194 Allow X.com in ftc
  src/helpers/social-profiles-helper.php
Labels: changelog: bugfix

#20874 Optimize build commands & building the plugin js
  .eslintrc
  .github/workflows/jstest.yml
  config/grunt/task-config/aliases.yaml
  config/grunt/task-config/shell.js
  package.json
  packages/analysis-report/.eslintrc.js
  packages/analysis-report/babel.config.js
  packages/analysis-report/package.json
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/analysis-report/tests/__snapshots__/SiteSEOReportTest.js.snap
  packages/components/.babelrc
  packages/components/jest.config.js
  packages/components/package.json
  packages/components/postcss.config.js
  packages/components/tests/__snapshots__/AlertTest.js.snap
  packages/components/tests/__snapshots__/styledSectionTest.js.snap
  packages/e2e-tests/package.json
  packages/eslint/default.yml
  packages/feature-flag/.babelrc
  packages/feature-flag/jest.config.js
  packages/feature-flag/package.json
  packages/helpers/.babelrc
  packages/helpers/jest.config.js
  packages/helpers/package.json
  packages/js/.eslintrc.js
  packages/js/package.json
  packages/replacement-variable-editor/.babelrc
  packages/replacement-variable-editor/.eslintrc.js
  packages/replacement-variable-editor/jest.config.js
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/.babelrc
  packages/search-metadata-previews/.eslintrc.js
  packages/search-metadata-previews/jest.config.js
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/.babelrc
  packages/social-metadata-forms/jest.config.js
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/.babelrc
  packages/social-metadata-previews/jest.config.js
  packages/social-metadata-previews/package.json
  packages/style-guide/.babelrc
  packages/style-guide/package.json
  packages/ui-library/babel.config.js
  packages/ui-library/package.json
  packages/ui-library/tests/__image_snapshots__/storyshots-js-image-snapshot-tests-1-elements-tooltip-factory-1-snap.png
  packages/yoast-components/.babelrc
  packages/yoast-components/composites/Plugin/Shared/tests/__snapshots__/KeywordInputTest.js.snap
  packages/yoast-components/package.json
  packages/yoastseo/.babelrc
  packages/yoastseo/.eslintrc-tests
  packages/yoastseo/jest.config.js
  packages/yoastseo/package.json
  packages/yoastseo/spec/helpers/errorsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/spec/languageProcessing/researches/keyphraseDistributionSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseLengthAssessmentSpec.js
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/worker/createWorker.js
  yarn.lock
Labels: technical-debt, innovation, changelog: non-user-facing, Shopify

#21182 Makes sure the slug is synced correctly when the post is in draft.
  packages/js/src/watchers/elementorWatcher.js
Labels: changelog: bugfix

#21195 Fix GH actions' JS tests when not needing to run yoastseo tests
  .github/workflows/jstest.yml
Labels: changelog: non-user-facing

#21160 Refactor enabled plugin features
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  composer.json
  packages/js/src/analysis/isContentAnalysisActive.js
  packages/js/src/analysis/isCornerstoneContentActive.js
  packages/js/src/analysis/isInclusiveLanguageAnalysisActive.js
  packages/js/src/analysis/isKeywordAnalysisActive.js
  packages/js/src/initializers/post-scraper.js
  src/editors/application/analysis-features/enabled-analysis-features-repository.php
  src/editors/domain/analysis-features/analysis-feature.php
  src/editors/domain/analysis-features/analysis-features-list.php
  src/editors/framework/analysis-feature-interface.php
  src/editors/framework/cornerstone-content.php
  src/editors/framework/inclusive-language-analysis.php
  src/editors/framework/keyphrase-analysis.php
  src/editors/framework/previously-used-keyphrase.php
  src/editors/framework/readability-analysis.php
  src/editors/framework/word-form-recognition.php
  tests/Unit/Editors/Domain/Analysis_Features/Analysis_Feature_Test.php
  tests/Unit/Editors/Domain/Analysis_Features/Analysis_Features_List_Test.php
  tests/Unit/Editors/Framework/Cornerstone_Content_Test.php
  tests/Unit/Editors/Framework/Inclusive_Language_Analysis_Test.php
  tests/Unit/Editors/Framework/Keyphrase_Analysis_Test.php
  tests/Unit/Editors/Framework/Previously_Used_Keyphrase_Test.php
  tests/Unit/Editors/Framework/Readability_Analysis_Test.php
  tests/Unit/Editors/Framework/Word_Form_Recognition_Test.php
  tests/WP/Formatter/Metabox_Formatter_Test.php
Labels: changelog: non-user-facing

#21109 Add upgrade routine integration tests
  inc/class-upgrade.php
  inc/sitemaps/class-sitemaps-cache-validator.php
  tests/WP/Doubles/Inc/Upgrade_Double.php
  tests/WP/Inc/Upgrade_Test.php
Labels: changelog: non-user-facing

#21199 Add cross-env before using NODE_ENV
  config/grunt/task-config/shell.js
Labels: changelog: non-user-facing

#21148 Add placeholders to upgrade routine
  composer.json
  inc/class-upgrade-history.php
  inc/class-upgrade.php
Labels: changelog: non-user-facing

#20926 Performance: yoastseo research
  apps/content-analysis/.eslintrc
  apps/content-analysis/.nvmrc
  apps/content-analysis/config/webpack.config.js
  apps/content-analysis/package.json
  apps/content-analysis/src/App.js
  apps/content-analysis/src/analysis.worker.js
  apps/content-analysis/src/components/Container.js
  apps/content-analysis/src/components/DisabledWrapper.js
  apps/content-analysis/src/components/Performance.js
  apps/content-analysis/src/components/SelectTestPaper.js
  apps/content-analysis/src/components/SimpleMultiSelect.js
  apps/content-analysis/src/index.js
  apps/content-analysis/src/redux/actions/performance.js
  apps/content-analysis/src/redux/reducers/performance.js
  apps/content-analysis/src/redux/reducers/rootReducer.js
  apps/content-analysis/src/redux/utils/StoreSubscriber.js
  apps/content-analysis/src/utils/calculateProminentWords.js
  apps/content-analysis/src/utils/measureTextWidth.js
  apps/content-analysis/src/utils/prepareResearcher.js
  apps/content-analysis/src/utils/runKeyphraseAnalysis.js
  apps/content-analysis/yarn.lock
  packages/yoastseo/src/languageProcessing/researches/getKeywordDensity.js
Labels: changelog: non-user-facing

#21196 Replace .substr() with .substring() (or .slice()) in JS files since it's deprecated
  apps/content-analysis/config/paths.js
  config/webpack/webpack.config.base.js
  packages/components/src/GenerateId.js
  packages/js/src/helpers/createInterpolateElement.js
  packages/js/src/helpers/replacementVariableHelpers.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/workouts/components/WorkoutsPage.js
  packages/yoastseo/spec/languageProcessing/languages/en/config/abbreviationsSpec.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/freeAuxiliaryParticipleOrder/getClausesSplitOnStopWords.js
  packages/yoastseo/src/languageProcessing/helpers/passiveVoice/periphrastic/getClauses.js
  packages/yoastseo/src/languageProcessing/languages/id/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/languages/ja/customResearches/findKeyphraseInSEOTitle.js
  packages/yoastseo/src/languageProcessing/languages/ru/helpers/internal/stem.js
  packages/yoastseo/src/languageProcessing/researches/findKeyphraseInSEOTitle.js
  packages/yoastseo/src/markers/addMarkSingleWord.js
Labels: changelog: other

#21198 Remove notification when WooCommerce is deactivated or uninstalled
  admin/class-plugin-availability.php
  admin/class-suggested-plugins.php
  composer.json
  src/integrations/watchers/woocommerce-beta-editor-watcher.php
  tests/Unit/Admin/Suggested_Plugins_Add_Notifications_Test.php
  tests/Unit/Admin/Suggested_Plugins_Register_Hooks_Test.php
  tests/Unit/Admin/Suggested_Plugins_TestCase.php
  tests/Unit/Integrations/Watchers/Woocommerce_Beta_Editor_Watcher_Test.php
  tests/WP/Admin/Plugin_Suggestions_Test.php
  tests/WP/Doubles/Admin/Plugin_Availability_Double.php
  tests/WP/Doubles/Conditionals/False_Conditional_Double.php
  tests/WP/Doubles/Conditionals/True_Conditional_Double.php
Labels: changelog: other

#20925 Small performance enhancements for the content analysis
  packages/yoastseo/src/languageProcessing/researches/getWordForms.js
  packages/yoastseo/src/parse/build/private/tokenize.js
Labels: changelog: non-user-facing

#21201 Re-instate correct max width for page type field.
  packages/js/src/settings/routes/templates/post-type.js
Labels: UI change, changelog: other

#21219 Add defensive coding to stop deprecation warnings
  inc/class-addon-manager.php
  tests/Unit/Inc/Addon_Manager_Test.php
Labels: changelog: other

#21178 Fixes a bug where the attachment would never be marked as external.
  src/helpers/image-helper.php
  tests/Unit/Helpers/Image_Helper_Test.php
  tests/WP/Helpers/Get_Attachment_By_Url_Image_Helper_Test.php
Labels: changelog: enhancement

#21237 Sets the WordPress tested up to version to 6.5
  readme.txt
  tests/Unit/bootstrap.php
  wp-seo-main.php
Labels: changelog: other

#21244 Adds click to buy data attributes.
  admin/watchers/class-slug-change-watcher.php
Labels: changelog: non-user-facing

#21246 Rename 'leiCode' to 'LEI code'
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/site-representation.js
Labels: UI change, changelog: other

#21241 Fix ES_WP_Query incompatibility issue
  src/helpers/current-page-helper.php
  tests/Unit/Helpers/Current_Page_Helper_Test.php
  tests/WP/Helpers/Current_Page_Helper_Test.php
Labels: changelog: enhancement

#21253 Prevent Mockery from being updated to the buggy 1.6.10 version
  .github/workflows/test.yml
  composer.json
  composer.lock
Labels: changelog: non-user-facing

#21262 Revert: prevent Mockery to be updated to the buggy 1.6.10 version
  .github/workflows/test.yml
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#21249 Fix coverage report for the WPSEO_Suggested_Plugins class
  tests/Unit/Admin/Suggested_Plugins_Add_Notifications_Test.php
  tests/Unit/Admin/Suggested_Plugins_Construct_Test.php
Labels: changelog: non-user-facing

#21263 Prevent unnecessary redirects by not using the wrong URLs in hyperlinks
  packages/js/src/ai-generator/components/modal-content.js
  packages/js/src/introductions/components/content.js
Labels: community-patch

#21264 Re-instate original checks
  src/helpers/current-page-helper.php
  tests/Unit/Helpers/Current_Page_Helper_Test.php
Labels: changelog: non-user-facing

#21231 Removed the Mobile-Friendly test link from the admin menu bar
  inc/class-wpseo-admin-bar-menu.php
Labels: changelog: other

#21268 Make language-specific checks work for all locale variations
  packages/yoastseo/spec/languageProcessing/helpers/match/matchTextWithTransliterationSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/addWordBoundarySpec.js
  packages/yoastseo/src/languageProcessing/helpers/match/matchTextWithTransliteration.js
  packages/yoastseo/src/languageProcessing/helpers/word/addWordboundary.js
Labels: changelog: bugfix

#21247 Introduce allowed MIME type check for social templates images
  packages/js/src/settings/helpers/validation.js
Labels: changelog: enhancement

#21260 Prevent unsupported images to be used in the twitter image tag
  src/generators/twitter-image-generator.php
  src/helpers/open-graph/image-helper.php
  src/helpers/twitter/image-helper.php
  src/values/twitter/images.php
  tests/Unit/Generators/Twitter_Image_Generator_Test.php
  tests/Unit/Helpers/Open_Graph/Image_Helper_Test.php
  tests/Unit/Helpers/Twitter/Image_Helper_Test.php
Labels: changelog: enhancement

#21266 Update transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/de/config/transitionWords.js
Labels: community-patch, changelog: other, Shopify
