Repository Yoast/wordpress-seo, pull requests merged in 2024-07, with the labels that each got.

#21368 Move generic site data into self contained objects.
  admin/formatter/class-metabox-formatter.php
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  src/editors/application/integrations/integration-information-repository.php
  src/editors/application/site/website-information-repository.php
  src/editors/framework/site/base-site-information.php
  src/editors/framework/site/post-site-information.php
  src/editors/framework/site/term-site-information.php
  tests/Unit/Doubles/Editors/Site_Information_Mocks_Trait.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/WP/Formatter/Metabox_Formatter_Test.php
  tests/WP/Formatter/Post_Metabox_Formatter_Test.php
  tests/WP/Formatter/Term_Metabox_Formatter_Test.php
Labels: changelog: non-user-facing

#21458 Bump deprecation version to 23.1
  admin/formatter/class-post-metabox-formatter.php
Labels: changelog: non-user-facing

#21461 Fixes the previously used keywords in terms not expecting script data
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
Labels: changelog: non-user-facing

#21410 Release `yoastseo` and preview packages to NPM
  packages/analysis-report/package.json
  packages/browserslist-config/index.js
  packages/browserslist-config/jest.config.js
  packages/browserslist-config/package.json
  packages/browserslist-config/tests/indexTest.js
  packages/components/CHANGELOG.MD
  packages/components/package.json
  packages/eslint/package.json
  packages/feature-flag/CHANGELOG.md
  packages/feature-flag/package.json
  packages/helpers/CHANGELOG.md
  packages/helpers/package.json
  packages/js/package.json
  packages/replacement-variable-editor/CHANGELOG.md
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/CHANGELOG.md
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/CHANGELOG.MD
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/CHANGELOG.md
  packages/social-metadata-previews/package.json
  packages/style-guide/CHANGELOG.md
  packages/style-guide/package.json
  packages/ui-library/package.json
  packages/yoastseo/CHANGELOG.md
  packages/yoastseo/package.json
Labels: changelog: non-user-facing, fix-before-release

#21463 Add website information to the script data in Elementor
  admin/metabox/class-metabox.php
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#21464 Replace icons with animated GIFs
  svn-assets/icon-128x128.gif
  svn-assets/icon-128x128.png
  svn-assets/icon-256x256.gif
  svn-assets/icon-256x256.png
  svn-assets/icon.svg
Labels: changelog: non-user-facing

#21457 Allows disabling AI buttons
  css/src/ai-fix-assessments.css
  packages/components/src/IconAIFixesButton.js
  packages/components/tests/__snapshots__/IconAIFixesButtonTest.js.snap
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
  packages/js/src/redux/actions/AIButton.js
  packages/js/src/redux/actions/activeAIButton.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/reducers/AIButton.js
  packages/js/src/redux/reducers/activeAIButton.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/selectors/AIButton.js
  packages/js/src/redux/selectors/activeAIButton.js
  packages/js/src/redux/selectors/index.js
  packages/js/tests/ai-assessment-fixes/components/AIAssessmentFixesButton.test.js
  packages/js/tests/redux/actions/AIButton.test.js
  packages/js/tests/redux/actions/activeAIButton.test.js
  packages/js/tests/redux/reducers/AIButton.test.js
  packages/js/tests/redux/reducers/activeAIButton.test.js
  packages/js/tests/redux/selectors/AIButton.test.js
  packages/js/tests/redux/selectors/activeAIButton.test.js
Labels: innovation, changelog: non-user-facing

#21471 Sets the WordPress tested up to version to 6.6
  readme.txt
  tests/Unit/bootstrap.php
  wp-seo-main.php
Labels: changelog: other

#21473 Update readme.txt
  readme.txt
Labels: changelog: non-user-facing

#21474 With AI activated, content analysis has slowed down for longer texts
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
Labels: changelog: non-user-facing

#21483 disable AI button when other ai button is pressed.
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
Labels: changelog: non-user-facing

#21486 Remove aria label required to have the flexibility not to use the tooltip
  packages/components/src/IconAIFixesButton.js
Labels: changelog: non-user-facing

#21484 Fix introduction gradient.
  css/src/introductions.css
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
Labels: changelog: other

#21485 Release `@yoast/analysis-report` and `@yoast/components` to NPM
  packages/analysis-report/CHANGELOG.MD
  packages/analysis-report/package.json
  packages/components/CHANGELOG.MD
  packages/components/package.json
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/package.json
Labels: changelog: non-user-facing

#21479 Improve storybook documentation toast element
  packages/ui-library/src/elements/toast/docs/complex-layout.md
  packages/ui-library/src/elements/toast/docs/component.md
  packages/ui-library/src/elements/toast/docs/index.js
  packages/ui-library/src/elements/toast/docs/use-toast-context.md
  packages/ui-library/src/elements/toast/index.js
  packages/ui-library/src/elements/toast/stories.js
  packages/ui-library/src/index.js
Labels: changelog: non-user-facing

#21495 Consider reimplementing lock icon for AI buttons
  packages/js/images/lock-closed.svg
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
Labels: changelog: non-user-facing

#21498 rename filter back.
  src/editors/framework/seo/posts/keyphrase-data-provider.php
Labels: changelog: bugfix, fix-before-release

#21492 Fix schema warning in potentialaction webpage property
  src/generators/schema/website.php
  tests/Unit/Generators/Schema/Website_Test.php
  tests/Unit/Generators/Schema_Generator_Test.php
Labels: changelog: enhancement

#21503 Hides AI buttons when the AI feature is disabled
  inc/class-wpseo-utils.php
  packages/js/package.json
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#21489 Keyphrase assessment fixes: Ensure good output when the user requests the exact match of the keyphrase
  packages/yoastseo/src/languageProcessing/helpers/index.js
Labels: changelog: non-user-facing

#21504 Deprecate concatenate scripts integration.
  composer.json
  config/dependency-injection/deprecated-classes.php
  src/deprecated/src/integrations/admin/disable-concatenate-scripts-integration.php
Labels: changelog: enhancement
