Repository Yoast/wordpress-seo, pull requests merged in 2024-11, with the labels that each got.

#21742 Call _load_textdomain_just_in_time correctly
  admin/class-admin-init.php
  admin/class-admin.php
  admin/filters/class-abstract-post-filter.php
  admin/metabox/class-metabox.php
  inc/class-post-type.php
  inc/class-rewrite.php
  inc/class-upgrade.php
  inc/class-wpseo-meta.php
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-options.php
  src/helpers/options-helper.php
  tests/Unit/Admin/Admin_Features_Test.php
  wp-seo-main.php
Labels: changelog: other

#21779 Change how we retrieve rule descriptions when generating the inclusive language database
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/createRuleDescriptionsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/InclusiveLanguageAssessment.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/createRuleDescriptions.js
Labels: changelog: non-user-facing, Shopify

#21720 Add target blank to server rendering of blocks.
  src/integrations/blocks/abstract-dynamic-block-v3.php
  src/presenters/breadcrumbs-presenter.php
  src/presenters/url-list-presenter.php
  tests/Unit/Presenters/Breadcrumbs_Presenter_Test.php
Labels: changelog: enhancement

#21708 Fix overstemming of non adjectives ending on -er in English
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/internal/determineStemSpec.js
  packages/yoastseo/spec/languageProcessing/languages/en/helpers/internal/getAdjectiveStemSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getProminentWordsForInternalLinkingSpec.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/countSyllables.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/determineStem.js
  packages/yoastseo/src/languageProcessing/languages/en/helpers/internal/getAdjectiveStem.js
Labels: changelog: enhancement, Shopify

#21697 283 add keyword difficulty and intent to semrush modal with table in tailwind design
  packages/related-keyphrase-suggestions/.browserslistrc
  packages/related-keyphrase-suggestions/.eslintignore
  packages/related-keyphrase-suggestions/.eslintrc.js
  packages/related-keyphrase-suggestions/.gitignore
  packages/related-keyphrase-suggestions/.storybook/interactive-docs-page.js
  packages/related-keyphrase-suggestions/.storybook/main.js
  packages/related-keyphrase-suggestions/.storybook/manager.js
  packages/related-keyphrase-suggestions/.storybook/preview.js
  packages/related-keyphrase-suggestions/.storybook/style.css
  packages/related-keyphrase-suggestions/.storybook/theme.js
  packages/related-keyphrase-suggestions/babel.config.js
  packages/related-keyphrase-suggestions/changelog.md
  packages/related-keyphrase-suggestions/package.json
  packages/related-keyphrase-suggestions/postcss.config.js
  packages/related-keyphrase-suggestions/readme.md
  packages/related-keyphrase-suggestions/scripts/build-css.js
  packages/related-keyphrase-suggestions/scripts/watch-css.js
  packages/related-keyphrase-suggestions/src/components/CountrySelector/docs/component.md
  packages/related-keyphrase-suggestions/src/components/CountrySelector/docs/index.js
  packages/related-keyphrase-suggestions/src/components/CountrySelector/index.js
  packages/related-keyphrase-suggestions/src/components/CountrySelector/stories.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/docs/component.md
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/docs/index.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/stories.js
  packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/docs/component.md
  packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/docs/index.js
  packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/index.js
  packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/stories.js
  packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/style.css
  packages/related-keyphrase-suggestions/src/elements/IntentBadge/docs/component.md
  packages/related-keyphrase-suggestions/src/elements/IntentBadge/docs/index.js
  packages/related-keyphrase-suggestions/src/elements/IntentBadge/index.js
  packages/related-keyphrase-suggestions/src/elements/IntentBadge/stories.js
  packages/related-keyphrase-suggestions/src/elements/IntentBadge/style.css
  packages/related-keyphrase-suggestions/src/elements/TableButton/docs/component.md
  packages/related-keyphrase-suggestions/src/elements/TableButton/docs/index.js
  packages/related-keyphrase-suggestions/src/elements/TableButton/index.js
  packages/related-keyphrase-suggestions/src/elements/TableButton/stories.js
  packages/related-keyphrase-suggestions/src/elements/TableButton/style.css
  packages/related-keyphrase-suggestions/src/elements/TrendGraph/TrendGraphScreenReader.js
  packages/related-keyphrase-suggestions/src/elements/TrendGraph/docs/component.md
  packages/related-keyphrase-suggestions/src/elements/TrendGraph/docs/index.js
  packages/related-keyphrase-suggestions/src/elements/TrendGraph/index.js
  packages/related-keyphrase-suggestions/src/elements/TrendGraph/stories.js
  packages/related-keyphrase-suggestions/src/index.js
  packages/related-keyphrase-suggestions/tailwind.config.js
  yarn.lock
Labels: changelog: non-user-facing

#21766 New general page: fix routing issue and add error fallback
  packages/js/src/components/metabox-error-fallback.js
  packages/js/src/components/sidebar-error-fallback.js
  packages/js/src/elementor/components/elementor-error-fallback.js
  packages/js/src/general/app.js
  packages/js/src/general/components/index.js
  packages/js/src/general/components/notice.js
  packages/js/src/general/components/route-error-fallback.js
  packages/js/src/general/components/route-layout.js
  packages/js/src/general/components/sidebar-recommendations.js
  packages/js/src/general/initialize.js
  packages/js/src/general/routes/alert-center.js
  packages/js/src/general/routes/first-time-configuration.js
  packages/js/src/general/routes/index.js
  packages/js/src/settings/app.js
  packages/js/src/settings/components/error-fallback.js
  packages/js/src/settings/components/index.js
  packages/js/src/shared-admin/components/error-fallback.js
  packages/js/src/shared-admin/components/index.js
  packages/js/src/shared-admin/components/sidebar-recommendations.js
  packages/js/src/support/app.js
  packages/js/tests/__mocks__/react-router-dom.js
  packages/js/tests/general/components/route-error-fallback.test.js
  packages/js/tests/settings/search.test.js
  packages/js/tests/shared-admin/components/error-fallback.test.js
Labels: UI change, changelog: bugfix

#21789 Fix ftc first step shown again
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/first-time-configuration/tailwind-components/configuration-stepper-buttons.js
Labels: changelog: bugfix

#21798 implementation of the related keyphrase suggestions package
  css/src/modal.css
  css/src/tailwind.css
  package.json
  packages/js/.eslintrc.js
  packages/js/package.json
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/js/src/containers/SEMrushRelatedKeyphrases.js
  packages/js/src/redux/reducers/preferences.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
  packages/related-keyphrase-suggestions/src/elements/DifficultyBullet/index.js
  packages/ui-library/.storybook/style.css
  packages/ui-library/src/elements/table/index.js
  packages/ui-library/src/elements/table/style.css
  tailwind.config.js
Labels: UI change, changelog: enhancement

#21794 21712 add more portuguese transition words
  packages/yoastseo/src/languageProcessing/languages/en/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/pt/config/transitionWords.js
Labels: changelog: enhancement, Shopify

#21788 Improve the way that lists used for disability assessment rules are created
  packages/yoastseo/src/languageProcessing/languages/en/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/internal/passiveVoiceAuxiliaries.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityRulesData.js
Labels: changelog: non-user-facing, Shopify

#21793 Hide Local notice when site representation is completed via the FTC
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/src/general/app.js
  packages/js/src/general/initialize.js
  packages/js/src/general/store/first-time-configuration.js
  packages/js/src/general/store/index.js
Labels: changelog: non-user-facing

#21800 Update English morphology data version
  apps/content-analysis-api/index.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#21792 Remove some unneeded FTC and general page code.
  admin/menu/class-menu.php
  admin/pages/dashboard.php
  config/webpack/paths.js
  packages/js/src/first-time-configuration.js
  packages/js/src/first-time-configuration/first-time-configuration-app-container.js
  src/integrations/admin/first-time-configuration-integration.php
  tests/WP/bootstrap.php
Labels: changelog: non-user-facing

#21804 fix isRtl preference
  packages/js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#21809 restore the add more insights link
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
Labels: changelog: non-user-facing

#21812 21811 hide semrush loading table when user needs to upgrade
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
Labels: changelog: non-user-facing

#21739 Fix wrong type in docs
  admin/tracking/class-tracking.php
  inc/options/class-wpseo-option-wpseo.php
Labels: community-patch, changelog: non-user-facing

#21814 Add post type and taxonomy filters in the script data
  src/dash/application/content-types/content-types-repository.php
  src/dash/application/filter-pairs/filter-pairs-repository.php
  src/dash/application/taxonomies/taxonomies-repository.php
  src/dash/domain/content-types/content-type.php
  src/dash/domain/content-types/content-types-list.php
  src/dash/domain/filter-pairs/filter-pairs-interface.php
  src/dash/domain/filter-pairs/product-category-filter-pair.php
  src/dash/domain/taxonomies/taxonomy.php
  src/dash/infrastructure/taxonomies/taxonomies-collector.php
  src/dash/infrastructure/taxonomies/taxonomy-validator.php
  src/general/user-interface/general-page-integration.php
  tests/Unit/General/User_Interface/General_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21816 474 prepare ai optimize for readability assessments
  packages/js/src/components/contentAnalysis/ReadabilityAnalysis.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
Labels: changelog: enhancement, changelog: other

#21825 Add dashboard configuration object.
  packages/js/src/general/initialize.js
  src/dashboard/application/configuration/dashboard-configuration.php
  src/editors/application/analysis-features/enabled-analysis-features-repository.php
  src/editors/domain/analysis-features/analysis-features-list.php
  src/editors/framework/cornerstone-content.php
  src/editors/framework/inclusive-language-analysis.php
  src/editors/framework/keyphrase-analysis.php
  src/editors/framework/previously-used-keyphrase.php
  src/editors/framework/readability-analysis.php
  src/editors/framework/word-form-recognition.php
  src/general/user-interface/general-page-integration.php
  src/helpers/user-helper.php
  tests/Unit/Editors/Domain/Analysis_Features/Analysis_Features_List_Test.php
  tests/Unit/General/User_Interface/General_Page_Integration_Test.php
  tests/Unit/Helpers/User_Helper_Test.php
Labels: changelog: non-user-facing

#21838 Dashboard: implement descriptions scores
  packages/js/src/dashboard/hooks/use-fetch.js
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/scores/components/content-status-description.js
  packages/js/src/dashboard/scores/components/score-content.js
  packages/js/src/dashboard/scores/components/score-list.js
  packages/js/src/dashboard/scores/readability/readability-scores.js
  packages/js/src/dashboard/scores/score-meta.js
  packages/js/src/dashboard/scores/seo/seo-scores.js
Labels: changelog: non-user-facing

#21805 Change search volume format
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/js/src/redux/reducers/preferences.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/stories.js
Labels: UI change, changelog: enhancement

#21840 Dashboard: clear category in case another post type was selected
  packages/js/src/dashboard/scores/components/term-filter.js
  packages/js/src/dashboard/scores/seo/seo-scores.js
Labels: changelog: non-user-facing

#21817 add premium upsell component
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/docs/component.md
  packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/docs/index.js
  packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/index.js
  packages/related-keyphrase-suggestions/src/elements/PremiumUpsell/stories.js
  packages/related-keyphrase-suggestions/src/index.js
Labels: UI change, changelog: non-user-facing

#21826 fix add keyphrase direction and width and loading table storybook
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/index.js
  packages/related-keyphrase-suggestions/src/components/KeyphrasesTable/stories.js
Labels: changelog: non-user-facing

#21815 324 tailwindify the errors and notices in the related keyphrase suggestions modal
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/js/src/containers/SEMrushRelatedKeyphrases.js
  packages/js/tests/components/SEMrushRelatedKeyphrasesModalContent.test.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/components/MaxRelatedKeyphrases.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestEmpty.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestFailed.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/components/RequestLimitReached.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/components/index.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/docs/component.md
  packages/related-keyphrase-suggestions/src/elements/UserMessage/docs/index.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/index.js
  packages/related-keyphrase-suggestions/src/elements/UserMessage/stories.js
  packages/related-keyphrase-suggestions/src/index.js
Labels: UI change, changelog: enhancement

#21807 analysis-worker.js consumes memory until the browser tab crashes on a Hebrew site.
  packages/yoastseo/src/languageProcessing/researches/findKeyphraseInSEOTitle.js
Labels: changelog: non-user-facing, Shopify

#21860 Dashboard: UX feedback
  packages/js/src/dashboard/scores/components/score-chart.js
  packages/js/src/dashboard/scores/components/score-content.js
  packages/js/src/dashboard/scores/components/score-list.js
  packages/js/src/general/app.js
Labels: changelog: non-user-facing

#21855 Add micro caching around the score queries
  src/dashboard/infrastructure/scores/readability-scores/readability-scores-collector.php
  src/dashboard/infrastructure/scores/seo-scores/seo-scores-collector.php
  src/dashboard/infrastructure/taxonomies/taxonomies-collector.php
Labels: changelog: non-user-facing

#21849 21848 decouple posts overview script enqueuing from class metaboxphp
  admin/class-meta-columns.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  css/src/edit-page.css
Labels: changelog: non-user-facing

#21862 Dashboard: move to final copy
  packages/js/src/dashboard/components/dashboard.js
  packages/js/src/dashboard/components/page-title.js
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/scores/score-meta.js
  packages/js/src/general/initialize.js
Labels: changelog: non-user-facing

#21846 fix adjacent_rel_url and tests
  src/integrations/front-end-integration.php
  tests/WP/Frontend/Front_End_Integration_Test.php
Labels: changelog: bugfix

#21763 Fix l10n import/export tool buttons actions
  admin/views/tool-import-export.php
Labels: community-patch, changelog: bugfix

#21856 1935 wp 67 238 undefined console error for iframe
  admin/class-admin-asset-manager.php
  css/src/block-editor.css
  css/src/metabox.css
  src/integrations/blocks/block-editor-integration.php
  tests/Unit/Integrations/Blocks/Block_Editor_Integration_Test.php
Labels: changelog: non-user-facing

#21821 323 fix design of links in the related keyphrase suggestions modal semrush
  packages/js/src/components/SEMrushRelatedKeyphrasesModal.js
  packages/js/src/components/SEMrushRelatedKeyphrasesModalContent.js
  packages/js/src/components/modals/SEMrushCountrySelector.js
  packages/js/src/containers/SEMrushRelatedKeyphrasesModal.js
  packages/related-keyphrase-suggestions/.storybook/style.css
  packages/related-keyphrase-suggestions/src/components/CountrySelector/index.js
  packages/related-keyphrase-suggestions/src/components/Modal/YoastIcon.js
  packages/related-keyphrase-suggestions/src/components/Modal/docs/component.md
  packages/related-keyphrase-suggestions/src/components/Modal/docs/index.js
  packages/related-keyphrase-suggestions/src/components/Modal/index.js
  packages/related-keyphrase-suggestions/src/components/Modal/stories.js
  packages/related-keyphrase-suggestions/src/components/Modal/style.css
  packages/related-keyphrase-suggestions/src/index.js
Labels: UI change, changelog: non-user-facing

#21863 Make score endpoints work in plain permalinks
  packages/js/src/dashboard/scores/components/scores.js
  packages/js/src/dashboard/scores/components/term-filter.js
Labels: changelog: non-user-facing

#21834 Adds ability to also select Readability: Not Analyzed as option.
  admin/class-meta-columns.php
  composer.json
  inc/class-wpseo-rank.php
  tests/WP/Admin/Meta_Columns_Test.php
  tests/WP/Inc/Rank_Test.php
Labels: changelog: enhancement

#21868 Use `get_indexable_post_type_objects` instead of `get_indexable_post_…
  src/dashboard/infrastructure/content-types/content-types-collector.php
Labels: changelog: non-user-facing

#21874 Fix integration tests when black friday sale is on
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: changelog: non-user-facing

#21864 Return 500 error code when query fails
  src/dashboard/application/score-results/abstract-score-results-repository.php
  src/dashboard/domain/score-results/score-results-not-found-exception.php
  src/dashboard/infrastructure/score-results/readability-score-results/readability-score-results-collector.php
  src/dashboard/infrastructure/score-results/seo-score-results/seo-score-results-collector.php
  src/dashboard/user-interface/scores/abstract-scores-route.php
Labels: changelog: non-user-facing

#21876 Add draft yoastseo package overview
  packages/yoastseo/GLOSSARY.md
  packages/yoastseo/OVERVIEW.md
Labels: changelog: non-user-facing
