Repository Yoast/wordpress-seo, pull requests merged in 2024-02, with the labels that each got.

#21104 Update tests to not rely on the DI instance of the `Meta_Tags_Context_Memoizer`
  tests/WP/Generators/Schema/Person_Test.php
  tests/WP/Generators/Schema/WebPage_Test.php
Labels: changelog: non-user-facing

#21114 Removed Spanish from the support languages on Yoast SEO > Support page
  packages/js/src/support/app.js
Labels: UI change, changelog: non-user-facing

#21094 Update the sidebar Ad.
  css/src/yst_plugin_tools.css
  packages/js/src/shared-admin/components/premium-upsell-card.js
  src/presenters/admin/sidebar-presenter.php
Labels: UI change, changelog: other

#21119 Ensure disabled and read-only textareas apply this state
  packages/ui-library/src/components/textarea-field/index.js
Labels: changelog: bugfix

#21118 21105 sitemapxml not redirecting when serverhttps returns on instead of on
  composer.json
  inc/sitemaps/class-sitemaps-router.php
  tests/WP/Sitemaps/Router_Test.php
Labels: changelog: bugfix

#21127 Add main entity of page link to org node if on the profilepage schema…
  src/generators/schema/organization.php
  tests/WP/Generators/Schema/Organization_Test.php
Labels: changelog: non-user-facing

#21129 21120 number of employees can be focussed while disabled
  packages/js/src/settings/components/formik-autocomplete-field.js
  packages/js/src/settings/components/formik-page-select-field.js
  packages/ui-library/src/elements/autocomplete/index.js
Labels: changelog: non-user-facing

#21132 Add "x.com" as possible domain for the Twitter validation
  inc/options/class-wpseo-option-social.php
  packages/js/src/settings/helpers/validation.js
  tests/WP/Inc/Options/Option_Social_Test.php
Labels: changelog: bugfix

#21122 Add reference to primary image in posts schema generated by a REST request
  src/context/meta-tags-context.php
  tests/Unit/Context/Meta_Tags_Context_Test.php
Labels: changelog: bugfix

#21138 Update ad text
  packages/js/src/shared-admin/components/premium-upsell-card.js
  src/presenters/admin/sidebar-presenter.php
Labels: changelog: non-user-facing

#21142 Empty rewrite rules on (de)activation instead of flushing them
  wp-seo-main.php
Labels: changelog: bugfix, fix-before-release

#21151 Merges the feature branch feature/inclusive-language-fixes to trunk
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/ageAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/cultureAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/otherAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/sesAssessmentsSpec.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigs.test.js
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isPrecededByExceptionSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesConsecutiveWords.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/includesWordsAtPosition.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedByParticiple.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isPrecededByException.js
Labels: changelog: enhancement, Shopify

#21143 Adds our SEO group to the WC layout templates
  src/woocommerce-editor/user-interface/woocommerce-editor-seo-group.php
  tests/Unit/WooCommerce_Editor/User_Interface/WooCommerce_Editor_SEO_Group_Test.php
Labels: changelog: non-user-facing

#21159 WC Editor: add Yoast SEO block
  .gitignore
  config/grunt/task-config/copy.js
  config/webpack/paths.js
  config/webpack/webpack.config.base.js
  config/webpack/webpack.config.js
  packages/js/.eslintrc.js
  packages/js/src/woocommerce-editor/blocks/seo/block.json
  packages/js/src/woocommerce-editor/blocks/seo/edit.js
  packages/js/src/woocommerce-editor/blocks/seo/index.js
  packages/js/src/woocommerce-editor/components/seo-slot-fill.js
  packages/js/tests/__mocks__/@woocommerce/block-templates.js
  packages/js/tests/woocommerce-editor/blocks/seo/__snapshots__/edit.test.js.snap
  packages/js/tests/woocommerce-editor/blocks/seo/edit.test.js
  packages/js/tests/woocommerce-editor/components/__snapshots__/seo-slot-fill.test.js.snap
  packages/js/tests/woocommerce-editor/components/seo-slot-fill.test.js
  src/conditionals/conditional-interface.php
  src/loadable-interface.php
  src/woocommerce-editor/framework/woocommerce-product-block-editor-conditional.php
  src/woocommerce-editor/user-interface/woocommerce-editor-seo-block.php
  tests/Unit/WooCommerce_Editor/Framework/WooCommerce_Product_Block_Editor_Conditional_Test.php
  tests/Unit/WooCommerce_Editor/User_Interface/WooCommerce_Editor_SEO_Block_Test.php
Labels: changelog: non-user-facing

#21168 Make sure image is null when it is '' so that the schema generator does not create an empty record.
  src/context/meta-tags-context.php
Labels: changelog: non-user-facing

#21173 Add slate background to Storybook
  packages/ui-library/.storybook/preview.js
  packages/ui-library/src/elements/autocomplete/style.css
  packages/ui-library/src/elements/skeleton-loader/stories.js
Labels: changelog: bugfix

#21176 Version increase
  package.json
  packages/analysis-report/package.json
  packages/babel-preset/changelog.md
  packages/babel-preset/package.json
  packages/js/package.json
  packages/ui-library/changelog.md
  packages/ui-library/package.json
Labels: changelog: non-user-facing

#21170 Adds exception to the breadcrumb generator that ignores ancestor on the homepage.
  composer.json
  src/generators/breadcrumbs-generator.php
  tests/Unit/Generators/Breadcrumbs_Generator_Test.php
Labels: changelog: enhancement

#21187 1404 minor organizations founding date field looks broken in new chrome version
  packages/js/src/settings/routes/site-representation.js
  packages/ui-library/src/elements/text-input/index.js
  packages/ui-library/src/elements/text-input/stories.js
  packages/ui-library/src/elements/text-input/style.css
Labels: UI change, changelog: bugfix
