Repository Yoast/wordpress-seo, pull requests merged in 2024-09, with the labels that each got.

#21391 Add an integration to check the `Requires Yoast SEO` header.
  src/conditionals/check-required-version-conditional.php
  src/initializers/plugin-headers.php
  src/integrations/admin/check-required-version.php
Labels: changelog: non-user-facing

#21587 Elementor: stop editor watcher when switching the document
  packages/js/src/elementor/initializers/editor-watcher.js
Labels: changelog: non-user-facing

#21581 Improve disabled state of UI library field components
  packages/ui-library/src/components/autocomplete-field/index.js
  packages/ui-library/src/components/autocomplete-field/style.css
  packages/ui-library/src/components/tag-field/style.css
  packages/ui-library/src/components/toggle-field/style.css
Labels: UI change, changelog: bugfix

#21589 21588 remove woocommerceupsell from wpseoscriptdata
  admin/metabox/class-metabox.php
  packages/js/src/components/SchemaTab.js
  packages/js/src/containers/SnippetEditor.js
  packages/js/src/redux/selectors/editorContext.js
  packages/js/src/redux/selectors/isWooSEO.js
Labels: changelog: non-user-facing

#21592 21575 remove outdated properties in wpseo meta for translations
  admin/metabox/class-metabox.php
  inc/class-wpseo-meta.php
Labels: changelog: non-user-facing

#21590 Fixes "something went wrong" error when removing image caption
  packages/js/src/decorator/helpers/getAnnotationsHelpers.js
Labels: changelog: bugfix

#21601 Updates BF banners and sets the correct date.
  admin/class-premium-upsell-admin-block.php
  admin/menu/class-base-menu.php
  admin/views/licenses.php
  css/src/admin-global.css
  css/src/adminbar.css
  inc/class-wpseo-admin-bar-menu.php
  packages/js/src/components/BlackFridayPromotion.js
  packages/js/src/components/UpsellBox.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/helpers/shouldShowWebinarPromotionNotification.js
  packages/js/src/hooks/use-first-eligible-notification.js
  packages/js/src/settings/app.js
  packages/js/src/shared-admin/components/premium-upsell-card.js
  src/integrations/alerts/black-friday-promotion-notification.php
  src/integrations/settings-integration.php
  src/integrations/support-integration.php
  src/presenters/admin/sidebar-presenter.php
  src/promotions/domain/black-friday-promotion.php
  tests/Unit/Integrations/Support_Integration_Test.php
Labels: changelog: other

#21599 Adds pretest to the postinstall to ensure the Premium configuration is fetched
  apps/README.md
  apps/content-analysis-api/package.json
  apps/content-analysis-api/yarn.lock
Labels: changelog: non-user-facing

#21606 Initial new dashboard page
  admin/class-admin-asset-manager.php
  config/webpack/paths.js
  packages/js/src/dashboard/app.js
  packages/js/src/dashboard/constants/index.js
  packages/js/src/dashboard/initialize.js
  packages/js/src/dashboard/store/index.js
  packages/js/src/dashboard/store/preferences.js
  src/conditionals/new-dashboard-ui-conditional.php
  src/dashboard/user-interface/new-dashboard-page-integration.php
  tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21598 21597 refactor iswoocommerceactive
  admin/class-config.php
  admin/metabox/class-metabox.php
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/helpers/isWooCommerceActive.js
  packages/js/src/redux/selectors/isWooSEO.js
  src/editors/framework/integrations/multilingual.php
  src/editors/framework/integrations/woocommerce.php
  src/integrations/third-party/elementor.php
  tests/Unit/Editors/Framework/Integrations/WooCommerce_Test.php
Labels: changelog: non-user-facing

#21613 21610 deprecate and remove jetpack boost ad code
  admin/metabox/class-metabox.php
  composer.json
  packages/js/images/jetpack-boost-integration-logo.svg
  packages/js/images/jetpack-boost-logo.svg
  packages/js/images/yoast-seo-simple-logo.svg
  packages/js/src/components/JetpackBoost.js
  packages/js/src/integrations-page/jetpack-boost-integration.js
  src/conditionals/third-party/jetpack-boost-active-conditional.php
  src/conditionals/third-party/jetpack-boost-not-premium-conditional.php
  src/integrations/admin/integrations-page.php
  src/integrations/alerts/jetpack-boost-pre-publish.php
  tests/Unit/Integrations/Admin/Integrations_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21615 Implement useAnchor
  packages/js/package.json
  packages/js/src/inline-links/edit-link.js
  packages/js/src/inline-links/inline.js
  yarn.lock
Labels: changelog: bugfix

#21614 493 add navigation sidebar with alert center and first time configuration links
  admin/class-config.php
  css/src/first-time-configuration.css
  css/src/new-dashboard.css
  packages/js/src/dashboard/app.js
  packages/js/src/dashboard/components/index.js
  packages/js/src/dashboard/components/route-layout.js
  packages/js/src/dashboard/hooks/index.js
  packages/js/src/dashboard/hooks/use-select-dashboard.js
  packages/js/src/dashboard/initialize.js
  packages/js/src/settings/app.js
  packages/js/src/settings/components/index.js
  packages/js/src/shared-admin/components/index.js
  packages/js/src/shared-admin/components/menu-item-link.js
  packages/js/src/shared-admin/components/yoast-logo.svg
  packages/ui-library/src/components/sidebar-navigation/stories.js
  packages/ui-library/src/components/sidebar-navigation/submenu-item.js
  src/integrations/admin/first-time-configuration-integration.php
Labels: changelog: non-user-facing

#21620 21619 refactor is news seo active
  inc/class-wpseo-utils.php
  packages/js/src/redux/reducers/preferences.js
  src/editors/framework/integrations/news-seo.php
  tests/Unit/Editors/Framework/Integrations/News_SEO_Test.php
Labels: changelog: non-user-facing

#21617 21609 refactor iswoocommerceseoactive and iswooseo store
  admin/metabox/class-metabox.php
  packages/js/src/redux/reducers/preferences.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/redux/selectors/isWooSEO.js
  packages/js/src/redux/selectors/preferences.js
  src/editors/framework/integrations/woocommerce-seo.php
  tests/Unit/Editors/Framework/Integrations/WooCommerce_SEO_Test.php
Labels: changelog: non-user-facing

#21534 19849 og image tags are not showing the biggest available image when a resized version is used in the content
  composer.json
  inc/class-wpseo-content-images.php
  src/builders/indexable-link-builder.php
  src/helpers/image-helper.php
  src/images/Application/image-content-extractor.php
  tests/Unit/Builders/Indexable_Link_Builder/Abstract_Indexable_Link_Builder_TestCase.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Create_Internal_Link_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Get_Permalink_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Update_Incoming_Links_For_Related_Test.php
  tests/Unit/Builders/Indexable_Post_Builder_Test.php
  tests/Unit/Images/Application/Image_Content_Extractor_Test.php
  tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php
Labels: changelog: enhancement

#21634 Fix SelectControl deprecation warning
  packages/js/src/components/PrimaryTaxonomyPicker.js
  packages/js/src/components/TaxonomyPicker.js
Labels: changelog: non-user-facing

#21629 21628 refactor isprivateblog preference
  inc/class-wpseo-utils.php
  packages/js/src/redux/reducers/preferences.js
  src/editors/framework/site/base-site-information.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: changelog: non-user-facing

#21627 cleanup: remove outdated userLanguage property
  admin/class-config.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#21633 21632 refactor is ai feature active property
  inc/class-wpseo-utils.php
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/src/redux/reducers/preferences.js
Labels: changelog: non-user-facing

#21631 21630 refactor sitewide social image preference
  admin/formatter/class-metabox-formatter.php
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/initializers/editor-store.js
  src/editors/framework/site/base-site-information.php
  src/editors/framework/site/post-site-information.php
  src/editors/framework/site/term-site-information.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: changelog: non-user-facing

#21639 21638 refactor showsocial property
  admin/formatter/class-metabox-formatter.php
  src/editors/framework/site/base-site-information.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: changelog: non-user-facing

#21623 Extract FTC stept to own component to be reused in new dashboard.
  packages/js/src/dashboard/app.js
  packages/js/src/dashboard/components/route-layout.js
  packages/js/src/dashboard/routes/first-time-configuration.js
  packages/js/src/dashboard/routes/index.js
  packages/js/src/first-time-configuration.js
  packages/js/src/first-time-configuration/first-time-configuration-app-container.js
  packages/js/src/first-time-configuration/first-time-configuration-steps.js
  packages/js/tests/dashboard/components/__snapshots__/route-layout.test.js.snap
  packages/js/tests/dashboard/components/route-layout.test.js
Labels: changelog: non-user-facing

#21642 feat: added paper inside the components
  packages/js/src/dashboard/app.js
  packages/js/src/dashboard/components/index.js
  packages/js/src/dashboard/components/notifications.js
  packages/js/src/dashboard/components/problems.js
  packages/js/src/dashboard/routes/alert-center.js
  packages/js/src/dashboard/routes/first-time-configuration.js
  packages/js/src/dashboard/routes/index.js
Labels: changelog: enhancement

#21325 Transforms prototype-based classes to regular class syntax
  packages/yoastseo/spec/appSpec.js
  packages/yoastseo/spec/languageProcessing/values/ClauseSpec.js
  packages/yoastseo/spec/languageProcessing/values/SentenceSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SubheadingDistributionTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessors/storePostsAndPages/cornerstone/contentAssessorSpec.js
  packages/yoastseo/src/app.js
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
  packages/yoastseo/src/errors/invalidType.js
  packages/yoastseo/src/errors/missingArgument.js
  packages/yoastseo/src/helpers/factory.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/buildTopicStems.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/DeviationFragment.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/syllableCountIterator.js
  packages/yoastseo/src/languageProcessing/helpers/syllables/syllableCountStep.js
  packages/yoastseo/src/languageProcessing/values/Clause.js
  packages/yoastseo/src/languageProcessing/values/ProminentWord.js
  packages/yoastseo/src/languageProcessing/values/Sentence.js
  packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
  packages/yoastseo/src/scoring/assessors/assessor.js
  packages/yoastseo/src/scoring/assessors/collectionPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/collectionPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/contentAssessor.js
  packages/yoastseo/src/scoring/assessors/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/assessors/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/inclusiveLanguageAssessor.js
  packages/yoastseo/src/scoring/assessors/productPages/contentAssessor.js
  packages/yoastseo/src/scoring/assessors/productPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/assessors/productPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/productPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/productPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/productPages/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/relatedKeywordTaxonomyAssessor.js
  packages/yoastseo/src/scoring/assessors/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/storeBlog/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/storeBlog/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/storePostsAndPages/contentAssessor.js
  packages/yoastseo/src/scoring/assessors/storePostsAndPages/cornerstone/contentAssessor.js
  packages/yoastseo/src/scoring/assessors/storePostsAndPages/cornerstone/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/storePostsAndPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/storePostsAndPages/relatedKeywordAssessor.js
  packages/yoastseo/src/scoring/assessors/storePostsAndPages/seoAssessor.js
  packages/yoastseo/src/scoring/assessors/taxonomyAssessor.js
  packages/yoastseo/src/scoring/renderers/AssessorPresenter.js
  packages/yoastseo/src/values/AssessmentResult.js
  packages/yoastseo/src/values/Mark.js
  packages/yoastseo/src/values/Paper.js
  packages/yoastseo/src/worker/transporter/parse.js
Labels: innovation, changelog: non-user-facing, Shopify

#21641 Make new dashboard page the root of the Yoast SEO menu
  admin/menu/class-admin-menu.php
  css/src/new-dashboard.css
  src/dashboard/user-interface/new-dashboard-page-integration.php
  tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21647 275 preprare backend to hook problems and notifications into alert center front end
  admin/class-config.php
  src/dashboard/user-interface/new-dashboard-page-integration.php
  src/helpers/notification-helper.php
  tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21650 Fix not loading config_page scripts
  admin/class-config.php
Labels: changelog: non-user-facing

#21646 271 add problem and notification components to alert center
  packages/js/src/dashboard/components/alert-title.js
  packages/js/src/dashboard/components/alerts-list.js
  packages/js/src/dashboard/components/collapsible.js
  packages/js/src/dashboard/components/index.js
  packages/js/src/dashboard/components/notifications.js
  packages/js/src/dashboard/components/problems.js
  packages/js/src/dashboard/contexts/alerts-context.js
  packages/js/src/dashboard/routes/alert-center.js
Labels: changelog: non-user-facing

#21616 Extends Transition words list for Turkish after user feedback
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/languageProcessing/researches/findTransitionWordsSpec.js
  packages/yoastseo/spec/scoring/assessors/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/src/languageProcessing/languages/en/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/en/config/twoPartTransitionWords.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/tr/config/twoPartTransitionWords.js
Labels: changelog: enhancement, Shopify

#21062 Fix fatal error when other plugin runs exit() on plugins_loaded hook.
  admin/class-yoast-notification-center.php
Labels: community-patch, changelog: bugfix

#21649 Adds alert center redux store
  admin/class-yoast-notification.php
  packages/js/src/dashboard/components/alerts-list.js
  packages/js/src/dashboard/components/alerts-title.js
  packages/js/src/dashboard/components/index.js
  packages/js/src/dashboard/components/notifications.js
  packages/js/src/dashboard/components/problems.js
  packages/js/src/dashboard/initialize.js
  packages/js/src/dashboard/store/alert-center.js
  packages/js/src/dashboard/store/index.js
  packages/js/src/dashboard/store/preferences.js
  packages/js/tests/dashboard/components/__snapshots__/alerts-list.test.js.snap
  packages/js/tests/dashboard/components/__snapshots__/alerts-title.test.js.snap
  packages/js/tests/dashboard/components/__snapshots__/notifications.test.js.snap
  packages/js/tests/dashboard/components/__snapshots__/problems.test.js.snap
  packages/js/tests/dashboard/components/alerts-list.test.js
  packages/js/tests/dashboard/components/alerts-title.test.js
  packages/js/tests/dashboard/components/collapsible.test.js
  packages/js/tests/dashboard/components/notifications.test.js
  packages/js/tests/dashboard/components/problems.test.js
  packages/js/tests/dashboard/store/alert-center.test.js
  src/dashboard/user-interface/new-dashboard-page-integration.php
  src/helpers/notification-helper.php
  tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21658 21657 the buttons displayed in the notifications can get a secondary small styling
  css/src/new-dashboard.css
Labels: changelog: non-user-facing

#21645 273 add bottom upsell and upsell sidebar
  packages/js/src/dashboard/components/sidebar-recommendations.js
  packages/js/src/dashboard/routes/alert-center.js
  packages/js/src/settings/app.js
  packages/js/src/shared-admin/components/premium-upsell-list.js
  tests/Unit/Dashboard/User_Interface/New_Dashboard_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21659 refactor: restore the ignore_search_engines_discouraged_notice option
  composer.json
  src/integrations/watchers/search-engines-discouraged-watcher.php
  tests/Unit/Integrations/Watchers/Search_Engines_Discouraged_Watcher_Test.php
Labels: changelog: other

#21660 refactor: adjust button shaped as link to match the styling of the ui…
  css/src/new-dashboard.css
Labels: changelog: non-user-facing

#21667 fix: move promotion properties to site base info
  src/editors/framework/site/base-site-information.php
  src/editors/framework/site/post-site-information.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: changelog: non-user-facing

#21624 "Keyphrase in slug" assessment won't ever make sense on a static home…
  admin/metabox/class-metabox.php
  packages/js/src/analysis/collectAnalysisData.js
  packages/js/src/initializers/analysis.js
  packages/js/src/redux/reducers/editorContext.js
  packages/js/src/redux/selectors/editorContext.js
  packages/yoastseo/spec/scoring/assessments/seo/UrlKeywordAssessmentSpec.js
  packages/yoastseo/spec/worker/transporter/serializeSpec.js
  packages/yoastseo/src/scoring/assessments/seo/UrlKeywordAssessment.js
  packages/yoastseo/src/values/Paper.js
  src/integrations/third-party/elementor.php
Labels: changelog: enhancement
