Repository Yoast/wordpress-seo, pull requests merged in 2024-04, with the labels that each got.

#21197 Tooltip improvements
  packages/ui-library/src/elements/tooltip/docs/badgeShowsATooltipOnHover.md
  packages/ui-library/src/elements/tooltip/docs/component.md
  packages/ui-library/src/elements/tooltip/docs/index.js
  packages/ui-library/src/elements/tooltip/index.js
  packages/ui-library/src/elements/tooltip/stories.js
  packages/ui-library/src/elements/tooltip/style.css
Labels: changelog: enhancement

#21259 Adjust text length criteria for taxonomies
  packages/yoastseo/spec/scoring/assessments/seo/TextLengthAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/taxonomyTextLengthSpec.js
  packages/yoastseo/spec/scoring/collectionPages/cornerstone/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/collectionPages/seoAssessorSpec.js
  packages/yoastseo/spec/scoring/taxonomyAssessorSpec.js
  packages/yoastseo/src/languageProcessing/languages/ja/config/textLength.js
  packages/yoastseo/src/scoring/assessments/SCORING TAXONOMY.md
  packages/yoastseo/src/scoring/assessments/seo/TextLengthAssessment.js
  packages/yoastseo/src/scoring/collectionPages/cornerstone/seoAssessor.js
  packages/yoastseo/src/scoring/collectionPages/seoAssessor.js
  packages/yoastseo/src/scoring/taxonomyAssessor.js
Labels: changelog: enhancement, Shopify

#21291 Add ai course page for the academy
  images/academy/ai_for_seo_icon_my_yoast.png
  packages/js/src/academy/app.js
Labels: changelog: enhancement

#21296 Decrease threshold for PHPCS errors
  composer.json
Labels: changelog: non-user-facing

#21299 Composer: update dev dependencies + minor CS fixes
  .github/workflows/cs.yml
  .phpcs.xml.dist
  admin/class-plugin-availability.php
  composer.json
  composer.lock
  config/composer/actions.php
  inc/class-addon-manager.php
  inc/class-upgrade.php
  inc/class-wpseo-admin-bar-menu.php
  inc/options/class-wpseo-option-titles.php
  inc/sitemaps/class-sitemaps-cache-validator.php
  src/editors/application/analysis-features/enabled-analysis-features-repository.php
  src/editors/domain/analysis-features/analysis-feature.php
  src/editors/domain/analysis-features/analysis-features-list.php
  src/generators/breadcrumbs-generator.php
  src/helpers/schema/html-helper.php
  src/helpers/url-helper.php
  src/integrations/front-end/crawl-cleanup-rss.php
  src/values/twitter/images.php
  tests/Unit/Admin/Suggested_Plugins_Construct_Test.php
  tests/Unit/Doubles/Integrations/Settings_Integration_Double.php
  tests/WP/Admin/Watchers/Indexable_Ancestor_Watcher_Test.php
  tests/WP/Inc/Upgrade_Test.php
  tests/WP/Sitemaps/Post_Type_Sitemap_Provider_Test.php
  tests/WP/Sitemaps/Renderer_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#21297 Take into account future changes to WordPress options autoload.
  inc/class-upgrade.php
  tests/WP/Inc/Upgrade_Test.php
Labels: changelog: non-user-facing

#21169 Introduce form patterns in Storybook
  packages/ui-library/src/components/autocomplete-field/index.js
  packages/ui-library/src/patterns/forms.stories.mdx
  packages/ui-library/tailwind.config.js
Labels: changelog: non-user-facing

#21301 Use different snippet editor wrappers in Elementor and block editor
  packages/js/src/components/modals/editorModals/SearchAppearanceModal.js
Labels: changelog: bugfix

#21302 WC editor: create initial Yoast editor integration in JS
  packages/js/src/initializers/analysis.js
  packages/js/src/initializers/pluggable.js
  packages/js/src/woocommerce-editor/initialize.js
Labels: changelog: non-user-facing

#21014 Use WHIP to deprecate PHP 7.2 and 7.3
  composer.json
  composer.lock
  src/integrations/admin/unsupported-php-version-notice.php
Labels: changelog: other

#21306 Add is_string check to safeguard against array meta keys.
  composer.json
  src/integrations/watchers/indexable-post-meta-watcher.php
Labels: changelog: bugfix

#21309 Add type reset to button - UI Library
  packages/ui-library/src/elements/button/index.js
Labels: changelog: enhancement

#21310 UI library release v4.0.0
  package.json
  packages/browserslist-config/CHANGELOG.md
  packages/browserslist-config/package.json
  packages/components/package.json
  packages/feature-flag/package.json
  packages/helpers/package.json
  packages/js/package.json
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/package.json
  packages/style-guide/package.json
  packages/ui-library/changelog.md
  packages/ui-library/package.json
  packages/yoast-components/package.json
  packages/yoastseo/package.json
Labels: changelog: non-user-facing

#21307 Stop storing empty usermeta used by sitemaps
  admin/class-admin-user-profile.php
  admin/class-admin.php
  inc/class-upgrade.php
  src/conditionals/user-can-edit-users-conditional.php
  src/conditionals/user-edit-conditional.php
  src/integrations/cleanup-integration.php
  src/user-meta/application/additional-contactmethods-collector.php
  src/user-meta/application/cleanup-service.php
  src/user-meta/application/custom-meta-collector.php
  src/user-meta/domain/additional-contactmethod-interface.php
  src/user-meta/domain/custom-meta-interface.php
  src/user-meta/framework/additional-contactmethods/facebook.php
  src/user-meta/framework/additional-contactmethods/instagram.php
  src/user-meta/framework/additional-contactmethods/linkedin.php
  src/user-meta/framework/additional-contactmethods/myspace.php
  src/user-meta/framework/additional-contactmethods/pinterest.php
  src/user-meta/framework/additional-contactmethods/soundcloud.php
  src/user-meta/framework/additional-contactmethods/tumblr.php
  src/user-meta/framework/additional-contactmethods/wikipedia.php
  src/user-meta/framework/additional-contactmethods/x.php
  src/user-meta/framework/additional-contactmethods/youtube.php
  src/user-meta/framework/custom-meta/author-metadesc.php
  src/user-meta/framework/custom-meta/author-title.php
  src/user-meta/framework/custom-meta/content-analysis-disable.php
  src/user-meta/framework/custom-meta/inclusive-language-analysis-disable.php
  src/user-meta/framework/custom-meta/keyword-analysis-disable.php
  src/user-meta/framework/custom-meta/noindex-author.php
  src/user-meta/infrastructure/cleanup-repository.php
  src/user-meta/user-interface/additional-contactmethods-integration.php
  src/user-meta/user-interface/cleanup-integration.php
  src/user-meta/user-interface/custom-meta-integration.php
  tests/Unit/Admin/Admin_Features_Test.php
  tests/Unit/Admin/User_Profile_Test.php
  tests/Unit/Conditionals/User_Can_Edit_Users_Conditional_Test.php
  tests/Unit/Conditionals/User_Edit_Conditional_Test.php
  tests/Unit/User_Meta/Application/Additional_Contactmethods_Collector_Test.php
  tests/Unit/User_Meta/Application/Cleanup_Service_Test.php
  tests/Unit/User_Meta/Application/Custom_Meta_Collector_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Facebook_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Instagram_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Linkedin_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Myspace_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Pinterest_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Soundcloud_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Tumblr_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Wikipedia_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/X_Test.php
  tests/Unit/User_Meta/Framework/Additional_Contactmethods/Youtube_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Author_Metadesc_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Author_Title_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Content_Analysis_Disable_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Inclusive_Language_Analysis_Disable_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Keyword_Analysis_Disable_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Noindex_Author_Test.php
  tests/Unit/User_Meta/Infrastructure/Cleanup_Repository_Test.php
  tests/Unit/User_Meta/User_Interface/Additional_Contactmethods_Integration_Test.php
  tests/Unit/User_Meta/User_Interface/Cleanup_Integration_Test.php
  tests/Unit/User_Meta/User_Interface/Custom_Meta_Integration_Test.php
Labels: changelog: enhancement

#21316 Merges feature/lingo-fixes to trunk
  packages/yoastseo/spec/bundledPlugins/previouslyUsedKeywordsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/match/findKeywordFormsInStringSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/morphology/stemPrefixedFunctionWordsSpec.js
  packages/yoastseo/spec/languageProcessing/languages/he/helpers/createBasicWordFormsSpec.js
  packages/yoastseo/spec/languageProcessing/researches/findKeyphraseInSEOTitleSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/KeyphraseInSEOTitleAssessmentSpec.js
  packages/yoastseo/src/bundledPlugins/previouslyUsedKeywords.js
  packages/yoastseo/src/languageProcessing/helpers/match/findKeywordFormsInString.js
  packages/yoastseo/src/languageProcessing/helpers/morphology/stemPrefixedFunctionWords.js
  packages/yoastseo/src/languageProcessing/languages/ar/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/ar/config/functionWords.js
  packages/yoastseo/src/languageProcessing/languages/ar/config/prefixedFunctionWords.js
  packages/yoastseo/src/languageProcessing/languages/ar/helpers/createBasicWordForms.js
  packages/yoastseo/src/languageProcessing/languages/he/Researcher.js
  packages/yoastseo/src/languageProcessing/languages/he/config/prefixedFunctionWords.js
  packages/yoastseo/src/languageProcessing/languages/he/helpers/createBasicWordForms.js
  packages/yoastseo/src/languageProcessing/researches/findKeyphraseInSEOTitle.js
Labels: changelog: non-user-facing

#21288 Add error bounday to metabox
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/metabox-error-fallback.js
  packages/js/src/components/sidebar-error-fallback.js
  packages/js/src/elementor/components/elementor-error-fallback.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/helpers/disableMetaboxTabs.js
  packages/js/src/settings/components/error-fallback.js
  packages/js/src/shared-admin/components/error-fallback.js
Labels: changelog: enhancement

#21319 Schedule the usermeta cleanup 24 hours into the future
  inc/class-upgrade.php
  src/integrations/cleanup-integration.php
Labels: changelog: non-user-facing

#20973 Tests: fix incorrect file and class name
  composer.json
  tests/Unit/Inc/Sitemaps/Sitemaps_Router_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#21267 Refactor integration enable disabled for script data.
  admin/formatter/class-metabox-formatter.php
  packages/js/src/analysis/isSEMrushIntegrationActive.js
  packages/js/src/analysis/isWincherIntegrationActive.js
  src/editors/application/analysis-features/enabled-analysis-features-repository.php
  src/editors/application/integrations/Integration-Information-repository.php
  src/editors/domain/analysis-features/analysis-feature-interface.php
  src/editors/domain/integrations/integration-data-provider-interface.php
  src/editors/framework/cornerstone-content.php
  src/editors/framework/inclusive-language-analysis.php
  src/editors/framework/integrations/jetpack-markdown.php
  src/editors/framework/integrations/multilingual.php
  src/editors/framework/integrations/semrush.php
  src/editors/framework/integrations/wincher.php
  src/editors/framework/keyphrase-analysis.php
  src/editors/framework/previously-used-keyphrase.php
  src/editors/framework/readability-analysis.php
  src/editors/framework/word-form-recognition.php
  tests/Unit/Editors/Framework/Integrations/Jetpack_Markdown_Test.php
  tests/Unit/Editors/Framework/Integrations/Multilingual_Test.php
  tests/Unit/Editors/Framework/Integrations/Semrush_Test.php
  tests/Unit/Editors/Framework/Integrations/Wincher_Test.php
Labels: changelog: non-user-facing

#21321 #1740 - Improve Autocomplete disabled state
  packages/ui-library/src/elements/autocomplete/style.css
Labels: changelog: enhancement

#21312 Cleanup: Remove templates directory and functionality that uses it
  packages/yoastseo/Gruntfile.js
  packages/yoastseo/src/scoring/renderers/AssessorPresenter.js
  packages/yoastseo/src/snippetPreview/snippetPreview.js
  packages/yoastseo/src/snippetPreview/templates.js
  packages/yoastseo/templates/assessmentPresenterResult.jst
  packages/yoastseo/templates/hiddenSpan.jst
  packages/yoastseo/templates/relevantWords.jst
  packages/yoastseo/templates/snippetEditor.jst
Labels: changelog: non-user-facing

#21330 Fix PHP deprecation error when passing null instead of string
  composer.json
  src/integrations/front-end-integration.php
  tests/WP/Frontend/Front_End_Integration_Test.php
Labels: changelog: bugfix

#21343 Set the minimum supported WordPress version to 6.4.
  .github/workflows/test.yml
  tests/Unit/Inc/Addon_Manager_Test.php
  tests/Unit/bootstrap.php
  wp-seo-main.php
  wp-seo.php
Labels: changelog: other

#21329 Convert the How To block and the FAQ block to the Blocks V3 API
  .gitignore
  admin/class-admin-asset-manager.php
  config/grunt/task-config/copy.js
  config/webpack/paths.js
  config/webpack/webpack.config.base.js
  config/webpack/webpack.config.js
  css/src/structured-data-blocks.css
  package.json
  packages/js/src/structured-data-blocks.js
  packages/js/src/structured-data-blocks/faq/block.js
  packages/js/src/structured-data-blocks/faq/block.json
  packages/js/src/structured-data-blocks/how-to/block.js
  packages/js/src/structured-data-blocks/how-to/block.json
  src/integrations/blocks/structured-data-blocks.php
  yarn.lock
Labels: changelog: enhancement
