Repository Yoast/wordpress-seo, pull requests merged in 2024-08, with the labels that each got.

#21511 Allows setting a reason for a disabled Yoast AI Optimize button
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
  packages/js/src/redux/actions/AIButton.js
  packages/js/src/redux/reducers/AIButton.js
  packages/js/src/redux/selectors/AIButton.js
  packages/js/tests/ai-assessment-fixes/components/AIAssessmentFixesButton.test.js
  packages/js/tests/redux/actions/AIButton.test.js
  packages/js/tests/redux/reducers/AIButton.test.js
  packages/js/tests/redux/selectors/AIButton.test.js
Labels: changelog: non-user-facing

#21515 Deprecate unneeded functions.
  admin/class-yoast-form.php
  admin/class-yoast-input-validation.php
  composer.json
  tests/Unit/Admin/Input_Validation_Test.php
Labels: changelog: other

#21502 Add auto inject with variadic operator
  src/integrations/admin/background-indexing-integration.php
  tests/Unit/Integrations/Admin/Background_Indexing_Integration_Test.php
Labels: changelog: non-user-facing

#21510 Remove no longer used `add_settings_error`
  inc/options/class-wpseo-option-social.php
  inc/options/class-wpseo-option.php
  tests/Unit/Inc/Options/Option_Social_Test.php
Labels: changelog: non-user-facing

#21514 Elementor: partially support document switching
  composer.json
  config/webpack/paths.js
  css/src/elementor.css
  packages/js/src/elementor/components/render-in-portal-if-element-exists.js
  packages/js/src/elementor/helpers/hooks.js
  packages/js/src/elementor/helpers/is-form-id.js
  packages/js/src/elementor/helpers/is-relevant-change.js
  packages/js/src/elementor/helpers/update-save-as-draft-warning.js
  packages/js/src/elementor/initialize.js
  packages/js/src/elementor/initializers/editor-integration.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/elementor/initializers/editor-watcher.js
  packages/js/src/elementor/initializers/form-watcher.js
  packages/js/src/elementor/initializers/post-status-watcher.js
  packages/js/src/elementor/initializers/render-sidebar.js
  packages/js/src/elementor/initializers/tab.js
  packages/js/src/externals/redux.js
  packages/js/src/helpers/elementorHook.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/redux/utils/create-freeze-reducer.js
  packages/js/src/redux/utils/create-snapshot-reducer.js
  packages/js/tests/elementor/render-in-portal-if-element-exists.test.js
  packages/js/tests/redux/utils/create-freeze-reducer.test.js
  packages/js/tests/redux/utils/create-snapshot-reducer.test.js
  src/conditionals/third-party/elementor-edit-conditional.php
  src/elementor/infrastructure/request-post.php
  src/integrations/third-party/elementor.php
  tests/Unit/Conditionals/Third_Party/Elementor_Edit_Conditional_Test.php
  tests/Unit/Elementor/Infrastructure/Request_Post_Test.php
Labels: UI change, changelog: bugfix

#21508 Refactor plugin availability.
  admin/class-plugin-availability.php
  admin/metabox/class-metabox.php
  src/integrations/admin/integrations-page.php
  src/integrations/settings-integration.php
  tests/Unit/Admin/Plugin_Availability_Test.php
  tests/Unit/Integrations/Admin/Integrations_Page_Integration_Test.php
  tests/WP/Admin/Plugin_Availability_Test.php
  tests/WP/Doubles/Admin/Plugin_Availability_Double.php
Labels: changelog: non-user-facing

#21522 Elementor: fix timing issue after save and before closing the document
  packages/js/src/elementor/initializers/editor-integration.js
Labels: changelog: non-user-facing

#21523 Fix hardcoded `wp-admin` path
  packages/js/src/components/SchemaTab.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/initializers/editor-store.js
  packages/js/src/installation-success.js
  packages/js/src/redux/actions/index.js
  packages/js/src/redux/reducers/index.js
  packages/js/src/redux/selectors/index.js
  packages/js/src/shared-admin/store/admin-url.js
  packages/js/src/shared-admin/store/index.js
  packages/js/tests/shared-admin/store/admin-url.test.js
  src/editors/framework/site/base-site-information.php
  src/integrations/admin/installation-success-integration.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/Unit/Editors/Framework/Site/Term_Site_Information_Test.php
Labels: changelog: bugfix

#21524 Add admin-ajax to conditional to rework permalinks based on primary category
  src/conditionals/primary-category-conditional.php
Labels: changelog: bugfix

#21513 Refactor filter_input and remove dependency.
  src/helpers/first-time-configuration-notice-helper.php
  src/integrations/settings-integration.php
  wp-seo-main.php
Labels: changelog: non-user-facing

#21530 Fix word complexity assessment not updating in Shopify when the keyphrase is changed
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: changelog: non-user-facing, Shopify

#21440 Update transitionWords.js
  packages/yoastseo/src/languageProcessing/languages/ru/config/transitionWords.js
Labels: community-patch, changelog: enhancement, Shopify

#21533 Add learn more link to primary category picker
  packages/js/src/components/PrimaryTaxonomyPicker.js
  packages/js/src/components/TaxonomyPicker.js
  packages/js/src/containers/PrimaryTaxonomyPicker.js
Labels: UI change, changelog: other

#21537 Don't overwrite user settings when the respective features are disabled
  admin/class-admin-user-profile.php
  admin/views/user-profile.php
  src/user-meta/application/custom-meta-collector.php
  src/user-meta/domain/custom-meta-interface.php
  src/user-meta/framework/custom-meta/author-metadesc.php
  src/user-meta/framework/custom-meta/author-title.php
  src/user-meta/framework/custom-meta/content-analysis-disable.php
  src/user-meta/framework/custom-meta/inclusive-language-analysis-disable.php
  src/user-meta/framework/custom-meta/keyword-analysis-disable.php
  src/user-meta/framework/custom-meta/noindex-author.php
  src/user-meta/user-interface/custom-meta-integration.php
  tests/Unit/User_Meta/Application/Custom_Meta_Collector_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Author_Metadesc_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Author_Title_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Content_Analysis_Disable_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Inclusive_Language_Analysis_Disable_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Keyword_Analysis_Disable_Test.php
  tests/Unit/User_Meta/Framework/Custom_Meta/Noindex_Author_Test.php
  tests/Unit/User_Meta/User_Interface/Custom_Meta_Integration_Test.php
Labels: changelog: bugfix

#21528 Remove zapier remnants
  admin/formatter/class-metabox-formatter.php
  admin/tracking/class-tracking-settings-data.php
  config/dependency-injection/deprecated-classes.php
  css/src/metabox.css
  inc/class-wpseo-meta.php
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  packages/js/src/analysis/isZapierConnected.js
  packages/js/src/analysis/isZapierIntegrationActive.js
  packages/js/src/editor-modules.js
  packages/js/src/initializers/admin.js
  packages/js/src/redux/reducers/preferences.js
  src/deprecated/src/integrations/duplicate-post-integration.php
  src/integrations/settings-integration.php
  tests/Unit/Integrations/Duplicate_Post_Integration_Test.php
  tests/WP/Inc/Options/Option_WPSEO_Test.php
Labels: changelog: non-user-facing

#21541 Only handle editor changes when on the document from our form
  packages/js/src/elementor/helpers/is-form-id.js
  packages/js/src/elementor/initializers/editor-watcher.js
Labels: changelog: non-user-facing, fix-before-release

#21545 Revert elementor document switching
  composer.json
  config/webpack/paths.js
  css/src/elementor.css
  packages/js/src/elementor.js
  packages/js/src/elementor/components/render-in-portal-if-element-exists.js
  packages/js/src/elementor/helpers/hooks.js
  packages/js/src/elementor/helpers/is-form-id.js
  packages/js/src/elementor/helpers/is-relevant-change.js
  packages/js/src/elementor/helpers/update-save-as-draft-warning.js
  packages/js/src/elementor/initializers/editor-integration.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/elementor/initializers/form-watcher.js
  packages/js/src/elementor/initializers/post-status-watcher.js
  packages/js/src/elementor/initializers/render-sidebar.js
  packages/js/src/elementor/initializers/tab.js
  packages/js/src/externals/redux.js
  packages/js/src/helpers/elementorHook.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/redux/utils/create-freeze-reducer.js
  packages/js/src/redux/utils/create-snapshot-reducer.js
  packages/js/src/watchers/elementorWatcher.js
  packages/js/tests/elementor/render-in-portal-if-element-exists.test.js
  packages/js/tests/redux/utils/create-freeze-reducer.test.js
  packages/js/tests/redux/utils/create-snapshot-reducer.test.js
  src/conditionals/third-party/elementor-edit-conditional.php
  src/elementor/infrastructure/request-post.php
  src/integrations/third-party/elementor.php
  tests/Unit/Conditionals/Third_Party/Elementor_Edit_Conditional_Test.php
  tests/Unit/Elementor/Infrastructure/Request_Post_Test.php
Labels: changelog: reverted

#21538 Add column-gap to each column inside the AnalysisList
  packages/analysis-report/src/AnalysisResult.js
  packages/analysis-report/tests/__snapshots__/AnalysisResultTest.js.snap
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
Labels: UI change, changelog: non-user-facing, Shopify

#21548 Elementor: partially support document switching
  composer.json
  config/webpack/paths.js
  css/src/elementor.css
  packages/js/src/elementor/components/render-in-portal-if-element-exists.js
  packages/js/src/elementor/helpers/hooks.js
  packages/js/src/elementor/helpers/is-form-id.js
  packages/js/src/elementor/helpers/is-relevant-change.js
  packages/js/src/elementor/helpers/update-save-as-draft-warning.js
  packages/js/src/elementor/initialize.js
  packages/js/src/elementor/initializers/editor-integration.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/elementor/initializers/editor-watcher.js
  packages/js/src/elementor/initializers/form-watcher.js
  packages/js/src/elementor/initializers/post-status-watcher.js
  packages/js/src/elementor/initializers/render-sidebar.js
  packages/js/src/elementor/initializers/tab.js
  packages/js/src/externals/redux.js
  packages/js/src/helpers/elementorHook.js
  packages/js/src/initializers/elementor-editor-integration.js
  packages/js/src/redux/utils/create-freeze-reducer.js
  packages/js/src/redux/utils/create-snapshot-reducer.js
  packages/js/tests/elementor/render-in-portal-if-element-exists.test.js
  packages/js/tests/redux/utils/create-freeze-reducer.test.js
  packages/js/tests/redux/utils/create-snapshot-reducer.test.js
  src/conditionals/third-party/elementor-edit-conditional.php
  src/elementor/infrastructure/request-post.php
  src/integrations/third-party/elementor.php
  tests/Unit/Conditionals/Third_Party/Elementor_Edit_Conditional_Test.php
  tests/Unit/Elementor/Infrastructure/Request_Post_Test.php
Labels: changelog: enhancement

#21549 Stop flushing cache aggressively when not needed
  inc/class-wpseo-utils.php
  src/analytics/user-interface/last-completed-indexation-integration.php
  tests/Unit/Analytics/User_Interface/Last_Completed_Indexation_Integration_Test.php
Labels: changelog: enhancement

#21535 Remove unnecessary inclusive language feedback string variables
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
Labels: changelog: non-user-facing

#21553 21550 move translations for media label from wpseoscriptdata
  admin/class-yoast-form.php
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy-fields-presenter.php
  css/src/metabox.css
  packages/js/src/initializers/admin-media.js
  packages/js/src/post-edit.js
  packages/js/src/settings.js
  packages/js/src/term-edit.js
  src/integrations/third-party/elementor.php
  tests/WP/Taxonomy/Taxonomy_Fields_Presenter_Test.php
Labels: changelog: non-user-facing

#21559 21558 deprecate the translate meta boxes method
  admin/class-yoast-form.php
  admin/metabox/class-metabox.php
Labels: changelog: non-user-facing

#21556 21555 remove featured image notice translation from wpseoscriptdata
  admin/metabox/class-metabox.php
  packages/js/src/initializers/featured-image.js
  packages/js/src/post-edit.js
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#21561 remove old translations property
  admin/formatter/class-metabox-formatter.php
  packages/js/src/analysis/getTranslations.js
  packages/js/src/analysis/worker.js
  packages/js/src/initializers/post-scraper.js
  packages/js/src/initializers/term-scraper.js
  tests/WP/Formatter/Metabox_Formatter_Test.php
Labels: changelog: non-user-facing

#21564 exclude image caption inside classic block from keyphrase in intro assessment
  packages/yoastseo/spec/languageProcessing/researches/findKeywordInFirstParagraphSpec.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInFirstParagraph.js
Labels: changelog: bugfix

#21572 21570 remove translation of no parent text from metabox class
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  packages/js/src/analysis/plugins/replacevar-plugin.js
  packages/js/src/elementor/replaceVars/blockEditor/parentTitle.js
  packages/js/src/elementor/replaceVars/classicEditor/parentTitle.js
  src/integrations/third-party/elementor.php
Labels: changelog: non-user-facing

#21574 Remove outdated media translation, related to #21554
  admin/class-config.php
  admin/taxonomy/class-taxonomy.php
Labels: changelog: non-user-facing

#21571 Move and rename inclusive language feedback strings variables
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/appearanceAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/cultureAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings/ageAssessmentStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings/cultureAssessmentStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings/disabilityAssessmentStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings/genderAssessmentStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/feedbackStrings/generalFeedbackStrings.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sesAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/sexualOrientationAssessments.js
Labels: changelog: non-user-facing, Shopify

#21569 Remove LRM marks from Arabic function words
  packages/yoastseo/src/languageProcessing/languages/ar/config/functionWords.js
Labels: changelog: bugfix, Shopify
