Repository Yoast/wordpress-seo, pull requests merged in 2024-01, with the labels that each got.

#21007 Uses an allowlist for the webworker's dependencies
  packages/js/src/analysis-worker.js
Labels: changelog: non-user-facing

#21024 Fix the opening of our document panel in WP 6.5
  packages/js/src/initializers/block-editor-integration.js
Labels: changelog: bugfix

#21025 Remove plugin icon size override [WP 6.5]
  css/src/metabox.css
Labels: changelog: bugfix

#21030 Fix the opening of our document panel in Gutenberg 17.4.1
  packages/js/src/initializers/block-editor-integration.js
Labels: changelog: non-user-facing

#21032 Fix get_head validation callback
  src/routes/indexables-head-route.php
  tests/Unit/Routes/Indexables_Head_Route_Test.php
  tests/WP/Routes/Indexables_Head_Route_Test.php
Labels: community-patch, changelog: bugfix

#21040 Revert "Force page type to itempage for products"
  admin/metabox/class-metabox.php
  packages/components/src/select/Select.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
  packages/js/src/components/SchemaTab.js
  packages/js/src/settings/routes/templates/post-type.js
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#21034 255 inclusive language tech debt flip the behavior of the isprecededbyexception function
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/helpers/isPrecededByExceptionSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/ageAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/disabilityAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/otherAssessments.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isFollowedAndPrecededByException.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/helpers/isPrecededByException.js
Labels: changelog: non-user-facing, Shopify

#21045 Deprecate @yoast/components
  .github/workflows/deprecation-check.yml
  packages/components/README.md
Labels: changelog: non-user-facing

#21056 Fix the opening of our document panel (Gutenberg 17.5)
  packages/js/src/initializers/block-editor-integration.js
Labels: changelog: bugfix

#21057 Fix the opening of our document panel in Gutenberg 17.4.1 (hotfix)
  packages/js/src/initializers/block-editor-integration.js
Labels: changelog: bugfix

#21055 Fix yarn add
  yarn.lock
Labels: changelog: non-user-facing

#21060 Fix wrong woo page type
  admin/metabox/class-metabox.php
  packages/components/src/select/Select.js
  packages/components/tests/__snapshots__/SelectTest.js.snap
  packages/js/src/components/SchemaTab.js
  packages/js/src/redux/selectors/isWooSEO.js
  packages/js/src/settings/routes/templates/post-type.js
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#21049 Update defaults for multiple locations and alert message
  packages/js/src/settings/routes/site-representation.js
  src/integrations/settings-integration.php
Labels: changelog: non-user-facing

#21046 20853 disable category prefix category archives can be accessed via 2 urls
  inc/class-rewrite.php
Labels: changelog: bugfix

#20839 Upgrade for node v18
  .github/workflows/deploy.yml
  .github/workflows/jslint.yml
  .github/workflows/jstest.yml
  .nvmrc
  VERSIONS.json
  config/webpack/webpack.config.base.js
  config/webpack/webpack.config.js
  package.json
  packages/browserslist-config/package.json
  packages/ui-library/package.json
  packages/yoastseo/grunt/config/shell.js
  yarn.lock
Labels: changelog: non-user-facing, Shopify

#21072 Improves some translator comments
  packages/js/src/components/WincherPerformanceReport.js
  packages/js/src/components/modals/WordProofWebhookFailed.js
  packages/js/src/first-time-configuration/tailwind-components/stepper.js
  packages/js/src/initializers/block-editor-integration.js
  packages/js/src/insights/components/prominent-words.js
  packages/js/src/settings/helpers/search.js
  packages/yoastseo/src/scoring/assessments/readability/SubheadingDistributionTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/PageTitleWidthAssessment.js
Labels: changelog: non-user-facing

#21073 Adds new filter and fixes CS issues in the file.
  composer.json
  inc/sitemaps/class-sitemaps-renderer.php
Labels: changelog: non-user-facing

#21078 Fix for strip category slug for blog on multisite
  inc/class-rewrite.php
Labels: changelog: non-user-facing, fix-before-release

#21075 Encode spaces in webpage id and url
  src/context/meta-tags-context.php
  src/generators/schema/webpage.php
  tests/WP/Generators/Schema/WebPage_Test.php
Labels: changelog: enhancement

#21082 Revert #20921 - Invalidate the Yoast SEO PHP files and directories instead of...
  wp-seo-main.php
Labels: changelog: bugfix

#21083 Fix filter params for images in sitemap
  inc/sitemaps/class-post-type-sitemap-provider.php
  tests/WP/Doubles/Inc/Post_Type_Sitemap_Provider_Double.php
  tests/WP/Sitemaps/Post_Type_Sitemap_Provider_Test.php
Labels: changelog: bugfix

#21054 Fix multiline label issue for file input
  packages/ui-library/src/elements/file-input/style.css
Labels: changelog: bugfix, Shopify

#21084 171 its not possible to search for ai in settings because of character limit
  packages/js/src/settings/components/search.js
  packages/js/src/settings/helpers/search.js
  packages/js/tests/settings/__snapshots__/search.test.js.snap
  packages/js/tests/settings/search.test.js
Labels: changelog: enhancement

#21070 Sync JS dependencies (to WP versions)
  config/scripts/sync-wp-dependencies.js
  package.json
Labels: changelog: non-user-facing

#21085 Add id attribute to SidebarCollapsible inner button
  packages/js/src/components/SidebarCollapsible.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/tests/components/SidebarCollapsibleTest.js
  packages/js/tests/components/__snapshots__/SidebarCollapsibleTest.js.snap
Labels: changelog: non-user-facing

#21088 Remove parameter type declaration on method hooked to a WP filter
  admin/filters/class-abstract-post-filter.php
  composer.json
Labels: changelog: bugfix

#21069 20886 add placeholders and integration tests to watchers
  composer.json
  src/generators/schema/webpage.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/integrations/watchers/option-titles-watcher.php
  tests/Unit/Integrations/Watchers/Indexable_Ancestor_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Option_Titles_Watcher_Test.php
  tests/WP/Admin/Watchers/Indexable_Ancestor_Watcher_Test.php
  tests/WP/Admin/Watchers/Option_Titles_Watcher_Test.php
  tests/WP/Doubles/Admin/Watchers/Indexable_Ancestor_Watcher_Double.php
Labels: changelog: non-user-facing

#21050 38-inclusive-language-make-analysis-section-headings-stand-out
  packages/analysis-report/src/ContentAnalysis.js
  packages/analysis-report/tests/__snapshots__/ContentAnalysisTest.js.snap
  packages/components/src/Collapsible.js
  packages/components/src/SectionTitle.js
  packages/components/tests/__snapshots__/CollapsibleTest.js.snap
  packages/js/src/components/contentAnalysis/InclusiveLanguageAnalysis.js
Labels: UI change, changelog: enhancement, Shopify

#21096 Links `Person or Organization` node to the `ProfilePage` Node.
  composer.json
  src/context/meta-tags-context.php
  src/generators/schema/person.php
  tests/WP/Generators/Schema/Person_Test.php
Labels: changelog: bugfix

#21095 Add discount on all plugins subscription card
  admin/views/licenses.php
  css/src/yoast-extensions.css
Labels: UI change, changelog: other

#21098 335 add gutenberg to the list of editors a pr should be tested on
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: non-user-facing

#21097 Prevent parsing with full url
  src/integrations/front-end-integration.php
  tests/WP/Frontend/Front_End_Integration_Test.php
Labels: changelog: bugfix
