Repository Yoast/wordpress-seo, pull requests merged in 2024-06, with the labels that each got.

#21423 Allow users to add additional CSS classes to the Toast's close button
  packages/ui-library/src/elements/toast/index.js
Labels: changelog: non-user-facing

#21335 Make the filter that disables indexable creation, cover also the creation when a post is created and updated
  src/actions/importing/aioseo/aioseo-posts-importing-action.php
  src/actions/indexing/abstract-link-indexing-action.php
  src/builders/indexable-builder.php
  src/builders/indexable-link-builder.php
  src/builders/primary-term-builder.php
  src/helpers/indexable-helper.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/integrations/watchers/indexable-author-watcher.php
  src/integrations/watchers/indexable-home-page-watcher.php
  src/integrations/watchers/indexable-post-type-archive-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-term-watcher.php
  src/integrations/watchers/primary-term-watcher.php
  src/repositories/indexable-hierarchy-repository.php
  src/repositories/primary-term-repository.php
  tests/Unit/Actions/Indexing/Abstract_Link_Indexing_Action_Test.php
  tests/Unit/Actions/Indexing/Post_Link_Indexing_Action_Test.php
  tests/Unit/Actions/Indexing/Term_Link_Indexing_Action_Test.php
  tests/Unit/Builders/Indexable_Builder/Abstract_Indexable_Builder_TestCase.php
  tests/Unit/Builders/Indexable_Builder/Build_For_Date_Archive_Test.php
  tests/Unit/Builders/Indexable_Builder/Build_For_Home_Page_Test.php
  tests/Unit/Builders/Indexable_Builder/Build_For_Id_And_Type_Test.php
  tests/Unit/Builders/Indexable_Builder/Build_For_Post_Type_Archive_Test.php
  tests/Unit/Builders/Indexable_Builder/Build_For_System_Page_Test.php
  tests/Unit/Builders/Indexable_Builder/Build_Test.php
  tests/Unit/Builders/Indexable_Builder/Maybe_Build_Author_Indexable_Test.php
  tests/Unit/Builders/Indexable_Builder/Save_Indexable_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Abstract_Indexable_Link_Builder_TestCase.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Create_Internal_Link_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Get_Permalink_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Update_Incoming_Links_For_Related_Test.php
  tests/Unit/Builders/Primary_Term_Builder_Test.php
  tests/Unit/Doubles/Builders/Indexable_Builder_Double.php
  tests/Unit/Helpers/Indexable_Helper_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Ancestor_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Author_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Home_Page_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Post_Type_Archive_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Post_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Term_Watcher_Test.php
  tests/Unit/Repositories/Indexable_Hierarchy_Repository_Test.php
  tests/WP/Admin/Watchers/Indexable_Ancestor_Watcher_Test.php
  tests/WP/Repositories/Primary_Term_Repository_Test.php
Labels: changelog: bugfix

#21428 Fix the `Premium` badge
  src/integrations/admin/menu-badge-integration.php
Labels: changelog: non-user-facing

#21415 Update styling of sparkle buttons ai assessment fixes
  packages/analysis-report/tests/__snapshots__/SiteSEOReportTest.js.snap
  packages/components/src/AIFixesButton.js
  packages/components/src/IconAIFixesButton.js
  packages/components/src/index.js
  packages/components/tests/__snapshots__/IconAIFixesButtonTest.js.snap
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
  packages/js/src/ai-assessment-fixes/components/sparkles-icon.js
  packages/js/src/components/contentAnalysis/SeoAnalysis.js
  packages/js/tests/ai-assessment-fixes/components/AIAssessmentFixesButton.test.js
  packages/js/tests/ai-assessment-fixes/components/SparklesIcon.test.js
  packages/js/tests/ai-assessment-fixes/components/__snapshots__/SparklesIcon.test.js.snap
  packages/ui-library/src/elements/toast/index.js
Labels: innovation, UI change

#21400 Exclude keyphrases from complex words
  packages/yoastseo/spec/languageProcessing/researches/wordComplexitySpec.js
  packages/yoastseo/src/languageProcessing/researches/wordComplexity.js
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
Labels: changelog: enhancement, Shopify

#21424 Deprecate the Wordproof feature
  admin/formatter/class-metabox-formatter.php
  admin/metabox/class-metabox.php
  admin/tracking/class-tracking-settings-data.php
  composer.json
  composer.lock
  config/dependency-injection/deprecated-classes.php
  config/grunt/task-config/copy.js
  config/php-scoper/wordproof.inc.php
  config/webpack/paths.js
  css/src/metabox.css
  css/src/modal.css
  inc/options/class-wpseo-option-ms.php
  inc/options/class-wpseo-option-wpseo.php
  packages/js/.eslintrc.js
  packages/js/package.json
  packages/js/src/analysis/isWordProofIntegrationActive.js
  packages/js/src/components/AdvancedSettings.js
  packages/js/src/components/WordProofTimestampToggle.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/modals/WordProofAuthenticationModals.js
  packages/js/src/components/modals/WordProofOauthFailed.js
  packages/js/src/components/modals/WordProofOauthSuccess.js
  packages/js/src/components/modals/WordProofWebhookFailed.js
  packages/js/src/containers/AdvancedSettings.js
  packages/js/src/elementor.js
  packages/js/src/elementor/components/fills/ElementorFill.js
  packages/js/src/helpers/fields/AdvancedFields.js
  packages/js/src/helpers/wordproof.js
  packages/js/src/initializers/block-editor-integration.js
  packages/js/src/initializers/classic-editor-integration.js
  packages/js/src/integrations-page/other-integrations.js
  packages/js/src/redux/actions/advancedSettings.js
  packages/js/src/redux/reducers/advancedSettings.js
  packages/js/src/redux/reducers/preferences.js
  packages/js/src/redux/selectors/advancedSettings.js
  packages/js/src/wordproof-uikit.js
  src/deprecated/src/conditionals/third-party/wordproof-integration-active-conditional.php
  src/deprecated/src/conditionals/third-party/wordproof-plugin-inactive-conditional.php
  src/deprecated/src/config/wordproof-app-config.php
  src/deprecated/src/config/wordproof-translations.php
  src/deprecated/src/helpers/wordproof-helper.php
  src/deprecated/src/integrations/third-party/wordproof.php
  src/integrations/admin/integrations-page.php
  src/integrations/watchers/option-wpseo-watcher.php
  tests/Unit/Integrations/Watchers/Option_Wpseo_Watcher_Test.php
  yarn.lock
Labels: changelog: other

#21436 Don't show sparkle buttons for scenarios we don't cover
  packages/yoastseo/spec/scoring/assessments/seo/KeywordDensityAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/seo/SubHeadingsKeywordAssessmentSpec.js
  packages/yoastseo/src/scoring/assessments/seo/KeywordDensityAssessment.js
  packages/yoastseo/src/scoring/assessments/seo/SubHeadingsKeywordAssessment.js
Labels: innovation, changelog: non-user-facing

#21437 Tooltip on ai assessment buttons doesnt show
  css/src/tooltips.css
  packages/components/src/AIFixesButton.js
  packages/components/src/IconAIFixesButton.js
  packages/components/tests/__snapshots__/IconAIFixesButtonTest.js.snap
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
  packages/js/tests/ai-assessment-fixes/components/AIAssessmentFixesButton.test.js
Labels: UI change, changelog: non-user-facing

#21441 Change 'blue' to 'indigo' in all AI branded components (Toast and AI …
  packages/components/src/AIFixesButton.js
  packages/components/tests/__snapshots__/IconAIFixesButtonTest.js.snap
  packages/js/src/ai-assessment-fixes/components/sparkles-icon.js
  packages/js/tests/ai-assessment-fixes/components/__snapshots__/SparklesIcon.test.js.snap
Labels: innovation, UI change

#21439 AI fixes buttons in the sidebar go blank
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
  packages/js/src/ai-assessment-fixes/components/sparkles-icon.js
  packages/js/tests/ai-assessment-fixes/components/SparklesIcon.test.js
  packages/js/tests/ai-assessment-fixes/components/__snapshots__/SparklesIcon.test.js.snap
Labels: innovation, changelog: non-user-facing

#21431 Updates the copy for the introduction and consent modals
  css/src/introductions.css
  images/ai-fix-assessments-thumbnail.png
  packages/js/src/ai-assessment-fixes/components/modal-content.js
  packages/js/src/ai-generator/initialize.js
  packages/js/src/introductions/components/content.js
  packages/js/src/introductions/components/modal.js
  packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js
  packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap
Labels: changelog: non-user-facing

#21339 21318 refactor seo data provision to script data
  admin/formatter/class-post-metabox-formatter.php
  admin/formatter/class-term-metabox-formatter.php
  composer.json
  src/editors/application/seo/post-seo-information-repository.php
  src/editors/application/seo/term-seo-information-repository.php
  src/editors/domain/seo/description.php
  src/editors/domain/seo/keyphrase.php
  src/editors/domain/seo/seo-plugin-data-interface.php
  src/editors/domain/seo/social.php
  src/editors/domain/seo/title.php
  src/editors/framework/seo/description-data-provider-interface.php
  src/editors/framework/seo/keyphrase-interface.php
  src/editors/framework/seo/posts/abstract-post-seo-data-provider.php
  src/editors/framework/seo/posts/description-data-provider.php
  src/editors/framework/seo/posts/keyphrase-data-provider.php
  src/editors/framework/seo/posts/social-data-provider.php
  src/editors/framework/seo/posts/title-data-provider.php
  src/editors/framework/seo/social-data-provider-interface.php
  src/editors/framework/seo/terms/abstract-term-seo-data-provider.php
  src/editors/framework/seo/terms/description-data-provider.php
  src/editors/framework/seo/terms/keyphrase-data-provider.php
  src/editors/framework/seo/terms/social-data-provider.php
  src/editors/framework/seo/terms/title-data-provider.php
  src/editors/framework/seo/title-data-provider-interface.php
  tests/Unit/Admin/Formatter/Post_Metabox_Formatter_Test.php
  tests/Unit/Admin/Formatter/Term_Metabox_Formatter_Test.php
  tests/Unit/Admin/User_Profile_Test.php
  tests/Unit/Editors/Domain/Seo/Description_Test.php
  tests/Unit/Editors/Domain/Seo/Keywords_Test.php
  tests/Unit/Editors/Domain/Seo/Social_Test.php
  tests/Unit/Editors/Domain/Seo/Title_Test.php
Labels: changelog: non-user-facing

#21450 AI: Minor: Lock icon missing on AI assessment button in free version #1622
  admin/class-admin-asset-manager.php
  admin/metabox/class-metabox.php
  composer.json
  css/src/ai-fix-assessments.css
  packages/components/src/AIFixesButton.js
  packages/components/tests/__snapshots__/IconAIFixesButtonTest.js.snap
  packages/js/images/lock-closed.svg
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
Labels: innovation, UI change

#21452 Update copies to cover the new AI features in the card and the upsell
  packages/js/src/settings/routes/site-features.js
  packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js
  packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap
Labels: changelog: non-user-facing

#21438 21404 when indexable creation is disabled cleanups are being scheduled upon post creation
  composer.json
  src/integrations/admin/activation-cleanup-integration.php
  src/integrations/cleanup-integration.php
  src/integrations/watchers/indexable-attachment-watcher.php
  src/integrations/watchers/indexable-author-archive-watcher.php
  src/integrations/watchers/indexable-post-type-change-watcher.php
  src/integrations/watchers/indexable-post-watcher.php
  src/integrations/watchers/indexable-taxonomy-change-watcher.php
  tests/Unit/Integrations/Admin/Activation_Cleanup_Integration_Test.php
  tests/Unit/Integrations/Cleanup_Integration_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Attachment_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Post_Type_Change_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Post_Watcher_Test.php
  tests/Unit/Integrations/Watchers/Indexable_Taxonomy_Change_Watcher_Test.php
Labels: changelog: enhancement

#21454 Make Yoast AI non-translatable in feature card
  packages/js/src/settings/routes/site-features.js
Labels: changelog: non-user-facing

#21442 Add early return in the hierachy creation to make sure we don't run a useless query.
  composer.json
  src/builders/indexable-hierarchy-builder.php
  tests/Unit/Builders/Indexable_Hierarchy_Builder_Test.php
Labels: changelog: enhancement
