Repository Yoast/wordpress-seo, pull requests merged in 2025-10, with the labels that each got.

#22611 Rename new submenu item for redirects
  src/integrations/admin/redirections-tools-page.php
Labels: changelog: non-user-facing, required-for-rc

#22614 Merge `feature/yoast-content-blocks` to `trunk`
  admin/class-expose-shortlinks.php
  css/src/metabox.css
  packages/analysis-report/tests/__snapshots__/SiteSEOReportTest.js.snap
  packages/components/src/Collapsible.js
  packages/components/src/SectionTitle.js
  packages/components/tests/SectionTitleTest.js
  packages/components/tests/__snapshots__/SectionTitleTest.js.snap
  packages/js/src/components/SidebarCollapsible.js
  packages/js/src/components/contentBlocks/AddBlockButton.js
  packages/js/src/components/contentBlocks/BenefitItems.js
  packages/js/src/components/contentBlocks/ContentBlock.js
  packages/js/src/components/contentBlocks/ContentBlocks.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/modals/ContentBlocksUpsell.js
  packages/js/src/components/modals/UpsellModal.js
  packages/js/src/externals/components.js
  packages/js/tests/components/__snapshots__/SidebarCollapsibleTest.js.snap
  packages/js/tests/components/contentBlocks/AddBlockButton.test.js
  packages/js/tests/components/contentBlocks/BenefitItems.test.js
  packages/js/tests/components/contentBlocks/ContentBlock.test.js
  packages/js/tests/components/contentBlocks/ContentBlocks.test.js
  packages/js/tests/components/modals/ContentBlocksUpsell.test.js
Labels: changelog: enhancement

#22608 Add notification for unused SEO title and description features
  inc/options/class-wpseo-option-wpseo.php
  src/alerts/application/default-seo-data/default-seo-data-alert.php
  src/alerts/infrastructure/default-seo-data/default-seo-data-collector.php
  src/alerts/user-interface/default-seo-data/default-seo-data-cron-callback-integration.php
  src/alerts/user-interface/default-seo-data/default-seo-data-cron-scheduler.php
  src/alerts/user-interface/default-seo-data/default-seo-data-watcher.php
  src/helpers/indexable-helper.php
Labels: changelog: non-user-facing

#22612 Change helpscout beacon behavior
  composer.json
  packages/js/src/support/app.js
  src/integrations/admin/helpscout-beacon.php
  src/integrations/support-integration.php
  tests/Unit/Integrations/Support_Integration_Test.php
  tests/Unit/Main_Test.php
Labels: changelog: other

#22620 Open links for the AI generate feature in new tabs
  src/alerts/application/default-seo-data/default-seo-data-alert.php
Labels: changelog: non-user-facing, required-for-rc

#22624 Fix/copy for default seo data alerts
  src/alerts/application/default-seo-data/default-seo-data-alert.php
Labels: changelog: non-user-facing

#22627 Redesign the installation success page
  admin/class-admin-asset-manager.php
  css/src/installation-success.css
  packages/js/src/installation-success.js
  packages/js/tests/InstallationSuccessPage.test.js
  packages/js/tests/__snapshots__/InstallationSuccessPage.test.js.snap
  src/integrations/admin/installation-success-integration.php
  tests/Unit/Integrations/Admin/Installation_Success_Integration_Test.php
Labels: changelog: non-user-facing, fix-before-release
