Repository Yoast/wordpress-seo, pull requests merged in 2025-03, with the labels that each got.

#22080 Allow going back and forth with the setup widget.
  packages/js/src/dashboard/components/dashboard.js
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/services/data-provider.js
  packages/js/src/dashboard/services/widget-factory.js
  packages/js/src/dashboard/widgets/site-kit-setup-widget.js
  packages/js/src/general/initialize.js
  packages/js/src/integrations-page/recommended-integrations.js
  packages/js/src/integrations-page/site-kit-integration.js
  packages/js/tests/dashboard/__mocks__/data-provider.js
  packages/js/tests/dashboard/scores/components/scores.test.js
  packages/js/tests/dashboard/services/widget-factory.test.js
  packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js
  packages/js/tests/integrations-page/SiteKitIntegration.test.js
Labels: changelog: non-user-facing

#22072 fix error handling and capabilities for consent
  packages/js/src/dashboard/widgets/top-queries-widget.js
  packages/js/tests/dashboard/widgets/top-pages-widget.test.js
  packages/js/tests/dashboard/widgets/top-queries-widget.test.js
  src/dashboard/user-interface/configuration/site-kit-configuration-dismissal-route.php
  src/dashboard/user-interface/configuration/site-kit-consent-management-route.php
  tests/Unit/Dashboard/User_Interface/Configuration/Abstract_Site_Kit_Configuration_Permanent_Dismissal_Route_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Abstract_Site_Kit_Consent_Management_Route_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Check_Capabilities_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Check_Capabilities_Test.php
Labels: changelog: non-user-facing

#22073 Add Organic Sessions widget
  packages/js/src/dashboard/components/info-tooltip.js
  packages/js/src/dashboard/components/no-data-paragraph.js
  packages/js/src/dashboard/components/trend.js
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/services/data-formatter.js
  packages/js/src/dashboard/services/data-provider.js
  packages/js/src/dashboard/services/remote-data-provider.js
  packages/js/src/dashboard/services/widget-factory.js
  packages/js/src/dashboard/transformers/difference.js
  packages/js/src/dashboard/widgets/organic-sessions-widget.js
  packages/js/src/dashboard/widgets/organic-sessions/compare.js
  packages/js/src/dashboard/widgets/organic-sessions/daily.js
  packages/js/src/dashboard/widgets/top-pages-widget.js
  packages/js/src/dashboard/widgets/top-queries-widget.js
  packages/js/src/general/initialize.js
  packages/js/tests/dashboard/__mocks__/data-provider.js
  packages/js/tests/dashboard/components/no-data-paragraph.test.js
  packages/js/tests/dashboard/components/trend.test.js
  packages/js/tests/dashboard/services/data-formatter.test.js
  packages/js/tests/dashboard/services/widget-factory.test.js
  packages/js/tests/dashboard/transformers/difference.test.js
  packages/js/tests/dashboard/widgets/organic-sessions-widget.test.js
  packages/js/tests/dashboard/widgets/organic-sessions/compare.test.js
  packages/js/tests/dashboard/widgets/organic-sessions/daily.test.js
  packages/js/tests/setupTests.js
  src/dashboard/infrastructure/integrations/site-kit.php
Labels: changelog: non-user-facing

#22084 Register more/missing chart plugins
  packages/js/src/dashboard/widgets/organic-sessions/daily.js
Labels: changelog: non-user-facing

#22081 Deprecate eslint-config package in favor of Yoast/eslint-config
  .github/workflows/deprecation-check.yml
  eslint.config.mjs
  package.json
  packages/analysis-report/eslint.config.mjs
  packages/analysis-report/package.json
  packages/browserslist-config/eslint.config.mjs
  packages/browserslist-config/package.json
  packages/components/eslint.config.mjs
  packages/components/package.json
  packages/eslint/CHANGELOG.md
  packages/eslint/README.md
  packages/eslint/package.json
  packages/feature-flag/eslint.config.mjs
  packages/feature-flag/package.json
  packages/helpers/eslint.config.mjs
  packages/helpers/package.json
  packages/js/eslint.config.mjs
  packages/js/package.json
  packages/related-keyphrase-suggestions/eslint.config.mjs
  packages/related-keyphrase-suggestions/package.json
  packages/replacement-variable-editor/eslint.config.mjs
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/eslint.config.mjs
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/eslint.config.mjs
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/eslint.config.mjs
  packages/social-metadata-previews/package.json
  packages/ui-library/eslint.config.mjs
  packages/ui-library/package.json
  packages/yoastseo/eslint.config.mjs
  packages/yoastseo/package.json
  yarn.lock
Labels: changelog: non-user-facing

#22089 Release of yoastseo and analysis-report
  package.json
  packages/analysis-report/CHANGELOG.MD
  packages/analysis-report/package.json
  packages/babel-preset/changelog.md
  packages/babel-preset/package.json
  packages/browserslist-config/CHANGELOG.md
  packages/browserslist-config/package.json
  packages/components/CHANGELOG.MD
  packages/components/package.json
  packages/feature-flag/CHANGELOG.md
  packages/feature-flag/package.json
  packages/helpers/CHANGELOG.md
  packages/helpers/package.json
  packages/js/package.json
  packages/related-keyphrase-suggestions/package.json
  packages/replacement-variable-editor/package.json
  packages/search-metadata-previews/package.json
  packages/social-metadata-forms/package.json
  packages/social-metadata-previews/package.json
  packages/style-guide/package.json
  packages/ui-library/package.json
  packages/yoastseo/CHANGELOG.md
  packages/yoastseo/package.json
  yarn.lock
Labels: changelog: non-user-facing

#22090 Use Authentication class from Site Kit to detect if it's set up
  src/dashboard/infrastructure/integrations/site-kit.php
Labels: changelog: non-user-facing

#22083 Adds unit tests for the site kit integration endpoints
  src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Abstract_Time_Based_SEO_Metrics_Route_Test.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Check_Capabilities_Test.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Constructor_Test.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Conditionals_Test.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Metrics_Test.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Register_Routes_Test.php
Labels: changelog: non-user-facing

#22086 Inclusive language: Add 'pregnant women' to potentially non-inclusive phrases
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/configuration/genderAssessmentsSpec.js
  packages/yoastseo/src/scoring/assessments/inclusiveLanguage/configuration/genderAssessments.js
Labels: changelog: enhancement, Shopify

#22092 Unit tests for the score group link collector.
  src/dashboard/infrastructure/score-groups/score-group-link-collector.php
  tests/Unit/Dashboard/Infrastructure/Score_Groups/Get_View_Link_Score_Group_Link_Collector_Test.php
Labels: changelog: non-user-facing

#22093 475 site kit setup widget dont show steps to the right of current step as completed and update copy
  packages/js/images/yoast-connect-google-site-kit-success.svg
  packages/js/src/dashboard/widgets/site-kit-setup-widget.js
Labels: changelog: non-user-facing

#22101 479 add unit test for endpoint container classes
  tests/Unit/Dashboard/Infrastructure/Endpoints/Readability_Scores_Endpoint_Test.php
  tests/Unit/Dashboard/Infrastructure/Endpoints/SEO_Scores_Endpoint_Test.php
  tests/Unit/Dashboard/Infrastructure/Endpoints/Site_Kit_Configuration_Dismissal_Endpoint_Test.php
  tests/Unit/Dashboard/Infrastructure/Endpoints/Site_Kit_Consent_Management_Endpoint_Test.php
  tests/Unit/Dashboard/Infrastructure/Endpoints/Time_Based_SEO_Metrics_Endpoint_Test.php
Labels: changelog: non-user-facing

#22100 448 not show ai modal on admin pages
  packages/js/src/introductions/initialize.js
Labels: UI change, changelog: other

#22091 469 site kit set up add alerts for user with no install plugin capabilities or dashboard viewing rights
  packages/js/src/dashboard/components/dashboard.js
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/services/data-provider.js
  packages/js/src/dashboard/services/widget-factory.js
  packages/js/src/dashboard/widgets/site-kit-setup-widget.js
  packages/js/src/general/initialize.js
  packages/js/src/integrations-page/recommended-integrations.js
  packages/js/src/integrations-page/site-kit-integration.js
  packages/js/tests/dashboard/__mocks__/data-provider.js
  packages/js/tests/dashboard/services/widget-factory.test.js
  packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js
  packages/js/tests/integrations-page/SiteKitIntegration.test.js
  src/dashboard/infrastructure/integrations/site-kit.php
  tests/Unit/Integrations/Admin/Integrations_Page_Integration_Test.php
Labels: changelog: non-user-facing

#22098 Add integration tests for the search console adapter
  composer.json
  composer.lock
  src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Abstract_Search_Console_Adapter_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Construct.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Failed_Request_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Comparison_Data_Unexpected_Response_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Failed_Request_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Get_Data_Unexpected_Response_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Validate_Comparison_Response_Test.php
  tests/WP/Dashboard/Infrastructure/Search_Console/Search_Console_Adapter_Validate_Response_Test.php
  tests/WP/Doubles/Dashboard/Infrastructure/Search_Console/Search_Console_Module_Mock.php
  tests/WP/TestCase.php
Labels: changelog: non-user-facing

#22075 Add Organic Sessions Compare widget
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/services/comparison-metrics-data-formatter.js
  packages/js/src/dashboard/services/data-formatter-interface.js
  packages/js/src/dashboard/services/data-formatter.js
  packages/js/src/dashboard/services/plain-metrics-data-formatter.js
  packages/js/src/dashboard/services/widget-factory.js
  packages/js/src/dashboard/widgets/organic-sessions-widget.js
  packages/js/src/dashboard/widgets/search-ranking-compare-widget.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-metric-divider.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-metric.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
  packages/js/src/dashboard/widgets/top-pages-widget.js
  packages/js/src/dashboard/widgets/top-queries-widget.js
  packages/js/src/general/initialize.js
  packages/js/tests/dashboard/__mocks__/fake-data-formatter.js
  packages/js/tests/dashboard/services/comparison-metrics-data-formatter.test.js
  packages/js/tests/dashboard/services/data-formatter-interface-test.js
  packages/js/tests/dashboard/services/plain-metrics-data-formatter.test.js
  packages/js/tests/dashboard/services/widget-factory.test.js
  packages/js/tests/dashboard/widgets/organic-sessions-widget.test.js
  packages/js/tests/dashboard/widgets/top-pages-widget.test.js
  packages/js/tests/dashboard/widgets/top-queries-widget.test.js
Labels: changelog: non-user-facing

#22103 Finalizes widget tooltips
  packages/js/src/dashboard/components/info-tooltip.js
  packages/js/src/dashboard/widgets/organic-sessions-widget.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-metric.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
  packages/js/src/dashboard/widgets/top-pages-widget.js
  packages/js/src/dashboard/widgets/top-queries-widget.js
  packages/js/src/dashboard/widgets/widget.js
  packages/js/tests/dashboard/widgets/organic-sessions-widget.test.js
Labels: changelog: non-user-facing

#22110 Add error boundary on Widget level
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/services/use-remote-data.js
  packages/js/src/dashboard/widgets/organic-sessions-widget.js
  packages/js/src/dashboard/widgets/organic-sessions/compare.js
  packages/js/src/dashboard/widgets/organic-sessions/daily.js
  packages/js/src/dashboard/widgets/score-widget.js
  packages/js/src/dashboard/widgets/search-ranking-compare-widget.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
  packages/js/src/dashboard/widgets/search-ranking-compare/use-search-ranking-compare.js
  packages/js/src/dashboard/widgets/top-pages-widget.js
  packages/js/src/dashboard/widgets/top-queries-widget.js
  packages/js/src/dashboard/widgets/widget.js
  packages/js/src/general/initialize.js
  packages/js/tests/dashboard/__mocks__/data-provider.js
Labels: changelog: non-user-facing

#21974 Converts the sentence beginnings assessment to use the HTML parser
  packages/js/src/decorator/helpers/positionBasedAnnotationHelper.js
  packages/yoastseo/spec/fullTextTests/testTexts/sk/slovakPaper.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/getSentencesFromTreeSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/sentencesLengthSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getSentenceBeginningsSpec.js
  packages/yoastseo/spec/parse/language/LanguageProcessorSpec.js
  packages/yoastseo/spec/parse/traverse/getParentNodeSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceBeginningsAssessmentSpec.js
  packages/yoastseo/src/helpers/htmlEntities.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/getSentencesFromTree.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/sentencesLength.js
  packages/yoastseo/src/languageProcessing/helpers/word/getAllWordsFromTree.js
  packages/yoastseo/src/languageProcessing/researches/countSentencesFromText.js
  packages/yoastseo/src/languageProcessing/researches/findKeywordInFirstParagraph.js
  packages/yoastseo/src/languageProcessing/researches/getSentenceBeginnings.js
  packages/yoastseo/src/languageProcessing/researches/keywordCount.js
  packages/yoastseo/src/parse/build/private/filterTree.js
  packages/yoastseo/src/parse/structure/Heading.js
  packages/yoastseo/src/parse/structure/Node.js
  packages/yoastseo/src/parse/structure/Paragraph.js
  packages/yoastseo/src/parse/structure/Sentence.js
  packages/yoastseo/src/parse/structure/Token.js
  packages/yoastseo/src/parse/traverse/findAllInTree.js
  packages/yoastseo/src/parse/traverse/getParentNode.js
  packages/yoastseo/src/parse/traverse/index.js
  packages/yoastseo/src/parse/traverse/innerText.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceBeginningsAssessment.js
  packages/yoastseo/src/values/Paper.js
Labels: innovation, changelog: enhancement, Shopify

#22112 Remove Flesch reading ease from the assessments documentation
  packages/yoastseo/src/scoring/assessments/SCORING READABILITY.md
Labels: changelog: non-user-facing

#22085 Unit tests for the site kit configuration.
  src/dashboard/infrastructure/integrations/site-kit.php
  tests/Unit/Dashboard/Infrastructure/Configuration/Site_Kit_Consent_Repository_Fake.php
  tests/Unit/Dashboard/Infrastructure/Integrations/Abstract_Site_Kit_Test.php
  tests/Unit/Dashboard/Infrastructure/Integrations/Is_Site_Kit_Enabled_Test.php
  tests/Unit/Dashboard/Infrastructure/Integrations/Is_Site_Kit_Ga_Connected_Test.php
  tests/Unit/Dashboard/Infrastructure/Integrations/Site_Kit_To_Array_Test.php
  tests/WP/Dashboard/Infrastructure/Integrations/Is_Site_Kit_On_Boarded_Test.php
  tests/WP/Dashboard/Infrastructure/Integrations/Is_Site_Kit_On_Boarded_Without_Site_Kit_Test.php
  tests/patchwork.json
Labels: changelog: non-user-facing

#22114 Dashboard: fix responsiveness
  packages/js/images/yoast-connect-google-site-kit-success.svg
  packages/js/src/academy/app.js
  packages/js/src/dashboard/components/dashboard.js
  packages/js/src/dashboard/components/learn-more-link.js
  packages/js/src/dashboard/scores/components/content-status-description.js
  packages/js/src/dashboard/widgets/score-widget.js
  packages/js/src/dashboard/widgets/site-kit-setup-widget.js
  packages/js/src/general/app.js
  packages/js/src/installation-success.js
  packages/js/src/settings/app.js
  packages/js/src/shared-admin/components/site-kit-consent-modal.js
  packages/js/src/support/app.js
  packages/js/tests/__snapshots__/InstallationSuccessPage.test.js.snap
  packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js
  packages/tailwindcss-preset/index.js
Labels: changelog: non-user-facing

#22119 Docs: fix incorrect type specificity
  composer.json
  tests/Unit/Integrations/Watchers/Search_Engines_Discouraged_Watcher_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22117 Update copy in search ranking compare
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
Labels: changelog: non-user-facing

#22121 Composer: normalize the file
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#22113 Add two CTB button codes
  packages/js/src/shared-admin/components/ai-fix-assessments-upsell.js
  packages/js/src/shared-admin/components/ai-generate-titles-and-descriptions-upsell.js
  packages/js/tests/shared-admin/components/__snapshots__/ai-fix-assessments-upsell.test.js.snap
  packages/js/tests/shared-admin/components/__snapshots__/ai-generate-titles-and-descriptions-upsell.test.js.snap
Labels: changelog: non-user-facing

#22122 Composer: update to YoastCS 3.2.0
  composer.json
  composer.lock
Labels: yoast cs/qa, changelog: non-user-facing

#22123 Revert "PHPCS: minor ruleset tweak"
  .phpcs.xml.dist
Labels: yoast cs/qa, changelog: non-user-facing

#21964 Fixes issue #31963: Added space at end of the input fields
  admin/class-bulk-editor-list-table.php
  admin/class-premium-popup.php
  admin/views/tabs/tool/import-seo.php
  admin/views/user-profile.php
Labels: community-patch, changelog: other

#22126 Tests: fix variety of broken covers tags
  tests/Unit/Builders/Indexable_Builder/Build_For_System_Page_Test.php
  tests/Unit/Builders/Indexable_Builder/Build_Test.php
  tests/Unit/Builders/Indexable_Builder/Maybe_Build_Author_Indexable_Test.php
  tests/Unit/Builders/Indexable_Builder/Save_Indexable_Test.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Set_Site_Kit_Permanent_Dismissal_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Check_Capabilities_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Constructor_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Get_Conditionals_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Configuration_Permanent_Dismissal_Route_Register_Routes_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Get_Conditionals_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Register_Routes_Test.php
  tests/Unit/Dashboard/User_Interface/Time_Based_SEO_Metrics/Time_Based_SEO_Metrics_Route_Get_Conditionals_Test.php
  tests/Unit/Editors/Domain/Analysis_Features/Analysis_Features_List_Test.php
  tests/Unit/Images/Application/Image_Content_Extractor_Test.php
  tests/Unit/User_Meta/Infrastructure/Cleanup_Repository_Test.php
  tests/WP/Formatter/Post_Metabox_Formatter_Test.php
  tests/WP/Formatter/Term_Metabox_Formatter_Test.php
  tests/WP/Images/Application/Image_Content_Extractor_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22128 CS/QA: no need for `is_null()`
  admin/class-yoast-form.php
  admin/class-yoast-notification-center.php
  admin/class-yoast-plugin-conflict.php
  admin/import/plugins/class-import-squirrly.php
  admin/taxonomy/class-taxonomy.php
  inc/class-addon-manager.php
  inc/class-wpseo-admin-bar-menu.php
  inc/class-wpseo-custom-fields.php
  inc/class-wpseo-custom-taxonomies.php
  inc/class-wpseo-replace-vars.php
  inc/sitemaps/class-sitemaps-cache-validator.php
  inc/sitemaps/class-sitemaps.php
  lib/orm.php
  src/actions/configuration/first-time-configuration-action.php
  src/actions/indexing/abstract-indexing-action.php
  src/actions/wincher/wincher-account-action.php
  src/actions/wincher/wincher-keyphrases-action.php
  src/builders/indexable-builder.php
  src/config/badge-group-names.php
  src/content-type-visibility/application/content-type-visibility-watcher-actions.php
  src/context/meta-tags-context.php
  src/deprecated/frontend/breadcrumbs.php
  src/deprecated/frontend/frontend.php
  src/generators/schema/person.php
  src/helpers/current-page-helper.php
  src/helpers/indexable-to-postmeta-helper.php
  src/helpers/schema/article-helper.php
  src/helpers/url-helper.php
  src/helpers/wpdb-helper.php
  src/integrations/front-end-integration.php
  src/integrations/watchers/indexable-ancestor-watcher.php
  src/presentations/indexable-term-archive-presentation.php
  src/presenters/admin/notice-presenter.php
  src/surfaces/meta-surface.php
  src/values/oauth/oauth-token.php
  tests/Unit/Helpers/Short_Link_Helper_Test.php
  tests/Unit/Helpers/Url_Helper_Test.php
  tests/WP/Doubles/Admin/Meta_Columns_Double.php
Labels: yoast cs/qa, changelog: non-user-facing

#22129 Docs: remove redundant property names in `@var` tags
  src/dashboard/application/configuration/dashboard-configuration.php
  src/dashboard/domain/endpoint/endpoint-list.php
  src/dashboard/infrastructure/score-results/readability-score-results/cached-readability-score-results-collector.php
  src/dashboard/infrastructure/score-results/seo-score-results/cached-seo-score-results-collector.php
  src/editors/application/integrations/integration-information-repository.php
  src/editors/application/seo/post-seo-information-repository.php
  src/editors/application/seo/term-seo-information-repository.php
  src/editors/application/site/website-information-repository.php
  src/editors/domain/seo/description.php
  src/editors/domain/seo/keyphrase.php
  src/editors/domain/seo/social.php
  src/editors/domain/seo/title.php
  src/editors/framework/integrations/multilingual.php
  src/editors/framework/integrations/woocommerce.php
  src/editors/framework/seo/posts/description-data-provider.php
  src/editors/framework/seo/posts/keyphrase-data-provider.php
  src/editors/framework/seo/posts/social-data-provider.php
  src/editors/framework/seo/posts/title-data-provider.php
  src/editors/framework/site/base-site-information.php
  src/editors/framework/site/post-site-information.php
  src/general/user-interface/general-page-integration.php
  src/user-meta/application/additional-contactmethods-collector.php
  src/user-meta/application/cleanup-service.php
  src/user-meta/application/custom-meta-collector.php
  src/user-meta/user-interface/additional-contactmethods-integration.php
  src/user-meta/user-interface/cleanup-integration.php
  src/user-meta/user-interface/custom-meta-integration.php
  tests/Unit/Editors/Framework/Site/Post_Site_Information_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22135 Tests: various removals
  composer.json
  tests/Unit/Admin/User_Profile_Test.php
  tests/WP/Inc/Utils_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22136 CS: various minor whitespace fixes
  admin/class-my-yoast-proxy.php
  admin/services/class-file-size.php
  config/composer/actions.php
  inc/class-my-yoast-api-request.php
  inc/options/class-wpseo-option.php
  lib/abstract-main.php
  src/actions/indexing/indexable-post-type-archive-indexation-action.php
  src/builders/indexable-builder.php
  src/dashboard/infrastructure/taxonomies/taxonomies-collector.php
  src/editors/framework/readability-analysis.php
  src/editors/framework/seo/terms/description-data-provider.php
  src/editors/framework/seo/terms/title-data-provider.php
  src/integrations/admin/unsupported-php-version-notice.php
  src/presenters/url-list-presenter.php
  tests/Unit/Builders/Indexable_Link_Builder/Build_Test.php
  tests/Unit/Images/Application/Image_Content_Extractor_Test.php
  tests/WP/Editors/Framework/Site/Post_Site_Information_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22137 CS/QA: prefer exit() over die()
  admin/ajax.php
  admin/class-yoast-notification-center.php
  admin/views/tool-file-editor.php
  inc/sitemaps/class-sitemaps.php
Labels: yoast cs/qa, changelog: non-user-facing

#22138 CS/QA: no unnecessary multi-line function signatures
  src/actions/importing/aioseo/aioseo-cleanup-action.php
  src/actions/indexing/indexing-prepare-action.php
  src/builders/indexable-date-archive-builder.php
  src/builders/indexable-link-builder.php
  src/builders/indexable-system-page-builder.php
  src/config/semrush-client.php
  src/config/wincher-client.php
  src/dashboard/application/score-groups/seo-score-groups/seo-score-groups-repository.php
  src/dashboard/application/score-results/abstract-score-results-repository.php
  src/dashboard/application/score-results/current-scores-repository.php
  src/dashboard/infrastructure/content-types/content-types-collector.php
  src/dashboard/infrastructure/taxonomies/taxonomies-collector.php
  src/dashboard/user-interface/scores/abstract-scores-route.php
  src/dashboard/user-interface/scores/readability-scores-route.php
  src/dashboard/user-interface/scores/seo-scores-route.php
  src/deprecated/src/introductions/application/ai-generate-titles-and-descriptions-introduction-upsell.php
  src/generators/schema-generator.php
  src/helpers/aioseo-helper.php
  src/helpers/author-archive-helper.php
  src/helpers/current-page-helper.php
  src/helpers/first-time-configuration-notice-helper.php
  src/helpers/import-cursor-helper.php
  src/helpers/indexing-helper.php
  src/helpers/pagination-helper.php
  src/helpers/post-helper.php
  src/helpers/robots-helper.php
  src/helpers/short-link-helper.php
  src/integrations/admin/activation-cleanup-integration.php
  src/integrations/admin/cron-integration.php
  src/integrations/admin/installation-success-integration.php
  src/integrations/blocks/structured-data-blocks.php
  src/integrations/front-end/feed-improvements.php
  src/presentations/indexable-term-archive-presentation.php
  src/routes/first-time-configuration-route.php
  src/routes/integrations-route.php
  src/routes/workouts-route.php
  src/services/health-check/default-tagline-check.php
  src/services/health-check/links-table-check.php
  src/services/health-check/links-table-runner.php
  src/services/health-check/page-comments-check.php
  src/services/health-check/postname-permalink-check.php
  src/services/importing/aioseo/aioseo-robots-provider-service.php
  src/services/importing/aioseo/aioseo-robots-transformer-service.php
  src/services/importing/aioseo/aioseo-social-images-provider-service.php
  src/surfaces/values/meta.php
  src/user-profiles-additions/user-interface/user-profiles-additions-ui.php
  tests/Unit/Editors/Framework/Integrations/News_SEO_Test.php
  tests/Unit/Editors/Framework/Integrations/Semrush_Test.php
  tests/Unit/Editors/Framework/Integrations/WooCommerce_SEO_Test.php
  tests/Unit/Editors/Framework/Integrations/WooCommerce_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22139 CS/QA: remove unused import use statements
  src/dashboard/infrastructure/taxonomies/taxonomy-validator.php
  tests/Unit/Dashboard/User_Interface/Configuration/Site_Kit_Consent_Management_Route_Constructor_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#22141 Docs: fix unconventional tag order
  admin/class-plugin-availability.php
  admin/class-yoast-form.php
  admin/class-yoast-input-validation.php
  admin/import/plugins/class-import-aioseo-v4.php
  admin/menu/class-replacevar-editor.php
  config/composer/actions.php
  src/actions/importing/aioseo/abstract-aioseo-settings-importing-action.php
  src/actions/importing/aioseo/aioseo-taxonomy-settings-importing-action.php
  src/dashboard/application/search-rankings/top-page-repository.php
  src/dashboard/application/search-rankings/top-query-repository.php
  src/dashboard/infrastructure/endpoints/readability-scores-endpoint.php
  src/dashboard/infrastructure/endpoints/seo-scores-endpoint.php
  src/dashboard/infrastructure/endpoints/site-kit-configuration-dismissal-endpoint.php
  src/dashboard/infrastructure/endpoints/site-kit-consent-management-endpoint.php
  src/dashboard/infrastructure/score-results/readability-score-results/cached-readability-score-results-collector.php
  src/dashboard/infrastructure/score-results/seo-score-results/cached-seo-score-results-collector.php
  src/dashboard/user-interface/time-based-seo-metrics/time-based-seo-metrics-route.php
  src/deprecated/admin/class-customizer.php
  src/deprecated/src/helpers/request-helper.php
  src/deprecated/src/integrations/admin/disable-concatenate-scripts-integration.php
  src/editors/framework/site/base-site-information.php
  src/helpers/notification-helper.php
  src/integrations/third-party/wincher-publish.php
  src/services/importing/aioseo/aioseo-replacevar-service.php
Labels: yoast cs/qa, changelog: non-user-facing

#22142 Docs: fix up inline `@var` docblocks
  admin/metabox/class-metabox.php
  admin/taxonomy/class-taxonomy.php
  admin/views/tabs/dashboard/dashboard.php
  inc/class-wpseo-meta.php
  inc/class-wpseo-utils.php
  lib/orm.php
  src/initializers/migration-runner.php
  src/integrations/third-party/elementor.php
  src/integrations/watchers/indexable-post-watcher.php
  src/surfaces/values/meta.php
  tests/Unit/Repositories/Indexable_Repository_Test.php
Labels: yoast cs/qa, changelog: non-user-facing

#21958 Improve function words list for Farsi
  packages/yoastseo/src/languageProcessing/languages/fa/config/functionWords.js
Labels: changelog: enhancement, Shopify

#22134 Dashboard: improve search ranking compare widget responsiveness
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-metric-divider.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-metric.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
Labels: changelog: non-user-facing

#22145 Dashboard: check search console view data permissions before returning the component
  .github/workflows/finish-coveralls.yml
  packages/js/src/dashboard/services/widget-factory.js
  packages/js/tests/dashboard/services/widget-factory.test.js
  phpunit-wp.xml.dist
Labels: changelog: non-user-facing

#22106 get editor data image doesn't include image from the content
  packages/js/src/elementor/containers/FacebookEditor.js
  packages/js/src/elementor/containers/SnippetEditor.js
  packages/js/src/elementor/containers/TwitterEditor.js
  packages/js/src/elementor/initializers/editor-store.js
  packages/js/src/elementor/initializers/editor-watcher.js
  packages/js/src/redux/reducers/snippetEditor.js
Labels: changelog: bugfix

#22127 4580 fix ai modal when using astra plugins
  css/src/tailwind.css
Labels: changelog: bugfix

#22144 487 show notification if site kit version is not supported
  packages/js/src/dashboard/index.js
  packages/js/src/dashboard/services/widget-factory.js
  packages/js/src/dashboard/widgets/site-kit-setup-widget.js
  packages/js/src/integrations-page/recommended-integrations.js
  packages/js/src/integrations-page/site-kit-integration.js
  packages/js/tests/dashboard/__mocks__/data-provider.js
  packages/js/tests/dashboard/widgets/site-kit-setup-widget.test.js
  packages/js/tests/integrations-page/SiteKitIntegration.test.js
  src/dashboard/infrastructure/integrations/site-kit.php
  tests/Unit/Dashboard/Infrastructure/Integrations/Site_Kit_To_Array_Test.php
Labels: changelog: non-user-facing

#22148 fix google ai name in crawl optimization and search
  packages/js/src/settings/helpers/search.js
  packages/js/src/settings/routes/crawl-optimization.js
Labels: changelog: other

#22149 Dashboard: add tests for the Search Ranking Compare widget
  packages/js/src/dashboard/components/trend.js
  packages/js/src/dashboard/widgets/search-ranking-compare/search-ranking-compare-widget-content.js
  packages/js/tests/dashboard/widgets/search-ranking-compare-widget.test.js
Labels: changelog: non-user-facing

#22150 refactor and added tests for widget factory
  packages/js/tests/dashboard/services/widget-factory.test.js
Labels: changelog: non-user-facing
