Repository Yoast/wordpress-seo, pull requests merged in 2025-01, with the labels that each got.

#21937 Check for product by slug
  packages/js/src/redux/reducers/editorContext.js
  packages/js/src/redux/selectors/editorContext.js
Labels: changelog: non-user-facing

#21942 GH Actions: add actionlint job
  .github/workflows/cs.yml
  .github/workflows/deploy.yml
Labels: yoast cs/qa, changelog: non-user-facing

#21943 GH Actions: ensure second PHP install run always uses latest PHP version
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: yoast cs/qa, changelog: non-user-facing

#21945 Rename feature flag
  src/conditionals/google-site-kit-feature-conditional.php
Labels: changelog: non-user-facing

#21940 395 outdated translations
  packages/js/src/components/WincherPerformanceReport.js
  src/integrations/admin/link-count-columns-integration.php
Labels: UI change, changelog: non-user-facing

#21866 Convert Sentence length and paragraph length to use HTML parser and enable AI button for both assessments
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.html
  packages/yoastseo/spec/fullTextTests/testTexts/el/greekPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/en/englishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/es/spanishPaperForPerformanceTest.js
  packages/yoastseo/spec/fullTextTests/testTexts/fa/farsiPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/fr/frenchPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/he/hebrewPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/ja/japanesePaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaper.js
  packages/yoastseo/spec/fullTextTests/testTexts/pl/polishPaperForPerformanceTest.js
  packages/yoastseo/spec/languageProcessing/helpers/html/matchParagraphsSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/sentence/sentencesLengthSpec.js
  packages/yoastseo/spec/languageProcessing/languages/ar/ResearcherSpec.js
  packages/yoastseo/spec/languageProcessing/researches/countSentencesFromTextSpec.js
  packages/yoastseo/spec/languageProcessing/researches/getParagraphLengthSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/ParagraphTooLongAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessments/readability/SentenceLengthInTextAssessmentSpec.js
  packages/yoastseo/spec/scoring/assessors/collectionPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/assessors/collectionPages/fullTextTests/testTexts/en/englishPaper3.js
  packages/yoastseo/spec/scoring/assessors/productPages/fullTextTests/testTexts/en/englishPaper1.js
  packages/yoastseo/spec/scoring/assessors/productPages/fullTextTests/testTexts/en/englishPaper2.js
  packages/yoastseo/spec/scoring/helpers/assessments/checkForTooLongSentencesSpec.js
  packages/yoastseo/src/languageProcessing/helpers/html/matchParagraphs.js
  packages/yoastseo/src/languageProcessing/helpers/sentence/sentencesLength.js
  packages/yoastseo/src/languageProcessing/helpers/word/getAllWordsFromTree.js
  packages/yoastseo/src/languageProcessing/researches/countSentencesFromText.js
  packages/yoastseo/src/languageProcessing/researches/getParagraphLength.js
  packages/yoastseo/src/scoring/assessments/readability/ParagraphTooLongAssessment.js
  packages/yoastseo/src/scoring/assessments/readability/SentenceLengthInTextAssessment.js
  packages/yoastseo/src/scoring/helpers/assessments/checkForTooLongSentences.js
Labels: innovation, changelog: enhancement, Shopify

#21952 Feature/plugin fixes
  packages/js/src/components/WincherPerformanceReport.js
  packages/js/src/redux/reducers/editorContext.js
  packages/js/src/redux/selectors/editorContext.js
  src/integrations/admin/link-count-columns-integration.php
Labels: changelog: non-user-facing

#21948 Remove cache around changing link
  packages/js/src/inline-links/inline.js
Labels: changelog: bugfix

#21912 Only show a modified time tag if it's later than the created time
  src/generators/schema/article.php
  src/generators/schema/webpage.php
  src/presentations/indexable-post-type-presentation.php
  tests/Unit/Generators/Schema_Generator_Test.php
Labels: changelog: bugfix

#21953 Updates the readability analysis when the client IDs of the blocks change
  packages/yoastseo/spec/worker/AnalysisWebWorkerSpec.js
  packages/yoastseo/src/worker/AnalysisWebWorker.js
Labels: innovation, changelog: non-user-facing

#21957 Fixes running researches that require a tree in the experimental content analysis API
  apps/content-analysis-api/routes/research.js
  packages/yoastseo/src/parse/language/LanguageProcessor.js
  packages/yoastseo/src/parse/language/index.js
Labels: changelog: non-user-facing

#21960 Correctly enable or disable the highlighting button
  packages/js/src/ai-assessment-fixes/components/ai-assessment-fixes-button.js
  packages/js/src/components/fills/MetaboxFill.js
  packages/js/src/components/fills/SidebarFill.js
  packages/js/src/components/fills/hooks/useToggleMarkerStatus.js
Labels: innovation, changelog: bugfix

#21970 Revert "Export inclusive language"
  .github/workflows/manual-run.yml
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigSpec.js
Labels: changelog: reverted

#21796 Extend exception list for German nouns with umlaut in plural
  packages/yoastseo/spec/languageProcessing/languages/de/helpers/internal/determineStemSpec.js
  packages/yoastseo/src/languageProcessing/languages/de/helpers/internal/determineStem.js
Labels: changelog: enhancement, Shopify

#21979 Updates the morphology data version number for German
  apps/content-analysis-api/helpers/get-researcher.js
  packages/yoastseo/spec/specHelpers/getMorphologyData.js
Labels: changelog: non-user-facing

#21976 refactor: remove duplicate/redundant condition
  inc/class-wpseo-replace-vars.php
Labels: community-patch, changelog: other

#21971 Allow transpiling all js files inside yoastseo/src and allow import with asterisk *
  packages/yoastseo/package.json
  packages/yoastseo/tsconfig.json
Labels: changelog: non-user-facing

#21965 First run at a setup
  src/dashboard/application/search-rankings/top-page-repository.php
  src/dashboard/application/search-rankings/top-query-repository.php
  src/dashboard/domain/data-provider/dashboard-repository-interface.php
  src/dashboard/domain/data-provider/data-container.php
  src/dashboard/domain/data-provider/data-interface.php
  src/dashboard/domain/data-provider/parameters.php
  src/dashboard/domain/search-rankings/search-data.php
  src/dashboard/infrastructure/endpoints/search-rankings/top-page-endpoint.php
  src/dashboard/infrastructure/endpoints/search-rankings/top-query-endpoint.php
  src/dashboard/infrastructure/search-console/search-console-parameters.php
  src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php
  src/dashboard/user-interface/search-rankings/abstract-ranking-route.php
  src/dashboard/user-interface/search-rankings/top-page-route.php
  src/dashboard/user-interface/search-rankings/top-query-route.php
Labels: changelog: non-user-facing

#21951 367 site kit tables UI
  packages/js/package.json
  packages/js/src/dashboard/components/most-popular-table.js
  packages/js/src/dashboard/components/table-widget.js
  packages/js/src/dashboard/index.js
  packages/ui-library/src/elements/table/docs/index.js
  packages/ui-library/src/elements/table/docs/table-row.md
  packages/ui-library/src/elements/table/docs/table-variant-minimal.md
  packages/ui-library/src/elements/table/index.js
  packages/ui-library/src/elements/table/stories.js
  packages/ui-library/src/elements/table/style.css
Labels: changelog: non-user-facing

#21962 Show alert when avif file is used in social preview
  packages/components/src/image-select/ImageSelect.js
  packages/js/src/components/social/FacebookWrapper.js
  packages/js/src/components/social/SocialForm.js
  packages/js/src/components/social/TwitterWrapper.js
  packages/js/src/components/social/useFallbackWarning.js
  packages/social-metadata-forms/src/SocialMetadataPreviewForm.js
  packages/social-metadata-previews/src/editor/SocialPreviewEditor.js
Labels: changelog: enhancement

#21995 Fixes processing of hyphens at start and end positions
  packages/yoastseo/spec/languageProcessing/helpers/sentence/sentencesLengthSpec.js
  packages/yoastseo/spec/languageProcessing/helpers/word/getAllWordsFromTreeSpec.js
  packages/yoastseo/src/languageProcessing/helpers/word/getAllWordsFromTree.js
Labels: changelog: bugfix, Shopify

#21991 Add SEO scores in top pages endpoint
  src/dashboard/application/score-groups/seo-score-groups/seo-score-groups-repository.php
  src/dashboard/application/search-rankings/top-page-repository.php
  src/dashboard/domain/data-provider/data-container.php
  src/dashboard/domain/search-console/failed-request-exception.php
  src/dashboard/domain/search-rankings/search-data.php
  src/dashboard/domain/search-rankings/top-page-data.php
  src/dashboard/infrastructure/indexables/top-page-indexable-collector.php
  src/dashboard/infrastructure/search-console/site-kit-search-console-adapter.php
  src/dashboard/user-interface/search-rankings/abstract-ranking-route.php
Labels: changelog: non-user-facing

#21984 Add the Site Kit consent modal
  packages/js/src/shared-admin/components/site-kit-consent-modal.js
  packages/ui-library/src/components/modal/index.js
  packages/ui-library/src/components/modal/stories.js
Labels: changelog: enhancement

#21988 561 create site kit permanent dismissal route
  inc/options/class-wpseo-option-wpseo.php
  src/dashboard/infrastructure/configuration/permanently-dismissed-site-kit-configuration-repository-interface.php
  src/dashboard/infrastructure/configuration/permanently-dismissed-site-kit-configuration-repository.php
  src/dashboard/infrastructure/endpoints/site-kit-configuration-dismissal-endpoint.php
  src/dashboard/user-interface/configuration/site-kit-configuration-dismissal-route.php
  tests/Unit/Dashboard/Infrastructure/Configuration/Abstract_Permanently_Dismissed_Site_Kit_Configuration_Repository_Test.php
  tests/Unit/Dashboard/Infrastructure/Configuration/Constructor_Test.php
  tests/Unit/Dashboard/Infrastructure/Configuration/Is_Site_Kit_Configuration_Dismissed_Test.php
  tests/Unit/Dashboard/Infrastructure/Configuration/Permanently_Dismissed_Site_Kit_Configuration_Repository_Fake.php
  tests/Unit/Dashboard/Infrastructure/Configuration/Set_Site_Kit_Configuration_Dismissal_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Abstract_Site_Kit_Configuration_Permanent_Dismissal_Route_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Check_Capabilities_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Constructor_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Get_Conditionals_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Register_Routes_Test.php
  tests/Unit/Dashboard/User_Interface/Configuration/Set_Site_Kit_Permanent_Dismissal_Test.php
  tests/WP/Dashboard/Application/Endpoints/Endpoints_Repository_Test.php
Labels: changelog: other

#21996 424 onionize the sitekit configuration checks
  packages/js/src/integrations-page/recommended-integrations.js
  src/dashboard/infrastructure/integrations/site-kit.php
  src/integrations/admin/integrations-page.php
  tests/Unit/Integrations/Admin/Integrations_Page_Integration_Test.php
Labels: changelog: non-user-facing

#21987 Export inclusive language csv contents
  .github/workflows/generate_csv.yml
  packages/yoastseo/package.json
  packages/yoastseo/spec/scoring/assessments/inclusiveLanguage/exportInclusiveLanguageConfigSpec.js
Labels: changelog: non-user-facing
